### ISSUE TITLE
Debugger in VS Code Jupyter notebooks fails with 'Error in inserting pydevd breaks'

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/debugpy#1000]
## Environment data

- debugpy version: 1.6.2 (run `import debugpy; print(debugpy.__version__)` if uncertain)
- OS and version: Linux Ubuntu
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.9
- Using VS Code or Visual Studio: VS Code

## Actual behavior

At times the debugger fails with the following message
`Error in inserting pydevd breaks

## Expected  behavior

XXX

## Steps to reproduce:
1. XXX

We run tests on CI for debugging Jupyter notebooks.
Please find attached notebook with all of the outputs and screenshots for each of the failing tests.
In the screenshots and the output you can see Pydevd throws errors.
[TestResultNotebook-raw-nonConda-3.9--ubuntu-latest (1).zip](https://github.com/microsoft/debugpy/files/9246118/TestResultNotebook-raw-nonConda-3.9--ubuntu-latest.1.zip)
![pydevd_breaks](https://user-images.githubusercontent.com/1948812/182486767-a632747c-a88d-4015-81b0-f1827a47ce3e.png)

**Comment by fabioz** [comment]
@DonJayamanne this was actually fixed a few days ago in: https://github.com/microsoft/debugpy/pull/996

And the custom support for IPython stepping (https://github.com/microsoft/debugpy/pull/998) was just merged (this should make it possible to use IPython with `justMyCode: false` -- note that it requires `"PYDEVD_IPYTHON_COMPATIBLE_DEBUGGING" = "1"` to be set in the environment prior to importing `debugpy` (I created https://github.com/microsoft/vscode-jupyter/issues/11033 to track that in in the jupyter side in VSCode).
