### ISSUE TITLE
Enable controlling shell expansion via "argsCanBeInterpretedByShell"

### ISSUE THREAD

**Issue by roblourens** [microsoft/debugpy#1001]
We now have the ability to let the user decide whether arguments passed to a debuggee in a terminal should be escaped for the shell. This is adopted in js-debug, https://github.com/microsoft/vscode-js-debug/issues/1335, also see https://github.com/microsoft/vscode/issues/149910, would love to see it adopted for python in August. In js-debug, the `args` property can be a string or an array of strings. If it's just a string, the args are not escaped. I can talk more about what it will take to  adopt this if needed.

**Comment by int19h** [comment]
Unless there are any specific reasons to not do so, I think we should follow the pattern established by JS, so that configs are consistent across languages as much as possible. Implementing this in debugpy should be straightforward.

**Comment by roblourens** [comment]
Thanks for getting to this so quickly!
