### ISSUE TITLE
New Line issue

### ISSUE THREAD

**Issue by theCrazyCode** [microsoft/debugpy#1006]
Issue Type: <b>Bug</b>

#print method does not add a newline correctly but somehow still preserves the newline space as if the code was printed on that newline but it is printed on the line where the previous print method was called:

![image](https://user-images.githubusercontent.com/110078998/182050410-a4e15cdb-518c-453e-ad7c-eb8d10154a64.png)
![image](https://user-images.githubusercontent.com/110078998/182050514-1f982565-7840-41fe-a524-6dc4cd46392d.png)
![image](https://user-images.githubusercontent.com/110078998/182050526-635de1f1-e2b8-4ea6-af86-172da30fc619.png)

VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:52.460Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by theCrazyCode** [comment]
Okay just did and still nothing has changed.

**Comment by int19h** [comment]
`print()` is not an atomic operation. If you invoke it concurrently from multiple threads without synchronizing, any kind of interleaving is possible. In practice, it appears that the implementation of `print()` invokes the `write()` syscall (or equivalent) for every argument. Thus, if you do:
```py
# thread 1
print('a', 'b')

# thread 2
print('c', 'd')
```
you can get "acbd" or even "acdb" very easily. And the newline is also effectively a separate output, hence why you're consistently seeing it interleave at that point.

The only way to fix this is to synchronize your prints using e.g. a mutex.

**Comment by theCrazyCode** [comment]
Could you show me an example on how to implement that with print statements

**Comment by int19h** [comment]
This seems to cover all the caveats: https://superfastpython.com/thread-safe-print-in-python/
