### ISSUE TITLE
Limitation of the number of variables

### ISSUE THREAD

**Issue by JohanMabille** [microsoft/debugpy#101]
Currently the number of variables returned by a `variables` request cannot exceed 300. This limit is [hardcoded](https://github.com/microsoft/debugpy/blob/master/src/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_resolver.py#L16).

Is it possible to either remove it or give the ability to change it from the outside (via the DAP for instance).

**Comment by fabioz** [comment]
This is now fixed in https://github.com/microsoft/debugpy/commit/01b1c7b23860ccf224ee17ca6f2880f6a3fc81e8

Some environment variables can be used to affect it:
```
# Values used to determine how much container items will be shown.
# PYDEVD_CONTAINER_INITIAL_EXPANDED_ITEMS:
#     - Defines how many items will appear initially expanded after which a 'more...' will appear.
#
# PYDEVD_CONTAINER_BUCKET_SIZE
#    - Defines the size of each bucket inside the 'more...' item
#        i.e.: a bucket with size == 2 would show items such as:
#            - [2:4]
#            - [4:6]
#            ...
#
# PYDEVD_CONTAINER_RANDOM_ACCESS_MAX_ITEMS
#    - Defines the maximum number of items for dicts and sets.
#
# PYDEVD_CONTAINER_NUMPY_MAX_ITEMS 
#    - Defines the maximum number of items for numpy arrays.
```
