### ISSUE TITLE
Debug Enter debugging host:port

### ISSUE THREAD

**Issue by STRUGGLE1999** [microsoft/debugpy#1011]
When I clicked "Run and Debug", it doesn't appear information, and it lets me enter the debugging host:port, but I have no idea which host and port should I enter, because I am trying to debug file on VS Code through cloud server.
Please help me!

![image](https://user-images.githubusercontent.com/66925708/184137593-ef50eeb0-3915-4244-82dd-7fe12aa5c4f6.png)

**Comment by judej** [comment]
Thanks for the report, unfortunately, this is not enough data for us to debug. 

If this continues to be a problem, would you please reopen the issue and add the information in the report as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue) as well include the launch.json file?
