### ISSUE TITLE
Is there a way to run initial python commands for debug tasks?

### ISSUE THREAD

**Issue by xxc-zsz** [microsoft/debugpy#1015]
Whenever I "Run and Debug" one of my Python files in VS Code, like this one:
```
import numpy
a = numpy.arange(1000)
print("Hello World!")  # <-- Breakpoint here
```
I'd like to have a few Python commands run first so they are "active" for the current session in the Debug Console, e.g., printing options like
```
import numpy as np
np.set_printoptions(linewidth=200, threshold=5000)
```
such that printed output in the Debug Console is more useful, e.g., if I type `a` in the Debug Console, I do want long lines as with the print options set.

I know one can run predefined tasks (via **tasks.json**) via the **launch.json**, but they run in an independent terminal, so they as far as I know can not be set up to affect the actual Python debug session. Is there a way to achieve this?

I'm aware that this could mess with the code, e.g., if somebody imported something else as `np`, but I'd be willing to take that risk.

**Comment by int19h** [comment]
Off the top of my head, one way to do it with the existing features is to use the "code" launch target, like so:
```
"type": "python",
"request": "launch",
"code": [
   "import runpy, numpy",
   "numpy.set_printoptions(linewidth=200, threshold=5000)",
   "runpy.run_path('foo')", 
],
```
@fabioz, are there any magic env vars in pydevd that could be used as autoexec for this scenario?
