### ISSUE TITLE
Python debugger is not stopping at breakpoints

### ISSUE THREAD

**Issue by ajloder** [microsoft/debugpy#1017]
Type: <b>Bug</b>

Python debugger is not stopping at breakpoints consistently, it just continues through the code as if there are no breakpoints. If I add the condition "True" to the breakpoint, it sometimes breaks, but I cannot determine why it sometimes does and sometimes does not.

Extension version: 2022.12.0
VS Code version: Code 1.70.1 (6d9b74a70ca9c7733b29f0456fd8195364076dda, 2022-08-10T06:08:33.642Z)
OS version: Windows_NT x64 10.0.19043
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 PRO 5850U with Radeon Graphics      (16 x 1896)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|14.83GB (3.57GB free)|
|Process Argv|--crash-reporter-id 85bee0b1-5941-4da2-b584-5817f0b45e20|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912cf:30529770
vsclangdf:30486550
c4g48928:30535728
d7fjc500:30543455
dsvsc012cf:30540253

```

</details>

**Comment by fabioz** [comment]
@ajloder can you provide the logging for your debug session to help diagnose your issue?

i.e.: 

* Run the command `Extensions: Open Extensions Folder`
* Locate the Python extension directory, typically of the form `ms-python.python-2022.*.****`
* In that directory ensure you do not have any debug*.log files, if you do, please delete them
* Go back into VS Code and modify your launch.json to add the setting `"logToFile": true`, see below:

```
{
    "name": "Python: Current File (Integrated Terminal)",
    "type": "python",
    "request": "launch",
    "program": "${file}",
    "console": "integratedTerminal",
    "logToFile": true
}
```

* Start debugging
* When done, go back into the extension directory and upload the debug*.log files into this GitHub issue.


Also, one thing to check could be disabling frame eval mode to know if it makes any difference.

To do that, set an environment variable as: `PYDEVD_USE_FRAME_EVAL=0`.

**Comment by fabioz** [comment]
Closing issue as additional feedback wasn't given. 

Please provide the logs to reopen the issue.
