### ISSUE TITLE
Gunicorn: Attach to Process Id Error - Timed out waiting for debug server to connect

### ISSUE THREAD

**Issue by lukeamcmurray** [microsoft/debugpy#102]
## Environment data

- VS Code version: 1.43.1
- Extension version:
  - Python: 2020.3.69010
  - Remote-WSL: 0.42.4
- OS and version:
  - Windows 10 Enterprise Version 1903 Build 18362.592
  - WSL Ubuntu 18.04
- Python version: 3.7.5
- Type of virtual environment used: N/A
- Jedi or Language Server?: Jedi
- Value of the `python.languageServer` setting: Microsoft

## Expected behaviour

With the project opened in a VS Code WSL session, starting an "Attach using Process Id" debug session and selecting the python process that is running in a WSL terminal should attach the debugger to the process.

## Actual behaviour

An error "Timed out waiting for debug server to connect" occurs after ~10 seconds and the debugger exits.

## Steps to reproduce:

1. Open WSL Bash session
2. Create a new test project and open in VS Code:

```sh
$ mkdir test && cd test && code .
```

3. Add a simple `test.py` script which continuously prints a counter:

```python
import time

count = 0
while True:
    print(count)
    count += 1
    time.sleep(1)
```

4. Add a launch config:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Attach using Process Id",
            "type": "python",
            "request": "attach",
            "processId": "${command:pickProcess}"
        }
    ]
}

```

5. Run the script in the WSL Bash session:

```sh
$ python3 test.py
```

6. In VS Code start an "Attach using Process Id" debug session and select the running process e.g.:

```
python3 1234
python3 test.py
```

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
> ps axww -o pid=,comm=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,args=
```

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`; turn on source maps to make any tracebacks be useful by running `Enable source map support for extension debugging`)

```
ERR timeout after 500 ms: Error: timeout after 500 ms
    at t.RawDebugSession.handleErrorResponse (file:///C:/Users/lmcmurray2/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2954:952)
    at file:///C:/Users/lmcmurray2/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2954:250
    at async t.RawDebugSession.shutdown (file:///C:/Users/lmcmurray2/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2952:336)
```

**Comment by int19h** [comment]
@devNaresh Does attach-by-PID work for you with a simple test app (i.e. no gunicorn or Flask - just a simple loop printing out numbers, or something like that)?

**Comment by int19h** [comment]
@fabioz Is there anything else that Luke could do here to get better diagnostics?

**Comment by fabioz** [comment]
As a note, the `GEVENT_SUPPORT=True` definitely must be set for Gunicorn (as it's being done)... 

The stack trace below hints that everything is working as expected for the connection on the debugger side (but the connection is not going through properly).

```
File "/home/luke/.vscode-server/extensions/ms-python.python-2020.3.69010/pythonFiles/lib/python/debugpy/wheels/debugpy/../debugpy/server/attach_pid_injected.py", line 80, in attach
 setup["address"], access_token=setup["adapter_access_token"]
File "/home/luke/.vscode-server/extensions/ms-python.python-2020.3.69010/pythonFiles/lib/python/debugpy/wheels/debugpy/common/compat.py", line 204, in kwonly_f
 return f(*args, **kwargs)
File "/home/luke/.vscode-server/extensions/ms-python.python-2020.3.69010/pythonFiles/lib/python/debugpy/wheels/debugpy/__init__.py", line 132, in connect
 return api.connect(address, access_token=access_token)
File "/home/luke/.vscode-server/extensions/ms-python.python-2020.3.69010/pythonFiles/lib/python/debugpy/wheels/debugpy/server/api.py", line 124, in debug
 log.reraise_exception("{0}() failed:", func.__name__, level="info")
File "/home/luke/.vscode-server/extensions/ms-python.python-2020.3.69010/pythonFiles/lib/python/debugpy/wheels/debugpy/server/api.py", line 122, in debug
 return func(address, settrace_kwargs, **kwargs)
File "/home/luke/.vscode-server/extensions/ms-python.python-2020.3.69010/pythonFiles/lib/python/debugpy/wheels/debugpy/server/api.py", line 248, in connect
 _settrace(host=host, port=port, client_access_token=access_token, **settrace_kwargs)
File "/home/luke/.vscode-server/extensions/ms-python.python-2020.3.69010/pythonFiles/lib/python/debugpy/wheels/debugpy/server/api.py", line 35, in _settrace
 return pydevd.settrace(*args, **kwargs)
File "/home/luke/.vscode-server/extensions/ms-python.python-2020.3.69010/pythonFiles/lib/python/debugpy/wheels/debugpy/_vendored/pydevd/pydevd.py", line 2539, in settrace
 __setup_holder__=__setup_holder__,
File "/home/luke/.vscode-server/extensions/ms-python.python-2020.3.69010/pythonFiles/lib/python/debugpy/wheels/debugpy/_vendored/pydevd/pydevd.py", line 2602, in _locked_settrace
 py_db.connect(host, port)  # Note: connect can raise error.
File "/home/luke/.vscode-server/extensions/ms-python.python-2020.3.69010/pythonFiles/lib/python/debugpy/wheels/debugpy/_vendored/pydevd/pydevd.py", line 1211, in connect
 s = start_client(host, port)
File "/home/luke/.vscode-server/extensions/ms-python.python-2020.3.69010/pythonFiles/lib/python/debugpy/wheels/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 534, in start_client
 s.connect((host, port))
ConnectionRefusedError: [Errno 111] Connection refused
```

The reasons I can think for this are:

1. There's some firewall blocking the communication (there may be nuances here related to WSL).

2. The `OSError: [Errno 92] Protocol not available: 'protocol'` seems to mean that there's some issue setting up the socket... it'd be nice to see the whole stack trace (if there's any) here (we could be trying to set some option which the Linux kernel doesn't support).

It'd be indeed nice to try with a simple app (the initial setup) to see if it works in that simpler use-case before proceeding with `gevent` which has more caveats (you can `import threading` to not have the `The threading module was not imported by user code in the main thread.`, but the interesting thing here would be knowing if it hits a breakpoint or not after doing a connection in some program with a `while True`).

**Comment by lukeamcmurray** [comment]
@fabioz here is the full output, including the stack trace:

```
[2020-04-06 08:32:04] [175] [DEBUG] [gunicorn.error] Current configuration:
  config: api/gunicorn.py
  bind: ['localhost:8000']
  backlog: 2048
  workers: 1
  worker_class: gevent
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 5
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  preload_app: True
  sendfile: None
  reuse_port: False
  chdir: /c/source/test-api/app
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 1000
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: None
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: -
  loglevel: info
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {'version': 1, 'disable_existing_loggers': True, 'root': {'level': 'DEBUG', 'handlers': ['console', 'seq']}, 'loggers': {'gunicorn.access': {'qualname': 'gunicorn.access', 'propagate': False, 'level': 'DEBUG', 'handlers': ['console', 'seq']}, 'gunicorn.error': {'qualname': 'gunicorn.error', 'propagate': False, 'level': 'DEBUG', 'handlers': ['console', 'seq']}}, 'handlers': {'console': {'class': 'seqlog.structured_logging.ConsoleStructuredLogHandler', 'formatter': 'standard'}, 'seq': {'class': 'seqlog.structured_logging.SeqLogHandler', 'formatter': 'seq', 'server_url': 'http://host.docker.internal:5341', 'api_key': None, 'batch_size': 1, 'auto_flush_timeout': 5}}, 'formatters': {'seq': {'style': '{'}, 'standard': {'format': '[%(asctime)s] [%(process)d] [%(levelname)s] [%(name)s] %(message)s', 'datefmt': '%Y-%m-%d %H:%M:%S'}}}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags:
  statsd_prefix:
  proc_name: None
  default_proc_name: api.api
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7fb9096d8170>
  on_reload: <function OnReload.on_reload at 0x7fb9096d8290>
  when_ready: <function when_ready at 0x7fb90a646b00>
  pre_fork: <function Prefork.pre_fork at 0x7fb9096d84d0>
  post_fork: <function Postfork.post_fork at 0x7fb9096d85f0>
  post_worker_init: <function post_worker_init at 0x7fb908dbe290>
  worker_int: <function WorkerInt.worker_int at 0x7fb9096d8830>
  worker_abort: <function WorkerAbort.worker_abort at 0x7fb9096d8950>
  pre_exec: <function PreExec.pre_exec at 0x7fb9096d8a70>
  pre_request: <function PreRequest.pre_request at 0x7fb9096d8b90>
  post_request: <function PostRequest.post_request at 0x7fb9096d8c20>
  child_exit: <function ChildExit.child_exit at 0x7fb9096d8d40>
  worker_exit: <function WorkerExit.worker_exit at 0x7fb9096d8e60>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7fb9096d8f80>
  on_exit: <function OnExit.on_exit at 0x7fb9096e60e0>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2020-04-06 08:32:48] [175] [INFO] [gunicorn.error] Starting gunicorn 20.0.4
[2020-04-06 08:32:48] [175] [DEBUG] [gunicorn.error] Arbiter booted
[2020-04-06 08:32:48] [175] [INFO] [gunicorn.error] Listening at: http://127.0.0.1:8000 (175)
[2020-04-06 08:32:48] [175] [INFO] [gunicorn.error] Using worker: gevent
[2020-04-06 08:32:48] [394] [INFO] [gunicorn.error] Booting worker with pid: 394
[2020-04-06 08:32:48] [175] [DEBUG] [gunicorn.error] 1 workers
/home/luke/miniconda3/envs/rosie-api/lib/python3.7/site-packages/gunicorn/workers/ggevent.py:53: MonkeyPatchWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. It may also silently lead to incorrect behaviour on Python 3.7. Please monkey-patch earlier. See https://github.com/gevent/gevent/issues/1016. Modules that had direct imports (NOT patched): ['urllib3.contrib.pyopenssl (/home/luke/miniconda3/envs/rosie-api/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py)'].
  monkey.patch_all()
[2020-04-06 08:32:49] [394] [ERROR] [gunicorn.error] Exception in worker process
Traceback (most recent call last):
  File "/home/luke/miniconda3/envs/rosie-api/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/luke/miniconda3/envs/rosie-api/lib/python3.7/site-packages/gunicorn/workers/ggevent.py", line 160, in init_process
    self.patch()
  File "/home/luke/miniconda3/envs/rosie-api/lib/python3.7/site-packages/gunicorn/workers/ggevent.py", line 62, in patch
    fileno=s.sock.fileno()))
  File "/home/luke/miniconda3/envs/rosie-api/lib/python3.7/site-packages/gevent/_socket3.py", line 114, in __init__
    self._sock = self._gevent_sock_class(family, type, proto, fileno)
OSError: [Errno 92] Protocol not available: 'protocol'
[2020-04-06 08:32:49] [394] [INFO] [gunicorn.error] Worker exiting (pid: 394)
[2020-04-06 08:32:49] [175] [INFO] [gunicorn.error] Shutting down: Master
[2020-04-06 08:32:49] [175] [INFO] [gunicorn.error] Reason: Worker failed to boot.
```

The initial setup was using the sync worker type which gave the debug timeout error.

**Comment by devNaresh** [comment]
yes @int19h attaching a process on simple test app works for me

**Comment by int19h** [comment]
Let's see if the environment variable is getting propagated correctly. Can you try doing `print(os.environ("GEVENT_SUPPORT"))` in the *child* process, and see what it says?

**Comment by lukeamcmurray** [comment]
I've confirmed that the GEVENT_SUPPORT env variable is being propagated and correctly set (`GEVENT_SUPPORT=True`) in the child worker. However i am unable to start the Gunicorn server using the config `worker_class='gevent'` as the worker throws a 'Protocol not available' error (same error as I shared above) and crashes the server. Are you able to confirm if gevent is the required worker class type for debugging support? If so, i'll need to figure out why i get that protocol error.

**Comment by int19h** [comment]
Oh, not at all! I think we were assuming that gevent is a fundamental dependency for Gunicorn - all the talk about `GEVENT_SUPPORT` above is stemming from that assumption, and that variable is only needed to enable special debugger support for gevent. If it's not in the picture, that actually simplifies things.

Attach-by-PID is inherently somewhat brittle, though, because we're working with a non-cooperative runtime (hence why it has to use gdb to inject code etc). It might be that Gunicorn itself also fiddles with stdlib in ways similar to gevent.

One thing that might be worth trying here is using attach to socket instead of attach to PID, if it is possible with your workflow (i.e. if you can start the server with `python -m debugpy ...`, or if you can sneak in `debugpy.listen()` call in there somewhere *before* it spawns the child processes). This would ensure that the debugger is loaded in all processes before the framework can do anything weird.

**Comment by lukeamcmurray** [comment]
Good to know gevent is not required for debugpy; my service is CPU bound so there was no intention of using an async worker type. 

I'll try your suggestions and get back to you.

**Comment by lukeamcmurray** [comment]
I managed to get the debugger to attach to the worker process by importing debugpy however it doesn't work fully; here's what I did;

Added the following to my `api/__init__.py`:

```py
import debugpy
debugpy.log_to('logs')
debugpy.listen(5678)
```

Added a remote attach launch config:

```json
{
	"name": "Python: Remote Attach",
	"type": "python",
	"request": "attach",
	"port": 5678,
	"host": "localhost",
	"pathMappings": [
		{
			"localRoot": "${workspaceFolder}",
			"remoteRoot": "."
		}
	],
	"justMyCode": false
}
```

Started the Gunicorn server:

```sh
gunicorn -c api/gunicorn.py api.api
```

Started the remote attach debug session in VS Code. The debugger successfully attached to the process however the issues I had are:
1. Can't set a breakpoint by clicking on a line in VS Code. Breakpoint is greyed out and followin g message shows when I hoiover over the breakpoint icon: breakpoint in file that does not exist.
2. Have to manually set a `breakpoint()` in the code to get the program to halt execution.
3. Even though the program halts execution at the breakpoint there is no visual indication of this (i.e. the line is not highlighted, although debugging control 'continue' is functional)
4. The following error shows when the breakpoint is hit and if i try to step through the code:

```
Unable to open 'api.py': Unable to read file 'vscode-remote://wsl+ubuntu/c/source/test-api/api/api.py' (Error: Unable to resolve non-existing file 'vscode-remote://wsl+ubuntu/c/source/test-api/api/api.py').
```

**Comment by int19h** [comment]
Huh, looks like we have a bigger issue with attach (path mapping specifically, I think?) not working properly when used in a remote VSCode session, then! Admittedly this is a bit of a weird scenario, but not so weird that it shouldn't be supported. Can you please file a separate issue for that?

Also, out of curiosity, what happens if you omit "pathMappings" entirely? I believe we did some improvements that should make them unneeded in the case when it's the same filesystem on both ends.

**Comment by lukeamcmurray** [comment]
Removing the 'pathMappings' entirely fixed all of the issues i listed in my previous post; although now i can't stop the debugger and i have to exit VS Code to do so. If i try to stop it using the controls or shift+F5 I get the following output:

```
[2020-04-17 12:42:18.373] [renderer1] [error] No debug adapter, can not send 'terminate': Error: No debug adapter, can not send 'terminate'
    at e.terminate (file:///C:/Users/luke/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6273:20)
    at e.stopSession (file:///C:/Users/luke/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6301:458)
    at handler (file:///C:/Users/luke/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6191:51)
    at d.invokeFunction (file:///C:/Users/luke/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1592:965)
    at e._tryExecuteCommand (file:///C:/Users/luke/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3629:267)
    at file:///C:/Users/luke/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3629:16
    at async run (file:///C:/Users/luke/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:127:287)
```

I suppose the good news is i can now debug the worker process, although i was hoping to be able to do so using the new attach to pid feature and without having to import a debugger into the code. Also, having to restart VS Code after each debugging session is not ideal ;)

**Comment by int19h** [comment]
I think we have to consider attach-to-PID to be unstable with Gunicorn for the time being.

Can you please file a separate issue for the unable-to-stop bug? Logs (from "logToFile") for that one would also be very useful.

**Comment by mosbasik** [comment]
@smuuf  

As a result of https://github.com/microsoft/vscode-docs/issues/5268, the [Troubleshooting section of the Python debugging docs](https://code.visualstudio.com/docs/python/debugging#_troubleshooting) now describe the `ptrace_scope=0` thingy.

And after https://github.com/microsoft/debugpy/issues/882 I was able to successfully attach the debugger to a running process on Arch.  Don't know if the fix for that issue is actually released yet, but [the workaround](https://github.com/microsoft/debugpy/issues/882#issuecomment-1092139563) they describe works for me in the meantime.

Can't help you much with WSL, though, sorry.

**Comment by judej** [comment]
Since attach-to-PID is unstable with Gunicorn, we are not planning on supporting this.
