### ISSUE TITLE
Debugger Does Not Enumerate ctypes Arrays

### ISSUE THREAD

**Issue by TheRealQuantam** [microsoft/debugpy#1025]
**Describe the bug**
The debugger in Visual Studio 2022 does not treat ctypes arrays as containers, and hovering over them or looking at them in the variables window does not show length or allow the items to be enumerated like a list or dict. This is a new problem in VS2022, and did not occur in VS2017 or VS2019, which is why I've only recently started using VS2022 and this problem is making it very unpleasant as I use ctypes extensively in my work.

Ordinarily I would post in a forum to ask if there is some setting that's set incorrectly (the settings are default for Python), but as there's no forum here I'm making a bug report.

**Steps to Reproduce**
For me this occurs any and all times I use ctypes arrays in any context, so I don't really have any specific instructions to reproduce. The only thing worth noting is that this occurs regardless of whether "Enable debugging of the Python standard library" is enabled (I mostly work with it enabled). Maybe read a random binary file into a bytearray and do something like

x = (ctypes.c_uint8 * len(file_bytes)).from_buffer(file_bytes)

Then hover over x (or look at it in the variables window). It will only show "special variables" and "protected variables".

**Expected behavior**
In past VS versions the debugger would display as if it was a list, showing the length and list of all elements.

**Configuration information**
VS Version: Community 2022 (64-bit) 17.3.0
PTVS version: 17.0.22179.3
Python version: 3.9.7 64-bit (x64)
Debugger Type: I don't think this is relevant for VS2022?

**Comment by int19h** [comment]
It looks like we don't actually handle collections in a sufficiently generic way for it to "just work":
https://github.com/microsoft/debugpy/blob/ea423ae5983c54b0a633dd51f2f7454078fdfa30/src/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_xml.py#L36-L114
So far as I can see, `TupleResolver` should work as is if it's registered as a resolver for ctypes arrays. However, because different array sizes produce different types, this will have to be implemented as a `TypeResolveProvider`.

**Comment by TheRealQuantam** [comment]
When and how will this fix be deployed?

**Comment by int19h** [comment]
Whenever a new version of debugpy is published on PyPI, the following PTVS release will normally pick it up. We do not have a regular release schedule for debugpy, so I can't specifically say when this will happen.

Note that you can always deploy fixes locally by placing a more up-to-date version of debugpy under "c:\users\advolker\appdata\local\microsoft\visualstudio\17.0_f467929dexp\extensions\microsoft corporation\python". It should work even if you just get it directly from git and copy it over, although you'll need to build it first (via `setup.py bdist`) to get native code optimizations that improve performance.
