### ISSUE TITLE
Debugger sometimes looks stuck with embedded interpreter

### ISSUE THREAD

**Issue by antounas** [microsoft/debugpy#1026]
I am using debugpy to debug a Python script which runs in the embedded interpreter of my application. Here is my test script:

```
import time

def foo():
    print("foo")
    d = 2
    e = 2
#    time.sleep(1)
def boo():
    print("Hello")
    print("Visual")
    print("Studio")
    print("World")
```
I have two breakpoints, one in line print('foo') and one in line print('Hello').

If I run function foo the debugger hits the breakpoint. Next I press the Continue button and the debugger runs the rest of the script. If I run foo again the debugger hits the breakpoint but when I press Continue the print('foo') line is still colored yellow. However I know that the execution of the script has finished because my application is no longer frozen. Moreover in the first run foo is printed in the Debug Console. In the second run it doesn't. Both foo are printed though in the terminal I used to launch my application. The log of this is adapter-6716/server-18329.

If I uncomment the time.sleep(1) line and repeat the above procedure everything works ok. The log of this is adapter-14888/server-11076.

If I run function boo twice the debugger doesn't look stuck e.g. the line doesn't stay yellow after the run but in the first run only Hello Visual Studio is printed while in the second run World Hello Visual is printed. The last print of the first run appears in the second run. The log of this is adapter-2516/server-14432.

I had the same problem with debugpy 1.2.1 but I had modified _vendored/pydevd/_pydeved_bundle/pydevd_io.py by adding a time.sleep(0.1) command in the IORedirector.flush function. This doesn't seem to work with debugpy 1.6.2.

Here are the log files mentioned above.
[163log.zip](https://github.com/microsoft/debugpy/files/9413800/163log.zip)

## Environment data

- debugpy version: 1.6.3
- OS and version: Windows 10
- Python version: 3.8.1
- Using VS Code: VS Code 1.70.2

**Comment by fabioz** [comment]
Can you describe the workflow you're using to start the debugger in your embedded interpreter?

Also, how exactly is Python embedded in your app? Are you calling the `atexit` callbacks? Usually in plain Python the `atexit` callbacks would be called and those would call `pydevd.stoptrace()` prior to exiting the interpreter to make sure all messages are written and to stop the tracing gracefully. If the embedded interpreter is shutdown in the embedding without calling the `atexit` callbacks it's very likely that messages won't be timely sent before exiting the process.

Also, I'm more interested in the logs given by pydevd itself which don't seem available in your logs (along with the session it is related to from debugpy) -- usually using the `logToFile` would generate them... If they weren't generated you can make pydevd generate them directly by setting the following environment variables:

```
PYDEVD_DEBUG=1
PYDEVD_DEBUG_FILE=<path/to/file.log>
```

**Comment by antounas** [comment]
First of all, thank you very much for the quick reply.

In order to start the debugger I run the following script in the embedded interpreter

```
import debugpy
debugpy.configure(python='/path/to/python_executable.exe')
ip, port = debugpy.listen(0)
```

The script takes the ip and port and updates the following launch configuration via the InitDebuggingTask with the correct values.

```
    "launch": {
        "version": "0.2.0",
        "configurations": [
            {
                "name": "Remote Debug",
                "type": "python",
                "request": "attach",
                "connect": {
                    "host": "127.0.0.1",
                    "port": 56995
                },
                "preLaunchTask": "InitDebuggingTask"
            }
        ],
        "compounds": []
    },
```

By running this launch configuration the debugger attaches to the embedded interpreter.

The embedded Python starts with Py_InitializeEx(0) when the application starts and stays alive as long as the application runs. The scripts are executed by using the C-API. So, I don't call any atexit function. I flush the stdout and stderr though after each script execution.

I used debugpy.log_to() function to generate the logs. I got only what was in the previous .zip file. Nevertheless, I now used the logToFile. In the attached [163logv2.zip](https://github.com/microsoft/debugpy/files/9424611/163logv2.zip) file you will find the 3 logs for the 3 cases I described above.

**Comment by fabioz** [comment]
Those logs still don't show the pydevd logs -- I'll investigate to know why that's happening, but that's a separate issue. Can you try setting the environment variables mentioned in https://github.com/microsoft/debugpy/issues/1026#issuecomment-1227147535?

In the case where you run the script (where the breakpoint still appears as suspended), are you shutting down the interpreter right afterwards or holding on to the gil? -- both of those could explain why messages which are sent from a thread from the debugger to the adapter are not arriving...

**Comment by antounas** [comment]
I run again the above scenarios with the environment variables enabled. You will find the results in [163logv3.zip](https://github.com/microsoft/debugpy/files/9430048/163logv3.zip). However running case1 as I did previously seemed to work correctly. The line didn't remain yellow after pressing the Continue button in the second run. This is case1ok.log. However, after hitting the breakpoint I pressed Step Over and afterwards Continue. This time the line remained yellow. This is case1.log.

I do not shut down the interpreter until my application exits. After pushing the Continue button for the second time I just press the Disconnect button in the debugger. The interpreter is still alive holding on to the gil.

**Comment by fabioz** [comment]
> The interpreter is still alive holding on to the gil.

If you create a thread and start it in the callback, does it keep running?

i.e.: in your callback call something as the code below... after you exit the callback, does it keep printing or does it stop?

```
import threading
import time
def target():
    while True:
        print('in thread')
        time.sleep(.2)

threading.Thread(target=target).start()
```

**Comment by antounas** [comment]
It stops. I get a couple  of prints "in thread" and then it stops.

**Comment by fabioz** [comment]
> It stops. I get a couple of prints "in thread" and then it stops.

This explains it. The threads that should send the debugger messages to the client aren't running in this case.

Given that, it's not really possible for the debugger to function properly. This needs to be fixed in your own integration and let the additional threads created by the debugger run so that the messages can be sent to the client... the debugger has provisions to send all the messages prior to shutdown of the Python process, but it can't know that the Python VM is going to be paused at an arbitrary point to send the messages before that.

**Comment by antounas** [comment]
OK I see.

So I guess, the modification I had applied at _vendored/pydevd/_pydeved_bundle/pydevd_io.py by adding a time.sleep(0.1) command in the IORedirector.flush function was fixing the problem because the debugger threads had some extra time to finish? But that just happened to work randomly?

**Comment by fabioz** [comment]
> So I guess, the modification I had applied at _vendored/pydevd/_pydeved_bundle/pydevd_io.py by adding a time.sleep(0.1) command in the IORedirector.flush function was fixing the problem because the debugger threads had some extra time to finish? But that just happened to work randomly?

Yes. If the message was sent before the sleep finished it'd work, otherwise it wouldn't (as the Python VM becomes frozen when your call completes it's very reliant on what's executed before it pauses).

**Comment by antounas** [comment]
I was wondering if I could call a debugpy function when the execution of my script finishes to let debugpy know that it can now flush everything.

**Comment by fabioz** [comment]
Right now there's no clear API for that, but if you're open to patching your local version you can get a callback to be run when no messages are pending to be handled (which'd mean it should be OK to freeze threads, so, you'd run the script and prior to going back to your code create an event and wait for that event to be set prior to locking threads from running).

It'd be something as:

```
from pydevd import get_global_debugger
from threading import Event

py_db = get_global_debugger()
writer = py_db.writer

event = Event()
writer.call_on_idle(event.set)
event.wait()
```

The patch to be applied to the writer thread would be something as:

At: https://github.com/microsoft/debugpy/blob/main/src/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py#L341
```
    # At the WriterThread class level:
    _call_on_idle = None

    def call_on_idle(self, on_idle):
        self._call_on_idle = on_idle
```

At: https://github.com/microsoft/debugpy/blob/main/src/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py#L367
```
                    # Change except clause to:
                    try:
                        cmd = self._cmd_queue.get(True, 0.1)
                    except _queue.Empty:
                        call_on_idle = self._call_on_idle
                        if call_on_idle is not None:
                            call_on_idle()
```


To know the file in your local installation you can run in the debugger:

```
from _pydevd_bundle import pydevd_comm
print(pydevd_comm.__file__)
```

Just as a note, anything that happens in VSCode after threads are paused may not be received by the debugger (I guess socket buffers would get filled and when threads start running again it syncs up, but there may be delays associated with that, so, in theory things as breakpoint changes after the initially setup could be missed).

**Comment by antounas** [comment]
Many thanks! I will give it a try and let you know how it goes.
