### ISSUE TITLE
unable to debug python program

### ISSUE THREAD

**Issue by pengzhangzhi** [microsoft/debugpy#1027]
I use vscode for remote python development. Normally I can debug my code in vscode. But sometimes when I debug, a error occurs. I literally didn't change any arguments in launch.json. I think it is because the OS system is stuck at doing something. Any helps?
![image](https://user-images.githubusercontent.com/59241275/186454989-8473dc7a-000e-4b2c-af18-358a454d52d0.png)

**Comment by fabioz** [comment]
@pengzhangzhi can you provide the logs when this happens?

See: https://github.com/microsoft/debugpy/wiki/Enable-debugger-logs for information on how to enable logs.

**Comment by fabioz** [comment]
Closing as no additional info was provided.

@pengzhangzhi please provide additional information to reopen the issue.
