### ISSUE TITLE
Debugpy adapter process is not closing even after debug is completed

### ISSUE THREAD

**Issue by sathish-sa-dev** [microsoft/debugpy#1034]
I'm trying to debug a file using debugpy through i/o stream. Debugging has done properly. But the strange behavior here is, the debug process is not terminated. It keeps on running. Need to kill manually each time. Please share if there is any workaround or proper solution to this issue. I can find something in *debugpy.pydevd.log* file. **The following pydb threads may not have finished correctly: pydevd.CommandThread, pydevd.Reader**. Ill share the logs here.

[debugpy.adapter-256905.log](https://github.com/microsoft/debugpy/files/9444002/debugpy.adapter-256905.log)
[debugpy.launcher-256913.log](https://github.com/microsoft/debugpy/files/9444003/debugpy.launcher-256913.log)
[debugpy.pydevd.256919.log](https://github.com/microsoft/debugpy/files/9444004/debugpy.pydevd.256919.log)
[debugpy.server-256919.log](https://github.com/microsoft/debugpy/files/9444005/debugpy.server-256919.log)

**Comment by int19h** [comment]
Can you clarify which process it is that does not exit (since they're all going to be Python, the complete command line is needed to distinguish)?

Judging by the logs, the process being debugged definitely exited, and various debugger helper processes are all at least trying to shut down.

**Comment by sathish-sa-dev** [comment]
I'm initiating debugger by using command: "absolute_path_of_python [space] absolute_path_of_debugpy/adapter" 
Eg: "/use/bin/python3.8 /home/workspace/.local/lib/python3.8/site-packages/debugpy/adapter"

This debugpy/adapter process starts debugpy/launcher process and once the debugging is completed, launcher process exits, but not the debugpy/adapter process. 

But in VSCODE editor, the debugpy/adapter process got exited smoothly. How is that happening ?

**Comment by int19h** [comment]
Oh, I didn't realize this is for a custom client!

Are you closing the redirected stdout pipe handle from your end? The adapter assumes that, as long as the pipe/socket remains open (i.e. it can `read()` on it and not get an EOF), the client may still wish to issue more requests, even after the debuggee has exited.

**Comment by int19h** [comment]
Please re-open if the above didn't work for you.
