### ISSUE TITLE
cannot import ipykernel debugger in Pycharm debug mode

### ISSUE THREAD

**Issue by eastonsuo** [microsoft/debugpy#1037]
when execute 
```
import debugpy
from ipykernel.debugger import Debugger
```
in **pycharm debug mode**, result in `ImportError: cannot import name 'pydevd_defaults' from '_pydevd_bundle'`

and an more specfic notice is :

`/Users/suoyi/miniforge3/envs/aicoder/lib/python3.9/site-packages/debugpy/_vendored/force_pydevd.py:20: UserWarning: incompatible copy of pydevd already imported`

## Environment data

- debugpy version: 1.6.2 (run `import debugpy; print(debugpy.__version__)` if uncertain)
- OS and version: MacOS
- Python version (& distribution if applicable, e.g. Anaconda): 1.9
- Using VS Code or Visual Studio: PyCharm

## Actual behavior

ImportError

## Expected  behavior

success
## Steps to reproduce:
execute in PyCharm debug mode
```
import debugpy
from ipykernel.debugger import Debugger
```

**Comment by fabioz** [comment]
PyCharm has a fork of `pydevd` (which is the same debug engine used by `debugpy`) which is incompatible with the one in `debugpy`, so, it's not possible to debug `debugpy` in `PyCharm` (so, to debug `debugpy` you need to use a client which is using `debugpy` too).
