### ISSUE TITLE
Debugger not working

### ISSUE THREAD

**Issue by ankurbhattarkasganj** [microsoft/debugpy#1039]
Type: <b>Bug</b>

1. Run - > start Debugging 
2. Debugger process starts and then Stop 

Extension version: 2022.12.1
VS Code version: Code 1.70.2 (Universal) (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:36:37.829Z)
OS version: Darwin arm64 21.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 12fe88bc-7e06-4260-878c-e4356a4610d5|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by fabioz** [comment]
@ankurbhattarkasganj or @pakyr can you provide the logs for the run when that happens?

See: https://github.com/microsoft/debugpy/wiki/Enable-debugger-logs for details on how to collect the logs.

**Comment by CwjXFH** [comment]
@ankurbhattarkasganj I have the same [issue](https://github.com/microsoft/debugpy/issues/1060), set the `justMyCode` value to false maybe can help you.

**Comment by int19h** [comment]
One thing of note is that this is macOS on ARM.

**Comment by TacoBel42** [comment]
same erorr
