### ISSUE TITLE
The chinese character doesn't correctly show in locals when debugging

### ISSUE THREAD

**Issue by gagmeng** [microsoft/debugpy#1046]
As shown below：
![image](https://user-images.githubusercontent.com/13564117/189096577-5a742299-e6a2-4497-aadb-bf8018b0991c.png)

python version: 2.7
vscode-python version: v2021.12.1559732655

**Comment by fabioz** [comment]
@gagmeng unfortunately Python 2.7 is no longer supported (so, ideally upgrade to Python 3 and get a newer version of vscode-python).
