### ISSUE TITLE
Handle ExceptionGroups in the debugger

### ISSUE THREAD

**Issue by rchiodo** [microsoft/debugpy#1047]
https://peps.python.org/pep-0654/ will be part of Python 3.11

This might require some changes in the UI?

/cc @int19h @zooba

**Comment by int19h** [comment]
I think the first step would be to make sure that we correctly break when an exception group with one or more of the exceptions for which a breakpoint was set. This shouldn't require new UI.

There's a potential separate feature here to allow setting breakpoints on several exceptions such that it only matches a group that has *all* of them - that would require new UI, and probably some DAP changes, too. But it feels like a fairly fringe use case, so I don't think we should do it until we have a real world scenario for it.

**Comment by judej** [comment]
Thank you for the report. Given our current resources are working on the Python 3.12 debugger, we will not be fixing this issues in the pre Python 3.12 debugger.
