### ISSUE TITLE
BSOD after runing Django debuger

### ISSUE THREAD

**Issue by amirhfro** [microsoft/debugpy#1053]
Type: <b>Bug</b>

# Behaviour
Windows 11 Insider Beta ran into BSOD and WATCHDOG_VIOLATION code right after start runing Djano debuger.

## Steps to reproduce:

1. Start Debuging Django

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.7
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): MicrosoftStore
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

</details>

<details>

<summary>User Settings</summary>

<p>

```

venvPath: "/.venv"

languageServer: "Pylance"

```

</p>
</details>

Extension version: 2022.15.12561016
VS Code version: Code 1.71.1 (e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb, 2022-09-08T19:56:36.424Z)
OS version: Windows_NT x64 10.0.22622
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900HX with Radeon Graphics         (16 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.42GB (3.73GB free)|
|Process Argv|--crash-reporter-id 36335a2b-a54f-4279-93ac-452951446b9c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30557514
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
pylanb8912:30545647
vsclangdf:30486550
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903

```

</details>

**Comment by judej** [comment]
Thanks for the report, unfortunately, this is not enough data for us to debug. 

If this continues to be a problem, would you please reopen the issue and add the information in the report as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

**Comment by debonte** [comment]
Collecting a memory dump would probably be useful to at least identify what component is at fault and therefore how to route this issue. In the Start menu, search for and select "View advanced system settings", click "Settings..." under "Startup and Recovery", and see the "System failure" configuration. Here's how mine is configured:

![image](https://user-images.githubusercontent.com/12820898/190478285-acaaa44c-872c-47ee-8184-2f9aef9dced7.png)
