### ISSUE TITLE
pythonArgs are not taking effect

### ISSUE THREAD

**Issue by fatandy567** [microsoft/debugpy#1055]
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

Expected:
c:/Users/dtu/AppData/Roaming/Python/Python38/Scripts/ipython.exe --ipython-dir=.\\

Actual:
c:/Users/dtu/AppData/Roaming/Python/Python38/Scripts/ipython.exe
## Steps to reproduce:

1. use pythonArgs in launch.jason
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "justMyCode": true,
            "python": "C:\\Users\\dtu\\AppData\\Roaming\\Python\\Python38\\Scripts\\ipython.exe --ipython-dir=.\\",
            "pythonArgs": [ "--ipython-dir=.\\"],
            "cwd": "C:\\Dropbox\\dtu_HP_desktop2\\PythonLab_beryllium\\PythonLab"
        }
    ]
}

2. run python code with VS Code and you will see "pythonArgs" are not there.

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.10
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Unknown
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

```

</p>
</details>

Extension version: 2022.14.0
VS Code version: Code 1.71.1 (e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb, 2022-09-08T19:56:36.424Z)
OS version: Windows_NT x64 10.0.19042
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (16 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.78GB (8.75GB free)|
|Process Argv|C:\\Dropbox\\dtu_HP_desktop2\\PythonLab_beryllium\\PythonLab --crash-reporter-id 94eeb4f1-25d8-4061-bd76-d99a58948e3e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903

```

</details>

**Comment by rchiodo** [comment]
Sorry pythonArgs isn't actually used during running a python file. You should instead use 
```
    "python.terminal.launchArgs": [
        "arg1", "arg2"
    ]
```

That is only going to pass the arg to python though. I don't believe there's any way to use IPython instead of Python as your python executable. 

Have you tried the [Python Interactive Window](https://code.visualstudio.com/docs/python/jupyter-support-py)? It is attempts to do what IPython is used for.

**Comment by rchiodo** [comment]
Unless you're actually trying to debug ipython? That's supported in the interactive window too:

![image](https://user-images.githubusercontent.com/19672699/190475625-2c6410b5-394c-4a29-8610-be9fac1733b9.png)

If you add `# %%` comments to your python file, you can click on 'debug cell' to debug the code in that cell.

**Comment by int19h** [comment]
"pythonArgs" is supposed to be passed to the Python binary specified, so if it doesn't get passed, it is a bug.

However, if you're looking at the terminal to see what gets passed, it'll be misleading. What gets spawned by the shell in the terminal is the debugpy launcher, not your app - and while this does use the interpreter specified via "python", it ignores "pythonArgs". The launcher then spawns your app using "python" + "pythonArgs". This should be observable from within the app if you access the complete command line of the process.
