### ISSUE TITLE
HitBreakpointIds is empty

### ISSUE THREAD

**Issue by chikalee** [microsoft/debugpy#1058]
Before creating a new issue, please check the [FAQ](https://github.com/microsoft/debugpy/wiki/FAQ) to see if your question is answered there.

## Environment data

- debugpy version: 1.6.3
- OS and version: Window11
- Python version: 3.10.7
- Using VS Code or Visual Studio:Visual Studio

## Actual behavior
I an using c# to write am editor. I set a breakpoint and debugger stop but no hit id return.
`
<--   E (stopped): {"seq": 11, "type": "event", "event": "stopped", "body": {"reason": "breakpoint", "threadId": 1, "preserveFocusHint": false, "allThreadsStopped": true}}`

**Comment by fabioz** [comment]
Well, the specification notes that `hitBreakpointIds?` is optional, so, this is correct/ok... 

The thread id is there for you to request the stack afterwards.

**Comment by chikalee** [comment]
Worked ! Thanks a lot ！
