### ISSUE TITLE
Cannot debug in virtual environment

### ISSUE THREAD

**Issue by CwjXFH** [microsoft/debugpy#1060]
```
Python version: 3.10.5
VS Code version: 1.71.2
Python extension version: v2022.14.0 / v2022.15.12591021
```

1. Create a virtual environment in one folder
    `python3 -m venv .`
2. Write some code
    ```python
    [breakpoint here] print("debug")
    ```
3. Select Python interpreter, which in the virtual environment
4. Press F5 to run the program, but cannot hit the breakpoint

5. Set the `justMyCode` value to `false`, and press F5 to run the program again, this time can hit the breakpoint
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "justMyCode": false
        }
    ]
}
```

But there is only my code in the program, it's confusing to me.

**Comment by rchiodo** [comment]
I believe the problem is that your source directory is inside your venv. You should put the venv in a separate folder. Like so:

```
python -m venv .venv
```

Anything under the venv folder is considered not your code as it's part of the virtual environment.
