### ISSUE TITLE
"ValueError: embedded null byte" during debugging

### ISSUE THREAD

**Issue by KirbyBroderick** [microsoft/debugpy#1066]
Type: <b>Bug</b>

Run python debugger inside kubectl using Remote - Kubernetes extension

```
:~/doegap$  /usr/bin/env /opt/conda/bin/python /home/jovyan/.vscode-server/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher 39827 -- /home/jovyan/doegap/doegap/load_data.py 
E+00000.023: /handling microsoft/vscode-python#1 request "launch" from Adapter/
             Traceback (most recent call last):
               File "/home/jovyan/.vscode-server/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/launcher/debuggee.py", line 91, in spawn
                 process = subprocess.Popen(cmdline, env=env, bufsize=0, **kwargs)
               File "/opt/conda/lib/python3.9/subprocess.py", line 951, in __init__
                 self._execute_child(args, executable, preexec_fn, close_fds,
               File "/opt/conda/lib/python3.9/subprocess.py", line 1754, in _execute_child
                 self.pid = _posixsubprocess.fork_exec(
             ValueError: embedded null byte
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
               File "/home/jovyan/.vscode-server/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/common/messaging.py", line 1015, in __init__
                 raise self
             debugpy.common.messaging.MessageHandlingError: Couldn't spawn debuggee: embedded null byte
             
             Command line:['/opt/conda/bin/python', '/home/jovyan/.vscode-server/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy', '--connect', '127.0.0.1:40429', '--configure-qt', 'none', '--adapter-access-token', 'b79119877e5a65440eb0d1ba422251674a964271de82bc3f392e3560af79f207', '/home/jovyan/doegap/doegap/load_data.py']
             
             Stack where logged:
               File "/opt/conda/lib/python3.9/threading.py", line 937, in _bootstrap
                 self._bootstrap_inner()
               File "/opt/conda/lib/python3.9/threading.py", line 980, in _bootstrap_inner
                 self.run()
               File "/opt/conda/lib/python3.9/threading.py", line 917, in run
                 self._target(*self._args, **self._kwargs)
               File "/home/jovyan/.vscode-server/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/common/messaging.py", line 1458, in _run_handlers
                 handler()
               File "/home/jovyan/.vscode-server/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/common/messaging.py", line 701, in _handle
                 result = handler(self)
               File "/home/jovyan/.vscode-server/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/launcher/handlers.py", line 140, in launch_request
                 debuggee.spawn(process_name, cmdline, env, redirect_output)
               File "/home/jovyan/.vscode-server/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/launcher/debuggee.py", line 93, in spawn
                 raise messaging.MessageHandlingError(
               File "/home/jovyan/.vscode-server/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/common/messaging.py", line 1017, in __init__
                 log.swallow_exception()
               File "/home/jovyan/.vscode-server/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/common/log.py", line 215, in swallow_exception
                 _exception(format_string, *args, **kwargs)
             

E+00000.033: /handling microsoft/vscode-python#1 request "launch" from Adapter/
             Handler 'launch_request' (file '/home/jovyan/.vscode-server/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/launcher/handlers.py', line 14)
             couldn't handle microsoft/vscode-python#1 request "launch" from Adapter:
             Couldn't spawn debuggee: embedded null byte
             
             Command line:['/opt/conda/bin/python', '/home/jovyan/.vscode-server/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy', '--connect', '127.0.0.1:40429', '--configure-qt', 'none', '--adapter-access-token', 'b79119877e5a65440eb0d1ba422251674a964271de82bc3f392e3560af79f207', '/home/jovyan/doegap/doegap/load_data.py']
```

Extension version: 2022.14.0
VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:03:37.738Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.3.18-150200.24.126-default
Remote OS version: Linux x64 5.3.18-150200.24.126-default
Remote OS version: Linux x64 5.13.0-39-generic
Remote OS version: Linux x64 5.13.0-52-generic
Remote OS version: Linux x64 5.13.0-52-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.71GB (15.53GB free)|
|Process Argv|--crash-reporter-id 40140715-e4be-46e1-9426-c83bba5db9bc|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|bandgap in bandgap-0 (ulissigroup/kubeflow:bandgap)|
|OS|Linux x64 5.13.0-52-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz (56 x 1300)|
|Memory (System)|125.78GB (118.19GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30557514
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
hb751961:30553087
dsvsc012cf:30540253
azure-dev_surveyone:30548225
i497e931:30553904
fc301958:30573243

```

</details>

**Comment by fabioz** [comment]
@KirbyBroderick I think the issue is in the arguments you're passing to subprocess (a `\0` probably is getting in that string somehow).

**Comment by int19h** [comment]
The arguments as logged look fine to me, but I think this restriction might also apply to "env".

If you run it with `"logToFile": true` in your debug config, you'll get a complete log in `/home/jovyan/.vscode-server/extensions/ms-python.python-2022.14.0/debugpy.launcher*.log`. This might provide more clues - in particular, it logs "env".

**Comment by KirbyBroderick** [comment]
> ...

cat /home/jovyan/.vscode-server/extensions/ms-python.python-2022.14.0/debugpy.launcher-290381.log 
I+00000.009: Linux-5.13.0-39-generic-x86_64-with-glibc2.31 x86_64
             CPython 3.9.13 (64-bit)
             debugpy 1.6.3

I+00000.018: debugpy.launcher startup environment:
             
             System paths:
                 sys.prefix: /opt/conda
                 sys.base_prefix: /opt/conda
                 sys.real_prefix: <missing>
                 site.getsitepackages(): /opt/conda/lib/python3.9/site-packages
                 site.getusersitepackages(): /home/jovyan/.local/lib/python3.9/site-packages
                 sys.path (site-packages): /opt/conda/lib/python3.9/site-packages
                 sysconfig.get_path('stdlib'): /opt/conda/lib/python3.9
                 sysconfig.get_path('platstdlib'): /opt/conda/lib/python3.9
                 sysconfig.get_path('purelib'): /opt/conda/lib/python3.9/site-packages
                 sysconfig.get_path('platlib'): /opt/conda/lib/python3.9/site-packages
                 sysconfig.get_path('include'): /opt/conda/include/python3.9
                 sysconfig.get_path('scripts'): /opt/conda/bin
                 sysconfig.get_path('data'): /opt/conda
                 os.__file__: /opt/conda/lib/python3.9/os.py
                 threading.__file__: /opt/conda/lib/python3.9/threading.py
                 debugpy.__file__: /home/jovyan/.vscode-server/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__init__.py(/home/jovyan/.vscode-server/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/__init__.py)

I+00000.018: sys.argv before parsing: ['/home/jovyan/.vscode-server/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher', '34939', '--', '/home/jovyan/catlas/test.py']

I+00000.018: sys.argv after patching: ['/home/jovyan/.vscode-server/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher', '/home/jovyan/catlas/test.py']

I+00000.019: Connecting to adapter at 127.0.0.1:34939

D+00000.019: Starting message loop for channel Adapter

D+00000.020: Adapter --> {
                 "seq": 1,
                 "type": "request",
                 "command": "launch",
                 "arguments": {
                     "name": "Python: Current File",
                     "type": "python",
                     "request": "launch",
                     "program": "/home/jovyan/catlas/test.py",
                     "console": "integratedTerminal",
                     "justMyCode": true,
                     "logToFile": true,
                     "__configurationTarget": 6,
                     "python": [
                         "/opt/conda/bin/python"
                     ],
                     "debugAdapterPython": "/opt/conda/bin/python",
                     "debugLauncherPython": "/opt/conda/bin/python",
                     "cwd": "/home/jovyan/catlas",
                     "envFile": "/opt/conda/bin/python",
                     "env": {
                         "p": "",
                         "dont_inherit": "False, optimize=-1, *, _feature_version=-1)",
                         "x": "firstval",
                         "co_kwonlyargcount": "-1, co_nlocals=-1, co_stacksize=-1,",
                         "co_flags": "-1, co_firstlineno=-1, co_code=None, co_consts=None,",
                         "co_names": "None, co_varnames=None, co_freevars=None,",
                         "co_cellvars": "None, co_filename=None, co_name=None,",
                         "co_lnotab": "None)",
                         "translate": "False, it ensures that the newline sequence is returned in",
                         "line_buffering": "False, write_through=False)",
                         "errors": "None, newline=None, closefd=True, opener=None)",
                         "follow_symlinks": "True)",
                         "after_in_child": "<unrepresentable>,",
                         "after_in_parent": "<unrepresentable>)",
                         "dir_fd": "None, follow_symlinks=True)",
                         "setpgroup": "<unrepresentable>, resetids=False, setsid=False,",
                         "setsigmask": "(), setsigdef=(), scheduler=<unrepresentable>)",
                         "d": "{}",
                         "i": "\u0000\u0000C\u0001\u0000\u0001\ufffd\u0011\ufffd\u0003\u0000\u0006\u001bi=\u0000[",
                         "n": "\u0000\ufffdN\t\u0000\ufffdN\t\u0000\u0013\ufffd\u00113\u0000\ufffd",
                         "a": "\u000f\u0000\u0000\u0000\u0000\u0000\ufffd)\u0000\u0000n\ufffd",
                         "k": "\u000f\u0000\u0000\u0000\u0000\u0000\ufffd(\u0000\u0000\ufffd\ufffd",
                         "R": "\u001f\u0000\u0000\u0000\u0000\u0000\ufffd\ufffd\u000f\u0000\ufffdn\u000e\u0000\b\u0001U\u0002s\u0000\b\u0001Q\u00010\b\u0001R\u00010\u0000",
                         "Z": "\u0010\u0000\u0000\u0000\u0000\u0000Hs\u0007\u0000S\u0003.\u0000\b\u0001U\u0002|\u0000\u0000",
                         "q": "\u0000\u0000\u0000\u0000\u0000r\ufffd\u0001\u0000vH\u0017\u0000\b\u0001T\t\u0003h\ufffd&\u0000\u0000\u0000\u0000\u0000\b\u0001Q\u0004\ufffd\ufffd\u007f\u0006\u0000",
                         "W": "!\u0000\u0000\u0000\u0000\u0000\ufffdO\u0013\u0000\ufffd\ufffd\u0019\u0000\b\u0001U\u0002u\u0000\u001f&\ufffd\u0010\u0000\u0002s\u0000\u0000",
                         "V": "\u0000\u0000\u0000\u0000\u0000\ufffd\ufffd\u0001\u00008, \u0000\b\u0001U\t\u0003\ufffd\ufffd&\u0000\u0000\u0000\u0000\u0000\b\u0001T\u0003",
                         "T": "\u0000\u0000\u0000\u0000\u0000\u0019D\u0007\u0000\ufffd%%\u0000\b\u0001U\u0002}\u0000\b\u0001T\t\u0003\ufffd\ufffd7\u0000\u0000\u0000\u0000\u0000\u0000",
                         "h": "\u0000\u0000\u0000\u0000\u0000\ufffd\ufffd\u0001\u0000\ufffd%%\u0000\b\u0001U\u0002s\u0000\u0000",
                         "M": "\u0002\u0000|",
                         "F": "\u0001\u0000\u001e\ufffd\u0017\ufffd\u001d\u0000\u0000\u0018\u0000\u000f\u0010\u001e\ufffd\t\ufffd\"\u0000\u0000",
                         "E": "\u0000\u0000\u0015\u0018\u00109\u000e\u0000\u0000@",
                         "m": "\u0000\u0000\u0015\u001c\u00109\u000e\u0000\u0000H",
                         "PYTHONIOENCODING": "UTF-8",
                         "PYTHONUNBUFFERED": "1"
                     },
                     "stopOnEntry": false,
                     "showReturnValue": true,
                     "internalConsoleOptions": "neverOpen",
                     "debugOptions": [
                         "ShowReturnValue"
                     ],
                     "workspaceFolder": "/home/jovyan/catlas",
                     "__sessionId": "6758000e-70de-4203-bd30-3b97170e29c7",
                     "pythonArgs": [],
                     "processName": "/home/jovyan/catlas/test.py",
                     "port": 46477,
                     "adapterAccessToken": "37cd8666f13908cdf5129fad462a919b9dab296ff67f2752f98fffecbde216c2"
                 }
             }

Looks like something was corrupted or improperly coded?

**Comment by int19h** [comment]
You have `"envFile": "/opt/conda/bin/python"` in your launch.json. I'm not sure what the intent was, but this tells VSCode that it should read environment variable definitions (as `NAME=VALUE\n`) from that file. Looks like it did just that!
