### ISSUE TITLE
Use "startDebugging" request for subprocesses

### ISSUE THREAD

**Issue by rchiodo** [microsoft/debugpy#1074]
See:
https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_73.md#new-startdebugging-reverse-request

**Comment by int19h** [comment]
For backwards compatibility, we'll need to fall back to `debugpyAttach` if `supportsStartDebuggingRequest` is false.

@karthiknadig, is there anything special that vscode-python does about `debugpyAttach` request, other than forwarding it to VSCode to initiate a new session, like any attribute rewrites?

**Comment by int19h** [comment]
Some blockers and limitations on VSCode side:

https://github.com/microsoft/vscode/issues/173654
https://github.com/microsoft/vscode/issues/173655
