### ISSUE TITLE
Python Debugger Crashes confusing Python extension locking VScode app

### ISSUE THREAD

**Issue by thisiswhereitype** [microsoft/debugpy#1076]
Type: <b>Bug</b>

My bug occurs (I think) when an error is throw and supressed in a `finally` block, this only occurs when [supressing errors](https://docs.python.org/3/tutorial/errors.html#defining-clean-up-actions). 

However when I tested this for a minimal reproduction I couldn't replicate the crashing.

<summary> Code replication</summary>
<details>

```python
import torch.nn as nn
import torch.nn.functional as F
import functools as ftls
def runner():    
    def evaluate_loss(xb,yb, loss):
        return loss(xb,yb)
    try:
        l = [evaluate_loss(t=5,p=1, loss=ftls.partial(F.mse_loss, clips=True)) for i in range(5)]
    except Exception as e:
        print('Error to be suppressed:', type(e), e)
        raise e
    finally:
        return 
    
runner()
```
</details>
At which point the debugger crashes and a prompt appears suggesting to open `lanuch.json`, either options will have no effect and the notification about the port checked for the debugger process will appear in the bottom right.

The effect is the app must be ended externally and restarted.

<summary>System Info</summary>

Extension version: 2022.17.12772303
VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:03:37.738Z)
OS version: Windows_NT x64 10.0.19042
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (24 x 2500)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.91GB (53.56GB free)|
|Process Argv|--crash-reporter-id 3ad53ac5-f4fd-4704-94ce-7a59410678f7|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (24 x 2499)|
|Memory (System)|50.14GB (48.51GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2144e591:30553903
pyindex848cf:30577861
40g7c324:30573242

```

</details>

**Comment by fabioz** [comment]
@thisiswhereitype does this happen if you disable the debugger compiled extensions?

i.e.: set an environment variable as: `PYDEVD_USE_CYTHON=0` in your launch config and try to run again.

Also, do you have any stack trace when this happens if you enable `faulthandler`? (see: https://docs.python.org/3/library/faulthandler.html)

**Comment by thisiswhereitype** [comment]
This is still on my plate, apologies for delay - 

I will extract the notebook as a script and then edit `launch.json` to set the env var?
Looks like it can be done such as this: https://stackoverflow.com/a/45426595

**Comment by int19h** [comment]
Please re-open if you're still seeing this and can try the workaround.

Given that this is a remote WSL scenario, the most reliable way to set the environment variable is probably to put it in your `.profile` or equivalent and re-login, so that it applies to all the processes running in your session.
