### ISSUE TITLE
cannot receive dap response?

### ISSUE THREAD

**Issue by zhouyi-u** [microsoft/debugpy#1088]
After I start debugpy in command line:
"python3 -m debugpy --listen 9249 --wait-for-client main.py",

I connect 9249 with dap client (base on google cppdap), I can send the request : initialize \launch\ setbreakpoints\ next，but I cannot receive stopped event，I received output event "ptvsd \debugpy" , then received no more any messages.

What wrong with my program?

**Comment by fabioz** [comment]
It's hard to know why it's not stopping on breakpoints from that description.

Can you provide the logs?

See: https://github.com/microsoft/debugpy/wiki/Enable-debugger-logs for details on how to collect the logs.

**Comment by zhouyi-u** [comment]
I have resolve it with attaching the port 9249, thank you very much.

**Comment by fabioz** [comment]
Great that you've been able to solve it ;)
