### ISSUE TITLE
Cannot received TerminatedEvent or  ExitedEvent.

### ISSUE THREAD

**Issue by zhouyi-u** [microsoft/debugpy#1090]
I started debugpy in command line:
"/usr/bin/python3.7 -m debugpy --listen 6999 --wait-for-client --log-to /home/xxx/pythonlog /data/home/xxx/main.py --pid 9567"

when I send request about inintialize、 attach、next、continue， it is okey.
but the python program has run finished, I had no received the event about TerminatedEvent or ExitedEvent.
and in command line the "/usr/bin/python3.7 -m debugpy --listen 6999 --wait-for-client --log-to /home/xxx/pythonlog /data/home/xxx/main.py --pid 9567" finished.

there is ExitedEvent in log, but not received in dap client.

5905 Client <-- Adapter:
{
    "seq": 30,
    "type": "response",
    "request_seq": 20,
    "success": true,
    "command": "continue",
    "body": {
        "allThreadsContinued": true
    }
}
5905 Client <-- Adapter:
{
    "seq": 31,
    "type": "event",
    "event": "continued",
    "body": {
        "threadId": 1,
        "allThreadsContinued": true
    }
}
5906 Client <-- Adapter:
{
    "seq": 32,
    "type": "event",
    "event": "thread",
    "body": {
        "reason": "exited",
        "threadId": 1
    }
}
6435 Client <-- Adapter:
{
    "seq": 33,
    "type": "event",
    "event": "exited",
    "body": {
        "exitCode": 0
    }
}
6435 Client <-- Adapter:
{
    "seq": 34,
    "type": "event",
    "event": "terminated"
}
6438 Client --> Adapter:
{
    "command": "disconnect",
    "arguments": {
        "restart": false
    },
    "type": "request",
    "seq": 21
}
6438 Client <-- Adapter:
{
    "seq": 35,
    "type": "response",
    "request_seq": 21,
    "success": true,
    "command": "disconnect"
}
6940 Stopping Session
6942 Error:
{}
6943 Exit:
Exit-Code: 0
Signal: none

the dap client code:
dapSession->registerHandler([&](const ExitedEvent &event) {
    Q_UNUSED(event)
    qInfo() << "\n--> recv : "
            << "ExitedEvent";
    printOutput(tr("The debugee has Exited.\n"), NormalMessageFormat);
    updateRunState(kNoRun);
});

// The event indicates that debugging of the debuggee has terminated.
// This does not mean that the debuggee itself has exited.
dapSession->registerHandler([&](const TerminatedEvent &event) {
    Q_UNUSED(event)
    qInfo() << "\n--> recv : "
            << "TerminatedEvent";
    printOutput(tr("\nThe debugee has Terminated.\n"), NormalMessageFormat);
    updateRunState(kNoRun);
});

// The event indicates that a thread has started or exited.
dapSession->registerHandler([&](const ThreadEvent &event) {
    Q_UNUSED(event)
    qInfo() << "\n--> recv : "
            << "ThreadEvent";
});

**Comment by zhouyi-u** [comment]
I have known the reason. I used google's cppdap as dap client, which "body" field in "Terminated Event" is an optional field, but if no "body" will return {} in processEvent function.

![image](https://user-images.githubusercontent.com/112470190/197090828-ef2d9af7-0dcb-42f3-a842-10d118113702.png)
![image](https://user-images.githubusercontent.com/112470190/197090852-38831334-18d8-43f2-ae0d-2022e0c1facb.png)

**Comment by fabioz** [comment]
Closing since the debugger seems to be doing the right thing here.
