### ISSUE TITLE
"variables" command question

### ISSUE THREAD

**Issue by zhouyi-u** [microsoft/debugpy#1093]
The cycle is not over. is it right？

![企业微信截图_16663209285454](https://user-images.githubusercontent.com/112470190/197101765-eac5c7c5-c94c-40a9-9d6f-59af12e1fd00.png)

[debugpy.adapter-12818.log](https://github.com/microsoft/debugpy/files/9835366/debugpy.adapter-12818.log)

**Comment by fabioz** [comment]
Yes, that's correct.

![image](https://user-images.githubusercontent.com/117621/197180943-4ab2d4de-9d5e-4b6d-98cc-98d293e79da1.png)
