### ISSUE TITLE
Pytest with Django in Docker breaks on exceptions but not breakpoints

### ISSUE THREAD

**Issue by nkanderson** [microsoft/debugpy#1098]
## Environment data

- debugpy version: 1.6.3
- OS and version: macOS Monterey 12.3.1
- Python version (& distribution if applicable, e.g. Anaconda): 3.10.7 (python:3.10.7-slim-bullseye Docker image)
- Using VS Code or Visual Studio: VS Code

## Actual behavior

Debugger does **not** break on any breakpoints in test files while running a valid test using `pytest` in a docker container with Django installed, but does break on exceptions raised from the test file, as well as breakpoints in a basic python script.

## Expected  behavior

Debugger breaks on breakpoints in a test file run via `pytest`, with Django installed.

## Steps to reproduce:
1. Create a basic Django app with `pytest` installed:

(Assuming a basic virtual env is set up as needed)

requirements.txt:
```
asgiref==3.5.2
attrs==22.1.0
Django==4.1.2
iniconfig==1.1.1
packaging==21.3
pluggy==1.0.0
py==1.11.0
pyparsing==3.0.9
pytest==7.1.3
sqlparse==0.4.3
tomli==2.0.1
```

```sh
pip install -r requirements.txt
```

```sh
django-admin startproject config .
```

Minimal test file, e.g. `test_debugger.py`:
```py
import pytest


def test_debug():
    x = 1
    y = 5
    z = x + y
    assert z == 1 # debugger will break on this exception, but not breakpoints in this file
```

 and `pytest` config, e.g. `setup.cfg`:
```
[tool:pytest]
python_files = tests.py test_*.py *_tests.py
addopts = -vv -x
```

2. Add config for Docker and compose

example `Dockerfile`:
```
FROM python:3.10.7-slim-bullseye

EXPOSE 8000

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

# Install pip requirements
COPY requirements.txt .
RUN python -m pip install -r requirements.txt

WORKDIR /app
COPY ./ /app

RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

# During debugging, this entry point will be overridden. For more information, please refer to https://aka.ms/vscode-docker-python-debug
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "config.wsgi"]
```

`compose.yaml`:
```
services:
  debug_vscode:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./:/app
```

3. Add VS Code debug config

launch.json:
```json
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Python: Attach",
      "type": "python",
      "request": "attach",
      "justMyCode": false,
      "connect": {
        "host": "localhost",
        "port": 5678
      },
      "pathMappings": [
        {
          "localRoot": "${workspaceFolder}",
          "remoteRoot": "/app"
        }
      ],
    }
  ]
}
```

4. Run pytest in docker container with debugpy and attach debugger:
```sh
docker compose run --publish 5678:5678 --rm debug_vscode sh -c "pip install debugpy -t /tmp && python /tmp/debugpy --log-to log/debug --wait-for-client --listen 0.0.0.0:5678 -m pytest"
```
Then attach debugger. Tests will run through to completion if all are passing, skipping any breakpoints in the test file. If an exception is thrown, the debugger will break as expected, but still skip user-specified breakpoints.

I've verified that the same `launch.json` and docker config works as expected in a codebase with just pytest.

**Comment by int19h** [comment]
Could you share the logs from `--log-to`, as well? The `debugpy.pydevd*.log` would be especially helpful.

**Comment by nkanderson** [comment]
@int19h I got the first 2 from the container, and the last 4 from the directory specified in the `--log-to` command.

[debugpy.pydevd.10.log](https://github.com/microsoft/debugpy/files/9856189/debugpy.pydevd.10.log)
[debugpy.pydevd.17.log](https://github.com/microsoft/debugpy/files/9856190/debugpy.pydevd.17.log)

[debugpy.adapter-14.log](https://github.com/microsoft/debugpy/files/9856183/debugpy.adapter-14.log)
[debugpy.adapter-28.log](https://github.com/microsoft/debugpy/files/9856184/debugpy.adapter-28.log)
[debugpy.server-10.log](https://github.com/microsoft/debugpy/files/9856185/debugpy.server-10.log)
[debugpy.server-17.log](https://github.com/microsoft/debugpy/files/9856186/debugpy.server-17.log)

**Comment by fabioz** [comment]
One thing that stood out for me: there's a path translation setup.

i.e.:

```
0.01s - Request for breakpoint in: <redacted - local file path to workspace dir>/debugpy-django/test_debugger.py line: 7
0.01s - Breakpoint (after path translation) in: /app/test_debugger.py line: 7
0.01s - Added breakpoint:/app/test_debugger.py - line:7 - func_name:None
```

The path translation seems to map to an existing file, but later on, the output logs from `pytest` seem to print the original path?

i.e.: 
> 0.00s - sending cmd (http_json) --> CMD_WRITE_TO_CONSOLE {"type": "event", "event": "output", "body": {"output": "test_debugger.py::test_debug <- ..<redacted - local file path to workspace dir>/debugpy-django/test_debugger.py ", "category": "stdout", "source": {}}, "seq": 56, "pydevd_cmd_id": 116}

So, could it be that although the path translation does change the path to a proper place, the filename that's being run in the remote isn't really the translated one?

i.e.: if you `print(__file__)` in the `test_debugger.py` module, does the output match the one from the path translation? If it doesn't that'd be an issue...

**Comment by nkanderson** [comment]
@fabioz the result of `print(__file__)` in the test file is the path on my local machine instead of inside the docker container. Any ideas what might be causing that issue?

**Comment by fabioz** [comment]
Maybe it's copying `.pyc` files generated in your machine?

**Comment by nkanderson** [comment]
Ahh yes, thank you, I think that's the issue! I had added `__pycache__` to my `.dockerignore` in my original project where I found this issue, but I'm using a volume mount with docker compose to avoid having to rebuild my container every time there's any application code change (same as in the example compose file above).

I guess having attempted to run the tests locally first created `__pycache__` dirs that were included in the container via the volume, with paths on the host instead of the container. Having deleted those dirs, the breakpoints are breaking now, as expected.

So it sounds like the debugger ignores commands sent to non-existent files in the container?

**Comment by fabioz** [comment]
> So it sounds like the debugger ignores commands sent to non-existent files in the container?

Actually, the file (`/app/test_debugger.py`) did exist in the container, the problem is that when executing python it loaded the .pyc which said that the file had a different filename than it actually had (because it was built from a different machine and in this case, there's not much that can be done in the debugger as python itself is saying that the filename is different).

Presumably if `PYTHONDONTWRITEBYTECODE=1` wasn't set, this wouldn't be an issue...

**Comment by nkanderson** [comment]
That's interesting, I didn't realize a `pyc` file with a non-existent filepath wouldn't result in some other type of error - but I guess since it's an optimization, it just attempts to use that path, then falls back to running without it? Anyways, thanks for taking a look!
