### ISSUE TITLE
Clipboard context value for the "evaluate" request

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/debugpy#110]
DAP clients (frontends) use the `evaluate` request when copying variable and expression values to the clipboard. To help debug adapters detect this scenario, a new value `clipboard` has been added to the value set for the `context` argument that is passed to the `evaluate` request. To ensure backward compatibility, a client is only allowed to pass the new value if the debug adapter returns a `supportsClipboardContext` capability.

**Comment by nmay231** [comment]
Implementing this feature would be much appreciated :smiley:

**Comment by fabioz** [comment]
As a note, this is already in my short-list of issues TODO, so, it should not take much longer for it to be implemented...
