### ISSUE TITLE
PyInt_FromLong not found

### ISSUE THREAD

**Issue by Corfucinas** [microsoft/debugpy#1100]
## Environment data

- debugpy version: 1.6.3
- OS and version: Ubuntu 22.10 
-  Kernel: 5.19.0-23-generic
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.11.0 (installed via pyenv)
- Using VS Code or Visual Studio: VS Code

## Actual behavior

Debugger prints constantly `PyInt_FromLong not found.`

## Expected  behavior

Debugger to work without this behavior

## Steps to reproduce:
1. Install python 3.11.0
2. Debug any file (no .vscode/launch.json is required, it will fail with both).

**Comment by fabioz** [comment]
Can you provide the logs when that happens?

See: https://github.com/microsoft/debugpy/wiki/Enable-debugger-logs for details on how to collect the logs.

**Comment by kpms-mayank-kumar** [comment]
Facing the same issue. Debugger prints constantly PyInt_FromLong not found.
Image built on top of "FROM python:3-slim ".

172.23.0.1 - - [26/Oct/2022 03:23:44] "POST /logging/insert HTTP/1.1" 200 -
PyInt_FromLong not found.
PyInt_FromLong not found.
PyInt_FromLong not found.
172.23.0.1 - - [26/Oct/2022 03:23:44] "POST /logging/insert HTTP/1.1" 200 -
PyInt_FromLong not found.
172.23.0.1 - - [26/Oct/2022 03:23:44] "POST /logging/insert HTTP/1.1" 200 -
PyInt_FromLong not found.
PyInt_FromLong not found.
172.23.0.1 - - [26/Oct/2022 03:23:44] "POST /logging/insert HTTP/1.1" 200 -
PyInt_FromLong not found.
172.23.0.1 - - [26/Oct/2022 03:23:44] "POST /logging/insert HTTP/1.1" 200 -
PyInt_FromLong not found.
PyInt_FromLong not found.
PyInt_FromLong not found.

**Comment by bcxpro** [comment]
I am seeing the same message when I launch a debug task from vscode.

Python 3.11.0 on Ubuntu 20.04 from deadsnake's ppa (on a new vanilla .venv dir installed with `python -m venv .venv`) and a simple program

```python
print("Hello World!")
```

my `launch.json`
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "justMyCode": true,
            "logToFile": true
        }
    ]
}
```

Console oputput
```
$  cd /tmp/reprodebugerror ; /usr/bin/env DEBUGPY_LOG_DIR=/home/barce/.vscode-server/extensions/ms-python.python-2022.16.1 /tmp/reprodebugerror/.venv/bin/python /home/barce/.vscode-server/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher 34067 -- /tmp/reprodebugerror/hello_world.py 
PyInt_FromLong not found.
PyInt_FromLong not found.
PyInt_FromLong not found.
PyInt_FromLong not found.
PyInt_FromLong not found.
PyInt_FromLong not found.
PyInt_FromLong not found.
PyInt_FromLong not found.
Hello World!
PyInt_FromLong not found.
```

[debugpy.adapter-2555.log](https://github.com/microsoft/debugpy/files/9869688/debugpy.adapter-2555.log)
[debugpy.launcher-2563.log](https://github.com/microsoft/debugpy/files/9869689/debugpy.launcher-2563.log)
[debugpy.pydevd.2568.log](https://github.com/microsoft/debugpy/files/9869690/debugpy.pydevd.2568.log)
[debugpy.server-2568.log](https://github.com/microsoft/debugpy/files/9869691/debugpy.server-2568.log)

**Comment by fabioz** [comment]
Thanks for the logs. I'll be able to investigate this properly tomorrow.

**Comment by bcxpro** [comment]
If it helps, I just tried the exact same thing on Windows 11, python 3.11.0 installed  from the Microsoft Store and **it worked OK** without any `PyInt_FromLong not found` message.

[debugpy.server-12764.log](https://github.com/microsoft/debugpy/files/9870600/debugpy.server-12764.log)
[debugpy.adapter-38948.log](https://github.com/microsoft/debugpy/files/9870601/debugpy.adapter-38948.log)
[debugpy.launcher-9620.log](https://github.com/microsoft/debugpy/files/9870603/debugpy.launcher-9620.log)
[debugpy.pydevd.12764.log](https://github.com/microsoft/debugpy/files/9870604/debugpy.pydevd.12764.log)

**Comment by MarcosRolando** [comment]
Having the same problem here, PopOS 22 with Python 3.11 installed

**Comment by alexandr-osprey** [comment]
Same here in pyton dev container. Here is repo, so you could reproduce locally.
https://github.com/alexandr-osprey/linearalgebrastudy

**Comment by fabioz** [comment]
@alexandr-osprey this is already fixed in main.

**Comment by goktugerol-dev** [comment]
I have the same issue when I use Pandas and Jupyter notebook.

**Comment by AlgebraQuant** [comment]
The same here, with Fedora and Python 3.9.

**Comment by goktugerol-dev** [comment]
I had the same issue when I use Pandas and Jupyter notebook on Linux Debian 11 and I solved the issue.

But as far as I see this issue occurs on different occasions.  In my case, it occurred on Jupyter Notebook & Pandas.

Honestly, it is the first time I faced this kind of error when I work with Python but it didn't take a long time to solve it... Maybe temporary, not sure but it doesn't affect me now...

This is how I solved my issue, if anyone had this issue in the same way I had you can try it out.

First of all, I think it would be useful to mention that, Python is not a compiled language, it's an interpreted language (with its unique way of working because it even has some differences from the other interpreted languages.), so it interprets the code line by line, then CPython converts the source code into bytecode and then runs the bytecode on the virtual machine. So, I was getting this error when I work on Jupyter notebook and when I wanted to run only one part of the code. I was getting dozens of repeating `Pyint_FromLong not found` messages.

But when I run the whole code from the beginning, instead of running partially, the error didn't show up. I assume that it probably has something to do with this. 

I also did some research on the internet and it is mentioned here that PyInt is a discontinued project. 
Source: https://snyk.io/advisor/python/pyint
Source2: https://pypi.org/project/pyint/

One more interesting detail here is that both sources show us PyInt as a PyPi library. PyPi uses JIT Compiler and standard Python works on CPython interpreter that has nothing to do with JIT Compiler structure. This might be useful info to find out the reason and fix the issue.

**Comment by jdphenix** [comment]
If you happen to be using VSCode server with remote extensions, you can workaround this in the meantime. I've done this and it seems to work fine. Obviously, no guarantees. 

All commands are executed on the remote system.

1. Find the VSCode Server lib directory for ms-python.python. On my system, it's at `~/.vscode-server/extensions/ms-python.python-2022.18.2/pythonFiles/lib/python`. For saving fingers, 

`export $PYLIB_PATH=$HOME/.vscode-server/extensions/ms-python.python-2022.18.2/pythonFiles/lib/python"

2. Clone debugpy. 

`$ git clone https://github.com/microsoft/debugpy.git ~/.debugpy`

3. Backup the extension's debugpy. 

`$ tar cf ~/.debugpy.bak.tar $PYLIB_PATH`

4. Copy the debugpy repository code to extension. 

```bash
$ rm -rf $PYLIB_PATH/debugpy && \
cp -R ~/.debugpy/src $PYLIB_PATH/debugpy
```

Obviously this is hacky. Works for me though! Thank you @fabioz!

**Comment by nszceta** [comment]
@jdphenix I made a trivial update to your suggestion. Pasting this block in a Linux terminal on the current VSCode should seamlessly fix the issue in one shot. I'm on Python 3.11.1.

```
git clone --depth 1 https://github.com/microsoft/debugpy.git ~/.debugpy
rm -rf ~/.vscode/extensions/ms-python.python-2022.20.1/pythonFiles/lib/python/debugpy/
mv -v ~/.debugpy/src/debugpy/ ~/.vscode/extensions/ms-python.python-2022.20.1/pythonFiles/lib/python
rm -rf ~/.debugpy
```

Reference: https://adamgradzki.com/visual-studio-code-fix-for-python-311-debugging.html

**Comment by jtele2** [comment]
> @jdphenix I made a trivial update to your suggestion. Pasting this block in a Linux terminal on the current VSCode should seamlessly fix the issue in one shot. I'm on Python 3.11.1.
> 
> ```
> git clone --depth 1 https://github.com/microsoft/debugpy.git ~/.debugpy
> rm -rf ~/.vscode/extensions/ms-python.python-2022.20.1/pythonFiles/lib/python/debugpy/
> mv -v ~/.debugpy/src/debugpy/ ~/.vscode/extensions/ms-python.python-2022.20.1/pythonFiles/lib/python
> rm -rf ~/.debugpy
> ```
> 
> Reference: https://adamgradzki.com/visual-studio-code-fix-for-python-311-debugging.html

Had to change the `.vscode` to `.vscode-server`. It worked, but now it's telling me to "[Switch] over from `ptvsd` to `debugpy`"

**Comment by sergei3000** [comment]
I'm still hitting this with Python 3.11 on Linux and with the latest vscode installation

**Comment by Corfucinas** [comment]
Same here, no changes since I opened the issue
