### ISSUE TITLE
Have to step multiple times when "stepping in" with justMyCode=true

### ISSUE THREAD

**Issue by roblourens** [microsoft/debugpy#1104]
Before creating a new issue, please check the [FAQ](https://github.com/microsoft/debugpy/wiki/FAQ) to see if your question is answered there.

## Environment data

- debugpy version: 1.6.3
- OS and version: macOS
- Python version (& distribution if applicable, e.g. Anaconda): 3.9.5
- Using VS Code or Visual Studio: VS Code

From https://github.com/microsoft/vscode-jupyter/issues/11774

*  "jupyter.debugJustMyCode": true,
* use the snippet below
* press step into on line 5
* :bug: you need to press step into a couple of times before it resumes on the next line

```py
import ipywidgets as widgets

print(12)

a = widgets.IntSlider(description='a')
a

```

@fabioz I assume this comes from the way ipython executes code one line at a time- is it possible for a single "step in" to advance to the next line when justMyCode is enabled, the same way it does when debugging a normal python script?

Lmk if you want debugpy logs for this, I'd be happy to grab them.

**Comment by fabioz** [comment]
I can reproduce this. It's the same issue related to IPython because each new line is a completely new frame.

I'll have to investigate how to improve this on the step in (but I have some other issues I'll need to tackle first).

**Comment by roblourens** [comment]
Actually this isn't just about what happens when a user uses "step in" while debugging, this is almost a deal breaker for vscode's "run by line" experience. We give users one button to step through all the code in their cell, and so we always issue a stepIn. So now if they use RBL on a cell with print statements, they are stuck clicking multiple times to progress. Can you think of any workaround for us?

**Comment by roblourens** [comment]
To be clear, this only happens when `PYDEVD_IPYTHON_COMPATIBLE_DEBUGGING = '1';` is set. If we can't get a workaround here, we probably have to back out the change to enable justMyCode in notebooks.

I'm wondering whether it's safe to do a hack like, if the user is using Run By Line and we pause in the exact same position of the last pause, we automatically issue a step-over. Do you think that would be a safe workaround or is there a legit situation where that would happen, like in debugging some kind of loop?

**Comment by fabioz** [comment]
I think that it'd be a reasonable workaround (although maybe doing a step in until it changes the position vs a step over might be better to make sure you don't accidentally go over some code which should've been a step in and not a step over) ... as a note, I'm taking a look at the gevent breakage (which broke debugging in the latest update) and my plan is taking a look at this one afterwards.

**Comment by roblourens** [comment]
Thanks! In a test, it seemed that when I step through a list comprehension, I pause at the same position multiple times, so that might not give perfect results, but might still be an acceptable compromise if needed.

**Comment by fabioz** [comment]
I'll start to take a look at this (note: I'll probably only finish next week).

**Comment by roblourens** [comment]
Thanks for the fix!
