### ISSUE TITLE
still cant debug library even after set justMyCode to false

### ISSUE THREAD

**Issue by zyzhang1130** [microsoft/debugpy#1110]
Before creating a new issue, please check the [FAQ](https://github.com/microsoft/debugpy/wiki/FAQ) to see if your question is answered there.

## Environment data

- debugpy version: 1.5.1
- OS and version: Windows 11 Home 22H2, WSL2 Ubuntu 20.04.5 LTS
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.13, conda 22.9.0
- Using VS Code or Visual Studio: VS Code

## Actual behavior

As the title suggests, I still cant debug library even after setting justMyCode to false. I also followed some suggested answered to add another configuration (as shown below), still not working.

## Expected  behavior

Should be able to debug (pip installed) python library (i.e. stop at the breakpoint in the script in library is there is one)

## Steps to reproduce:
The following is my launch.json:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "justMyCode": false
        },
        {
            "name": "Python: Debug Tests",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "purpose": ["debug-test"],
            "console": "integratedTerminal",
            "justMyCode": false
          }
    ]
}
```

**Comment by fabioz** [comment]
@zyzhang1130 can you provide the logging when that happens?

See: https://github.com/microsoft/debugpy/wiki/Enable-debugger-logs for details on how to collect the logs.

**Comment by int19h** [comment]
This is a fairly old debugpy version - can you try updating your VSCode?

**Comment by marktodisco** [comment]
How can I update debugpy? I'm also experiencing a similar issue where I cannot step into third-party source code. @int19h

**Comment by marktodisco** [comment]
I upgraded to version **1.6.3** with `python -m pip install --upgrade debugpy`, but I still can't debug.

**Warning Message at Breakpoint**
![image](https://user-images.githubusercontent.com/36463460/201160265-815f3dad-423c-4c3f-b440-1150fed78182.png)

`launch.json`
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "justMyCode": false
        }
    ]
}
```

**Comment by fabioz** [comment]
@marktodisco can you provide the logs when that happens?

See: https://github.com/microsoft/debugpy/wiki/Enable-debugger-logs for details on how to collect the logs.

**Comment by int19h** [comment]
`pip install` upgrades your global debugpy installation, but that is only used when you do `import debugpy` or `python -m debugpy`. VSCode Python extension bundles its own copy of debugpy, and that's the one that gets used when you use VSCode to run & debug your app; you can update it if you want, but it's really meant to be updated along with the extension.

**Comment by marktodisco** [comment]
> @marktodisco can you provide the logs when that happens?
> 
> See: https://github.com/microsoft/debugpy/wiki/Enable-debugger-logs for details on how to collect the logs.

I've followed the instructions to enable the logs, but I'm not sure what files you need. Could you please help me find the correct logs? @fabioz

**Comment by fabioz** [comment]
> > @marktodisco can you provide the logs when that happens?
> > See: https://github.com/microsoft/debugpy/wiki/Enable-debugger-logs for details on how to collect the logs.
> 
> I've followed the instructions to enable the logs, but I'm not sure what files you need. Could you please help me find the correct logs? @fabioz

Well, it should've generated a few log files (one from the adapter, server and pydevd). Ideally you could attach them all, but the most important for this case is the one related to pydevd.

**Comment by marktodisco** [comment]
I could only get the files to generate using the CLI instructions. Also, the pydev log file appears to be missing.

[debugpy.server-29990.log](https://github.com/microsoft/debugpy/files/9983599/debugpy.server-29990.log)
[debugpy.adapter-29994.log](https://github.com/microsoft/debugpy/files/9983600/debugpy.adapter-29994.log)

**Comment by fabioz** [comment]
Humm, the pydevd file would be the most important here, but even those logs seem to be very reduced (i.e.: I can't see the breakpoints being set in them).

Let's try to get the logs from pydevd first:

Another option is setting the following environment variables and running with those set:

```
PYDEVD_DEBUG_FILE=/path/to/pydevd.log
PYDEVD_DEBUG=1
```

Note: replace `/path/to/pydevd.log` to point to a file in a directory that already exists in your machine.

**Comment by zyzhang1130** [comment]
> This is a fairly old debugpy version - can you try updating your VSCode?

Hi, sorry for the late reply, have been extremely busy. I installed the latest version of VScode on Windows11 and open it in WSL2 with the command `code .`. I tried to update VScode through `Help => Restart to update` and my VScode version now is 1.73.0. But my debugpy version is still 1.5.1. How should I update debugpy in this case?

**Comment by zyzhang1130** [comment]
> @zyzhang1130 can you provide the logging when that happens?
> 
> See: https://github.com/microsoft/debugpy/wiki/Enable-debugger-logs for details on how to collect the logs.
[pydevd.txt](https://github.com/microsoft/debugpy/files/9991003/pydevd.txt)


the attached is my pydevd. There are some successful 'step into'. Those are not installed library. There is one place when I clicked 'step into' then it says 'Frame skipped from debugging during step-in. Note: may have been skipped because of "justMyCode" option (default == true). Try setting "justMyCode": false in the debug configuration (e.g., launch.json).', but I already set justMyCode = False:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "justMyCode": false,
            "logToFile": true,
        }
    ]
}
```

**Comment by fabioz** [comment]
@zyzhang1130 the file you included has the pydevd source code, not really the logs generated...

**Comment by int19h** [comment]
To update debugpy, you need to update the VSCode Python extension - it is separate from VSCode proper.

**Comment by zyzhang1130** [comment]
> To update debugpy, you need to update the VSCode Python extension - it is separate from VSCode proper.

Looks like it is quite up-tp-date (v2022.16.1) and I didn't see any option to further update it:
![image](https://user-images.githubusercontent.com/36942574/201456737-57fc713e-a75c-46dc-8580-29b41abf94b8.png)

**Comment by zyzhang1130** [comment]
> @zyzhang1130 the file you included has the pydevd source code, not really the logs generated...

this is the only file I could find named 'pydevd '. What is the typical name of the logs? There are too many files/directories under `%USERPROFILE%\.vscode\extensions\ms-python.python-*`

**Comment by int19h** [comment]
The files should match the pattern `debugpy*.log`. One of these is something like `debugpy.pydevd....log`

**Comment by marktodisco** [comment]
## Objective

Set a breakpoint in third-party source code (SciPy) and step through code.

## Problem

vscode ignores breakpoint even though my debugging configuration looks correct.

**launch.json**
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "justMyCode": false,
            "logToFile": true
        }
    ]
}
```

![image](https://user-images.githubusercontent.com/36463460/230729981-dd341641-ad6b-402e-b1fe-85fcaaabef19.png)

## How to reproduce issue

**Source code:**

```python
import numpy as np
from scipy.stats import bootstrap

boot = bootstrap(data=[np.random.random(100)], statistic=np.mean)
print(boot)
```

**Breakpoint**

Set a breakpoint in the `boostrap` function.

![image](https://user-images.githubusercontent.com/36463460/230730200-7e48a480-63f1-4271-bffb-bd841346922e.png)

## Log Files

@fabioz, I tried following the instructions to generate pydev log files again, but still cannot produce anything more than the the adapter/server log files.

![image](https://user-images.githubusercontent.com/36463460/230730297-e468f8c6-eb31-4b15-8d32-413f8b9aa64b.png)

## Environment Information

OS: Windows 11
Environment: Miniconda
Python: 3.10.10

| Package | Version |
| - | - |
| certifi | 2022.12.7 |
| numpy | 1.24.2 |
| pip | 23.0.1 |
| scipy | 1.10.1 |
| setuptools | 65.6.3 |
| wheel | 0.38.4 |
| wincertstore | 0.2 |

**Comment by int19h** [comment]
Those logs might still be interesting.
