### ISSUE TITLE
Multiprocess Debugger Fails to Launch

### ISSUE THREAD

**Issue by kelleyjbrady** [microsoft/debugpy#1116]
Type: <b>Bug</b>

# Behavior
When stepping through code with F11, the debugger crashes when it is time to go into the first sub process. The crash is accompanied by a 'standard windows error popup' reading: 'Couldn't find a debug adaptor descriptor for debug type 'Python Kernel Debug Adapter' (extension may have failed to activate). The popup is generated for each of the threads launched by Joblib. Each of the popups is accompanied by a 'VSCode style red X' error that says 'Failed to launch debugger for child process ______' with the ______ filled in with a large integer. 

I submitted this bug using the pre-release version of the extension, but this is also happing for me on the current release -- I switched to the prerelease to see if that could resolve the issue. 

## Expected vs. Actual
The debugger should launch
vs
The debugger does not launch

## Steps to reproduce:

1. Write some code that parallelizes a task with Joblib running in 'loky' mode. 
2. Place a breakpoint before the the parallel code starts
3. Run the debugger
4. When the debugger stops on your breakpoint, use F11 to attempt to step into one of the sub processes. 
5. The debugger will fail. 

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.12
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Conda
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```
Multiroot scenario, following user settings may not apply:

languageServer: "Pylance"

```

</p>
</details>

Extension version: 2022.12.1
VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)
OS version: Windows_NT x64 10.0.19044
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10900X CPU @ 3.70GHz (20 x 3696)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|127.68GB (114.95GB free)|
|Process Argv|--crash-reporter-id e8819f4f-f4c0-4dbe-aec2-6040aa6dcc5d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
i497e931:30552240

```

</details>

**Comment by int19h** [comment]
Does it happen if you run the same code as a plain Python script or module, outside of any notebook?

**Comment by kelleyjbrady** [comment]
Nope, debugging the parallel code works fine in a .py file. I noticed today that, when the issue occurs in a notebook, the debugger becomes stuck in the broken state induced by the multiprocessing.  

## 1) Run this first. No Bug w/ no `Parallel`
``` python
from joblib import Parallel, delayed

def my_adder(val_in):
    val_out = val_in + 1 #put debugger flag here
    return val_out

#this will debug
res = []
for i in range(10):
    res.append(my_adder(i))
    
print(res)
```

## 2) Run this second. Bug with `Parallel`
``` python
from joblib import Parallel, delayed

def my_adder(val_in):
    val_out = val_in + 1 #put debugger flag here
    return val_out

#this will not debug
res = Parallel(n_jobs=-1)(delayed(my_adder)(i) for i in range(10))
    
print(res)
```

## 3) Run this third. Now `Parallel` now has Bug
```python
from joblib import Parallel, delayed

def my_adder(val_in):
    val_out = val_in + 1 #put debugger flag here
    return val_out

#this will now generate the same bug
res = []
for i in range(10):
    res.append(my_adder(i))
    
print(res)
```

**Comment by roblourens** [comment]
I just recently realized that this is not supported - we need to do some work here https://github.com/microsoft/vscode-jupyter/issues/9886.

So this is a custom event sent to the client, and presumably we just need to call startDebugging to handle it, right?

**Comment by roblourens** [comment]
Well I will look at how vscode-python handles it.

**Comment by int19h** [comment]
It's a custom event, but the body is a premade "attach" request that can be used as is. The only catch is that you need to specify the correct parent session for it when passing it to VSCode, to ensure that processes are correctly rendered as a tree. Here's the code that handles it in vscode-python:

https://github.com/microsoft/vscode-python/blob/96927c73734722509252d40872ba74bc8d5dcb8b/src/client/debugger/extension/hooks/childProcessAttachHandler.ts

I think that in your case, you might also need to rewrite "type" - debugpy generates that event by taking the original "launch" or "attach" request that was used to start the session, rewriting it into "attach" if it wasn't that already, and adding the parent process ID as a property. So if your original request had "type" set to something other than "python", it will be the same in the event; it looks like this is where it might be breaking up.

It should be noted that [VSCode recently added support for a new DAP request](https://github.com/microsoft/vscode-docs/blob/dd1aaea4c417ac1b0de6894dab66c24587a05089/release-notes/v1_73.md#new-startdebugging-reverse-request) that serves the same function. We haven't migrated debugpy to it yet - https://github.com/microsoft/debugpy/issues/1074 tracks that. When it's implemented, debugpy will use the standard DAP request if the client sets "supportsStartDebuggingRequest", but we'll continue supporting "debugpyAttach" event for backwards compatibility.

**Comment by int19h** [comment]
I'm going to close this issue since there's one tracking this work in the vscode-jupyter repo.
