### ISSUE TITLE
Support for hot-reloading buggy function after raising exception, preserving context, stepping in/out of exception

### ISSUE THREAD

**Issue by James4Ever0** [microsoft/debugpy#1119]
Debugpy is able to capture 'raised exception' and preserve context. However what I want to do is to modify the code, fix the bug, reload the buggy function and continue execution, which is similar to #212, also [mentioned in reloadium](https://github.com/reloadware/reloadium/issues/61).

I have achieved similar capabilities with [my modified version of reloading](https://github.com/James4Ever0/reloading) to deal with the following code:

```python
from reloading import reloading
import asyncio


@reloading
class mClass:
    someValue = 2

    @reloading
    def someMethod(self):
        @reloading
        def someInnerMethod():
            raise Exception("inner exception")
            return "inside function return"
        raise Exception("exception")
        val = someInnerMethod()
        return val

    @reloading
    async def someOtherMethod(self):
        @reloading
        async def asyncInside():
            raise Exception("inner async exception")
            return "async inside return"
        raise Exception('async exception')
        val = await asyncInside()
        return val

    @reloading
    def runAsync(self):
        loop = asyncio.get_event_loop()
        val = loop.run_until_complete(self.someOtherMethod())
        print("value from async func:", val)
        return val


@reloading
def main():
    MClass = mClass
    print(MClass)
    val = MClass.someMethod()
    print("return value:", val)
    val = MClass.runAsync()
    print("return async value:", val)
    print("success!")


main()

```

Similar tools:

[jurigged](https://github.com/breuleux/jurigged/)
[reloadium](https://github.com/reloadware/reloadium)

**Comment by fabioz** [comment]
There is already support for hot-reloading in the debugger.

To enable it, you need to add: `"autoReload": { "enable": true },` to your launch config (this will make it start tracking for changes in the filesystem to apply the hot reloading).

Note that it'll track changes in files in your current dir as well as based on the `program` specified, but you can also customize what's to be tracked through `watchDirectories`,  `exclude` and `include` in the `autoReload`.

It's interesting to note that it'll patch the code objects but the current frame being executed won't be affected (you need to exit the frame and call the function again for it to see the change).

Reloading is never perfect though (you may want to check https://github.com/microsoft/debugpy/blob/main/src/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_reload.py for some details on how it works and how to participate/customize the reloading if you want through `__xreload_old_new__` and `__xreload_after_reload_update__` and check its limitations).
