### ISSUE TITLE
Debugger crashes randomly during stepover or stepin with breakpoint

### ISSUE THREAD

**Issue by rADikal8e7** [microsoft/debugpy#112]
## Environment data

- PTVSD version: ms-python.python Version: 2020.3.71659
- OS and version: Darwin x64 19.4.0
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.1
- Using VS Code or Visual Studio: VS code
Version: 1.44.0-insider
Commit: e8dbc5ea6092ba73ae70069d3e730f2cc56addff
Date: 2020-04-03T22:09:44.908Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
- Remote - Containers : ms-vscode-remote.remote-containers Version: 0.111.0

## Actual behavior
Please note all the below actions are being done when attaching to remote container.

- After the auto update of python extension to **2020.3.71659** remote debugger crashes randomly.

- When using breakpoint to pause and using stepover or stepinto sometimes the debugger randomly crashes and asks to reload the window causing lose of script execution.

<img width="422" alt="image" src="https://user-images.githubusercontent.com/6048537/78709961-61a22f80-78c9-11ea-9469-8cf76c00c312.png">

- Also after the crash and the subsequent reload` top `shows that ms.python is using up ridiculous amount of CPU utilzilation.

<img width="814" alt="image" src="https://user-images.githubusercontent.com/6048537/78710584-6ca98f80-78ca-11ea-9301-132b9eba5788.png">

- This goes down after a few minutes.

- These actions used to work perfectly fine with the same code base and ms.python **2020.3.69010** in the same env (remote container).

- Only changes done to vscode are the auto update of python extension and installation of gitlens extension **Version: 10.2.1** on local and remote.

## Expected  behavior

Using breakpoint stepover or stepinto should not crash the debugger.

## Steps to reproduce:

1. Load the current stable python extension **2020.3.71659** and the gitlens extension to remote container.
2. Attach to said remote container and execute any python script which uses multiprocessing module.
3. Pause in a code block and perform stepinto and stepover while there are subprocesses running in the vs code.
4. Click the stepover or stepinto icon 2 or 3 times in quick succession and the debugger appears to hang for a min before throwing the reload window error.
5. Also i see the following error on the console when the crash occurs.
<img width="1205" alt="image" src="https://user-images.githubusercontent.com/6048537/78749206-a4442600-7922-11ea-8856-25ec1a26a2a1.png">

Let me know what additional logs can be presented to debug this further for root cause.

**Comment by rADikal8e7** [comment]
> Same story here - an "evaluate" immediately after resuming execution:
> 
> ```
> D+00356.346: Client[1] --> {
>                  "seq": 104,
>                  "type": "request",
>                  "command": "continue",
>                  "arguments": {
>                      "threadId": 1
>                  }
>              }
> 
> D+00356.348: Client[1] --> {
>                  "seq": 105,
>                  "type": "request",
>                  "command": "evaluate",
>                  "arguments": {
>                      "expression": "self.route_map_config_dict",
>                      "frameId": 2,
>                      "context": "hover"
>                  }
>              }
> 
> ...
> 
> D+00356.352: /handling microsoft/ptvsd#102 request "next" from Client[1]/
>              Client[1] <-- {
>                  "seq": 1469,
>                  "type": "response",
>                  "request_seq": 102,
>                  "success": true,
>                  "command": "next"
>              }
> 
> ...
> 
> D+00356.420: /handling microsoft/ptvsd#105 request "evaluate" from Client[1]/
>              Client[1] <-- {
>                  "seq": 1473,
>                  "type": "response",
>                  "request_seq": 105,
>                  "success": false,
>                  "command": "evaluate",
>                  "message": "Unable to find thread for evaluation."
>              }
> 
> ...
> 
> D+00390.654: Exiting message loop for channel Client[1]: [Errno 104] Connection reset by peer
> ```
> 
> But at least it's clearer here that it the socket is really getting closed from the other side.
> 
> If I'm understanding everything correctly, this all works fine _in the same container_ if you use Remote - SSH to debug inside it rather than Remote - Containers?

Not in the same container... i am using `remote-ssh `extension for a different server which doenst use container and has the old py2 env.

To connect to containers(that run on a different server) i use `remote-container` extension.

I see that you transferred this issue. Let me check with the remote-extension team.

Thanks for the help everyone.

**Comment by int19h** [comment]
It's moved to the debugpy repo, which is the new name for ptvsd, more or less. This is just so that it's easier to track, but for now we're still tracking it as a debugger bug - I just looped in the remote extension in case they can clarify anything here, or confirm that it's likely another manifestation of some issue that they're aware of.

**Comment by rADikal8e7** [comment]
@roblourens let me know if additional logs are required.

**Comment by rADikal8e7** [comment]
@int19h any update on this??

I have completely moved away `ms-vscode-remote.remote-containers` 

Setup a venv and using 'ms-vscode-remote.remote-ssh' ext and still hit this issue frequently if i go more than 5 stepovers in succession using debugger.
Entire vscode crashes and asks for a reload making the debugger unusable for my scenario.
<img width="1004" alt="Screen Shot 2020-05-01 at 10 00 03 PM" src="https://user-images.githubusercontent.com/6048537/80855575-1ee92400-8bf7-11ea-9e28-5674767f4be2.png">

Willing to try any workarounds that you can think off at this point.

**Comment by rADikal8e7** [comment]
Very similar symptoms to https://github.com/microsoft/vscode-remote-release/issues/1257

**Comment by int19h** [comment]
I'm afraid there isn't much we can do about this from the debugger side - it's blissfully unaware of whether it's running in a remote SSH session or not, and based on all the information you have provided, the cause of the problem is external. I think it would be best to file an issue on the Remote SSH extension, and link this one from there so that they can see the preliminary analysis above.
