### ISSUE TITLE
Python Debug in internalConsole doesn't work with setting cwd

### ISSUE THREAD

**Issue by matthieuheitz** [microsoft/debugpy#1120]
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

I am debugging a python file that is in a subfolder of the root folder of the project: 
```
midterm
|- scans-and-canvas-upload
   |- push-to-canvas.py
```
So to debug this script, I have to add the following option to `launch.json`:
`"cwd": "scans-and-canvas-upload",`
When I'm debugging with the option `"console": "integratedTerminal"`, it works fine.
However, when I'm debugging with the option `"console": "internalConsole"`, I get the following error:
> Failed to spawn launcher: [Errno 2] No such file or directory: 'scans-and-canvas-upload'.
And I can either Cancel or Open 'launch.json'.

I feel like there must be a bug where having a custom cwd is not compatible with the internalConsole. I have looked online but couldn't find a similar issue.
Is there additional configuration that I need to add when I'm using the internalConsole?

Thank you!

**EDIT**

Actually now, running with `integratedTerminal` doesn't work anymore...

I get:
> The terminal process failed to launch: Starting directory (cwd) "scans-and-canvas-upload" does not exist.

Although the folder really does exist.
![Screenshot from 2022-11-05 13-32-27](https://user-images.githubusercontent.com/2835332/200140183-4d4a1985-245b-4c86-9755-213baec2b76f.png)

Here is my `launch.json`:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "push-to-canvas.py",
            "type": "python",
            "request": "launch",
            "cwd": "scans-and-canvas-upload",
            "program": "push-to-canvas.py",
            // "console": "internalConsole",
            "console": "integratedTerminal",
            "justMyCode": true,
            "args": [
                "--dry-run",
            ]
        }
        ]
    }
```

## Steps to reproduce:

1. See above

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.10
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Global
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

```

</p>
</details>

Extension version: 2022.18.2
VS Code version: Code 1.73.0 (8fa188b2b301d36553cbc9ce1b0a146ccb93351f, 2022-11-01T15:44:09.336Z)
OS version: Linux x64 5.15.0-52-generic
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3950X 16-Core Processor (32 x 2200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|0, 0, 0|
|Memory (System)|62.74GB (43.35GB free)|
|Process Argv|--unity-launch --crash-reporter-id e424459f-456d-4d84-918e-444764c154ef|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
fc301958:30595537
2e4cg342:30602488
gswce2:30605431
3d0df643:30604793
dbltrim-noruby:30604474
89544117:30607850

```

</details>

**Comment by fabioz** [comment]
You need to specify a full path there.

i.e.: `"${workspaceFolder}/scans-and-canvas-upload",`
