### ISSUE TITLE
`del` doesn't delete object and `x = None` doesn't create `None` object

### ISSUE THREAD

**Issue by rcasero** [microsoft/debugpy#1138]
Before creating a new issue, please check the [FAQ](https://github.com/microsoft/debugpy/wiki/FAQ) to see if your question is answered there.

## Environment data

- debugpy version: 1.6.3 (run `import debugpy; print(debugpy.__version__)` if uncertain)
- OS and version: MacOS X Ventura 13.0.1
- Python version (& distribution if applicable, e.g. Anaconda): 3.8.13, miniconda 3
- Using VS Code or Visual Studio: VS Code Version: 1.73.1 (Universal)

## Actual behavior

In Debug Console

* `del x` is ignored.
* `x = None` doesn't create an object.

## Expected  behavior

* `del x` should delete the object.
* `x = None` should create an object with `None` value.

## Steps to reproduce:
1. Create dummy script with just
    ```python
    import sys
    ```
    and place a breakpoint on that line
2. Start debugging session using remote -SSH extension on server running Linux CentOS Stream 8, with Microsoft Python extension and following `launch.json`. The script 
    ```json
    {
        "version": "0.2.0",
        "configurations": [
            {
                "name":       "Python: Current File",
                "type":       "python",
                "request":    "launch",
                "cwd":        "${workspaceFolder}/bin",
                "program":    "${file}",
                "console":    "integratedTerminal",
                "redirectOutput": true,
                "justMyCode": true,
                "env": {"PYDEVD_WARN_SLOW_RESOLVE_TIMEOUT": "2"}
            }
        ]
    }
    ```
3. Go to Debug Console
4. Create variable `x=5`
5. Print variable `print(x)`. This shows `5`
6. Delete variable `del x`. 
7. Print deleted variable `print(x)`. This still shows `5`. Even after `import gc; gc.collect()`, `x` still exists.
8. Create new variable with `None` value. `y = None`
9. Print new variable `print(y)`. This produces the error
    ```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    NameError: name 'y' is not defined
    ```
10. However, if a previously defined variable is assigned `None`, e.g. `x = None`, then the variable is still defined.

**Comment by int19h** [comment]
The part about assigning to `None` not working is because it happens to hit this check:
https://github.com/microsoft/debugpy/blob/79b7c5634ed5179d193ae563c56ee25dcaed9c30/src/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_save_locals.py#L86-L87

**Comment by fabioz** [comment]
I've just provided a PR for this.

So, it works in the case given, but still, it has caveats in that it's not possible to `del` a var from a variable depending on how it's set (it works for variables you create in the frame during evaluation but may not work for variables already defined in the frame -- this is a CPython limitation).

The example below shows what I mean:

```
import ctypes
import sys

def method():
    A = 10
    return sys._getframe()

frame = method()

del frame.f_locals['A']
ctypes.pythonapi.PyFrame_LocalsToFast(ctypes.py_object(frame), ctypes.c_int(0))

# "A" is still there even though we deleted it...
print(frame.f_locals)
```
