### ISSUE TITLE
Set a variable from a different frame

### ISSUE THREAD

**Issue by brichet** [microsoft/debugpy#1142]
Is there a way to copy a local variable (in a function) to the global scope (module), in order to inspect it after debugging ?

In my experience, sending a `setExpression` request with a global variable as expression does not create a global variable:

```
type: "request",
command: "setExpression",
arguments: {
   expression: "globals()['global_variable']", 
   value: "local_variable", 
   frameId: local_function_frame_id
},
seq: XXX,
```

The above request will create a variable within the frame of the function only. This variable will not be accessible from the frame of the module.

I may have misunderstood how frames and scopes work, I'd be happy to have some clarification if this is the case.

**Comment by int19h** [comment]
Also applies when you do "evaluate" with an equivalent assignment. This is kinda related to https://github.com/microsoft/debugpy/issues/1138 - I believe it's the same code that's responsible for the update. But it also seems to not be updating the real globals dict on purpose, so this restriction might be in place to work around some other limitation; @fabioz, does this sound familiar?

**Comment by fabioz** [comment]
The problem is that `globals()` refers to the globals given at evaluation time which was a dict and not the actual globals from the frame. I've just provided a PR for this.

**Comment by brichet** [comment]
Thanks @fabioz, after a first quick test, it seems to work well.
