### ISSUE TITLE
cannot run debugger 

### ISSUE THREAD

**Issue by samyuan9826** [microsoft/debugpy#115]
## Environment data

- PTVSD version: 4.3.2
- OS and version: Windows 10 18363.720
- Python version (& distribution if applicable, e.g. Anaconda): 3.8.2
- Using VS Code or Visual Studio: VS Code

## Actual behavior

${env:DEBUGPY_LAUNCHER_PORT}='11409'; & 'C:\Users\me\AppData\Local\Programs\Python\Python38\python.exe' 'c:\Users\me\.vscode\extensions\ms-python.python-2020.3.71659\pythonFiles\lib\python\debugpy\no_wheels\debugpy\launcher' '*.py file directory'

## Expected  behavior

Python Debugger on VS Code Runs

## Steps to reproduce:

Start debugger

![Annotation 2020-04-14 014417](https://user-images.githubusercontent.com/33525927/79204740-e0c7c400-7df1-11ea-9a9d-84ffd39df9c5.png)

**Comment by int19h** [comment]
The screenshot looks correct - it should be trying to execute that command line when you start debugging. How exactly does it fail?

**Comment by samyuan9826** [comment]
> The screenshot looks correct - it should be trying to execute that command line when you start debugging. How exactly does it fail?

If that's correct - how am I supposed to start debugging exactly? 

I remember a few years ago - I was able to call the (main) functions on the debug console or so, and  then I could go step by step and see what output/variables in each functions on the left. 

This version of VS Code and Python extension look similar, yet new and different. When I clicked "debug,"  it ran and then nothing happened. And then the terminal would be waiting for a new command. Assuming I am missing/misunderstood something, is it possible to do:

- click/run debugger
- on the debug console
- call functions
- see variables' values step by step

Thanks! Haven't done python for a long time ;/

**Comment by int19h** [comment]
It's correct in a sense that it should be running things in the terminal. The debug session should start after that. This has always been the case, although the command itself changed. If the session did start correctly, you should see the Debug toolbar pop up, however briefly.

Whether the session continues running or not, depends on the app being debugged. Is it some kind of server, or a long-running computation? Or does it just run some code and exit immediately? If it's the latter case, then you should set a breakpoint where you want it to stop, and then you can use the Debug Console and Watch to invoke functions etc.

**Comment by samyuan9826** [comment]
> It's correct in a sense that it should be running things in the terminal. The debug session should start after that. This has always been the case, although the command itself changed. If the session did start correctly, you should see the Debug toolbar pop up, however briefly.
> 
> Whether the session continues running or not, depends on the app being debugged. Is it some kind of server, or a long-running computation? Or does it just run some code and exit immediately? If it's the latter case, then you should set a breakpoint where you want it to stop, and then you can use the Debug Console and Watch to invoke functions etc.

Thanks! Now I understand it a little bit better! I tested it on the server one, and it just ran - I guess the code was fine then. Setting breakpoint did help on another test file - thanks so much!
