### ISSUE TITLE
When using editable_mode=strict, breakpoints only hit for symlinked code in build/**, not original code

### ISSUE THREAD

**Issue by mcrumiller** [microsoft/debugpy#1152]
This is related to microsoft/pylance-release#3473. Let me know if I should open this issue in the vscode-python repository instead of Pylance.

When using editable installs with a pure pyproject.toml installation (i.e. no setup.py available) as per [PEP 660](https://peps.python.org/pep-0660/), installation requires `ediable_mode=strict`:

```shell
pip install -e <package> --config-settings editable_mode=strict
```

This in turn creates a `build/__editable__.<package>-<version>-py3-none-any/<package>/` directory of symbolically linked files to the actual code itself.

In order to activate breakpoints when debugging, breakpoints must be set on the code in the `build/**` directory; breakpoints on the original source code do not activate. This is a bit cumbersome, as the symbolic links are prone to break, which makes working directly on the `build/**` files dangerous: changes made to these files may not be reflected in the actual package code.

## Environment data

-   Language Server version: 2022.12.20 (pyright 621d886b)
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9

## Repro Steps

1. Install a local package in editable mode using `pip install -e . --config-settings editable_mode=strict`.
2. Set a breakpoint in your original code.
3. Run the code in debug mode.

## Expected behavior

Debugger should hit breakpoint.

## Actual behavior

Debugger does not hit breakpoint

**Comment by rchiodo** [comment]
Transferred to debugpy.

My guess is that debugpy can't (or doesn't try to) follow symbolic links when matching up breakpoint paths. 

@int19h do you know if pydevd would use os.path.realpath on files while matching against breakpoint paths?

@mcrumiller As a workaround, I believe you could use this to map paths between the build directory and real folder in your launch.json:

```json
        {
            "name": "Python current file",
            "type": "python",
            "request": "launch",
            "args": [
                "${file}"
            ],
            "pathMappings": [
                {
                    "localRoot": "${workspaceFolder}",
                    "remoteRoot": "build/__editable__.<package>-<version>-py3-none-any/"
                }
            ],
        }
```

There's an example described in the VS code [docs around remote debugging](https://code.visualstudio.com/docs/python/debugging#_remote-script-debugging-with-ssh).

**Comment by fabioz** [comment]
@mcrumiller if you want symlinks resolved, please set the following environment variable in your launch:

`PYDEVD_RESOLVE_SYMLINKS=1`

**Comment by fabioz** [comment]
Actually, the debugger should actually resolve symlinks when matching breakpoints by default (that setting is just so that the match given to the client would also be translated), so, I'll have to investigate more why it's not matching it in this case (a question: are you sure it's a symbolic link and not a hard link?)

**Comment by fabioz** [comment]
As a reference, the code in https://github.com/microsoft/debugpy/blob/v1.6.4/src/debugpy/_vendored/pydevd/pydevd_file_utils.py#L444 does `os.path.realpath` (which should resolve links -- on Windows it should work properly since Python 3.8).

**Comment by fabioz** [comment]
If you open a python shell and do `import os;os.path.realpath(path)` with that `path`, does it resolve the path to the original path or does it keep the same path?

**Comment by mcrumiller** [comment]
@fabioz it reports the separate path for each item:

original path:
```shell
>>> os.path.realpath(r"C:\Projects\project-brr\src\python\brr\fbo_sim.py")
'C:\\Projects\\project-brr\\src\\python\\brr\\fbo_sim.py'
```

linked path:
```shell
>>> os.path.realpath(r"C:\Projects\project-brr\build\__editable__.project_brr-2022.12-py3-none-any\brr\fbo_sim.py")
'C:\\Projects\\project-brr\\build\\__editable__.project_brr-2022.12-py3-none-any\\brr\\fbo_sim.py'
```

**Comment by fabioz** [comment]
Are you sure that's a link at all? If `realpath` cannot resolve it, it's possible that it's just a copy and not a link (in which case the debugger can't do much about it).

If this is the case you need to use the approach using `pathMappings` commented at: https://github.com/microsoft/debugpy/issues/1152#issuecomment-1349179183

**Comment by mcrumiller** [comment]
I tested by altering one file and saving that file: the changes were immediately reflected in the other file.

**Comment by fabioz** [comment]
It's probably a hard link then, but I don't think hard links are resolvable (you have 2 different entries pointing to the same data, but I don't think one can be considered the canonical representation -- you need to delete both to erase the data).

**Comment by mcrumiller** [comment]
Ok; I'll use the `pathMappings` technique. Thanks for your help.
