### ISSUE TITLE
debugpy requires `pathFormat` in initialize request, according to spec it should be optional

### ISSUE THREAD

**Issue by mfussenegger** [microsoft/debugpy#116]
## Environment data

- PTVSD version: debugpy 1.0.0b6
- OS and version: Archlinux; 5.6.4-arch1
- Python version (& distribution if applicable, e.g. Anaconda): 3.8.2
- Using VS Code or Visual Studio: Neither, trying to develop a DAP plugin for Neovim

## Actual behavior

Sending a minimal initialize request:

```
arguments = {
  adapterID = "neovim",
  clientId = "neovim",
  clientname = "neovim",
  locale = "UTF-8"
},
command = "initialize",
seq = 0,
type = "request"
}
```

Results in the following response:

```
{
  command = "initialize",
  message = "Invalid message: \"pathFormat\" must be one of: ['path']",
  request_seq = 0,
  seq = 3,
  success = false,
  type = "response"
}
```

## Expected  behavior

A success or some other error.

According to the [specification](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Initialize), `pathFormat` is optional:

```
  /**
   * Determines in what format paths are specified. The default is 'path', which is the native format.
   * Values: 'path', 'uri', etc.
   */
  pathFormat?: string;
```

**Comment by int19h** [comment]
Thank you for reporting it. It's always good to see more DAP clients!

If you don't mind me asking - is it a fork of Vimspector, or an independent implementation?

**Comment by mfussenegger** [comment]
> If you don't mind me asking - is it a fork of Vimspector, or an independent implementation?

An independent implementation. Not much there yet and I'm not sure how far it will get https://github.com/mfussenegger/nvim-dap
