### ISSUE TITLE
debugger not finding venv locations (the python311.zip problem)

### ISSUE THREAD

**Issue by ManPython** [microsoft/debugpy#1160]
## Environment data

- debugpy version: 1.6.3
- OS and version: W11
- Python version (& distribution if applicable, e.g. Anaconda): 311
- Using VS Code or Visual Studio: 
Version: 1.73.1
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T04:27:29.066Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: No

## Actual behavior

```
Exception has occurred: FileNotFoundError
[WinError 2] Can't find file: 'E:\\Python311\\python311.zip'
  File "E:\Python311\Lib\genericpath.py", line 19, in exists
    os.stat(path)
  File "E:\Python311\Lib\runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "E:\Python311\Lib\runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
```

## Expected  behavior

Debug in normal situation
[debugpy.pydevd.24900.log](https://github.com/microsoft/debugpy/files/10262550/debugpy.pydevd.24900.log)
[debugpy.server-24900.log](https://github.com/microsoft/debugpy/files/10262552/debugpy.server-24900.log)

## Steps to reproduce:
1. It's old well know problem
2. https://github.com/microsoft/debugpy/issues/358
3. https://github.com/microsoft/debugpy/issues/390
4. What I do.. for my VSC portable.. 
`mklink /J "C:\Users\Laptop\AppData\Roaming\Python\Python311\site-packages\" "E:\Python311-venv\Lib\site-packages\"`

In my opinion the problem is to often and related with venv. I have created new venv and all is new instaled and I don't know what is wrong with venvs around VSC and debugpy.
By this I think that user need some configuration for venv in launch.json
`//"envFile": "E:\\Python311-venv\\Scripts\\python.exe",` - like this

```
   {   "name": "Python311-venv Django Debugpy",
   "type": "python",
   "request": "launch",
   "stopOnEntry": false,
   "python": "E:\\Python311-venv\\Scripts\\python.exe",
   "program": "${workspaceRoot}\\django\\manage.py",
   "console": "integratedTerminal",
   "args": ["runserver", "127.0.0.1:8000", "--traceback", "-v", "3"],
   "django": true,
   "subProcess": true,
   "justMyCode":  false,
   "env": {
      "DEBUGPY_LOG_DIR":"C:\\Logs",
      "PYDEVD_DEBUG":"True",
      "PYDEVD_DEBUG_FILE":"C:\\Logs\\pydevd.log"
   },
   "logToFile": true,
   //"envFile": "E:\\Python311-venv\\\\Scripts\\python.exe",
   //"envFile": "${workspaceRoot}\\",
   "debugOptions": [
       "WaitOnAbnormalExit",
       "WaitOnNormalExit",
       "RedirectOutput",
       "DjangoDebugging",
       "ShowReturnValue",
   ]
},
```

**Comment by ManPython** [comment]
Again.. why VSC and Debugpy lookin here something: 
`C:\Users\Laptop\AppData\Roaming\Python\Python311\site-packages\` 
..in case launch.json not configure this. This is point of misunderstanding in whole configurations role in launch.json

**Comment by int19h** [comment]
The debugger doesn't do anything about `python*.zip`. If this shows up, it's due to the configuration of the interpreter itself.

I don't think that this kind of thing:
```
mklink /J "C:\Users\Laptop\AppData\Roaming\Python\Python311\site-packages\" "E:\Python311-venv\Lib\site-packages\"
```
is a supported scenario for venv. 

"envFile" is not related to venvs in any way, but rather to "env" - it's the file from which environment variables are to be read.

**Comment by ManPython** [comment]
Soo.. what is the solution for this case? We using venvs to build env.. then project is in this env.. VSC don't like this.

**Comment by int19h** [comment]
If you create a venv and install packages into it normally, instead of hardlinking site-packages, does it not work?

**Comment by ManPython** [comment]
Not working coz want path as
 `"C:\Users\Laptop\AppData\Roaming\Python\Python311\site-packages\"` 
that is not venv from
 `"python": "E:\\Python311-venv\\Scripts\\python.exe",`
Due this I doink mklink but then next error `python*.zip` ..soo.. wthck? It's not possible then use 2 option as expections from debuger, then it's not debuging but just runing from VSC, and due other problem where VSC can't run corectly django I runing cmd.. but what a tool.. and comfort by this.. Then IntelliJ .. but I don't like this.. want VSC.

In fact other user reporting this, and as You know from my other issues is old problem. How they resolving this or how I should configure this? Or they not using venv or django? Coz in fact I'm using VSC+python ew. QT aps are ok, but not when django.

**Comment by int19h** [comment]
I don't think this is properly supported by Python itself. If you want your site-packages to be under AppData\Roaming, you need to create the entire venv there. 

In any case, what's going on here is actually by design - you've asked to break on raised exceptions, and further set `"justMyCode": false`, meaning that debugger is expected to break every time exception occurs in stdlib. Since `os.path.exists()` is implemented in stdlib as `try..except` around `os.stat()`, there's an exception raised whenever the existence of a non-existing file is checked. If you press F5, it should continue.

**Comment by johnbendi** [comment]
I'm having this same issue. debugpy does not use `python.defaultinterpreterPath` setting when restarting from `os.kill` due to `inotify` restarting the process. It then uses the linked python instead of the one from `python.defaultinterpreterPath` thereby causing missing module issues. How can I correct this issue?

**Comment by johnbendi** [comment]
> I'm having this same issue. debugpy does not use `python.defaultinterpreterPath` setting when restarting from `os.kill` due to `inotify` restarting the process. It then uses the linked python instead of the one from `python.defaultinterpreterPath` thereby causing missing module issues. How can I correct this issue?

**Comment by johnbendi** [comment]
> @int19h I'm having this same issue. debugpy does not use `python.defaultinterpreterPath` setting when restarting from `os.kill` due to `inotify` restarting the process. It then uses the linked python instead of the one from `python.defaultinterpreterPath` thereby causing missing module issues. How can I correct this issue?

I guess another way of putting this issue is to say the debugpy uses the global environment when restarting

**Comment by ManPython** [comment]
> I guess another way of putting this issue is to say the debugpy uses the global environment when restarting
@johnbendi You identified differences after start and restart when debugging and the 1st start? This can be important indication to this issue.. around .pyc cache

**Comment by int19h** [comment]
debugpy doesn't handle restarts and is not aware of other apps that might do so (unless it's a Python process that you're debugging in multiproces mode, and it restarts its own child processes). So in that case, it would be down to how `inotify` was configured.

**Comment by ManPython** [comment]
The issue is solved.. the `"justMyCode": false` was bad setting for me when many profiles with logging.. dam..

**Comment by Baileyswu** [comment]
> The issue is solved.. the `"justMyCode": false` was bad setting for me when many profiles with logging.. dam..

I commented the option as `settings.json`,  then it turns out to be fine.
// "debugpy.debugJustMyCode": false,
