### ISSUE TITLE
Invalid change log record color

### ISSUE THREAD

**Issue by xxc-zsz** [microsoft/debugpy#1161]
I use the following settings to change the logging color of the debug console, but both warn and erro are displayed in green.

***settings.json***
```json
{
    "workbench.colorCustomizations": {
        "[Default Dark+]": {
            "debugConsole.infoForeground": "#ffffff",
            "debugConsole.warningForeground": "#fddf00",
            "debugConsole.errorForeground": "#69ba63",
            "debugConsole.sourceForeground": "#c2c900",

        },
    }
}
```

***launch.json***
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "internalConsole",
            "justMyCode": true
        }
    ]
}
```
***code***
```python
import logging
_logger = logging.getLogger(__name__)

if __name__ == "__main__":
    _logger.warning('Test warning')
    _logger.error('Test error')
```

![image](https://user-images.githubusercontent.com/108051416/208630219-47560431-ab75-4607-b0bf-032d2d68e7e0.png)

In addition, when I use `colorlog`, the log information has not changed. Only the error level names have color changes.

***code***
```python
import logging
from colorlog import ColoredFormatter

formatter = ColoredFormatter(
    fmt="%(log_color)s%(levelname)-8s%(reset)s %(yellow)s%(message)s",
    datefmt=None,
    reset=True,
    log_colors={
        'DEBUG':    'cyan',
        'INFO':     'white',
        'WARNING':  'yellow',
        'ERROR':    'green',
        'CRITICAL': 'red',
    }
)

handler = logging.StreamHandler()
handler.setFormatter(formatter)

logging.getLogger().addHandler(handler)

logging.debug("This is a debug message")
logging.info("This is an info message")
logging.warning("This is a warning message")
logging.error("This is an error message")
logging.critical("This is a critical message")
```

![image](https://user-images.githubusercontent.com/108051416/208630782-3eca46dc-4c2a-4e9a-9e44-3829a25e8171.png)

**Comment by int19h** [comment]
The Debug Console is a generic VSCode facility that is not aware of the Python logging module, and vice versa. Logging output ends up in Debug Console because it goes to stderr by default, and everything in stderr is captured in the console. However, there's no way to know whether the message was logged as "warning" or "error" at this point.

`colorlog` applies its own colorization at the point where the messages are output, which is why it works.
