### ISSUE TITLE
xvfb-run wrapper for debug scripts

### ISSUE THREAD

**Issue by jordan-schneider** [microsoft/debugpy#1163]
I run code on headless servers using vscode-remote. Because the server is headless in order to get these scripts to run at all, I have to wrap them in xvfb-run. Unfortunately, as far as I can tell I cannot specify in a launch.json that I want to launch the debug run inside of a xvfb-run call. Is there a way to do this currently? If not, I would appreciate the feature.

Probably it would be best to make this some general ability to wrap debug commands in outer bash commands, which would e.g. enable you to nice your debug script, or isolate it to one core using taskset.

**Comment by Luoji-0** [comment]
Hi, I also meet the problem, and I find runing command "Xvfb :611 -screen 0 1024x768x16 &" and add "DISPLAY=611" to environment variables before starting dubugging can solve the problem, "611" is the server-num,.
