### ISSUE TITLE
'debug adapter' error in jupyter notebook 

### ISSUE THREAD

**Issue by PeterM18** [microsoft/debugpy#1166]
Type: <b>Bug</b>

ACTUAL BEHAVIOR
When running debug on a particular cell in the notebook below, the debugging halts and an error message appears.
https://github.com/phlippe/uvadlc_notebooks/blob/master/docs/tutorial_notebooks/tutorial5/Inception_ResNet_DenseNet.ipynb

The cell is the one with the first line: imgs, _ = next(iter(train_loader)).  

With a breakpoint on that cell, the debugger stops normally.  I then seek to step to the next line and then the debugger greys out VSCode and shows the following error message:

"Couldn't find a debug adapter descriptor for debug type 'Python Kernel Debug Adapter' (extension might have failed to activate)"

This occurs with multiple instances of the message:  "I also get a "Failed to launch debugger for child process XXX"

I ran the debugger for multiple cells above this cell and had no problems.  I've tried reinstalling and switching to the pre-release versions of both the Python and Jupyter extensions (both Microsoft) and restarting vscode each time.  The error occurs in all cases.  (BTW, I tried to submit this bug report by using 'Python: Report Issue', but I do not have that option.)

EXPECTED BEHAVIOR:
On debugging the cell, after stepping over the first line of code, the debugger should move to the 2nd line of code with no error message.

Extension version: 2022.20.1
VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:27:19.253Z)
OS version: Linux x64 5.10.0-20-amd64
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz (8 x 3247)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|23.44GB (4.06GB free)|
|Process Argv|--unity-launch --crash-reporter-id d556c1c3-5a8d-4575-970a-2b1a16582954|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
3biah626:30602489
gswce1:30612156
iaj6b796:30613358
f6dab269:30613381
fim-prod:30623723
vscup:30628656

```

</details>

**Comment by int19h** [comment]
Jupyter debugger doesn't support debugging subprocesses currently; this is tracked at https://github.com/microsoft/vscode-jupyter/issues/9886

**Comment by PeterM18** [comment]
I'm fuzzy on just what debugging subprocesses entails.  Does that involve splitting the debugger to follow each of the subprocesses?  If so, check out how Eclipse with Pydev handles the kind of multiprocessing code VS Code can't.  It just steps through it as if it were one process.  Maybe not ideal if someone needs to debug interacting threads, but more than covers my, and I suspect many people's, use cases.

**Comment by int19h** [comment]
debugpy itself supports this; it just needs to be wired on Jupyter side of things.

**Comment by PeterM18** [comment]
That's good to know!  Any suggestions on how I could get this to work?

**Comment by int19h** [comment]
I can't think of any obvious workaround here given that you don't get access to the debug config to set `"subProcess": false` to ignore the child processes, unfortunately.  It would require changing the code of vscode-jupyter extension that's referenced in the issue comments there, and then [building your own local version](https://github.com/microsoft/vscode-jupyter/blob/main/CONTRIBUTING.md#local-build) of the extension VSIX with the fix.

**Comment by PeterM18** [comment]
Thanks for letting me know.  Out of my wheelhouse.

**Comment by matthiasgeihs** [comment]
> I can't think of any obvious workaround here given that you don't get access to the debug config to set `"subProcess": false` to ignore the child processes, unfortunately. It would require changing the code of vscode-jupyter extension that's referenced in the issue comments there, and then [building your own local version](https://github.com/microsoft/vscode-jupyter/blob/main/CONTRIBUTING.md#local-build) of the extension VSIX with the fix.

@int19h, any chance debug configurations for cell debugging will be made modifiable in the future?

**Comment by karthiknadig** [comment]
@matthiasgeihs You could make a feature request to provide configurability on the Jupyter extension (https://github.com/microsoft/vscode-jupyter)

/cc @rebornix @DonJayamanne

**Comment by zaheeruddinfaiz** [comment]
[this worked for me](https://github.com/microsoft/debugpy/issues/1168#issuecomment-1377998813)
thanks @int19h

**Comment by milosacimovic** [comment]
zaheeruddinfaiz 's solution no longer works since __init__.py does not contain _config in it

**Comment by cholojuanito** [comment]
> zaheeruddinfaiz 's solution no longer works since **init**.py does not contain _config in it

It's located in `debugpy/server/api.py` like the comment says.

**Comment by imskull** [comment]
Changing `num_workers` to 0 when you are creating DataLoader, it woks for me.

**Comment by asantos-6** [comment]
> Changing `num_workers` to 0 when you are creating DataLoader, it woks for me.

This worked for me, thanks!

**Comment by xlnn** [comment]
Try reinstalling your extension. This is a known error.

**Comment by aa-morgan** [comment]
In case it helps anyone, I found that using `tqdm` triggered this error for me. Removing fixed the error.
python==3.12.10
debugpy== 1.8.14
tqdm==4.67.1
