### ISSUE TITLE
Debugger Not Stopping or Stopping in Random Places

### ISSUE THREAD

**Issue by small-pants** [microsoft/debugpy#1171]
## Environment data

- debugpy version: 1.6.5
- OS and version: MacOS 12.6.1 Monterey and a Vagrant VM running Ubuntu 18.04.5
- Python version: 3.8.1
- Using VS Code or Visual Studio: VS Code

## Actual behavior

My current process:

1. Insert the debugpy macro either above the pytest test definition or at the top level of the code being debugged.
```
import debugpy
debugpy.listen(5678)
debugpy.wait_for_client()
```
2. Insert the `debugpy.breakpoint()` call above the line to stop at _OR_ use the red gutter button to mark a breakpoint.
3. Hit the F5 key when pytest has started and the `collecting...` message appears in the terminal.

If I use the `debugpy.breakpoint()` call to stop at a line, the code will stop however in a seemingly random place. Depending on whether I placed the breakpoint in the pytest or the code being tested, it would stop at a random line inside a file from the pytest library or inside our test database teardown code. This behavior occurs even if Uncaught Exceptions is turned off as a automatic stopping point. In addition, if I use the red gutter button to mark a breakpoint, the debugger will not stop at all.

Downgrading to 1.6.4 resolves these issues entirely. I discovered this only after reinstalling VS Code cleanly and even destroying my Vagrant VM and creating a new one.

## Expected  behavior

The debugger should stop at the line marked by the `debugpy.breakpoint()` call or where a gutter breakpoint has been activated. 

## Steps to reproduce:
1. Upgrade to debugpy 1.6.5
2. Set up VS to use SSH for editing code on a Vagrant VM running Ubuntu.
3. Create some code to be tested and a pytest testing this code.
4. Place either style breakpoint in either the test or the code.
5. Run the test from inside the VM via the terminal.
6. Run the debugger so it attaches to the process.

**Comment by int19h** [comment]
Is it specific to SSH remoting, or does it also reproduce for you in local sessions?

**Comment by small-pants** [comment]
> Also, can you try setting the environment variable `PYDEVD_USE_FRAME_EVAL=0` for the process that's importing debugpy, and see if that makes any difference?

Unfortunately I can't test this in a local session as our code must remain on the VM for security and compliance reasons. However, your environment variable did work to fix one of the simple modules I was testing. 

It does not work for a different module I was testing which consists of a mock call to an API endpoint. The breakpoint only works inside the pytest but not in the endpoint being tested. This used to work in VS and additionally, I was able to do this in PyCharm before I recently converted to VS so it's definitely not our mocking method.

**Comment by int19h** [comment]
When you say "endpoint", does that mean that it's a multiprocess scenario? If so, are you manually attaching to each process separately, or relying on `"subProcess": true` to automate that? I'm wondering if the variable gets propagated correctly to all sides in that scenario.
