### ISSUE TITLE
Make exclude from debugging work for tests

### ISSUE THREAD

**Issue by PhysicistProgs** [microsoft/debugpy#1173]
Now debugpy has undocumented feature according to answer in #1170 : excluding files from debugging, and it works for me.

But how I understand, it doesn't work for unit tests debugging, according to message https://github.com/microsoft/ptvsd/issues/997#issuecomment-475354687. It is the old issue, but I didn't find newer exactly test debug excluding mention. And it doesn't work for me as written in that comment.  

Is there any plan to add this feature?

**Comment by artee2025** [comment]
I faced a similar problem.

**Comment by int19h** [comment]
It should be available, the only question is how you get the debug configuration right. Are you adding it to a [test debug config](https://code.visualstudio.com/docs/python/testing#_debug-tests) with `"purpose": ["debug-test"]`?

**Comment by PhysicistProgs** [comment]
Well,  I then it seemed to me that I added `"purpose": ["debug-test"]`, but I'm not sure.
Last time I tried to put debug configuration with "rules" field to .code-workspace file "launch" section and it didn't work.
Today I tried to put debug configuration to .vscode/launch.json and this worked. 
Didn't expect this difference. Is it ok?

**Comment by karthiknadig** [comment]
@PhysicistProgs That is a known issue see here https://github.com/microsoft/vscode-python/issues/18778
