### ISSUE TITLE
Breakpoint option "Uncaught Exceptions" is activated automatically

### ISSUE THREAD

**Issue by TTSPhilipp** [microsoft/debugpy#1174]
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual
Expected:
If I uncheck the breakpoint option "Uncaught Exceptions", it should remain unchecked even after restarting vs code.
Actual:
The option is always activated again.

## Steps to reproduce:
* start vscode
* Uncheck "Uncaught Exceptions"
* Restart vs code
* Start debugging
*  -> Option is checked again

______________________________________

-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.9
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Poetry
-   Value of the `python.languageServer` setting: Pylance

Extension version: 2022.20.2
VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.64GB (20.53GB free)|
|Process Argv|. --enable-proposed-api genuitecllc.codetogether|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by int19h** [comment]
Debugpy receives this setting in form of exception breakpoints from VSCode anew on every session; it's not aware of UI state and how and whether it's persisted.

**Comment by TTSPhilipp** [comment]
Thanks for the feedback. I have created a new ticket for vs code (https://github.com/microsoft/vscode/issues/172354).
