### ISSUE TITLE
Bizarre Crash when debugging

### ISSUE THREAD

**Issue by theVivern** [microsoft/debugpy#1176]
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual
Expected: For the program to print "Hello" and the debugger to stop at the breakpoint.

Actual: Nothing is printed and the debugging session ends prematurely, without any error message

## Steps to reproduce:

1. Create a file with the following Code

```py
def main():
    foo = 1
    print("Hello")

    if False:
        a = foo

    b = lambda: foo

main()
```

2. Set a breakpoint on the line `print("hello")`
3. Debug the file

# Diagnostic data

-   Python version: 3.10.9 (This is important! Doesn't happen on 3.11)
-   Type of virtual environment used: Happens in poetry as well as without any virtual environment
-   Value of the `python.languageServer` setting: Pylance

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
(No Output)
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

formatting
• provider: "black"

testing
• pytestArgs: "<placeholder>"
• pytestEnabled: true

```

</p>
</details>

Extension version: 2022.20.2
VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:27:19.253Z)
OS version: Linux x64 6.1.5-arch2-1
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 3799)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 1, 0|
|Memory (System)|15.57GB (9.96GB free)|
|Process Argv|--unity-launch --crash-reporter-id 2ce68aea-086f-4541-ab13-10ee2100aeff|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
282f8724:30602487
f6dab269:30613381
fim-prod:30623723

```

</details>

**Comment by int19h** [comment]
I can reproduce. The debuggee process exits with code 245, which is SIGSEGV.

The workaround is to add this to your debug configuration:
```json5
"env": {"PYDEVD_USE_FRAME_EVAL": "0"}
```

(if you use "attach" rather than "launch", you'll need to use the standard facilities of your shell to make sure this variable is set for the debuggee process)

**Comment by judej** [comment]
This will be resolved when we make the optimization will be disabled by default. https://github.com/microsoft/debugpy/pull/1181
