### ISSUE TITLE
Name debug console automatically using launch.json file

### ISSUE THREAD

**Issue by johnbendi** [microsoft/debugpy#1178]
I will like `vscode-python` to adapt `runInTerminal` command to use the name of the debug config from `launch.json` when naming debug terminals. This is already a possible with vscode in general. More info here: https://github.com/microsoft/vscode/issues/128108

**Comment by int19h** [comment]
In the meantime, note that you can use "consoleTitle" in your debug config to set an arbitrary name.

**Comment by johnbendi** [comment]
> In the meantime, note that you can use "consoleTitle" in your debug config to set an arbitrary name.

I'm getting the warning that `consoleTitle` is not allowed in the debug configuration. Is this a recent addition?

**Comment by int19h** [comment]
It's been around for a few years now, but I think it might still not be reflected in the JSON schema that VSCode uses for Python configs - this would result in a warning squiggle in the editor. It should still allow you to start debugging, though, and the setting should work as expected. 

@karthiknadig, given that this feature came up a few times before, should we go ahead and make it official in the docs, schema etc?

**Comment by judej** [comment]
the workaround is to use consoleTitle. closing.
