### ISSUE TITLE
Breakpoint incorrectly triggered

### ISSUE THREAD

**Issue by infinitesteps** [microsoft/debugpy#1180]
## Environment data

- debugpy version: 1.6.0 and 1.6.5
- OS and version: macOS 12.6
- Python version: 3.10.5 and 3.10.9
- Using VS Code or Visual Studio: VS Code

## Actual behavior

1. Set a breakpoint on line 3
2. Debug
3. When breakpoint triggered, i is equal to 0 not 3

```python
for i in range(17):
    if i == 3:
        assert True
```

## Expected  behavior

When breakpoint on line 3 is triggered, i is equal to 3

## Workarounds

- Python 3.8.9 and Python 3.11.1 do not have this problem
- Adding statements at next level of nesting avoids the problem

   ```python
   for i in range(17):
       if i == 3:
           assert True
       assert True
   ```

**Comment by int19h** [comment]
Assuming that this is a "launch" debug configuration, if you do this in your launch.json, does the problem go away?
```json5
"env": {"PYDEVD_USE_FRAME_EVAL": "0"}
```

**Comment by int19h** [comment]
Thank you for confirming! https://github.com/microsoft/debugpy/pull/1181 will fix this issue once it ships.
