### ISSUE TITLE
Python Debugger don't stop on breakpoint, v2022.18.2 works

### ISSUE THREAD

**Issue by mikeseven** [microsoft/debugpy#1194]
Type: <b>Bug</b>

using latest version of vscode and extensions for python, on macos latest OS version, macbook pro x86
Breakpoints don't stop especially on inner functions.
Had to revert Microsoft Python extension to v2022.18.2, all others after don't work.

Extension version: 2022.18.2
VS Code version: Code 1.74.3 (Universal) (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T17:07:18.579Z)
OS version: Darwin x64 22.3.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 4|
|Memory (System)|64.00GB (39.68GB free)|
|Process Argv|--crash-reporter-id 96848e6a-87e6-423e-aaa9-74c48fe44cb8|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30577860
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30647091
89544117:30613380
a9j8j154:30646983

```

</details>

**Comment by int19h** [comment]
Most likely, this is a known issue with optimizations that is already fixed in the most recent debugpy release, but the fix is not in stable vscode-python builds yet. Can you try setting environment variable `PYDEVD_USE_FRAME_EVAL=no` and see if that helps?

**Comment by int19h** [comment]
Closing since it's likely fixed now that VSCode is shipping the new debugpy bits; let me know if it comes up again.
