### ISSUE TITLE
Debugpy not catching at breakpoints

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/debugpy#1195]
## Environment data

- debugpy version:  "1.6.3"
- OS and version: Mac Apple M1 Pro, Ventura 13.1
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.10.8
- Using VS Code or Visual Studio: VS Code

## Steps to reproduce:
1. I am using a local version of the python extension for VS Code and trying to set breakpoints in this flow.
2. I have a main typescript file that will call a python file. The typescript file does so just by creating a server and executing a python command with a set of args (therefore the typescript is not relevant as this could be run from the command line as well)
3. This python file is also an `__init__.py` file and during execution is used as a module in the command
4. Import debugpy and add both a breakpoint via debugpy.breakpoint() and through adding one in the gutter of VS Code
5. Run the application and use a listener to listen for debugpy 
6. The program stops on the python file, ie the entire program does not continue, but debugpy does display breakpoints or the UI to step through them
7. kill the listener and the program continues on and is no longer stuck in the python file

Logs
[debugpy.pydevd.77904.log](https://github.com/microsoft/debugpy/files/10540381/debugpy.pydevd.77904.log)

**Comment by eleanorjboyd** [comment]
tagging @karthiknadig so he can keep up with this issue

**Comment by int19h** [comment]
@eleanorjboyd If this is debugpy 1.6.3, can you try it on the most recent version (1.6.6)? I wonder if you are hitting https://github.com/microsoft/debugpy/issues/1031 somehow...

**Comment by eleanorjboyd** [comment]
That was the fix! I am hitting the breakpoints now!
