### ISSUE TITLE
Jupyter: Run Current File in Python Interactive Window` disappears as an option in Jupyter notebook

### ISSUE THREAD

**Issue by dokutoshi** [microsoft/debugpy#1197]
> There's no way to 'debug' the current selection, but you can debug the entire python file with 'Jupyter: Debug current file in Interactive Window'.
> 
> ![image](https://user-images.githubusercontent.com/19672699/182460163-8e668e7d-ac1c-45c0-b107-867d2d3d162c.png)
> 
> Debug current cell requires the cell markers be available, but the Debug current file will just load the entire python file as a single cell and let you step over it one line at a time.

Any reason that the `Debug Current File in Interactive Window` or `Jupyter: Run Current File in Python Interactive Window` disappears as an option in Jupyter notebook?

_Originally posted by @dokutoshi in https://github.com/microsoft/debugpy/issues/997#issuecomment-1409669543_

**Comment by dokutoshi** [comment]
> See my other response, but notebooks have their own way to debug: https://code.visualstudio.com/docs/datascience/jupyter-notebooks#_debug-a-jupyter-notebook

@rchiodo Related to the following:  There is a inconsistent behavior in Code's Jupyter debug feature.  One pattern i have noticed relates to the virtual environment.  Conda appears to be more reliable while venv normally  on an  AWS Linux, as an example, cannot initiate debugpy for some reason.

https://github.com/microsoft/vscode-jupyter/issues/12871

**Comment by rchiodo** [comment]
Rob should respond in the bug you logged, but one thing that would probably help is if you included the log output. There should be something indicating an error there.

**Comment by dokutoshi** [comment]
> Rob should respond in the bug you logged, but one thing that would probably help is if you included the log output. There should be something indicating an error there.
Let me share environment info there.
