### ISSUE TITLE
python file name case changed won't reflect on "Run without debugging"

### ISSUE THREAD

**Issue by zoo-k** [microsoft/debugpy#1205]
Type: <b>Bug</b>

**short description:**
	After changing the case of the name of a python file, the run command(F4) will still be using the old file name.

**steps to reproduce:**
	1. create a file "A.py" in vscode's file explorer.
	2. rename it to "a.py" in vscode's file explorer.
	3. open it and call command "Run without debuging" (F4 as default)
	4. in the terminal, you will see "A.py" in cmdLine, instead of "a.py"

**expected results:**
	"a.py" in step 4

**when is this issue noticable:**
	when using attribute \_\_file\_\_ in your \_\_main\_\_ script, the \_\_file\_\_ will be in the wrong case as the cmdLine is.

**picture:**
![a-and-A](https://user-images.githubusercontent.com/83531237/210128863-acabb409-75af-417c-9bd7-a47a0e362d67.png)
runnig 'a.py', get 'A.py'

Extension version: 2022.20.1
VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:29:14.590Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3337U CPU @ 1.80GHz (4 x 1796)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|

|Load (avg)|undefined|
|Memory (System)|7.87GB (3.68GB free)|
|Process Argv|C:\\Users\\zoo_k\\Desktop\\my\\projects\\keyboard\\cleaner\\cleaner.code-workspace --crash-reporter-id 1ad8c237-5d97-472a-a31e-bdd660e90514|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1:30587005
2e4cg342:30602488
3d0df643:30613357
f6dab269:30613381
fim-prod:30623723
vscsbc:30628655

```

</details>

**Comment by int19h** [comment]
The filename that shows up in the terminal is the same one that comes from the debug configuration (`"program": "..."`) in launch.json, used as-is. Can you share the active config when this problem occurs?
