### ISSUE TITLE
1.6.6 behaviour on Python 3.10 differs from that on 3.9 or 3.11

### ISSUE THREAD

**Issue by krassowski** [microsoft/debugpy#1208]
## Environment data

- debugpy version: 1.6.6
- OS and version: Ubuntu 20.04.5 LTS (runner version 2.301.1)
- Python version: 3.10 (CPython 3.10.9 from actions/setup-python@v4)
- Using VS Code or Visual Studio: No

## Actual behavior

Since https://github.com/microsoft/debugpy/pull/1181 disabled frame evaluation (`PYDEVD_USE_FRAME_EVAL`) we noticed failures on CI with Python 3.10 (https://github.com/jupyterlab/jupyterlab/issues/13903). Forcing `PYDEVD_USE_FRAME_EVAL` back to `yes` fixed the issues. Changing Python version to 3.9 or 3.11 also resulted in CI tests passing (https://github.com/jupyterlab/jupyterlab/issues/13903#issuecomment-1419458407 and https://github.com/jupyterlab/jupyterlab/pull/13941).

As for the test failures some of them are concerning but I don't know enough about the debugger to say if those are bugs or just different behaviours (mostly related to the breakpoint being set at lines other than expected).

If this is not a bug, please treat this as a friendly heads-up to highlight divergent behaviour between Python versions.

## Expected  behavior

Debugging behaves consistently across Python versions.

## Steps to reproduce:

The failing tests tests are in [debugger/test/session.spec.ts](https://github.com/jupyterlab/jupyterlab/blob/cb26f15084af61ec112c46c0246f4e0118be5f2b/packages/debugger/test/session.spec.ts) and the failing tests are highlighted in https://github.com/jupyterlab/jupyterlab/issues/13903#issuecomment-1412673120

**Comment by int19h** [comment]
Can you clarify a little bit more about what's different between those test runs? i.e. for the test that reports differences in stack frames, which expected frames are missing & which unexpected ones are present?

**Comment by krassowski** [comment]
Sure! The way I understand it is that it is not a missing frame, but that the `line` returned in the frame points to a different line which indicates a breakpoint was set in a place other than expected; similarly the other failing test indicates that the breakpoint was set on the next line:

```python
i = 0
i += 1   # we were expecting this one
i += 1   # we saw this one based on value of `i` being 2
i = i**2
```

**Comment by krassowski** [comment]
I updated the comment above with more details. The `breakpointsInfo` of `debugInfo` reply indicates that indeed two breakpoints are registered as expected, it is just that in `stackTrace` request reply we we see the stack frame corresponding to the second and not the first breakpoint.

**Comment by int19h** [comment]
Could you run this with logging enabled on debugpy & pydevd side? Setting `DEBUGPY_LOG_DIR=...` env var to the directory where they're supposed to go should give you a bunch of `debugpy*.log` in there.

**Comment by krassowski** [comment]
Please see the logs generated on CI ([run 4119311750](https://github.com/krassowski/jupyterlab/actions/runs/4119311750)) attached: [logs.zip](https://github.com/microsoft/debugpy/files/10684603/logs.zip)

**Comment by int19h** [comment]
I don't see anything obviously broken in the logs, and I cannot repro this on any platform when debugging a plain file. Do you happen to have a simplified standalone repro that doesn't involve JL testing infrastructure?

I tried to set up the latter locally according to [the contributor guide](https://jupyterlab.readthedocs.io/en/latest/developer/contributing.html#setting-up-a-local-development-environment), but the relevant debugger tests all fail immediately with "Could not start the debugger: undefined" - and I cannot find any logs or other diagnostics to figure out what the problem is (debugpy is installed in the conda environment which is active at the point tests are run).

**Comment by int19h** [comment]
One theory that I do have, though, is that the code starts executing before the attach fully completes and debugger has a chance to do settrace on the relevant thread. I notice that you don't seem to be using `debugpy.wait_for_client()` in the test code, and assume that as soon as "configurationDone" response is received, tracing is active - which might not be reliable. It should be easy to test this hypothesis by adding a sleep before the first breakpoint. 

(Although it's unclear why that would be affected by different Python versions, unless the timing of the test is different between them for whatever reasons.)

**Comment by judej** [comment]
Thank you for the report. Given our current resources are working on the Python 3.12 debugger, we will not be fixing this issues in the pre Python 3.12 debugger.
