### ISSUE TITLE
Support for "launch" requests in a remote scenario

### ISSUE THREAD

**Issue by haniamr** [microsoft/debugpy#121]
The ask here is to support debug launch requests in remote scenarios where the app is running on a different machine/container.

**Comment by int19h** [comment]
To be more specific: this is about allowing the use of "connect" and "listen" in conjunction with `"request": "launch"`. Currently, these are only supported for "attach"; but there's no reason why the client cannot connect to a remote adapter, and issue a "launch" request to it, to spawn and debug a process remotely. 

The original scenario is described in https://github.com/microsoft/ptvsd/issues/2117

**Comment by int19h** [comment]
We are revisiting the design due to issues with multiproc in the original proposal (network boundary between client and adapter). The new design has the boundary between the adapter and the launcher instead.

**Comment by int19h** [comment]
This is implemented now.

**Comment by theoribeiro** [comment]
@int19h Wonder if you could clarify a little bit what was decided and implemented on this issue. I tried following the comment and the PRs but couldn't really understand what was done. Does this implement the feature proposed in #123 ?

My use case is I'd like to be able to wait for a process to connect to my debugger, reversing the direction of the connection, much like what PyCharm currently does. This allows me, for example, to debug API GW and lambda functions on AWS remotely or running in LocalStack. 

Thanks
