### ISSUE TITLE
Syntax error when debugging

### ISSUE THREAD

**Issue by irenepc** [microsoft/debugpy#1210]
## Environment data

- debugpy version: 1.6.6
- OS and version: Windows 10
- Python version: 3.7.9 64-bit
- Using VS Code

## Actual behavior
I get this error:
```
  File "c:\Users\irenec\.vscode\extensions\ms-python.python-2023.2.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd.py", line 3244
    def log_to(log_file:str, log_level=3) -> None:
                       ^
SyntaxError: invalid syntax
```
## Expected  behavior

Successful continuation of the code

## Steps to reproduce:

Launch a debug configuration within vscode

I wish I could provide more details, but my knowledge of environments and how debugpy interacts with the code when debugging through vsc is limited.
However, I suspect it may be related to issue #1193

**Comment by int19h** [comment]
debugpy requires Python 3.7 or later.

**Comment by irenepc** [comment]
I'm using 3.7.9 as my interpreter. Does this syntax error mean there is something else in there running an older version? Can I have some insight?
Thanks for the help!

**Comment by int19h** [comment]
You should be able to see the command line that's actually used to start the debugger, including the exact Python binary in the VSCode built-in terminal, so long as you didn't set `"console": "internalConsole"` in your launch.json. Can you check that it is indeed the version that you expect?

**Comment by irenepc** [comment]
Hello,

This is the line in the integrated terminal that startes the debugger (from what I can tell)
`PS Y:\irenec\pipelaunch\src>  & 'y:\irenec\pipelaunch\pl_venv\Scripts\python.exe' 'c:\Users\irenec\.vscode\extensions\ms-python.python-2023.2.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher' '59266' '--' 'ttflauncher/app_launcher.py' 
`
I navigated manually to that interpreter and launched it. First line in the interpreter window that opens is:
`Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
`

**Comment by int19h** [comment]
Very interesting. Does `app_launcher.py` start a separate child process to run code in, by chance? You've mentioned https://github.com/microsoft/debugpy/issues/1193 earlier as potentially relevant, but the specific scenario there is that a Python 3.7+ process spawns a Python 2 process, and we try to debug the latter. In this case, could it be the same, or, perhaps, the main process spawns the child some different version of Python 3?

The most reliable way to check this would be to edit your local copy of pydevd.py to print out the value of `sys.executable` right before the offending line.

**Comment by irenepc** [comment]
Yes, there was definitely a subprocess spawned somewhere in the code I was getting the error on. However, I think I will close this for now because I am not seeing this error anymore even on the code still spawning that subprocess. I tweaked some settings on my project which I think were related. Previously, the terminal that the debug process would launch in was running the virtual environment that the interpreter is set to. It's no longer running in that venv and I'm not seeing the error anymore.
Will reopen if I get more info or if I can recreate it again.
Thanks for the help!

**Comment by rk-exxec** [comment]
I am experiencing the same problem when using Python 3.11 and spawning a Python 2.7 subprocess.

```
SyntaxError: invalid syntax
  File "c:\Users\[]\.vscode\extensions\ms-python.python-2023.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd.py", line 3244
    def log_to(log_file:str, log_level=3) -> None:
                       ^
```

Debug command:
`cd 'c:\Users\[]\Documents\Python\evaluation_tools'; & 'c:\Users\[]\Documents\Python\evaluation_tools\.venv\Scripts\python.exe' 'c:\Users\[]\.vscode\extensions\ms-python.python-2023.14.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher' '63239' '--' 'C:\Users\[]\Documents\Python\evaluation_tools\profilometr\lext_eval.py' `
