### ISSUE TITLE
Enable setting access token from launch.json

### ISSUE THREAD

**Issue by martijnthe** [microsoft/debugpy#1211]
I'm using the `listen` mode from launch.json, like so:

```
        {
            "name": "Start debugpy server",
            "type": "python",
            "request": "attach",
            "listen": {
                "port": 8888,
                "host": "127.0.0.1"
            }
        }
```

But it looks like it's not possible to pass the [access token](https://github.com/microsoft/debugpy/blob/d1e5db7d8eb3cc4a05947fbbce0df8847f4b7c70/src/debugpy/public_api.py#L90) via the launch.json.

It would be nice if that was possible.

**Comment by int19h** [comment]
Indeed - we only used this feature internally for "launch" scenarios. But, given that it's already a part of the debugpy API, it makes sense to support it on the adapter end. It's easy enough to add, too:
https://github.com/microsoft/debugpy/blob/e9dc3e8844c95c9f31b33c8283b8936f91b60e79/src/debugpy/adapter/clients.py#L466-L474

Let's give it a try! If you change `adapter.access_token = listen("accessToken", str)` in your local copy of debugpy, I think it should handle everything correctly from there, even in multiproc scenarios.
