### ISSUE TITLE
Unable to view complex numpy arrays in Dataviewer in VSCode

### ISSUE THREAD

**Issue by xxc-zsz** [microsoft/debugpy#1213]
I am working with complex arrays (numpy) in python, and I use VSCode for development. When I work with real case, it's fine. I use the "Run and Debug" in VSCode to set breakpoints and debug the code. However, when I use complex numpy arrays, the data viewer is unable to show me the values of the array. They are shown as [object Object]

Here is a test example:
```
import numpy as np
a = np.array([[1+2j, 3+4j],[5+5j,7+8j]]) 
print(a) 
print("please help me view the complex array")
```
![image](https://user-images.githubusercontent.com/108051416/218359642-bf312cfc-c8ee-4983-824b-4fbc5e28c76a.png)
The numpy arrays are being stored at complex numbers (I guess there's no problem with that), as we can see on the left hand side "variables" section. However, when I try to view in the data Viewer, it doesn't print properly.

Being able to look into the values of the complex numpy arrays will really help with debugging the actual bigger codes that I am working on.

I have seen that this was a bug in VSCode but the bug was closed. Link for ref:

https://github.com/microsoft/vscode-jupyter/issues/4288

I have through the above thread and some other threads which are stated as dupes. But I can't find a solution and I am kind of stuck. Please help me out with this!

Thank you in advance!

**Comment by int19h** [comment]
As Data Viewer is owned by the vscode-jupyter extension and is not implemented directly by debugpy, the referenced bug is in the right repo - it sounds like it was fixed but then regressed. I'll reopen it in the other repo and close this one.
