### ISSUE TITLE
breakpoints in PyQt's QThread are ignored

### ISSUE THREAD

**Issue by rhaschke** [microsoft/debugpy#1214]
Type: <b>Bug</b>

This is the same as https://github.com/microsoft/vscode-python/issues/176: breakpoints in QThread's `run()` method (or functions called from there) are silently ignored.

## Steps to reproduce:

1. Use example program below
2. Set breakpoint in `Worker.run()`
3. Debug program
4. Observe worker doing its work, but the breakpoint not being hit

```python
from PyQt5.QtCore import QThread
from PyQt5.QtWidgets import QApplication


class Worker(QThread):
    def __init__(self):
        super().__init__()
        self.setObjectName("worker")
        self.running = False

    def run(self):
        self.running = True
        while self.running:
            print("Running")
            self.sleep(1)


if __name__ == "__main__":
    app = QApplication([])
    worker = Worker()
    worker.start()
    worker.finished.connect(app.quit)

    QThread.currentThread().sleep(10)
    worker.running = False

    app.exec()
```

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.10
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Global
-   Value of the `python.languageServer` setting: Pylance

<details>
<summary>Output for <code>Python</code> in the <code>Output</code> panel</summary>
<pre>
Experiment 'pythonSurveyNotificationcf' is active
LSP Notebooks experiment is enabled
LSP Notebooks interactive window support is enabled
> conda info --json
Python interpreter path: /usr/bin/python3
> /bin/python -I ~/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/interpreterInfo.py
> /bin/python2 -I ~/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/interpreterInfo.py
[ERROR 2023-1-12 21:18:24.895]: [Error: Command failed: /bin/python2 -I /homes/rhaschke/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/get_output_via_markers.py /homes/rhaschke/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/interpreterInfo.py
Unknown option: -I
usage: /bin/python2 [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.

	at ChildProcess.exithandler (node:child_process:408:12)
	at ChildProcess.emit (node:events:526:28)
	at maybeClose (node:internal/child_process:1092:16)
	at Socket.<anonymous> (node:internal/child_process:451:11)
	at Socket.emit (node:events:526:28)
	at Pipe.<anonymous> (node:net:687:12)] {
  killed: false,
  code: 2,
  signal: null,
  cmd: '/bin/python2 -I /homes/rhaschke/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/get_output_via_markers.py /homes/rhaschke/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/interpreterInfo.py'
}
> /bin/python3 -I ~/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/interpreterInfo.py
> /usr/bin/python2 -I ~/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/interpreterInfo.py
[ERROR 2023-1-12 21:18:25.93]: [Error: Command failed: /usr/bin/python2 -I /homes/rhaschke/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/get_output_via_markers.py /homes/rhaschke/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/interpreterInfo.py
Unknown option: -I
usage: /usr/bin/python2 [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.

	at ChildProcess.exithandler (node:child_process:408:12)
	at ChildProcess.emit (node:events:526:28)
	at maybeClose (node:internal/child_process:1092:16)
	at Socket.<anonymous> (node:internal/child_process:451:11)
	at Socket.emit (node:events:526:28)
	at Pipe.<anonymous> (node:net:687:12)] {
  killed: false,
  code: 2,
  signal: null,
  cmd: '/usr/bin/python2 -I /homes/rhaschke/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/get_output_via_markers.py /homes/rhaschke/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/interpreterInfo.py'
}
> /bin/python2 -I ~/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/interpreterInfo.py
[ERROR 2023-1-12 21:18:26.909]: [Error: Command failed: /bin/python2 -I /homes/rhaschke/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/get_output_via_markers.py /homes/rhaschke/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/interpreterInfo.py
Unknown option: -I
usage: /bin/python2 [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.

	at ChildProcess.exithandler (node:child_process:408:12)
	at ChildProcess.emit (node:events:526:28)
	at maybeClose (node:internal/child_process:1092:16)
	at Socket.<anonymous> (node:internal/child_process:451:11)
	at Socket.emit (node:events:526:28)
	at Pipe.<anonymous> (node:net:687:12)] {
  killed: false,
  code: 2,
  signal: null,
  cmd: '/bin/python2 -I /homes/rhaschke/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/get_output_via_markers.py /homes/rhaschke/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/interpreterInfo.py'
}
> /usr/bin/python2 -I ~/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/interpreterInfo.py
[ERROR 2023-1-12 21:18:27.106]: [Error: Command failed: /usr/bin/python2 -I /homes/rhaschke/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/get_output_via_markers.py /homes/rhaschke/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/interpreterInfo.py
Unknown option: -I
usage: /usr/bin/python2 [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.

	at ChildProcess.exithandler (node:child_process:408:12)
	at ChildProcess.emit (node:events:526:28)
	at maybeClose (node:internal/child_process:1092:16)
	at Socket.<anonymous> (node:internal/child_process:451:11)
	at Socket.emit (node:events:526:28)
	at Pipe.<anonymous> (node:net:687:12)] {
  killed: false,
  code: 2,
  signal: null,
  cmd: '/usr/bin/python2 -I /homes/rhaschke/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/get_output_via_markers.py /homes/rhaschke/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/interpreterInfo.py'
}
[ERROR 2023-1-12 21:18:27.203]: Invalid version for /bin/python2: {"name":"","location":"","kind":"global-other","executable":{"filename":"/bin/python2","sysPrefix":"","ctime":1613119163752,"mtime":1584102683000},"display":"Python 2.7.x","version":{"major":2,"minor":7,"micro":-1},"arch":1,"distro":{"org":""},"source":["path env var"],"id":"/bin/python2","detailedDisplayName":"Python 2.7.x"}
[ERROR 2023-1-12 21:18:27.206]: Invalid version for /usr/bin/python2: {"name":"","location":"","kind":"global-other","executable":{"filename":"/usr/bin/python2","sysPrefix":"","ctime":1613119163752,"mtime":1584102683000},"display":"Python 2.7.x","version":{"major":2,"minor":7,"micro":-1},"arch":1,"distro":{"org":""},"source":["path env var"],"id":"/usr/bin/python2","detailedDisplayName":"Python 2.7.x"}
Starting Pylance language server.
Extension search path: /homes/rhaschke/.vscode/extensions
> /usr/bin/python3 ~/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/linter.py -m pylint /tmp/test.py
cwd: /tmp
##########Linting Output - pylint##########

[
    {
        "type": "convention",
        "module": "test",
        "obj": "",
        "line": 1,
        "column": 0,
        "path": "test.py",
        "symbol": "missing-module-docstring",
        "message": "Missing module docstring",
        "message-id": "C0114"
    },
    {
        "type": "error",
        "module": "test",
        "obj": "",
        "line": 1,
        "column": 0,
        "path": "test.py",
        "symbol": "no-name-in-module",
        "message": "No name 'QThread' in module 'PyQt5.QtCore'",
        "message-id": "E0611"
    },
    {
        "type": "error",
        "module": "test",
        "obj": "",
        "line": 2,
        "column": 0,
        "path": "test.py",
        "symbol": "no-name-in-module",
        "message": "No name 'QApplication' in module 'PyQt5.QtWidgets'",
        "message-id": "E0611"
    },
    {
        "type": "convention",
        "module": "test",
        "obj": "Worker",
        "line": 5,
        "column": 0,
        "path": "test.py",
        "symbol": "missing-class-docstring",
        "message": "Missing class docstring",
        "message-id": "C0115"
    },
    {
        "type": "convention",
        "module": "test",
        "obj": "Worker.run",
        "line": 11,
        "column": 4,
        "path": "test.py",
        "symbol": "missing-function-docstring",
        "message": "Missing function or method docstring",
        "message-id": "C0116"
    },
    {
        "type": "refactor",
        "module": "test",
        "obj": "Worker",
        "line": 5,
        "column": 0,
        "path": "test.py",
        "symbol": "too-few-public-methods",
        "message": "Too few public methods (1/2)",
        "message-id": "R0903"
    },
    {
        "type": "convention",
        "module": "test",
        "obj": "",
        "line": 19,
        "column": 4,
        "path": "test.py",
        "symbol": "invalid-name",
        "message": "Constant name \"app\" doesn't conform to UPPER_CASE naming style",
        "message-id": "C0103"
    },
    {
        "type": "convention",
        "module": "test",
        "obj": "",
        "line": 20,
        "column": 4,
        "path": "test.py",
        "symbol": "invalid-name",
        "message": "Constant name \"worker\" doesn't conform to UPPER_CASE naming style",
        "message-id": "C0103"
    }
]
</pre>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

```

</p>
</details>

Extension version: 2023.2.0
VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:35:30.018Z)
OS version: Linux x64 5.14.0-1057-oem
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 3538)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 2|
|Memory (System)|30.97GB (26.47GB free)|
|Process Argv|/tmp/test.py --crash-reporter-id 86e0562d-0f33-43dc-be28-36d3bfc63712|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xubuntu|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848cf:30577861
nodejswelcome1cf:30587006
3biah626:30602489
f6dab269:30613381
pythonsymbol12cf:30657549
a9j8j154:30646983
vscodeenable:30660116

```

</details>

**Comment by int19h** [comment]
Does it help if you add this to your launch.json?
```json5
"qt": "pyqt5"
```
The default is "auto", but it works by probing installed packages, so it may get confused if you have different major versions side by side, or PyQt and PySide.

**Comment by rhaschke** [comment]
Yes, that helps indeed. And yes, I have both PyQt and PySide installed.
Wouldn't it be possible to enable debugging for _all_ found packages?
If not, can I configure this option globally, i.e. at least within a workspace or even better for all workspaces?
Setting this parameter per launch config requires many edits...

By the way, I worked around that issue explicitly enabling debugging within the thread's `run()` function:
```python
import debugpy
debugpy.debug_this_thread()
```

**Comment by int19h** [comment]
Supporting one version at a time is a pydevd limitation. It looks like it might be possible to monkey-patch multiple versions at once, but I'm not sure what effect having both PyQt and PySide fully loaded in the same process would have; it might be why it's restricted to one at a time.

It seems that you can set it globally by using `"qt": "auto"` (the default) and then overriding that with environment variable `PYDEVD_PYQT_MODE` - just make sure that it's in effect for the process being debugged.
