### ISSUE TITLE
Support "restart" in "terminated" event for "attach"{"listen"}

### ISSUE THREAD

**Issue by int19h** [microsoft/debugpy#1217]
See https://github.com/microsoft/debugpy/issues/577 for details.

**Comment by ilyakochik** [comment]
Hello, @int19h , @karthiknadig , by chance was it implemented? I see two commits but almost a years past on my latest VS Code I see notification that `"restart"` property is not allowed.

I'm a bit cornered here as with `"attach": "listen"` the restart of the "debugee" would kill the "listener", while in `"attach": "connect"` the `os.fork()` causes issues. Had to implement a quick and dirty workaround for that in my script to manually connect to "listener" vs using `debugpy` cli
