### ISSUE TITLE
Basic debugging doesn't work from v2022.10.0

### ISSUE THREAD

**Issue by boxabirds** [microsoft/debugpy#1224]
Type: <b>Bug</b>

# Behaviour
## Expected 
Putting a break point on the second line of  two line file "main.py" stops when I launch
```
print("hello 1")
print("hello 2")

```

## Actual: from v2022.10.0 (prior versions work ok)
Syntax error. 

Note that the file runs fine in this environment without the debugger enabled. 
Also this is a reduction of the issue I had in another project so it's not a problem with the python code either. 

## Steps to reproduce:

1. Create a simple main.py with the two lines above
2. create a launch.json file as below

```
{
    "version": "0.2.0",
    "configurations": [
        
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "justMyCode": "false"
        }
    ]
}
```
3. Press "debug"

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.2
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): PipEnv
-   Value of the `python.languageServer` setting: Pylance

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

linting
• pycodestyleEnabled: true

```

</p>
</details>

Extension version: 2023.2.40
VS Code version: Code 1.75.1 (Universal) (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:34:59.000Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.77GB free)|
|Process Argv|--crash-reporter-id e6752dd2-5542-4a95-a028-993c20301102|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewvextcfv2:30669238
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30662994
nodejswelcome1:30587005
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
pythonb192cf:30669361
funwalk2:30671524

```

</details>

**Comment by int19h** [comment]
The error message implies that runpy.py in the standard library your Python 3.11 installation is corrupt - it should not contain a backtick at that point. Can you look at the file on disk and see if it's actually there? And if so, what happens if you run Python directly outside of VSCode and do `import runpy`?

**Comment by boxabirds** [comment]
I will check but as noted the same binary works without debug mode and
v2022.8.1 and earlier don’t exhibit the problem with the exact same binary.

**Comment by int19h** [comment]
That it works without the debugger is not surprising if you're not importing `runpy` yourself - hence why it would be interesting to see what happens if you do. The fact that it works on older versions somehow is puzzling, but so is the error message if the file is actually fine.

One other thing that I find interesting looking at the second screenshot is that this runpy came not from a base conda environment, but from brew. If you manually run `python` from that environment, what is `runpy.__file__`?

**Comment by boxabirds** [comment]
Here we go. 

1. `import runpy.py` works fine
2. the location of `runpy.__file__` is `/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/runpy.py` which is the same as the file used

![Screenshot 2023-03-06 at 09 03 04](https://user-images.githubusercontent.com/147305/223064544-28c4f725-7acf-43c3-b5e0-6d870db70ba4.png)
 
Also I *did* notice an extraneous backtick that seems to have got inserted into my copy of `runpy.py` -- so the earlier presumption that my install of python seems to have got corrupted makes sense. I guess there's 1000 reasons why it would work on previous builds and not the new one. I'll try with a completely fresh environment and report back.

**Comment by boxabirds** [comment]
Reinstalling python seems to have resolved this. Thank you all for your support as I work through this.
