### ISSUE TITLE
Debugging not possible for different python interpreter

### ISSUE THREAD

**Issue by HJSteinort** [microsoft/debugpy#1226]
## Environment data

- debugpy version: 1.6.6
- OS and version: SIMATIC Industrial OS 2.2 (based on Debian 10 (buster))
- Python version: 3.9.16
- Using VS Code: 1.76.0
- Python extension: v2023.4.0
- setuptools: 67.4.0

## Actual behavior

Run Python File is working.
Debug Python File throws error

simple test-script used:
```
def main():
    print(f'\nHello world!\n')

if __name__=='__main__':
    main()
```

Error:

`"Timed out waiting for debuggee to spawn" `

Traceback:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/airnd/.vscode-server/extensions/ms-python.python-2023.4.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 37, in <module>
    from debugpy.server import cli
  File "/home/airnd/.vscode-server/extensions/ms-python.python-2023.4.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/__init__.py", line 7, in <module>
    import debugpy._vendored.force_pydevd  # noqa
  File "/home/airnd/.vscode-server/extensions/ms-python.python-2023.4.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/_vendored/force_pydevd.py", line 40, in <module>
    preimport('pydevd', [
  File "/home/airnd/.vscode-server/extensions/ms-python.python-2023.4.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/_vendored/__init__.py", line 126, in preimport
    import_module(name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/airnd/.vscode-server/extensions/ms-python.python-2023.4.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd_plugins/__init__.py", line 5, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
AttributeError: module 'pkg_resources' has no attribute 'declare_namespace'
```

Script is executing without errors when using default Python installation (version 3.7.3).

## Expected  behavior

Running script with debugger (added logfiles for both cases)

## Steps to reproduce:
1. installed python 3.9.16 manually via _wget_ and _make altinstall_ (apt does not provide package on my OS)
2. added interpreter to VS code
3. Switched between interpreter versions for varification of issue

## Possible Fixes tested:

- reinstall setuptools
- use older version of setuptools (v65.5.0)
- use older version of debugpy
- use older version of vscode-python (v2023.2.0 / v2022.20.0)

[debugger.vscode_3-9-test.log](https://github.com/microsoft/debugpy/files/10881315/debugger.vscode_3-9-test.log)
[debugpy.adapter-3-9-test.log](https://github.com/microsoft/debugpy/files/10881316/debugpy.adapter-3-9-test.log)
[debugpy.launcher-3-7-test.log](https://github.com/microsoft/debugpy/files/10881317/debugpy.launcher-3-7-test.log)
[debugpy.launcher-3-9-test.log](https://github.com/microsoft/debugpy/files/10881318/debugpy.launcher-3-9-test.log)
[debugpy.pydevd.3-7-test.log](https://github.com/microsoft/debugpy/files/10881319/debugpy.pydevd.3-7-test.log)
[debugpy.server-3-7-test.log](https://github.com/microsoft/debugpy/files/10881320/debugpy.server-3-7-test.log)

**Comment by int19h** [comment]
The error message indicates that your custom Python build has missing or corrupt `setuptools` package, and specifically the `pkg_resources` module. If I remember correctly, manual Python builds don't include the stuff that's normally prepackaged under `site-packages` by official releases (like `pip` and `setuptools`), so you need to install those manually after building.

**Comment by HJSteinort** [comment]
Thank you for this important hint!

I installed Python 3.9.16 via wget from python.org. `pip` and `setuptools` were included, fortunately. But even after reinstalling `setuptools` and adding `debugpy` using`pip` (see attached screenshot) the error remains

![image](https://user-images.githubusercontent.com/60009706/223027685-c94ffff8-e05a-4a92-a909-c89c34a8ba45.png)

**Comment by int19h** [comment]
I'm not sure I understand what you mean by installing it from python.org via wget. My understanding was that you were previously downloading the source code and then building it locally. Do you mean that a prebuilt release from python.org results in the same error for you?

**Comment by HJSteinort** [comment]
You are right, I got the wording wrong.

For clarification I followed these steps for my installation:

1. download python from the official Python release page
`wget https://www.python.org/ftp/python/3.9.16/Python-3.9.16.tgz`
2. extract tarball
`tar xzf Python-3.9.16.tgz`
3. navigate to directory and run configure command
4.

**Comment by int19h** [comment]
If you do `import pkg_resources` manually using your Python build, can you check via its `__file__` where it gets loaded from?

**Comment by HJSteinort** [comment]
After digging deeper into this issue it seems to be the case that the error corresponds with my specific OS.

Using python versions 3.8, 3.9 and 3.10 with a functioning debugger is possible, if I use virtual environments created with the respective versions as interpreter instead of the local installations.

So
`Python 3.10.10 ('venv3.10': venv) ./debugFunctions/venv3.10/bin/python3.10`
as used as interpreter works and starts the debugger as intended, but
`Python 3.10.10 64-bit /usr/local/bin/python3.10`
does not.

We will test the code with a "standard" Debian distribution within the next week, but I don't expect this issue to remain outside the current configuration.

Therefore I don't think that any further actions are neccessary.
Thank you for your time.
