### ISSUE TITLE
Attaching to .exe from /script connection timeout

### ISSUE THREAD

**Issue by NewUserHa** [microsoft/debugpy#1228]
## Environment data

- debugpy version: 1.6.6
- OS and version: win10 1803
- Python version: 3.11.2 .msi
- Using VS Code or Visual Studio: VS Code

## Actual behavior
After running a .exe from /script, there're 2 process, one for the script.exe ..., one for the python.exe ...
Attaching to the python one works good.
But attaching to a local process of script.exe, the debugger reported timeout to connect.

## Expected  behavior
it may should work.

## Steps to reproduce:
N/A

BTW, it seems that the attaching process can't goto references if without launch.json

**Comment by int19h** [comment]
If I remember correctly, on Windows, the script.exe files are just stubs that spawn the real thing as a python.exe subprocess. Thus, if you attach to the stub, there's no Python code (or even Python runtime) in it to debug, so the behavior is expected.

**Comment by NewUserHa** [comment]
Ok.
maybe could hide those script or sort those to the button or something?

**Comment by int19h** [comment]
The drop-down is filled by the Python extension for VSCode, so it would have to be a feature request in https://github.com/microsoft/vscode-python. I'm not entirely sure how it would detect that a process is a Python stub, though - it might be possible to do by inspecting the binary, but there doesn't seem to be anything clearly advertising it as a stub.

**Comment by NewUserHa** [comment]
The poped-out source code in the editor doesn't have the 'goto references' functions, should issue this in vscode-python too?

**Comment by NewUserHa** [comment]
ok.
but I remember it only requires in workspace.
