### ISSUE TITLE
Debug session cannot run for a .py file when there is an active breakpoint in a Jupyter notebook

### ISSUE THREAD

**Issue by JTP3XP** [microsoft/debugpy#1231]
## Environment data

- debugpy version: 1.6.6 (run `import debugpy; print(debugpy.__version__)` if uncertain)
- OS and version: Windows 10.0.17763
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.9.7
- Using VS Code or Visual Studio: VS Code

## Actual behavior

When debugging a .py file in a VS Code session that includes an active breakpoint in a Jupyter notebook, the debug session will fail with a message like the following:

> Traceback (most recent call last):
>   File "c:\Users\jpatton\.vscode\extensions\ms-python.python-2023.4.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_file_utils.py", line 876, in get_abs_path_real_path_and_base_from_file
>     return NORM_PATHS_AND_BASE_CONTAINER[filename]
> KeyError: 'vscode-notebook-cell://shareserver/share/Profiles/JPatton/Desktop/ErrorTest/test.ipynb#W1sZmlsZQ%3D%3D'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "c:\Users\jpatton\.vscode\extensions\ms-python.python-2023.4.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_file_utils.py", line 430, in _abs_and_canonical_path
>     return NORM_PATHS_CONTAINER[filename]
> KeyError: 'vscode-notebook-cell:/shareserver/share/Profiles/JPatton/Desktop/ErrorTest/test.ipynb#W1sZmlsZQ%3D%3D'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Program Files\Python39\lib\ntpath.py", line 647, in realpath
>     path = _getfinalpathname(path)
> FileNotFoundError: [WinError 161] The specified path is invalid: '\\\\shareserver\\share\\Profiles\\JPatton\\Desktop\\ErrorTest\\vscode-notebook-cell:\\shareserver\\share\\Profiles\\JPatton\\Desktop\\ErrorTest\\test.ipynb#W1sZmlsZQ%3D%3D'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "c:\Users\jpatton\.vscode\extensions\ms-python.python-2023.4.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_comm.py", line 252, in _on_run
>     self.process_net_command_json(self.py_db, json_contents)
>   File "c:\Users\jpatton\.vscode\extensions\ms-python.python-2023.4.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_process_net_command_json.py", line 193, in process_net_command_json
>     cmd = on_request(py_db, request)
>   File "c:\Users\jpatton\.vscode\extensions\ms-python.python-2023.4.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_process_net_command_json.py", line 804, in on_setbreakpoints_request
>     result = self.api.add_breakpoint(
>   File "c:\Users\jpatton\.vscode\extensions\ms-python.python-2023.4.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_api.py", line 485, in add_breakpoint
>     translated_absolute_filename = pydevd_file_utils.absolute_path(translated_filename)
>   File "c:\Users\jpatton\.vscode\extensions\ms-python.python-2023.4.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_file_utils.py", line 417, in absolute_path
>     return get_abs_path_real_path_and_base_from_file(filename)[0]
>   File "c:\Users\jpatton\.vscode\extensions\ms-python.python-2023.4.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_file_utils.py", line 897, in get_abs_path_real_path_and_base_from_file
>     abs_path, canonical_normalized_filename = _abs_and_canonical_path(f)
>   File "c:\Users\jpatton\.vscode\extensions\ms-python.python-2023.4.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_file_utils.py", line 456, in _abs_and_canonical_path
>     real_path = _apply_func_and_normalize_case(filename, os_path_real_path, isabs, normalize)
>   File "c:\Users\jpatton\.vscode\extensions\ms-python.python-2023.4.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_file_utils.py", line 483, in _apply_func_and_normalize_case
>     r = func(filename)
>   File "C:\Program Files\Python39\lib\ntpath.py", line 651, in realpath
>     path = _getfinalpathname_nonstrict(path)
>   File "C:\Program Files\Python39\lib\ntpath.py", line 601, in _getfinalpathname_nonstrict
>     path = _getfinalpathname(path)
> FileNotFoundError: [WinError 161] The specified path is invalid: '\\\\shareserver\\share\\Profiles\\JPatton\\Desktop\\ErrorTest\\vscode-notebook-cell:\\shareserver\\share\\Profiles\\JPatton\\Desktop\\ErrorTest\\test.ipynb#W1sZmlsZQ%3D%3D'

## Expected  behavior

The debug session for the .py file should ignore breakpoints in .ipynb files, which it seems it cannot find anyway.

## Steps to reproduce:
1. Create a new folder
2. Open folder as a workspace in VS Code
3. Add an .ipynb file to the workspace, add some code and a breakpoint somewhere in the file
4. Add a .py file to the workspace, add some code and a breakpoint somewhere in the file
5. Click the "Debug Python File" while the .py file is selected in the VS Code window

I noticed that only active breakpoints cause this issue. Unchecking the breakpoint in the notebook using the "Breakpoints" configuration in VS Code will allow the debug session to run properly for the .py file.

**Comment by int19h** [comment]
It shouldn't quite ignore them, because it is possible to have Python code loaded from a file with a different extension. It just shouldn't do anything about those breakpoints unless and until it sees a code object with a matching `__file__`; it certainly shouldn't crash! Thank you for reporting this.
