### ISSUE TITLE
pythonArgs do not seems to work

### ISSUE THREAD

**Issue by jpele-tis** [microsoft/debugpy#1238]
Type: <b>Bug</b>

# Behaviour
Hello,
We want to execute our Python in isolated mode, but the flags do not seems to be passed in the execution

## Expected vs. Actual
'C:\Program Files (x86)\wapt\waptpython.exe' "-I"
'C:\Program Files (x86)\wapt\waptpython.exe' 

## Steps to reproduce:

1. fill a launch.json with pythonArgs
```
        {
            "name": "WAPT: update-package",
            "type": "python",
            "request": "launch",
            "justMyCode": true,
            "program": "${config:python.wapt-get}",
            "args": [
                "update-package-sources",
                "${workspaceFolder}"
            ],
            "console": "integratedTerminal",
            "python": "${command:python.interpreterPath}",
            "pythonArgs": [
                "-I"
            ]
        },
```

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.16
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Global
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
Send text to terminal:  c:; cd 'c:\wapt-packages\tuxpaint\windows\x64'; & 'C:\Program Files (x86)\wapt\waptpython.exe' 'c:\Users\jpadmin\.vscode\extensions\ms-python.python-2023.4.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher' '63824' '--' 'C:\Program Files (x86)\wapt\wapt-get.py' 'update-package-sources' 'C:\wapt-packages\tuxpaint\windows\x64' 

```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

formatting
• provider: "black"
• blackArgs: "<placeholder>"

```

</p>
</details>

Extension version: 2023.4.1
VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:00.131Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz (4 x 2100)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|5.99GB (2.23GB free)|
|Process Argv|C:\\wapt-packages\\tuxpaint\\windows\\x64 C:\\wapt-packages\\tuxpaint\\windows\\x64\\setup.py C:\\wapt-packages\\tuxpaint\\windows\\x64\\WAPT\\control C:\\wapt-packages\\tuxpaint\\windows\\x64\\update_package.py C:\\wapt-packages\\tuxpaint\\windows\\x64\\WAPT\\changelog.txt|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by int19h** [comment]
Note that the command line that you see in the terminal when launching does *not* accurately represent those flags. That command line is used to spawn the debugpy launcher, which then spawns your app. You should check `sys.flags` from inside the app to see whether the flag was correctly applied. You can see the actual command line used to spawn your app by enabling logging (`"logToFile": true` in debug config) and then looking at `debugpy.launcher*.log`.

**Comment by jpele-tis** [comment]
In `debugpy.server-12328.log` I found :
`
             Command line: ['C:\\Program Files (x86)\\wapt\\Scripts\\python.exe', '-I', 'c:\\Users\\jpadmin\\.vscode\\extensions\\ms-python.python-2023.4.1\\pythonFiles\\lib\\python\\debugpy\\adapter/../..\\debugpy\\launcher/../..\\debugpy', '--connect', '127.0.0.1:58805', '--configure-qt', 'none', '--adapter-access-token', '2e2a00c648ca38ec98624ec07c6e33637902acb64f8548818a55bdca1d5164e8', 'C:\\Program Files (x86)\\wapt\\wapt-get.py', 'update-package-sources', 'C:\\waptdev-private\\wapt-education\\50-exp\\windows']
`
So I guess it is working, thanks @int19h
