### ISSUE TITLE
test_flask.py and test_run.py fail

### ISSUE THREAD

**Issue by doronbehar** [microsoft/debugpy#1241]
## Environment data

- debugpy version: 1.6.6
- OS and version: NixOS
- Python version: 3.10

## Actual behavior

Tests fail:

```
FAILED tests/debugpy/test_flask.py::test_flask_breakpoint_multiproc[launch] - AssertionError: Unobserved occurrences detected:
FAILED tests/debugpy/test_run.py::test_run_relative_path[launch(internalConsole)] - assert 'Traceback' not in 'Traceback (...: finished\n'
```

Here are the logs:

https://gist.github.com/doronbehar/621cda33da729f25abc3dfc5af704a3c

https://gist.github.com/doronbehar/621cda33da729f25abc3dfc5af704a3c

## Expected  behavior

No tests fail

## Steps to reproduce:

Perhaps some combination of dependencies which is present at the moment only on NixOS is what's causing this issue. You can browse https://github.com/NixOS/nixpkgs/tree/master/pkgs/development/python-modules to see what's the versions of debugpy's dependencies in Nix' packages collection.

**Comment by int19h** [comment]
The second error is due to https://github.com/microsoft/debugpy/issues/1230. Can you share the log for the Flask failure? (both links seem to point to the log for test_run_relative_path atm)
