### ISSUE TITLE
'args' not passed to python when launching a debug session.

### ISSUE THREAD

**Issue by weiyshay** [microsoft/debugpy#1243]
## Environment data
debugpy version: 1.5.1
OS and version: CentOS 7.6
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.8
- Using VS Code or Visual Studio: Neovim

## Actual behavior
'args' not passed to program.

## Expected  behavior
Get the args correctly

## Steps to reproduce:
Using the belowing configuration, either in a long string or separate parametes, 
no args received after debug session started. What am I missing? 
 
I am referring to the guide:
https://github.com/microsoft/debugpy/wiki/Debug-configuration-settings

It seems to be in json file, can I use it in dap configuration? Is json supported in Neovim?

```
args | Array[string] | Launch | Command line arguments passed to the program.
Example: "args": ["--arg1", "-arg2", "val", ...]
-- | -- | -- | --

```

```
args = "--action convert tput --batch-size 4 --log debug --convert-config config.json.ljf"
args = ["--action", "convert", "tput", "--batch-size", "4", "--log", "debug", "--convert-config", "config.json.ljf"]

```

```
# cat ~/.config/nvim/lua/dap-python.lua 
local dap = require('dap')

dap.adapters.python = {
    type = "executable",
    -- command = "/localdata/weix/env/virtual-env/centos76-tf793/bin/python3";
    command = "python3";
    args = { "-m", "debugpy.adapter" },
}

dap.configurations.python = {
    -- launch exe
    {
        type = "python", -- the type here established the link to the adapter definition: `dap.adapters.python`
        request = "launch",
        name = "Launch file",
        -- program = "${file}", -- This configuration will launch the current file if used.
        program = function()
            return vim.fn.input('file')
        end,
        -- args = "--action convert tput --batch-size 4 --log debug --convert-config config.json.ljf"
        args = ["--action", "convert", "tput", "--batch-size", "4", "--log", "debug", "--convert-config", "config.json.ljf"]
        pythonPath = function()
            local venv_path = os.getenv("VIRTUAL_ENV")
            if venv_path then
                return venv_path .. "/bin/python3"
            end
            return "/usr/bin/python3"
        end
    }
}
```

**Comment by int19h** [comment]
I'm not familiar with how NeoVim sets up debugpy integration, so I'm unable to help with the specifics of their config, especially since it's based on Lua and they map that to JSON somehow. In a JSON config, the way you defined `args` as a list should have worked, and so I would expect this Lua config to work the same. But the mapping might not be so trivial. It might be best to ask on the NeoVim forums or issue tracker first.

**Comment by weiyshay** [comment]
Pavel,
Thank you very much for your feedback! I will seek for help from Neovim.
