### ISSUE TITLE
Python 3.11 reports frozen modules warning despite passing during startup

### ISSUE THREAD

**Issue by miketheman** [microsoft/debugpy#1251]
## Environment data

- debugpy version: 1.6.6
- OS and version: Debian GNU/Linux 11
- Python version (& distribution if applicable, e.g. Anaconda): CPython 3.11.2
- Using VS Code or Visual Studio: VS Code

## Actual behavior

Given a startup command like this:

```sh
python -X frozen_modules=off -m debugpy --listen 0.0.0.0:5678 -m gunicorn ... (rest of gunicorn startup args)
```

Once started, debugpy emits this warning:

```
0.01s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
```

Note: I've tried it both with a space and without, no change. ref: https://github.com/microsoft/debugpy/pull/937/files#r1145404312 

## Expected  behavior

No warning emitted

## Steps to reproduce:
See above

**Comment by davetapley** [comment]
See also:
- https://github.com/microsoft/debugpy/issues/1284

**Comment by ergoithz** [comment]
related https://github.com/python/cpython/issues/106723

**Comment by judej** [comment]
@miketheman, checking in if this if fixed after  https://github.com/python/cpython/issues/106723 was closed over a year ago. If this is still an issue, please reopen the issue.
