### ISSUE TITLE
Got time out error If using debugpy with cpy3(gopython)

### ISSUE THREAD

**Issue by blair-long** [microsoft/debugpy#1253]
Hello Dear Friends, I got error when I use debugpy on python code called by gopython. Hope someone can give some guidance, Thank you in advance.

## Environment data

- debugpy version: 16.6
- OS and version: Windows 10 19045.2728
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.7.9 (tags/v3.7.9:13c94747c7)
- Using VS Code or Visual Studio: Vs Code

Since I'm using Gopython to run python code by golang , I also list the golang version and gopython version here.
- golang: 1.18.4 windows/amd64
- gopython: Use cpy3, github link: https://github.com/go-python/cpy3

## Actual behavior
If I follow debugpy doc to write simple example in python code as below(test.py), and run it use python command, It works fine., I can use VS code to debug it with remote attach mode.
``` python
print("Hello World remote")
import debugpy;
debugpy.listen(("localhost", 5678));
print("listen success")
debugpy.wait_for_client()
print("exit")
```

But If I use cpy3 to run the python code as below, I got timeout error , the 5678 port cannot be listened. Below is the simple code(test.go) to run python code with debugpy by cpy3.
``` golang
package main

import (
	"fmt"
	python3 "github.com/go-python/cpy3"
)

func main() {
	python3.Py_Initialize()

	fmt.Println("init success")

	python3.PyRun_SimpleString("print('hello world' )")
	python3.PyRun_SimpleString("import debugpy;" +
		"debugpy.log_to('C:/Users/user/GolandProjects/test_gopython');" +
		"debugpy.listen((\"localhost\", 5678));" +
		"debugpy.wait_for_client();" +
		"print('hello debugpy')")

	fmt.Println("done ")
	python3.Py_Finalize()
}

```

Below is the detailed error:
```
init success
hello world
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\debugpy\server\api.py", line 237, in listen
    sock, _ = endpoints_listener.accept()
  File "C:\Python37\lib\socket.py", line 212, in accept
    fd, addr = self._accept()
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python37\lib\site-packages\debugpy\public_api.py", line 31, in wrapper
    return wrapped(*args, **kwargs)
  File "C:\Python37\lib\site-packages\debugpy\server\api.py", line 143, in debug 
    log.reraise_exception("{0}() failed:", func.__name__, level="info")
  File "C:\Python37\lib\site-packages\debugpy\server\api.py", line 141, in debug 
    return func(address, settrace_kwargs, **kwargs)
  File "C:\Python37\lib\site-packages\debugpy\server\api.py", line 251, in listen
    raise RuntimeError("timed out waiting for adapter to connect")
RuntimeError: timed out waiting for adapter to connect

```

I also try to print the detail error to use debugpy.log_to('path/to/logs'), the log output include mutiple files which filename prefix is "debugpy.server-xxxx.log", I attached the zip file include all the log files.  A very strange behavior is:
after I stop running the golang code, the log file is still generate continually, It genereated more than hundreds of log files in 5 minutes.
[test_gopython.zip](https://github.com/microsoft/debugpy/files/11120360/test_gopython.zip)

## Expected  behavior

The localhost 5678 port should be listened and I can debug the python code on VS Code.

## Steps to reproduce:
See actual behavior part

**Comment by int19h** [comment]
debugpy needs access to `python.exe` (or something that behaves like one wrt its CLI) to spawn its helper processes. Normally it uses `sys.executable`, but when you're hosting Python in your app, that points at the app. You should use `debugpy.configure(python="...")` to point it at a suitable interpreter before `listen()`.
