### ISSUE TITLE
Wheel RECORD for run_code_on_dllmain_amd64.dll size does not match the size of the actual file

### ISSUE THREAD

**Issue by aykutkilic-avl** [microsoft/debugpy#1256]
Before creating a new issue, please check the [FAQ](https://github.com/microsoft/debugpy/wiki/FAQ) to see if your question is answered there.

## Environment data

- debugpy version: 1.6.6 (run `import debugpy; print(debugpy.__version__)` if uncertain)
- OS and version: Win64
- Python version (& distribution if applicable, e.g. Anaconda): 3.9.13
- Using VS Code or Visual Studio: CODE

## Actual behavior

The Wheel RECORD file has the statement:
debugpy/_vendored/pydevd/pydevd_attach_to_process/run_code_on_dllmain_amd64.dll,sha256=O5iYwJrOTR0TnCttACPTS97fdu7IDKCWPfYVDWWnyj8,16896
Which states that the file size is 16896 bytes, while the actual file is: 27048 bytes.

## Expected  behavior

The RECORD should be corrected

## Steps to reproduce:
1. Expand the zip file and compare the RECORD and the actual expanded files.

**Comment by int19h** [comment]
Yep, it's the same issue as in #1246.
