### ISSUE TITLE
Cannot not close the Django server when stop debugging in Django 

### ISSUE THREAD

**Issue by justin8953** [microsoft/debugpy#126]
There was an issue that I tried to use debug in Django. 
When I saved my change several times and I tried to restart debug, it can't restart. 
Even I closed the VS code, it will still used the port I ran before. 
What's worse, I tried to kill the port which I used, it still kept using.

**Comment by int19h** [comment]
Can you try this with `"console": "internalConsole"`, and see if that makes any difference for you?

**Comment by int19h** [comment]
Are you still seeing this issue with the most recent version of the extension? Does `"console": "internalConsole"` help anything?

**Comment by justin8953** [comment]
Hi Pavel,

the problem has been fixed when I changed to used other OS. Thank you very
much.

Many thanks
Yu-Ting Lan

Pavel Minaev <notifications@github.com> 於 2020年5月2日 週六 上午11:06寫道：

**Comment by int19h** [comment]
We were unable to repro this on WSL, so I'm going to close the issue as unactionable. Please re-open if you see the same problem again.
