### ISSUE TITLE
VSCode doesn't show any variable, and stops

### ISSUE THREAD

**Issue by ranggihwang** [microsoft/debugpy#1275]
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

I am currently using the VSCode Python debugger to debug HuggingFace SwitchTransformer.

Initially, the debugger worked well and displayed variables and call stacks. However, at some point, it stopped showing variables and only displayed call stacks. Then it stopped showing the message "terminate timeout 2000ms".

Here is a detailed explanation of the problem.

* I am debugging a Python file that uses the HuggingFace framework within a docker container on a Linux machine.
* It is interesting to note that the debugger works well for a lightweight Python file and displays variables, call stacks, and other relevant information.
* I should mention that I am using a Mac and accessing a remote Linux machine. Interestingly, when I access and debug the same file using a Windows machine, everything works as expected.

[![Screen capture][1]][1]

Here's the solution that I've tried but didn't work.

* I already re-installed VScode and deleted the related cache in VScode.
* I've re-installed, downgraded, and upgraded the VScode Python extension to a different version.

https://stackoverflow.com/questions/74646338/variables-panel-not-showing-when-debugging-any-language-in-vscode

I suspect that my Mac environment can cause this problem (maybe memory problem) because,
* The remote Linux machine works well from a Windows machine.
* The debugger works well from my Mac for a lightweight Python file but does not works for the large Python file.

Can the local machine's memory capacity be the reason for this problem? I'm using M1 Mac with 16 GB memory.

I'm using Vscode Version: 1.77.1 (Universal) and Python extension v2023.7.10971005, v2022.8.0.

  [1]: https://i.stack.imgur.com/XlPaL.png

https://stackoverflow.com/questions/75969331/vscode-doesnt-show-any-variable-and-stops
This is the same question that I uploaded in StackOverflow.

## Steps to reproduce:

1. Download HuggingFace Transformer.
2. Make a random script that can run HuggingFace SwitchTransformer.
You can just copy and paste the sample script here.
https://huggingface.co/google/switch-base-8
3. Set a breakpoint in random point of the bash script.
4. Then start Dubugging.

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.13
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Venv
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
Experiment 'pythonPromptNewToolsExt' is active
> conda info --json
Python interpreter path: ./HuggingFace/HF/bin/python
> /opt/conda/bin/python -I ./.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/get_output_via_markers.py ./.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/interpreterInfo.py
> . ./HuggingFace/HF/bin/activate && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python ./.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/printEnvVariables.py
shell: bash
Starting Pylance language server.
DAP Server launched with command: /root/HuggingFace/HF/bin/python /root/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/lib/python/debugpy/adapter
Send text to terminal: source /root/HuggingFace/HF/bin/activate
Send text to terminal:  /usr/bin/env /root/HuggingFace/HF/bin/python /root/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher 35803 -- /root/accelerating_moe_inference/hugging_face_/Offloading_experiment/1_offloading/inference.py --model_name google/switch-base-8 --device_mapping gpu-cpu --batch 1 --iter 1 --varbose True 
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

```

</p>
</details>

Extension version: 2023.6.0
VS Code version: Code 1.77.3 (Universal) (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:19:37.325Z)
OS version: Darwin arm64 22.4.0
Modes:
Sandboxed: No
Remote OS version: Linux x64 4.15.0-55-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.62GB free)|
|Process Argv|--crash-reporter-id d97b7fd7-6d82-4f7a-9c74-fbc22d836ec2 --crash-reporter-id d97b7fd7-6d82-4f7a-9c74-fbc22d836ec2|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container nvcr.io/nvidia/pytorch:22.09-py3 (FastTransformer) @ ssh://DGX_V100|
|OS|Linux x64 4.15.0-55-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz (80 x 2437)|
|Memory (System)|503.79GB (481.80GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
6233i204:30672705
vsccsb:30705552
vscodedisable:30660115
defaultazurewalk:30687958
pythonms35:30701012
pythonclientmvcf:30713944

```

</details>

**Comment by int19h** [comment]
I wonder if perhaps one of the variables has a repr that is causing issues - we have some custom code for builtin types, but most everything else is formatted via `repr()`. We've had an issue before, with sklearn I think, where a value would end up recursing infinitely, causing a `StackOverflowError` that cannot be caught.

If this is the case, it might be possible to identify the offending variable by observing which ones get into scope or have their values change right at the point when it happens, and confirm by doing `repr()` manually from your code and seeing if that triggers a stack trace.
