### ISSUE TITLE
Python debug attach silently fails efter short while

### ISSUE THREAD

**Issue by ripperdoc** [microsoft/debugpy#1276]
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

I expect to be able to attach debugger to a Python container.

## Steps to reproduce:

I have a python file:
```
import debugpy
debugpy.listen(5678)
debugpy.wait_for_client()
```
and Dockerfile:
```
FROM python:3.8-slim

WORKDIR /app

USER root
RUN pip install debugpy
ADD run.py /app/
```
.. and this is the relevant part of launch.json:
```
    {
      "name": "Python: Attach",
      "type": "python",
      "request": "attach",
      "connect": {
        "host": "localhost",
        "port": 5678
      }
    }
```

If I run the Docker image with:
```
docker run -p 5678:5678 test python run.py
```
It hangs waiting for me to attach, but when I click to start debug with "Python: Attach" the debug menu shows up for a moment but then disappears. No error is shown, but in Python log I can see one line:

```
Connecting to DAP Server at:  localhost:5678
```

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.13
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Venv
-   Value of the `python.languageServer` setting: Pylance

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

formatting
• provider: "black"
• blackArgs: "<placeholder>"

testing
• pytestArgs: "<placeholder>"
• pytestEnabled: true

experiments
• optOutFrom: ["PtvsdWheels37 - experiment"]

```

</p>
</details>

Extension version: 2023.6.1
VS Code version: Code 1.77.3 (Universal) (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:19:37.325Z)
OS version: Darwin x64 19.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 7, 13|
|Memory (System)|16.00GB (0.94GB free)|
|Process Argv|-psn_0_5842322 --crash-reporter-id f38762bb-c266-463a-bc0c-77d8ce21e900|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
nodejswelcome1:30587005
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
defaultazurewalk:30687958
pythonms35:30701012
pythonfmttextcf:30716743

```

</details>

**Comment by int19h** [comment]
Is this the complete Python script being debugged? If so, the described behavior would be expected - if it succeeds to attach, the script will resume running and terminate, which would explain the debug toolbar flashing in and out briefly.

**Comment by ripperdoc** [comment]
> Is this the complete Python script being debugged? If so, the described behavior would be expected - if it succeeds to attach, the script will resume running and terminate, which would explain the debug toolbar flashing in and out briefly.

It has been reduced to a minimal example, but maybe too minimal. However, if the debug connection did go through, the program would terminate which it doesn't, if I add a print on the last line I never reach that breakpoint and if I do Ctrl+C stack trace shows that it's still on `wait_for_client()`

**Comment by AlexTMjugador** [comment]
I can reproduce this issue with updated Python, VS Code and Python language support extensions. It was not fixed.

**Comment by navels** [comment]
This is driving me crazy . . . anyone?

**Comment by rchiodo** [comment]
Adding `logToFile` in the launch.json should give more output as described here:
https://github.com/microsoft/debugpy/wiki/Enable-debugger-logs

It might show what went wrong. 

My guess is there's a timeout occurring somewhere. Hopefully the log will say where.

**Comment by navels** [comment]
> Adding `logToFile` in the launch.json should give more output as described here: https://github.com/microsoft/debugpy/wiki/Enable-debugger-logs
> 
> It might show what went wrong.
> 
> My guess is there's a timeout occurring somewhere. Hopefully the log will say where.

Thanks for that, but it didn't help.  I'm not seeing anything of note in the debug logs, just startup stuff and then nothing until I shutdown the process. E.g., from `debugpy.server-dddd.log`:
```
I+00000.953: Adapter is accepting incoming client connections on 127.0.0.1:5678

D+00000.953: pydevd.settrace(*(), **{'host': '127.0.0.1', 'port': 65375, 'wait_for_ready_to_run': False, 'block_until_connected': True, 'access_token': '28731ebd9bd887951bd462da2c8f49c4c7ba2cc28c48eb038eead333282e2b00', 'suspend': False, 'patch_multiprocessing': True, 'dont_trace_start_patterns': ('C:\\Program Files\\Python312\\Lib\\site-packages\\debugpy',), 'dont_trace_end_patterns': ('debugpy_launcher.py',)})

I+00001.093: pydevd is connected to adapter at 127.0.0.1:65375

D+00001.093: wait_for_client()

I+00089.515: Not logging to "<stderr>" anymore.
```

FWIW I am tunneling the connection over ssh to a remote Windows host . . . so there *shouldn't* be any connectivity issues.  Tunneling via
```
ssh -N -L 5678:localhost:5678 <remote_host>
```
and telnet connects:
```
telnet localhost 5678
Trying ::1...
Connected to localhost.
Escape character is '^]'.
```
(connection dropped after a few seconds).

**Comment by rchiodo** [comment]
Are you just tunnelling the one port? It opens multiple. At least the log is showing that. I thought the `debugpy.listen(port)` didn't require secondary ports but I may be wrong.

**Comment by navels** [comment]
> Are you just tunnelling the one port? It opens multiple. At least the log is showing that. I thought the `debugpy.listen(port)` didn't require secondary ports but I may be wrong.

Just the one but I think that is all that is required.
