### ISSUE TITLE
Debugpy throwing caught exception

### ISSUE THREAD

**Issue by FaimMedia** [microsoft/debugpy#1278]
Before creating a new issue, please check the [FAQ](https://github.com/microsoft/debugpy/wiki/FAQ) to see if your question is answered there.

## Environment data

- debugpy version: 1.6.7
- OS and version: macOS Ventura 13.2.1
- Python version: 3.11.2
- Using VS Code: VSCode 1.77.1 (Universal)

## Actual behavior

Debugpy is halting on what it thinks is a 'User Uncaught Exception':

<img width="773" alt="Exception" src="https://user-images.githubusercontent.com/11771199/233356712-6c0ff8ac-a590-40b3-9f4c-f11eb9d77557.png">

However inspecting the Python source code, showing a try/except block, so it shouldn't break:

<img width="1068" alt="collections_abc" src="https://user-images.githubusercontent.com/11771199/233357270-874fecf6-75ed-4721-8158-f29522255eae.png">

Selected breakpoints:

<img width="273" alt="Breakpoints" src="https://user-images.githubusercontent.com/11771199/233356703-32b75882-9be2-4645-88b5-68fc364bd5bf.png">

## Expected  behavior

Debugpy not halting on a caught exception.

## Steps to reproduce:

Use the following code block and run with debugpy:

```python
from time import sleep
from collections.abc import MutableMapping

# Add sleep to let debugpy startup 
#sleep(10)

class DictWithDefaults(MutableMapping):
    def __init__(self, default, *args, **kwargs):
        assert isinstance(default, dict)
        self._config = {}
        self._default = default
        for key, value in dict(*args, **kwargs).items():
            self.__setitem__(key, value)

    def __getitem__(self, key):
        if key in self._config:
            return self._config[key]
        return self._default[key]

    def __setitem__(self, key, value):
        current_value = self._default.get(key)
        if isinstance(value, (str, Promise)):
            current_value = str(current_value)

        if current_value == value:
            if key in self._config:
                del self._config[key]
        else:
            self._config[key] = value
            return

    def __iter__(self):
        for key in self._config:
            yield key
        for key in self._default:
            if key not in self._config:
                yield key

    def __len__(self):
        return len(list(iter(self)))

    def __delitem__(self, key):
        if key in self._config:
            del self._config[key]
            return
        if key not in self._default:
            raise KeyError

    def __repr__(self):
        return "<DictWithDefaults {}, {}>".format(self._config, self._default)


a = DictWithDefaults({
	"existingkey": "value"
})

b = a.get("nonexistingkey", None)

print(b)
```

**Comment by int19h** [comment]
`Mapping` is part of stdlib, so this doesn't count as *user*-uncaught - the latter is basically any exception that bubbles up from your frame into stdlib. This can be changed by setting `"justMyCode": false` - that should cause everything in the library to be treated as "your code".

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
