### ISSUE TITLE
VS-Code Python remote Debugger issue: "Timed out waiting for debuggee to spawn"

### ISSUE THREAD

**Issue by srinidhiPY** [microsoft/debugpy#1281]
Hello,

I am having an issue with python debugger. It was working until very recently, but now I am getting this error ""Timed out waiting for debuggee to spawn". I tried to re-install but it wasn't useful.

The debugger works on my local system, but I get the above error while doing remote debugging using [SSH FS].

Please, could you help me with this issue.

Details:
OS - Windows 10 Enterprise x64 10.0.19044
Python - 3.9.15
Conda -  4.10.3
VScode - 1.77.3
Sandboxed: No
![Screenshot 2023-04-25 103059](https://user-images.githubusercontent.com/16255955/234180307-6b5038a7-cf82-4241-bc01-a2a6fb86f2bf.jpg)

**Comment by int19h** [comment]
Are you doing remote debugging as in `"attach"` to a different IP in your launch.json? Or are you using the VSCode Remote SSH extension to remote the entire VSCode session?

**Comment by srinidhiPY** [comment]
Hi Pavel,

Thanks for the help.

I am using the VSCode Remote SSH extension to remote the entire VSCode
session. Whenever, there is any new updates with the python-debugger it
stops working for some reason always. Below is my launch.json file for
debugging.

{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit:
https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: CLI",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal"
             ]
        }
    ]
}

**Comment by int19h** [comment]
Thank you. Can you try adding `"logToFile": true` to this and grab the log files from the remote machine? They'll be in the same directory where the extension ends up installed remotely - you should be able to see where from the command line used in the terminal to start debugging.

**Comment by srinidhiPY** [comment]
Thank you for the quick response.

Please, find the attachment of the log-files as requested. Kindly, let me
know if you need any other information.

Regards,
Chetan

**Comment by srinidhiPY** [comment]
Hi,

Sorry for the late reply.

I have attached the VS-Code log files to google drive so you can access
them. *The link is
here: https://drive.google.com/file/d/18Y-dbsEz7IAf9h7TdTHmO_8RWlRrFamI/view?usp=sharing
<https://drive.google.com/file/d/18Y-dbsEz7IAf9h7TdTHmO_8RWlRrFamI/view?usp=sharing>*

Please, kindly let me know if you face any problem. Looking forward to your
response.

Regards,
Chetan

**Comment by int19h** [comment]
Looking at the logs, I wonder if there is anything special about the Python interpreter or the system itself that might cause thread starvation? The component that is supposed to initiate the connection actually does that and reports that it could connect to the listener socket successfully; but the background thread on the other end that is sitting waiting for `accept()` call on said listener socket doesn't get control until after the timeout already happened. This is really weird, though - even on a system under very heavy load I'd expect 15s to be more than enough for the thread to get a slice of time to at least report the incoming connection right away.

**Comment by srinidhiPY** [comment]
Hello,

Thanks so much for your quick response.

I usually face this issue whenever there is any new update with the
python-debugger. Earlier, this issue used to persist for some time (maybe a
week), and it usually gets resolved by itself. However, it is almost three
weeks this time, and the python-debugger is not working. I even tried to
re-install VScode, but nothing helped. Also, I tried to switch the debugger
to an earlier version but same issue.

Is there any other workaround for this? My productivity has been hindered
because of this. Looking forward for your help.

Regards,
Chetan

**Comment by int19h** [comment]
I can't think of anything that we have changed wrt this networking code in the past version (the past several, actually). But, based on what you describe, I wonder if it might be some kind of enterprise anti-malware interfering with what it perceives as suspicious network connections?

**Comment by srinidhiPY** [comment]
Thank you so much for your reply.

I am curious to know if it is some kind of enterprise anti-malware
interfering then why does the "run without debugging works" in VS code.
But, why not the debugging option?

Meanwhile, I will contact our IT support team and get back to you if I need
any help.

Thank you for your time and patience.

Regards,
Chetan

**Comment by int19h** [comment]
When running without debugging, there aren't all those debugger helper processes in the picture trying to communicate with each other using TCP sockets. I'm not entirely sure what's causing issues - the malware theory is, well, a theory - but the logs strongly imply some kind of external interference with connections; I can't make sense of it otherwise.

**Comment by srinidhiPY** [comment]
Thank you so much for your support. I will contact our IT support and
meanwhile, you can close this ticket for now. I will get back to you if I
need any assistance.

Regards,
Chetan

**Comment by doubleZ0108** [comment]
You can find my solution in https://github.com/microsoft/debugpy/issues/953#issuecomment-2270784588 .
