### ISSUE TITLE
VS-Code Python Remote Debugger issue: "Timed out waiting for debuggee to spawn"

### ISSUE THREAD

**Issue by srinidhiPY** [microsoft/debugpy#1282]
Hello,

I am having an issue with python debugger. It was working until very recently, but now I am getting this error after the update ""Timed out waiting for debuggee to spawn". I tried to re-install but it wasn't useful.

The debugger works on my local system, but I get the above error while doing remote debugging using [SSH FS].

Please, could you help me with this issue.

Details:
OS - Windows 10 Enterprise x64 10.0.19044
Python - 3.9.15
Conda - 4.10.3
VScode - 1.77.3
Sandboxed: No

**Comment by judej** [comment]
Thanks for the report, unfortunately, this is not enough data for us to debug. Could you please reopen this issue and send the repro steps for this?

If this continues to be a problem, would you please reopen the issue and add the information in the report as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?
