### ISSUE TITLE
Duplicate file tab during debugging on Windows (similar to closed issue #4166)

### ISSUE THREAD

**Issue by gdrolet** [microsoft/debugpy#129]
## Environment data

-   VS Code version: 

Version: 1.44.1 (user setup)
Commit: a9f8623ec050e5f0b44cc8ce8204a1455884749f
Date: 2020-04-11T01:48:12.622Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 6.1.7601

-   Extension version (available under the Extensions sidebar): 2020.3.71659 (2 April 2020)

-   OS and version: Windows 7 64-bit Professional Edition (SP1)

-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.7.5 (default, Oct 31 2019, 15:18:51) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32

-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): miniconda (conda 4.8.3)

-   Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): false

-   Value of the `python.languageServer` setting: Microsoft

## Expected behaviour

When debugger stops at breakpoint, if the file containing the breakpoint is opened in a tab, show the debugger cursor at breakpoint location in the opened tab.

## Actual behaviour

Opens a new tab with a copy of the file containing the breakpoint. 

## Steps to reproduce:

This issue has been coming and going for a while now but haven't figured out a cause yet.

1. Open a file in the editor and set a breakpoint inside a function.

2. Open a second script, the main, which contains a call to the function from the other opened script, where the breakpoint resides.

3. Run the debugger on the main script.

4. When reaching the breakpoint, a new tab opens, showing a copy of the already opened file.

Note: if the file containing the breakpoint is closed when I start the debugger on the main script, only one new tab opens up. Also, the file containing the breakpoint is in a src folder that I add to PYTHONPATH in a .env file:

PYTHONPATH=./src;${PYTHONPATH}

## Logs

> conda --version
> python3.7 -c "import sys;print(sys.executable)"
> pyenv root
> python3.6 -c "import sys;print(sys.executable)"
> python -c "import sys;print(sys.executable)"
> python3 -c "import sys;print(sys.executable)"
> python2 -c "import sys;print(sys.executable)"
> py -3.7 -c "import sys;print(sys.executable)"
> py -3.6 -c "import sys;print(sys.executable)"
> py -3 -c "import sys;print(sys.executable)"
> py -2 -c "import sys;print(sys.executable)"
> ~\AppData\Local\Continuum\miniconda3\envs\geospatial\python.exe -c "import sys;print(sys.executable)"
Starting Microsoft Python language server.
> ~\AppData\Local\Continuum\miniconda3\Scripts\conda.exe info --json
> ~\AppData\Local\Continuum\miniconda3\Scripts\conda.exe info --json
> ~\AppData\Local\Continuum\miniconda3\Scripts\conda.exe env list
> ~\AppData\Local\Continuum\miniconda3\Scripts\conda.exe info --json
> ~\AppData\Local\Continuum\miniconda3\Scripts\conda.exe info --json
> ~\AppData\Local\Continuum\miniconda3\Scripts\conda.exe info --json
> ~\AppData\Local\Continuum\miniconda3\envs\geospatial\python.exe -m pylint --generate-members --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text e:\Code\projects\mortality_hires_mauricie_2007\scripts\data\load_forestmap_asset.py
cwd: e:\Code\projects\mortality_hires_mauricie_2007
> ~\AppData\Local\Continuum\miniconda3\envs\geospatial\python.exe -m pylint --generate-members --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text e:\Code\projects\mortality_hires_mauricie_2007\scripts\data\load_forestmap_asset.py
cwd: e:\Code\projects\mortality_hires_mauricie_2007
> ~\AppData\Local\Continuum\miniconda3\Scripts\conda.exe env list
> ~\AppData\Local\Continuum\miniconda3\python.exe -c "import jupyter"
> ~\AppData\Local\Continuum\miniconda3\python.exe -c "import notebook"
##########Linting Output - pylint##########
> ~\AppData\Local\Continuum\miniconda3\python.exe -m jupyter kernelspec --version
> ~\AppData\Local\Continuum\miniconda3\envs\geospatial\python.exe -m pylint --generate-members --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text e:\code\projects\mortality_hires_mauricie_2007\src\geeutils.py
cwd: e:\code\projects\mortality_hires_mauricie_2007\src
> ~\AppData\Local\Continuum\miniconda3\envs\geospatial\python.exe -m pylint --generate-members --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text e:\code\projects\mortality_hires_mauricie_2007\src\geeutils.py
cwd: e:\code\projects\mortality_hires_mauricie_2007\src
##########Linting Output - pylint##########

**Comment by int19h** [comment]
Is the workspace folder unusual in any way? E.g. network share, or some kind of cloud storage like OneDrive or Dropbox.

**Comment by fabioz** [comment]
@gdrolet please include the logs you have when that happens.

i.e.:

* Open VS Code
* Select the command Extensions: Open Extensions Folder
* Locate the Python extension directory, typically of the form ms-python.python-2020.*.****
* In that directory ensure you do not have any debug*.log files, if you do, please delete them
* Go back into VS Code and modify your launch.json to add the setting "logToFile": true, see below:

```
"version": "0.2.0",
"configurations": [
    {
        "name": "Python: Current File (Integrated Terminal)",
        "type": "python",
        "request": "launch",
        "program": "${file}",
        "stopOnEntry": true,
        "console": "integratedTerminal",
        "logToFile": true
    },
```

* Start debugging
* When done, go back into the extension directory and upload the debug*.log files into this GitHub issue.

**Comment by judej** [comment]
Closing stale issue. Please reopen if needed
