### ISSUE TITLE
Unable to debug python files: Timed out waiting for debuggee to spawn

### ISSUE THREAD

**Issue by hbhuyt** [microsoft/debugpy#1294]
Before creating a new issue, please check the [FAQ](https://github.com/microsoft/debugpy/wiki/FAQ) to see if your question is answered there.

## Environment data

- debugpy version: 1.6.7
- OS and version: win10
- Python version : Winpython3.9.2
- Using VS Code: v1.78.1
## Actual behavior
My python code runs normally directly, but run in debug mode, timed out waiting for debuggee to spawn appears
mistake

my launch.json
{
    // 使用 IntelliSense 了解相关属性。 
    // 悬停以查看现有属性的描述。
    // 欲了解更多信息，请访问: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: 当前文件",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "justMyCode": true,
            "logToFile": true,
        }
    ]
}
here is my log files:
debug mode log:
https://github.com/hbhuyt/vscode-debug/blob/main/debug_log.7z
nodebug log:
https://github.com/hbhuyt/vscode-debug/blob/main/nodebug.7z

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
