### ISSUE TITLE
Why report "security issues" to Microsoft but not here? I am seeing Malware in debugpy

### ISSUE THREAD

**Issue by lundeen-bryan** [microsoft/debugpy#1309]
I just want to start a conversation here, not sure if the is is a bug or error. 

I'm kind of new to some of the apps that are installed by default in a Jupyter notebook environment for VS Code. But something was detected as malware. 
Perhaps you have a way for me to investigate deeper and figure out what is triggering the malware detection? 

![image](https://github.com/microsoft/debugpy/assets/13512507/ea0c25f2-6c13-48e2-8ed4-1611decd78f2)

There are a bunch of exe's here: \.venv\Lib\site-packages\debugpy\_vendored\pydevd\pydevd_attach_to_process\windows

I use "IObit Malware Fighter version 10.1" but I'm not familiar enough with the settings to get a log to show you where it found the malware. 

It's kind of hard to figure out exactly what is triggering the alert. Do you still want me to report this to Microsoft?

**Comment by gramster** [comment]
pydevd is a vendored dependency that is located here: https://github.com/fabioz/PyDev.Debugger. There is some native code in pydevd for DLL injection and other things. My guess is this is probably a false positive.  I'd try a different malware scanner and see if it also flags any of those files.

**Comment by judej** [comment]
Closing issue, no further action from Pylance
