### ISSUE TITLE
Issue 1160 should be reopened

### ISSUE THREAD

**Issue by soesto** [microsoft/debugpy#1312]
https://github.com/microsoft/debugpy/issues/1160 should be reopened

It happens in Windows 11, python 3.11, and only in VS code. Pdb from the command line works like a clockwork

**Comment by ManPython** [comment]
Edit your post with version info, config.

**Comment by soesto** [comment]
![image](https://github.com/microsoft/debugpy/assets/114020155/8eccfde7-09e0-412d-8ea8-a07009a1fa45)

Python is 3.11.4

**Comment by judej** [comment]
@soesto, could you please reopen the original issue? thanks

**Comment by soesto** [comment]
See comment in #1160
