### ISSUE TITLE
Debugger hung during the launch subprocess

### ISSUE THREAD

**Issue by inkcherry** [microsoft/debugpy#1314]
Hi, vscode team.
I encountered a scenario in my work environment that caused the debugger to hang. This scenario can be expressed by the following mechanism. May I ask how to solve this problem.

## Environment data

- debugpy version: 1.6.7
- OS and version: Ubuntu 22.04.1 
- Python version : 3.9.7
- Using VS Code:

## Actual behavior
debugger hang at subprocess launch, I found this subprocess is alive, but block  and can't attach.

## Expected  behavior
- when direct run with `python runner.py` or use debugger and set launch.json ```"subprocess":false```, get the following correct output
```shell
runner started
__init__ started
run cmd:  ['/home/inkc/miniconda3/envs/env4/bin/python', '/home/inkc/workspace/code_issue/packageA/../fun.py']
__init__ end
run module1 
runner finished
```
- when use debugger with the following launch.json, get the following output
```shell
runner started
__init__ started
run cmd:  ['/home/inkc/miniconda3/envs/env4/bin/python', '/home/inkc/workspace/code_issue/packageA/../fun.py']
```
forever hang
## Steps to reproduce:
- The directory structure is as follows, including four Python files
```shell
├── fun.py
├── packageA
│   ├── __init__.py
│   └── module1.py
└── runner.py
```
- file content

1. runner.py

```py
import subprocess
from argparse import ArgumentParser, REMAINDER
import sys

print('runner started')
cmd =[sys.executable, '-m', 'packageA.module1']
result = subprocess.Popen(cmd)
result.wait()
print('runner finished')
```

2. fun.py

```py
pass
```

3. packageA/\_\_init\_\_.py
```py
from subprocess import Popen, PIPE, run
import sys
from pathlib import Path
import os
python_file = os.path.join(Path(__file__).parent.absolute(), '../fun.py')
print('__init__ started')



cmd =[sys.executable, python_file]
print("run cmd: ", cmd)
p1 = Popen(cmd, stdout=PIPE, stderr=PIPE, stdin=PIPE)
output = p1.wait()

print('__init__ end')

```
4. packageA/module1.py

```py
print("run module1 ")
```

- launch.json
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "runner.py",
            "console": "integratedTerminal",
            "justMyCode": true,
            "subProcess": true
        }
    ]
}
```

**Comment by judej** [comment]
This looks related to frozen modules.


Adding the `-Xfrozen_modules=off` flag to the cmd in `runner.py` should fix it.

`cmd = [sys.executable, "-m -Xfrozen_modules=off", "packageA.module1"]`

if this does not fix the problem, please reopen this issue,

thanks
