### ISSUE TITLE
Bug: pydev debugger: unable to find translation for ...

### ISSUE THREAD

**Issue by h2appy** [microsoft/debugpy#1316]
Does this issue occur when all extensions are disabled?: Yes/No
There is the only one extension: Python(from Microsoft). And the issue is still there.

- VS Code Version: 1.79.1
- OS Version: macOS 13.4

Bug:
pydev debugger: unable to find translation for: "/Users/johnny/workspaces/vscode-bug-demo/project-b/foo.py" in ["/Users/johnny/workspaces/vscode-bug-demo/project-a/", "/Users/liqiang/workspaces/vscode-bug-demo/project-a"] (please revise your path mappings).

Steps to Reproduce:

I have created a repository which will be used to reproduce the bug:
[vscode-bug-demo
](https://github.com/h2appy/vscode-bug-demo)

**Comment by gramster** [comment]
The path mappings refer to project-a; do you need to add some for project-b?

**Comment by h2appy** [comment]
> The path mappings refer to project-a; do you need to add some for project-b?

Thanks for the suggestion!

After adding the following path mappings, the warning(pydev debugger: unable to find translation for...) disappeared.
"pathMappings": [
        { "localRoot": "${workspaceFolder}/project-a", "remoteRoot": "." },
        { "localRoot": "${workspaceFolder}/project-b", "remoteRoot": "." }
]

While, if we have multiple projects, we need to specify the path mappings for every project in each configuration. I think that this way of handling is redundant and counterintuitive. For example:
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Python: Remote Attach to project-a",
      "type": "python",
      "request": "attach",
      "connect": {
        "host": "localhost",
        "port": 5678
      },
      // If we have multiple projects, we need to specify the path mappings
      // for every project in the current configuration.
      // It's redundant and counterintuitive.
      "pathMappings": [
        { "localRoot": "${workspaceFolder}/project-a", "remoteRoot": "." },
        { "localRoot": "${workspaceFolder}/project-b", "remoteRoot": "." },
        { "localRoot": "${workspaceFolder}/project-c", "remoteRoot": "." }
      ],
      "justMyCode": true
    },
    {
      "name": "Python: Remote Attach to project-b",
      "type": "python",
      "request": "attach",
      "connect": { "host": "localhost", "port": 5679 },
      // If we have multiple projects, we need to specify the path mappings
      // for every project in the current configuration.
      // It's redundant and counterintuitive.
      "pathMappings": [
        { "localRoot": "${workspaceFolder}/project-a", "remoteRoot": "." },
        { "localRoot": "${workspaceFolder}/project-b", "remoteRoot": "." },
        { "localRoot": "${workspaceFolder}/project-c", "remoteRoot": "." }
      ],
      "justMyCode": true
    },
    {
      "name": "Python: Remote Attach to project-c",
      "type": "python",
      "request": "attach",
      "connect": { "host": "localhost", "port": 5680 },
      // If we have multiple projects, we need to specify the path mappings
      // for every project in the current configuration.
      // It's redundant and counterintuitive.
      "pathMappings": [
        { "localRoot": "${workspaceFolder}/project-a", "remoteRoot": "." },
        { "localRoot": "${workspaceFolder}/project-b", "remoteRoot": "." },
        { "localRoot": "${workspaceFolder}/project-c", "remoteRoot": "." }
      ],
      "justMyCode": true
    }
  ]
}
