### ISSUE TITLE
Incorrect member variable display

### ISSUE THREAD

**Issue by vitaminSP** [microsoft/debugpy#1318]
Type: <b>Bug</b>

When debugging this code:
```python
@dataclasses.dataclass(frozen=True)
class Test:
  UNHANDLED: ClassVar[object] = object()
  prefix: str = ""
  py_type: type = None.__class__
  type_handlers: tuple[type] = ()
aa = Test(py_type=int)
```

Variable `aa.py_type` is being displayed as a class variable (but has the correct value of `int` rather than `NoneType`), and `aa.UNHANDLED` is displayed as an instance variable.
In reality, `py_type` is an instance variable in this case, and `UNHANDLED` is a class variable.

Extension version: 2023.8.0
VS Code version: Code 1.78.2 (Universal) (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:44:45.204Z)
OS version: Darwin arm64 22.5.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.53GB free)|
|Process Argv|--crash-reporter-id 0eee40a4-88b5-40ec-a372-194eb64b779d|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by debonte** [comment]
![image](https://github.com/microsoft/debugpy/assets/12820898/6bb668b9-503f-4809-98da-271ae8f5721a)

**Comment by int19h** [comment]
The debugger shows variables as they actually are at runtime. In this case, even though it is a dataclass, until you reassign the attribute on the object, the value is actually coming from the class, so at runtime it is a class variable. Here's a simple example demonstrating this behavior without debugger in the picture:
```
from dataclasses import dataclass

class Foo: pass

@dataclass(frozen=True)
class Test:
    foo: Foo = Foo()

t1 = Test()
t2 = Test()
t1.foo.bar = 42
print(t2.foo.bar)
```
Broadly speaking, things that show up under "instance variables" for any given X are those that you can see in `dir(X)` output, while "class variables" correspond to `dir(X.__class__)`.
