### ISSUE TITLE
Debug mode spawns a new "Python Debug Console" every time with `console` set to `integratedTerminal`

### ISSUE THREAD

**Issue by LightCC** [microsoft/debugpy#132]
## Environment data

- VS Code version: 
---
- Version: 1.38.1 (user setup)
- Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
- Date: 2019-09-11T13:35:15.005Z
- Electron: 4.2.10
- Chrome: 69.0.3497.128
- Node.js: 10.11.0
- V8: 6.9.427.31-electron.0
- OS: Windows_NT x64 10.0.17763
---
- Extension version (available under the Extensions sidebar): 2019.10.41019
- OS and version: Windows 10
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.4
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
- Relevant/affected Python packages and their versions: builtin
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): not jedi

## Expected behaviour

With the `"console": "integratedTerminal"` setting, when a file is debugged or the debugger is restarted, if there is an existing "Python Debug Console" terminal, it will be reused.

This is what happens with the default "internalConsole" setting, which reuses the `DEBUG CONSOLE` terminal tab with every launch. (However, the `DEBUG CONSOLE` cannot accept keyboard input, among other limitations.)

## Actual behaviour

The first debug will create a new "Python Debug Console" in the `TERMINAL` tab of the terminal window:
![image](https://user-images.githubusercontent.com/19731713/66689429-c94c2a80-ec58-11e9-9ea0-8af837b85f4e.png)

Every additional time debug is launched or restarted, instead of reusing an existing "Python Debug Console", a new terminal (with the same name) is spawned. These will eventually cause problems with the system, and need to be manually trashed.
![image](https://user-images.githubusercontent.com/19731713/66689520-4bd4ea00-ec59-11e9-85ef-c64096f53549.png)

I was getting VS Code errors after 20-30 of these were spawned, before I even realized this was happening.

## Steps to reproduce:
1. Setup Debug for "integratedTerminal" (set `"console":` setting to `"integratedTerminal"` in `launch.json` for `Python: Current File` or other Python launch configuration).
2. Debug a python script more than once.

## Logs
N/A

**Comment by int19h** [comment]
Not something we can fix on debugpy side.
