### ISSUE TITLE
Cannot debug Jupyter notebooks (through breakpoints) which are executed by other Python process 

### ISSUE THREAD

**Issue by nishikantparmariam** [microsoft/debugpy#1321]
## Environment data

- debugpy version: **1.6.6**
- OS and version: **Linux, RHEL8**
- Python version (& distribution if applicable, e.g. Anaconda): **3.10.4**
- Using VS Code or Visual Studio: **1.79.1**

## Actual behavior

When a breakpoint is set on an `.ipynb` file, then while debugging, it turns into `Breakpoint in file that does not exist` and execution does not stop. My use case it to set breakpoints in `.ipynb` file which are accepted as input in other Python programs e.g. nbconvert (See launch.json below), or **[panel serve](https://panel.holoviz.org/api/cheatsheet.html#panel-serve-app-ipynb)**.

## Expected  behavior

The debugging should work as expected with the breakpoint.

## Steps to reproduce:

![debug-ipynb](https://github.com/microsoft/debugpy/assets/7736252/21dcb80c-5193-4d6a-bedb-cf01817c32b6)

- Create an `.ipynb` file and set breakpoint
- Use this `launch.json` - 
  
  ```json
  {
    "version": "0.2.0",
    "configurations": [
      {
        "name": "Python: Debug Notebook",
        "type": "python",
        "request": "launch",
        "module": "jupyter",
        "args": [
            "nbconvert",
            "--to",
            "notebook",
            "--execute",
            "${file}"
        ],
        "logToFile": true
      }
    ]
  } 
  ``` 

My actual use-case is to do remote debugging through `debugpy` but it seems like it does not work for local debugging itself. Are there solutions / workarounds for this or is this expected ? Would be happy to add more details as needed. Let me know if this could be better answered on https://github.com/microsoft/vscode-jupyter.

**Comment by gramster** [comment]
Those breakpoints you set in the Visual Studio Code user interface are for when you run the notebook code in Visual Studio Code; they won't work while running nbconvert.

**Comment by nishikantparmariam** [comment]
Thanks @gramster for the response, so this seems expected. Are there any workarounds here or some ongoing work related to this?

**Comment by gramster** [comment]
I don't think there are any trivial workarounds. I'm a bit confused as to why you would want a breakpoint to fire while running nbconvert though; can you elaborate more on your use case?

**Comment by nishikantparmariam** [comment]
Hi @gramster, sorry for the delayed response here. Can we please re-open this issue? I am adding the use case below.

[Panel](https://panel.holoviz.org/index.html) is an open-sourced library that allows to build dashboards entirely in Python. We can bring up a Panel server using `panel serve /path/to/app.ipynb` command.

My use-case is to interactively debug Panel apps inside VSCode i.e. when I interact with my app in browser, I want to inspect variables live etc., see this GIF - 

![panel-py-debugging-vscode](https://github.com/microsoft/debugpy/assets/7736252/d0afe76f-41a2-40d1-94ec-a118099e90f0)

[See debugging guide from Panel](https://panel.holoviz.org/how_to/editor/vscode_configure.html#debugging)

`launch.json` file looks like - 

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Panel Serve",
            "type": "python",
            "request": "launch",
            "program": "-m",
            "args": [
                "panel",
                "serve",
                "/absolute/path/to/app.py",
            ],
            "console": "integratedTerminal",
            "justMyCode": true
        },
    ]
}
```

The problem is, I am not able to set breakpoints when I write Panel apps in notebooks (`.ipynb`). Developing apps in notebooks provides interactive experience so it is preferred. See the below image where I get `Breakpoint in file that does not exist` when I set a breakpoint and  hover over it -

![vscode-debugging-ipynb](https://github.com/microsoft/debugpy/assets/7736252/3cda2fc8-4d1c-4634-9991-97fd536e3d68)

`launch.json` for this looks same as above with just path being - `/absolute/path/to/app.ipynb`.

Please let me know if more details are needed here.

**Comment by nishikantparmariam** [comment]
cc: @gramster, let me know if I should open a new issue. Thanks!

**Comment by nishikantparmariam** [comment]
I created new issue https://github.com/microsoft/debugpy/issues/1400 due to inactivity here. Thanks!
