### ISSUE TITLE
The v1.6.8 tag complicates building a v1.6.7 distribution

### ISSUE THREAD

**Issue by reytchison** [microsoft/debugpy#1339]
The new `v1.6.8` tag is on the same commit as `v1.6.7`. I know this is intentional, but it makes it harder to build a `v1.6.7` distribution. 

When I try to build a `v1.6.7` distribution, I now build `debugpy-1.6.8.tar.gz` and `debugpy-1.6.8-cp38-cp38-linux_x86_64.whl`: 
```
git clone https://github.com/microsoft/debugpy.git -b v1.6.7
cd debugpy
python -m build
```
I will note a workaround to build a `v1.6.7` distribution is to delete the conflicting tag: `git tag -d v1.6.8`

**Comment by AdamYoblick** [comment]
I apologize for this. I'm testing our new release mechanism out and I didn't want to blow away the existing 1.6.7 in PyPi. So I had to create a new release to do this, since debugpy uses versioneer and it's driven off the tag. I'm not sure that I could have done it any other way ☹️

**Comment by int19h** [comment]
The tag is gone now so this should be working.
