### ISSUE TITLE
Could not find a version that satisfies the requirement debugpy==1.6.8

### ISSUE THREAD

**Issue by huyhoang8398** [microsoft/debugpy#1345]
Before creating a new issue, please check the [FAQ](https://github.com/microsoft/debugpy/wiki/FAQ) to see if your question is answered there.

## Environment data

- OS and version: MacOS 11.7.6
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.10.4 using venv
- Using Neovim ( Pip install)
## Actual behavior
        Installing pip package debugpy@1.6.8…
        ERROR: Could not find a version that satisfies the requirement debugpy==1.6.8 (from versions: 1.0.0b1, 1.0.0b2, 1.0.0b3, 1.0.0b4, 1.0.0b5, 1.0.0b6, 1.0.0b7, 1.0.0b8, 1.0.0b9, 1.0.0b10, 1.0.0b11, 1.0.0b12, 1.0.0rc1, 1.0.0rc2, 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.4.0, 1.4.1, 1.4.2, 1.4.2.post1, 1.4.3, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7)
        ERROR: No matching distribution found for debugpy==1.6.8
        spawn: /Users/kn/.local/share/nvim/mason/packages/debugpy/venv/bin/python failed with exit code 1 and signal 0. 

## Expected  behavior

Install successfully debuggpy

## Steps to reproduce:
1. pip install debugpy

**Comment by mecampbellsoup** [comment]
My guess is this is because `1.6.8` was (attempted) published to PyPI, which recognized the [commit was the same as `1.6.7`](https://github.com/microsoft/debugpy/releases/tag/v1.6.8), and didn't publish anything...

Either that or the PyPI automation they were testing w/ the `1.6.8` release didn't work!

**Comment by temporal7** [comment]
I found a workaround that involves manually installing `debugpy` in a way that matches `Mason`'s installation process: create the directory  `~/.local/share/nvim/mason/packages/debugpy/venv`, install a virtual environment in the `venv` directory, then install `debugpy` with that virtual environment's `pip` using `~/.local/share/nvim/mason/packages/debugpy/venv/bin/pip install debugpy`.

---

In your particular case @huyhoang8398, I believe you would execute the following (if you haven't done so already):

```
mkdir /Users/kn/.local/share/nvim/mason/packages/debugpy/venv/ -p
python -m venv /Users/kn/.local/share/nvim/mason/packages/debugpy/venv
/Users/kn/.local/share/nvim/mason/packages/debugpy/venv/bin/pip install debugpy
```

After that, try opening up Neovim and doing `:Mason` to confirm that `debugpy` is installed.

---

Granted, I'm using a Linux distribution while it appears that you are on a Mac system, so I'm not 100% sure if these commands will work perfectly (especially in the case of `mkdir -p`, which is meant to create the directory and any "parents" that contain that directory). In that case though, you can just use whatever means or methods you have to **create the directory**,  **create a virtual environment in that directory**, and **use the `pip` from that virtual environment to install `debugpy`**. Hopefully this works while we wait for the correct version to appear on PyPI.

**Comment by GiorgosXou** [comment]
@temporal7 I did this too, but I'm stuck with this error:
```terminal
E5108: Error executing lua: /home/xou/.local/share/nvim/lazy/nvim-dap/lua/dap.lua:493: .../xou/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1319: adapter.command must not be empty. Got: {
  command = "",
  type = "executable"
}
stack traceback:
        [C]: in function 'trigger_run'
        /home/xou/.local/share/nvim/lazy/nvim-dap/lua/dap.lua:493: in function 'run'
        /home/xou/.local/share/nvim/lazy/nvim-dap/lua/dap.lua:406: in function 'cb'
        /home/xou/.local/share/nvim/lazy/nvim-dap/lua/dap/ui.lua:34: in function 'pick_if_many'
        /home/xou/.local/share/nvim/lazy/nvim-dap/lua/dap.lua:400: in function 'select_config_and_run'
        /home/xou/.local/share/nvim/lazy/nvim-dap/lua/dap.lua:871: in function 'continue'
        /home/xou/.config/nvim/lua/astronvim/mappings.lua:358: in function </home/xou/.config/nvim/lua/astronvim/mappings.lua:358>
Press ENTER or type command to continue
```
[cross-reference to a post in AstroNvim's discord server](https://discord.com/channels/939594913560031363/1137223909754814574)

**Comment by saiwing-yeung** [comment]
This works for me:
`:MasonInstall debugpy@1.6.7`

**Comment by iceychris** [comment]
My `Pipfile.lock` (using [pipenv](https://github.com/pypa/pipenv)) currently contains this:

```json
"debugpy": {
    "hashes": [
        "sha256:05d1b288167ce3bfc8e1912ebed036207a27b9569ae4476f18287902501689c6",
        "sha256:1ca76d3ebb0e6368e107cf2e005e848d3c7705a5b513fdf65470a6f4e49a2de7",
        "sha256:1fe3baa28f5a14d8d2a60dded9ea088e27b33f1854ae9a0a1faa1ba03a8b7e47",
        "(more hashes...)"
    ],
    "markers": "python_version >= '3.7'",
    "version": "==1.6.8"
}
```

So It seems like for some short period of time (probably while invoking `pipenv lock`), the `1.6.8` release _kinda was present_ on pypi... (?)
 
Trying to install `1.6.8` explicitly now fails:
 
 ```bash
$ pip3 uninstall -y debugpy && pip3 install debugpy==1.6.8
WARNING: Skipping debugpy as it is not installed.
ERROR: Could not find a version that satisfies the requirement debugpy==1.6.8 (from versions: 1.0.0b1, 1.0.0b2, 1.0.0b3, 1.0.0b4, 1.0.0b5, 1.0.0b6, 1.0.0b7, 1.0.0b8, 1.0.0b9, 1.0.0b10, 1.0.0b11, 1.0.0b12, 1.0.0rc1, 1.0.0rc2, 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.4.0, 1.4.1, 1.4.2, 1.4.2.post1, 1.4.3, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7)
ERROR: No matching distribution found for debugpy==1.6.8
```

So yea, I guess one workaround is pinning to `1.6.7`.

**Comment by sailorbob134280** [comment]
> This works for me: `:MasonInstall debugpy@1.6.7`

That worked for me too

**Comment by sshishov** [comment]
We are having the same issue!

But at least we can track it back and understand what happened. The release 1.6.8 was actually published, and our dependabot integration created an MR to update the dependency (what we did)

<img width="756" alt="Screenshot 2023-08-06 at 15 50 07" src="https://github.com/microsoft/debugpy/assets/2711700/99c7efee-1afd-44bb-9da8-05717146a612">

I guess it is very **unprofessional** to release something to public (for testing) and then just remove it. At least the release should be **YANKED** form PyPi (at least it will produce the visual explanation).

By now I agree that we should just move back to `1.6.7` (and if you have a pin, you should update it).

**Comment by samedii** [comment]
Forced to pin the version because of this...

**Comment by sinwoobang** [comment]
Same here. One of the granted contributors might need to take action.

**Comment by kiblik** [comment]
@AdamYoblick, I noticed your comment for release [`v1.6.8`](https://github.com/microsoft/debugpy/releases/tag/v1.6.8)
> This release is identical to 1.6.7. It uses the same commit.
> The purpose of this release is to test the new automated release pipeline we've created to deploy to PyPi.

For me, it looks like the pipeline does not work because there is no package in https://pypi.org/project/debugpy/#history named `1.6.8`.

Can you check it, please?

**Comment by sylvainmouquet** [comment]
poetry allows to install the release 1.6.8 as the latest version available but the package is not present in pypi

**Comment by AdamYoblick** [comment]
1.6.8 was actually yanked from PyPi because of a signing issue. I’m going to remove the release from this repo and make a new release which doesn’t break people’s processes.

Something like 1.6.7.post1

I’ll get that done this week :)
________________________________

**Comment by AdamYoblick** [comment]
Sorry again for all the problems everyone, I should have removed the 1.6.8 tag and release when we pulled it from pypi. My fault. I'm new to this product and python releases in general, so I'm still learning. Appreciate the information 😄

**Comment by AdamYoblick** [comment]
Tag and release have been removed, 1.6.7 is the latest tag and release for now.

I still need to test the release pipeline with proper signing, so the test release will be something like 1.6.7.post1.

Going to close out this issue since the offending release has been removed.

**Comment by AdamYoblick** [comment]
> We are having the same issue!
> 
> But at least we can track it back and understand what happened. The release 1.6.8 was actually published, and our dependabot integration created an MR to update the dependency (what we did)
> 
> Dependabot MR details
> I guess it is very **unprofessional** to release something to public (for testing) and then just remove it. At least the release should be **YANKED** form PyPi (at least it will produce the visual explanation).
> 
> By now I agree that we should just move back to `1.6.7` (and if you have a pin, you should update it).

Yeah sorry about this. The release was yanked, but we decided to actually remove it because of the signing issue. Won't happen again 😄

**Comment by AdamYoblick** [comment]
I was also unaware that versioneer (or maybe the way we're using it), which is what debugpy uses for versioning, requires a github release with an associated github tag. AND if the commit is the same commit as the previous release, it causes all sorts of problems, which is silly imo. But now we know 🤷

**Comment by sshishov** [comment]
Thanks for the updates @AdamYoblick . The good think that the issue has been resolved and we are lerning from the mistakes and oversights. Sorry for my arrogant sentence with "in-bold" words... just was a little bit frustrated that pipeline start failing all of a sudden...

I was just always thinking that it would be enough to YANK the release from pypy that pip will not try to install it, but pinned dependencies it is getting a little bit more complex, after yanked release (I assume) we should release next patch release the same as 1.6.7 or with just some fake commit to update the SHA that users will not stuck in yanked release and their dependabot would update the package automatically.

But the is no great solution here anyways, the best is to notify users about broken release and ask them to pin old version meanwhile, create some issue to track the progress and people can just subscribe to the updates of that issue... everything is imho!

**Comment by AdamYoblick** [comment]
1.6.7.post1 has been tagged, released, and available on pypi. The commit hash is different from the 1.6.7 release. Since we've now proven that the new release pipeline works, there won't be any more of these test releases. Thanks again for understanding, and sorry again for causing headache to anyone 😄

**Comment by isaac-hazy** [comment]
Is this really fully fixed?  I'm still getting poetry trying to install 1.6.8 and then failing to find it.  Workaround at the moment is to pin to <1.6.8 but that's not ideal.

**Comment by AdamYoblick** [comment]
There is no 1.6.8 anywhere on GitHub nor on PyPi.org, so the problem should be fixed on our end.

Does poetry do some sort of version caching? If you can provide repro steps, I can look into it :)
________________________________

**Comment by karthiknadig** [comment]
This can happen if the poetry lock file has a reference to 1.6.8 from when it was still out. As you can see here there is no reference to it if you query pypi: https://pypi.org/simple/debugpy/
