### ISSUE TITLE
Debug Console output from different subprocesses is merged incorrectly

### ISSUE THREAD

**Issue by bersbersbers** [microsoft/debugpy#135]
## Environment data

-   VS Code version: 1.44.2
-   Extension version (available under the Extensions sidebar): 2020.3.71659
-   OS and version: Win 10, 1909
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.2
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): none

## Expected behaviour

`Python: Current File` output in Debug Console shows 100 lines of 
```
1234567890
```

## Actual behaviour
Output looks largely okay, except line breaks appear in odd places and are missing elsewhere:
```
...
1234567890
1234567890
12345678901234567890
1234567890

1234567890
1234567890
1234567890
...
```

This happens several (e.g., 2) times per 100 lines of output. Regardless of `"console": "internalConsole"`. But does not happen when running `python bug.py` in terminal.

## Steps to reproduce:

```
from multiprocessing import Pool

def fun(_):
    print("1234567890")

Pool(10).map(fun, range(100))
```

## Logs

Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

(nothing relevant, only linters)

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`; turn on source maps to make any tracebacks be useful by running `Enable source map support for extension debugging`)

(don't think this is relevant here)

**Comment by int19h** [comment]
Python does separate writes for the string you pass to `print()` and for the newline, so these usually get captured as separate "output" events - and output from different processes is not synchronized.

The reason why this kinda sorta works when outputting directly to the terminal is because stdout is line-buffered in that scenario, so the entire line including the newline only gets flushed when that newline shows up. But I don't think it actually guarantees that output will never interleave - it just makes it less likely.

**Comment by bersbersbers** [comment]
> The reason why this kinda sorta works when outputting directly to the terminal is [...] But I don't think it actually guarantees that output will never interleave - it just makes it less likely.

You are right, and it's even worse. When looping a million (instead of 100) times in the terminal, I get 20-200 lines like this, that is, 10-100 problems.
```
> python bug.py | grep -v "^1234567890$"
12345678901234567890
12345678901234567890
12345678901234567890
12345678901234567890
12345678901234567890
12345678901234567890
12345678901234567890
12345678901234567890
12345678901234567890
1234567
1234567890890
123456
12345678907890
123
1234567
1234567
1234567890890
12345678904567890
1234567
1234567890890890
123456
12345678907890
123456
12345678907890
12
12
12
12
123456789034567890
123456789034567890
123456789034567890
123456789034567890
1234567
12
12
12
12
123456789034567890
123456789034567890
123456
123456789034567890
123456789034567890
1234567890890
12
12
12345678907890
123456789034567890
123456789034567890
12
12
12
12
12
123456789034567890
123456789034567890
123456789034567890
123456789034567890
123456789034567890
123456
1234567
1234567
1234567890890
12345678907890
1234567890890
123
12345678904567890
12
12
12
12
123456789034567890
123456789034567890
123456789034567890
123456789034567890
123
12345678904567890
1234567
12
12
12
12
123456789034567890
123456789034567890
123456789034567890
123456789089034567890
123456
12345678907890
12
12
12
12
123456789034567890
123456789034567890
123456789034567890
123456
123456789034567890
1234567
1234567
12345678908907890
1234567890890
12
12
12
123456789034567890
123456789034567890
123456789034567890
123456
12
12
12
12
123456789034567890
123456789034567890
123456789034567890
12345678907890
123456789034567890
123456
12345678907890
123
12345678904567890
123
12345678904567890
123
12
12345678904567890
123456789034567890
123456
12345678907890
1234567
1234567890890
123
12345678904567890
1234567
1234567890890
12
123456789034567890
1234567
1234567890890
123456
12345678907890
123
12345678904567890
123
12345678904567890
123
12345678904567890
1234567
1234567890890
123456
12345678907890
1234567
1234567890890
1234567
1234567890890
123
12345678904567890
12
123456789034567890
12
123456789034567890
1234567
1234567890890








```

**Comment by fabioz** [comment]
Closing as the behavior in the debugger seems to be correct.

If you need to sync output, my suggestion would be synchronizing it through a queue.

For this example it'd be something as:

```
import multiprocessing
import threading


class PrinterThread(threading.Thread):

    def __init__(self, queue):
        threading.Thread.__init__(self)
        self._queue = queue

    def run(self):
        while True:
            output = self._queue.get()
            if output == Finish:
                return
            print(output)


class Finish(object):
    pass


def fun(queue):
    queue.put("1234567890")


def main():
    manager = multiprocessing.Manager()
    queue = manager.Queue()
    t = PrinterThread(queue)
    t.start()

    pool = multiprocessing.Pool(10)
    pool.map(fun, [queue for _ in range(1000)])
    queue.put(Finish)


if __name__ == '__main__':
    main()
```
