### ISSUE TITLE
pythonArgs is ignored

### ISSUE THREAD

**Issue by fehrlich** [microsoft/debugpy#1360]
Type: <b>Bug</b>

In the launch file:
```json
        {
            "name": "Bugreport",
            "type": "python",
            "request": "launch",
            "module": "pytest",
            "pythonArgs": ["-Xfrozen_modules=off"],
            "args": [
                "mytestfile.py"
            ]
        },
```
Produces following command:

` cd ...; /usr/bin/env ....conda\\envs\\sleepy\\python.exe ....vscode\\extensions\\ms-python.python-2023.14.0\\pythonFiles\\lib\\python\\debugpy\\adapter/../..\\debugpy\\launcher 63663 -- -m pytest mytestfile.py `

Also for a file:

```json
        {
            "name": "Bugreport",
            "type": "python",
            "request": "launch",
            "program": "mytestfile.py",
            "pythonArgs": ["-Xfrozen_modules=off"],
        },
```

In Powershell:
`& '...\.conda\envs\sleepy\python.exe' '...\.vscode\extensions\ms-python.python-2023.14.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher' '64012' '--' 'mytestfile.py'`

Extension version: 2023.14.0
VS Code version: Code 1.80.2 (2ccd690cbff1569e4a83d7c43d45101f817401dc, 2023-07-27T20:40:28.909Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Connection to 'ssh-remote+sv-teleschlaf-ml' could not be established
Remote OS version: Linux x64 3.10.0-1127.19.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.65GB (8.65GB free)|
|Process Argv|--crash-reporter-id 7d0a7228-5ef5-4f67-8ba3-8e0cc7362eb6|
|Screen Reader|no|
|VM|0%|

removed remote connections
 
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
282f8724:30602487
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30812748

```

</details>

**Comment by int19h** [comment]
The command line that you're seeing is the one that spawns the debugpy launcher, whereas "python" and "pythonArgs" are used by the launcher to construct the command line to run the actual program being debugged. 

You can control the Python interpreter used to spawn the launcher via the undocumented "debugLauncherPython" debug config property, but there's no way to control the interpreter arguments beyond that.
