### ISSUE TITLE
test_gevent is failing

### ISSUE THREAD

**Issue by int19h** [microsoft/debugpy#1375]
Due to warning for deprecated usage of pkg_resources in more recent versions of setuptools.

**Comment by int19h** [comment]
Fixed by https://github.com/microsoft/debugpy/pull/1374

**Comment by kira-bruneau** [comment]
Hi @int19h! It looks like we're still having this problem in python versions older than 3.7 in nixpkgs. Was just wondering if you had any insight for why it'd still be failing: https://github.com/NixOS/nixpkgs/pull/255379#pullrequestreview-1630121817.

Adding `importlib-metadata` as a test dependency doesn't seem to make a difference.

**Comment by int19h** [comment]
`importlib-metadata` is really only used for logging. The problem with `gevent` is a different issue - it's due to an incompatibility between `gevent` and newer versions of `setuptools`. You have to use `setuptools<66` to fix it.

Also note that any version of debugpy >=1.6.0 doesn't support versions of Python older than 3.7, and debugpy>=1.8.0 requires python>=3.8.

**Comment by kira-bruneau** [comment]
Oh yep!! We've marked python 3.8 as the minimum compatible python version in the 1.8.0 update.

We were just seeing this deprecation warning in newer versions of python too. From what I can tell, it looks like the `setuptools<66` workaround was only being used for python 3.7?

**Comment by int19h** [comment]
Yep, that's the only version for which it showed up in our CI runs. Although I believe the problem there wasn't actually with Python itself, but rather with setuptools version that is bundled with it; if it's too old, it ends up being updated to the most recent version as a transitive dependency of something else (IIRC, tox itself), causing the problem.

**Comment by kira-bruneau** [comment]
Oh ok that makes sense! In nixpkgs, we package setuptools ourselves, so it would generally always be the latest version. Thanks!! 😊
