### ISSUE TITLE
debugger generally slower than command line for big loops

### ISSUE THREAD

**Issue by wz0919** [microsoft/debugpy#1378]
I've tested the performance of Vscode debugger with big loops. The code is very simple:
```
import tqdm
a = list(range(40000))

for _ in tqdm.tqdm(a):
    for __ in a:
        pass
```

However, on three computers (including one Mac M1 pro and two Centos 7),  using `Debug Python File` to debug it will be at least two times slower than using `Run Python File` to run it with the command line. Is this a general issue for debugpy?

## Environment data

- debugpy version: 2023.4.0
- OS and version: Mac M1 Pro and Centos 7
- Python version (& distribution if applicable, e.g. Anaconda): 3.10.9
- Using VS Code or Visual Studio: Vscode

## Actual behavior

Using debugpy has 2~3 x times slower speed than running with command line for big loops.

## Expected  behavior

I expect using debugpy should has similar speed to command line running.

## Steps to reproduce:

Just create a python script:
```
import tqdm
a = list(range(40000))

for _ in tqdm.tqdm(a):
    for __ in a:
        pass
```

Then with this script open, click `Debug Python File`/`Run Python File` button on the top right of the IDE (next to the `Split Editor...` button) to test the speed of debugging/running.

**Comment by int19h** [comment]
This is fairly typical for Python debuggers - the overhead comes from the callback-based tracing API offered by the VM. 

https://peps.python.org/pep-0669/ is a new API added in Python 3.12 to improve this situation, but it will take time for us to make use of that.

**Comment by wz0919** [comment]
> This is fairly typical for Python debuggers - the overhead comes from the callback-based tracing API offered by the VM.
> 
> https://peps.python.org/pep-0669/ is a new API added in Python 3.12 to improve this situation, but it will take time for us to make use of that.

Thanks for your prompt answer! Looking forward to seeing some improvements in the future.

**Comment by ElDavoo** [comment]
> it will take time for us to make use of that.

Hello, is there a tracker issue for this enhancement? Thank you!

**Comment by int19h** [comment]
That would be https://github.com/microsoft/debugpy/issues/1419
