### ISSUE TITLE
Error while enumerating installed packages.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/debugpy#1379]
**Describe the bug**

![image](https://github.com/microsoft/PTVS/assets/82852072/be2dd9af-3175-46a5-ac14-a4ae1463f884)

**Steps to Reproduce**

1. Create a Python Application project.
2. Type
```
import debugpy
print(debugpy.__version__)
debugpy.listen(("localhost", 5678))
debugpy.wait_for_client()
print('hello')
```
3. Set a breakpoint on the ```print('hello')```. (Note: Install debugpy in the current environment.)
4. Start Without Debugging.

**Expected behavior**
 
No error.

**Additional context and screenshots**

Error while enumerating installed packages.

![image](https://github.com/microsoft/PTVS/assets/82852072/b8b42b8b-fd43-4b91-8722-0b9849f72172)

## Logs

<details>
<p>

```
1.7.0
E+00000.047: Error while enumerating installed packages.

             Traceback (most recent call last):
               File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\debugpy\common\log.py", line 361, in get_environment_description
                 report("    {0}=={1}\n", pkg.name, pkg.version)
             AttributeError: 'PathDistribution' object has no attribute 'name'

             Stack where logged:
               File "C:\Users\vting\source\repos\PythonApplication2\PythonApplication2\PythonApplication2.py", line 4, in <module>
                 debugpy.listen(("localhost", 5678))
               File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\debugpy\public_api.py", line 31, in wrapper
                 return wrapped(*args, **kwargs)
               File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\debugpy\server\api.py", line 122, in debug
                 ensure_logging()
               File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\debugpy\server\api.py", line 61, in ensure_logging
                 log.describe_environment("Initial environment:")
               File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\debugpy\common\log.py", line 369, in describe_environment
                 info("{0}", get_environment_description(header))
               File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\debugpy\common\log.py", line 363, in get_environment_description
                 swallow_exception("Error while enumerating installed packages.")
               File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\debugpy\common\log.py", line 215, in swallow_exception
                 _exception(format_string, *args, **kwargs)
```

</p>
</details>

**Comment by int19h** [comment]
If `importlib-metadata` is installed, try upgrading it. It seems that there are some incompatibilities of older versions with some packages.

**Comment by int19h** [comment]
@ttSpace Can you please try the following. Locate debugpy/common/log.py under site-packages (following the path you see in the output). Find the line in that file that says:
```
swallow_exception("Error while enumerating installed packages.")
```
replace it with:
swallow_exception("Error while enumerating installed packages.", level="info")

Does it help?

**Comment by ttSpace** [comment]
@int19h @StellaHuang95 

No errors after installing ```importlib-metadata```.

![image](https://github.com/microsoft/debugpy/assets/82852072/6314b720-7de0-41c8-bf82-d17f90c21793)

> @ttSpace Can you please try the following. Locate debugpy/common/log.py under site-packages (following the path you see in the output). Find the line in that file that says:
> 
> ```python
> swallow_exception("Error while enumerating installed packages.")
> ```
> 
> replace it with:
> 
> ```python
> swallow_exception("Error while enumerating installed packages.", level="info")
> ```
> 
> Does that help?

No errors after replacement.

![image](https://github.com/microsoft/debugpy/assets/82852072/a5e006db-0934-4436-8b4b-3141a9ad55d3)

**Comment by mingp** [comment]
I am encountering the same issue. For whatever it's worth, I tried upgrading `importlib-metadata`, and it did not help.

My installed versions are as follows:
```
debugpy==1.7.0

importlib-metadata==4.11.3 # before upgrade
importlib-metadata==6.8.0 # after upgrade
```

Because I'm encountering this issue in a work codebase, whose dependencies are managed using Bazel, it's not easy for me to swap out a locally-vendored version to test that.

**Comment by mingp** [comment]
I downgraded the version of `debugpy` as follows:

```
debugpy==1.6.7
```

This at least avoids this particular issue. Putting this here in case it might help anyone else.

But, it's unclear to me yet if it's working end-to-end, because I have not yet been able to connect VS Code, and it's unclear to me yet if that's an error on my part.

**Comment by int19h** [comment]
It should not affect operation other than the message being printed.

`debugpy` itself doesn't have any dependencies other than the Python stdlib, and is runnable directly from the repo tree (i.e. you should be able to just clone or copy the source directory and then do `python src/debugpy` to run it from command line). I'm pretty sure that the above line would be sufficient to fix it but I'd love to test it before pushing out an update.

**Comment by mingp** [comment]
I was able to get the VS Code debugger working end-to-end on `debugpy==1.6.7`. Putting this here in case it might help anyone else.

**Comment by SushNag** [comment]
> @ttSpace Can you please try the following. Locate debugpy/common/log.py under site-packages (following the path you see in the output). Find the line in that file that says:
> 
> ```python
> swallow_exception("Error while enumerating installed packages.")
> ```
> 
> replace it with:
> 
> ```python
> swallow_exception("Error while enumerating installed packages.", level="info")
> ```
> 
> Does that help?

This worked for me, Thanks

**Comment by fartzy** [comment]
> debugpy==1.6.7

Thank you so much, yes this worked for me too

**Comment by styk-tv** [comment]
> Could you also install the `importlib-metadata` and try again?

2 hours of wasted life. typical microsoft - above fixed error `conda install importlib-metadata`

**Comment by int19h** [comment]
The workaround should not be necessary on current debugpy versions. Please let me know if you're running into some issue.

**Comment by bearrito** [comment]
Is this fixed with the extension?
