### ISSUE TITLE
Is not possible to execute debug modules using configurations declared on launch.json file 

### ISSUE THREAD

**Issue by cpinamtz** [microsoft/debugpy#138]
# WARNING! This was working fine previous to 1.44 version

## Environment data

-   VS Code version: 1.44.2
-   Extension version: 2020.3.71659
-   OS and version: Ubuntu 18.04.4 LTS 64 bit
-   Python version: 3.6.9
-   Type of virtual environment used: virtualenvwrapper
-   Jedi or Language Server?: Jedi
-   Value of the `python.languageServer` setting: Microsoft

## Expected behaviour

Execute a task from `launch.json` file which behind the scenes calls Python `hug` module to execute the desired module.

## Actual behaviour

Running the desired task which is selected from a set of `inputs` declared on the `launch.json` file. Output of the execution on the VSCode console:
```bash
$ env DEBUGPY_LAUNCHER_PORT=$RANDOM_PORT $PYTHON_BIN_PATH_VENV \
$HOME/.vscode/extensions/ms-python.python-2020.3.71659/pythonFiles/lib/python/debugpy/no_wheels/debugpy/launcher \
 "hug -f data-export/export/commands.py -c export --job ${input:task_name}"
```

launch.json task is the following:
```json
{
    "name": "Python: Batch export jobs",
    "type": "python",
    "request": "launch",
    "program": "hug -f /export/commands.py -c export --job ${input:task_name}",
    "cwd": "${workspaceFolder}",
}
```
I've also tried to remove the `cwd` attribute and place it into the `program` attribute to create the absolute path to the module and nor works.

## Logs

It throws me the following error:
```bash
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "$HOME/.vscode/extensions/ms-python.python-2020.3.71659/pythonFiles/lib/python/debugpy/no_wheels/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "$HOME/.vscode/extensions/ms-python.python-2020.3.71659/pythonFiles/lib/python/debugpy/no_wheels/debugpy/../debugpy/server/cli.py", line 429, in main
    run()
  File "$HOME/.vscode/extensions/ms-python.python-2020.3.71659/pythonFiles/lib/python/debugpy/no_wheels/debugpy/../debugpy/server/cli.py", line 266, in run_file
    runpy.run_path(options.target, run_name=compat.force_str("__main__"))
  File "/usr/lib/python3.6/runpy.py", line 261, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/usr/lib/python3.6/runpy.py", line 231, in _get_code_from_file
    with open(fname, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'hug -f /export/commands.py -c export --job events_cart_overview'
```

**Comment by int19h** [comment]
This use of "program" is not supported, and was never supported in the past - it probably inadvertently worked due to lax escaping.

"program" should specify the Python file that will be run. If you need to pass arguments to it, they go into "args" - which is a JSON array, so that they can be quoted and escaped properly depending on the current shell.

I'm not entirely sure what `hug -f` is, but it looks like some kind of custom Python interpreter? If so, you can specify that using `"pythonPath": ["hug", "-f"]`. However, this is only guaranteed to work if `hug -f` will accept any command line arguments that the standard Python interpreter does (in particular, stuff like `-m` and `-c`), and if it does not interfere with stdin/out of the script that it runs.

**Comment by cpinamtz** [comment]
Issue solved. I only needed to remove `program` and change it by `module`. The final launch configuration is the following:
```json
{
    "name": "Python: Batch export jobs  with Hug",
    "type": "python",
    "request": "launch",
    "module": "hug",
    "args": [
        "DESIRED_ARGS"
    ],
    "cwd": "${workspaceFolder}",
}
```
In my case the `DESIRED_ARGS` were those to provide to Hug the execution of the desired job. But as I said, I don't understand what has changed respect old version because the old command worked perfectly.
