### ISSUE TITLE
Add or Remove breakpoint not trigger event

### ISSUE THREAD

**Issue by pointhex** [microsoft/debugpy#1386]
When I send the request "setBreakpoints" I expect to get a response with a breakpoint list and also events about deleted/inserted breakpoints. https://microsoft.github.io/debug-adapter-protocol/specification#Events_Breakpoint

But now I get only a response. Could you please add the even as well?

Environment data

- debugpy version: 1.6.7.post1
- OS and version: Ubuntu 22.04
- Python version (& distribution if applicable, e.g. Anaconda):  Python 3.10.6
- Using VS Code or Visual Studio: -

Actual behavior
- send SetBreakpoints with one breakpoint "Content-Length: 160\r\n\r\n{\"arguments\":{\"breakpoints\":[{\"line\":25}],\"source\":{\"path\":\"/home/artem/work/testproj/untitledpy/main.py\"}},\"command\":\"setBreakpoints\",\"seq\":5,\"type\":\"request\"}"
- get successful response "Content-Length: 231\r\n\r\n{\"seq\": 11, \"type\": \"response\", \"request_seq\": 5, \"success\": true, \"command\": \"setBreakpoints\", \"body\": {\"breakpoints\": [{\"verified\": true, \"id\": 0, \"source\": {\"path\": \"/home/artem/work/testproj/untitledpy/main.py\"}, \"line\": 25}]}}"
- but get no event that the breakpoint inserted
- send SetBreakpoints empty "Content-Length: 150\r\n\r\n{\"arguments\":{\"breakpoints\":[],\"source\":{\"path\":\"/home/artem/work/testproj/untitledpy/main.py\"}},\"command\":\"setBreakpoints\",\"seq\":11,\"type\":\"request\"}"
- get response "Content-Length: 125\r\n\r\n{\"seq\": 20, \"type\": \"response\", \"request_seq\": 11, \"success\": true, \"command\": \"setBreakpoints\", \"body\": {\"breakpoints\": []}}"
- but get no event that the breakpoint removed

Expected  behavior
 - get events as well

**Comment by int19h** [comment]
My understanding of these events is that they apply when the breakpoint changes because of something that debug server does (e.g. line adjustment), not in response to setting the breakpoints, since the breakpoint response would cover the latter case. @connor4312, can you clarify what's the expected behavior here?

**Comment by connor4312** [comment]
>My understanding of these events is that they apply when the breakpoint changes because of something that debug server does (e.g. line adjustment), not in response to setting the breakpoints, since the breakpoint response would cover the latter case

That's correct

**Comment by pointhex** [comment]
I got it. Thanks! Is it possible to add this info to DAP doc somehow?

**Comment by pointhex** [comment]
I also have the same question about "output" event https://microsoft.github.io/debug-adapter-protocol/specification#Events_Output. It is absent as well. Is there any purpose underneath?

**Comment by int19h** [comment]
To get "output" events, you need to set `"redirectOutput": true`. The default for this property depends on "console" - it defaults to true for "internalConsole", and to false for integrated or external terminals.

**Comment by pointhex** [comment]
Thanks for the answer about "output" events.
About break point events, [the issue](https://github.com/microsoft/debug-adapter-protocol/issues/434) was created. Let's wait till answer and then close that one:)
