### ISSUE TITLE
VSCode python debugger incredibly slow / unresponsive / slow repr / spinning icons in "Variables" pane

### ISSUE THREAD

**Issue by apmoore499** [microsoft/debugpy#1391]
Debugging python scripts has become very slow in the last few days, I don't know why. Rolling vscode back to previous version didn't fix anything. The performance is very laggy whereas previously it worked very fast.

Steps to reproduce:
1. Run debug with basic config:
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "justMyCode": true,
            "logToFile": true
        },
2. Click on arrow to start debug

The following issues are encountered:

- Breakpoints take ages to hit. However, the script contents are simple and should not take this long, so it seems the problem is with debugger.
- Messages indicating slow repr computation: "pydevd warning: Computing repr of da (ConfigDict) was slow (took 141.01s) ". I have never seen this message before. The script I am debugging runs fine if I call 'python script_name.py' without debug. ConfigDict object is from ml_collections package. I have used this package for months without any issues.
- After code has hit a breakpoint, if I try to query any variables by calling 'print(variable_name)' to the debug console, it prints no output. The cursor is still blinking. If I leave it for a few minutes, it might print the variable. It doesn't appear to be completely frozen, just going very slow.
- In debug panel on right hand side, under the 'Variables' section, there are only two displayed items: locals, and globals. These two items are accompanied by a spinning icon that never stops, even when a breakpoint is hit. Additionally, there are no variables listed underneath if I try to click the dropdown arrow. Again, if I leave it for a few minutes, a list of variables may populate eventually. 

I have attached debug.log files. 
[debugpy.adapter-7080.log](https://github.com/microsoft/debugpy/files/12678736/debugpy.adapter-7080.log)
[debugpy.launcher-6365.log](https://github.com/microsoft/debugpy/files/12678737/debugpy.launcher-6365.log)
[debugpy.launcher-7104.log](https://github.com/microsoft/debugpy/files/12678738/debugpy.launcher-7104.log)
[debugpy.pydevd.6370.log](https://github.com/microsoft/debugpy/files/12678739/debugpy.pydevd.6370.log)
[debugpy.server-6370.log](https://github.com/microsoft/debugpy/files/12678740/debugpy.server-6370.log)

[debugpy.adapter-6340.log](https://github.com/microsoft/debugpy/files/12678735/debugpy.adapter-6340.log)

**Comment by apmoore499** [comment]
Issue has been fixed.

The issue was caused by an instance of ml_collections ConfigDict() class. A neural net was added to the dict which caused the slowdown. The network has ~22million weights. I believe this causes slowdown in repr as vscode debugger may be running repr query for all parameters in network. Have not confirmed if this is the exact cause, regardless I have changed code and no slowdown.

Example of code which throws the issue:
```python
import ml_collections
cdict=ml_collections.ConfigDict()
neural_net=load_my_neural_net()
cdict.neural_net=neural_net```

**Comment by int19h** [comment]
To clarify, debugger uses `repr()` to compute the representation of variables that it needs to show in Variables, Watch etc. If you have a breakpoint, this happens every time that breakpoint is hit.

**Comment by poedator** [comment]
in my case this did not help.
Somehow debugger continues trying to calculate repr for heavy variables, even though the variables panel was switched off...

**Comment by rchiodo** [comment]
That would depend upon VS code (or Visual Studio) or whatever your IDE is sending a variables request. If you turn on [logging](https://github.com/microsoft/debugpy/wiki/Enable-debugger-logs), the vscode log should show if there is a variables request or not.

**Comment by dbolser** [comment]
Can this be turned off? Generally I don't look at 'variables' and just stick to the debug console

**Comment by rchiodo** [comment]
Not sure if this prevents the request from being made but you can hide the variables pane:

![Image](https://github.com/user-attachments/assets/16d31074-0b7a-47fc-a96a-980f34299313)

**Comment by DylanSp** [comment]
I ran into this issue when working on a project involving [Z3's Python bindings](https://github.com/Z3Prover/z3). Hiding the variables pane did _not_ prevent the request being made; what worked was overriding `__repr__` for a dataclass in my code that contained Z3 objects.

Thanks for the pointers on what to look at - I'm posting this for the benefit of people searching in the future.

**Comment by kaikai23** [comment]
> Not sure if this prevents the request from being made but you can hide the variables pane:
> 
> ![Image](https://github.com/user-attachments/assets/16d31074-0b7a-47fc-a96a-980f34299313)

This works for me, thanks!
