### ISSUE TITLE
Cannot use debugpy with runserver_plus

### ISSUE THREAD

**Issue by sauravkhakurel** [microsoft/debugpy#1392]
Before creating a new issue, please check the [FAQ](https://github.com/microsoft/debugpy/wiki/FAQ) to see if your question is answered there.

## Environment data

- debugpy version: 1.8.0
- OS and version: Ubuntu 22.0 LTS
- Python version (& distribution if applicable, e.g. Anaconda): 3.10.12
- Using VS Code or Visual Studio: VS Code
- Using cookiecutter-django for project setup

## Actual behavior

Once the debugpy listen assigns the port, the runserver_plus autoloads and error message is shown regarding port already in use.

## Expected  behavior

Even if the server reloads debugpy should check if the port is already in use and if its in use by debugpy it should be able to be reused again so that the server does not crash.

## Steps to reproduce:
1. Setup django project using cookiecutter-django using docker y as option
2. After project setup, inorder to attach debugger, modiy the manage.py file to include the following:
if os.environ.get("DEBUG"):
    import debugpy

    debugpy.listen(("0.0.0.0", 6087))

3. The runserver_plus command is executed from the /start script of the compose file for django.
4. On the first instance the port is assigned to debugpy but later the runserver_plus auto reloads and shows error of port already in use.

Setting runserver_plus with --no-reload arg is not the solution that I am looking for. Is there any other way this can be achieved?
Regards

**Comment by int19h** [comment]
The port can't be reused because the parent process is still running, so connecting to that port would debug it. This would be better handled by only attaching the debugger to the child process - i.e. only doing `listen()` in the auto-reloaded process. Is that possible to detect?
