### ISSUE TITLE
PtvsdWheels37 - experiment breaks the debugger under windows

### ISSUE THREAD

**Issue by grbd** [microsoft/debugpy#140]
## Environment data

- PTVSD version: Python Extension version 2020.4.74986 under VSCode (latest)
- OS and version: Windows 10 Pro 1903
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.7.3 64bit windows standard
- Using VS Code or Visual Studio: VSCode

## Actual behavior

This is similar to what other users have been seeing but the symptoms were a little different in my case which is why I raised a new issue. The debugger just wouldn't launch at all

Under Log Windows:
```
[2020-04-24 02:06:13.983] [renderer1] [error] timeout after 1000 ms: Error: timeout after 1000 ms
    at t.RawDebugSession.handleErrorResponse (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3044:67)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3043:339
    at async t.RawDebugSession.shutdown (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3041:336)
```

as per https://github.com/microsoft/debugpy/issues/108 adding the following to the user settings file fixed it
```
    "python.experiments.optOutFrom": [
        "PtvsdWheels37 - experiment"
    ]
```

I did try disabling all other extensions (except for cosmetic ones) and tried this out with a project that worked before. (one that I came back to which I knew worked before the updates)

maybe this is an issue for https://github.com/Microsoft/vscode-python instead I'm not sure (if they're using an older version than they should be)

## Steps to reproduce:
1. Run the Python debugger

**Comment by grbd** [comment]
Just to add my pythonpath is set to a virtual environment directory instead of the usual C:\Python37

**Comment by int19h** [comment]
If you do `import debugpy; print(debugpy.__version__)` at the very beginning of your script, what does it say?

**Comment by grbd** [comment]
I just tried that but I don't think it gets that far
the output appears to be the same with that one line at the top
```
[2020-04-24 02:31:03.050] [renderer1] [error] timeout after 1000 ms: Error: timeout after 1000 ms
    at t.RawDebugSession.handleErrorResponse (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3044:67)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3043:339
    at async t.RawDebugSession.shutdown (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3041:336)
```

for info for the launh.json (vscode) I'm using
```
    "version": "0.2.0",
    "configurations": [
    
        {
            "name": "Python: arduino-dlang",
            "type": "python",
            "request": "launch",
            "cwd": "${workspaceFolder}",
            "program": "${workspaceFolder}/../../arduino_dlang/arduino_dlang.py",
            "args": [],
            "env": {
                "PYTHONPATH" : "${workspaceFolder}/../../",
            },
        },
```

Just in case it's something odd to do with the use of a python virtual environment

**Comment by grbd** [comment]
just tried it with the fix in place, but it didn't seem to find the debugpy module
I'm starting to wonder if vscode-python uses debugpy, I found this repo based on the errors I was getting though

**Comment by int19h** [comment]
It does use it - the difference between being in the experiment or not is whether you're using debugpy or not; the name is somewhat misleading (it's from before we renamed ptvsd 5.x to debugpy).

Can you share what it looks like in the terminal? Both the command line that it submits, and any resulting output, if there is one.

Also, try adding `"logToFile": true` to launch.json - that should generate some log files (`debugpy*.log`) in the folder where the extension is installed - you should be able to see that path in the terminal when you run things.

**Comment by grbd** [comment]
I just had a dig through the changelog file in the installed directory, I think it's using v1.0.0b5 for debugpy

with logging added to launch.json

debugger.vscode_cc7caf96-c7ca-4c82-8dfe-19143a4d0be9.log
```
0 Starting Session:
{
    "name": "Python: arduino-dlang",
    "type": "python",
    "request": "launch",
    "cwd": "D:\\SourceCode\\Private\\Hecatron-Private\\arduino-dlang\\examples\\blinky-c-example",
    "program": "D:\\SourceCode\\Private\\Hecatron-Private\\arduino-dlang\\examples\\blinky-c-example/../../arduino_dlang/arduino_dlang.py",
    "args": [],
    "env": {
        "PYTHONPATH": "D:\\SourceCode\\Private\\Hecatron-Private\\arduino-dlang\\examples\\blinky-c-example/../../",
        "PYTHONIOENCODING": "UTF-8",
        "PYTHONUNBUFFERED": "1"
    },
    "logToFile": true,
    "pythonPath": "d:\\SourceCode\\Private\\Hecatron-Private\\arduino-dlang\\examples\\blinky-c-example/../../virtenv/py37dev/Scripts/python",
    "envFile": "d:\\SourceCode\\Private\\Hecatron-Private\\arduino-dlang\\examples\\blinky-c-example/.env",
    "stopOnEntry": false,
    "showReturnValue": true,
    "console": "integratedTerminal",
    "internalConsoleOptions": "neverOpen",
    "debugOptions": [
        "ShowReturnValue",
        "FixFilePathCase"
    ],
    "justMyCode": true,
    "workspaceFolder": "d:\\SourceCode\\Private\\Hecatron-Private\\arduino-dlang\\examples\\blinky-c-example"
}
1 Error:
{}
3 Client --> Adapter:
{
    "command": "disconnect",
    "arguments": {
        "restart": false
    },
    "type": "request",
    "seq": 1
}
3 Client --> Adapter:
{
    "command": "initialize",
    "arguments": {
        "clientID": "vscode",
        "clientName": "Visual Studio Code",
        "adapterID": "python",
        "pathFormat": "path",
        "linesStartAt1": true,
        "columnsStartAt1": true,
        "supportsVariableType": true,
        "supportsVariablePaging": true,
        "supportsRunInTerminalRequest": true,
        "locale": "en-gb",
        "supportsProgressReporting": true
    },
    "type": "request",
    "seq": 2
}
1506 Stopping Session
```

**Comment by grbd** [comment]
I checked all the other log windows under vscode but couldn't find any other text

**Comment by int19h** [comment]
You've mentioned that you're using a virtual environment. Does it work for you if you try with a global interpreter? This should also let you get the version number out of it.

**Comment by grbd** [comment]
I had a look at the vscode extensions directory

under C:\Users\ric\.vscode\extensions\ms-python.python-2020.4.74986\pythonFiles\lib\python\debugpy\wheels\debugpy\_version.py
it lists
```
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-15T13:29:45-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "ade162b1d31f989548bf7c4c647694e02f0b4ef0",
 "version": "1.0.0b7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
```

**Comment by int19h** [comment]
Thank you! This confirms that it's not one of the original issues with the same symptoms - those should all be resolved in b7.

Did running it without virtual environment work for you, or are you running into the same problem regardless?

**Comment by int19h** [comment]
One other thing that'd be interesting to try is to start the debug adapter manually, and then tell VSCode to use it. To start it, run this in the terminal:
```cmd
py -3 ...\debugpy\adapter --port 8765 --log-stderr
```
and then add the following to your launch.json:
```json5
"debugServer": 8765,
```
That way, we should be able to observe any early failures.

**Comment by int19h** [comment]
Please re-open and attach the logs if you can still repro this on the most recent version of the Python extension and debugpy.
