### ISSUE TITLE
Debug With Threads does not work, may be related to opening a device ie: with PySerial.

### ISSUE THREAD

**Issue by duaneellissd** [microsoft/debugpy#1411]
This is on windows.
It is not trivial for me to extract out a simple example, because I do not know what you have to work with.

Stopping and Halting a python app with threads and devices open (such as a serial port) is very complex and often does not work, I often have to exit VS CODE to get it to RUN the application again.

Simple configuration:
   Consider 2 machines, I'll call them the LEFT side and RIGHT side.
   The LEFT side is your Python app running on Windows
   The RIGHT side is an Raspberry PI, or Arduino or maybe another windows machine using TERRA TERM.
   The left and right side are connected via a SERIAL interface - any USB serial converter will work.
   Or if your pc still has a DB9 Serial port that will work too.

   What ever you have on the RIGHT SIDE - should be simple, very simple.
   For example if you send the letter "A" - the right side should respond with the text: "You pressed A" on the serial port.

   For the LEFT side - configure a THREAD to read from the serial port.
   In my case, the thread does protocol decoding and at this stage of development it has bugs and throws exceptions.
   I am trying to debug that thread other threads in the system.

   A simple Left side example would be:
      Thread(LEFT_READER) - just reads from the serial port and prints what it receives.
      Periodically - make this thread throw and exception.

   The Main Thread - should for example look- sleep - and every 1 to 2 seconds send a byte 
   Thus, the RIGHT side will respond with "You pressed <somekey>" 
   Configure the LEFT_READER thread to sometimes throw an exception.

When this exception occurs - it is hard if not impossible to restart the application and debug again.
Often one must exit VSCODE and start VSCODE agian.

Otherwise, the application gets hung and you cannot restart, or the PySerial throws an exception that the COMPORT is already open by another the previous debug session.

The EXPECTED operation is this:
     If I click the RESTART button, or DEBUG - again - then it should just work.

**Comment by int19h** [comment]
"Restart debugging" is basically the equivalent of force-stopping the debuggee and then starting debugging again. In cases where the process holds some OS resources that need to be released (such as e.g. files, sockets, or in this case serial ports), the debugger isn't aware of them, so it's down to the OS to clean them up. Win32 normally does this for all HANDLEs, but I guess COM ports are an exception; I don't see what we can do about it, though.
