### ISSUE TITLE
Debugging for Entry Points / console_scripts

### ISSUE THREAD

**Issue by rigelifland** [microsoft/debugpy#1416]
I'm not sure if this belongs in `microsoft/debugpy` or `microsoft/vscode-python`, but it would be nice to be able to debug entry points for a module/package. I found this SO question describing this issue: https://stackoverflow.com/questions/61693769/vs-code-run-debug-configuration-for-a-console-script-in-module-mode

The syntax mentioned in the SO question seems reasonable, but I don't know enough about how `launch.json` works to know if it's  appropriate. 
```json
"module": "my_package.my_module:my_entry_point"
```

**Comment by joshbode** [comment]
My solution to this is to add a `__main__.py` file to `my_package` to make ir runnable, something like this:

```python
import sys

from my_package.my_module import my_entry_point

if __name__ == "__main__":
    sys.exit(my_entry_point(sys.argv[1:]))
```

and then you should be able to use `"module": "my_package"` to launch the debugger.

**Comment by int19h** [comment]
Note that there's also `"code"`, which lets you write the same thing directly in your launch.json, e.g.:
```
"code": "import sys; from my_package.my_module import my_entry_point; sys.exit(my_entry_point(sys.argv[1:]))"
```

**Comment by int19h** [comment]
That aside, the feature request to support it directly is tracked at https://github.com/microsoft/debugpy/issues/1311
