### ISSUE TITLE
VSC Python Debug will not stop at break point

### ISSUE THREAD

**Issue by pseudocyber** [microsoft/debugpy#143]
I found issue mentioned before, but space in title did not seem to be causing the issue.  See attached .gif.

## Environment data

-   VS Code version: 1.44.2
-   Extension version (available under the Extensions sidebar): 2020.4.74986
-   OS and version: Windows 10 ver. 1903
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.2 32 bit
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Relevant/affected Python packages and their versions: n/a
-   Relevant/affected Python-related VS Code extensions and their versions: n/a
-   Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): N/A
-   Value of the `python.languageServer` setting: XXX

## Expected behaviour

Script execution stops on break point line.

## Actual behaviour

Execution does not stop on break point.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

`a = 1
b = 2
c = a + b
print (f'c is {c}')`

## Logs

Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
XXX
```

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`; turn on source maps to make any tracebacks be useful by running `Enable source map support for extension debugging
[console dev tool output python debugging issue.txt](https://github.com/microsoft/vscode-python/files/4528128/console.dev.tool.output.python.debugging.issue.txt)
![dumbtest](https://user-images.githubusercontent.com/28627440/80200882-4a658080-85f1-11ea-8a46-6b5abaffd69c.gif)

`)

```
XXX
```

**Comment by int19h** [comment]
Can you please try running it with `"logToFile": true` in your launch.json, and then share `debugpy*.log` that will produce in `C:\Users\...\.vscode\extensions\ms-python...\`

**Comment by pseudocyber** [comment]
Good Morning int19h, I am attaching the file.  Thanks.

**Comment by pseudocyber** [comment]
[debugpy.server-23908.zip](https://github.com/microsoft/debugpy/files/4538788/debugpy.server-23908.zip)

**Comment by int19h** [comment]
Ah, so the reason why it's not hitting the breakpoint, is because your script is inside the folder where Python is installed:
> Breakpoint in file excluded by filters.
> Note: may be excluded because of "justMyCode" option (default == true). Try setting "justMyCode": false in the debug configuration (e.g., launch.json).

However, rather than tweaking "justMyCode", I'd recommend not maintaining your code under C:\Python (note, this also applies to virtual environments, if you create any).

The reason for this behavior is to prevent you from accidentally stepping into the standard library, since it's usually not desired.

**Comment by pseudocyber** [comment]
Hey @int19h, that totally worked.  Thanks so much, and I will take your advice, and move the scripts.  I've been pulling my hair out trying to get this working.  Thank you!
