### ISSUE TITLE
[sys.monitoring] Snap breakpoints to valid locations

### ISSUE THREAD

**Issue by int19h** [microsoft/debugpy#1434]
If breakpoint couldn't be verified (https://github.com/microsoft/debugpy/issues/1433) because it is on invalid source location, but there is adjacent valid location that is logically the same (e.g. when setting breakpoint on empty line, this is the first logically following line of executable code in the same function), adjust breakpoint location as needed.

**Comment by judej** [comment]
shelving work for sys.monitoring implmentation for now
