### ISSUE TITLE
[sys.monitoring] Exception breakpoints

### ISSUE THREAD

**Issue by int19h** [microsoft/debugpy#1436]
Handle `setExceptionBreakpoints` DAP request and associated machinery such as exception filters. All items should include special handling of expected control flow exceptions such as `StopIteration`. 

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/debugpy/issues/1452
- [ ] https://github.com/microsoft/debugpy/issues/1453
- [ ] https://github.com/microsoft/debugpy/issues/1454
- [ ] https://github.com/microsoft/debugpy/issues/1455
```

**Comment by judej** [comment]
shelving work for sys.monitoring implmentation for now
