### ISSUE TITLE
[sys.monitoring] safe repr - collections

### ISSUE THREAD

**Issue by int19h** [microsoft/debugpy#1448]
Implementing safe-repr for standard Python collections. The output should follow the standard `repr()` output for them while intelligently using ellipsis to exclude enough parts to fit within the specified length limits. It should also safely handle recursive collections (those that directly or indirectly include themselves as items).
```[tasklist]
### Tasks
- [ ] tuple
- [ ] list
- [ ] set
- [ ] dict
- [ ] array
- [ ] frozenset
- [ ] collections.deque
- [ ] collections.namedtuple
- [ ] collections.*
- [ ] namedtuple
```

**Comment by judej** [comment]
shelving work for sys.monitoring implmentation for now
