### ISSUE TITLE
[sys.monitoring] Django breakpoints

### ISSUE THREAD

**Issue by int19h** [microsoft/debugpy#1466]
Source breakpoints in Django templates.

**Comment by rchiodo** [comment]
Been doing some research (using this to test our stable build of pylance).

In the old code I believe this is handled here:
https://github.com/microsoft/debugpy/blob/09b5af0bb730e2707ec3bbc14c509523eca116c0/src/debugpy/_vendored/pydevd/pydevd_plugins/django_debug.py#L514

Basically the plugin is called to:
- Check if current frame is a render_template call or not
- If it is, find the template name
- Use template name to find matching lines
- Get the template_line and see if there's a breakpoint on it
- Return a different type of frame if there is

I think it's likely the new code will have the same logic as the pydevd code.

**Comment by judej** [comment]
shelving work for sys.monitoring implmentation for now
