### ISSUE TITLE
[sys.monitoring] Stdout redirection

### ISSUE THREAD

**Issue by int19h** [microsoft/debugpy#1470]
In "attach" mode, there's no launcher to capture the output of the spawned process from the outside, so debug server needs some logic in it to do so on the inside and generate the corresponding DAP `output` events.

The implementation should be as low-level as possible to intercept all output regardless of how it is performed. Ideally this should replace the stdout file handle for the process altogether and then copy everything it receives to the actual stdout. It might be desirable to do this in native code so that output is always streamed regardless of GIL etc, but a pure Python implementation would still be needed for portability.

**Comment by judej** [comment]
shelving work for sys.monitoring implmentation for now
