### ISSUE TITLE
[sys.monitoring] Report loaded modules

### ISSUE THREAD

**Issue by int19h** [microsoft/debugpy#1472]
VS requires each stack frame to be associated with a DAP `Module`, and valid modules must be reported via `module` events. For Python, the intended behavior is that each unique .py file corresponding to one or more live code objects represents a module. The debug server should do a best-effort enumeration of loaded modules (e.g. by inspecting `sys.modules` and trying to infer it from that) on start, then report new modules as they are detected while tracing code.

**Comment by judej** [comment]
shelving work for sys.monitoring implmentation for now
