### ISSUE TITLE
Breakpoint in file that does not exist when folder name contains `.zipx`

### ISSUE THREAD

**Issue by russau** [microsoft/debugpy#1473]
Before creating a new issue, please check the [FAQ](https://github.com/microsoft/debugpy/wiki/FAQ) to see if your question is answered there.

## Environment data

- debugpy version: 1.8.0
- OS and version: macOS 13.5.2
- Python version (& distribution if applicable, e.g. Anaconda): 3.10.12
- Using VS Code or Visual Studio: VS Code 1.84.2,  ms-python.python v2023.20.0

## Actual behavior

Seeing an error "Breakpoint in file that does not exist.", when the breakpoint is in a folder that contains `.zip(anything)` and debugger never hits the breakpoint.

## Expected  behavior

Debugger stops on breakpoint

## Steps to reproduce:
1. In VS Code create a `.zipx/main.py` file
2. Add something like `print("hello")`, set a breakpoint on it
3. Launch debugger and breakpoint isn't hit

I think the problem is with the vendored PyDev.Debugger, I've created a matching issue @ https://github.com/fabioz/PyDev.Debugger/issues/265

**Comment by judej** [comment]
Thank you for the report. Given our current resources are working on the Python 3.12 debugger, we will not be fixing this issues in the pre Python 3.12 debugger.
