### ISSUE TITLE
Can't see libraries in stack trace even with "justMyCode": false

### ISSUE THREAD

**Issue by adamerose** [microsoft/debugpy#1474]
I want VS Code's default Python debugging behavior to include full stack trace details from inside libraries similar to PyCharm shown below, how can I achieve this?

![image](https://github.com/microsoft/vscode-python/assets/10884874/fc6a9ff7-2840-416d-8662-75b9e3119ad4)

![image](https://github.com/microsoft/vscode-python/assets/10884874/1e5d835b-d722-40d5-b9f8-ad9670a79208)

**Comment by judej** [comment]
Thanks for the report. Setting "justMyCode" to false should give you the additional stack traces you are looking for.
```{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python Debugger: Current File",
            "type": "debugpy",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "justMyCode": false
        }
    ]
}```

If this does not work for you, pleas feel to reopen the issue.
