### ISSUE TITLE
Multi-thread debugging, the main thread is suspended, the child thread can not be suspended? 

### ISSUE THREAD

**Issue by YuhongZeng** [microsoft/debugpy#1475]
Multi-thread debugging, the main thread is suspended, the child thread can not be suspended? You can perform continue, parse, and step control on each thread.
Our expected multi-threaded debugging feature for VSCode includes the following:
 1. The main thread is suspended, but the sub-threads are not suspended at the same time.
 2. Each thread can be separately controlled to continue, pause, and step. 
The following video demonstrates the implementation of this multi-threaded debugging feature.

**Comment by YuhongZeng** [comment]
I understand having the other threads running ended up incredibly confusing in most scenarios. I believe that this confusion is mainly caused by the vendored PyDev.Debugger. Here are the reasons we think this is happening.
1.

https://github.com/microsoft/debugpy/blob/ef9a67fe150179ee4df9997f9273723c26687fab/src/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command_json.py#L728C1-L813C81

**Comment by YuhongZeng** [comment]
1. Breakpoint hits cause all threads to be suspended
- When setting breakpoints, pydevd forcibly set suspend policy to ALL.
https://github.com/microsoft/debugpy/blob/ef9a67fe150179ee4df9997f9273723c26687fab/src/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command_json.py#L728C1-L813C81

- When ` suspend_policy = 'ALL'`  causes the `suspend_other_threads` parameter to be set to `True`.
https://github.com/microsoft/debugpy/blob/ef9a67fe150179ee4df9997f9273723c26687fab/src/debugpy/_vendored/pydevd/pydevd.py#L1845C1-L1892C60

- The `self.multi_threads_single_notification=True` sets suspend_other_threads to True when `suspend_policy ='NONE'. `multi_threads_single_notification`cannot be set to False. If it is set to False, Development Tools cannot accept debugging signals from pydevd.

`
        if not suspend_other_threads and self.multi_threads_single_notification:
            # In the mode which gives a single notification when all threads are
            # stopped, stop all threads whenever a set_suspend is issued.
            suspend_other_threads = True
`

**Comment by YuhongZeng** [comment]
2. StoppedEvent and ContinuedEvent returned by pydevd to Development Tools
https://github.com/microsoft/debugpy/blob/ef9a67fe150179ee4df9997f9273723c26687fab/src/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_net_command_factory_json.py#L347C1-L397C89

```
        body = pydevd_schema.StoppedEventBody(
            reason=stop_reason,
            description=exc_desc,
            threadId=thread_id,
            text=exc_name,
            allThreadsStopped=True,
            preserveFocusHint=preserve_focus_hint,
        )
```
```
body = ContinuedEventBody(threadId=thread_id, allThreadsContinued=True)
```
The `allThreadsStopped` and `allThreadsContinued` are forcibly set to True, which causes Development Tools to respond to continue and stop for all threads, regardless of whether continue and stop of the debugger work for all threads.

**Comment by int19h** [comment]
The reason why step resumes all threads is because there are many cases where a thread is dependent on another thread doing something (e.g. releasing a lock), so resuming just the single thread would often translate to the debugged problem hanging with no clear indication of the problem and no good way to resolve it at that point (since we can't pause the thread again once it's inside a native call that is blocked).

As I recall now, originally pydevd worked as you described, only pausing/resuming a single thread in all circumstances. It was changed based on real world experience with that. Unfortunately it does seem like this isn't just a one-line change, so we'll have to treat it as an enhancement - which for practical purposes means that it'll likely only be available in the next major version of debugpy that is currently in progress.

**Comment by YuhongZeng** [comment]
We have added a configurations args multiThread, when multiThread is true, multi-thread debugging phenomenon is shown in the following video:

https://github.com/microsoft/debugpy/assets/40681646/25594729-fc33-4f30-9bee-efed31336d57

**Comment by YuhongZeng** [comment]
We found that when multi-threaded debugging, pause will occasionally have bugs.the control thread suspend, but the vscode interface does not respond, this is because the thread sleeps when pause, if it exceeds 0.5s, it will think that the request has timed out, and then return failed to the IDE, but the thread will still suspend after sleeping.After debugging

https://github.com/microsoft/debugpy/assets/40681646/32f8618b-d1e3-4af0-ba71-263be8404d36

 with other threads, pause can be resumed

**Comment by int19h** [comment]
I have tried to implement this cleanly in the new debug adapter, and found DAP itself to be underspecified in the presence of individual threads; no wonder that clients get into weird states with it. Between that and lack of VS support, we're not going to support this feature going forward until DAP spec makes it possible for clients to clearly indicate which behavior they expect, and specifies what happens in various corner cases (e.g. what if client requests all threads suspend, then resumes individual threads which spawn more threads).
