### ISSUE TITLE
Python3.12 Unable to attach to PID (Jupyter python process)

### ISSUE THREAD

**Issue by fleming79** [microsoft/debugpy#1476]
With VScode I normally debug IpyWidgets by attaching to a Jupyter Kenrnel using PID. With python 3.11 this works with an external Jupyter kernel or one managed by VScode.

Switching to using Python 3.12 it no longer connects to the PID. The only indication is a message in the console Python:....

```
Attaching to PID: 19800 (elapsed: 1.00s).
Attaching to PID: 19800 (elapsed: 2.00s).
```
Stops counting at 2.00s.

With Python 3.11 it counts up to about 8s then connects.

## Environment data

- debugpy version: 1.8.0
- OS and version: Windows 10
- Python version (& distribution if applicable, e.g. Anaconda): 3.12 [WinPython distribution](https://github.com/winpython/winpython/issues/1258) 
- Using VS Code:
Version: 1.84.2
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:51:52.184Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045
## Actual behavior

* Debugger doesn't attach (Timeout error).

## Expected  behavior

* Debugger attaches to PID after about 8s.

## Steps to reproduce:
1. Start VScode.
2. Start Jupyter and obtain PID for a Python 3.12 kernel.
3. Attach to PID using Python debugger.

### Launch settings
        {
            "name": "Python: Attach using Process Id",
            "type": "python",
            "request": "attach",
            "processId": "${command:pickProcess}",
            "subProcess": false
        }

**Comment by int19h** [comment]
Could you enable logs using `"logToFile": true` in your launch.json, and share `debugpy.server*.log`?

**Comment by fleming79** [comment]
Here is the log file.
[debugger.vscode_24ababd2-a99b-44d7-a395-aea0bf4197c5.log](https://github.com/microsoft/debugpy/files/13551247/debugger.vscode_24ababd2-a99b-44d7-a395-aea0bf4197c5.log)

For my ref: [how to find log file](https://github.com/microsoft/debugpy/wiki/Enable-debugger-logs)

**Comment by int19h** [comment]
Indeed, my apologies; the "logToFile" setting wouldn't be applied in this case. Instead, set the `DEBUGPY_LOG_DIR` environment variable for the process you're attaching to point at the directory where it should place the logs.

**Comment by fleming79** [comment]
Thank you for the guidance.
[debugpy.server-21680.log](https://github.com/microsoft/debugpy/files/13552266/debugpy.server-21680.log)

**Comment by fleming79** [comment]
There are two files created at the same time.
### Python 3.12 kernel. 
[debugpy.server-6620.log](https://github.com/microsoft/debugpy/files/13552431/debugpy.server-6620.log)
[debugpy.pydevd.6620.log](https://github.com/microsoft/debugpy/files/13552432/debugpy.pydevd.6620.log)

### Python 3.11 kernel.
Similar log files (with same prefix) are generated when successfully connecting.
[debugpy.server-19904.log](https://github.com/microsoft/debugpy/files/13552441/debugpy.server-19904.log)
[debugpy.pydevd.19904.log](https://github.com/microsoft/debugpy/files/13552442/debugpy.pydevd.19904.log)

**Comment by fleming79** [comment]
I switched to using system environment variable instead of using WinPython and now get three files:

[debugpy.adapter-4172.log](https://github.com/microsoft/debugpy/files/13606699/debugpy.adapter-4172.log)
[debugpy.pydevd.6836.log](https://github.com/microsoft/debugpy/files/13606700/debugpy.pydevd.6836.log)
[debugpy.server-6836.log](https://github.com/microsoft/debugpy/files/13606701/debugpy.server-6836.log)

**Comment by fleming79** [comment]
As another hint, the console in which Jupyter is running emits the following message:
```console
Python version unknown!
Error when injecting code in target process. Error code (on windows): 5
```

**Comment by omasoud** [comment]
I ran into the same error. Tried with the process being just python.exe too; same thing.
```
Python version unknown!
Error when injecting code in target process. Error code (on windows): 5
```
[debugpy.adapter-22480.log](https://github.com/microsoft/debugpy/files/14132740/debugpy.adapter-22480.log)
[debugger.vscode_236ca7a3-324e-4f22-870f-7f2842027d18.log](https://github.com/microsoft/debugpy/files/14132741/debugger.vscode_236ca7a3-324e-4f22-870f-7f2842027d18.log)

I'm guessing it's ending up [here](https://github.com/microsoft/debugpy/blob/42853a99c4d3d4d27e4960c8894d780d4f091d68/src/debugpy/_vendored/pydevd/pydevd_attach_to_process/windows/attach.cpp#L335).

**Comment by tonyroberts** [comment]
Seems like Python 3.12 isn't supported at the moment? GetPythonVersion returns PythonVersion_Unknown for Python 3.12

https://github.com/microsoft/debugpy/blob/42853a99c4d3d4d27e4960c8894d780d4f091d68/src/debugpy/_vendored/pydevd/pydevd_attach_to_process/common/py_version.hpp#L74

**Comment by NitroTamagotschi** [comment]
I ran into the same error by using a simple Python script instead of a jupyter notebook.

**Comment by xuweiwang2021** [comment]
Any solution for this issue? I got the same error in Anaconda Prompt running python 3.12 when debug in VS Code by attach using Process Id. 
conda 24.3.0
python 3.12.2, python 3.12.3
VS Code 1.89.0
Python version unknown!
Error when injecting code in target process. Error code (on windows): 5

**Comment by AdamYoblick** [comment]
Yeah this is a known issue. Attach to a python 3.12 process doesn't work yet because of all the internal changes in 3.12 that we haven't caught up with. In the meantime, 3.11 should work.

**Comment by xuweiwang2021** [comment]
Thank you!

Xuwei

**Comment by rchiodo** [comment]
This issue should be fixed in the latest build of debugpy. It should ship with VS code in a future version of the [Python Debugger Extension](https://marketplace.visualstudio.com/items?itemName=ms-python.debugpy) or you can install your own debugpy from pypi
