### ISSUE TITLE
Debugger: Dictionaries not correctly listed for multiple key objects with identical representation

### ISSUE THREAD

**Issue by mankeph** [microsoft/debugpy#148]
## Environment data
-   VS Code version: 1.45.0-insider
-   Extension version (available under the Extensions sidebar): 2020.4.76186
-   OS and version: Linux Mint 18.2
-   Python version (& distribution if applicable, e.g. Anaconda): 3.6.8 : Anaconda
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Relevant/affected Python packages and their versions: None
-   Relevant/affected Python-related VS Code extensions and their versions: None
-   Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): [default]
-   Value of the `python.languageServer` setting: [default] 
(Fresh install of the insider build and default Python extension)

## Expected behaviour

Show the full dictionary listing in the debugger "Variables" window.

## Actual behaviour

The listing only shows the first occurance of duplicate `__repr__` values for dictionary key items.

## Steps to reproduce:

```
class T:
    def __init__(self, name, value):
        self.name = name
        self.value = value
    def __repr__(self):
        return self.name

td = {T("foo", 24): "bar",
      T("gad", 42): "zooks",
      T("foo", 12): "bur"}

print("Keys: " + str((td.keys())))  
print("Values: " + str((td.values()))) # Breakpoint here
```

1. We need Python objects that can return identical representations for different objects (`__repr__()`).
2. Create multiple of such objects and use them as key values for a dictionary.
3. Start the debugger and look at the dictionary in the variable listing. 
4. Only the first key from all duplicate representations will be displayed, even though the dictionary may contain multiple different key objects.

Screenshot using the code example:
![Dictionary_Debugger_bug](https://user-images.githubusercontent.com/10772412/80478054-38ffd980-894d-11ea-97a6-45c16d4cde3f.png)

**Comment by int19h** [comment]
It might be a VSCode limitation, or else we're shoving them into a dict somewhere and collapsing the keys in the process. Need to investigate.

**Comment by fabioz** [comment]
I'll investigate this.

**Comment by fabioz** [comment]
This really seems like a limitation VSCode: https://github.com/microsoft/vscode/issues/107506

It seems we need some code to work around that (and I noted that the `evaluateName` is also wrong in this case).
