### ISSUE TITLE
Breakpoints not triggered in Flask app

### ISSUE THREAD

**Issue by wonboyn** [microsoft/debugpy#1489]
## Environment data

- debugpy version: 1.6.7
- OS and version: Ubuntu 20.04
- Python version 3.9.5
- Using VS Code or Visual Studio: VS Code with Dev Container

## Actual behavior
Set a breakpoint inside a Flask route
Start debugging of the Flask app.
Launch browser & hit Flask route & breakpoint does not trigger

Launch config:
type: python
request: launch
program: Flask application module
console: integratedTerminal
cwd: ${workspaceFolder}/app_directory

## Expected  behavior
Breakpoint is triggered

## Steps to reproduce:
1. Setup launch config
2. Set breakpoint inside a route
3. Start debugging
4. Launch browser & try access the route

**Comment by int19h** [comment]
Are you running Flask with the reloader? If so, is multiprocess debugging enabled?

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
