### ISSUE TITLE
tries to debug a wrong file, behaves weird if file is moved

### ISSUE THREAD

**Issue by aurkaxi** [microsoft/debugpy#1493]
## Environment data

- debugpy version: 2023.3.13341006
- OS and version: arch linux. kernel 6.6.9-arch1-1
- Python version (& distribution if applicable, e.g. Anaconda): 3.11.6
- Using VS Code or Visual Studio: vscode

## Actual behavior
it tries to debug another file in this directory (file is in markdown) and says unknown syntax. 
here look at my directory tree:
![image](https://github.com/microsoft/debugpy/assets/72933395/70e68a90-bbd9-4477-9fb5-421dd956d8d8)
there is a file `list_method.md` but i am on `day_8.py`. in my active editor i clicked run without debugging. but the output says it is debugging the list_method file.
```sh
❯  /usr/bin/env /bin/python /home/aurka/.vscode-insiders/extensions/ms-python.debugpy-2023.3.13341006-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher 51731 -- /home/aurka/softwares/bootcamp/codesyntropy/list_method.md
  File "/home/aurka/softwares/bootcamp/codesyntropy/list_method.md", line 4
    Adds an element at the end of the list
         ^^
SyntaxError: invalid syntax
```

I tried moving day_8.py to another subfolder and open that folder from menu bar > file> open folder ... [ctrl+k ctrl+o]. but still it checks for this list_method and says file not found.

i tried moving list_method.md to a sub folder and kept day_8.py in root folder. now if i run it, terminal pops up, it starts typing \uttttttt... and keeps typing letter `t` till i keep pressing ctrl+c.

## Expected  behavior
same behavior if i did `python file.py`

## Steps to reproduce:
1. i don't know, it just happened today. even yesterday everything was fine. today it asked to select a python debugger even though i clicked "run without debuggin", redirected me to python extension, said reload. i did and shaka laka boom. nothing works anymore.
2. it only happens with this folder.  i tried creating a new file in my home and nothing went wrong. i think something went wrong  with my settings.

## things i tried to fix:
restart: pc, vscode, python server

**Comment by judej** [comment]
@aurkaxi, thanks for the report. Could you please make sure that your `launch.json` is correctly set the debug the current file?

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",  // Use "python" here
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal"
        }
    ]
}

``` 

If this does not address the problem, please reopen is issue.
