### ISSUE TITLE
Jump to cursor doesn't seem to work when debugging cells

### ISSUE THREAD

**Issue by luabud** [microsoft/debugpy#150]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

1. Start debugging a cell 
2. Step over a bit, then right click on a few lines behind and select "Jump to Cursor"

## Actual behavior
![image](https://user-images.githubusercontent.com/45497113/80656782-e00c7000-8a36-11ea-9e8f-680c800285f1.png)

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:** Local
-   **Extension version:** 2020.5.76036-dev
-   **VS Code version:** 1.44.2
-   **Python and/or Anaconda version:** Python 3.8.0 32 bit
-   **OS:** Windows
-   **Virtual environment:** venv

**Comment by fabioz** [comment]
I'm taking a look at this (the problems seems to be that the lines aren't being properly mapped in this case).
