### ISSUE TITLE
Python Debugger not showing NumPy array values after update - NOT resolved

### ISSUE THREAD

**Issue by jav-ed** [microsoft/debugpy#1505]
[https://github.com/microsoft/vscode-python-debugger/issues/135](https://github.com/microsoft/vscode-python-debugger/issues/135) was closed. However, the issue still remains, see:

![0](https://github.com/microsoft/vscode-python-debugger/assets/47569896/bae86126-5d06-4d7a-b8c5-8c4f68a11212)
![1](https://github.com/microsoft/vscode-python-debugger/assets/47569896/a140c5b2-3104-416a-9181-7d1819515373)

- VSCode Version:
Version: 1.85.2
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
Date: 2024-01-18T06:40:19.222Z
Electron: 25.9.7
ElectronBuildId: 26354273
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 5.14.21-150500.55.39-default

### Additional
Also, please see: https://github.com/microsoft/debugpy/issues/1770
> Sorry, my bad.
> 
> Just as a background, where the confusion might come from: on microsoft/vscode-python-debugger#135 (marked as closed) they will link to --> [microsoft/debugpy#1418](https://github.com/microsoft/debugpy/issues/1418) (marked as closed) they will link to --> [microsoft/debugpy#1408](https://github.com/microsoft/debugpy/issues/1408) (also marked as closed)
> 
> I will inshallah try to create a new issue on debugpy, hoping that they do not mind and not forward me somewhere else.

**Comment by int19h** [comment]
It's closed because the fix has been committed to the repo, but there hasn't been a debugpy release that includes the fix yet.

In the meantime, you can use the most recent bits from the repo by doing this in your launch.json (assuming that you cloned the repo into `~/git/debugpy`):
```json5
"debugAdapterPath":"${userHome}/git/debugpy/src/debugpy/adapter"
```
(you'll get an error squiggle from the JSON schema validator because it doesn't know about this property, but it should still work)

**Comment by jav-ed** [comment]
Nice to hear that, the team did not forget about this issue. Thank you for the quick reply. Can you guess of a timeframe when the new release with this correction can be expected?

**Comment by jaortizco** [comment]
Hi, I noticed debugpy v1.8.1 was released with a fix for this issue. Do you have an estimated timeframe for when this fix will be integrated into the Python extension? Thanks!
