### ISSUE TITLE
[sys.monitoring] Deadlocks when breakpoints are hit

### ISSUE THREAD

**Issue by int19h** [microsoft/debugpy#1510]
When breakpoint with an associated log message is hit, debugpy has a high chance of deadlocking while trying to send the "output" message.

**Comment by jacobdwyer16** [comment]
I am also experiencing the same issue when allowing breaks on raised exceptions.

**Comment by int19h** [comment]
This bug is specifically about debugpy v2, which is a work in progress and has not been released yet. If you're experiencing something similar on published debugpy versions, please file a separate issue describing the exact scenario.

**Comment by jacobdwyer16** [comment]
I'm unable to replicate the bug at the moment. Thanks for the response. Deleting and recreating `launch.json` seems to have helped? It might have been runtime specific. I'll follow up if I am able to recreate it.
