### ISSUE TITLE
"View Value in Data Viewer" Just Disappear from python debugger 

### ISSUE THREAD

**Issue by AleCozar13** [microsoft/debugpy#1513]
## Environment data

- debugpy version: 1.7.0 
- OS and version: Apple m2 Ventura 13.5.2 (22G91)
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.10.11
- Using VS Code or Visual Studio: VS Code

## Actual behavior

Right-click on dataframe variable does not show "View in Data Viewer"
## Expected  behavior
Right-click on dataframe variable does show "View in Data Viewer" as usual

## Steps to reproduce:
<img width="514" alt="Screenshot 2024-02-02 at 13 22 02" src="https://github.com/microsoft/debugpy/assets/112964111/64987d8f-74c6-4bfa-b3a6-c4d0ab7c4860">
<img width="514" alt="Screenshot 2024-02-02 at 13 24 21" src="https://github.com/microsoft/debugpy/assets/112964111/ddef87d0-e6b1-43a0-ab74-441ddd7dc61e">

Also i attach  my actual setting.json
[settings.json](https://github.com/microsoft/debugpy/files/14139996/settings.json)

**Comment by crypla** [comment]
It seems to be dependent on Jupyter Extension which was upgraded

**Comment by wilsonchen719** [comment]
Same here...

**Comment by grahama1970** [comment]
same here

**Comment by Ptlmw666** [comment]
Same here

**Comment by AleCozar13** [comment]
> I have the same issue that just occured in the last day - It seems to be dependent on Jupyter Extension - I tried uninstalling and installing again with no success debugpy version: 1.8.0 OS and version: Windows 23H2 OS Build 22631.3085 Python version (& distribution if applicable, e.g. Anaconda): Python 3.11.5 Using VS Code or Visual Studio: VS Code Python Debugger Extension: v2024.0.0 Jupyter Extension: v2024.1.0

I tried to downgrade the Jupyter extension, but it didnt work

**Comment by e2tovar** [comment]
Temp Solution: It's not Jupyter extension. It's the new Python extension 2024.0.0. The new default debugger is "debugpy" instead of "python". There are two ways of fixing it. 
- One is to downgrade Python version. Any version before 2024.0.0
- The second is to Change the type value in launch.json 
![image](https://github.com/microsoft/debugpy/assets/62236958/cdfb0495-bf67-4917-96a3-a2dcb2c62814)
Adding "python instead of "debugpy" will work. It will warn that it is deprecated, but it works fine.

**Comment by AleCozar13** [comment]
> Temp Solution: It's not Jupyter extension. It's the new Python extension 2024.0.0. The new default debugger is "debugpy" instead of "python". There are two ways of fixing it.
> 
> * One is to downgrade Python version. Any version before 2024.0.0
> * The second is to Change the type value in launch.json
>   ![image](https://private-user-images.githubusercontent.com/62236958/302125008-cdfb0495-bf67-4917-96a3-a2dcb2c62814.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMTk5ODAsIm5iZiI6MTcwNzExOTY4MCwicGF0aCI6Ii82MjIzNjk1OC8zMDIxMjUwMDgtY2RmYjA0OTUtYmY2Ny00OTE3LTk2YTMtYTJkY2IyYzYyODE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDA3NTQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxYjMyYmIxYWQ0ZWZiNzQ0YmIxNjcyMTQxYmJiOWZmODhkYWE1ZGU5OWZjZTM2YTg3ZjFjMTVhMmM2ZjIxNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OljjrJQMfqvgIbQ4_pO_VdnXLdbkhi3qwy0KKveFYXc)
>   Adding "python" instead of "debugpy" will work. It will warn that it is deprecated, but it works fine.

The second option was the one that fixed it. Thank you 👍

**Comment by crypla** [comment]
I had to do both the first and second options, as well as uninstall the "Python Debugger" Extension (debugpy) to get it to work.
