### ISSUE TITLE
Data Viewer with "debugpy"

### ISSUE THREAD

**Issue by henrybaugniet** [microsoft/debugpy#1516]
## Environment data

- debugpy version: 1.7.0
- OS and version: Mac OS 14.3
- Python version (& distribution if applicable, e.g. Anaconda): conda 3.9.18
- Using VS Code or Visual Studio: VS Code

## Actual behaviour

Data viewer does not appear as an option when trying to view variables when I launch with "debugpy". 
![Screenshot 2024-02-07 at 10 12 01](https://github.com/microsoft/debugpy/assets/71974363/9dc3ab0a-1179-4f4a-b1ac-b90f149502c9)

![Screenshot 2024-02-07 at 10 12 10](https://github.com/microsoft/debugpy/assets/71974363/4604b759-5612-4df2-9740-3efeda51bac7)

## Expected  behaviour

However if I use "python" it  shows data viewer. 
![Screenshot 2024-02-07 at 10 11 50](https://github.com/microsoft/debugpy/assets/71974363/7ae67b08-1716-4f11-b49e-b4d7000df736)
![Screenshot 2024-02-07 at 10 12 43](https://github.com/microsoft/debugpy/assets/71974363/27c2b2a2-6fe4-44fb-815d-d3751aa68090)

## Steps to reproduce:
1. Create a dataframe
2. Attempt to view 

I have jupyter and python installed in VS Code. 

Now that debugpy is used by default this issue is frustrating.

**Comment by paulacamargo25** [comment]
Yes, Jupyter extension registers a tracker for the Data Viewer to work, this was registered only for the `python` type, this is why it does not work with the `debugpy` type. Jupyter is already working on this, you can track it [here](https://github.com/microsoft/vscode-jupyter/issues/15121).
