### ISSUE TITLE
Debugger crashes if running under CPython debug build (--with-pydebug)

### ISSUE THREAD

**Issue by patrickkidd** [microsoft/debugpy#152]
## Environment data

- PTVSD version: 4.3.2
- OS and version: macOS 10.15.4, Windows 10 latest
- Python version: 3.6.4
- Using VS Code or Visual Studio: VS Code

## Actual behavior

Crashes immediately when debugging via launch.

## Expected  behavior

Does not crash; can break at breakpoint.

## Steps to reproduce:
1. Build and install python from source with generic configure options.
2. Set built python as interpreter.
3. Set breakpoint in first line of python code.
4. Launch debugger.
5. Observe crash w/ crash report in OS.

**Comment by fabioz** [comment]
Note: I'm currently taking a look at this issue.

From what I searched, it seems that the best way to find out if it is a debug build is using:

`hasattr(sys, 'gettotalrefcount')`

i.e.: python itself seems to use that: https://github.com/python/cpython/blob/e3dfb9b967c560f4d094092dcae4a16fc9634681/Lib/test/pythoninfo.py#L128
