### ISSUE TITLE
Debugger passes path to debugpy extension as command line argument to script

### ISSUE THREAD

**Issue by patrickkidd** [microsoft/debugpy#153]
## Environment data

- PTVSD version: 2020.4.76186
- OS and version: macOS 10.15.4
- Python version: 3.7.2, built from source with generic arguments
- Using VS Code or Visual Studio: 1.44.2

## Actual behavior

Debugger passes path to debugpy extension as command line argument to script

## Expected  behavior

Debugger should not pass extra command line arguments to debugged script, which breaks common convention in many scripts.

## Steps to reproduce:
1. Debug a python script
2. Observe path to debugpy extension passed as additional command line argument in sys.argv. In my case: '/Users/patrick/.vscode/extensions/ms-python.python-2020.4.76186/pythonFiles/lib/python/debugpy/wheels/debugpy'

**Comment by int19h** [comment]
I can't repro it on a simple script - can you please share your launch.json, and the output of `print(sys.argv)`?

**Comment by patrickkidd** [comment]
Shoot, I'm glad you checked, because It turns out that I was wrong, this is actually coming in as (at least) a macOS application file open event, the kind where you drop a file on the dock icon to open it. I am actually receiving this through Qt/QApplication, so I am not sure how this is all working.

**Comment by int19h** [comment]
I wonder if perhaps Qt is trying to parse command line arguments directly, without going through `sys.argv`. When you start debugging, the entry point is `__main__` in `debugpy` package itself, which sets up all the necessary debugging hooks, and then runs your code - so the original command line that Python binary receives does include debugpy and its arguments. The entrypoint also adjusts `sys.argv` to make it look like it should if you just directly ran Python with your script. But if Qt is getting the arguments directly from the OS, bypassing `sys.argv`, it would still see the original command line.

**Comment by patrickkidd** [comment]
That would make sense since Qt is a C++ library.

**Comment by int19h** [comment]
I would have hoped that PyQt / PySide did the appropriate mapping as part of their projection. There isn't much that we can do about it otherwise, I'm afraid - there's simply no way to run Python with debugger injected without touching either the command line, or the code of the app being run (in which case you can use "attach" + `debugpy.listen()` etc).
