### ISSUE TITLE
Debugger Does Not Call __exit__ on Context Manager When Stopped Mid-Execution

### ISSUE THREAD

**Issue by prokie** [microsoft/debugpy#1543]
Before creating a new issue, please check the [FAQ](https://github.com/microsoft/debugpy/wiki/FAQ) to see if your question is answered there.

## Environment data

- debugpy version: v2024.2.0
- OS and version: Windows 10
- Python version: 3.12.0
- Using VS Code or Visual Studio: VS Code

## Actual behavior

When the debugger is stopped while execution is paused inside the context manager block, the __exit__ method of the context manager is not called.

## Expected  behavior

I expect the __exit__ method of the context manager to be called when the debugger is stopped, ensuring proper resource management and cleanup as per the context manager protocol.

## Steps to reproduce:
```python
class MyContextManager:
    def __enter__(self):
        print("Entering the context")
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        print("Exiting the context")


with MyContextManager() as context:
    print("Inside the context, about to raise a ValueError")
```

1. Create a Python file (context_manager_test.py) with the provided content.
2. Set a breakpoint inside the with block.
3. Start debugging the script.
4. When the execution stops at the breakpoint, stop the debugger using the "Stop" button in the debug toolbar.

**Comment by int19h** [comment]
This is by design. When you do "Stop", it kills the process immediately, thus no cleanup code runs, similar to using `kill` etc. This is intentional, because "Stop" has to reliably work in all situations, even if e.g. the process is deadlocked.

**Comment by prokie** [comment]
Okay, is there another way to exit the program and still run the exit code?

**Comment by int19h** [comment]
It really depends on the app, but for simple console apps, using Ctrl+C to trigger a `KeyboardInterrupt` is the usual approach. For something more complicated, the app itself needs to implement the appropriate way to gracefully shut itself down.

**Comment by prokie** [comment]
Yes `KeyboardInterrupt` seems to do the trick. Thanks.
