### ISSUE TITLE
[sys.monitoring] Local variable cleanup is delayed by debugger

### ISSUE THREAD

**Issue by int19h** [microsoft/debugpy#1548]
When variables are inspected while stopped in a frame, debugger creates reference cycles that cause the frame object and its locals not being released by refcounting, requiring GC to clean up instead. For some types such as file objects this can make previously deterministic cleanup non-deterministic when user code relies on refcounting for the former.

**Comment by judej** [comment]
shelving work for sys.monitoring implmentation for now
