### ISSUE TITLE
Debugger won't launch (Could not import runpy module)

### ISSUE THREAD

**Issue by vadi2** [microsoft/debugpy#1558]
Before creating a new issue, please check the [FAQ](https://github.com/microsoft/debugpy/wiki/FAQ) to see if your question is answered there.

## Environment data

- debugpy version: 2024.2.0 (run `import debugpy; print(debugpy.__version__)` if uncertain)
- OS and version: Debian 12 (Chromebook)
- Python version (& distribution if applicable, e.g. Anaconda): Conda, 3.11.8
- Using VS Code or Visual Studio: VS Code

## Actual behavior

Launching the Python debugger to start debugging is failing with:

```
$  /usr/bin/env /home/vadi/Programs/miniconda3/envs/disy/bin/python /home/vadi/.vscode/extensions/ms-python.debugpy-2024.2.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher 49253 -- /home/vadi/Programs/DiSyFHIRtools/run_examples.py --direction disy_to_fhir 
Could not import runpy module
Traceback (most recent call last):
  File "/home/vadi/Programs/miniconda3/envs/disy/lib/python3.11/runpy.py", line 15, in <module>
    import importlib.util
  File "/home/vadi/Programs/miniconda3/envs/disy/lib/python3.11/importlib/util.py", line 1, in <module>
    current.entry.append({'resource': fhir_resource})
    ^^^^^^^
NameError: name 'current' is not defined
```

`current` is defined however, and running a script without debugging works just fine:

```
$  cd /home/vadi/Programs/DiSyFHIRtools ; /usr/bin/env /home/vadi/Programs/miniconda3/envs/disy/bin/python /home/vadi/.vscode/extensions/ms-python.debugpy-2024.2.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher 60081 -- /home/vadi/Programs/DiSyFHIRtools/run_examples.py --direction disy_to_fhir 
# script output here
```

What could be the issue? I've went as far as deleting the line `current.entry.append({'resource': fhir_resource})` entirely from my script and the error message is exactly the same. 

I've also tried:
* reinstalling the extension
* using an older version of the extension
* reinstalling vscode
* removing $HOME/.config/Code and ~/.vscode entirely
* removing `__pycache__`
* cloning the repository into a new location
* creating a new conda environment

The cached error still present even after all those steps.

## Expected  behavior

Debugger launches as expected.

## Steps to reproduce:
1. Launch debugger in vscode

**Comment by int19h** [comment]
The error message says that this is from the first line of your script. Where is `current` meant to be coming from?

**Comment by vadi2** [comment]
I accidentally modified `/home/vadi/Programs/miniconda3/envs/disy/lib/python3.11/importlib/util.py`and didn't notice!
