### ISSUE TITLE
Skip nonrelevant `case`s in `match/case` during step by step debugging

### ISSUE THREAD

**Issue by Real-Gecko** [microsoft/debugpy#1565]
When debugging C application inf VSCode I've noticed that step by step debugging(F10) through `switch/case` "jumps" immediately to the matched case.
OTOH while debugging Python's `match/case` debugger is stopped on every `case` statement so you have to spam F10 constantly to get to the proper condition and continue execution.
Anyway to prevent this from happening?

**Comment by int19h** [comment]
In C, the values in case labels are all constant expressions, so the only evaluation that needs to take place at runtime is that of the switch expression. In Python, however, every pattern actually needs to be matched against the object at runtime in sequence, as patterns can contain arbitrary expressions in them which aren't evaluated until all previous patterns failed to match. So it's fundamentally a different construct semantically even if it looks similar for simple cases.

**Comment by Real-Gecko** [comment]
Currently I use following trick:
1. Put breakpoint on `match`
2. Put breakpoints right after every `switch`
3. Hit `F5` every time after `match` to "jump" to matched `switch` block
4. Continue through the block with `F10`
While it works it's also very inconvenient to put all those breakpoints and disable them as VSCode does not have [breakpoint groups](https://github.com/microsoft/vscode/issues/105927)

**Comment by judej** [comment]
Thanks for the update @Real-Gecko, unfortunately, the method you are using is the way to do it, because of what @int19h said earlier - Each case is treated as an individual block, causing the debugger to stop on every case during step-by-step debugging (F10).
