### ISSUE TITLE
Implement `justMyCode` fine grained control feature in debugger

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/debugpy#159]
This setting could expand into:
* MyCode - Just my code on/off (everything inside workspace directory is considered `just my code`, excluding `virtual envs`)
* Pkg - Enable debugging of `site packages` (`Just my code is off`)
* StdLib - Enable debugging of `stdlibs` (`Just my code is off`)

I.e. we have three states:
* MyCode
* Pkg
* StdLib
* Pkg + StdLib

Possibly even allowing users to define other directories that fall into `Pkg` category. E.g. user is importing modules from some other directory.

I'll try to come up with an extensible structure for this and then we can discuss.

**Todo:**
* Review how other extensions do this today (configuration)
* Review how VS structures the config settings today

**Comment by johnnybigoode** [comment]
Not sure if this is the same issue but my case `'justMyCode':false` works if I'm using the system's python interpreter. If I switch to conda's it won't even go down standard library. 

Is this expected? Is there anything else I should config?

**Comment by int19h** [comment]
@johnnybigoode It's a different issue - can you please file it separately, and describe it in more detail? Ideally, include the logs from `"logToFile": true`.

**Comment by fabioz** [comment]
Closing this issue.

I believe that what's asked here is already achievable through `rules` (if the standard `justMyCode:false|true` is not enough).

i.e.:
```
rules=[
   {"path": "**/other.py", "include":true},
   {"path": "**/another.py", "include":false},
]
```

Also, the debugger should notify whether breakpoints are actually active (meaning that if the breakpoint is excluded by some `rule` or `justMyCode`, there should be a visual indication now).

Feel free to reopen if you believe I'm missing something here.

**Comment by rrmistry** [comment]
@fabioz , how can we implement `rules`?

I can't seem to find this setting even in insider builds:
![image](https://user-images.githubusercontent.com/25514145/110208682-a0809280-7e56-11eb-93e1-5de82b38f543.png)

Can you reference the PR / extension-repo that allows this?

This is a long sought after feature.
__________

What I am using as of this moment:

VS Code:
> Version: 1.55.0-insider (system setup)
> Commit: 04770364fdc1bebeca9d1a257df2cacce06b35d6
> Date: 2021-03-05T15:40:03.281Z
> Electron: 11.3.0
> Chrome: 87.0.4280.141
> Node.js: 12.18.3
> V8: 8.7.220.31-electron.0
> OS: Windows_NT x64 10.0.19042

Python Extension:
> 2021.2.625869727

**Comment by fabioz** [comment]
It's still not in the vscode-python schema, but it can already be used.

See: https://github.com/microsoft/vscode-python/issues/13719#issuecomment-705768580

**Comment by eddy-geek** [comment]
Full example of *launch.json* to display the full stack but *starting* in user code, ie without the useless stack of the `runpy.py` wrapper:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "justMyCode": false,
            "rules": [
                {"path": "**/runpy.py", "include": false},
            ],
            "env": {
                "PYTHONPATH": "${workspaceFolder}"
            },
        }
    ]
}
