### ISSUE TITLE
Exceptions that inherit from BaseException should not be treated as Uncaught Exceptions

### ISSUE THREAD

**Issue by danielniccoli** [microsoft/debugpy#1590]
Before creating a new issue, please check the [FAQ](https://github.com/microsoft/debugpy/wiki/FAQ) to see if your question is answered there.

## Environment data

- debugpy version: 1.8.1
- OS and version: Windows 11
- Python version: 3.11
- Using VS Code or Visual Studio: VS Code

## Actual behavior

`exit(1)` halts the debugging session due to an "uncaught exception"

![grafik](https://github.com/microsoft/debugpy/assets/2971735/a8baa702-09cf-4965-a396-3e6a0210e62c)

![grafik](https://github.com/microsoft/debugpy/assets/2971735/563eaa10-04a9-4dfd-a933-c7a9f32d8fd8)

## Expected  behavior

The program program should exit without the debugger halting.

Exceptions that inherit from `exception.BaseException` should not fall under the category of "uncaught exceptions", since they are "technically not an error"[^1].

> #### exception.BaseException
> The base class for all built-in exceptions. **It is not meant to be directly inherited by user-defined classes** (for that, use [Exception](https://docs.python.org/3/library/exceptions.html#Exception)).

https://docs.python.org/3/library/exceptions.html#BaseException

One of these exceptions is `exception.SystemExit`, which is called when calling `exit(1)`.

> #### exception SystemExit
> This exception is raised by the [sys.exit()](https://docs.python.org/3/library/sys.html#sys.exit) function. **It inherits from [BaseException](https://docs.python.org/3/library/exceptions.html#BaseException) instead of [Exception](https://docs.python.org/3/library/exceptions.html#Exception) so that it is not accidentally caught by code that catches [Exception](https://docs.python.org/3/library/exceptions.html#Exception)**. This allows the exception to properly propagate up and cause the interpreter to exit. When it is not handled, the Python interpreter exits; no stack traceback is printed.

https://docs.python.org/3/library/exceptions.html#SystemExit

There are only three other Exceptions that inherit from `exception.BaseException`, not counting `exception.Exception`, which does fall under the category of "Uncaught Exceptions":

```
BaseException
 ├── BaseExceptionGroup
 ├── GeneratorExit
 ├── KeyboardInterrupt
 ├── SystemExit
 └── Exception
```

https://docs.python.org/3/library/exceptions.html#exception-hierarchy

> #### exception KeyboardInterrupt
> Raised when the user hits the interrupt key (normally Control-C or Delete). During execution, a check for interrupts is made regularly. **The exception inherits from [BaseException](https://docs.python.org/3/library/exceptions.html#BaseException) so as to not be accidentally caught by code that catches [Exception](https://docs.python.org/3/library/exceptions.html#Exception) and thus prevent the interpreter from exiting.**

> #### exception GeneratorExit
> Raised when a [generator](https://docs.python.org/3/glossary.html#term-generator) or [coroutine](https://docs.python.org/3/glossary.html#term-coroutine) is closed; see [generator.close()](https://docs.python.org/3/reference/expressions.html#generator.close) and [coroutine.close()](https://docs.python.org/3/reference/datamodel.html#coroutine.close). **It directly inherits from [BaseException](https://docs.python.org/3/library/exceptions.html#BaseException) instead of [Exception](https://docs.python.org/3/library/exceptions.html#Exception) since it is technically not an error.**

[^1]: https://docs.python.org/3/library/exceptions.html#GeneratorExit

**Comment by rchiodo** [comment]
Transferring to dicussions for up votes
