### ISSUE TITLE
Please add support for PyCharm

### ISSUE THREAD

**Issue by m-s-abeer** [microsoft/debugpy#1595]
Debugpy is a great tool and easy to get started with. While it's quite easy to configure in vscode, I found no way to connect to PyCharm.

Can we expect to see any tools/plugins that help debug in PyCharm using debugpy?

**Comment by rchiodo** [comment]
Thanks for the suggestion but I believe this would be up to Jetbrains to implement. They do have a help page about it:
https://www.jetbrains.com/help/pycharm/debugging-python-code.html

**Comment by depocoder** [comment]
The Issue in JetBrains
https://youtrack.jetbrains.com/issue/PY-63403/Support-debugpy
