### ISSUE TITLE
debugpy will not step into other's code with justmycode:false automatically

### ISSUE THREAD

**Issue by Mactarvish** [microsoft/debugpy#1597]
Before creating a new issue, please check the [FAQ](https://github.com/microsoft/debugpy/wiki/FAQ) to see if your question is answered there.

## Environment data

- debugpy version: 1.8.1 (run `import debugpy; print(debugpy.__version__)` if uncertain)
- OS and version: Ubuntu 20.04 Desktop
- Python version (& distribution if applicable, e.g. Anaconda): 3.8.18
- Using VS Code

## Actual behavior
From today(before is well) debugpy will not auto step into other's code through `justmycode:fase` set.
Here's my config:
```
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "justMyCode": false
        },
```
![image](https://github.com/microsoft/debugpy/assets/13399458/34fb83f8-1372-43d5-b854-2a1697fc3513)

Now code is under `glob.glob("aaa")` which is third party code, if I click `step into`, the page will instantly jump to `glob.glob("aaa") instead of step into source code of glob (but I can still check source code by clicking the GRAY glob in CALL STACK), which is pretty unconvenient.

XXX

## Expected  behavior

After clicking step into, the code should jump to the source code.

**Comment by dyitzchaki-roku** [comment]
also reported in https://github.com/microsoft/vscode-python-debugger/issues/362

**Comment by rchiodo** [comment]
Thanks for the issue.

This is actually a bug in VS code. See this issue here:
https://github.com/microsoft/vscode/issues/214433
