### ISSUE TITLE
Can't create plot from the debug console

### ISSUE THREAD

**Issue by rameshcjn** [microsoft/debugpy#1606]
Hey!

With the new update a new problem got introduced as described in the following thread regarding the Python version  [https://github.com/microsoft/vscode-python/issues/23649](url)

Since then matplotlib does not work anymore when calling e.g. plt.imshow() from the debug console . An empty window opens without an image inside and it cant be closed either. Only a full stop of the debugger closes it. When calling the same function from the script everything works fine.

**Comment by yhidaka** [comment]
I'm encountering the same issue. But if I lower `matplotlib` version from 3.9 to 3.8 (3.8.4 to be precise) in my `conda` environment, then the problem has disappeared, at least for me.
