### ISSUE TITLE
When JustMyCode Disabled, the breakpoint does not automatically stop at the script exception

### ISSUE THREAD

**Issue by joon612** [microsoft/debugpy#1628]
When `justMyCode` is *false* in `launch.json`, the breakpoint does not automatically stop at the script exception. And if the break point is set, it doesn't stop there.
``` powershell
(env) PS C:\Users\user> conda --version
conda 24.5.0
(env) PS C:\Users\user> python -V
Python 3.9.19
(env) PS C:\Users\user> code --version
1.91.1
f1e16e1e6214d7c44d078b1f0607b2388f29d729
x64
```
Reproduce:
![Recording 2024-07-18 at 08 51 40](https://github.com/user-attachments/assets/b57a6abb-8d87-4cd9-8148-cd3bdef8b7ae)

**Comment by rchiodo** [comment]
This looks like another case for this issue here:
https://github.com/microsoft/vscode/issues/214433

The exception is being hit but VS code is not showing the callstack.

**Comment by rchiodo** [comment]
I can't reproduce the issue though. 

I used this code:

```python
import json
import sys

from pathlib import Path

def main():
    input_path = Path(r"/non-existent-path")
    print(list(input_path.rglob("*.whl"))[1])

main()
```

And tried it with justMyCode by true and false. I get the exception in both cases.

**Comment by rchiodo** [comment]
Can you double-check that you're using the latest VS code? The help about should show something like this;

![image](https://github.com/user-attachments/assets/f0295bc2-65b5-4c5b-bbce-2d67914a1bbd)

**Comment by rchiodo** [comment]
Oh I can reproduce the problem when it's set to catch the raise of the exception too. 

There's an error from VS code here:
![image](https://github.com/user-attachments/assets/94930575-7887-4eff-a9bf-c74d98bb947b)

**Comment by rchiodo** [comment]
That path seems to be invalid. Not sure why.

**Comment by rchiodo** [comment]
Oh that's because that's the error. The issue is in VS code. It seems to be another symptom of the original issue. Closing this one again.

Here's the logs for when thi
[debugger_logs.zip](https://github.com/user-attachments/files/16287000/debugger_logs.zip)
s reproduces:

**Comment by joon612** [comment]
> Can you double-check that you're using the latest VS code? The help about should show something like this;
> 
> ![image](https://private-user-images.githubusercontent.com/19672699/350069803-f0295bc2-65b5-4c5b-bbce-2d67914a1bbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNDkyMDgsIm5iZiI6MTcyMTM0ODkwOCwicGF0aCI6Ii8xOTY3MjY5OS8zNTAwNjk4MDMtZjAyOTViYzItNjViNS00YzViLWJiY2UtMmQ2NzkxNGExYmJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDAwMjgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2YmU2MWI0MmYwODYyOTBiY2Q4MDQ5YWY3MWM0N2YxMDU3MjVhN2MwYjczYWY5MWNkZjAwNzJlYmRkOWY4MmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vDuMjT_f3cs-l7b1ONAM4CDFkqdhSF6Sk0ol9jIrkNY)

![image](https://github.com/user-attachments/assets/de9a8383-baaa-4707-baf6-d8972f86f8b0)
here it is my VS Code version

**Comment by clement-moulin-frier** [comment]
This issue has been bugging me for a while as well. I have solved it simply by unchecking "Raised Exceptions" in the Breakpoints tab of VSCode. 
This way it only breaks for uncaught exceptions.
