### ISSUE TITLE
Debugger is entering runpy.py for no reason

### ISSUE THREAD

**Issue by ibobak** [microsoft/debugpy#1631]
Type: <b>Bug</b>

# Behaviour

When debugging the following code I am redirected to some internal module - see below.  
This should not happen. 

## Steps to reproduce:

Use this code:
```
class Node:
    def __init__(self, a_val) -> None:
        self.val = a_val
        self.next = None
    
    def __eq__(self, value: object) -> bool:
        if isinstance(value, Node):
            return self.val == value.val
        return False
        
a = Node(20)
b = Node(20)

print(a==b)
```

on this line:
![image](https://github.com/microsoft/vscode-python-debugger/assets/8807043/36827cad-6d92-436e-9594-5f5fc6c56a78)

after pressing F10  I will get this:
![image](https://github.com/microsoft/vscode-python-debugger/assets/8807043/b1d5b547-ff41-4061-b1df-70bc8477e96c)

My shortcuts
![image](https://github.com/microsoft/vscode-python-debugger/assets/8807043/f2aad71c-f813-49ba-aab0-e21c8debf4e8)

# Diagnostic data
<details>

<summary><code>launch.json</code> configuration
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>Output for <code>Python Debugger</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python Debugger</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

Extension version: 2024.6.0
VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:16:23.416Z)
OS version: Linux x64 6.4.6-060406-generic
Modes:

-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.9
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Conda<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2696 v4 @ 2.20GHz (88 x 1197)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|251.76GB (87.86GB free)|
|Process Argv|--crash-reporter-id 27d42247-63fb-4d9e-9cb0-87d9974843dc|
|Screen Reader|no|
|VM|50%|
|DESKTOP_SESSION|ubuntu-xorg|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu-xorg|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelt:31048053
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31049070
a69g1124:31058053
pythonprt:31056678
dwnewjupyter:31046869
26j00206:31048877

```

</details>

**Comment by rchiodo** [comment]
That's the last line of execution and you have justMyCode turned off. It's stepping into the code that called you. (running under the debugger launches the program differently)

This should be by design. I don't believe pydevd modules are special cased to not count towards stepping when justMyCode is false.

**Comment by rchiodo** [comment]
Yeah it's the runpy in the system runtime, so it's not even stepping through the debugger code. It's stepping through the code that's running in the system.

I suppose we could special case this situation to detect that it's the last line of the program? Seems like overkill though.

**Comment by clement-moulin-frier** [comment]
This issue has been bugging me for a while as well. I have solved it simply by unchecking "Raised Exceptions" in the Breakpoints tab of VSCode. 
This way it only breaks for uncaught exceptions (the one raised by runpy.py is actually caught, so we don't care breaking there)
