### ISSUE TITLE
investigate integration with pydevd that has the sys.monitoring changes

### ISSUE THREAD

**Issue by judej** [microsoft/debugpy#1640]

**Comment by rchiodo** [comment]
Did some preliminary work on this. I'm not sure pydevd is finished with sys.monitoring support. We get about 50 test failures with py312 (py311 and others work fine) after the port.

**Comment by rchiodo** [comment]
Root cause of failures seems to be 3.12 pydevd doesn't handle unhandled exceptions. 

In 3.11 for one of the tests that fails, this output shows up in the log:

```
0.00s - Handling post-mortem stop on exception breakpoint BaseException
0.00s - We are stopping in unhandled exception.
0.00s - Suspending all threads except: <_MainThread(MainThread, started 28628)>
0.00s - PyDB.do_wait_suspend
name: <module> (line: 11)
 file: C:\Users\rchiodo\AppData\Local\Temp\pytest-of-rchiodo\pytest-9\popen-gw0\test_systemexit_0_zero_uncaugh0\code_to_debug.py
 event: exception
 arg: (<class 'SystemExit'>, SystemExit(0), <traceback object at 0x000001D50CDFCE00>)
 step: CMD_STEP_INTO (original step: <Unknown: -1>)
 thread: <_MainThread(MainThread, started 28628)>, thread id: pid_26076_id_2014531609488, id(thread): 2014531609488
0.00s -   Stack: C:\Users\rchiodo\AppData\Local\Temp\pytest-of-rchiodo\pytest-9\popen-gw0\test_systemexit_0_zero_uncaugh0\code_to_debug.py, <module>, 11
0.00s -   Stack: <frozen runpy>, _run_code, 88
0.00s -   Stack: <frozen runpy>, _run_module_as_main, 198
0.00s - Skipping per-thread thread suspend notification.
0.00s - Thread suspend mode: single notification
0.00s - Sending suspend notification.
0.00s - sending cmd (http_json) --> CMD_THREAD_SUSPEND_SINGLE_NOTIFICATION {"type": "event", "event": "stopped", "body": {"reason": "exception", "description": "0", "threadId": 1, "preserveFocusHint": false, "text": "SystemExit", "allThreadsStopped": true}, "seq": 36, "pydevd_cmd_id": 157}
```

Same test in 3.12, no such post-mortem stop

**Comment by rchiodo** [comment]
Question then becomes do we integrate newer pydevd or just finish the sys.monitoring work for 3.12 in debugpy.

**Comment by rchiodo** [comment]
This test and many others is failing currently in our implementation of sys.monitoring, so pydevd is likely further along.

**Comment by rchiodo** [comment]
Consensus was to scrap this work (archived at https://github.com/rchiodo/debugpy/tree/rchiodo/update_pydevd) and just finish the debugpy work on 3.12

**Comment by rchiodo** [comment]
Changed our minds again. Going to integrate latest pydevd.

**Comment by rchiodo** [comment]
First reason for failure, stack frames on attach are deeper than launch. Not sure why (I don't think sys module would know about filtering out just my code?).

Deeper stack frame means the frame matching for the unhandled exception walk doesn't work.

**Comment by rchiodo** [comment]
Finished this work
