### ISSUE TITLE
Can't install version 1.8.3

### ISSUE THREAD

**Issue by danielzn** [microsoft/debugpy#1648]
## Environment data

- OS and version: macOS 14.6

## Actual behavior

> Could not find a matching version of package debugpy

## Expected  behavior

Installs debugpy 1.8.3

## Steps to reproduce:
1. `poetry add debugpy=1.8.3`

**Comment by tadasgedgaudas** [comment]
Seems like someone removed 1.8.3

https://pypi.org/project/debugpy/#history

![image](https://github.com/user-attachments/assets/648c1100-cb80-4707-9808-ceb2c6028455)

**Comment by pawel-biernacki-roche** [comment]
So that is why our CI is breaking since the morning.
