### ISSUE TITLE
py2.py3-none-any wheels include pyd files with missing symbols

### ISSUE THREAD

**Issue by rzhao271** [microsoft/debugpy#1651]
Before creating a new issue, please check the [FAQ](https://github.com/microsoft/debugpy/wiki/FAQ) to see if your question is answered there.

## Environment data

- debugpy version: debugpy-1.8.5-py2.py3-none-any.whl
- OS and version: Windows 11
- Python version (& distribution if applicable, e.g. Anaconda): N/A
- Using VS Code or Visual Studio: N/A

## Actual behavior

After extracting the wheel, I notice there are no PDB files for pydevd_frame_evaluator.cp39-win_amd64.pyd and pydevd_cython.cp39-win_amd64.pyd.

## Expected  behavior

After extracting the wheel, PDB files should either be there for pydevd_frame_evaluator.cp39-win_amd64.pyd and pydevd_cython.cp39-win_amd64.pyd, or symbols for those pyd files should be available for downstream consumption.

## Steps to reproduce:
1. Download debugpy-1.8.5-py2.py3-none-any.whl from https://pypi.org/project/debugpy/1.8.5/#files
2. Rename the .whl to .zip and extract it
3. In a pwsh terminal, change the directory into the extracted folder and run `Get-ChildItem -Path . -Filter "*.pdb" -Recurse` and `Get-ChildItem -Path . -Filter "*.pyd" -Recurse`
4. :bug: There are no PDB files for pydevd_frame_evaluator.cp39-win_amd64.pyd and pydevd_cython.cp39-win_amd64.pyd.

**Comment by rchiodo** [comment]
Thanks for the issue but why should we ship pdb files? Seems like unnecessary bloat. If you want to debug the c++ code in debugpy, you can build it locally.

**Comment by rchiodo** [comment]
1.8.6 should have fixed this. PDB files are there now.
