### ISSUE TITLE
Debugpy 1CS assessment

### ISSUE THREAD

**Issue by AdamYoblick** [microsoft/debugpy#1658]
https://devdiv.visualstudio.com/DevDiv/_compliance/product/426903c3-8904-63d0-d281-6617c5e1f2ea/assessments

**Comment by AdamYoblick** [comment]
I'm unassigning myself from this as all the assessment tasks are done except some stuff in IcMNow that I don't have access to. @judej This last task is yours I believe. 😄

**Comment by judej** [comment]
done
