### ISSUE TITLE
Matplotlib and Opencv do not open the images when I use them in debug mode in vscode.

### ISSUE THREAD

**Issue by gazziro** [microsoft/debugpy#1663]
When I use plt.imshow or cv2.imshow in vscode debug mode, my image doesn't load, see what happens:
![image](https://github.com/user-attachments/assets/c88d7220-ecdb-44db-a3cf-b391ee4fa77d)

But, if I use it outside the debugger, just running the file, my image appears normally.

Python 3.12.5
Matplotlib 3.9.2
opencv-python 4.10.0.84

When my code was in Python 3.7, it worked normally

**Comment by rchiodo** [comment]
I would guess this is either a dupe of this item:
https://github.com/microsoft/debugpy/issues/1640
Or this item:
https://github.com/microsoft/debugpy/issues/1640

**Comment by gazziro** [comment]
Hello Rich, thanks for answering! I solved just downgrading my matplotlib version from 3.9.2 to 3.7.5 (probably for the same reason matplot 3.8.x versions don't work). I hope there will be compatibility in the future!
