### ISSUE TITLE
Add Python 3.13 to test matrix

### ISSUE THREAD

**Issue by AdamYoblick** [microsoft/debugpy#1667]

**Comment by AdamYoblick** [comment]
@judej @karthiknadig Karthik, Jude asked me to add Python 3.13 to the test matrix in anticipation of release. Unfortunately, 3.13 is not available to the `Use Python Version` Azdo task, so this step is failing for all platforms.

See https://dev.azure.com/debugpy/debugpy/_build/results?buildId=4228&view=logs&j=e545b7f1-8fae-520d-02ab-d6dba42df965&t=a282e492-efe7-5343-e9fe-8ee87399707a

I checked the task docs and I think it's failing because `allowUnstable` is set to false. I'll try it enabled and see what happens.

**Comment by AdamYoblick** [comment]
Allowing unstable doesn't seem to make a difference. This is odd though because I checked the python-versions manifest file at https://github.com/actions/python-versions/blob/main/versions-manifest.json#L103 and I do see an unstable release for python 3.13 so I'm not sure why it can't be downloaded.

**Comment by karthiknadig** [comment]
You may have to install 3.13 locally and test. GitHub actions typically has dev builds available. May be we need to keep test runner for dev builds on there.

**Comment by juliangilbey** [comment]
`debugpy` was just tested on Debian with Python 3.13 and failed several tests: the Debian bug report is here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1082090 (and it gives a link to full test logs which will be available for the next 30 days).

Best wishes, Julian

**Comment by AdamYoblick** [comment]
> `debugpy` was just tested on Debian with Python 3.13 and failed several tests: the Debian bug report is here: [bugs.debian.org/cgi-bin/bugreport.cgi?bug=1082090](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1082090) (and it gives a link to full test logs which will be available for the next 30 days).
> 
> Best wishes, Julian

Thank you for this! I've downloaded the full logs and put it on my OneDrive. People from MS can get it at https://microsoft-my.sharepoint.com/:t:/p/advolker/EVNkdfQR8jVHnV9qEkv-xOEB_Mq6Vu6SZK_T2vYtkVCixw?e=mXCxgb

**Comment by AdamYoblick** [comment]
Looks like I was able to attach it to this issue as well.

[log.txt](https://github.com/user-attachments/files/17050390/log.txt)

**Comment by rchiodo** [comment]
This commit in CPython changes how `_is_stopped` is computed. This is likely breaking stuff because pydevd looks directly at this attribute.

https://github.com/python/cpython/commit/33da0e844c922b3dcded75fbb9b7be67cb013a17#diff-b250d3d0e0d909784a67083e9069ce507513a67e8514a011e2f364027e25e0b0

We need to fix all of the spots were we call `thread._is_stopped` to instead use `thread._handle.is_done()`

**Comment by rchiodo** [comment]
This should be part of the test matrix now.
