### ISSUE TITLE
PID reuse can cause errors in the adapter

### ISSUE THREAD

**Issue by int19h** [microsoft/debugpy#168]
Consider this scenario:

1. Process X with PID=123 spawned.
1. X connects to adapter, registers itself.
1. X exits, but the exit is not yet observed by adapter.
1. Process Y with reused PID=123 spawned.
1. Y connects to adapter, tries to register it.
1. Adapter sees that PID=123 corresponds to X, rejects Y.
1. Adapter observes X exiting, deregisters X.

The problem is that, while process lifetimes themselves are ordered and non-overlapping, observing those lifetimes happens asynchronously across multiple threads inside the adapter, and that can create phantom overlapping of PIDs. 

The fix would be to not immediately fail when a duplicate PID tries to connect, but wait a little bit to allow the other thread to observe process exit and deregister it. It still needs a timeout in case this really is an invalid connection with identical PID, though.

**Comment by judej** [comment]
Closing since we do not have any cases of this happening in the wild. If someone encounters this issue, please reopen.
