### ISSUE TITLE
Debugging doesn't work in Jupyter notebooks

### ISSUE THREAD

**Issue by johnl800** [microsoft/debugpy#1693]
Debugging doesn't work in Jupyter notebooks - the breakpoints are ignored.

Debugging works with a normal .py file.

VS Code and all of my extensions are up to date.
I'm running Windows 10. I don't think the Python version matters: I've recently updated to 3.12, I think I was running 3.8 when I first noticed it.

Please fix this.

**Comment by rchiodo** [comment]
Thanks for the issue but we're going to need more information.

It works for me:

![Image](https://github.com/user-attachments/assets/c4126b89-57e9-42a2-9030-1fb721b05ff2)

Did you try with a simple notebook? How did you start the debugger?

**Comment by johnl800** [comment]
I'm not sure what you mean by simple notebook, the file extension is .ipynb.

I started the debugger from the run menu.

The file is saved locally.

I just tried disabling other Jupyter related extensions, but that didn't help. I notice that when the cell runs (after loading the kernel) the break point changes from a red dot to a white doughnut.

**Comment by rchiodo** [comment]
By simple notebook I mean something that just has a couple of print statements, and not something that's calling into say other functions defined in other cells or python files.

By run menu, I assume you mean this?

![Image](https://github.com/user-attachments/assets/a1873909-808a-4ceb-a214-8b0ef357ef36)


The jupyter extension has to be enabled for this to work (it's the one that sends the necessary commands to the debugger). 

What's your version of the jupyter extension?

**Comment by rchiodo** [comment]
If you set this to debug:

![Image](https://github.com/user-attachments/assets/0526b886-32f1-4d60-9e78-5cb820beb0a3)


The jupyter output log will show all of the conversions it does for debugging.

For example, I have output like so:

```
14:00:31.669 [debug] [Debug] to kernel: {"command":"setBreakpoints","arguments":{"source":{"name":"test_notebook.ipynb","path":"vscode-notebook-cell:/c%3A/Users/~/source/testing/test_pylance/test_notebook.ipynb#W3sZmlsZQ%3D%3D"},"lines":[4],"breakpoints":[{"line":4}],"sourceModified":false},"type":"request","seq":6}
```

Which is how debugpy is told what cell your breakpoint is in.

**Comment by johnl800** [comment]
Actually, I was selecting debug from the VS Code Run menu. I thought I'd tried the menu on the cell and it didn't work, but now it works! If you think that it should work from the VS Code menu, then that's the issue. If not, you can close this issue.

Thanks!

**Comment by rchiodo** [comment]
Sorry it only works from the debug cell menu. Jupyter has to do that translation for that I showed for debugging in a notebook to work and they handle the 'debug cell' command.

Thanks for getting back to us.
