### ISSUE TITLE
Send custom message to Python extension in VS Code for justMyCode

### ISSUE THREAD

**Issue by Anapo14** [microsoft/debugpy#170]
We are learning that most users are struggling to discover the justMyCode warning message we print in the debugger console when they attempt to step into library and have the toggle set to 'true'. It would be great if we could send a custom message to the python extension and let the extension-side handle the action of pulling focus to the console,better alerting users about the justMyCode warning.  We could even have a pop-up that allows the user to disable the setting as well as a 'learn more' link included in the notification that leads to a screenshot/example in the docs displaying the behavior.

**Comment by fabioz** [comment]
I think we may also want to show a message in case a breakpoint is disabled due to justMyCode (i.e.: the VSCode UI isn't great at the moment: https://github.com/microsoft/debugpy/issues/572).

**Comment by int19h** [comment]
DAP now has the "important" category that is exactly this: https://github.com/microsoft/debug-adapter-protocol/issues/218

It's not implemented in the VSCode client just yet, but it's already scheduled: https://github.com/microsoft/vscode/issues/138091

Note that existing clients are already required by the spec to implement any unknown value as "console", so we can switch right away without having to wait for VSCode.

**Comment by karthiknadig** [comment]
> DAP now has the "important" category that is exactly this: microsoft/debug-adapter-protocol#218

This is fantastic.
