### ISSUE TITLE
Logpoints not working if there's no active breakpoints.

### ISSUE THREAD

**Issue by farzbood** [microsoft/debugpy#1702]
Hi there,
In my experience, when debugging my python code, the Logpoint(s) only works when there'll be at least one active breakpoint set in the editor, and they become inactive/suppressed otherwise (provide no output message).
It would be nice to still receive Log messages when debugging code, to be informed of the code behavior even if there were no active breakpoint desired.

P.S
Based on the [VSCode documentation](https://code.visualstudio.com/docs/editor/debugging#_logpoints), Logpoints supposed to replace temp print() lines in the code to help keeping it clean, which is nice, but in the above mentioned situation, developers still have to use those print() lines to get insights!

DEV Environment:
- Windows 10 Enterprise (Version 22H2 - OS build 19045.5011)
- VSCode, Python, Python Debugger Extensions (Latest versions to date)
- Python 3.11.2

Regards

**Comment by rchiodo** [comment]
Do you have an example? They work for me:

![Image](https://github.com/user-attachments/assets/514de2ea-7dc8-43be-b912-289ca4669035)

Output shows up in the Debug Console, not the terminal.

**Comment by farzbood** [comment]
Hi Rich,
Just when I was going to reproduce it, recieved this **update** for `Python Debugger`, and the case resolved. (Logpoints work as expected now)

![Image](https://github.com/user-attachments/assets/e3e7d7a6-8d5f-4b81-941f-8d19a372248f)

Thanks for the response anyway
Happy Coding
