### ISSUE TITLE
debugger cannot be used

### ISSUE THREAD

**Issue by StrawberryGZ** [microsoft/debugpy#1707]
Hi guys,

I don't know why my debugger cannot be used. I tried to changed the python version from the latest one to 2022.4.0 and it still cannot work.

And I followed an instruction to change my launch.json to this:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        // {
        //     "name": "Python: 
        //     "type": "python",
        //     "request": "launch",
        //     "program": "${file}",
        //     "console": "integratedTerminal",
        //     "justMyCode": true
        // }    
        {
                "name": "Python", 
                "type": "debugpy",
                "request": "launch",
                "stopOnEntry": false, 
                "python": "D:\\softwares\\anaconda\\python.exe", 
                "program": "${file}",
                "cwd": "${workspaceRoot}",
                "console": "integratedTerminal",
                "justMyCode": true, //只调试自己的Code
                "env": {},
                "envFile": "${workspaceRoot}/.env",
                "redirectOutput": true
        }
    ]
}
```
vscode Version: 1.94.2 (user setup)
python debugger: v2024.12.0
python: v2024.16.1
pylance: v2024.10.1

AND things aren't change, I still cannot use debugger, plsssssssss help!!!

**Comment by rchiodo** [comment]
I don't think you're using the configuration you think from the launch.json. In this drop down it should just say "Python" (not Python can post processing) 

Your command line args look like you're just running the debugger without any arguments.

**Comment by rchiodo** [comment]
No, I take that back. It looks like there must be multiple workspaces and that launch.json for the current workspace has just one item in it. 

@karthiknadig wouldn't this be an issue in the launch then? Debugpy doesn't send the arguments here, it's the extension?

**Comment by karthiknadig** [comment]
If you see the screenshot of the logs here:
![Image](https://github.com/user-attachments/assets/6baea468-13c7-4eaf-8de4-37bf95d6151a)

It looks like the extension is submitting the correct adapter path and python. It looks like debugpy is failing to start because you can see the brief moment of the debug session starting.

I suspect either a library shadowing issue or extension corruption.

**Comment by rchiodo** [comment]
@StrawberryGZ what does the terminal say? Running the debugger should output something in the terminal.

For me it does this:

```
PS C:\Users\rchiodo\source\testing\test_auto_import>  & 'c:\Users\rchiodo\AppData\Local\Microsoft\WindowsApps\python3.11.exe' 'c:\Users\rchiodo\.vscode-insiders\extensions\ms-python.debugpy-2024.13.2024101501-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher' '62219' '--' 'C:\Users\rchiodo\source\testing\test_auto_import\app\db\test.py' 
```

That will likely show whatever error is occurring.

**Comment by karthiknadig** [comment]
@StrawberryGZ You can also try running this from the terminal:
`d:\softwares\anaconda\python c:\Users\Yanbo.Zhang7\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\adapter`

If there is any issue it will throw an error. If there are no issue then it will be blank. You can terminate the process using `ctrl+c`.  

@rchiodo If it fails before the DAP server has the opportunity to start then they might not see the terminal command. The above should indicate if something is failing before it can start the server. If that does not fail, then the next step is to manually launch the DAP server, using the debug server mode, and you can then connect to it from VS Code using debugServer in launch config. This way you can check if the server is starting independent of VS Code. Then launch config will then attach to the DAP server, from that point on it goes through the same process as regular launch. We use this to isolate issue between debugpy and the extension.

**Comment by StrawberryGZ** [comment]
hi guys, I tried again. and nothing showed up in the terminal output. It seems debugger does not start.

**Comment by rchiodo** [comment]
Nothing shows up, not even the command?

This:

'c:\Users\rchiodo\AppData\Local\Microsoft\WindowsApps\python3.11.exe' 'c:\Users\rchiodo\.vscode-insiders\extensions\ms-python.debugpy-2024.13.2024101501-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher' '62219' '--' 'C:\Users\rchiodo\source\testing\test_auto_import\app\db\test.py'

**Comment by StrawberryGZ** [comment]
![Image](https://github.com/user-attachments/assets/ac686b75-8f28-4b31-9178-b458c71d2125)

Like this.

**Comment by StrawberryGZ** [comment]
![Image](https://github.com/user-attachments/assets/2de17976-107f-4696-9156-0dd95cfe6485)
sorry  for the late response, it shows like this

**Comment by StrawberryGZ** [comment]
![Image](https://github.com/user-attachments/assets/4a5c8c1d-1749-442c-954c-c5d31aaabe31)
sorry for the late response, it shows like this

**Comment by rchiodo** [comment]
Can you follow the directions here and upload the logs?
https://github.com/microsoft/debugpy/wiki/Enable-debugger-logs

That should show the commands sent to the debugger and sent back to VS code. I suspect VS code is not getting the commands or is erroring when receiving them.
