### ISSUE TITLE
TypeError: 'None' comparison in collect_try_except_info()

### ISSUE THREAD

**Issue by Sorontik** [microsoft/debugpy#1720]
Hello,

when an exception occured in my Program, i got this output in the debug console:

> 79.61s - Error collecting try..except info from source (src/main.py)
Traceback (most recent call last):
  File "c:\Users\<username>\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\pydevd.py", line 796, in collect_try_except_info
    if line > max_line:
       ^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'NoneType' and 'int'

Unfortunately, the Program is rather complex and i was unable to reproduce this error in a simplified Version of my script.

This did not happen previously, so it might be related to the changes in one of the last releases (I'm currently on v2024.12.0 which should be the latest - on a up-to-date VS-Code)

**Comment by rchiodo** [comment]
Thanks for the issue. This was caused by changes in 3.12. Similar to this issue here:
https://github.com/microsoft/debugpy/issues/1708
