### ISSUE TITLE
After continue from breakpoint an enter is inserted in my code

### ISSUE THREAD

**Issue by AUNL-BartRijvers** [microsoft/debugpy#1728]
## Environment data

- debugpy version: 1.8.7
- OS and version: Windows 11 Business version 23H2
- Python version: 3.10.11
- Using VS Code: 1.95.2

## Actual behavior

I'm debuging my python code and put a breakpoint where execution halts without issues. When I however step over, step out, continue with, also an enter is inserted at the cursor position. This sometimes also occurs just before hitting the breakpoint.

## Expected  behavior

Debug controls should not modify my code

## Steps to reproduce:

Edit any python scipt in vscode
Put a breakpoint
Debug the script, let it hit the breakpoint
Put the cursor mid-line
Choose step over or continue and the code is changed afterward, an enter has been put at the cursor position

A reboot of my computer did not give other results

![Image](https://github.com/user-attachments/assets/4b06771e-2ce2-45fa-95ad-c8d98cd46aac)
1) I put my cursor at this position where the line was still complete with the next line appended.
2) I put a breakpoint there and ran the code in debugger
3) Choose Continue button
4) Code hit the next breakpoint 
5) I scrolled back to find the previous break location changed like in the picture, text after the previous cursor position was put at next line

**Comment by rchiodo** [comment]
Thanks for the issue but this wouldn't be debugpy doing this. Debugpy has no code running in VS code. There must be some other extension that's doing something when a debug event occurs.

I would try it again with all other extensions disabled.

**Comment by AUNL-BartRijvers** [comment]
Thanks, I was working from home yesterday (using bluetooth mouse, different keyboard, different monitor) and now working from office (wired mouse, docking station) and the issue is not seen anymore, I can't reproduce anymore. I will check next time I work from home but I agree to close it.
