### ISSUE TITLE
Watch variables de-activates debugger (breakpoints and code-stepping fails) with GEVENT

### ISSUE THREAD

**Issue by felmoreno1726** [microsoft/debugpy#1743]
## Environment data

- debugpy version: v2024.12.0
- OS and version: Fedora 40
- Python version Python 3.12.7
- Using VS Code or Visual Studio: VS Code

## Actual behavior

Whenever a Watch Variable is defined, only the first breakpoint is hit. Subsequent breakpoints are ignored and the code will continue executing without stopping at a subsequent breakpoint. Also stepping-in or stepping-over becomes disabled and the code will just resume execution afterwards.

## Expected  behavior

The expected behavior is that the debugger is able to control the execution of the program: stepping through lines of code, stepping-in and stopping at subsequent breakpoints. (Even if Watch Variables are defined).

## Steps to reproduce:
1. I'm running a Flask application with Gevent workers and monkey_patch enabled.
2. The environment variable GEVENT_SUPPORT = True  (However annoying warnings are still present)

``` It seems that the gevent monkey-patching is being used.
Please set an environment variable with:
GEVENT_SUPPORT=True
to enable gevent support in the debugger.
```

**Comment by felmoreno1726** [comment]
I go the following out of DEBUG CONSOLE output:

`Exception ignored in thread started by: <bound method Thread._bootstrap of <WriterThread(pydevd.Writer, started daemon 140290625427136)>>
Traceback (most recent call last):
  File "/usr/lib64/python3.12/threading.py", line 1032, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.12/threading.py", line 1079, in _bootstrap_inner
    self._delete()
  File "/usr/lib64/python3.12/threading.py", line 1111, in _delete
    del _active[get_ident()]
        ~~~~~~~^^^^^^^^^^^^^
KeyError: 140290516462976`


Let me know if you need additional information to reproduce the issue.

**Comment by rchiodo** [comment]
Do you have a sample app that I can use to try this out?
