### ISSUE TITLE
"List index error out of range" when debugger breaks on uncaught exception

### ISSUE THREAD

**Issue by kunom** [microsoft/debugpy#1745]
## Environment data

- debugpy version: 1.8.7
- OS and version: Windows 11
- Python version (& distribution if applicable, e.g. Anaconda): 3.13.0,  downloaded from python.org
- Using VS Code or Visual Studio: VS Code

## Actual behavior

When the debugger breaks on an exception, the following output appears in the terminal:

```
2.79s - Error on build_exception_info_response.
Traceback (most recent call last):
  File "c:\Users\mek\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_comm.py", line 1533, in build_exception_info_response 
    stack_str = "".join(stack_summary.format())
                        ~~~~~~~~~~~~~~~~~~~~^^
  File "c:\Program Files\Python313\Lib\traceback.py", line 749, in format
    formatted_frame = self.format_frame_summary(frame_summary, colorize=colorize)
  File "c:\Program Files\Python313\Lib\traceback.py", line 553, in format_frame_summary
    last_line = all_lines_original[frame_summary.end_lineno - frame_summary.lineno]
                ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range
```

## Expected  behavior

The output distracts. Also, there might be functional degradation.

## Steps to reproduce:
In Visual Studio Code, enable "halt on exception", F5-debug a file that throws an exception

**Comment by rchiodo** [comment]
That error looks like a bug in Python itself, not the debugger. The traceback module shouldn't throw an exception when asking for a format.

**Comment by rchiodo** [comment]
I can't reproduce the issue either. What's your version of CPython? I'm using 3.13.0.

This is the code I used to reproduce:

```python
i = 0
while True:
    x = 1 / i # Exception thrown here
```

No output in debug console for me:

![Image](https://github.com/user-attachments/assets/8a4e6f50-faea-463b-a4a1-b1c408a2a4c7)

**Comment by rchiodo** [comment]
Maybe the exception you're throwing has something to do with the issue. Can you provide a code sample?

**Comment by kunom** [comment]
Minimal reproduction see below. The issue is triggered by having the parameters to the `query` call distributed over multiple lines.

```python
def query(url, params=None, json=True):
    raise Exception("foo")

query(
    "",
    params=None,
    json=False,  # distribute your parameters over multiple lines!
)
```

Results in:
![Image](https://github.com/user-attachments/assets/9bf4dc77-e7fc-45fa-9d81-1bd946bb6e3d)

----

By the way, but maybe not related, if you select "break on raised exception", it tries to load a packed variant of the standard library, which does not exist:
![Image](https://github.com/user-attachments/assets/d6af8a01-a4e2-41bd-a323-b3ad4be9b20c)

**Comment by rchiodo** [comment]
The raised exception error is expected when you have 'justMyCode' set to false. That's an internal error that is always thrown when running.

**Comment by rchiodo** [comment]
Thanks, I can reproduce the issue with your query exception. It looks like a bug here:
https://github.com/microsoft/debugpy/blob/f4ba976121ce38ee1c7c1f3174fcc520bccc7e19/src/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py#L1527

That code needs to make sure the line numbers are not none before adding it to the summary.

**Comment by rchiodo** [comment]
Actually, it was slightly more complicated. Not sure how this worked in 3.11 and 3.12 but the frame summaries we were generating didn't have the correct line text.

**Comment by bartvanandel** [comment]
Thanks for this fix! Just yesterday I ran into this as well when debugging some python code suffering from a circular import chain. I just monkey-patched the installed `ms-python.debugpy` extension with this fix, and it resolved the issue (after cleaning any `__pycache__` dirs and restarting the extension host). I'm hoping for a quick release of that extension, thanks! 🚀
