### ISSUE TITLE
Bad breakpoint condition crashes VSCode with "oom" code -536870904 or "crashed" code -36863

### ISSUE THREAD

**Issue by cbeytas** [microsoft/debugpy#1746]
VSCode v1.95.3 with Python Debugger v2024.12.0 on Windows 10 19045.5131

### Steps to reproduce:
``` python
i = 0
while True:
    i += 1
```
Add a breakpoint on `i += 1` with a condition that causes an exception e.g. `i.blah == 2370433`.
Run the code in the debugger then hit the pause button.

### Result:
VSCode will become unresponsive and the `Code.exe --type=renderer` process will use 100% CPU and start to consume a huge amount of memory.
In my system when it hits 17 GB it will crash VSCode.

![Image](https://github.com/user-attachments/assets/a80e314a-a822-4f9a-a7e1-a2903c34af98) ![Image](https://github.com/user-attachments/assets/08dd737f-5c85-48c6-a3b6-7bd850ec9d5a)

**Comment by rchiodo** [comment]
I get no such problem. It just stops at the current line:

![Image](https://github.com/user-attachments/assets/5e2eb98c-17e6-40e9-96a0-e1e8bca0a0e9)


An OOM on VS code shouldn't be causable by the debugger. It would be an issue in VS code. I recommend logging an issue there and including any logging information you can.
