### ISSUE TITLE
Timed out waiting for debugger on first debugpy run

### ISSUE THREAD

**Issue by connor4312** [microsoft/debugpy#1768]
Testing https://github.com/microsoft/vscode-python-debugger/issues/35

This is the first time I used debugpy.

1. Attach to a process
2. After a few moments, there's a prompt from macOS asking something about enabling developer tools. I grant it.
3. In the meantime, the debug connection times out and results in a modal error
4.

**Comment by rchiodo** [comment]
I imagine this is gdb asking for permissions. If it works on second try, then that would be by design. If gdb doesn't let us inject the attach dll, it's not going to work.
