### ISSUE TITLE
Is hot reload now supported when debugging？

### ISSUE THREAD

**Issue by autoDR** [microsoft/debugpy#1778]
When breakpoint is triggered, I modify the file and save it, but no hotreload is triggered.
![20231226211225_rec_](https://github.com/microsoft/debugpy/assets/70084835/4f939672-e757-49ac-8ad4-bb52e8e976fe)

**Comment by rchiodo** [comment]
This is only supported when the runtime you're running actually supports it. Django apps can do this. There may be others, but a default python app cannot.
