### ISSUE TITLE
Query the results of an evaluate with no frameId with a variables request.

### ISSUE THREAD

**Issue by fabioz** [microsoft/debugpy#178]
See: discussion: https://github.com/microsoft/ptvsd/pull/1729#discussion_r318733292

**Comment by fabioz** [comment]
@karthiknadig @int19h 

Can you give me a bit more context on what's the real-world usage for this feature?

i.e.: I started working on it, but I'd like to know if it'd be OK to compromise and actually create a strong reference to the created variable here and clear all such references whenever a thread is run again...

I was initially thinking about re-evaluating the expression to avoid a strong-reference, but there are absolutely no guarantees that evaluating something a 2nd time would actually return the same object, so, it wouldn't work on some corner cases. Also, I don't like the idea of holding references to an object evaluated here forever either and weak-references have too many cases where they wouldn't work, so, I was considering keeping strong references and clearing those whenever the user resumes a thread, but I don't really know the use-case here to know if that'd be OK.

**Comment by karthiknadig** [comment]
This is something that @int19h and @rchiodo (for notebook debugging) were interested in. They are both on vacation, so I would wait until we have some input from them.

**Comment by rchiodo** [comment]
The relevant situation for notebooks (it's not actually notebooks, just func eval for normal python debugging) is this issue here:
https://github.com/microsoft/vscode-jupyter/issues/4065

The TLDR is we need to import some modules such that the import can be used in any frame after the initial import. 

Maybe there's another way to eval our import such that it creates a global variable?

I think this is the essential problem. We're creating ```x``` in this situation:

```python
def bar():
    x = 4
    print(x)

def foo():
    print(x) <-- Failure happens here

bar()
foo()
```

@joyceerhl do you think we could use a 'global' keyword in our import scripts instead?

Essentially do this to fix it
```python
def bar():
    global x
    x = 4
    print(x)

def foo():
    print(x)

bar()
foo()
```

**Comment by joyceerhl** [comment]
@rchiodo I discussed our debugger ask with @fabioz in https://github.com/microsoft/debugpy/issues/598 and implemented the proposed workaround for our scenario in https://github.com/microsoft/vscode-jupyter/pull/5625 Was there another use case that we had? The only one I had has already been resolved.

**Comment by fabioz** [comment]
As a note, this issue is just for being able to return the variable reference to a variables request without the `frameId`, so, it wouldn't really do anything for that particular use-case, which is mostly about scoping of variables.

As @joyceerhl  mentioned, that use-case was solved by using `__import__` (and if that wasn't enough, adding directly to the `builtins` could be a potential alternative, although `__import__` is probably better suited for that particular use-case).

Note that unless we do have a good real-world use-case for this issue, I'd rather not implement it (as there are issues on defining the proper lifetime of the variables that'd be returned here).

**Comment by rchiodo** [comment]
Sounds like we don't need it to me then. I'd be fine with scraping this request.

**Comment by fabioz** [comment]
Ok, I'm going to close this then (we can reopen it later on if there's some real-world case for it).
