### ISSUE TITLE
Assign a special name to the last console output.

### ISSUE THREAD

**Issue by maxslimmer** [microsoft/debugpy#1787]
Feature Request

I would be cool if you could access the last (and maybe second-to-last) values returned from debug console evaluations via a special name (like maybe "_" and "__"), similar to ipython and other interactive REPL.

```
> 2
2

> 1
1

> f"last expression: {_}, second-to-last: {__}"
'last expression: 1, second-to-last: 2'
```

**Comment by rchiodo** [comment]
Thanks for the suggestion. Moving to a discussion item for up votes.
