### ISSUE TITLE
Build native binaries on ci and distribute those.

### ISSUE THREAD

**Issue by fabioz** [microsoft/debugpy#179]
Up until now the binaries were mostly the accelerators (which should be already built on the ci) and some files which changed very little (mostly the attach to pid) which were on git.

Now, with the latest changes on microsoft/ptvsd#509, microsoft/ptvsd#305 and microsoft/ptvsd#1624 those dependencies that changed infrequently will change more and will require more native code, so, I think we should start to organize things differently so that it's possible to do a build without having to commit binary dependencies to git.

We should probably have some structure where we can compile the files on the ci and then upload those dlls somewhere where we can get it later to do the final build (because unlike the usual build where we create several packages for each python version when distributing in the ide we want all those dependencies together -- and each needs to be created on a different OS/python version).

The same structure should also make it possible to have accelerators available for all OSes at once.

Note 1: I just checked and it seems that the accelerators aren't currently distributed in the VSCode/Python plugin (so, final users have a debugger that's much slower than it needs to be) and this issue should also fix that.

Note 2: Both `ptvsd` and `pydevd` should use the same structure to do that (we can probably create a hash from the c/c++ code to create a cache-key which we can use to recover the binary as it'd be the same for both)... I'm not sure where's the best place to keep this info -- maybe a separate git repository only for those binaries where the cache-key (hash) is a folder and the dlls are inside it.

**Comment by Apteryks** [comment]
Hi!

>Another option would be to separate such native bits into their own independent packages, and actually publish those on PyPI.

That's the ideal options from my perpective.  Distributions often want the ability to unbundle libraries and `pydevd` already has its own package which could be used here as a normal dependency, simplifying many things in debugpy (lots of boilerplate to locate and ensure the vendored copy gets loaded).

**Comment by Apteryks** [comment]
I experimented with using an unbundled (properly packaged on my system, with test suite passing) `pydevd` copy here: https://github.com/Apteryks/debugpy/tree/allow-unbundled-builds, without luck so far; here's a test sample output:
```
I+00.299: Realized {..., "type": "response", "command": "initialize", "request_seq": 1, ...}
                == {"seq": 3, "type": "response", "command": "initialize", "request_seq": 1}

D+00.300: Adapter[1] <-- {
              "seq": 2,
              "type": "request",
              "command": "launch",
              "arguments": {
                  "justMyCode": true,
                  "name": "Test",
                  "type": "python",
                  "module": "code_to_debug",
                  "args": [
                      "--arg1",
                      "arg2",
                      "-arg3",
                      "--",
                      "arg4",
                      "-a"
                  ],
                  "console": "internalConsole",
                  "internalConsoleOptions": "neverOpen",
                  "python": "/gnu/store/fby6l226w8kh2mwkzpjpajmgy0q1kxli-python-wrapper-3.9.9/bin/python",
                  "debugOptions": [
                      "ShowReturnValue"
                  ]
              }
          }

I+00.301: Waiting for (
              {..., "type": "event", "event": "initialized", ...} | 
              {..., "type": "response", "command": "launch", "request_seq": 2, ...}
          )

D+15.587: Adapter[1] --> {
              "seq": 4,
              "type": "response",
              "request_seq": 2,
              "success": false,
              "command": "launch",
              "message": "Timed out waiting for debuggee to spawn"
          }

I+15.591: Realized (
              {..., "type": "event", "event": "initialized", ...} | 
              {..., "type": "response", "command": "launch", "request_seq": 2, ...}
          ):
          
             where {..., "type": "response", "command": "launch", "request_seq": 2, ...}
                == {"seq": 4, "type": "response", "command": "launch", "request_seq": 2}

```

**Comment by int19h** [comment]
Part of the problem is that debugpy historically did things with pydevd outside of its public/stable API surface, so treating it as a normal dependency just isn't feasible unless the boundary between the two is firmly stabilized.  Until then, you should consider pydevd as an implementation detail of debugpy.

This particular issue was not about packaging pydevd itself separately, but rather about packaging the native code that is an optional part of pydevd separately.

**Comment by Apteryks** [comment]
Yes, my suggestion was venturing perhaps farther than envisioned here, but it seemed related as if pydevd was a regular dependency the problem would shift to become a pydevd packaging problem rather than a debugpy one.  If I understand correctly, pydevd is used by at least 3 users (PyDev, Visual Studio Code (via debugpy) and PyCharm); it'd make sense if pydevd had a public API.

**Comment by judej** [comment]
this is already done
