### ISSUE TITLE
Any DAP request that causes thread state change should respond immediately

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/debugpy#193]
When ever user does any action like pause, step*, continue, goto, run-to-cusor, etc. These cause thread state change. These should send a response back immediately acknowledging the receipt of the request. They should perform the action after sending the response.

The state of the thread itself is reported via thread events (such as thread, stopped, etc). 

Finally, for any thread whose thread state is changed from stopped to running, and this change was not a direct result of user action. Then it should use the continued event. For example, in a multi threaded scenario, with threads t1, t2, t3, t4. If user issues a step action on t1, and the policy is to continue all other threads. Then t2, t3, t4 should raise continued event. This should only happen if the IDE is **NOT** `visualstudio`. Visual Studio assumes all threads are continued, and sending a continued event breaks things in the IDE.

**Comment by int19h** [comment]
What are the specific cases that remain to be fixed?
