### ISSUE TITLE
End-to end logging support

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/debugpy#198]
We need a way to collect `ptvsd` and `pydevd` logs in one place. Currently ptvsd logs are set via `PTVSD_LOG_DIR=<path>` env-var (or `--log-dir`). `pydevd` logs have to be set via `PYDEVD_DEBUG=True` and `PYDEVD_DEBUG_FILE=<path>`. We need a way so that all these logs are consolidated in one place.

There is separate logging on the extension side as well. Potentially we would want a single place where all the debugger related logging goes to.

**Comment by fabioz** [comment]
@karthiknadig @int19h I think that the current logging structure (which shows logs from debugpy and pydevd) is in good shape now... is there something still missing or can this issue be closed already?
