### ISSUE TITLE
Add type annotations to ptvsd API

### ISSUE THREAD

**Issue by int19h** [microsoft/debugpy#199]
The minbar would be our public APIs such as `enable_attach`, to enable better code completion for them in VSCode and other Python IDEs. 

However, we would also derive some engineering benefits from having them in internal code, as well. So let's add them for all newly written code, at least.

Since we need to support Python 2.7, this has to be either in form of PEP 484 type comments, or via .pyi files.

**Comment by fabioz** [comment]
This is now done (the public API has type annotations now).

**Comment by lev-blit** [comment]
coming back to this - the public API has type annotations but the package doesn't ship a `py.typed` file so type checkers like mypy assume the package is untyped...
