### ISSUE TITLE
Support case sensitive folders on Windows

### ISSUE THREAD

**Issue by c-herff** [microsoft/debugpy#200]
This bug has been reported and apparently been solved before, but since the latest update I'm experiencing the problem, again.

In CamelCased Filenames, the debugger tries to open a new all-lowercase file which does not exist.

## Environment data

- VS Code version:  1.35.1
- Extension version (available under the Extensions sidebar): 2019.5.18875
- OS and version: XXX
- Python version (& distribution if applicable, e.g. Anaconda): Anaconda 3.6.6
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda

## Steps to reproduce:
1. Set Breakpoint in CamelCase file name alignData.py

## Logs
pydev debugger: warning: trying to add breakpoint to file that does not exist: c:\workspace\pilot-data-structure\aligndata.py (will have no effect)

**Comment by fabioz** [comment]
Since it seems we seem to be having more reports due to this, I think we should address this in the short-term.

**Comment by fabioz** [comment]
Note for anyone with this issue: there's a workaround changing the code of the debugger itself so that it doesn't do the case normalization at:

https://github.com/microsoft/debugpy/issues/361#issuecomment-672980974

**Comment by fabioz** [comment]
Note: I'm currently investigating this.

**Comment by fabioz** [comment]
Note: I'm still working on this.

The approach I'm taking is that the internal version we work with (which has the real-normalized filename) should not be used for doing the check, while the parameter passed will be checked in `os.exists` (the only case where it wouldn't work is if the user has 2 files with exactly the same path but with different cases as a breakpoint added would be actually address both files at the same time -- as this should be really rare, this should be ok).

Internally many things were already structured this way, but I'm taking a bit more time to review the existing code and make sure that each path uses what's needed on each place -- i.e.: some places need the absolute normalized version, other places need the canonical version and other places need the original version with the proper case (so, reviewing the code for consistency in that is taking a while -- I hope to finish this next week).
