### ISSUE TITLE
__future__ division not working for the debug console

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/debugpy#210]
@xiaodongzhao commented on [Thu Mar 28 2019](https://github.com/Microsoft/vscode-python/issues/4994)

## Environment data

- VS Code version: 1.32.3
- Extension version (available under the Extensions sidebar): 2019.3.6139
- OS and version: Ubuntu 18.04
- Python version (& distribution if applicable, e.g. Anaconda): Python 2.7.15rc1  
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A  
- Relevant/affected Python packages and their versions: __future__

## Expected behaviour

For file: 
```
#! /usr/bin env python
from __future__ import division
a = 2 / 3
print(a)
```
Set a breakpoint at the last line and run, after pause, in the DEBUG CONSOLE, type *a*, should print 0.6666666666666666
type 2/3, should print 0.6666666666666666

## Actual behaviour

2/3 prints 0
`from __future__ import division` didn't work for the debug console. 

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```

```   

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`; turn on source maps to make any tracebacks be useful by running `Enable source map support for extension debugging`)

```

```

**Comment by fabioz** [comment]
Given that Python 2 is being phased out, I'm not sure it's worth it to pursue this issue to support true division in Python 2 when evaluating in the console/watches (we'd probably need to have some setting to define which is the default evaluation mode to be used and pass it in the launch config or through env variables).
