### ISSUE TITLE
Collapsible stack frames 

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/debugpy#218]
When using Just-my-code, frames for code in stdlib or site-packages should be collapsible. 
See C# VS example:
Collapsed:
![image](https://user-images.githubusercontent.com/3840081/42243677-fa81a23e-7ec6-11e8-825a-afb38d45119f.png)

Expanded:
![image](https://user-images.githubusercontent.com/3840081/42243706-18e133f2-7ec7-11e8-9bfa-82dce47ef4a8.png)

**Comment by int19h** [comment]
No traction on this to date; closing until we decide we actually need it.
