### ISSUE TITLE
Add Qt-related options to `debugpy.configure()`

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/debugpy#219]
Add support for debugging of PyQT apps when using `ptvsd.enable_attach`
See here https://github.com/Microsoft/ptvsd/issues/435#issuecomment-398487058

Solution would be to move `PYDEVD_DEFAULTS` from [__main__](https://github.com/Microsoft/ptvsd/blob/master/ptvsd/__main__.py#L52) into [_local.py](https://github.com/Microsoft/ptvsd/blob/master/ptvsd/_local.py)

This should also fix microsoft/ptvsd#526 (if that's confirmed to be an issue).

**Comment by int19h** [comment]
Actually, do we surface this as a property in launch.json at all?

**Comment by karthiknadig** [comment]
No we don't. Since this was one of those features that we always enabled when start up pydevd. We set pydevd flag to auto-detect and patch.

**Comment by int19h** [comment]
This is implemented.
