### ISSUE TITLE
Investigate native thread detection

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/debugpy#220]
Investigate how we can detect and report threads that were started using mechanisms other than those started from Python.

**Comment by keenox** [comment]
Any updates on the results of this investigation? It's almost the end of 2022 and the only solution is still that workaround with `debug_this_thread()`

**Comment by fabioz** [comment]
@keenox, when the debugger uses the frame eval mode this should work. The only catch is that it's not available for all platforms/architectures (for instance, aarch64 is not supported).

If this is not your case please create a new issue for your particular use-case (along with the logs for the run -- See: https://github.com/microsoft/debugpy/wiki/Enable-debugger-logs for details on how to collect the logs).

**Comment by fabioz** [comment]
On a side-note, when/if CPython implements https://peps.python.org/pep-0669/ tracing could be setup independent of threads (and should work on any platform). 

That will require adaptation on the debugger side once it's available though.

**Comment by fabioz** [comment]
That works for me (see screenshot below), so, I guess you're not using the frame eval mode. Please create a new issue with the logs and information on your System/OS if you want to track it down.

![image](https://user-images.githubusercontent.com/117621/188165754-dfcea523-9077-44e5-925b-77f2e90426e0.png)

**Comment by keenox** [comment]
@fabioz How do I use frame eval mode and what is that?
