### ISSUE TITLE
completion.py stuck in endless loop @ 100% CPU

### ISSUE THREAD

**Issue by patrickkidd** [microsoft/debugpy#233]
## Environment data

- PTVSD version: 2020.4.76186
- OS and version: macOS Catalina 10.15.4
- Python version: 3.7.2 - source build w/ "configure --prefix=$SYSROOT -with-ensurepip=install --with-system-expat"
- Using VS Code or Visual Studio: VS Code

## Actual behavior

completion.py stuck in endless loop @ 100% CPU

## Expected  behavior

completion.py should at least quit at some point (instead of draining the battery), if not using less CPU and then quitting.

## Steps to reproduce:
1. Start up VS Code with python project in above environment. Happens almost every time.

**Comment by int19h** [comment]
There is no completion.py in debugpy, and your repro steps don't mention debugging. Can you clarify if you meant to file a bug about completion in the debug console, or is this about code completion in the editor?

**Comment by patrickkidd** [comment]
Sure enough, I got the projects mixed up. Sorry, it's taking me a while to figure out where all the pieces are for VS Code and the various extensions....
