### ISSUE TITLE
Debug instances are never terminated

### ISSUE THREAD

**Issue by andreamoro** [microsoft/debugpy#234]
## Environment data

-   VS Code version: 1.44
-   OS and version: Mac OS 10.15.4
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.2

## Expected behaviour

Debug sessions to be terminated by the time the process is stop by the user.

## Actual behaviour

Python sessions remains attached, and I arrived to a point where it was impossible to debug the code due to the many instances open.

## Steps to reproduce:

I was playing around with a codebook to complete a series of exercises, and had to start and stop the debugger several time. After (I believe) 30 or 40 sessions I ended up getting the error.

I'm unable at present to report more than the above as I encountered this issue a while ago and I forgot to report this back.
Also this happened on a Mac Book Pro that is now dead, so I cannot recover the job/tasks I was doing.

**Comment by int19h** [comment]
Do you recall the wording of the error message that you were seeing?

**Comment by andreamoro** [comment]
It was something around "too many instances".
But I wouldn't bet on it ATM

**Comment by int19h** [comment]
If it's a Django app, you might be hitting #125. Otherwise, we can't do much here without a repro or logs. I'm going to close it for now - please re-open if you see it again.
