### ISSUE TITLE
"presentationHint" is not set for variable scopes

### ISSUE THREAD

**Issue by int19h** [microsoft/debugpy#236]
DAP `Scope` interface defines `presentationHint` for the purposes of distinguishing standard scope (locals, globals etc). Visual Studio uses this to determine whether the scope is locals or not, to inline locals into the top level. However, pydevd does not set `presentationHint` for any of the scopes - only the label.

**Comment by fabioz** [comment]
Just to confirm: 

From the docs it seems that the values available for `presentationHint` are: `arguments`, `locals` and `registers`.

So, the fix to this issue is just passing `locals` to the `'Locals'` scope or should it also pass `locals` to the `Globals` scope?

**Comment by fabioz** [comment]
(or does VS accept something as `globals` there, even not being in the spec?)

**Comment by int19h** [comment]
Just "Locals". What we want is for that group to be auto-inlined into the parent (i.e. all variables to show as top level) in VS. It might also do this in VSCode - if so, that's fine.
