### ISSUE TITLE
Debug attach times out every time

### ISSUE THREAD

**Issue by deejcunningham** [microsoft/debugpy#241]
## Environment data

-   VS Code version: 1.44.2
-   Extension version (available under the Extensions sidebar): 2020.5.78807
-   OS and version: Arch Linux Kernel 5.6.11
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.2
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Pipenv
-   Relevant/affected Python packages and their versions: N/A
-   Relevant/affected Python-related VS Code extensions and their versions: N/A
-   Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): false
-   Value of the `python.languageServer` setting: Microsoft (default)

## Expected behaviour

- Python script is kicked off by external process - waits for debugger to attach.
- I run the debug attach profile, select the process, and the debugger attaches and allows me to debug.

## Actual behaviour

- Python script is kicked off by external process - waits for debugger to attach.
- I run the debug attach profile, select the process, debugger pops up: "Timed out waiting for debug server to connect."

## Steps to reproduce:

This code is triggered by another semi-complex system (a shell script that calls a python script I believe among a bunch of asynchronous code). It successfully prints the PID and waits for the debugger attach.

```
def __main__():
    if (pysof.get_env('DEBUG')):
        import os
        print(f'PID={os.getpid()}')
        import debugpy
        debugpy.listen(5678)
        print('Waiting for debugger attach')
        debugpy.wait_for_client()
        debugpy.breakpoint()
        print('break on this line')
```

Here is the relevant part of my launch.json:
```
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach",
            "type": "python",
            "request": "attach",
            "processId": "${command:pickProcess}"
        },
```

When I hit run, it asks me to select a process - I select the PID that was printed by the python chunk above. It waits a few seconds, then the timeout message appears.

I need to be able to attach to this process so I can debug.

**Comment by int19h** [comment]
You're trying to use attach-by-PID to attach to a process that is set up for attach-by-socket.

If you want to use `debugpy.listen(5689)`, then you should use `"connect": {"port": 5678}` in your config.

Alternatively, get rid of all the code that mentions debugpy in the app, and then you can use `"processId"`. When you attach by PID, it effectively injects the equivalent of this function into the process, which won't work so well if you're already doing `wait_for_client()`.

**Comment by deejcunningham** [comment]
Thanks a ton! Changing my launch.json to attach-by-socket did the trick. I also tried the alternative you mentioned, so I could just attach by PID, but it still times out even without any debugpy references in the app. Not a problem though as long as I can debug.
