### ISSUE TITLE
When debugging with `integratedTerminal` the terminal switches to `PScore` when default is `cmd`

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/debugpy#245]
![issue9357](https://user-images.githubusercontent.com/3840081/71923477-edc57f00-3141-11ea-91b0-eb879e6727bf.gif)

When debugging with `integratedTerminal` the terminal switches to `PS`. But when user hits the `+` button it uses the `cmd` shell (default is `cmd`). Also, we attempt to activate the environment using `conda activate` after we execute the debugger command (this is a known issue, where there is a race between when we detect a new terminal is created and when VSCode runs the command it receives via `runInTerminal` request.

_Originally posted by @karthiknadig in https://github.com/microsoft/vscode-python/issues/9357#issuecomment-571739526_

**Comment by karthiknadig** [comment]
This might be a bug with VSCode itself. I don't believe we control the shell that gets used.

**Comment by karthiknadig** [comment]
We need to make sure this still occurs before handing off this issue to VSCode.

**Comment by int19h** [comment]
We do not. We don't even control the terminal that gets used - the only thing we set is the terminal title. But I'd expect whatever is selected as the default VSCode shell to be used here.
