### ISSUE TITLE
Question - Remote debugging with Visual Studio Community 2019

### ISSUE THREAD

**Issue by mkashif14** [microsoft/debugpy#249]
I have a question - Can I use debugpy for remote Linux debugging using "Visual Studio Community 2019 (version 16.5.4)"? My local machine (where VS is installed) is Windows 10 and the remote machine is Debian 9.x.

**Comment by int19h** [comment]
@huguesv, can you remind me which version of ptvsd or debugpy shipped with 16.5.4?

**Comment by huguesv** [comment]
That was debugpy 1.0.0b1

**Comment by mkashif14** [comment]
So does that mean I should use debugpy (and NOT ptvsd) for remote debugging with Visual Studio Community 2019 (version 16.5.4)?

**Comment by int19h** [comment]
Yes. It might work with ptvsd, but all bets are off.

**Comment by mkashif14** [comment]
Thanks @int19h for the confirmation. I will close this thread and start a new one with the issues that I'm facing while trying to attach to a remote process using Visual Studio Community and debugpy.
