### ISSUE TITLE
Abort trap 6

### ISSUE THREAD

**Issue by dr-costas** [microsoft/debugpy#252]
## Environment data

- debugpy version: 1.0.0b9
- OS and version: macOS Catalina v. 10.15.4
- Python version (& distribution if applicable, e.g. Anaconda): Anaconda 3.7.3
- Using VS Code or Visual Studio: No

## Actual behavior

When opening a python file and pressing <F9> for entering a breakpoint then: 

Vim crashes with message: 

````bash
Vim: Caught deadly signal ABRT
Vim: Finished.
Abort trap: 6
````
## Expected  behavior

Add a breakpoint

## Steps to reproduce:

Open vim, open a python file, add a breakpoint with <F9>.

**Comment by fabioz** [comment]
@dr-costas this issue doesn't seem related to the `debugpy` as the crash is on Vim itself, so, please report this to the Vim maintainers.
