### ISSUE TITLE
Python Individual Unittest Debugging: Unhandled exception in thread started by 

### ISSUE THREAD

**Issue by JaredVargason** [microsoft/debugpy#253]
## Environment data

-   VS Code version: 1.45.1
-   Extension version (available under the Extensions sidebar): 2020.5.78807
-   OS and version: macOS Catalina 10.15.4
-   Python version (& distribution if applicable, e.g. Anaconda): 3.6.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenv
-   Relevant/affected Python packages and their versions: unittest
-   Value of the `python.languageServer` setting: Microsoft

## Expected behaviour

I should be able to debug an individual unittest in the sidebar. I can still run all tests in the suite.

## Actual behaviour

This behavior worked previously, but is now outputs the message `Unhandled exception in thread started by`. 

I am aware this was an issue in the past: see https://github.com/microsoft/vscode-python/issues/1529.

**Comment by int19h** [comment]
I can't reproduce it on a simple no-op test, so it might have something to do with the specific test that you're running. Can you try to identify the simplest test on which you're seeing this, and also share your launch.json, and any settings.json options that are relevant to testing?

**Comment by int19h** [comment]
Please re-open and add the logs if you are still running into this issue in the most recent version of the Python extension.
