### ISSUE TITLE
vscode-python debugJustMyCode does not stop for modules installed via pip

### ISSUE THREAD

**Issue by Paladiamors** [microsoft/debugpy#256]
## Environment data

-   VS Code version: 1.45.0
-   Extension version (available under the Extensions sidebar): 2020.5.78807
-   OS and version: Ubuntu 20.04-   Python version (& distribution if applicable, e.g. Anaconda): 3.8
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv + pyenv
-   Relevant/affected Python packages and their versions: code related to justMyCode = False
-   Relevant/affected Python-related VS Code extensions and their versions: None
-   Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): True
-   Value of the `python.languageServer` setting: Microsoft

## Expected behaviour

The debugger should stop at a breakpoint outside of my code with justMyCode = False

## Actual behaviour

The debuger skips the breakpoint eg. placed in the `import json` module

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Create the following settings.json:

{
    "python.pythonPath": "/home/justin/Coding/LearnReact/SanicBasics/pybin/bin/python3.8",
    "python.linting.pylintEnabled": false,
    "python.linting.flake8Enabled": true,
    "python.linting.enabled": true,
    "python.linting.flake8Args": [
        "--max-line-length=120"
    ],
    "python.dataScience.debugJustMyCode": false
}

2. Code for testing 

```
import json

json.dumps(str)
```

3. I expect to get the following error:

```Traceback (most recent call last):
  File "/home/justin/Coding/LearnReact/SanicBasics/test_json.py", line 3, in <module>
    json.dumps(str)
  File "/home/justin/.pyenv/versions/3.8.1/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/home/justin/.pyenv/versions/3.8.1/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/justin/.pyenv/versions/3.8.1/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/justin/.pyenv/versions/3.8.1/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type type is not JSON serializable
```

4. I place a break point at line 179 of "/home/justin/.pyenv/versions/3.8.1/lib/python3.8/json/encoder.py", the debugger does not stop there.

## Logs
None, the debugger does not stop at the break point

**Comment by Paladiamors** [comment]
@karthiknadig Hi there, I noticed that this issue has been transferred somewhere. May I know where this is being tracked?

**Comment by karthiknadig** [comment]
> @karthiknadig Hi there, I noticed that this issue has been transferred somewhere. May I know where this is being tracked?

`debugpy` is the underlying debugger, and it handles how stepping occurs. This issues will be triaged here first. It might take a few days before we get to looking into this issue though.

**Comment by Paladiamors** [comment]
Any update to this issue?

**Comment by fabioz** [comment]
@Paladiamors can you provide the logs for the run when that happens?

i.e.:


i.e.:

* Open VS Code
* Select the command Extensions: Open Extensions Folder
* Locate the Python extension directory, typically of the form ms-python.python-2020.*.****
* In that directory ensure you do not have any debug*.log files, if you do, please delete them
* Go back into VS Code and modify your launch.json to add the setting "logToFile": true, see below:

```
"version": "0.2.0",
"configurations": [
    {
        "name": "Python: Current File (Integrated Terminal)",
        "type": "python",
        "request": "launch",
        "program": "${file}",
        "stopOnEntry": true,
        "console": "integratedTerminal",
        "logToFile": true
    },
```

* Start debugging
* When done, go back into the extension directory and upload the debug*.log files into this GitHub issue.

**Comment by Paladiamors** [comment]
I'm currently running from my work PC (Mac) and my home PC is and Ubuntu machine. I've reproduced the error and attached the logs here.

[debugger.vscode_915bf104-35b4-4701-9972-87f133194f77.log](https://github.com/microsoft/debugpy/files/4711950/debugger.vscode_915bf104-35b4-4701-9972-87f133194f77.log)
[debugpy.adapter-65791.log](https://github.com/microsoft/debugpy/files/4711951/debugpy.adapter-65791.log)
[debugpy.launcher-65797.log](https://github.com/microsoft/debugpy/files/4711952/debugpy.launcher-65797.log)
[debugpy.pydevd.65801.log](https://github.com/microsoft/debugpy/files/4711953/debugpy.pydevd.65801.log)
[debugpy.server-65801.log](https://github.com/microsoft/debugpy/files/4711954/debugpy.server-65801.log)

**Comment by Paladiamors** [comment]
Also thanks for looking into this problem @fabioz! I'm a huge fan of your Pydev since it is on Eclipse days and still use it as my main editor. Very cool that I've run into the man here :)

**Comment by int19h** [comment]
`"python.dataScience.debugJustMyCode": false` is not the correct setting - that one is specific to Data Science features (Jupyter notebooks etc). What you want is `"justMyCode": false` in your **launch**.json.

**Comment by Paladiamors** [comment]
I've attached a new set of logs to the message here and see that the `justMyCode` flag is being picked up. However the debugger is not stopping at the breakpoints. Also I used the "Settings UI" to setup this flag in the settings.json file and it is indeed setting up the wrong `debugJustMyCode` setting in the file. 

[debugger.vscode_320d3f87-6329-49bc-90c0-7f89694d8123.log](https://github.com/microsoft/debugpy/files/4714141/debugger.vscode_320d3f87-6329-49bc-90c0-7f89694d8123.log)
[debugpy.adapter-75030.log](https://github.com/microsoft/debugpy/files/4714142/debugpy.adapter-75030.log)
[debugpy.launcher-75035.log](https://github.com/microsoft/debugpy/files/4714144/debugpy.launcher-75035.log)
[debugpy.pydevd.75039.log](https://github.com/microsoft/debugpy/files/4714145/debugpy.pydevd.75039.log)
[debugpy.server-75039.log](https://github.com/microsoft/debugpy/files/4714146/debugpy.server-75039.log)
![Screen Shot 2020-06-02 at 9 43 30](https://user-images.githubusercontent.com/498056/83467878-22055780-a4b6-11ea-8294-6c19751a0083.png)

**Comment by karthiknadig** [comment]
@Paladiamors Looking at the log, were you launch a file using a debug configuration you provided in `launch.json`?
```
157 Client --> Adapter:
{
    "command": "launch",
    "arguments": {
        "name": "Python: Current File (Integrated Terminal)",
        "type": "python",
        "request": "launch",
        "program": "/Users/justin.ho/Coding/Test/test.py",
        "stopOnEntry": true,
        "console": "integratedTerminal",
        "logToFile": true,
        "pythonPath": "/Users/justin.ho/Coding/Test/pybin/bin/python",
        "cwd": "/Users/justin.ho/Coding/Test",
        "envFile": "",
        "env": {
            "PYTHONIOENCODING": "UTF-8",
            "PYTHONUNBUFFERED": "1"
        },
        "showReturnValue": true,
        "internalConsoleOptions": "neverOpen",
        "debugOptions": [
            "StopOnEntry",
            "ShowReturnValue"
        ],
        "justMyCode": true, // <--- THIS IS NOT SET
        "workspaceFolder": "/Users/justin.ho/Coding/Test",
        "__sessionId": "320d3f87-6329-49bc-90c0-7f89694d8123"
    },
    "type": "request",
    "seq": 2
}
```
The `debugJustMyCode` is specific for data science uses. In Data Science case the debugger is started before you can provide any settings. If you are debugging on your own then set the `justMyCode` option in the launch json. You won't find it when you search for settings, because it is a debugger configuration not a setting.

```
{
    "name": "Python: Current File (Integrated Terminal)",
    "type": "python",
    "request": "launch",
    "program": "${file}",
    "console": "integratedTerminal",
    "justMyCode": false, // <---- Set it here
}
```

**Comment by Paladiamors** [comment]
Ok thanks for the information. I've tested the configuration as suggested and the debugger stops at the intended location. I never realized that "justMyCode" is a debugger configuration vs a setting. I'll close this issue with this understanding.
