### ISSUE TITLE
[SSH] Cannot start debugging after choosing "run without debugging" even once during a remote SSH session

### ISSUE THREAD

**Issue by narfanar** [microsoft/debugpy#259]
## Environment data

-   VS Code version: 1.46.0
-   Extension version (available under the Extensions sidebar): 2020.05.80290
-   OS and version: Ubuntu 14.04 LTS (remote); Windows 10 1909 (local)
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7.7
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Conda
-   Relevant/affected Python packages and their versions: XXX
-   Relevant/affected Python-related VS Code extensions and their versions: XXX
-   Jedi or Language Server: Language server
-   Value of the `python.languageServer` setting: Microsoft

## Expected behaviour

You can choose to `Debug` or `Run without debugging` without issue during a session.

## Actual behaviour

Choosing once to `Run without debugging` makes it so `Debug` no longer invokes the debugger for the duration of the remote SSH session.

## Steps to reproduce:

1. Have python code with breakpoints
2. `Start debugging`
3. `Run without debugging`
4. `Start debugging` again. The script should run fine but you don't hit any breakpoints

## Logs

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
> ~/anaconda3/envs/.../bin/python ~/.vscode-server-insiders/extensions/ms-python.python-2020.5.80290/pythonFiles/pyvsc-run-isolated.py mypy --ignore-missing-imports --follow-imports=silent --show-column-numbers ~/data/myscript.py
cwd: ~/data/
##########Linting Output - mypy##########
```

Repeated many times.

</p>
</details>

<br />

<details>

<summary>
Output from <code>Console</code> under the <code>Developer Tools</code> panel (toggle Developer Tools on under <code>Help</code>; turn on source maps to make any tracebacks be useful by running <code>Enable source map support for extension debugging</code>)
</summary>

<p>

```
Nothing new is printed.
```

</p>
</details>

**Comment by karthiknadig** [comment]
@narfanar Can you add `"logToFile": true`  to your launch.json debug configuration? This should capture the logs in `~\.vscode-server\extensions\ms-pyhton.python*` directory on the ssh remote. Please share those logs. There should be multiple log files in that directory.

**Comment by int19h** [comment]
Please re-open and attach the logs if it still happens for you.
