### ISSUE TITLE
Debugger hangs and process left unterminated when forking inside subprocess.run

### ISSUE THREAD

**Issue by Flamefire** [microsoft/debugpy#264]
## Environment data

-   VS Code version: 1.45.1
-   Extension version (available under the Extensions sidebar): 2020.5.80290
-   OS and version: Linux Mint 18
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7.4 
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): pyenv

## Expected behaviour

Spawned process terminate successfully (exit with 0) and debugging continues finally terminating the parent process

## Actual behaviour

When capturing stdout (`stdout=subprocess.PIPE`) the parent process hangs indefintely waiting for the child process. When not capturing stdout the forked child process hangs and is never terminated.

## Steps to reproduce:

This happened in a complex scenario which went like this: Python script starts another python script, which invokes an external tool (compiler via `distutils`)

I reduces this to the following code by checking what is happening:

```
import os
import sys
import subprocess

if len(sys.argv) == 1:
    out = subprocess.run([sys.executable, __file__, '--foo'],
            stdout=subprocess.PIPE
            )
else:
    pid = os.fork()
    print(pid)
```

- Save this and try to debug with the default "Python: Current file" template
1. Observe that the debugger hangs indefinitely
2. Comment out the `stdout=subprocess.PIPE` line and observe that the subprocesses-child-pid (return value of fork) is printed but the child never runs (which should print a zero) and although debugging will end in this case the child process is never terminated (check `ps -aux | grep python`)

Note that usually the parent process of the `fork` waits for the child which means that again the debugged process never returns/continues.

**Comment by fabioz** [comment]
I'll start to investigate this.

**Comment by fabioz** [comment]
I wasn't able to investigate this properly last time, so, I'll start tackling this again.

**Comment by fabioz** [comment]
Attaching the logs related to this:

[debugpy.launcher-17933.log](https://github.com/microsoft/debugpy/files/5386824/debugpy.launcher-17933.log)
[debugpy.adapter-17923.log](https://github.com/microsoft/debugpy/files/5386825/debugpy.adapter-17923.log)
[debugger.vscode_58e35c81-7446-4f43-8ebd-cc1295ce3679.log](https://github.com/microsoft/debugpy/files/5386826/debugger.vscode_58e35c81-7446-4f43-8ebd-cc1295ce3679.log)
[debugpy.pydevd.17965.log](https://github.com/microsoft/debugpy/files/5386827/debugpy.pydevd.17965.log)
[debugpy.pydevd.17954.log](https://github.com/microsoft/debugpy/files/5386828/debugpy.pydevd.17954.log)
[debugger.vscode_38d004d4-a0c9-4218-86af-fb0f3de1888f.log](https://github.com/microsoft/debugpy/files/5386829/debugger.vscode_38d004d4-a0c9-4218-86af-fb0f3de1888f.log)
[debugpy.server-17939.log](https://github.com/microsoft/debugpy/files/5386830/debugpy.server-17939.log)
[debugpy.pydevd.17939.log](https://github.com/microsoft/debugpy/files/5386831/debugpy.pydevd.17939.log)

The logs on the pydevd side seem to show that a connection was done, but the initialize event isn't really sent after that (I also tested in plain pydevd and it seems to work properly there, so, it's probably something related to the connection management on the debugpy/vscode side).

**Comment by fabioz** [comment]
Actually, the problem was on the pydevd side. It wasn't properly keeping the protocol after a fork after a subprocess.

This happened because debugpy set the default protocol in memory, but that in-memory default was lost if it first created a subprocess and then a fork after that subprocess and the logging doesn't really show which protocol it was using (the message just didn't arrive in the other side because there was no new-line sent) -- took me a while to actually find this one (and as all hard to debug things it's a really small fix: https://github.com/microsoft/debugpy/pull/438/files#diff-942a2e05c676f6fb0f7a70883d2f885bcb47c1af4feb1a3a48f57fd77c17d5b5R685).
