### ISSUE TITLE
Unable to attach debugger to a process using pid

### ISSUE THREAD

**Issue by hashirsarwar** [microsoft/debugpy#265]
## Environment data

- debugpy version: 1.0.0b9
- OS and version: Windows 10 (WSL2)
- Python version: 3.6.9
- Using VS Code

## Actual behavior

I am debugging a web server that runs different python scripts for specific processing jobs. I use the script below to attach the debugger:
```
import debugpy
debugpy.listen(5678)
debugpy.wait_for_client()
```
The debugger is attached to that process successfully. But then, several subprocesses are generated by the script and I attempt to connect all the processes using their PIDs to the same port i.e. 5678. I use the command for that as follows:
```python3 -m debugpy --connect localhost:5678 --pid {process.pid}```
This command fails and the log prints the error:
```
Traceback (most recent call last):
  File "/srv/zulip-py3-venv/lib/python3.6/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 330, in _on_run
    self.process_net_command_json(self.py_db, json_contents)
  File "/srv/zulip-py3-venv/lib/python3.6/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command_json.py", line 167, in process_net_command_json
    assert request.type == 'request'
AssertionError
```
## Expected  behavior
The command should attach the process to the debugger and I should be able to set breakpoints and stop the execution for all the processes.

**Comment by karthiknadig** [comment]
@hashirsarwar You should not have to attach to the sub-processes that get started. I highly recommend starting your we server under the debugger itself instead of `import debugpy`. That way the debugger can manage the sub-processes better.

```
python -m debugpy --listen 5678 --wait-for-client <your web server CLI>
```
This approach will give you the best experience. Let me know if you can't apply this approach.

**Comment by hashirsarwar** [comment]
@karthiknadig thanks for the reply. Unfortunately, that didn't work as well. I ran the command:
```
python3 -m debugpy --listen 5678 --wait-for-client tools/run-dev.py
```
and it stops the execution if I set the breakpoint at the `run-dev.py` itself. But for the subprocesses that `run-dev` creates, the debugger ignores the breakpoints.

Here is my launch.json file:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Remote Attach",
            "type": "python",
            "request": "attach",
            "port": 5678,
            "host": "localhost",
            "subProcess": true,
            "pathMappings": [
                {
                    "localRoot": "${workspaceFolder}",
                    "remoteRoot": "."
                }
            ]
        }
    ]
}
```

**Comment by hashirsarwar** [comment]
Here is some extra information that might be useful:
* I am running the insiders versions of Python extension in VS Code. `2020.6.81425-dev` to be specific.
* The extension is enabled on WSL: Ubuntu-18.04.
* If you want the check the the `run-dev.py` script, here's the [link](https://github.com/zulip/zulip/blob/master/tools/run-dev.py) and [this](https://github.com/zulip/zulip/blob/master/tools/run-dev.py#L378) is how the multiple subprocesses are being generated in the script.

**Comment by karthiknadig** [comment]
@hashirsarwar When you launch the command line add `--log-dir <path to existing dir>` to collect logs from the debugger. The issue is likely path mappings are not working as expected. This usually happens when the working directory on the remote is different from what the extension expects it to be.

**Comment by int19h** [comment]
When you're forming the command line for your processes, the binary name is another Python script. Are you relying on that script having the +x bit, and `#!/usr/bin/env python` shebang? I don't think that's a pattern that we detect - try using `sys.executable` instead, and passing the script name as an argument.

**Comment by hashirsarwar** [comment]
> The issue is likely path mappings are not working as expected.

@karthiknadig it doesn't look like a path mapping issue.

The following information from `debugpy.adapter-3777.log` might be helpful because actions.py is executed from a subprocess.
```
D+00009.286: /handling #12 event "process" from Server[1]/
             Propagation deferred.

D+00009.286: /handling #16 event "thread" from Server[1]/
             Propagation deferred.

D+00009.302: Client[1] --> {
                 "seq": 3,
                 "type": "request",
                 "command": "setBreakpoints",
                 "arguments": {
                     "source": {
                         "name": "actions.py",
                         "path": "/home/hashir/zulip/zerver/lib/actions.py"
                     },
                     "lines": [
                         1296
                     ],
                     "breakpoints": [
                         {
                             "line": 1296
                         }
                     ],
                     "sourceModified": false
                 }
             }

D+00009.303: /handling #3 request "setBreakpoints" from Client[1]/
             Server[1] <-- {
                 "seq": 8,
                 "type": "request",
                 "command": "setBreakpoints",
                 "arguments": {
                     "source": {
                         "name": "actions.py",
                         "path": "/home/hashir/zulip/zerver/lib/actions.py"
                     },
                     "lines": [
                         1296
                     ],
                     "breakpoints": [
                         {
                             "line": 1296
                         }
                     ],
                     "sourceModified": false
                 }
             }
```

**Comment by hashirsarwar** [comment]
> I don't think that's a pattern that we detect - try using sys.executable instead, and passing the script name as an argument.

@int19h I ran `run-dev.py` as `./tools/run-dev.py` and `python3 tools/run-dev.py` and it looks like the debugger detects both the patterns. Did you mean something else?

**Comment by int19h** [comment]
@hashirsarwar I mean the code that I linked to above. The command line that it generates for subprocesses has `./manage.py` as the first entry in the list that it passes to `subprocess.Popen()` - try inserting `sys.executable` there.

**Comment by hashirsarwar** [comment]
Replacing `./` with the sys.executable solved the issue. Huge thanks @karthiknadig @int19h! 🙂
