### ISSUE TITLE
Cannot install on Jetson Tegra

### ISSUE THREAD

**Issue by lfdmn** [microsoft/debugpy#270]
## Environment data

- debugpy version: 1.0.0b9 
- OS and version: poky 3.0 (Yocto warrior) - so Linux
- Python version: Python 3.7.6
- Using VS Code

## Actual behavior

Cannot deploy python-debugpy.

## Expected  behavior

Deploy python-debugpy on arm, arm64, aarch64, etc Linux distro

## Steps to reproduce:
1. add the following recipe 

python3-debugpy_1.0.0b9.bb
```
SUMMARY = "An implementation of the Debug Adapter Protocol for Python"
DESCRIPTION = "debugpy is an implementation of the Debug Adapter Protocol for Python."
HOMEPAGE = "https://aka.ms/debugpy"

LICENSE = "EPL-2.0"
LIC_FILES_CHKSUM = "file://PKG-INFO;beginline=24;endline=24;md5=3b201838177122a902b64d8ee1e9e499"

SRC_URI[md5sum] = "8ab53428ac94fa0fa65e2406451189d7"
SRC_URI[sha256sum] = "d57e4854c78d007d9516b8d3ae0c827cd6df87374d6d56d9c4fbc7adfa83546b"

RDEPENDS_${PN} += "python3-core"
PYPI_PACKAGE = "debugpy"
PYPI_PACKAGE_EXT = "zip"

inherit pypi setuptools3 ptest
```
2. try to build the package
```
bitbake python3-debugpy
```

3. Here the error
```
ERROR: python3-debugpy-1.0.0b9-r0 do_package: Fatal errors occurred in subprocesses:
Command '['aarch64-poky-linux-objcopy', '--only-keep-debug', '/yocto-warrior/build-jetson-xavier/tmp/work/aarch64-poky-linux/python3-debugpy/1.0.0b9-r0/package/usr/lib/python3.7/site-packages/debugpy/_vendored/pydevd/pydevd_attach_to_process/attach_linux_x86.so', '/yocto-warrior/build-jetson-xavier/tmp/work/aarch64-poky-linux/python3-debugpy/1.0.0b9-r0/package/usr/lib/python3.7/site-packages/debugpy/_vendored/pydevd/pydevd_attach_to_process/.debug/attach_linux_x86.so']' returned non-zero exit status 1.
Subprocess output:aarch64-poky-linux-objcopy: Unable to recognise the format of the input file `/yocto-warrior/build-jetson-xavier/tmp/work/aarch64-poky-linux/python3-debugpy/1.0.0b9-r0/package/usr/lib/python3.7/site-packages/debugpy/_vendored/pydevd/pydevd_attach_to_process/attach_linux_x86.so'
Command '['aarch64-poky-linux-objcopy', '--only-keep-debug', '/yocto-warrior/build-jetson-xavier/tmp/work/aarch64-poky-linux/python3-debugpy/1.0.0b9-r0/package/usr/lib/python3.7/site-packages/debugpy/_vendored/pydevd/pydevd_attach_to_process/attach_linux_amd64.so', '/yocto-warrior/build-jetson-xavier/tmp/work/aarch64-poky-linux/python3-debugpy/1.0.0b9-r0/package/usr/lib/python3.7/site-packages/debugpy/_vendored/pydevd/pydevd_attach_to_process/.debug/attach_linux_amd64.so']' returned non-zero exit status 1.
Subprocess output:aarch64-poky-linux-objcopy: Unable to recognise the format of the input file `/yocto-warrior/build-jetson-xavier/tmp/work/aarch64-poky-linux/python3-debugpy/1.0.0b9-r0/package/usr/lib/python3.7/site-packages/debugpy/_vendored/pydevd/pydevd_attach_to_process/attach_linux_amd64.so'
```

The issue being here that the package distributes pre-built shared objects:
* attach_linux_amd64.so
* attach_linux_x86.so

The sources should be bundled and built during the installation. That is if this attach library is opensource.

**Comment by karthiknadig** [comment]
@lfdmn The source is bundled here: https://github.com/microsoft/debugpy/tree/master/src/debugpy/_vendored/pydevd/pydevd_attach_to_process/linux_and_mac

We have to ship prebuilt version of this to support container scenarios as used by the docker extension and Azure app services. They volume map the debugger from say windows host into a linux container.

You should be able to download source only version via pypi, delete the *.so, and run compile_linux.sh to get this built, then use pip do install from a folder location as source.

**Comment by lfdmn** [comment]
Thanks @karthiknadig 

I managed to build and install in my image.

For reference for other yocto users
```bash
SUMMARY = "An implementation of the Debug Adapter Protocol for Python"
DESCRIPTION = "debugpy is an implementation of the Debug Adapter Protocol for Python."
HOMEPAGE = "https://aka.ms/debugpy"

LICENSE = "EPL-2.0"
LIC_FILES_CHKSUM = "file://PKG-INFO;beginline=24;endline=24;md5=3b201838177122a902b64d8ee1e9e499"

SRC_URI[md5sum] = "8ab53428ac94fa0fa65e2406451189d7"
SRC_URI[sha256sum] = "d57e4854c78d007d9516b8d3ae0c827cd6df87374d6d56d9c4fbc7adfa83546b"

RDEPENDS_${PN} += "python3-core"
PYPI_PACKAGE = "debugpy"
PYPI_PACKAGE_EXT = "zip"

inherit pypi setuptools3 ptest

TARGET_CC_ARCH += "${LDFLAGS}"

RDEPENDS_${PN} += " \
    ldd \
" 

do_configure(){
    # Remove 32bit shared library of packaging will fail
    cd ${WORKDIR}/debugpy-1.0.0b9/src/debugpy/_vendored/pydevd/pydevd_attach_to_process/
    rm -f attach_linux_*.so
}

do_compile_append() {
    cd ${WORKDIR}/debugpy-1.0.0b9/src/debugpy/_vendored/pydevd/pydevd_attach_to_process/linux_and_mac
    ${CXX} -shared -o attach_linux_amd64.so -fPIC -nostartfiles attach.cpp
    mv attach_linux_amd64.so ../attach_linux_amd64.so
}
```

I'm not able to start a process for debugging though. The vscode asks in a loop for the interpreter in the remote device. Could it be due to this extension?

**Comment by int19h** [comment]
I see you've filed a separate bug about interpreter not getting selected (https://github.com/microsoft/vscode-python/issues/12084) - and yes, that one is an issue in the extension proper. I'm going to close this one, since the original issue is resolved.

**Comment by RobertSwirsky** [comment]
I don't think this should be closed. I just ran into the same thing trying to put debugpy into a buildroot build for an arm board.

> _We have to ship prebuilt version of this to support container scenarios as used by the docker extension and Azure app services. They volume map the debugger from say windows host into a linux container._

When the system checks architectures before assembling the binaries, it fails on these:

![image](https://user-images.githubusercontent.com/13056860/110014522-bca9f580-7cd7-11eb-9363-b2e2efbbef3b.png)

the "pure source" tar file on PyPi shouldn't have these.

**Comment by int19h** [comment]
The binaries in question are loaded dynamically as needed on supported architectures (of which ARM currently isn't one), and are inert on others. They're not part of the package proper. The build process in question should be treating them as resources, basically, not as binaries.
