### ISSUE TITLE
Debugging Python tests don't start anymore

### ISSUE THREAD

**Issue by evowilliamson** [microsoft/debugpy#272]
## Environment data

-   VS Code version: 1.45.1
-   Extension version (available under the Extensions sidebar): XXX
-   OS and version: Ubuntu 19.10
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Relevant/affected Python packages and their versions: Not relevant
-   Relevant/affected Python-related VS Code extensions and their versions: Python extension
-   Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): XXX
-   Value of the `python.languageServer` setting: 0.5.50.0

## Expected behaviour

Clicking the lense "Debug Test" should launch the debug session

## Actual behaviour

The launch doesn't happen

## Steps to reproduce:

1. Start the virtual env
2. Start code
3. Discover the tests
4. Debug one tests -> The debug session doesn't launch

After discovering the tests, any test in any project have stopped working. I remember just before there was a message regarding **runpy** in the right lower corner, saying that it couldn't run and asked me to try with sudo. I clicked "yes". After this action, no tests can be debugged when I click the "Debug Test" lense, nothing happens. This happens to any project I open. I tried reinstalling Visual Code and also reinstalling the Python extension, but no change.

```
I have the following standard config:
        {
            "name": "Debug Tests",
            "type": "python",
            "request": "test",
            "console": "integratedTerminal",
            "justMyCode": false
        }    ]

```

## Logs

I inspected the developer tools section and it throws the following error when I start a debug session through the lense or through a

```
console.ts:137 [Extension Host] (node:10318) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
3
log.ts:197   ERR timeout after 1000 ms: Error: timeout after 1000 ms
    at t.RawDebugSession.handleErrorResponse (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3061:355)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3060:679
    at async t.RawDebugSession.shutdown (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3058:772)

```

Output of the terminal console:

Pyright language server 1.1.40 starting
Server root directory: /home/ivo/.vscode/extensions/ms-pyright.pyright-1.1.40
Starting service instance "python-algorithms"
Received updated settings
No configuration file found.
Setting pythonPath for service "python-algorithms": "/home/ivo/projects/python-algorithms/venv/bin/python"
stubPath /home/ivo/projects/python-algorithms/typings is not a valid directory.
Searching for source files
Auto-excluding /home/ivo/projects/python-algorithms/venv
Found 24 source files
Background analysis root directory: /home/ivo/.vscode/extensions/ms-pyright.pyright-1.1.40
Background analysis started

**Comment by int19h** [comment]
The error message is from a file in the Python standard library, and it is not supposed to have any backquotes in it, so it looks like a damaged Python installation. Can you try reinstalling it? Since it's in /usr/lib, this probably means `apt reinstall python3`.

**Comment by evowilliamson** [comment]
@int19h ,

You are correct. The Python installation was corrupted. Thanks for the swift reaction.
