### ISSUE TITLE
When ungrouped, list and dict variables have inconvenient sort order

### ISSUE THREAD

**Issue by huguesv** [microsoft/debugpy#278]
## Environment data

- debugpy version: 1.0.0 beta 10
- OS and version: windows
- Python version (& distribution if applicable, e.g. Anaconda): 3.7
- Using VS Code or Visual Studio: Visual Studio

## Actual behavior

![image](https://user-images.githubusercontent.com/1696845/83931534-1d5ccf80-a752-11ea-9556-53f77caeb932.png)

![image](https://user-images.githubusercontent.com/1696845/83931541-251c7400-a752-11ea-868c-bee82280dc59.png)

## Expected  behavior

The actual list items should be at the top instead of the bottom, to avoid the need to scroll all the way down to see them.

## Steps to reproduce:
1. Declare a list or dict with a few values in them
2. Expand at the variable in the debugger

**Comment by V1NAY8** [comment]
Hi, @int19h I am thinking of contributing to this issue.
Here's my understanding:
- I declared two variables `a` and `x` to replicate this. Here's how it comes in VSCode
- Does this mean that the values of list and dict should be in top,  `special variables` and `function variables` should be at bottom?
![image](https://user-images.githubusercontent.com/33659563/99139799-ed4f1c00-2661-11eb-9757-e352dea0de67.png)

**Comment by int19h** [comment]
This issue is specifically about how the items look when they're *not* grouped - which is the case in Visual Studio by default (but not in Visual Studio Code).

**Comment by V1NAY8** [comment]
Yes :) I'm just trying to figure out the repository. Can you please give me some inputs on where to make changes? 😃

**Comment by AdamYoblick** [comment]
This is no longer an issue. Variable grouping has been the default behavior in VS for some time now, identical to vs code. Here's an example of this working on Visual Studio 17.7.7:

![image](https://github.com/microsoft/debugpy/assets/29436557/b680101f-d375-43bc-99f7-5e2d798b0a37)

You can change how variables are grouped from the debugger by going to Tools -> Options -> Python -> Debugging:

![image](https://github.com/microsoft/debugpy/assets/29436557/9520acd5-5764-458c-ace6-33365a57ea70)

**Comment by int19h** [comment]
The issue isn't that the variables are ungrouped. It's that list & dict list child attributes first, and only then list their items. So when grouping is disabled, you see all the methods first, and only then the items. Since usually users want to see the items when expanding a collection, the items should arguably be first.

However for large collections changing it to work that way would mean that you can't easily get to other things when you need to, sometimes. So I think it's best to keep this as is after all.
