### ISSUE TITLE
Python can't use the curses library

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/debugpy#283]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1063969/python无法使用curses库.html)._

---
You can run without vs 2019 with PowerShell.
And with vs 2019, it's a hint:
LINES value must must be s 2 and s 470: got 22353
initscr (): Unable to create SP
With curses-2.2.1 plus utf8-cp37-cp37m-win_amd64.whl this version of curses

---
#### Visual Studio Feedback System on 6/4/2020, 10:49 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### 409261315 on 6/4/2020, 10:52 AM: 

ok

---
### Original Solutions
(no solutions)

**Comment by int19h** [comment]
Is this with `"redirectOutput": true`, by chance?

**Comment by huguesv** [comment]
Good point, yes it is.

So for the user that reported this on developer community: you can disable redirect output by unchecking this option in Tools/Options/Python/Debugging:
![image](https://user-images.githubusercontent.com/1696845/84202266-15a47000-aa5d-11ea-92bc-7d3bb5fd4eda.png)

**Comment by int19h** [comment]
When redirected, there's no console to speak of, so it's expected for curses-based stuff to not work. The library itself could report the error more clearly, but it's a fairly old one, and I'm not sure if it's even still updated.

From the perspective of a Python app that uses curses, and wants to fall back to something else (e.g. non-interactive mode) when it's redirected, it should check `sys.stdout.isatty()` and/or `sys.stderr.isatty()`, depending on which ones of those it is writing to. Note that these can be redirected separately, so it cannot assume the same result for both.

**Comment by Brambor** [comment]
I have the same problem, in cmd I launch python and write:

```
>>> import curses
>>> curses.initscr()
LINES value must be >= 2 and <= 63: got 1
initscr(): Unable to create SP
```
which drops me from python. This is a problem, I would like to write "Your window is too small" by print, but I cannot try/except it!

```
>>> import curses
>>> try:
...     curses.initscr()
... except Exception as e:
...     print("wut?")
...     raise e
```
Does the same, prints the LINES... and exits Python.

Please help!

**Comment by int19h** [comment]
It doesn't sound like a debugger issue though?

**Comment by Brambor** [comment]
No, sorry I got there by Google search...

**Comment by An-S** [comment]
I understand that the debugger console window is designed for output of one line after another. I also understand that it is difficult to redirect curses output to the debugger window. Most developers can probably live with it that complex screen layouts are not redirected to the debugger window (why on earth should somebody want frames and widgets in a debugger window?) 

However, i also understand the critics that one expects that the debugger window backend bypasses the ncurses interface and that all the stdout stuff (in contrast to the ncurses stdscr) will still be forwarded to the debugger window.
