### ISSUE TITLE
Trouble with debugger using pyserial

### ISSUE THREAD

**Issue by GreenToxicPain** [microsoft/debugpy#285]
## Environment data

-   VS Code version: 1.45.1 (user setup)
-   Extension version (available under the Extensions sidebar): 2020.5.86398
-   OS and version: Windows 10 Pro
-   Python version (& distribution if applicable, e.g. Anaconda): python 3.7.4
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualvenv/no virtual environment
-   Relevant/affected Python packages and their versions: pyserial==3.4 (error occurs with any version > 3.)
-   Relevant/affected Python-related VS Code extensions and their versions: XXX
-   Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): XXX
-   Value of the `python.languageServer` setting: XXX

## Expected behaviour

Script with pyserial should run with no mistakes as in no-debug mode.
Also such script ran without any mistakes before last update of python extension

## Actual behaviour

An error during opening serial port occurs:
Cannot configure port, something went wrong. Original message: OSError(22, 'The parameter is incorrect.', None, 87)

## Steps to reproduce:

1. Run script with code

import serial
serial.Serial(port = 'COM5')  # or some other serial port name

I don't know if it is important, as a device I use stm32 (but it works without debugging)

**Comment by fabioz** [comment]
This is a bit odd... in this particular case it seems like the exception is actually being thrown and seems to get to user code (the top of the stack is `h:\Job\Board\git\python_test\some_test.py, <module>, 2` in the logs, which would make it correct to handle it as user code).

@GreenToxicPain if you run that code without any debugging, do you have an exception on the console?

**Comment by GreenToxicPain** [comment]
> This is a bit odd... in this particular case it seems like the exception is actually being thrown and seems to get to user code (the top of the stack is `h:\Job\Board\git\python_test\some_test.py, <module>, 2` in the logs, which would make it correct to handle it as user code).
> 
> @GreenToxicPain if you run that code without any debugging, do you have an exception on the console?

No, I don't

**Comment by fabioz** [comment]
@GreenToxicPain, can you run the code below (in the regular case) and provide the output?

```
import serial

def main():
    serial.Serial(port = 'COM5')

import trace
tracer = trace.Trace(trace=1, count=0)
tracer.run('main()')
```

p.s.: I wanted to reproduce it locally but I don't really have any ports that will work with pyserial on my machine to test and it worked on a socket port, so, if you can run and get the debug info needed there it'd be quite helpful.

**Comment by fabioz** [comment]
Closing due to lack of feedback.
