### ISSUE TITLE
Support "step into targets" in VS Code

### ISSUE THREAD

**Issue by luabud** [microsoft/debugpy#288]
From VS Code's 1.46 update:
https://code.visualstudio.com/updates/v1_46#_step-into-targets

### _Step Into Targets_
_Debugging into a statement with many nested function calls can be painful because you might have to step through functions you are not really interested in. To improve this scenario, the Debug Adapter Protocol has supported the "Step Into Target" feature that displays UI for directly stepping into the function you are interested in._

_In this milestone, VS Code has started to use this feature. When debugging has stopped on a statement, the context menu shows a new action Step Into Targets. This action presents a list of all targets (typically functions) that are available at the current stack frame. Selecting one of them will step into that target._

_Note that every stack frame can have its own set of targets. So the result of the Step Into Targets actions depends on the currently selected frame in the CALL STACK view._

Is that something we can add support to? 😊

**Comment by fabioz** [comment]
> Is that something we can add support to? 😊

Yes... seems a nice feature, I'll take a look at that after the issue I'm working on .

**Comment by int19h** [comment]
Let's think what can be done before going for implementation. I suspect that this would be a very big item, since there's no API in Python to get a list like that - it'd need to parse bytecode, and I'm not sure we can map that back to the specific bits of the original line of code to present a readable list of calls to the user.

**Comment by fabioz** [comment]
Sure... I'll do some investigation first before coding it.

**Comment by fabioz** [comment]
I did some investigation and to parse the bytecode it's really more work to do, so, I was thinking about using the ast module here... The shortcoming from using it is that it won't work in cases where the source code is not available, but I think that for this particular feature this would be a reasonable compromise.

@int19h @karthiknadig do you think it's ok going forward with this approach? I think that it'd take around 5 days to implement.

**Comment by int19h** [comment]
Bugs are higher priority at the moment. This one is more of a nice to have.

**Comment by fabioz** [comment]
Note: I'm currently working on this.

**Comment by fabioz** [comment]
Related issue in vscode-python: https://github.com/microsoft/vscode-python/issues/13719

**Comment by fabioz** [comment]
Note: my plan is to provide a pull request for this next week.
