### ISSUE TITLE
VSC or debugpy not reseting python instance

### ISSUE THREAD

**Issue by ManPython** [microsoft/debugpy#292]
## Environment data

- debugpy version: 1.0.0b11

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 6.1.7601
Steps to repair:

## Actual behavior
1. When django is working in debug mode and reseting "session" by refresh icon, then VSC stoping debug not reseting and the python process working. In this case when runing again debug we have next python.exe process and we don't know what we debuging and what working coretly or not.
2. In case of reset and tunr again the debug console is empty, not loging changes in get actions by browser

## Expected  behavior
1. Reset should reset python session or run again

## Steps to reproduce:
1. I using maing config sugestion:
https://github.com/microsoft/ptvsd
```            "debugOptions": [
                "RedirectOutput",       // Whether to redirect stdout and stderr (see pydevd_comm.CMD_REDIRECT_OUTPUT)
                "WaitOnNormalExit",     // Wait for user input after user code exits normally
                "WaitOnAbnormalExit",   // Wait for user input after user code exits with error
                "Django",               // Enables Django Template debugging
                "Jinja",                // Enables Jinja (Flask) Template debugging
                "FixFilePathCase",      // See FIX_FILE_PATH_CASE in wrapper.py
                "DebugStdLib",          // Whether to enable debugging of standard library functions
                "StopOnEntry",          // Whether to stop at first line of user code
                "ShowReturnValue",      // Show return values of functions
            ]
```
2. Must modify to delete:
                ```"WaitOnNormalExit",     // Wait for user input after user code exits normally
                "WaitOnAbnormalExit",   // Wait for user input after user code exits with error```


![django_problems](https://user-images.githubusercontent.com/25403861/84567931-58778800-ad7c-11ea-87ae-0c3c1f3b2a54.png)
3. Time ago was sure about:
"Djangodebug",      - this or as in down?
"Django",               // Enables Django Template debugging

I'm sure that I not clicked "Disconect" or something. It's happeing when django meet some bug and need reset in case app not refreshing if save changes in code.
Due to many configs in VSC, ptvsd and debugpy.. and back to usage VSC with this.. possible that I omitted some important setting maybe?

**Comment by ManPython** [comment]
What I meet.. 
1. If no any process of python.exe in list W7, and start debug then in default I have 4 instance of python.exe
2. When disconect, then still have logs in debug console. Soo.. this is logical bug in logic of debug management proces.
3. Stop made that that logs are not colected but Django app working (1 instance python.exe). 
4. Coz we thinkig that process was closed and disconected we starting debug again in case 1 instance python.exe working with the app.

How this should be repaired in my opinion.
The `STOP` btn should stop debug and session.
The `Disconect` is not needed I think coz `Pause` can do this.

I'm really not sure about role of `Disconect`. If idea was to start app on some producion and leave runed by close VSC then it was but idea. If was some way to manage multiple projects then work need usage of ned instance of VSC as new window.

**Comment by ManPython** [comment]
```
Watching for file changes with StatReloader
Performing system checks...

System check identified some issues:

WARNINGS:
?: (urls.W005) URL namespace 'admin' isn't unique. You may not be able to reverse all URLs in this namespace

System check identified 1 issue (0 silenced).
June 13, 2020 - 14:20:36
Django version 2.2.6, using settings '_app.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
```
When `STOP` then console should be cleared or need option for this type.
In case we don't have timelog of some events then we don't know what was las as actual
https://github.com/microsoft/vscode/issues/83129
Thats why need some `event datetime`
https://github.com/microsoft/vscode/issues/99850

**Comment by ManPython** [comment]
And something else.. 
If we made changes in code thats mind Django restarting, but in this phase `Restart` should be blocked (eg. not clicable or in other colour - orange [wait]) to prevent this in case restart need time (the run by VSC is slower than CMD)
https://github.com/microsoft/ptvsd/issues/1879

**Comment by int19h** [comment]
"Disconnect" just means disconnecting the debugger from the current active process. 

Neither debugpy nor the Python extension control the behavior of "Restart", and we don't know if and when Django decides to restart the child process for auto-reload. In any case, "Restart" in VSCode has nothing to do with Django itself - it's a command that's applicable to any process, and is thus present in any debug session, regardless of what is being debugged, and whether the debuggee itself starts and stops processes.

The behavior of "Restart" is somewhat confusing, unfortunately - it applies to the current active *process* (selected in the Call Stack window), not the entire multiprocess session, and basically restarts the subsession for that process using the same debug config that was used to start it. In case of Django running with auto-reloader, this will usually be the child process running your code, because that's where breakpoints etc occur. Doing "Restart" on that should just detach and re-attach to it.

If you do "Restart" after selecting the parent process, then it will stop that process and start a new one. 

Can you please clarify which scenario this is? A self-contained repro would be ideal to make sure that we don't miss anything wrt settings etc. I couldn't repro it regardless of `--noreload` being used or not used.

**Comment by ManPython** [comment]
About scenario, You mind with " --noreload" or without? It was without, I not using  --noreload . 
Like on image.
```
            "args": ["runserver", "127.0.0.1:8000", "--traceback", "--force-color"],
            "django": true,
            "subProcess": true,
            "justMyCode":  false,
            "env": {
            },
```
In the fact of the "debuging" it's misunderstanding maybe - coz it's more start app from VSC like debug on my side. Why? Coz if django meet some problems then VSC not reacting for this case like pure Python app, eg with QT (I have vary advanced apps) - not moving to the part of code where is bug and not doing highlighs (red layer), etc. just log in internal console. Due to this I back to usage CMD coz facts are that runing app by VSC working long thime, reload this same, on some long time with working with VCS and many tabs of code whole IDE looks overloading memory or something, that made system working hard. The one sense of usage of VSC with django in this case is good IDE editor, exts, tools, like git where I can fast manage code and repo.
Soo.. I'm not sure about VSC and this all with Django. I'ts ok with pure python apps, but with ` "django": true,` in whole django is like difrent method of usage VSC and debuging process. 
**I omitted something here ot it's normal as early stage cooperation with Django?**

**Comment by int19h** [comment]
Does this issue still occur with the most recent version of debugpy?

**Comment by judej** [comment]
Closing stale issue. Please reopen if needed
