### ISSUE TITLE
Debugger evaluation cancellation option

### ISSUE THREAD

**Issue by syagev** [microsoft/debugpy#294]
Python @ VSCode rocks.

When the debugger is busy in evaluation - e.g. after entering a long-running command in the debug window, or when hovering above a variable that has a long-running `__repr__` method - there is no visible indication of this work. This contributes to a programmer's confusion/frustration trying to understand why the debugger is non-responsive.

A good counter example is the "Locals" window which **does** show an indicator when evaluating variables.

Also, sometimes one might hover over a really nasty variable (e.g. a big pandas DataFrame) and the debugger will work very hard to show the str representation in a tool-tip. Could be useful to be able to cancel this evaluation in the middle.

**Comment by int19h** [comment]
The "busy" indicator in Locals is something that VSCode itself implements for all debug adapters - we don't control that. So the same for the Debug Console would be a feature request for https://github.com/microsoft/vscode

With respect to cancelable evaluations - we'd love to have them, but unfortunately the runtime doesn't provide any reliable means to implement it. There's `Py_AddPendingCall()`, but this only works for main thread, and even then it's implemented by CPython's bytecode eval loop - so any long-running operation in native code (which would be the case with large numpy arrays or Pandas dataframes) wouldn't be affected by it.

**Comment by int19h** [comment]
#173 is the existing item tracking cancellation.
