### ISSUE TITLE
Could a disable_attach API available?

### ISSUE THREAD

**Issue by buddyliao** [microsoft/debugpy#297]
ptvsd offers an enable_attach() API for us to start the debug, however, if we want to disable the debugger, we need to restart the python process, I am wonder whether a disable_attach API is available for us to stop the debugger？

**Comment by buddyliao** [comment]
I want to use IDE to debug remote python app. So I also need a wait_for_attach API in some situations. For disable_attach API, just stop tracing is OK. Actually, pydevd.stoptrace() works, but it's better if pydevd.stoptrace is packaged in debugpy.disable_attach. Since I just need to import debugpy, otherwise I also need to import pydevd.

**Comment by int19h** [comment]
Since the API is now `debugpy.listen()`, the proposed counterpart would be named `debugpy.stop_listening()`.

**Comment by judej** [comment]
Thank you for the report. Given our current resources are working on the Python 3.12 debugger, we will not be fixing this issues in the pre Python 3.12 debugger.

**Comment by Andrej730** [comment]
Is there some current workaround to stop the debugging server? `pydevd.stoptrace()` doesn't seem to help.
Can we keep this issue open to indicate that it's unresolved?

```python
import debugpy
port = 9992
debugpy.listen(port)
print('start debug server')

import pydevd
pydevd.stoptrace()
print('debug server stopped')

debugpy.listen(port)
# RuntimeError: timed out waiting for adapter to connect

# never printed:
print('debug server restarted')
```

**Comment by heartacker** [comment]
please

**Comment by nhadziosma1** [comment]
There is so much of us who would really appreciate if you could implement a function like `debugpy.stop_listening()` and/or `debugpy.disconnect()`, and thus I think that this issue should not be considered as 'Closed', but actually prioritized.

**Comment by heartacker** [comment]
yes please
