### ISSUE TITLE
Remote attach from ms-python to debugpy failing: Invalid message: Session is not initialized yet

### ISSUE THREAD

**Issue by kmroz** [microsoft/debugpy#302]
Hi,

I'm experiencing a problem with remote attach to debugpy from the ms-python in VS Code.

When launching the debug configuration in VS Code, I receive the following error message:

"Invalid message: Session is not initialized yet"

Adapter logs from debugpy are below.  It appears that debugpy receives the 'attach' request
before 'initialize' and throws an exception.  Google also found a discussion (but with no
apparent resolution on gitmemory.com - https://www.gitmemory.com/issue/microsoft/ptvsd/2044/575232817)

I've tried 2 prior me-python extension versions with no luck, as well as the 1.0.0b11
debubpy version.  The problem persists.

My launch.json configuration for the remote attach:

    {
        "name": "Python: Remote Attach",
        "type": "python",
        "request": "attach",
        "port": 5678,
        "host": "10.10.0.10",
        "logToFile": true,
        "pathMappings": [
            {
                "localRoot": "${workspaceFolder}/.debug-eggs",
                "remoteRoot": "<trimmed>"
            }
        ]
     },

Debubpy is running on the target as follows:
`/usr/lib/python-exec/python2.7/python2 -m debugpy --log-to /root --listen 0.0.0.0:5678 -m <trimmed>`
`/usr/lib/python-exec/python2.7/python2 /usr/lib/python2.7/site-packages/debugpy-1.0.0b10-py2.7-linux-x86_64.egg/debugpy/adapter --for-server 36011 --host 0.0.0.0 --port 5678 --server-access-token abc55ae1e288443348f5f1fdd15289bca8fd1243f5d253b407f93df5888fb294 --log-dir /root`

I've read through https://github.com/microsoft/debugpy/issues/171, but the 'localhost' workaround
is inadequate in my case.  Further, the requirements.txt point is nearing a year old.

Thanks in advance for any guidance/help.

Regards,
-Karol

debubpy adapter logs:
    
    I+-0000.008: Accepted incoming Client connection from 10.10.0.1:43446.

    D+-0000.007: Starting message loop for channel Client[2]

    D+-0000.007: Client[2] --> {
                 "seq": 2, 
                 "type": "request", 
                 "command": "attach", 
                 "arguments": {
                     "pathMappings": [
                         {
                             "remoteRoot": "<trimmed>", 
                             "localRoot": "<trimmed>"
                         }
                     ], 
                     "name": "Python: Remote Attach", 
                     "__sessionId": "67575f8a-56b8-428e-865d-b25af1d422b3", 
                     "logToFile": true, 
                     "request": "attach", 
                     "debugOptions": [
                         "RedirectOutput", 
                         "UnixClient", 
                         "ShowReturnValue"
                     ], 
                     "host": "10.10.0.10", 
                     "workspaceFolder": "<trimmed>", 
                     "showReturnValue": true, 
                     "type": "python", 
                     "port": 5678, 
                     "justMyCode": true
                 }
             }

    D+-0000.005: Client[2] --> {
                 "seq": 1, 
                 "type": "request", 
                 "command": "initialize", 
                 "arguments": {
                     "supportsProgressReporting": true, 
                     "adapterID": "python", 
                     "locale": "en-us", 
                     "supportsRunInTerminalRequest": true, 
                     "pathFormat": "path", 
                     "clientID": "vscode", 
                     "supportsVariableType": true, 
                     "supportsVariablePaging": true, 
                     "linesStartAt1": true, 
                     "columnsStartAt1": true, 
                     "clientName": "Visual Studio Code"
                 }
             }
    E+-0000.003: /handling #2 request "attach" from Client[2]/
             Traceback (most recent call last):
               File "/usr/lib/python2.7/site-packages/debugpy-1.0.0b10-py2.7-linux-x86_64.egg/debugpy/adapter/../../debugpy/common/messaging.py", line 1058, in __init__
                 raise self
             InvalidMessageError: Invalid message: Session is not initialized yet
             
             Stack where logged:
               File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
                 self.__bootstrap_inner()
               File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                 self.run()
               File "/usr/lib/python2.7/threading.py", line 754, in run
                 self.__target(*self.__args, **self.__kwargs)
               File "/usr/lib/python2.7/site-packages/debugpy-1.0.0b10-py2.7-linux-x86_64.egg/debugpy/adapter/../../debugpy/common/messaging.py", line 1500, in _run_handlers
                 handler()
               File "/usr/lib/python2.7/site-packages/debugpy-1.0.0b10-py2.7-linux-x86_64.egg/debugpy/adapter/../../debugpy/common/messaging.py", line 743, in _handle
                 result = handler(self)
               File "/usr/lib/python2.7/site-packages/debugpy-1.0.0b10-py2.7-linux-x86_64.egg/debugpy/adapter/../../debugpy/adapter/components.py", line 95, in lock_and_handle
                 return f(self, message)
               File "/usr/lib/python2.7/site-packages/debugpy-1.0.0b10-py2.7-linux-x86_64.egg/debugpy/adapter/../../debugpy/adapter/clients.py", line 175, in handle
                 raise request.isnt_valid("Session is not initialized yet")
               File "/usr/lib/python2.7/site-packages/debugpy-1.0.0b10-py2.7-linux-x86_64.egg/debugpy/adapter/../../debugpy/common/messaging.py", line 551, in isnt_valid
                 return self.error(InvalidMessageError, *args, **kwargs)
               File "/usr/lib/python2.7/site-packages/debugpy-1.0.0b10-py2.7-linux-x86_64.egg/debugpy/adapter/../../debugpy/common/messaging.py", line 542, in error
                 exc = exc_type(reason, self, silent)  # will log it
               File "/usr/lib/python2.7/site-packages/debugpy-1.0.0b10-py2.7-linux-x86_64.egg/debugpy/adapter/../../debugpy/common/messaging.py", line 1060, in __init__
                 log.swallow_exception()
               File "/usr/lib/python2.7/site-packages/debugpy-1.0.0b10-py2.7-linux-x86_64.egg/debugpy/adapter/../../debugpy/common/log.py", line 215, in swallow_exception
                 _exception(format_string, *args, **kwargs)
             

    D+-0000.002: /handling #2 request "attach" from Client[2]/
             Client[2] <-- {
                 "seq": 1, 
                 "type": "response", 
                 "request_seq": 2, 
                 "success": false, 
                 "command": "attach", 
                 "message": "Invalid message: Session is not initialized yet"
             }

    E+00000.000: /handling #2 request "attach" from Client[2]/
             Handler 'handle' (file u'/usr/lib/python2.7/site-packages/debugpy-1.0.0b10-py2.7-linux-x86_64.egg/debugpy/adapter/../../debugpy/adapter/components.py', line 91)
             couldn't handle #2 request "attach" from Client[2]:
             Invalid message: Session is not initialized yet

    D+00000.002: Client[2] <-- {
                 "seq": 2, 
                 "type": "event", 
                 "event": "output", 
                 "body": {
                     "category": "telemetry", 
                     "output": "ptvsd", 
                     "data": {
                         "packageVersion": "1.0.0b10"
                     }
                 }
             }

    D+00000.002: Client[2] <-- {
                 "seq": 3, 
                 "type": "event", 
                 "event": "output", 
                 "body": {
                     "category": "telemetry", 
                     "output": "debugpy", 
                     "data": {
                         "packageVersion": "1.0.0b10"
                     }
                 }
             }

    D+00000.003: /handling #1 request "initialize" from Client[2]/
             Capabilities: {
                 "supportsVariableType": true, 
                 "supportsRunInTerminalRequest": true, 
                 "supportsVariablePaging": true, 
                 "supportsMemoryReferences": false
             }

    D+00000.003: /handling #1 request "initialize" from Client[2]/
             Expectations: {
                 "locale": "en-us", 
                 "linesStartAt1": true, 
                 "columnsStartAt1": true, 
                 "pathFormat": "path"
             }
    D+00000.005: /handling #1 request "initialize" from Client[2]/
             Client[2] <-- {
                 "seq": 4, 
                 "type": "response", 
                 "request_seq": 1, 
                 "success": true, 
                 "command": "initialize", 
                 "body": {
                     "supportsModulesRequest": true, 
                     "supportsConfigurationDoneRequest": true, 
                     "supportsDelayedStackTraceLoading": true, 
                     "supportsDebuggerProperties": true, 
                     "supportsHitConditionalBreakpoints": true, 
                     "supportsSetExpression": true, 
                     "supportsSetVariable": true, 
                     "supportsLogPoints": true, 
                     "supportsCompletionsRequest": true, 
                     "exceptionBreakpointFilters": [
                         {
                             "filter": "raised", 
                             "default": false, 
                             "label": "Raised Exceptions"
                         }, 
                         {
                             "filter": "uncaught", 
                             "default": true, 
                             "label": "Uncaught Exceptions"
                         }, 
                         {
                             "filter": "userUnhandled", 
                             "default": true, 
                             "label": "User Uncaught Exceptions"
                         }
                     ], 
                     "supportsExceptionInfoRequest": true, 
                     "supportsValueFormattingOptions": true, 
                     "supportsEvaluateForHovers": true, 
                     "supportsExceptionOptions": true, 
                     "supportsGotoTargetsRequest": true, 
                     "supportsTerminateDebuggee": true, 
                     "supportsConditionalBreakpoints": true
                 }
             }

    D+00000.005: Client[2] --> {
                 "seq": 3, 
                 "type": "request", 
                 "command": "disconnect", 
                 "arguments": {
                     "restart": false
                 }
             }

    I+00000.006: /handling #3 request "disconnect" from Client[2]/
             client requested "disconnect"; finalizing Session[2].

    D+00000.006: /handling #3 request "disconnect" from Client[2]/
             Client[2] <-- {
                 "seq": 5, 
                 "type": "event", 
                 "event": "terminated"
             }

    I+00000.006: /handling #3 request "disconnect" from Client[2]/
             Session[2] finalized.

    D+00000.006: /handling #3 request "disconnect" from Client[2]/
             Client[2] <-- {
                 "seq": 6, 
                 "type": "response", 
                 "request_seq": 3, 
                 "success": true, 
                 "command": "disconnect"
             }

    D+00000.007: Exiting message loop for channel Client[2]: No more messages

    D+00000.007: Closing Client[2] message stream

    I+00000.008: /handling disconnect from Client[2]/
             Session[2] has ended.

## Environment data
VS Code 1.46.1
ms-python plugin 2020.6.89148
debugpy 1.0.0b10 (problem present with 1.0.0b11 also)
Python 2.7.16 on the remote host
OS: Local Ubuntu 18.04 (4.15.0-96-generic kernel), remote host is Gentoo based (4.18.0 kernel)

## Expected  behavior
VS Code with ms-python should be able to connect to the remote host running debugpy.

## Steps to reproduce:
Basic remote attach to debugpy listening on a remote host (as described above).

**Comment by pegre94** [comment]
I also have problem with debugpy which looks to me like the same issue that op have.

**Comment by karthiknadig** [comment]
Try restarting VSCode, this should be fixed. See https://github.com/microsoft/vscode-python/issues/12481#issuecomment-647274814

**Comment by kmroz** [comment]
@karthiknadig I just installed the latest 'insiders' vsix and was able to connect to debugpy.  Many thanks.  Closing this ticket.
