### ISSUE TITLE
Breakpoints not working with QThread/PySide2

### ISSUE THREAD

**Issue by intrinseca** [microsoft/debugpy#304]
## Environment data

- debugpy version: 1.0.0b11
- OS and version: Windows 10 1909 Build 18363.900
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.7.5 64-bit
- Using VS Code or Visual Studio: VS Code

First detected with general release of Python extension and also reproduced with the Insiders edition.

## Actual behavior

Breakpoints in an object moved to a new QThread are not triggered

## Expected  behavior

Breakpoints should work as normal.

I tried to work out if the Qt monkey-patching was being triggered properly, but debugging a debugger was beyond me! Is there any way to check if this has happened?

## Steps to reproduce:
1. `pip install PySide2`
2. Debug the following script, with a breakpoint set on the `print` inside `Receiver.test` (L11)
```python
import sys
import threading

from PySide2.QtCore import QObject, QThread, Slot
from PySide2.QtWidgets import QApplication, QPushButton


class Receiver(QObject):
    @Slot()
    def test(self):
        print(f"Received Event on thread {threading.current_thread().name}")


if __name__ == "__main__":
    app = QApplication(sys.argv)

    button = QPushButton("Hello World!")
    button.show()

    thread = QThread()
    receiver = Receiver()

    receiver.moveToThread(thread)
    thread.start()

    button.clicked.connect(receiver.test)

    app.exec_()
```
3. Click the button on the GUI window
4. Breakpoint is not triggered

## VS Code launch.json

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal"
        }
    ]
}
```

**Comment by intrinseca** [comment]
The debugger side of things seems to be working - if I manually enable debugpy on the background thread it works as intended:

```python
import sys
import threading

from PySide2.QtCore import QObject, QThread, Slot
from PySide2.QtWidgets import QApplication, QPushButton


class MyQThread(QThread):
    def run(self, *args, **kwargs):
        import debugpy
        debugpy.debug_this_thread()
        super().run()


class Receiver(QObject):
    @Slot()
    def test(self):
        print(f"Received Event on thread {threading.current_thread().name}")


if __name__ == "__main__":
    app = QApplication(sys.argv)

    button = QPushButton("Hello World!")
    button.show()

    thread = MyQThread()
    receiver = Receiver()

    receiver.moveToThread(thread)
    thread.start()

    button.clicked.connect(receiver.test)

    app.exec_()
```

**Comment by int19h** [comment]
Qt monkey-patching is supposed to be enabled by default, but it looks like we regressed that.

**Comment by int19h** [comment]
Looks like we regressed it quite a while ago, actually - before ptvsd became debugpy, even. Since it's not an easy revert, I'm going to do this properly - as a configurable property exposing the entire gamut of relevant pydevd settings, to allow fine tuning. The default will still be "auto" though, matching ptvsd 4 behavior.

**Comment by msc509** [comment]
Can you elaborate whether this is fixed? I have the same issue on the latest python extension, failing to capture breakpoints in a QThread. The fix reference above seem to add a config option, but I don't see how to use it.

**Comment by fabioz** [comment]
This should be fixed... 

There are 2 modes of operation, one in which the debugger can debug qt out of the box (when you use Python 3.6 onwards and its compiled extensions are available) and the other which requires some monkey-patching from the debugger.

Given that it's not working for you, you're probably on the 2nd case.

So, to turn on that monkey-patching, please set:

`"qt": "auto",` in the launch config.

-- note: it seems `vscode-python` currently complains that `Property qt is not allowed.`, that's ok, this is just that `vscode-python` still hasn't added that to the schema (it's tracking this at: https://github.com/microsoft/vscode-python/issues/12535).
