### ISSUE TITLE
Add test for "qt" debug config property

### ISSUE THREAD

**Issue by int19h** [microsoft/debugpy#309]
See https://github.com/microsoft/debugpy/pull/308

Need to figure out how to properly do this in a non-UI test. `QThread` is in `QtCore`, so it should be doable.

**Comment by fabioz** [comment]
As a note, you can use the code in `pydevd` as a reference.

i.e.:

https://github.com/microsoft/debugpy/blob/master/src/debugpy/_vendored/pydevd/tests_python/resources/_debugger_case_qthread1.py
https://github.com/microsoft/debugpy/blob/master/src/debugpy/_vendored/pydevd/tests_python/resources/_debugger_case_qthread2.py
https://github.com/microsoft/debugpy/blob/master/src/debugpy/_vendored/pydevd/tests_python/resources/_debugger_case_qthread3.py
https://github.com/microsoft/debugpy/blob/master/src/debugpy/_vendored/pydevd/tests_python/resources/_debugger_case_qthread4.py

Although if I remember well, I think that even in this case I had to use (in travis):
`export DISPLAY=:99.0`
`services: xvfb`
