### ISSUE TITLE
Occasional missing response to "configurationDone"

### ISSUE THREAD

**Issue by int19h** [microsoft/debugpy#314]
Sometimes, when receiving "configurationDone", and starting to execute user code, if the script exits almost immediately, the adapter closes the connection before the response to "configurationDone" is actually delivered to the client. 

I've only seen it on CI Linux and macOS runs, and it's very rare, so it's hard to diagnose. But I suspect that this is another manifestation of pydevd messaging being asynchronous (#1699) - basically, if the process exits too fast, pydevd simply doesn't deliver the response, or delivers a partial response. The adapter then treats it as a failed response from the server, and in turn responds to IDE's "configurationDone" with failure "Server-1 disconnected unexpectedly".

Part of the problem may be that `on_configurationdone_request()` in `pydevd_process_net_command_json.py` invokes `api.run()` _before_ sending the response. Perhaps that needs to be re-ordered?

**Comment by int19h** [comment]
This is still happening in test runs.

@fabioz, given the long history of this issue and all the attempts to remedy it so far, would you say that this just has to be gracefully handled by the adapter? i.e. that if it sends "configurationDone", and instead of a response, the server just disconnects, it should assume that it ran to completion, and not report it as an error to the client?

**Comment by fabioz** [comment]
> This is still happening in test runs.
> 
> @fabioz, given the long history of this issue and all the attempts to remedy it so far, would you say that this just has to be gracefully handled by the adapter? i.e. that if it sends "configurationDone", and instead of a response, the server just disconnects, it should assume that it ran to completion, and not report it as an error to the client?

Yes, I think that's a good idea.

**Comment by int19h** [comment]
The fix wasn't complete, and this still happens in test runs.
