### ISSUE TITLE
Wrong file indication by debuger in VSC when Exception

### ISSUE THREAD

**Issue by ManPython** [microsoft/debugpy#321]
## Environment data
- debugpy version: 1.0.0b12
- OS and version: W7
- Python version (& distribution if applicable, e.g. Anaconda): Python36
- Using VS Code or Visual Studio:
Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 6.1.7601

## Actual behavior
When bug, then wrong file indication by debuger in VSC when Exception.
In example bug is on `MainView.py, line 36`:
But opended file by VSC and debuger is `MainController.py` and this file is called.
![dedubpy_1](https://user-images.githubusercontent.com/25403861/86270236-33cc3e80-bbcb-11ea-868d-f638afed42e9.png)

## Expected  behavior
The indication should be on `MainView.py, line 36` not `MainController.py` point of importing MainView.py

## Steps to reproduce:
I;m using MVC with QT/Pyside2 and Dialogs. I made some typo on var.

**Comment by fabioz** [comment]
This is probably because you have the `justMyCode` setting set to `true` (so, it'll only report an exception when it reaches your own code).

**Comment by int19h** [comment]
This is because it's not a runtime error during execution of `MainView`, but rather a syntax error when it was *parsed*. So the *cause* of the syntax error is displayed as part of the error message; but the Call Stack pane (and thus, the highlighted line in the editor) shows where the code was *running* when the error happened. - and that was the `import` statement in MainController.

**Comment by ManPython** [comment]
@fabioz I'm don't have in settings justMyCode  = True, or False. And False for Django projects. HVR working now with QT and sometimes bug redirecting me to right files, other time no.

@int19h this case not convited me. In my opinion the exception should indicate the palce of line where is syntax error not import. 
This working in stupid way in case I must check the number and go to other file.

**Comment by int19h** [comment]
@ManPython The highlighted line in the editor is tied to Call Stack - that's just the way VSCode works. So for it to highlight the line where syntax error applied, there would have to be a stack frame with that line number on top of the stack, at the point Pause happens.

But there's *no actual stack frame* as far as Python is concerned, so why should it report a non-existing thing that doesn't correspond to anything real in your Python process? And if we did report one, where would it come from, and what would happen if you tried to inspect variables in it, or try to step?

**Comment by ManPython** [comment]
Why? Coz pratice? : )
Still not convicted ;]

I made test on other IDE and debuger. Eg. intersting solution have Pyscripter.  I was not in consciousness about some of solution if was't problematic and in this same bug Pyscripter offering clicl the line to move to the line/col where is problem. Right it's debug console, but in VSC code don't have this solution that is really required. If this is limitation on VSC then need improments here.
The fact Pyscripter is more simple and limited in options than VSC, this same PyCharm. I'm not oriented is limitation in VSC or debugpy/ptv
