### ISSUE TITLE
How do you set the debugpy launcher to use python3?

### ISSUE THREAD

**Issue by dwbelliston** [microsoft/debugpy#323]
![image](https://user-images.githubusercontent.com/11450118/86318308-d6e27f80-bbee-11ea-8f0d-f239331c7eda.png)

This file has a section of args that are passed to docker exec.

```
dockerExecArgs = ['docker', 'exec', '-d', containerId, 'python', '/debugpy/launcher'] + args
```

My debug fails, because the container recieves `python` as python2.7, but my program needs python3, which is available in the container. If i change this launcher.py file to python3 it works. Can i pass this somehow to the launcher?

**Comment by int19h** [comment]
This file is from https://github.com/microsoft/vscode-docker/blob/master/resources/python/launcher.py - can you file an issue on that repo? I couldn't find an existing one, and I don't have permissions needed to transfer this one, unfortunately.

**Comment by dwbelliston** [comment]
ah - mix up - thanks for pointing that out. link to the other repo incase someone stumbles on this later

https://github.com/microsoft/vscode-docker/issues/2123
