### ISSUE TITLE
Server[pid=7752] disconnected unexpectedly

### ISSUE THREAD

**Issue by ManPython** [microsoft/debugpy#327]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

1. There was issue on VSC but touching `vscode-python`
https://github.com/microsoft/vscode/issues/85318

## Actual behavior
2. When simple script is executed, looks we not have option to operate on objects - eg. like on Pyscripter, on the Debug Console

## Expected behavior
3. Aftrt script execution want operate on object, eg. to call object, checking types, etc. like print()

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 6.1.7601

## Developer Tools Console Output

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by fabioz** [comment]
From the report on vscode, the cause seems to be:

```
               File "/root/.vscode-server/extensions/ms-python.python-2019.11.49689/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/launcher/../../ptvsd/launcher/debuggee.py", line 76, in spawn
                 "pointerSize": struct.calcsize("P") * 8,
             TypeError: Struct() argument 1 must be string, not unicode
```

This is definitely fixed for quite some time already, so, it seems that the issue is that the version being used is old (so, please upgrade to a newer version).

**Comment by fabioz** [comment]
Note: if this is not the cane and you have an up to date version, please include the logs and reopen the issue when you have that `Server[pid=7752] disconnected unexpectedly`.

i.e.:

* Open VS Code
* Select the command Extensions: Open Extensions Folder
* Locate the Python extension directory, typically of the form ms-python.python-2020.*.****
* In that directory ensure you do not have any debug*.log files, if you do, please delete them
* Go back into VS Code and modify your launch.json to add the setting "logToFile": true, see below:

```
"version": "0.2.0",
"configurations": [
    {
        "name": "Python: Current File (Integrated Terminal)",
        "type": "python",
        "request": "launch",
        "program": "${file}",
        "stopOnEntry": true,
        "console": "integratedTerminal",
        "logToFile": true
    },
```

* Start debugging
* When done, go back into the extension directory and upload the debug*.log files into this GitHub issue.

**Comment by ManPython** [comment]
Looks problem is solved.
