### ISSUE TITLE
Adapter times out when running from Maya 

### ISSUE THREAD

**Issue by luabud** [microsoft/debugpy#334]
```
import cube
# Error: RuntimeError: file C:\Program Files\Autodesk\Maya2020\Python\lib\site-packages\debugpy\server\api.py line 224: timed out waiting for adapter to connect # 
```

cube.py:
```py
import maya.cmds as mc
import debugpy 
import time

#while debugpy.is_client_connected():
#    time.sleep(0.5)

debugpy.listen(("localhost",5678))
debugpy.wait_for_client()

debugpy.breakpoint()
r = mc.polyCube(w=2,h=9,d=2)

debugpy.breakpoint()
print("hey!")
```

Run selection for "import cube"

**Comment by fabioz** [comment]
I don't really have Maya to test and it seems to work for me in the usual attach to port `5678`... Do you know which Python version is Maya using?

One thing to try: replace `localhost` with `127.0.0.1` (both in the launch and in `debugpy.listen`).

If it doesn't work, please provide the logs (from Maya and from VSCode).

To get the logs from Maya, you should be able to do something as:

```
import debugpy
debugpy.log_to('c:/temp')
```

To get the logs from VSCode:

* Open VS Code
* Select the command Extensions: Open Extensions Folder
* Locate the Python extension directory, typically of the form ms-python.python-2020.*.****
* In that directory ensure you do not have any debug*.log files, if you do, please delete them
* Go back into VS Code and modify your launch.json to add the setting "logToFile": true to the attach, see below:

```
"version": "0.2.0",
"configurations": [
        {
            "name": "Python Attach to 5678",
            "type": "python",
            "request": "attach",
            "port": 5678,
            "host": "127.0.0.1",
            "logToFile": true,
        },```

* Start debugging
* When done, go back into the extension directory and upload the debug*.log files into this GitHub issue.

**Comment by int19h** [comment]
We had a collaborative debug session about this, and it's pretty complicated (there are various things that seem to not work in Maya). I'll investigate it further.

**Comment by fabioz** [comment]
As a note, I believe that plain `pydevd` does work in `Maya` using the remote attach (from reports I got in the past), so, my hunch is that this is related to launching the secondary adapter process/connecting to it, but if it turns out you need something on the `pydevd` side, please let me know.

**Comment by luabud** [comment]
FWIW Maya uses Python 2.7 😅 and I manually added debugpy to site-packages because they seem to use some sort of custom Python.

**Comment by munkybuttballs** [comment]
Are there any updates on this?
I am having the same problem in 3DsMax using debugpy where as pydevd used to work without issue.

**Comment by daniele-niero** [comment]
Same here

**Comment by bob-white** [comment]
I'm running into a similar problem with our own application that embeds maya.
The issue seems to be that `debugpy.listen` spawns a subprocess using `sys.executable` which will fail for Maya/Max/Our Tool. Because these aren't standard python processes that accept standard python arguments.

It would be nice if we could specify a python-process instead.

**Comment by RockShea** [comment]
I was considering the same approach, pointing it at the Max specific python exe.
Haven't had a chance to test yet.
If it is possible, it would be great to have this be exposed as a setting.

**Comment by int19h** [comment]
Ah, that makes sense! It would be https://github.com/microsoft/debugpy/issues/262, then.
