### ISSUE TITLE
Python Debugger can only attach but not launch

### ISSUE THREAD

**Issue by idotobi** [microsoft/debugpy#335]
## Environment data

-   VS Code version: VSCodium 1.47.0
-   Extension version (available under the Extensions sidebar): v2020.6.3
-   OS and version: Arch Linux
-   Kernel: Linux 5.7.7-arch1-1
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.3
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Value of the `python.languageServer` setting: Jedi

## Expected behaviour

When running a simple `test.py` script with the debugger, I would expect the debugger to launch the program without an error.

`src/test.py`:

```py
a = 2
b = 2 * a
print(b)
```

`launch.json`:

```jsonc
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Python: test.py",
      "type": "python",
      "request": "launch",
      "program": "${workspaceFolder}/src/test.py"
    },

    {
      "name": "Python: Attach",
      "type": "python",
      "request": "attach",
      "connect": {
        "host": "localhost",
        "port": 5678
      }
    }
  ]
}
```

## Actual behaviour

When launching the Debugger "Python: test.py" the debug control appears for a second and then disappears again.

![debug_launch](https://user-images.githubusercontent.com/16611056/87320051-b5589080-c52a-11ea-83f9-5fcd05fe7cd6.gif)

The Output of `Log (Window)` shows:

```
[2020-07-13 16:54:39.840] [renderer1] [error] timeout after 1000 ms: Error: timeout after 1000 ms
    at t.RawDebugSession.handleErrorResponse (file:///usr/share/vscodium-bin/resources/app/out/vs/workbench/workbench.desktop.main.js:3173:226)
    at file:///usr/share/vscodium-bin/resources/app/out/vs/workbench/workbench.desktop.main.js:3172:532
    at async t.RawDebugSession.shutdown (file:///usr/share/vscodium-bin/resources/app/out/vs/workbench/workbench.desktop.main.js:3170:536)
```

## Workaround

So far the only workaround I could find is to start the debugger in the terminal

```sh
python -m debugpy --wait-for-client --listen 5678 ./src/test.py
```

and then launching the Python attach:

![debug_attach](https://user-images.githubusercontent.com/16611056/87320036-affb4600-c52a-11ea-94fe-5bd4c67ffa1c.gif)

**Comment by fabioz** [comment]
@idotobi Can you provide the logs when this happens?

i.e.:

* Open VS Code
* Select the command Extensions: Open Extensions Folder
* Locate the Python extension directory, typically of the form ms-python.python-2020.*.****
* In that directory ensure you do not have any debug*.log files, if you do, please delete them
* Go back into VS Code and modify your launch.json to add the setting `"logToFile": true`... something like:

```
"version": "0.2.0",
"configurations": [
    {
        "name": "Python: Current File (Integrated Terminal)",
        "type": "python",
        "request": "launch",
        "program": "${file}",
        "stopOnEntry": true,
        "console": "integratedTerminal",
        "logToFile": true
    },
```

* Start debugging
* When done, go back into the extension directory and upload the debug*.log files into this GitHub issue.

**Comment by idotobi** [comment]
@fabioz Thank you for the quick reply:

Here is my output:

```jsonc
0 Starting Session:
{
    "name": "Python: Current File (Integrated Terminal)",
    "type": "python",
    "request": "launch",
    "program": "/home/user/Documents/05_IT/Programming/projects/app/src/app/main.py",
    "stopOnEntry": true,
    "console": "integratedTerminal",
    "logToFile": true,
    "pythonPath": "/home/user/.virtualenvironment/app/bin/python",
    "cwd": "/home/user/Documents/05_IT/Programming/projects/app",
    "envFile": "/home/user/Documents/05_IT/Programming/projects/app/.env",
    "env": {
        "PYTHONIOENCODING": "UTF-8",
        "PYTHONUNBUFFERED": "1"
    },
    "showReturnValue": true,
    "internalConsoleOptions": "neverOpen",
    "debugOptions": [
        "StopOnEntry",
        "ShowReturnValue"
    ],
    "justMyCode": true,
    "workspaceFolder": "/home/user/Documents/05_IT/Programming/projects/app"
}
11 Client --> Adapter:
{
    "command": "initialize",
    "arguments": {
        "clientID": "vscode",
        "clientName": "VSCodium",
        "adapterID": "python",
        "pathFormat": "path",
        "linesStartAt1": true,
        "columnsStartAt1": true,
        "supportsVariableType": true,
        "supportsVariablePaging": true,
        "supportsRunInTerminalRequest": true,
        "locale": "en-us",
        "supportsProgressReporting": true
    },
    "type": "request",
    "seq": 1
}
26 Exit:
Exit-Code: 2
Signal: none

```

**Comment by int19h** [comment]
This is the log from VSCode. You need to look for files names `debugpy*.log` in the directory where the Python extension is installed (under `~/.vscode` usually, I'm not sure what that'll be for VSCodium).

**Comment by idotobi** [comment]
Sadly there is no `debugpy*.log`. Looking for any debugpy file I only get following output

```bash
.vscode-oss $ fd debugpy
extensions/ms-python.python-2020.7.0/pythonFiles/install_debugpy.py
```

However both in the virtualenvironment and outside I can call it directly using:

```
python -m debugpy
```

Could it be a problem that my python version is `Python 3.8.3`?

**Comment by int19h** [comment]
Python 3.8 definitely shouldn't be causing any problems.

It's rather weird that "logToFile" is not working here, but we can try another way - set `DEBUGPY_LOG_DIR` environment variable in the shell from which you start VSCode (or in any other way that makes it be seen from the debugged proess), and point it to the directory where it should place the logs.

**Comment by int19h** [comment]
Oh, one more thing - since you're using "integratedTerminal", you should be seeing the command line that's used to start debugging in VSCode terminal. Can you share that?

**Comment by idotobi** [comment]
> Python 3.8 definitely shouldn't be causing any problems.
> 
> It's rather weird that "logToFile" is not working here, but we can try another way - set `DEBUGPY_LOG_DIR` environment variable in the shell from which you start VSCode (or in any other way that makes it be seen from the debugged proess), and point it to the directory where it should place the logs.

I don't see any debug log files being created. Only when I run `python -m debugpy --wait-for-client --listen 5678 main.py` directly then I get log files.



> Oh, one more thing - since you're using "integratedTerminal", you should be seeing the command line that's used to start debugging in VSCode terminal. Can you share that?

In the terminal I see nothing apart from the environment getting activated (`source /home/user/.virtualenvironment/app/bin/activate`) but there's no further command being executed.

It really seems that for some reason debugpy ist not started from vscode.

**Comment by int19h** [comment]
Can you double-check that it's the right terminal? The one used by the debugger should be titled "Python Debug Console" (you can switch them in the dropdown on the top right of the terminal pane). It's supposed to get focus automatically, but since this isn't mainline VSCode, it might be functioning differently.

Are any of the Remote extensions (SSH, WSL, Docker) involved?

**Comment by int19h** [comment]
One more thing. I suspect this might have something to do with VSCodium, being a fork that specifically removes telemetry, might also mess up A/B experiments - debugpy had been one, even though it has been running at 100% for a while. If VSCodium effectively opts you out of all experiments, then it would mean that the extension is using the old ptvsd in your install.

If this is the case, then updating the extension to 2020.7.0, which shipped a few days ago, should force it to use debugpy. It might actually fix your issue entirely, but either way, at least it should fix the missing logs.

**Comment by idotobi** [comment]
> Can you double-check that it's the right terminal? The one used by the debugger should be titled "Python Debug Console" (you can switch them in the dropdown on the top right of the terminal pane). It's supposed to get focus automatically, but since this isn't mainline VSCode, it might be functioning differently.

The Debugconsole is also empty (see screencapture below).

> Are any of the Remote extensions (SSH, WSL, Docker) involved?

No it's all local.

> If this is the case, then updating the extension to 2020.7.0, which shipped a few days ago, should force it to use debugpy. It might actually fix your issue entirely, but either way, at least it should fix the missing logs.

The version is `2020.7.0` and I'm launching the application with `DEBUGPY_LOG_DIR=/home/user vscodium` and there are still no logs.

![debugpy](https://user-images.githubusercontent.com/16611056/87857932-dbb36d00-c92a-11ea-982e-e6ba9e24860d.gif)

**Comment by idotobi** [comment]
I did a little bit more of debugging and I found the following when executing `DEBUGPY_LOG_DIR=/home/user vscodium --verbose`

```
[4729:0719/111433.109999:INFO:CONSOLE(4312)] "Error: [ms-python.python]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api ms-python.python
```

> One more thing. I suspect this might have something to do with VSCodium, being a fork that specifically removes telemetry, might also mess up A/B experiments - debugpy had been one, even though it has been running at 100% for a while. If VSCodium effectively opts you out of all experiments, then it would mean that the extension is using the old ptvsd in your install.

So it seems your suspicion was right :+1: 

 When running: `DEBUGPY_LOG_DIR=/home/user vscodium --verbose --enable-proposed-api ms-python.python`  I don't get that error anymore but this one:

```
[4383:0719/111344.503260:INFO:CONSOLE(1670)] "%c  ERR color: #f33 write after end: Error [ERR_STREAM_WRITE_AFTER_END]: write after end
        at writeAfterEnd (_stream_writable.js:250:14)
        at m.Writable.write (_stream_writable.js:299:5)
        at u.log (/home/tobidot/.vscode-oss/extensions/ms-python.python-2020.7.0/out/client/extension.js:48:722833)
        at u.onWillStopSession (/home/tobidot/.vscode-oss/extensions/ms-python.python-2020.7.0/out/client/extension.js:48:722594)
        at /usr/share/vscodium-bin/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:862:612
        at Array.forEach (<anonymous>)
        at k.onWillStopSession (/usr/share/vscodium-bin/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:862:579)
        at v.$stopDASession (/usr/share/vscodium-bin/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:853:278)
        at m._doInvokeHandler (/usr/share/vscodium-bin/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:801:683)
        at m._invokeHandler (/usr/share/vscodium-bin/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:801:375)
        at m._receiveRequest (/usr/share/vscodium-bin/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:800:14)
        at m._receiveOneMessage (/usr/share/vscodium-bin/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:798:832)
        at /usr/share/vscodium-bin/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:797:34
        at l.fire (/usr/share/vscodium-bin/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45:801)
        at v.fire (/usr/share/vscodium-bin/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:235:849)
        at /usr/share/vscodium-bin/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:975:744
        at l.fire (/usr/share/vscodium-bin/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45:801)
        at v.fire (/usr/share/vscodium-bin/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:235:849)
        at t.PersistentProtocol._receiveMessage (/usr/share/vscodium-bin/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:240:276)
        at /usr/share/vscodium-bin/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:237:357
        at l.fire (/usr/share/vscodium-bin/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45:801)
        at p.acceptChunk (/usr/share/vscodium-bin/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:233:393)
        at /usr/share/vscodium-bin/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:232:753
        at Socket.t (/usr/share/vscodium-bin/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:241:826)
        at Socket.emit (events.js:203:13)
        at addChunk (_stream_readable.js:295:12)
        at readableAddChunk (_stream_readable.js:276:11)
        at Socket.Readable.push (_stream_readable.js:210:10)
        at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)", source: file:///usr/share/vscodium-bin/resources/app/out/vs/workbench/workbench.desktop.main.js (1670)
```

There are still no debugpy logs and debugging is not working either.
So one problem solved another appeared :wink:

**Comment by int19h** [comment]
I tried to repro it, and found out that VSCodium uses its own package gallery (https://open-vsx.org/). The vscode-python package that's in that gallery is not made by us, and there's a warning to that effect displayed prominently if you [open the gallery in the browser](https://open-vsx.org/extension/ms-python/python). However, the same warning appears to be suppressed when browsing the gallery in VSCodium. In the browser, the actual publisher is reported as https://github.com/open-vsx, and there is a warning to that effect:

![image](https://user-images.githubusercontent.com/1175142/87975768-eda72400-ca80-11ea-9f2c-2e9f32384749.png)

I took a look at the VSIX, and it's badly broken - it's missing the entirety of the `lib` folder, which contains various Python packages that extension uses for much of its functionality. This includes `debugpy` package for the debugger, hence why it's not working. It appears that the publisher has already noticed, and opened an issue tracking this: https://github.com/open-vsx/publish-extensions/issues/89. You should follow that one to track resolution.

In addition, I think it would be good to file an issue on VSCodium to make it clearer that the package gallery, and the packages therein, are different from those in VSCode gallery. As it is, you had no way of knowing that it's a repackaged version, since VSCodium gallery browser shows publisher as "ms-python", and the Repository link goes to this repo.

**Comment by jankeromnes** [comment]
Hi all, apologies for the broken Python extension, and many thanks for helping troubleshoot & fix it in https://github.com/open-vsx/publish-extensions/issues/89.

As a quick update, https://open-vsx.org/extension/ms-python/python should now work again: If you uninstall & reinstall the Python extension in VSCodium, you should get version `2020.6.1`, which has been fixed. (Please confirm.)

We're now working to re-publish the other versions (because we've now deleted all broken uploads from OpenVSX), and we'll close the upstream issue once the latest Python extension (`2020.7.0`) has been re-published successfully.

**Comment by idotobi** [comment]
@jankeromnes : 🎉 It's working. Thank you very much for the quick fix.

Also thank you @int19h  for the amazing detective work.
