### ISSUE TITLE
Debugging dockerized Django in VS Code results in error “Timed out waiting for launcher to connect”

### ISSUE THREAD

**Issue by CrazyEasy** [microsoft/debugpy#339]
## Environment data
-   VS Code version: 1.47.1
-   Extension version (available under the Extensions sidebar): v2020.7.94776
-   OS and version: Ubuntu 18.04 LTS (Linux x64 4.15.0-111-generic snap)
-   Python version (& distribution if applicable, e.g. Anaconda): 3.6.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Docker Container
-   Relevant/affected Python packages and their versions: Django 3.0

## Expected behaviour

I want to debug my Django application using a docker container in Visual Studio Code.

Microsoft published a guide how to do that, which I followed step by step:
https://code.visualstudio.com/docs/containers/quickstart-python

## Actual behaviour

But when I try to run the debugger, I get the following error message:

    Timed out waiting for launcher to connect

## Steps to reproduce

Here is what I did step by step:

1. I initialized a simple Django application using `django-admin startproject helloworld`
2. In VS Code I opened the folder including the `manage.py`
3. Opened Command Palette `Ctrl + Shift + P`, and then selected `Docker: Add Docker Files to Workspace...`
4. Select Application Platform `Python: Django`
5. Include Docker Compose files `No`
6. Relative path to the app's entrypoint `manage.py`
7. What ports does your app listen on? `8000`

VS Codes then creates several files (see below).

## Terminal Output

When I try to start the debugger (like in the guide), I get the following error message:

[![Docker: Python - Django][1]][1]
[![Error: Timed out waiting for launcher to connect][2]][2]

The terminal doesn't show any error messages, but the commands executed:
[![terminal 1][3]][3]

[![terminal 2][4]][4]

## Files

.vscode/launch.json:

    {
        "configurations": [
            {
                "name": "Docker: Python - Django",
                "type": "docker",
                "request": "launch",
                "preLaunchTask": "docker-run: debug",
                "python": {
                    "pathMappings": [
                        {
                            "localRoot": "${workspaceFolder}",
                            "remoteRoot": "/app"
                        }
                    ],
                    "projectType": "django"
                }
            }
        ]
    }

.vscode/tasks.json:

    {
    	"version": "2.0.0",
    	"tasks": [
    		{
    			"type": "docker-build",
    			"label": "docker-build",
    			"platform": "python",
    			"dockerBuild": {
    				"tag": "dockerdebugging:latest",
    				"dockerfile": "${workspaceFolder}/Dockerfile",
    				"context": "${workspaceFolder}",
    				"pull": true
    			}
    		},
    		{
    			"type": "docker-run",
    			"label": "docker-run: debug",
    			"dependsOn": [
    				"docker-build"
    			],
    			"python": {
    				"args": [
    					"runserver",
    					"0.0.0.0:8000",
    					"--nothreading",
    					"--noreload"
    				],
    				"file": "manage.py"
    			}
    		}
    	]
    }

Dockerfile:

    # For more information, please refer to https://aka.ms/vscode-docker-python
    FROM python:3.8-slim-buster
    
    EXPOSE 8000
    
    # Keeps Python from generating .pyc files in the container
    ENV PYTHONDONTWRITEBYTECODE 1
    
    # Turns off buffering for easier container logging
    ENV PYTHONUNBUFFERED 1
    
    # Install pip requirements
    ADD requirements.txt .
    RUN python -m pip install -r requirements.txt
    
    WORKDIR /app
    ADD . /app
    
    # Switching to a non-root user, please refer to https://aka.ms/vscode-docker-python-user-rights
    RUN useradd appuser && chown -R appuser /app
    USER appuser
    
    # During debugging, this entry point will be overridden. For more information, please refer to https://aka.ms/vscode-docker-python-debug
    CMD ["gunicorn", "--bind", "0.0.0.0:8000", "helloworld.wsgi"]

requirements.txt:

    # To ensure app dependencies are ported from your virtual environment/host machine into your container, run 'pip freeze > requirements.txt' in the terminal to overwrite this file
    django==3.0.3
    gunicorn==20.0.4

  [1]: https://i.stack.imgur.com/KTgXH.png
  [2]: https://i.stack.imgur.com/XThLJ.png
  [3]: https://i.stack.imgur.com/CVSfD.png
  [4]: https://i.stack.imgur.com/5ClbP.png

**Comment by createchange** [comment]
@CrazyEasy - did you resolve this? Running into the same issue myself.

**Comment by CrazyEasy** [comment]
> @CrazyEasy - did you resolve this? Running into the same issue myself.

Yes, I had packages missing.

After `sudo apt install docker.io` everything worked fine.
