### ISSUE TITLE
Debugger Heisenbug where integer comparison appears to fail within a specific context

### ISSUE THREAD

**Issue by dddvision** [microsoft/debugpy#346]
## Environment data

-   VS Code version:
Version: 1.47.2
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:22:15.161Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-42-generic snap

-   Extension version (available under the Extensions sidebar):
ms-python.python v2020.7.96456

-   OS and version:
LSB Version:	core-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

-   Python version (& distribution if applicable, e.g. Anaconda):
Anaconda Python 3.7.7

-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...):
Python 3.7.7 64-bit ('base':conda)

-   Relevant/affected Python packages and their versions:
jsonpickle                    1.4.1  
numpy                         1.18.1  
SQLAlchemy               1.3.17 

-   Relevant/affected Python-related VS Code extensions and their versions:
ms-python.python v2020.7.96456

-   Value of the `python.languageServer` setting:
Microsoft

## Expected behaviour
When debugging the attached file and stepping into __main__ on line 33 with no arguments, the value of len(sys.argv) is 1, so the comparison N>=2 on line 35 should be False and the debugger should step to the else statement on line 39.

## Actual behaviour
The debugger steps to line 36 as if N>=2 were True. It also incorrectly steps to line 42 after comparing N>=3.

## Steps to reproduce:
Debug the attached file and step into __main__ on line 33 with no arguments, then see if the debugger steps to line 36 or 39. All settings are default with a fresh install of vscode and the python extension.

I have spent many hours trying to isolate the minimal code required to demonstrate this bug. As far as I can tell, every line of uncommented code in this file is required to demonstrate the problem. Furthermore, adding print statements before or after the bug makes it disappear.

If further evidence of this bug is needed, then please ask and I will provide a .gif.

## Logs
Nothing appears in the Output panel. In the terminal, the following appears:
cd /home/username ; env /home/username/anaconda3/bin/python /home/username/.vscode/extensions/ms-python.python-2020.7.96456/pythonFiles/lib/python/debugpy/launcher 39939 -- /home/username/vscode_debuger_bug.py 
1

## Code
```python
import os
import sys
import time
import random
import jsonpickle
import numpy as np
import sqlalchemy as sa
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

Base = declarative_base()

def MyFunction():
	pass

class MyClassA(Base):
	__tablename__ = 'tableA'
	n = sa.Column(sa.BigInteger, primary_key=True)

class MyClassB(Base):
	__tablename__ = 'tableB'
	n = sa.Column(sa.BigInteger, primary_key=True)

class MyClassC(object):
	def __init__(self):
		pass

class MyClassD(object):
	def __init__(self):
		pass

if __name__ == "__main__":
	N = len(sys.argv)  # set breakpoint here and pass no input arguments

	if N >= 2:
		arg1 = sys.argv[1]  # the debugger gets here even though N=1
		print(arg1)
	else:
		arg1 = 'MyString'

	if N >= 3:
		arg2 = int(sys.argv[2])  # the debugger gets here even though N=1
	else:
		arg2 = int(0)

	print(N)  # still N=1
	# print(arg1)  # if you print this then it changes the debugger behavior above
```

**Comment by int19h** [comment]
Can you try setting `PYDEVD_USE_FRAME_EVAL=NO` in environment variables, and see if that helps? Since you're launching the program using the debugger, you should be able to set it via "env" in launch.json.

**Comment by dddvision** [comment]
Setting "env":{"PYDEVD_USE_FRAME_EVAL": "NO"} in launch.json solves the problem. Thank you!

Should I add this to all of my launch.json files until a bug fix is pushed out?

**Comment by int19h** [comment]
It would probably be easiest to just set it as a global environment variable - that way it'll also apply to "attach" sessions.

**Comment by dddvision** [comment]
I'm looking forward to a more permanent bug fix.

**Comment by int19h** [comment]
@fabioz, can you take a look? It might be a rare corner case, but changing behavior of running code like that is very concerning.

**Comment by fabioz** [comment]
Sure, I'll give priority to this issue.

**Comment by int19h** [comment]
The crucial requirement for the repro is Python 3.7, although I suspect this has more to do with us only shipping Cython binaries for that.

**Comment by fabioz** [comment]
Note: I'm able to reproduce this and I'm investigating it (took me a bit more than I expected today because I ended up having to reinstall my Linux VirtualBox image which became corrupted).

**Comment by fabioz** [comment]
The issue is related to the bytecode modification in the frame eval mode -- I'm still working on it.

**Comment by fabioz** [comment]
Note: just to give more feedback, I'm still working on this.

I've actually found more issues related to that on the frame eval mode as I started doing some more tests on this, so, I'm actually scrapping the code related to the bytecode rewrite and doing the bytecode rewrite using https://github.com/vstinner/bytecode, which should allow for a better API for bytecode manipulation.

I think I'll be able to finish it next week.

**Comment by marknelson** [comment]
I'm seeing the same problem, python 3.7, the environment variable fix resolves the problem.

**Comment by BraveDistribution** [comment]
This is still valid on build: 1.74.3

"PYDEVD_USE_FRAME_EVAL": "NO" doesn't work as a fix anymore.

**Comment by int19h** [comment]
Are you doing an attach, by chance? Putting stuff in "env" only works for launch, otherwise environment variable has to be set specifically for the process you're attaching to when it's started.

If that doesn't solve the problem, can you please file a new issue?
