### ISSUE TITLE
Interactive prompt

### ISSUE THREAD

**Issue by Hypernut** [microsoft/debugpy#347]
I would like the option of an interactive prompt after a debug run completes. Like when running a script with the "-i" parameter: "python.exe -i myscript.py"

I tried adding "-i" as an argument in the launch.json, but the parameter does not seem to work with the debugger, it causes multiple errors and the script does not run.

**Comment by int19h** [comment]
If you're adding the argument directly to "pythonPath" in launch.json, i.e. something like `"python -i"`, that won't work - it is treated as a path to the Python binary in its entirety, including any spaces etc, so those are not argument delimiters. 

To be able to do this with VSCode, you'll have to wait until we implement https://github.com/microsoft/debugpy/issues/305.
