### ISSUE TITLE
Importing opencv fails with "ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: cannot allocate memory in static TLS block"

### ISSUE THREAD

**Issue by emdioh** [microsoft/debugpy#350]
## Environment data

- debugpy version: 1.0.0b12
- OS and version: Ubuntu 20.04.1 LTS
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.2 - coming with the distro
- Python3-Opencv version: 4.2.0+dfsg-5
- Using VS Code or Visual Studio: VS Code

## Actual behavior
Debugging scripts that import opencv2 fail to run at "import cv2" statement
 
```
$python -m debugpy --listen 1234 -c "import cv2"

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/yolo/.local/lib/python3.8/site-packages/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/yolo/.local/lib/python3.8/site-packages/debugpy/server/cli.py", line 430, in main
    run()
  File "/home/yolo/.local/lib/python3.8/site-packages/debugpy/server/cli.py", line 330, in run_code
    eval(code, {})
  File "<string>", line 1, in <module>
ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: cannot allocate memory in static TLS block
```

## Expected  behavior

Import succeeds, the script can run under the debugger.

## Steps to reproduce:

1. install debugpy 1.0.0b12
2. python -m debugpy --listen 1234 -c "import cv2"

## Notes

Version 1.0.0b11 works.

**Comment by int19h** [comment]
This sounds like https://bugs.launchpad.net/ubuntu/+source/opencv/+bug/1890170 - from the various reports there, it looks like `cv2` might have some conflicts with other packages employing native code?

**Comment by emdioh** [comment]
I can't see any diff in the environment variables.
In the mean time, debugpy 1.0.0rc2 is out and the issue went away

**Comment by int19h** [comment]
Sounds like we accidentally fixed it.
