### ISSUE TITLE
Remote breakpoints are not triggered

### ISSUE THREAD

**Issue by glisignoli** [microsoft/debugpy#354]
## Environment data

- debugpy version: 1.0.0b12
- OS and version: Fedora 32
- Python version (& distribution if applicable, e.g. Anaconda): Python3.8
- Using VS Code or Visual Studio: VS Code

## Actual behavior

Remote breakpoints are not triggered when set with `breakpoint()` or setting points in VSCode.

## Expected  behavior

Breakpoints should be triggered

## Steps to reproduce:
1. Using the launch.json below, run `python` in the remoteRoot
2. Lunch VSCode Python debugger
3. Debugger successfully connects but does not trigger breakpoints

## Settings.json
```json
{
  "python.pythonPath": "venv/bin/python",
  "launch": {
    "configurations": [
      {
        "name": "FCReplay Local VM",
        "type": "python",
        "request": "attach",
        "connect": {
          "host": "192.168.1.88",
          "port": 5678
        },
        "pathMappings": [
                {
                    "localRoot": "${workspaceFolder}/fcreplay/",
                    "remoteRoot": "/home/fcrecorder/fcreplay/venv/lib/python3.8/site-packages/fcreplay-0.9-py3.8.egg/fcreplay",
                }
            ],
      }
    ],
    "compounds": []
  }
}
```

**Comment by int19h** [comment]
Since you're debugging a library installed into site-packages, you need to set `"justMyCode": false` - does that help?

**Comment by glisignoli** [comment]
Yep that worked! Thank you!
