### ISSUE TITLE
Descriptor getting called when mouse being hovered over an element while debugging...

### ISSUE THREAD

**Issue by PyGamer0** [microsoft/debugpy#355]
## Environment data

-   VS Code version: 1.47.3
-   Extension version: v2020.7.96456 for Python, v2020.7.4 for PyLance
-   OS and version: Windows 10
-   Python version: Standard Python Interpreter v3.8.3
-   Type of virtual environment used: N/A
-   Value of the `python.languageServer` setting: Pylance

## Expected behaviour

I have the following code:
```# Descriptor class
class Name:
    def __get__(self, instance, owner):
        print('Fetch...')
        return instance._name

    def __set__(self, instance, value):
        print('Change...')
        instance._name = value

    def __delete__(self, instance):
        print('Remove')
        del instance._name

# Now for the class that utilises the Descriptor
class Person:
    name = Name()
    def __init__(self, name):
        self._name = name

    def __str__(self):
        return str(self._name)

# Create instances
bob = Person('Bob Smith')
print(bob)
bob.name = 'Bob Ross'
print(bob)
del bob.name

print('-' * 20)

sue = Person('Sue Jones')
print(sue)
```
Where i have a breakpoint on the line where bob is initialised.
When I start debugging and hover over "Person", it should show some necessary information...

## Actual behaviour
It shows the necessary info (aka special variables etc) but it calls the print('Fetch...") as well...

## Steps to reproduce:

Paste the above code and place a breakpoint on line where 'bob = Person('Bob Smith')'
Start debugging the python file (with F5)
Hover the mouse over 'Person' on the breakpoint line...
'Fetch...' will be printed out..

**Comment by fabioz** [comment]
This is expected... the basic introspection done by the debugger goes along the lines of the code below:

```
rep_dict = {}
for d in dir(Person):
    rep_dict[d] = str(getattr(Person, d))
```

and that triggers that condition when it goes on to get `Person.name` (in fact, just doing `str(Person.name)` raises an exception in that code).

Usually a property should be protected with the code below (as is the case for the Python `property` builtin) to avoid an error in that case:

```
    def __get__(self, obj, obj_type):
        if obj is None:
            return self
        ....
```

**Comment by PyGamer0** [comment]
OK thanks
