### ISSUE TITLE
DLL load failes after update

### ISSUE THREAD

**Issue by Muerio** [microsoft/debugpy#356]
Import of FreeCAD failes after update to version 2020.6.91350.
Works with version 2020.6.90262.
Running the same code outside of VS Code also works.

Nothing else was changed/updated with the update of the python extension.

## Environment data

-   VS Code version: 1.46.1
-   Extension version (available under the Extensions sidebar): 2020.6.91350
-   OS and version: Windows 10 10.0.17763
-   Python version (& distribution if applicable, e.g. Anaconda): 3.6.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): None
-   Relevant/affected Python packages and their versions: None
-   Relevant/affected Python-related VS Code extensions and their versions: None
-   Value of the `python.languageServer` setting: Microsoft

## Expected behaviour

Import module without error.

## Actual behaviour

Module is not imported. Throws exception:
```
Exception has occurred: ImportError
DLL load failed: The specified procedure could not be found.
```

## Steps to reproduce:
The following code throws the ImportError exception when extension version 2020.6.91350 is used.
Doesn't throw any exception when used with previous version 2020.6.90262

```
import sys

# Append FreeCAD's bin/lib directory to sys.path
sys.path.append("C:\\Program Files\\FreeCAD 0.18\\bin")
sys.path.append("C:\\Program Files\\FreeCAD 0.18\\lib")

import FreeCAD as App
```

**Comment by fabioz** [comment]
I installed FreeCAD here and I couldn't reproduce this (i.e.: the import works for me with Python 3.6 with the debugger in place).

So, let's see if we can get some additional info to diagnose the issue:

1. Can you provide some logging from the debugger when you have that error?

i.e.:

* Open VS Code
* Select the command Extensions: Open Extensions Folder
* Locate the Python extension directory, typically of the form ms-python.python-2020.*.****
* In that directory ensure you do not have any debug*.log files, if you do, please delete them
* Go back into VS Code and modify your launch.json to add the setting "logToFile": true, see below:

```
"version": "0.2.0",
"configurations": [
    {
        "name": "Python: Current File (Integrated Terminal)",
        "type": "python",
        "request": "launch",
        "program": "${file}",
        "stopOnEntry": true,
        "console": "integratedTerminal",
        "logToFile": true
    },
```

* Start debugging
* When done, go back into the extension directory and upload the debug*.log files into this GitHub issue.

2. Can you provide some more info on your env in the case where it runs (in the command line) vs the case where it doesn't work (in the debugger)?

i.e.: Run the code below and provide the output in each case:

```
import sys

sys.path.append("C:\\Program Files\\FreeCAD 0.18\\bin")
sys.path.append("C:\\Program Files\\FreeCAD 0.18\\lib")

import os
for key, val in sorted(os.environ.items()):
    print(key)
    for v in val.split(os.pathsep):
        print('    %s' % v)  

print('\nsys.path:')
for v in sys.path:
    print('    %s' % (v,)) 
print('\n')

import FreeCAD as App
```

**Comment by Muerio** [comment]
Hello @fabioz 
> 1. Can you provide some logging from the debugger when you have that error?
See the following files:
[debugger.vscode_412d6c80-296d-4b30-a9cb-515dff48040a.log](https://github.com/microsoft/debugpy/files/5049313/debugger.vscode_412d6c80-296d-4b30-a9cb-515dff48040a.log)
[debugger.vscode_b89e05fc-b4d2-4ba5-9edb-4e650833aac5.log](https://github.com/microsoft/debugpy/files/5049314/debugger.vscode_b89e05fc-b4d2-4ba5-9edb-4e650833aac5.log)
[debugger.vscode_22d27e67-822a-48f3-82be-77ec3853fce2.log](https://github.com/microsoft/debugpy/files/5049315/debugger.vscode_22d27e67-822a-48f3-82be-77ec3853fce2.log)

Files have been generated with version 2020.6.91350 of the python extension.

 
> 2. Can you provide some more info on your env in the case where it runs (in the command line) vs the case where it doesn't work (in the debugger)?

For security reasons I can't just post all that information here (company policies). Please let me know if you're interested in specific details of the output from the provided code. I will try to get that information to you.
For now I can provide the output regarding python.

When running the code with the python extension (same version):
```
PYDEVD_DEBUG
    True
PYDEVD_DEBUG_FILE
    c:\Users\user.name\.vscode\extensions\ms-python.python-2020.6.91350/debugpy.pydevd.log
PYTHONIOENCODING
    UTF-8
PYTHONUNBUFFERED
    1
sys.path:
    c:\Users\user.name\Desktop\Python Test
    C:\Users\user.name\AppData\Local\Programs\Python\Python36\python36.zip
    C:\Users\user.name\AppData\Local\Programs\Python\Python36\DLLs
    C:\Users\user.name\AppData\Local\Programs\Python\Python36\lib
    C:\Users\user.name\AppData\Local\Programs\Python\Python36
    C:\Users\user.name\AppData\Roaming\Python\Python36\site-packages
    C:\Users\user.name\AppData\Roaming\Python\Python36\site-packages\win32
    C:\Users\user.name\AppData\Roaming\Python\Python36\site-packages\win32\lib
    C:\Users\user.name\AppData\Roaming\Python\Python36\site-packages\Pythonwin
    C:\Users\user.name\AppData\Local\Programs\Python\Python36\lib\site-packages
    C:\Program Files\FreeCAD 0.18\bin
    C:\Program Files\FreeCAD 0.18\lib
```

When running the code from command line/powershell:
```
sys.path:
    C:\Users\user.name\Desktop\Python Test
    C:\Users\user.name\AppData\Local\Programs\Python\Python36\python36.zip
    C:\Users\user.name\AppData\Local\Programs\Python\Python36\DLLs
    C:\Users\user.name\AppData\Local\Programs\Python\Python36\lib
    C:\Users\user.name\AppData\Local\Programs\Python\Python36
    C:\Users\user.name\AppData\Roaming\Python\Python36\site-packages
    C:\Users\user.name\AppData\Roaming\Python\Python36\site-packages\win32
    C:\Users\user.name\AppData\Roaming\Python\Python36\site-packages\win32\lib
    C:\Users\user.name\AppData\Roaming\Python\Python36\site-packages\Pythonwin
    C:\Users\user.name\AppData\Local\Programs\Python\Python36\lib\site-packages
    C:\Program Files\FreeCAD 0.18\bin
    C:\Program Files\FreeCAD 0.18\lib
```

**Comment by Muerio** [comment]
@fabioz Thank you for getting back to me on this topic. I had a look at the `PATH` variable and I noticed this:
When changing from version 2020.6.90262 (import working) to version 2020.6.91350 (import no longer works) the following line is added to the top of `PATH`:

`C:\Users\user.name\AppData\Local\Programs\Python\Python36\lib\site-packages\PyQt5\Qt\bin`

Since FreeCAD depends on Qt5 I'm guessing that this is the part which breaks the import of FreeCAD in my script.

Since I didn't change any settings or update anything between running your test script this change in `PATH` comes from updating the Python extension, right?

**Comment by int19h** [comment]
The extension doesn't tweak path, and doesn't really know anything about PyQt. More likely, whatever installed Python into that particular directory, also added it to PATH.

**Comment by Muerio** [comment]
Why doesn't the PyQt directory show in `PATH` when using version 2020.6.90262 of the extension?
Since I didn't change any settings the extension should always use the same Python installation, regardless of the extension's version.

**Comment by Muerio** [comment]
I updated `VSCode - Python` to the latest version 2020.8.103604, cloned debugpy and started going backwards from version v1.0.0.rc2.

> git checkout v1.0.0rc2
> git checkout v1.0.0rc1
> git checkout v1.0.0b12

PyQt directory is listed in the `PATH` variable and the import of FreeCAD fails.

> git checkout v1.0.0b11

PyQt directory is not listed in the `PATH` variable and the import of FreeCAD succeeds.

I then went back to version 2020.6.91350 of `VSCode -Python` where this problem started for me.
The behavior is exactly the same: v1.0.0b11 works, newer versions don't.

**Comment by int19h** [comment]
It might be indirectly related, yes! When this setting is "auto" (which is the default), pydevd tries to detect the correct PyQt version by import probing... and perhaps that breaks here because it finds a "wrong" version first? I'm not entirely sure why `PATH` is different, but perhaps it's the PyQt module in question that's adjusting it as it gets imported...

Anyway, can you try `"qt": "none"` in your config to see if that helps?

**Comment by Muerio** [comment]
That's it. Adding `"qt":"none"` to the config in launch.json removed PyQT from `PATH` and all four mentioned versions work now.
Obviously this also works when removing the `"debugAdapterPath"` from the config.

**Comment by int19h** [comment]
I think this might be related to #362, somehow. It's still not clear to me as to why having that entry in PATH makes a difference, regardless of where it comes from, but we might have to reconsider the default in light of these side effects.

**Comment by Muerio** [comment]
Let me know if you want me to test anything else in this context.

For now I added the option `"qt":"none"` to all my launch configs allowing me to use the latest python extension for VSCode when working with FreeCAD.

**Comment by int19h** [comment]
We'll track further investigation in #362.
