### ISSUE TITLE
Tests fail due to missing "process" event

### ISSUE THREAD

**Issue by int19h** [microsoft/debugpy#360]
This happens sporadically, and can affect any test for which the debuggee process exits quickly. In some cases, it can exit before the adapter gets a chance to report the "process" event. The adapter sends "terminated" in this case, but the tests always wait for "process" first, and so time out.

**Comment by judej** [comment]
Thank you for the report. Given our current resources are working on the Python 3.12 debugger, we will not be fixing this issues in the pre Python 3.12 debugger.
