### ISSUE TITLE
VS Code python breakpoints do not work in files under certain folder

### ISSUE THREAD

**Issue by gtzedaki** [microsoft/debugpy#363]
## Environment data
-   VS Code version: 1.47.3
-   Extension version (available under the Extensions sidebar): 2020.7.96456
-   OS and version: Windows_NT x64 10.0.19041
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7, Anaconda 
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Relevant/affected Python packages and their versions: XXX
-   Relevant/affected Python-related VS Code extensions and their versions: XXX
-   Value of the `python.languageServer` setting: XXX

## Expected behaviour
Python breakpoints do not work if the file is in my organizations OneDrive folder and bellow i.e.:
C:\Users\tzeda\OneDrive - ΙΔΡΥΜΑ ΤΕΧΝΟΛΟΓΙΑΣ ΚΑΙ ΕΡΕΥΝΑΣ\devel

## Actual behavior
Also, the same thing is happening both in my laptop and pc.
When adding in launch.json the "stopOnEntry": true property the execution halts as excepted.
Also the execution stops for Exceptions (if ticked) as excepted.

## Steps to reproduce:
1. Create a folder path tree similar to this: C:\Users\tzeda\OneDrive - ΙΔΡΥΜΑ ΤΕΧΝΟΛΟΓΙΑΣ ΚΑΙ ΕΡΕΥΝΑΣ\devel
Using a folder of similar length with greek characters has the same effect.
Using a folder of similar length with lating characters enables the debugger to stop at the breakpoint.
I have not changed anything on the launch.json.

**Comment by int19h** [comment]
Can you try getting the logs for it? To do so, you'll need to add the following to your launch.json:
```json5
"logToFile": true
```
Then look for files matching `debugpy*.log` in the folder where extension was installed. The one that would be particularly interesting in this case is `debugpy.pydevd*.log`.

**Comment by fabioz** [comment]
I wonder if this is the same as the ones below:

https://github.com/microsoft/debugpy/issues/361
https://github.com/microsoft/debugpy/issues/200

@gtzedaki can you try to do the change noted at: https://github.com/microsoft/debugpy/issues/361#issuecomment-672980974 and let me know if it works for you with that?

**Comment by gtzedaki** [comment]
> 
> 
> I wonder if this is the same as the ones below:
> 
> #361
> #200
> 
> @gtzedaki can you try to do the change noted at: [#361 (comment)](https://github.com/microsoft/debugpy/issues/361#issuecomment-672980974) and let me know if it works for you with that?

Yes that works, the breakpoints work now.
Also, it is interesting that adding breakpoint() command halts the execution even without the fix.

**Comment by fabioz** [comment]
Yes, `breakpoint()` will stop regardless of the path being case sensitive or not -- since you're asking to stop at a given place without specifying the case of the file at all ;)

I'm closing this since https://github.com/microsoft/debugpy/issues/200 is tracking it already.
