### ISSUE TITLE
Python terminal input() not recognized during debug - Linux & 2020.8.101144 extension

### ISSUE THREAD

**Issue by edcheet** [microsoft/debugpy#369]
## Environment data

-   VS Code version: 1.48.0
-   Extension version (available under the Extensions sidebar): 2020.8.101144
-   OS and version: Linux x64 4.15.0-54-generic
-   Python version (& distribution if applicable, e.g. Anaconda): 3.6.8
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Relevant/affected Python packages and their versions: N/A
-   Relevant/affected Python-related VS Code extensions and their versions: N/A
-   Value of the `python.languageServer` setting: jedi

[**NOTE**: If you suspect that your issue is related to the Microsoft Python Language Server (`python.languageServer: 'Microsoft'`), please download our new language server [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) from the VS Code marketplace to see if that fixes your issue]

## Expected behaviour

with standard debug configuration in launch.json:
{
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal"
        }
would expect to be able to enter input() (or raw_input in 2.7) text during debug

## Actual behaviour
instead:

debug input not recognized (but normal/as expected if script simply run in terminal - no debug, 3.6 or 2.7).
Also OK in VS Code in Windows 10 (1.48.0,  2020.8.101144, 3.7.0)

## Steps to reproduce:

s = input("Type something in and hit enter: ")
print("Here's what you typed: {0}".format(s))

If working 's' would be recognised as a string, instead not recognised (just get carriage return after typing, and then "NameError: name '…' is not defined" on breaking out of debug session.

Problem resolved with Python extension rollback from 2020.8.101144 to 2020.7.96456

**Comment by karthiknadig** [comment]
@edcheet Try adding `"redirectOutput": true` to your launch.json debug configuration, see https://github.com/microsoft/debugpy/issues/296#issuecomment-660285084. This was changed recently to allow better control of IO redirection.

**Comment by fabioz** [comment]
Closing this in favor of https://github.com/microsoft/debugpy/issues/370
