### ISSUE TITLE
Wiki addition: How does Jinja Template debugging work

### ISSUE THREAD

**Issue by rioj7** [microsoft/debugpy#381]
According to the `Debug configuration settings` there is a setting `"jinja"` that can be set in the `launch.json` file to debug Jinja Templates.

There is a Jinja2 debug plugin: `/debugpy/no_wheels/debugpy/_vendored/pydevd/pydevd_plugins/jinja2_debug.py`

How do I set a `Jinja2LineBreakpoint`?

An addition to the Wiki would be very helpful.

**Comment by rioj7** [comment]
I have a launch config with `"jinja": true,` and selected in the debug side panel

I can set a breakpoint in my jinja template `main.html.jinja` on a line with a for-loop.

I see the breakpoint in the VSC Breakpoint list.

When I now debug my simple script no breakpoint is hit.

```
from jinja2 import Template

with open('main.html.jinja') as f:
    tmpl = Template(f.read())
print (tmpl.render(
    variable = 'Value with <unsafe> data',
    item_list = [1, 2, 3, 4, 5, 6]))
```

The jinja file is read as text and converted to some data structure in the `jinja2.Template()` constructor and used in the `render()` method.

How will the breakpoint in the Jinja file be hit?

> breakpoint to a non-python file

How do I set this type of breakpoint?

Should I use a different method of converting/rendering the Jinja Template?

**Comment by int19h** [comment]
You need to ensure that your template knows which file it originated from (i.e. such that `Template.filename` has a meaningful value). I'm not entirely sure how - we mainly support this feature for Flask, which does it correctly - but it probably involves using the right loaders.

**Comment by rioj7** [comment]
Based on the comment from @int19h I searched a bit and found another way of loading Jinja Templates through the `jinja2.Environment`

using a FileSystemLoader
```
from jinja2 import Environment, FileSystemLoader
env = Environment(loader=FileSystemLoader('.'))
# env = Environment(loader=FileSystemLoader('templates'))
tmpl = env.get_template('example.html.jinja')

print (tmpl.render(
    variable = 'Value with <unsafe> data',
    item_list = [1, 2, 3, 4, 5, 6]))
```

using a PackageLoader
```
from jinja2 import Environment, PackageLoader
env = Environment(loader=PackageLoader('main', 'templates'))
tmpl = env.get_template('example.html.jinja')

print (tmpl.render(
    variable = 'Value with <unsafe> data',
    item_list = [1, 2, 3, 4, 5, 6]))
```

Because Jinja uses the module `pkg_resources` you must add an empty `main/__init__.py` if you use the PackageLoader. Or you get an Exception
```
"Can't perform this operation for unregistered loader type"
```

When you now set a breakpoint in the template and run the application the debugger stops in the template and you can step through with F10.

**Make sure the Language type of the template file is set to `Jinja`.** Otherwise you can't set breakpoints.

**Comment by int19h** [comment]
Thank you for sharing the recipe!
