### ISSUE TITLE
Python 3.9 support

### ISSUE THREAD

**Issue by fabioz** [microsoft/debugpy#384]
There was some preliminary effort to support 3.9, so, we know that the basics work, but features which require more internal knowledge still need more work.

i.e.:
- attach to process
- frame eval mode

Now that 3.9rc1 is out, this may be a good time to tackle it.

**Comment by fabioz** [comment]
@int19h @karthiknadig 

I'll start to take a look at this (since Python 3.9 is out already).

**Comment by int19h** [comment]
If there's anything that's not working, and that isn't captured by the debugpy test suite (last I checked it was passing on 3.9), can you file test issues for that?

**Comment by fabioz** [comment]
Sure:
https://github.com/microsoft/debugpy/issues/433
https://github.com/microsoft/debugpy/issues/434

If everything goes well I'll probably be able to add the related support until tomorrow.

**Comment by fabioz** [comment]
(note: I had really done some pre-work on Python 3.9, but compiled extensions are a bit trickier to keep up to date, so, I was waiting for the final release to put things in place)

**Comment by fabioz** [comment]
Actually, although I reported "[Test] Check attach to process in Python 3.9 #433", which should not be possible until https://github.com/microsoft/debugpy/pull/436 is integrated, I think we should actually test the attach to process already... (in which case that can be closed).
