### ISSUE TITLE
Support exception chains in debugger

### ISSUE THREAD

**Issue by CallumJHays** [microsoft/debugpy#391]
Hi, I may be doing something wrong, but it doesn't seem like the python debugger supports error chaining? For example:

![image](https://user-images.githubusercontent.com/13251689/91511427-f5c96d80-e922-11ea-8349-435418568bdd.png)
The only error information shown is the outer exception, losing track of the original cause.

Error chaining works if run without the debugger (in a terminal):
![image](https://user-images.githubusercontent.com/13251689/91511511-32956480-e923-11ea-9ab7-0805bb23805a.png)

Error Chaining (PEP 3134) Spec: https://www.python.org/dev/peps/pep-3134/

**Comment by theHamsta** [comment]
When I tried out debugpy with a custom debugger it return `ExceptionInfo` without any `innerExceptions`. Would be nice if this would be supported.
