### ISSUE TITLE
Breakpoints not hit in unit tests

### ISSUE THREAD

**Issue by bSolt** [microsoft/debugpy#392]
Issue Type: <b>Bug</b>

The python debugger used to work for debugging pytest unit tests, but now will not stop on breakpoints, exceptions, or when using "stopOnEntry"

I have the following entry in my `launch.json`:

```json
{
    "name": "Python: Test",
    "type": "python",
    "request": "test",
    "console": "integratedTerminal",
    "envFile": "${workspaceFolder}/.env",
    "justMyCode": false,
    "stopOnEntry": false,
    "env": {
        "DEBUG": "true",
        "CF_DIET": "dev"
    }
}
```

And these settings:

```
 "python.testing.pytestArgs": [],
 "python.testing.unittestEnabled": false,
 "python.testing.nosetestsEnabled": false,
 "python.testing.pytestEnabled": true,
```

Extension version: 2020.8.105045
VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:56:10.074Z)
OS version: Linux x64 3.10.0-1127.13.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz (4 x 2399)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.51GB (0.58GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|50%|
|DESKTOP_SESSION|mate|
|XDG_CURRENT_DESKTOP|MATE|
|XDG_SESSION_DESKTOP|mate|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by int19h** [comment]
Does it break if you use Pause on the debugger toolbar, or the built-in `breakpoint()` function?

If so, is there anything unusual about the filenames that you see in the editor tabs and in the Call Stack pane when it breaks?

**Comment by bSolt** [comment]
Sorry, missed the questions. I am able to pause it but only before my local code is run. Here's a screenshot of the call stack pane, which I don't think is unusual but not really sure what to look for.

![Screenshot at 2020-09-11 10-34-11](https://user-images.githubusercontent.com/36494925/92950827-97b88200-f41a-11ea-80b3-40b374c6a520.png)

I also figured out it does have something to do with this specific project, on another project I am able to hit by breakpoints. I am using the red circle breakpoints, I am unaware of how to use the built-in `breakpoint` function

**Comment by bSolt** [comment]
> @bSolt Here is an example of calling `breakpoint()` function:
> 
> ```
> def foo():
>     breakpoint()
>     print('here')        # Debugger stops here
> 
> foo()
> ```
> 
> This assumes you are using Python 3.7 or greater.
> 
> For older versions of python, you can do this, and it is compatible with all versions of python (including 3.7 or greater).
> 
> ```
> import debugpy
> def foo():
>     debugpy.breakpoint()
>     print('here')        # Debugger stops here
> 
> foo()
> ```
> 
> Note: you don;t have to install debugpy if you are running locally (on the same machine as the python-extension).

Thanks for the quick tutorial, that's very straightforward. Running this particular project on 3.6.3 so I added

```python
import debugpy
debugpy.breakpoint()
```

But it doesn't stop either. How else can I help diagnose this?

**Comment by karthiknadig** [comment]
I see. Try this:
```js
{
    "name": "Python: Test",
    "type": "python",
    "request": "test",
    "console": "integratedTerminal",
    "envFile": "${workspaceFolder}/.env",
    "justMyCode": false,
    "stopOnEntry": false,
    "env": {
        "DEBUG": "true",
        "CF_DIET": "dev"
    },
    "logToFile": true  // <--- this will enable logging.
}
```
You should be able to find logs in the extension folder: `~/.vscode/extensions/ms-python.python*`. You should find files named debugpy-*.log and pydevd*.log. there will be multiple. Share them all.

**Comment by karthiknadig** [comment]
Also, Share the list of extensions installed. Just do `ls` in the `~/.vscode/extensions` folder.

**Comment by bSolt** [comment]
List of extensions:
```
$ ls ~/.vscode/extensions
albymor.increment-selection-0.2.0
alexkrechik.cucumberautocomplete-2.15.0
davidanson.vscode-markdownlint-0.36.3
eamodio.gitlens-10.2.2
github.vscode-pull-request-github-0.15.0
hediet.vscode-drawio-0.7.2
ms-azuretools.vscode-docker-1.5.0
ms-mssql.mssql-1.9.0
ms-python.python-2020.8.106424
ms-python.python-2020.8.108011
mtxr.sqltools-0.23.0
shaharkazaz.git-merger-0.4.1
streetsidesoftware.code-spell-checker-1.9.0
yzhang.markdown-all-in-one-3.3.0
```

And here are the log files when I tried to run a single unit test with the breakpoint on (test_orchestration.py:48 is where I'm expecting it to stop):
[debugger.vscode_1e8eec5f-be62-4ccb-aa5e-0a008e75cd2e.log](https://github.com/microsoft/debugpy/files/5210661/debugger.vscode_1e8eec5f-be62-4ccb-aa5e-0a008e75cd2e.log)
[debugpy.adapter-10606.log](https://github.com/microsoft/debugpy/files/5210662/debugpy.adapter-10606.log)
[debugpy.launcher-10669.log](https://github.com/microsoft/debugpy/files/5210663/debugpy.launcher-10669.log)
[debugpy.pydevd.10675.log](https://github.com/microsoft/debugpy/files/5210664/debugpy.pydevd.10675.log)
[debugpy.server-10675.log](https://github.com/microsoft/debugpy/files/5210665/debugpy.server-10675.log)

**Comment by karthiknadig** [comment]
Looks like it does not get to the breakpoint at all. Seems like you hit this error, before it gets to the breakpoint.
```
AttributeError: <module 'lodges.jobs.task_classes.orchestration' from '/home/bsolt/repos/loadable-orchestration/lodges/jobs/task_classes/orchestration.py'> does not have the attribute 'get_job_by_id'
```

You might have to use the `Raised` exception to catch these at the moment. `uncaught` is not enough because `pytest` catches all exceptions (so we can identify the above exception as uncaught). 
![image](https://user-images.githubusercontent.com/3840081/92957024-bae43100-f41c-11ea-80ad-99030af2b891.png)

Note: The debugger has a feature that detects these scenarios (user uncaught), but we have not enabled that yet.

**Comment by bSolt** [comment]
Oh that does make sense... Well I'm glad that the "User Uncaught" feature would have alleviated my pain. The issue can probably be closed but I'll leave that up to you.

**Comment by karthiknadig** [comment]
Closing this against user-unhandled, since this is closely related:
https://github.com/microsoft/debugpy/issues/275
https://github.com/microsoft/debugpy/issues/364

**Comment by bSolt** [comment]
@karthiknadig, can you take a look at another instance for me? I'm pretty sure this instance is a bug, because the execution fails a few lines into the test and I have put debug lines on each line of the test I am running, which seem to be ignored. Specifically, the line which pytest is highlighting here is test_flight_rule_check.py:22, which the execution should have been stopped on. The new log files are attached. Should I maybe open a new issue for this?


[debugpy.pydevd.7820.log](https://github.com/microsoft/debugpy/files/5220499/debugpy.pydevd.7820.log)
[debugpy.server-7820.log](https://github.com/microsoft/debugpy/files/5220500/debugpy.server-7820.log)
[debugger.vscode_fd38b750-9887-4eb7-b2ab-30c875f8d888.log](https://github.com/microsoft/debugpy/files/5220496/debugger.vscode_fd38b750-9887-4eb7-b2ab-30c875f8d888.log)
[debugpy.adapter-7804.log](https://github.com/microsoft/debugpy/files/5220497/debugpy.adapter-7804.log)
[debugpy.launcher-7814.log](https://github.com/microsoft/debugpy/files/5220498/debugpy.launcher-7814.log)

**Comment by bSolt** [comment]
In this case it seems like I am not about to pause using the toolbar.

**Comment by bSolt** [comment]
Oh interesting, but when I try to use the inline breakpoint (`debugpy.breakpoint()`) it is able to pause execution!

**Comment by bSolt** [comment]
Another note: once the inline breakpoint is caught, then you can continue as usual to hit subsequent breakpoints invoked via the UI without issue.

**Comment by fabioz** [comment]
@bSolt, I'm not exactly sure what's the issue... if you still can reproduce it, can you create a new issue providing some sample code to reproduce as well as the related logs?

**Comment by aminechm** [comment]
what worked for me was clearing  all `.pyc` and `__pycache__` recursively using : https://gist.github.com/hbsdev/a17deea814bc10197285

in both my local workspace and equivalent Docker container
