### ISSUE TITLE
Debugger works with one Python interpreter, but not with another?

### ISSUE THREAD

**Issue by ZenonH** [microsoft/debugpy#394]
## Environment data

-   VS Code version: 1.48.2
-   Extension version (available under the Extensions sidebar): XXX
-   OS and version: Windows 10 latest update installed
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8 64-bit, 3.8.5 34-bit,  Debugger works with 34-bit, not with 64-bit
-  

## Expected behaviour

In debug mode stops at breakpoints works with 34-bt

## Actual behaviour
with 64-bit Python code runs thru all breakpoints

XXX

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by karthiknadig** [comment]
@ZenonH Please share the logs if possible. You can do this by setting `logToFile: true` in the launch.json.

**Comment by fabioz** [comment]
Closing since logs weren't provided (@ZenonH, please feel free to reopen if you're able to provide the logs).
