### ISSUE TITLE
Cannot unset environment variables in launch configuration

### ISSUE THREAD

**Issue by brechtm** [microsoft/debugpy#396]
The [Launch.json attributes](https://code.visualstudio.com/docs/editor/debugging#_launchjson-attributes) section of the VSCode documentation mentions that the `env` atttribute of a launch configuration supports unsetting variables by using the `null` value.

This doesn't seem to work for Python launch configurations:

* it doesn't undefine variables when _running_ a program
* an error dialog is shown when _debugging_ a program (or test in my case): 
    > Invalid message: "env"["ELECTRON_RUN_AS_NODE"] must be str

## Environment data

-   VS Code version: 1.48.2
-   Extension version (available under the Extensions sidebar): 2020.8.105045
-   OS and version: macOS High Sierra 10.13.6
-   Python version (& distribution if applicable, e.g. Anaconda): CPython 3.8.3
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Value of the `python.languageServer` setting: (User) Microsoft

**Comment by int19h** [comment]
Yep, it's not supported at the moment. #93 is tracking this.

**Comment by brechtm** [comment]
Note that this doesn't work when running (versus debugging) either. I don't know if that is also handled by debugpy or not.

**Comment by int19h** [comment]
It does - running without debugging is debugpy running with `"noDebug": true`, and environment handling is the same in that case.

**Comment by brechtm** [comment]
Thanks for the clarification. I asked because I don't get the `Invalid message: "env"["ELECTRON_RUN_AS_NODE"] must be str` error when running (no debug).

I had a go at implementing this, but I didn't get far, unfortunately...
