### ISSUE TITLE
Debug runs thru breakpoint

### ISSUE THREAD

**Issue by ZenonH** [microsoft/debugpy#398]
Windows 10 OS
Installed Visual Studio code
Installed python 3.7 64-bit
Installed Microsoft Python debugging, linting extension
Debug runs thru breakpoint, no error messages
Code x=1, y=1, print(x+y) : set breakpoint on print.

Extension version: 2020.8.105369
VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.18363

|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.82GB (6.83GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

**Comment by karthiknadig** [comment]
@ZenonH Please share the logs. You can turn on logging by setting `logToFile: true`.

**Comment by fabioz** [comment]
Closing since logs weren't provided (@ZenonH, please feel free to reopen if you're able to provide the logs).
