### ISSUE TITLE
Can't debug Python source code (for a Jupyter kernel launched indirectly by `jupyter notebook`) with `attach` configuration in VS Code

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/debugpy#411]
## Environment data

- debugpy version: 1.0.0rc2 (run `import debugpy; print(debugpy.__version__)` if uncertain)
- OS and version: Windows_NT x64 10.0.19041
- Python version (& distribution if applicable, e.g. Anaconda): 64 bit 3.8.5 from python.org
- Using VS Code or Visual Studio: VS Code 1.49.0 stable

## Actual behavior

Debug configuration defined in launch.json which attaches to a running process results in breakpoints set in VS Code not being hit.

## Expected  behavior

Breakpoints should be respected.

## Steps to reproduce:
0. Install `jupyter`.
1. Clone https://github.com/vors/jupyter-powershell
2. Set some breakpoints in the `do_execute` method in the powershell_kernel/kernel.py module from the repo source code and install the kernel module locally by running `python -m powershell_kernel.install --powershell-command pwsh`
3. In the integrated terminal, run `python -m debugpy --listen 5678 --wait-for-client -m jupyter notebook`
4. Run the debugger with the following launch configuration:
```
        {
            "name": "Python: Remote Attach",
            "type": "python",
            "request": "attach",
            "connect": {
                "host": "localhost",
                "port": 5678
            },
            "logToFile": true,
            "justMyCode": false,
            "pathMappings": []
        }
```
5. The jupyter notebook interface should open in your browser. Now create a new Jupyter notebook with a PowerShell kernel, and execute a cell
6. Execution proceeds without hitting the breakpoints set in VS Code

Note also that this workaround works: https://gist.github.com/joyceerhl/f8226c2e2bc83f6ecebd459466acbd53 and this workaround is based on our documentation: https://code.visualstudio.com/docs/python/debugging#_local-script-debugging

Attaching some logs per @karthiknadig 's request. debugpy.adapter-20028.log and debugpy.server-1656.log were generated from the workaround described in the gist above. debugpy.server-19160.log and debugpy.adapter-19260.log were generated from the repro steps above (which result in my breakpoints not being hit). 

[debugpy.server-1656.log](https://github.com/microsoft/debugpy/files/5241794/debugpy.server-1656.log)
[debugpy.server-19160.log](https://github.com/microsoft/debugpy/files/5241795/debugpy.server-19160.log)
[debugpy.adapter-18260.log](https://github.com/microsoft/debugpy/files/5241796/debugpy.adapter-18260.log)
[debugpy.adapter-20028.log](https://github.com/microsoft/debugpy/files/5241797/debugpy.adapter-20028.log)

**Comment by fabioz** [comment]
The logs seem to be missing the `.pydevd.<pid>.log` files... can you include them?

-- I believe they should be generated by default, but if they are not in this case, please set the `PYDEVD_DEBUG_FILE` environment variable to point to a file (i.e.: `set PYDEVD_DEBUG_FILE=c:/temp/pydevd.log`).

**Comment by joyceerhl** [comment]
@fabioz sorry, just saw this. They weren't generated by default, and after setting the `PYDEVD_DEBUG_FILE` env var and rerunning both the repro steps and my workaround, nothing was logged to the pydevd logfile (i.e. it's empty). LMK if you would like to debug this together.

**Comment by int19h** [comment]
I wonder if it has to do with the corresponding thread already running by the time `debugpy.listen()` is invoked. We try to patch existing threads, but this isn't 100% reliable, especially not for frames that are already running.

**Comment by fabioz** [comment]
Sorry about the delay (it seems I missed the response somehow).

Related to the logs, another thing missing is the `PYDEVD_DEBUG=1` to actually get verbose output from the debugger (so, you need to set that as well as the `PYDEVD_DEBUG_FILE`).

Also, the `logToFile` probably doesn't need to be set in the launch configuration in this case (it may end up overriding the environment variable settings).

@joyceerhl are you still interested in tracking this? If so, please check if setting those environment variables does produce a log for you (and attach it to this issue if it does).

**Comment by judej** [comment]
Closing stale issue. Please reopen if needed
