### ISSUE TITLE
Reading from stdin whilst debugging

### ISSUE THREAD

**Issue by mpette200** [microsoft/debugpy#413]
Issue Type: <b>Bug</b>

On windows subsystem for linux, running python from a conda environment.
Steps:
- Create a python script that reads from `sys.stdin.read()` into a variable.
- From menu select: Run -> Start Debugging.
- When the script is waiting for input from the stdin, type 'hello world' + ctrl D to signify end-of-line.
- Expected result is that 'hello world' should be read into the variable.
- On the 1st run of the debugger the actual result is that '...../miniconda3/bin/activate\nconda activate\nhello world' is read into the variable. 
- However, on 2nd and subsequent runs the correct result happens, so on the 2nd run 'hello world' is correctly read into the variable.

![stdin_unwanted](https://user-images.githubusercontent.com/19962594/93667082-0f218d80-fa7b-11ea-8c01-81c1db59d823.png)

Extension version: 2020.8.109390
VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:27:51.792Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1500X Quad-Core Processor           (8 x 3493)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (10.03GB free)|
|Process Argv|--crash-reporter-id ca01eece-4c50-4f38-999f-25793d2dadf7|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|AMD Ryzen 5 1500X Quad-Core Processor           (8 x 3500)|
|Memory (System)|15.94GB (10.03GB free)|
|VM|0%|
</details>

**Comment by int19h** [comment]
This is not an issue with the debugger as such. It's caused by the VSCode Python extension trying to activate conda in the terminal in which it's running your app - it's meant to send the string to the shell prompt, but there's an inherent race condition there.

It's a known issue in the extension. For now, the workaround is to disable automatic activation, manually activate your Conda environments from the terminal, and then launch VSCode from said terminal.
