### ISSUE TITLE
Debugger does not attach with Visual Code

### ISSUE THREAD

**Issue by jugma** [microsoft/debugpy#418]
MAC OS: 10.15.6
Visual Code: 1.49.0
debugpy: 1.0.0rc2

**launch.json**
```json5
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Remote Attach",
            "type": "python",
            "request": "attach",
            "logToFile": true,
            "justMyCode": false,
            "connect": {
                "host": "localhost",
                "port": 8028
            },
            "pathMappings": [
                {
                    "localRoot": "${workspaceFolder}",
                    "remoteRoot": "${workspaceFolder}"
                }
            ]
        }
    ]
}
```

**I have the following in my python code**
```py
debugpy.log_to('../../logs')
debugpy.listen(8028)
debugpy.wait_for_client()
debugpy.breakpoint()
```

**Visual Code log**
[debugger.vscode_b34013f8-ee72-411b-93f7-e93613a2aedb.log](https://github.com/microsoft/debugpy/files/5261318/debugger.vscode_b34013f8-ee72-411b-93f7-e93613a2aedb.log)

**Docker run command**
```sh
docker run --name faber --rm -it \
	-p 0.0.0.0:8020-8027:8020-8027 -p 8028:8028 \
	.......
```

There are no debugpy logs generated. Please help

**Comment by jugma** [comment]
I could get the debugpy logs to show-up. Below are the 2 files:
[debugpy.adapter-44.log](https://github.com/microsoft/debugpy/files/5263988/debugpy.adapter-44.log)
[debugpy.server-6.log](https://github.com/microsoft/debugpy/files/5263989/debugpy.server-6.log)

**Comment by int19h** [comment]
What exactly happens when you try to connect? Judging by debugpy logs, the debug server has started successfully and is waiting for incoming connections, but it never gets any.

Unrelated, but that path mapping set up looks wrong to me, unless your remote filesystem is identical to local (in which case it's redundant).

**Comment by jugma** [comment]
In Visual Code the debugger tries to connect but returns almost right away. I see some errors in the Visual Code log file. I am wondering if these errors might have something to do with the debugger not attaching.

**Comment by jugma** [comment]
The Visual Studio debugger tries to connect but cannot and exits almost right away. Also I see some errors in the Visual Studio log file. Do you think these error messages may be preventing the debugger from attaching?

**Comment by int19h** [comment]
VSCode-side log is not very informative, but it looks like it just can't connect to the socket? I suspect this has something to do with Docker port mapping - not an expert on that, sorry.

You can try to check it manually by connecting to debugpy port from your dev box using telnet or netcat. If it can connect, and spews out some JSON, then the port is mapped correctly.

**Comment by cgarciae** [comment]
Same for me. `ptvsd` works however.

**Comment by jugma** [comment]
Below is the output when telnet to port 8028.
telnet localhost 5678
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Connection closed by foreign host.

As show above the telnet session terminates without any JSON output

**Comment by jugma** [comment]
I meant

telnet localhost 8028

**Comment by jugma** [comment]
I got ptvsd to work as well

**Comment by jjedele** [comment]
Have the same effect @jugma describes - ptvsd works as well.

**Comment by jjedele** [comment]
Ok, what helps for me with `debugpy==1.2.0` is listening on `0.0.0.0`. Don't understand why it is necessary yet, but might be related to the way Docker handles network.

**Comment by IliyVas** [comment]
@jjedele thanks for advice. 

`debugpy.listen(("0.0.0.0", 5678))` instead of debugpy.listen(5678) solved problem for me.

**Comment by int19h** [comment]
It looks like this is, ultimately, an issue with Docker port mapping, since telnet also doesn't work as it should in this case.
