### ISSUE TITLE
Duplicated tabs for same file when connecting through SSH

### ISSUE THREAD

**Issue by WurmD** [microsoft/debugpy#421]
Issue Type: <b>Bug</b>

**Expected behavior:** no duplicated tabs opened, for a same file, when debugging

**Steps to reproduce:**
1. Open VSCode remote session through "Remote - SSH" extension
2. open workspace
3. set launch configuration thusly

```
            {
                "name": "util.py",
                "type": "python",
                "request": "launch",
                "program": "util.py",
                "console": "integratedTerminal"
            },
```	

(**Note:** issue not reproducible when running "Python: Current File" default configuration)

```	
            {
                "name": "Python: Current File",
                "type": "python",
                "request": "launch",
                "program": "${file}",
                "console": "integratedTerminal"
            },
```	

4. open file, shows as /home/dario/centerNet-deep-sort/util.py
5. set breakpoint
6. run	

**Actual behavior:**
	execution stops at breakpoint, but new tab opened of same file showing as in /mnt/home/centerNet-deep-sort/util.py (and breakpoint only visible in /home/centerNet-deep-sort/util.py file)
	

Extension version: 2020.9.111407
VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:27:51.792Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.15.0-117-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (16.67GB free)|
|Process Argv|--crash-reporter-id ff587ffc-1e1c-4420-a3e0-f2a2ab6938a5|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 5.9.40.75|
|OS|Linux x64 4.15.0-117-generic|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3790)|
|Memory (System)|62.73GB (0.70GB free)|
|VM|0%|
</details>

**Comment by fabioz** [comment]
@WurmD can you provide the logs for this?

To get the logs, set `"logToFile": true` in the launch.

I'm not sure where it puts them in the case for the ssh connection (when running in the terminal the path should appear when `DEBUGPY_LOG_DIR` is set, or you can print it from the program with: `print(os.environ['DEBUGPY_LOG_DIR'])`).

**Comment by karthiknadig** [comment]
It should put them under `~/.vscode-server/extensions/ms-python.python*/`, you can also find the path the extension from Output > Python, and use that to navigate to the right location.

**Comment by WurmD** [comment]
Here goes

[debugger.vscode_97437db6-6649-47bc-b855-8660f75a15ed.log](https://github.com/microsoft/debugpy/files/5278768/debugger.vscode_97437db6-6649-47bc-b855-8660f75a15ed.log)
[debugpy.adapter-20104.log](https://github.com/microsoft/debugpy/files/5278769/debugpy.adapter-20104.log)
[debugpy.launcher-20114.log](https://github.com/microsoft/debugpy/files/5278770/debugpy.launcher-20114.log)
[debugpy.pydevd.20120.log](https://github.com/microsoft/debugpy/files/5278771/debugpy.pydevd.20120.log)
[debugpy.server-20120.log](https://github.com/microsoft/debugpy/files/5278772/debugpy.server-20120.log)

**Comment by fabioz** [comment]
The issue appears to be that the debugger currently resolves symlinks and considers a canonical version as it's possible to see that the debugger does:

```
Request for breakpoint in: /home/dario/nethra-scripts/download_images_from_json.py line: 42
Breakpoint (after path/source mapping) in: /mnt/home/dario/nethra-scripts/download_images_from_json.py line: 42
```

The latest master version actually had some fixes related on how this is handled internally so that internally we stop in a canonical place (even with symlinks resolved) but it reports the proper absolute (unresolved) path to the outside world.

Can you check with the current master to see if it fixes it for you?

It's something as:
```
git clone https://github.com/microsoft/debugpy.git
cd debugpy
pwd
```

Then, in your launch config add:

`"debugAdapterPath": "<pwd path>/src/debugpy/adapter"` 

-- Note: I haven't tested if this works in the SSH case, so, if you have any issues there, please report back.

If it still doesn't work, can you provide the logs you have with the master version?

**Comment by WurmD** [comment]
hmm, debugger won't start

[debugger.vscode_6264d242-cd95-4522-97fc-4659d85b57ff.log](https://github.com/microsoft/debugpy/files/5282673/debugger.vscode_6264d242-cd95-4522-97fc-4659d85b57ff.log)

**Comment by fabioz** [comment]
Humm, I think that another option could be installing the debugger from master in the python interpreter you want to use:

i.e.: something as:

`pip install https://github.com/microsoft/debugpy/archive/master.zip`

(in this case the `debugAdapterPath` should not be needed)

**Comment by int19h** [comment]
@WurmD Note that "debugAdapterPath" must be pointing at the `debugpy.adapter` module, not at the root of the repo. In your case, it should be:
```json5
"debugAdapterPath": "/home/dario/debugpy/src/debugpy/adapter",
```

**Comment by WurmD** [comment]
K, ran it again, duplicate file tab still opened

[debugpy.adapter-15966.log](https://github.com/microsoft/debugpy/files/5283225/debugpy.adapter-15966.log)
[debugpy.launcher-15994.log](https://github.com/microsoft/debugpy/files/5283226/debugpy.launcher-15994.log)
[debugpy.pydevd.16004.log](https://github.com/microsoft/debugpy/files/5283228/debugpy.pydevd.16004.log)
[debugpy.server-16004.log](https://github.com/microsoft/debugpy/files/5283229/debugpy.server-16004.log)
[debugger.vscode_f1aa6e08-32af-4d21-b3f9-359a43687d50.log](https://github.com/microsoft/debugpy/files/5283230/debugger.vscode_f1aa6e08-32af-4d21-b3f9-359a43687d50.log)

**Comment by fabioz** [comment]
It seems that the issue is that the `util.py` being executed doesn't have the full path frame and resolves to the working directory (that's actually `/mnt/home/dario/centerNet-deep-sort` and not `/home/dario/centerNet-deep-sort`).

i.e.: The logs shows the stack as:
```
  Stack: util.py, <module>, 4
  Stack: /home/dario/anaconda3/envs/CenterNet/lib/python3.6/runpy.py, _run_code, 85
  Stack: /home/dario/anaconda3/envs/CenterNet/lib/python3.6/runpy.py, _run_module_code, 96
  ....
```
So, it's possible to see that `util.py` doesn't really have the full path.

And it also says:

`File traced: /mnt/home/dario/centerNet-deep-sort/util.py`.

So, I think that you should have some `pathMapping` set to make that translation.

Something like:

```
            "pathMappings": [
                {
                    "localRoot": "/home/",
                    "remoteRoot": "/mnt/home/"
                }
            ],
```

(that should be added to the launch configuration)

**Comment by WurmD** [comment]
This is what was set 

```
	"folders": [
		{
			"path": "."
		}
	],
```

If the following is set

```
    "folders": [
        {
            "path": "../../../mnt/home/dario/centerNet-deep-sort"
        }
    ],
```

all files appear as under /mnt/home/... and the problem of duplicated tabs does not manifest

**Comment by fabioz** [comment]
Great ;)
