### ISSUE TITLE
General project debug in docker container doesn't start

### ISSUE THREAD

**Issue by robertsk50** [microsoft/debugpy#423]
## Environment data

-   VS Code version: 1.49.2 with WSL2
-   Extension version (available under the Extensions sidebar): v2020.9.111407
-   OS and version: Windows 10 version 20H2
-   Python version (& distribution if applicable, e.g. Anaconda): 3.6.8
-   Type of virtual environment used: I've tried both system python and conda
-   Relevant/affected Python-related VS Code extensions and their versions: Remote - Containers (v0.140.1), Remote - WSL (v0.44.5), Docker (v1.6.0)
-   Value of the `python.languageServer` setting: Jedi

## Expected behaviour

When I start a debug session of the "Docker: Python - General" configuration I expect the debugger to connect and stop on my set breakpoint.

## Actual behaviour

When I start the debug session, the docker container is built, the debug toolbar appears, but the session hangs, presumably waiting for the debugger to connect. There is no "Terminal->Python Debug Console" available to select. And the "Output->Python" window is empty. I thought this was related to [this ticket](https://github.com/microsoft/vscode-docker/issues/2313), but adding the "debugAdapterHost" entry to my launch configuration did not help.

## Steps to reproduce:

1. From wsl2, open VScode in an empty directory. 
2. Create simple test.py script.
3. Run the "Docker: Add Docker Files to Workspace" command and select "Python: General", select test.py, and don't add Docker compose files.
4. Press F5 to debug "Docker: Python - General" launch configuration.

## Logs

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel 
</summary>

<p>

The output is empty.

</p>
</details>

**Comment by fabioz** [comment]
I'm not really sure what the docker run does there (that's mostly out of the scope of `debugpy` itself -- what I can say is that if you do have a connection up, the debugger should work, but it's up to extension that handles that to set things up properly)... having said that, maybe https://github.com/microsoft/debugpy/issues/418 has some hints for doing a remote attach with docker.
