### ISSUE TITLE
GitHub Release, but isn't a release?

### ISSUE THREAD

**Issue by frenck** [microsoft/debugpy#428]
Follow up of issue #427

## Environment data

- debugpy version: 1.0.0
- OS and version:
- Python version (& distribution if applicable, e.g. Anaconda): 
- Using VS Code or Visual Studio:

## Actual behavior

In issue #427 I raised the release was missing on PyPI, which was closed and I was told it was invalid, as there is not release yet.

Hence, I open this issue. According to GitHub there is a stable release, which isn't true according to this response in #427: https://github.com/microsoft/debugpy/issues/427#issuecomment-702358979

> @int19h: That's because it's not actually released yet - the commit that's tagged as v1.0.0 is the one that will become the release, but it's still in process (we have to tag it before we build it, because the version number in the build comes from the tag). It's expected to be published by the end of this week.

## Expected  behavior

I expect a release on GitHub to be a release, especially when it is marked a non-prerelease as well:

![image](https://user-images.githubusercontent.com/195327/94959029-c80eb000-04f0-11eb-8a57-b52a6fa0b20e.png)

The previous issue was closed, but it talks about a tag, not release. Those are 2 different things in the GitHub world.

## Steps to reproduce:

Browse to: <https://github.com/microsoft/debugpy/releases/tag/v1.0.0>

**Comment by int19h** [comment]
We are not going to change the release process in the middle of an ongoing release. It should be considered released when it shows up on PyPI. Normally, the gap between the two is less than 24 hours, but not this time, due to some technical issues. We'll revisit this for future releases to avoid such disparities..
