### ISSUE TITLE
Debugging highlights the incorrect line of code at times

### ISSUE THREAD

**Issue by dxkaufman** [microsoft/debugpy#429]
## Environment data

-   VS Code version: 1.49.2
-   Extension version (available under the Extensions sidebar): v2020.9.112786
-   OS and version: Mac OS 10.14.6
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.7.5 (default, Nov  1 2019, 02:16:32) 
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Relevant/affected Python packages and their versions: (not aware that any of these are related, but this is the complete pip freeze list):
```
astroid==2.4.2
azure-common==1.1.25
azure-core==1.8.1
azure-functions==1.3.0
azure-storage-blob==1.5.0
azure-storage-common==1.4.2
azure-storage-queue==12.1.3
cachetools==4.1.1
certifi==2020.6.20
cffi==1.14.0
chardet==3.0.4
cryptography==2.9.2
google-auth==1.18.0
google-auth-oauthlib==0.4.1
gspread==3.6.0
httplib2==0.18.1
idna==2.10
isodate==0.6.0
isort==4.3.21
lazy-object-proxy==1.4.3
mccabe==0.6.1
msrest==0.6.19
numpy==1.19.0
oauth2client==4.1.3
oauthlib==3.1.0
pandas==1.1.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
pycryptodome==3.9.8
pylint==2.5.3
pyodbc==4.0.30
python-dateutil==2.8.1
pytz==2020.1
requests==2.24.0
requests-oauthlib==1.3.0
rsa==4.6
six==1.15.0
slack==0.0.2
SQLAlchemy==1.3.18
toml==0.10.1
typed-ast==1.4.1
urllib3==1.25.9
wrapt==1.12.1
```
-   Relevant/affected Python-related VS Code extensions and their versions: 
Azure Functions 0.24.1, Azure App Service 0.19.0, Azure Storage 0.10.0, Pylance 2020.9.7
-   Value of the `python.languageServer` setting: not aware that I'm using one, though I do have pylance installed?? 

[**NOTE**: If you suspect that your issue is related to the Microsoft Python Language Server (`python.languageServer: 'Microsoft'`), please download our new language server [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) from the VS Code marketplace to see if that fixes your issue]

## Expected behaviour

At any time while debugging, the current line of execution should be highlighted.

## Actual behaviour

In this image, the last line of code that executed was line 67, ```if not chargebee.validateSubscription(customerId, companyName, firstName, lastName, email):```, but the highlight jumped all the way to line 75. I think it's supposed to have landed on line 72 (else), but at the very least it should have stopped at 74 both because that's the next actual code line AND it has a breakpoint on it.

![image](https://user-images.githubusercontent.com/26446314/94960270-768e0300-04a7-11eb-939f-359fd6a2571e.png)

As you can see from the screenshot, line 74 **should have** set a variable called new_company, but the local variable list **does not include that variable**.

When I step over the current line of code, the highlight moves to line 76, and now the new_company variable is shown in the list, but new_first_name is not, even though that's what was on line 75:

![image](https://user-images.githubusercontent.com/26446314/94961365-5c552480-04a9-11eb-85ac-793654e37317.png)

If I continue stepping over for a bit, we get to line 80, but new_email is still not set:

![image](https://user-images.githubusercontent.com/26446314/94961533-a9d19180-04a9-11eb-92ff-ec47bc095419.png)

This is where it gets even harder to follow.  When I step INTO line 80, it goes to the first line of code in the getUsers call. If I then use the call stack to go back to main, you can see that it has added new_email to the variable list.

![image](https://user-images.githubusercontent.com/26446314/94961661-edc49680-04a9-11eb-9389-c0509db29cfa.png)

I put a breakpoint on the next line (81) and let it run, and when it came to 81, the result variable still does not show up in the local variable list even though it has clearly executed the getUsers function.

## Steps to reproduce:

I have had this happen in other modules as well, including one that doesn't involve sensitive data or Azure functions. Sometimes, exiting out of VSC completely and restarting resets it. I've also tried deleting the pychache directory for this function, but that hasn't helped either. I have a non-sensitive program I wrote that may exhibit the problem and I could send that, but it's not "minimal"

**Comment by fabioz** [comment]
I think this is the same thing already reported in: 

https://github.com/microsoft/debugpy/issues/346

This has already been fixed, but it seems that a release with it is still not available.

The workaround until a new release is setting:

`"env":{"PYDEVD_USE_FRAME_EVAL": "NO"}`

in the launch configuration.

Please reopen if the workaround doesn't work for you.

**Comment by dxkaufman** [comment]
@fabioz For VSC, would that mean adding it to launch.json, like this?
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Attach to Python Functions",
      "type": "python",
      "request": "attach",
      "port": 9094,
      "preLaunchTask": "func: host start"
    }
  ],
  "env":{"PYDEVD_USE_FRAME_EVAL": "NO"}
}
```

**Comment by karthiknadig** [comment]
@dxkaufman No, you have to set that environment variable where the debugger is launched. Setting it here does nothing, because when you use `attach`, all VS code does is connect to the given port. It does not launch the debugger.

so you have to set there where ever you run `python -m debugpy` or run a script that has `import debugpy`.

**Comment by dxkaufman** [comment]
@karthiknadig Thanks for the response. I don't have any idea where that happens in VSC. 

I did find ```python -m ``` in tasks.json:
```
{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "func",
      "command": "host start",
      "problemMatcher": "$func-watch",
      "isBackground": true,
      "dependsOn": "pipInstall"
    },
    {
      "label": "pipInstall",
      "type": "shell",
      "osx": {
        "command": "${config:azureFunctions.pythonVenv}/bin/python -m pip install -r requirements.txt"
      },
      "windows": {
        "command": "${config:azureFunctions.pythonVenv}/Scripts/python -m pip install -r requirements.txt"
      },
      "linux": {
        "command": "${config:azureFunctions.pythonVenv}/bin/python -m pip install -r requirements.txt"
      },
      "problemMatcher": []
    }
  ]
}
```

Can you give me any more details on this?

**Comment by karthiknadig** [comment]
@dxkaufman Are you using Azure Functions extension or something similar to work with your code? Then you have to look at their documentation on how to set the environment variables for the local runs.

**Comment by dxkaufman** [comment]
Gotcha. OK, so in case anyone else comes across this issue... For Azure functions, you add it to local.settings.json, like so:
```
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "DefaultEndpointsProtocol=https;AccountName=xyz;AccountKey=blahblahkeyblah==;EndpointSuffix=core.windows.net",
    "AzureStorageAccount":"xyz",    
 "AzureStorageKey":"blahblahkeyblah",
    "RunLocation": "Local",
    "BulkImportQueue":"bulk-import-dev",
    "FUNCTIONS_WORKER_RUNTIME": "python",
    "PYDEVD_USE_FRAME_EVAL": "NO"
  }
}
```

For direct launching from VSC to Python, according to the VSC docs, you can add environment variables in the configurations in launch.json, like so:
```
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "env":{"PYDEVD_USE_FRAME_EVAL": "NO"},
            "justMyCode": true
        },
        {
            "name": "Python: main.py",
            "type": "python",
            "request": "launch",
            "program": "main.py",
            "console": "integratedTerminal",
            "env":{"PYDEVD_USE_FRAME_EVAL": "NO"},
            "justMyCode": true
        }
    ],
```

**Comment by dxkaufman** [comment]
Thanks @karthiknadig !
