### ISSUE TITLE
Breakpoints won't break in Pydantic package, specifically

### ISSUE THREAD

**Issue by smcoll** [microsoft/debugpy#430]
## Environment data

-   VS Code version: 1.49.3
-   Extension version (available under the Extensions sidebar): 2020.0.112786
-   OS and version: Ubuntu 20.04
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.2
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Relevant/affected Python packages and their versions: pydantic
-   Relevant/affected Python-related VS Code extensions and their versions: Pylance 2020.9.8
-   Value of the `python.languageServer` setting: Pylance, although Jedi/Microsoft also show the same behavior

## Expected behaviour

Debugger will break on breakpoints in Pydantic code, as in other installed libs

## Actual behaviour

Debugger will break in other installed lib code, but not in Pydantic code.

## Steps to reproduce:

Detailed instructions at https://github.com/smcoll/vscode-python-14284, but here's the gist of it:

1. set up a workspace with only Python and Pylance extensions enabled, and set `"justMyCode": false`
1. set debug breakpoints in the env's `site-packages/pydantic/main.py` 
1. set breakpoints in other packages in `site-packages` for that virtualenv
1. run the debugger and note that any breakpoint will break except those in Pydantic

## Logs
```
User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'ShowExtensionSurveyPrompt - enabled'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - experiment'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - control'
User belongs to experiment group 'LocalZMQKernel - experiment'
User belongs to experiment group 'CollectLSRequestTiming - experiment'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
User belongs to experiment group 'EnableIPyWidgets - experiment'
User belongs to experiment group 'RunByLine - experiment'
User belongs to experiment group 'CustomEditorSupport - control'
User belongs to experiment group 'pythonaa'
> conda --version
> pyenv root
> python3.7 ~/.vscode/extensions/ms-python.python-2020.9.112786/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 ~/.vscode/extensions/ms-python.python-2020.9.112786/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 ~/.vscode/extensions/ms-python.python-2020.9.112786/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 ~/.vscode/extensions/ms-python.python-2020.9.112786/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2020.9.112786/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> ~/vscode-bug/.venv/bin/python3 ~/.vscode/extensions/ms-python.python-2020.9.112786/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> conda info --json
> pyenv root
> pyenv root
> pyenv root
> pyenv root
> pyenv root
> pyenv root
> ~/vscode-bug/.venv/bin/python3 ~/.vscode/extensions/ms-python.python-2020.9.112786/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> ~/vscode-bug/.venv/bin/python3 ~/.vscode/extensions/ms-python.python-2020.9.112786/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
Python interpreter path: ./.venv/bin/python3
Starting Pylance language server.
> conda --version
```

**Comment by int19h** [comment]
Looking at setup.py for that package, it is set up to cythonize all the .py files by default:

https://github.com/samuelcolvin/pydantic/blob/bf9cc4a5e7903ada2e819a63fe2da011f292a143/setup.py#L86-L92

This would make them native code, and thus not something that debugpy can trace. But, as a workaround, you should be able to build that package with `SKIP_CYTHON=1`, and then it should work. Can you give that a try?

**Comment by smcoll** [comment]
That makes sense... however, i'm still not getting this to work.  Here's how i reinstalled Pydantic without Cython, per https://github.com/samuelcolvin/pydantic/issues/555#issuecomment-647769091:

```
. .venv/bin/activate
pip uninstall pydantic
export SKIP_CYTHON=1
pip install --no-cache-dir --no-binary :all: pydantic
```

Sanity check, per [Pydantic install docs](https://pydantic-docs.helpmanual.io/install/) shows that Cython is not used:

```python
>>> import pydantic
>>> pydantic.compiled
False
```

And the debugger is behaving the same way.

**Comment by fabioz** [comment]
Can you provide the debugger logs for this?

i.e.:


* Open VS Code
* Select the command Extensions: Open Extensions Folder
* Locate the Python extension directory, typically of the form ms-python.python-2020.*.****
* In that directory ensure you do not have any debug*.log files, if you do, please delete them
* Go back into VS Code and modify your launch.json to add the setting "logToFile": true, see below:

```
"version": "0.2.0",
"configurations": [
    {
        "name": "Python: Current File (Integrated Terminal)",
        "type": "python",
        "request": "launch",
        "program": "${file}",
        "stopOnEntry": true,
        "console": "integratedTerminal",
        "logToFile": true
    },
```

* Start debugging
* When done, go back into the extension directory and upload the debug*.log files into this GitHub issue.

**Comment by smcoll** [comment]
Yes, thanks:

[debugpy.adapter-70145.log](https://github.com/microsoft/debugpy/files/5351167/debugpy.adapter-70145.log)
[debugpy.launcher-70319.log](https://github.com/microsoft/debugpy/files/5351168/debugpy.launcher-70319.log)
[debugpy.pydevd.70324.log](https://github.com/microsoft/debugpy/files/5351169/debugpy.pydevd.70324.log)
[debugpy.server-70324.log](https://github.com/microsoft/debugpy/files/5351170/debugpy.server-70324.log)
[debugger.vscode_98cecd11-ff17-402a-a48b-00f016b846e3.log](https://github.com/microsoft/debugpy/files/5351171/debugger.vscode_98cecd11-ff17-402a-a48b-00f016b846e3.log)

**Comment by int19h** [comment]
One other thing that would be interesting to check here - what happens if, instead of setting the breakpoint in UI, you use `breakpoint()` inside that same code? Does it break, and if so, what does the call stack look like?

**Comment by fabioz** [comment]
I can reproduce the issue with a simple `pip install pydantic`, as it really ships with everything cythonized, but uninstalling it and doing:

```
export SKIP_CYTHON=1
pip install --no-cache-dir --no-binary :all: pydantic
```

(or just moving the `.pyd` files to another directory) does enable the debugger to work properly, so, I think that in this case what's missing is that you also need to set `"justMyCode": false` to the launch.

Given that I've been able to debug it that way here, I'm closing the issue, but feel free to comment more in case you still have any issues.

**Comment by smcoll** [comment]
Ah!  Right.  That does indeed solve it. Thanks for your help, @fabioz and @int19h

**Comment by guillaumek** [comment]
thank you, you have no idea how much time i spend on this <3
