### ISSUE TITLE
Call Stack empty when Debugging

### ISSUE THREAD

**Issue by tiagosvf** [microsoft/debugpy#435]
## Environment data

-   VS Code version: 1.49.3
-   Extension version (available under the Extensions sidebar): v2020.9.114305
-   OS and version: Windows 10 2004
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Relevant/affected Python packages and their versions:
-   Relevant/affected Python-related VS Code extensions and their versions:
-   Value of the `python.languageServer` setting: Jedi

## Expected behaviour

Call Stack should show running processes and threads.
![Call Stack working with a C++ program](https://i.imgur.com/FKpMdEC.png)

## Actual behaviour

Call Stack is empty until a breakpoint is reached and even then it doesn't show the running threads.
![empty Call Stack when running Python program](https://i.imgur.com/EBtrBd4.png)

## Steps to reproduce:

1. Create python 'project' with these settings in .vscode

settings.json:
```json
{
    "python.pythonPath": "C:\\Users\\summo\\AppData\\Local\\Programs\\Python\\Python38\\python.exe"
}
```

launch.json
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "externalTerminal"
        }
    ]
}
```

2. Python code:

```python
import threading
import time

threads = []

MAX_THREADS = 3


def get_thread():
    while True:
        print(threading.get_ident())  # print thread ID
        time.sleep(1)


def main():
    for i in range(MAX_THREADS):
        getter_thread = threading.Thread(
            target=get_thread, name=f"Getter{i}", daemon=True)
        threads.append(getter_thread)
        getter_thread.start()
    
    wait = input()


if __name__ == "__main__":
    main()



```

**Comment by fabioz** [comment]
I can't reproduce it. 

I.e.: when I run the call stack is there:

![image](https://user-images.githubusercontent.com/117621/95497415-aa21cf00-0978-11eb-89da-0145364ee644.png)

and adding a breakpoint afterwards does stop and show the call stack:

![image](https://user-images.githubusercontent.com/117621/95497444-b60d9100-0978-11eb-92fa-b665ae9dea47.png)

@tiagosvf can you provide the logging for the run when you do that?

i.e.: 

* Open VS Code
* Select the command Extensions: Open Extensions Folder
* Locate the Python extension directory, typically of the form ms-python.python-2020.*.****
* In that directory ensure you do not have any debug*.log files, if you do, please delete them
* Go back into VS Code and modify your launch.json to add the setting "logToFile": true, see below:

```
{
    "name": "Python: Current File (External Terminal)",
    "type": "python",
    "request": "launch",
    "program": "${file}",
    "console": "externalTerminal",
    "logToFile": true
}
```

* Start debugging
* When done, go back into the extension directory and upload the debug*.log files into this GitHub issue.

**Comment by tiagosvf** [comment]
@fabioz

Here follow the log files:

[debugger.vscode_645c676e-d9ff-4d81-943c-d2cef99375d3.log](https://github.com/microsoft/debugpy/files/5351024/debugger.vscode_645c676e-d9ff-4d81-943c-d2cef99375d3.log)
[debugpy.adapter-17768.log](https://github.com/microsoft/debugpy/files/5351025/debugpy.adapter-17768.log)
[debugpy.launcher-23568.log](https://github.com/microsoft/debugpy/files/5351026/debugpy.launcher-23568.log)
[debugpy.pydevd.17184.log](https://github.com/microsoft/debugpy/files/5351027/debugpy.pydevd.17184.log)
[debugpy.server-17184.log](https://github.com/microsoft/debugpy/files/5351028/debugpy.server-17184.log)

**Comment by int19h** [comment]
So far as I can see, VSCode never issued a "stackTrace" request at all. 

Can you try it with the most recent version of Code (1.50 at the moment)? It might be something that they have already fixed.

**Comment by tiagosvf** [comment]
Just updated. Didn't fix it

**Comment by tiagosvf** [comment]
Just updated. Not fixed

**Comment by int19h** [comment]
You've mentioned that it behaves somewhat differently when there is a breakpoint that is hit - could you do that repro with logging enabled, as well?

**Comment by fabioz** [comment]
@tiagosvf Thank you for the logs. 

I've taken a look at them and the issue seems to be that you've `GEVENT_SUPPORT` enabled and yet, you're not using gevent threads (so, I guess you set the `GEVENT_SUPPORT` environment variable somewhere in the system). 

In the gevent mode the debugger expects that the threading modules are monkey-patched by gevent and thus it doesn't track those (as in gevent mode you're only expected to have 1 main thread).

The solution is not setting the `GEVENT_SUPPORT` flag in your environment or setting `"GEVENT_SUPPORT" = "0"` in your launch env.

i.e.:

```
{
    "name": "Python: Current File (External Terminal)",
    "type": "python",
    "request": "launch",
    "program": "${file}",
    "console": "externalTerminal",
    "env": {
        "GEVENT_SUPPORT": "0"
    }
}
```

**Comment by tiagosvf** [comment]
> 
> 
> @tiagosvf Thank you for the logs.
> 
> I've taken a look at them and the issue seems to be that you've `GEVENT_SUPPORT` enabled and yet, you're not using gevent threads (so, I guess you set the `GEVENT_SUPPORT` environment variable somewhere in the system).
> 
> In the gevent mode the debugger expects the threading modules to be monkey-patched by gevent and thus it doesn't track those (as in gevent mode you're only expected to have 1 main thread).
> 
> The solution is not setting the `GEVENT_SUPPORT` flag in your environment or setting `"GEVENT_SUPPORT" = "0"` in your launch env.
> 
> i.e.:
> 
> ```
> {
>     "name": "Python: Current File (External Terminal)",
>     "type": "python",
>     "request": "launch",
>     "program": "${file}",
>     "console": "externalTerminal",
>     "env": {
>         "GEVENT_SUPPORT": "0"
>     }
> }
> ```

That was exactly it!
I was using grequests before changing to multithreading and forgot about the environment variable.
I removed it and now threads show up in the Call Stack as they should
![Call Stack finally working as expected](https://user-images.githubusercontent.com/25352856/95606265-9a25f000-0a49-11eb-8382-08f9a563e1f7.png)

Thank you very much!

**Comment by taheriamm** [comment]
Hello @fabioz 
It is my problem too
can you help me?
![1](https://user-images.githubusercontent.com/94216358/219879551-2b2c2e69-1fe0-4297-b047-74fcb8949f38.png)
[debugger.vscode_2f82c2d0-f6f4-4215-929c-ff7835119a67.log](https://github.com/microsoft/debugpy/files/10774814/debugger.vscode_2f82c2d0-f6f4-4215-929c-ff7835119a67.log)
[debugpy.adapter-29044.log](https://github.com/microsoft/debugpy/files/10774815/debugpy.adapter-29044.log)
[debugpy.launcher-28244.log](https://github.com/microsoft/debugpy/files/10774816/debugpy.launcher-28244.log)
[debugpy.pydevd.26660.log](https://github.com/microsoft/debugpy/files/10774817/debugpy.pydevd.26660.log)
[debugpy.server-26660.log](https://github.com/microsoft/debugpy/files/10774818/debugpy.server-26660.log)

**Comment by taheriamm** [comment]
> Hello @fabioz It is my problem too can you help me? ![1](https://user-images.githubusercontent.com/94216358/219879551-2b2c2e69-1fe0-4297-b047-74fcb8949f38.png) [debugger.vscode_2f82c2d0-f6f4-4215-929c-ff7835119a67.log](https://github.com/microsoft/debugpy/files/10774814/debugger.vscode_2f82c2d0-f6f4-4215-929c-ff7835119a67.log) [debugpy.adapter-29044.log](https://github.com/microsoft/debugpy/files/10774815/debugpy.adapter-29044.log) [debugpy.launcher-28244.log](https://github.com/microsoft/debugpy/files/10774816/debugpy.launcher-28244.log) [debugpy.pydevd.26660.log](https://github.com/microsoft/debugpy/files/10774817/debugpy.pydevd.26660.log) [debugpy.server-26660.log](https://github.com/microsoft/debugpy/files/10774818/debugpy.server-26660.log)

my problem solved with edit launch.json to :
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Debug Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "stopOnEntry": true,
            "justMyCode": false
        },
    ]
}
