### ISSUE TITLE
module 'debugpy' has no attribute 'enable_attach'

### ISSUE THREAD

**Issue by marimeireles** [microsoft/debugpy#437]
[##](url) Environment data

- debugpy version: 1.0.0b9
- OS and version: Ubuntu20
- Python version (& distribution if applicable, e.g. Anaconda): 3.8.6 from conda
- Using VS Code or Visual Studio: No

## Actual behavior

When trying to upgrade xeus-python from ptvsd to debugpy I get the following:

```
module 'debugpy' has no attribute 'enable_attach'
```

Which makes sense since it doesn't exist an `enable_attach` method in debugpy's code. But the [docs](https://github.com/microsoft/debugpy/blob/master/doc/Subprocess_debugging.md#attach-scenario) says it does.

## Steps to reproduce:
1. Build xeus-python from this branch: https://github.com/jupyter-xeus/xeus-python/pull/329
2. Try to run the bugger

My question is, what's the equivalent method to do this?
Thanks!

cc: @JohanMabille

**Comment by marimeireles** [comment]
Oh man, my colleague just found a part of the docs that's explaining this! Sorry, I think this is jus a problem in this file :)
Thanks @wolfv!

**Comment by fabioz** [comment]
Hi @marimeireles thanks for the report... that was a design document created around the time that the subprocess attach was being done and it's really outdated... @int19h would you like to keep that and update it or just remove it altogether?

**Comment by fabioz** [comment]
Those docs are now no longer available (closing issue).
