### ISSUE TITLE
Wrong evaluation of if statement in debugging

### ISSUE THREAD

**Issue by sadjadanzabizadeh** [microsoft/debugpy#440]
Issue Type: <b>Bug</b>

When I debug the code provided in the screenshot below, the boolean variable is False. However, the debugger highlights and goes over the lines inside the if block, as if the condition is True! Note that it does not execute lines, but moves through them.
![image](https://user-images.githubusercontent.com/32469424/96759600-e48a6380-139d-11eb-975f-da2434489c46.png)

Extension version: 2020.9.114305
VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (1.31GB free)|
|Process Argv|--crash-reporter-id 19e6f19c-8117-4455-bc5e-1394785840d3|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by int19h** [comment]
This sounds like https://github.com/microsoft/debugpy/issues/346/. Can you try the workaround there? In your launch.json:
```json5
"env": {"PYDEVD_USE_FRAME_EVAL": "NO"}
```
If this helps, it's the same bug, and we already fixed it - the fix will be in the next version of the extension.

**Comment by fabioz** [comment]
The new extension release (2020.11.358366026) should already have the needed fixes, so, I'm closing the issue (please reopen if you can still reproduce).
