### ISSUE TITLE
Running `breakpoint()` in the watch causes buggy behaviour

### ISSUE THREAD

**Issue by noahbald** [microsoft/debugpy#447]
## Environment data

-   VS Code version: 1.50.1
-   Extension version (available under the Extensions sidebar): v2020.9.114305
-   OS and version: Windows 10: 2004
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.0 64-bit
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Relevant/affected Python packages and their versions: NA
-   Relevant/affected Python-related VS Code extensions and their versions: NA
-   Value of the `python.languageServer` setting: Microsoft

[**NOTE**: If you suspect that your issue is related to the Microsoft Python Language Server (`python.languageServer: 'Microsoft'`), please download our new language server [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) from the VS Code marketplace to see if that fixes your issue]

## Expected behaviour

Running `breakpoint()` in the watch should be unavailable or display some error.

It should not affect the runtime behaviour of the program being debugged.

## Actual behaviour

The program repeatedly continues and breaks until the program completes.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Set a reachable breakpoint in your python file
2. Once the breakpoint is reached, add a watch for `breakpoint()`
3. Question why you did this

![](https://i.imgur.com/pkStSkl.gif)

## Logs

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```

```

</p>
</details>

**Comment by int19h** [comment]
We can't reliably detect `breakpoint()` before we eval it. We do not even try to parse expressions for validity - just hand them over to the Python interpreter to execute. Even if we did parse them, we'd also have to somehow prevent you from calling functions that *eventually* call `breakpoint()`. 

However, this scenario should behave differently - `breakpoint()` is expected to behave as if it were a real breakpoint, and calling a function that contains a breakpoint inside of it from within a Watch expression is legal (it simply won't break). The function is probably missing a check that we have for regular breakpoints.

**Comment by judej** [comment]
Thank you for the report. Given our current resources are working on the Python 3.12 debugger, we will not be fixing this issues in the pre Python 3.12 debugger.
