### ISSUE TITLE
Having issues while trying to debug uwsgi 

### ISSUE THREAD

**Issue by SarthakAdhikari** [microsoft/debugpy#458]
## Environment data

- debugpy version: 1.1.0
- OS and version: Arch Linux 2020.11.01
- Python version (& distribution if applicable, e.g. Anaconda): 3.8.2
- Using VS Code or Visual Studio: VS Code

## Actual behavior

I am trying to debug a remote application inside docker[(this application)](https://github.com/chicagopython/chipy.org) and the django app is started through uwsgi.

When I try to attach it  inside the django application(in `wsgi.py` folder), I get the following error:
```
/usr/local/bin/uwsgi: unrecognized option '--for-server'

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/debugpy/server/api.py", line 218, in listen
    sock, _ = endpoints_listener.accept()
  File "/usr/local/lib/python3.8/socket.py", line 292, in accept
    fd, addr = self._accept()
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./chipy_org/wsgi.py", line 33, in <module>
    debugpy.listen(("0.0.0.0", 3000))
  File "/usr/local/lib/python3.8/site-packages/debugpy/__init__.py", line 113, in listen
    return api.listen(address)
  File "/usr/local/lib/python3.8/site-packages/debugpy/server/api.py", line 143, in debug
    log.reraise_exception("{0}() failed:", func.__name__, level="info")
  File "/usr/local/lib/python3.8/site-packages/debugpy/server/api.py", line 141, in debug
    return func(address, settrace_kwargs, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/debugpy/server/api.py", line 232, in listen
    raise RuntimeError("timed out waiting for adapter to connect")
RuntimeError: timed out waiting for adapter to connect

```
I tried to attach a debugger in the interactive python REPL(inside the same container) to test if it remote debugging works and it does. 

Does this have something to do with the above error?
```/usr/local/bin/uwsgi: unrecognized option '--for-server'```

## Expected  behavior

The expected behavior would be VSCode successfully attaching to debugpy.

## Steps to reproduce:
1. Clone https://github.com/SarthakAdhikari/chipy.org
2. Execute the following(debugpy is setup at `chipy_org/wsgi.py` folder):
```
make setup_env
make up
make tail-logs
```
3. Visit localhost:8000 in the browser and the error appears on the output of the above tail-logs command.

**Comment by int19h** [comment]
When you start the debugpy server in your process, it needs to spawn a separate process for the debug adapter; and it uses `sys.executable` to do so by default, on the assumption that it's some kind of Python interpreter, and understands the same command line switches as CPython.

When that is not the case - i.e. when you're trying to debug an app that hosts Python - you need to tell the debug server which Python interpreter it should be using to spawn that adapter process. In launch scenarios, the "python" or "pythonPath" property in your debug configuration (launch.json) does that; but here, you need to specify that property before configuration can be processed. We provide `debugpy.configure()` for this purpose:
```py
debugpy.configure(python="/usr/bin/python3")  # just "python3" will work if it's on PATH
debugpy.listen(...)
```

**Comment by SarthakAdhikari** [comment]
Thank you very much for the prompt response! Finally got it working.
