### ISSUE TITLE
Enable overriding "pythonPath" in the launcher

### ISSUE THREAD

**Issue by int19h** [microsoft/debugpy#463]
Problem: https://github.com/microsoft/vscode-docker/issues/2455#issuecomment-720651526

To solve this, the launcher needs to provide some way to override "pythonPath" that comes from the client (via the adapter), such that the custom launcher script that the Docker extension registers can change it.

**Comment by int19h** [comment]
As described here: https://github.com/microsoft/vscode-docker/issues/2455#issuecomment-724267419

**Comment by MichaelSchmidt82** [comment]
I can confirm backing out to docker versions 1.6.0 and python (extension) version 2020.8.109390 will work around this regression.

**Comment by bwateratmsft** [comment]
Reverting Docker shouldn't be necessary.
