### ISSUE TITLE
Breakpoints not working after update

### ISSUE THREAD

**Issue by ftrofin** [microsoft/debugpy#466]
Issue Type: <b>Bug</b>

After VS Code automatically updated the breakpoints i set are not working anymore. I uninstalled/reinstalled the Python extension, restarted VSCode, nothing.

Extension version: 2020.10.332292344
VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:14:40.758Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-3235 CPU @ 3.30GHz (24 x 3300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 2, 2|
|Memory (System)|96.00GB (70.18GB free)|
|Process Argv|--crash-reporter-id 5a9f9130-a73f-4083-966c-e894cacf4fed|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by int19h** [comment]
Can you provide more details about the code, and how you initiate debugging (launch.json configuration etc)?

Does it happen with everything - even a simple hello world app - or just one particular project?

**Comment by ftrofin** [comment]
Sorry, it was pilot error. Python is working fine. I have a problem with C++ debugging, not Python. I'll close this and open another one for the C++ extension.
