### ISSUE TITLE
VSCode update 1.51 breaks "Attach to Process ID"

### ISSUE THREAD

**Issue by CodeGuro** [microsoft/debugpy#470]
## Environment data

Version: 1.51.0
Commit: fcac248b077b55bae4ba5bab613fd6e9156c2f0c
Date: 2020-11-05T18:16:10.374Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-52-generic

## Actual behavior

The "PickProcess" context menu does not come up. It loads forever.

## Expected  behavior

I expected the process-picker dialog to come up.

## Steps to reproduce:

Simply run VSCode Version: 1.51.0.
It works just fine with version 1.50, however.

![Screenshot from 2020-11-11 15-29-55](https://user-images.githubusercontent.com/2359168/98861422-3f5e2a80-2433-11eb-9cc5-f086ff822163.png)

**Comment by karthiknadig** [comment]
This is same as https://github.com/microsoft/vscode-python/issues/14678.
This has to be fixed by VS Code itself, see comment here for why it occurs: https://github.com/microsoft/vscode-python/issues/14678#issuecomment-725573668
