### ISSUE TITLE
possible to debug CGI scripts

### ISSUE THREAD

**Issue by bedenko** [microsoft/debugpy#472]
It would be great, to be able to attach to CGI scripts, that run under Apache.

**Comment by karthiknadig** [comment]
Can you elaborate on the scenario? 

`debugpy` supports attaching to embedded python using `--pid` (attach to process by process id). You could also reverse the direction and have the process running python attach to the IDE using `listen` mode on the IDE side and using `debugpy.connect` in your scripts. So, it should be possible to do this.

**Comment by bedenko** [comment]
Well, my problem is, that python process is being spawned by Apache, so the PID is unknown to me beforehand.

**Comment by karthiknadig** [comment]
Using this in your script did not work?

Ensure debugpy is installed in your environment.
```python
import debugpy

# this will start the debug server.
debugpy.listen(5678)
# this will wait for you to connect to debug server using vscode.
debugpy.wait_for_client()

// your code
```
Use remote attach debug configuration. For this to work your python code should already be running, which will start the debug server.
```
    {
        "name":"Python: Remote Attach",
        "type":"python",
        "request":"attach",
        "connect":{
            "host":"localhost",
            "port":5678
        },
        "pathMappings":[
            {"localRoot":"${workspaceFolder}","remoteRoot":"."}
        ]
    }
```

For your scenario I would expect this to work.

**Comment by bedenko** [comment]
I created this basic example:

```
#!/usr/bin/env python3

import cgi
import debugpy
debugpy.listen(5678)
debugpy.wait_for_client()

data = cgi.FieldStorage() #<--breakpoint inserted here
print("Status: 200 OK")
print("Content-Type: text/plain\n")
print("Test!")
```
and launch.json, that you provided.
When i refreshed the page, GET request fires and browser waits for reply.
Next i run debug in vscode (F5), and the script gets executed.
This works great. What does not work are the breakpoints.
I am unable to pause the execution on inserted breakpoint.

**Comment by karthiknadig** [comment]
@bedenko Which version of python are you using? we had bug where mapping wasn't working on some of the later versions of python. As a work around you can use `debugpy.breakpoint()` on the line before you want to break. This will always force the execution to stop.

To investigate further we will need logs. Use `debugpy.log_to(<path to directory>)` before `debugpy.listen` to generate debugger logs and share. Note that this will generate several files per run. We will need all the files for a given run where the debugger does not break at the breakpoint.

**Comment by bedenko** [comment]
Python version is 3.6.8-13.el7.x86_64.

Log files for given example:
[debugpy.adapter-4095.log](https://github.com/microsoft/debugpy/files/5551690/debugpy.adapter-4095.log)
[debugpy.server-4089.log](https://github.com/microsoft/debugpy/files/5551691/debugpy.server-4089.log)

`debugpy.breakpoint()` is working, there is only one issue, not related to this problem perhaps:
When breakpoint occurs, VSCODE editor resets Language mode from _Python_ to _Plain Text_.
It does this, if executed script name does not have **.py** extension. If i add it, the problem is solved.

**Comment by karthiknadig** [comment]
Thanks for the logs.

"VSCODE editor resets Language mode from Python to Plain Text.", We don't control this, this should be filed on VS Code.

**Comment by karthiknadig** [comment]
Does this mapping look right to you?
```
"pathMappings": [
                         {
                             "localRoot": "/var/www",  // <--- this is your workspace folder in VS Code
                             "remoteRoot": "cgi-bin/" // <--- this is the current working directory where the python code is running.
                         }
                     ],
```

You could also try removing the path mapping to see it works. 
```
    {
        "name":"Python: Remote Attach",
        "type":"python",
        "request":"attach",
        "connect":{
            "host":"localhost",
            "port":5678
        },
        "pathMappings":[]
    }
```

If not then you may have to tweak the local and remote roots ( these have to be full absolute paths).
    {
        "name":"Python: Remote Attach",
        "type":"python",
        "request":"attach",
        "connect":{
            "host":"localhost",
            "port":5678
        },
        "pathMappings":[
            {
              "localRoot":"/var/www/cgi-bin",
              "remoteRoot":"/var/www/cgi-bin"
            }
        ]
    }

**Comment by bedenko** [comment]
Yes, i had `{"localRoot":"${workspaceFolder}","remoteRoot":"cgi-bin/"}` set up by default.
I changed it to absolute paths, as you suggested and breakpoints are working now.

Thank you!
