### ISSUE TITLE
Can't stop in subthread's breakpoint when debugging.

### ISSUE THREAD

**Issue by MyronCodes** [microsoft/debugpy#474]
This is the test code.
The Thread class is a sub thread.
When I make a breakpoint in `app = QApplication(sys.argv)`. I can stop when I debugging.
But when the breakpoint is in Thread's `    def run(self): ` , then code will run and print but didn't stop.

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# ----- ----- ----- ----- ----- <[ Sys ]> ----- ----- ----- ----- ----- #

import os
import sys
import time
import pynput

# ----- ----- ----- ----- ----- <[ PyQt5 ]> ----- ----- ----- ----- ----- #

from PyQt5.QtWidgets import *
from PyQt5.QtCore import *

class Thread(QThread):

    qt_signal = pyqtSignal(str)

    def __init__(self, parent = None):
        super().__init__(parent)
        print('Thread init')

    def run(self): 
        time.sleep(1)
        for i in range(10):
            print('Thread run')

class Basic(QMainWindow):

    def __init__(self):
        super().__init__()
        self.sub = Thread()
        self.sub.start()

app = QApplication(sys.argv)
ui = Basic()
sys.exit(app.exec_())
```

**Comment by fabioz** [comment]
As a note, when using the frame eval mode in the debugger (on Python 3.6 onwards with compiled extensions), this should work out of the box now.

Closing since there doesn't seem like there's anything else to be done here.

**Comment by Bwijn** [comment]
**Solution for Debugging QThread in PySide6 with Debugpy**



If you're working with PySide6 and encountering issues while trying to debug a QThread, you're not alone. Many users face challenges when trying to debug threads in Qt applications. Here's a solution that worked for me using debugpy to connect to the thread and set breakpoints.

Problem:
When debugging QThread in PySide6, breakpoints inside the run() method don't trigger

Solution:
`import sys
import time
from PySide6.QtWidgets import QApplication, QWidget, QVBoxLayout, QLabel, QPushButton
from PySide6.QtCore import QThread, Signal, Slot
import debugpy 
class WorkerThread(QThread):
    
    task_finished = Signal(int)

    def __init__(self, thread_id, parent=None):
        super().__init__(parent)
        self.thread_id = thread_id

    def run(self):
        debugpy.breakpoint()  # set here breakpoint !!!!!!!!!!!!!!!!!!!!!!!!!!!!Explicitly set!!!!!!!!!!!!!!!!!!!!

        print(f"Thread {self.thread_id} starting")
        time.sleep(2)  
        print(f"Thread {self.thread_id} finished")
        self.task_finished.emit(self.thread_id)
