### ISSUE TITLE
The timeout on listening is way too fast

### ISSUE THREAD

**Issue by dougransom** [microsoft/debugpy#478]
## Environment data

- debugpy version: 1.2.0
 - Windows 10 Pro  
Python 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:37:30) [MSC v.1927 32 bit (Intel)] on win32

Using VS Code or Visual Studio:

 The timeout is 10 seconds     for         debugpy.wait_for_client().

It is impossible for me to perform the necessary actions in Visual Studio in that time.  Even a loop of retrying doesn'twork well because then my app steals focus from Visual Studio so i can't connect the debugger.

I would suggest a longer default, and an argument to debugpy.wait_for_client() so I can set the time for 60 seconds.

**Comment by int19h** [comment]
There's no timeout for `debugpy.wait_for_client()`, so it must be something else that's causing it. Can you share the script that you're calling it from?

**Comment by dougransom** [comment]
This was a manifestation of embedded python within a windows program and not having debugpy.configure(python="C:\Python\python.exe").
