### ISSUE TITLE
Debug: hide special variables and function variables

### ISSUE THREAD

**Issue by jeffreyyjp** [microsoft/debugpy#481]
![image](https://user-images.githubusercontent.com/17985592/100040565-804a3c00-2e42-11eb-807b-8b024897b47e.png)

**Comment by int19h** [comment]
Try doing this in your launch.json:
```json5
"variablePresentation": {
    "function": "hide",
    "special": "hide",
}
```

**Comment by fabioz** [comment]
Closing as the support to change how that's presented is already in the debugger backend by editing the `launch.json`. 

You can follow https://github.com/microsoft/vscode-python/issues/12373 for a request to be able to set it in the settings and not only through individual launch configurations.

**Comment by glitchwizard** [comment]
Here's an example of my `launch.json` that worked for me 

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Attach debugger",
      "type": "python",
      "request": "attach",
      "pathMappings": [
        {
          "localRoot": "${workspaceFolder}",
          "remoteRoot": "/code"
        }
      ],
      "port": 8001,
      "host": "localhost",
      "variablePresentation": {
        "function": "hide",
        "special": "hide",
      },
    },
  ],
  
}
```

**Comment by Strajk** [comment]
Don't get discouraged by "Property variablePresentation is not allowed." error, it works
<img width="370" height="181" alt="Image" src="https://github.com/user-attachments/assets/9c0bf701-e594-4cab-b616-acc5549826b2" />
