### ISSUE TITLE
debugpy maps properly the path for setting breakpoints, but not for module location (and thus cannot open the file using the call stack while debugging)

### ISSUE THREAD

**Issue by Yajo** [microsoft/debugpy#482]
## Environment data

- debugpy version: 1.2.0
- OS and version: Debian GNU/Linux 9.13 (stretch)
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.5.10
- Using VS Code or Visual Studio: VS Code

[This is my launch configuration](https://gist.github.com/Yajo/75a6037ac4300d72dee24d788fc24c67#file-doodba-doodba-devel-12-0-code-workspace) (there are several; the one that affects this issue is called *"Attach Python debugger to running container"*). You can see that it has *lots* of path mappings because this is a complex multi-root project.

## Actual behavior

![imagen](https://user-images.githubusercontent.com/973709/100223978-18642600-2f14-11eb-8057-edf5a93ed530.png)

[Full debug session logs](https://gist.github.com/Yajo/75a6037ac4300d72dee24d788fc24c67#file-connecting-to-0-0-0-0-debugpy-adapter-39-log). Relevant parts:

1. [Debugpy acknowledged the proper path mapping for the `l10n_es_toponyms` module](https://gist.github.com/Yajo/75a6037ac4300d72dee24d788fc24c67#file-connecting-to-0-0-0-0-debugpy-adapter-39-log-L9443-L9444).
1. [The breakpoint seems to be properly enabled](https://gist.github.com/Yajo/75a6037ac4300d72dee24d788fc24c67#file-connecting-to-0-0-0-0-debugpy-adapter-39-log-L10385-L10427).
1. [Debugpy seems to be mapping incorrectly the `odoo.addons.l10n_es_toponyms.tests.test_l10n_es_toponyms` module into `/var/home/yajo/prodevel/doodba-devel-12.0/odoo/custom/src/odoo/addons/l10n_es_toponyms/tests/test_l10n_es_toponyms.py`](https://gist.github.com/Yajo/75a6037ac4300d72dee24d788fc24c67#file-connecting-to-0-0-0-0-debugpy-adapter-39-log-L11613-L11614) instead of `/var/home/yajo/prodevel/doodba-devel-12.0/odoo/custom/src/l10n-spain/l10n_es_toponyms/tests/test_l10n_es_toponyms.py`

## Expected  behavior

When clicking on the stack trace, or just when the python code is being paused by the debugger, inside the `l10n-spain/l10n_es_toponyms/tests/test_l10n_es_toponyms.py:10` breakpoint, VSCode should properly open the file.

## Steps to reproduce:

Well, as you might have guessed this is not going to be "minimal", but well... this is so hard to trigger that this is what it takes :shrug::

First, you are expected to have these tools to be able to reproduce it:

1. Linux.
1. Python 3.
1. Git.
1. Docker running in localhost.
1. Your user with write permissions to the docker socket (usually do `sudo usermod -aG docker $USER`).
1. Some python CLI apps that you'll need to make it work: `pip install pre-commit invoke docker-compose`

```bash
git clone -b 12.0 https://github.com/Yajo/doodba-devel.git doodba-devel-12.0
cd doodba-devel-12.0
invoke develop
invoke img-pull img-build --pull git-aggregate resetdb -m l10n_es_toponyms
code doodba.doodba-devel-12.0.code-workspace
```

Now that you opened the workspace in VSCode, and have all the code available:

1. Open `l10n-spain/l10n_es_toponyms/tests/test_l10n_es_toponyms.py` file.
1. Set a breakpoint on line 10.
1. While that file is still focused, go to debug tab.
1. Select "Test and debug current module" execution option.
1. Wait until the debugger hits line 10.

cc @joao-p-marques

**Comment by fabioz** [comment]
The logs aren't complete, so, I can't really diagnose this properly.

In particular, I'm interested in the `pydevd` log file. Can you provide it?

On a first glance I think that in this case one of the paths has more than one translation back and we just go with the first one found (the pydevd log should have more info on the actual targets and translations to be able to diagnose this better).

Ideally your mapping should be an injective function, but if that's not possible, you should put the ones you want to match first earlier in that list.

p.s.: please attach the log files to this issue instead of putting it in a `gist`.

**Comment by Yajo** [comment]
El vie, 27 de nov de 2020 a las 05:22, Fabio Zadrozny 
<notifications@github.com> escribió:
> In particular, I'm interested in the pydevd log file. Can you provide 
> it?
> 

How can I get those logs? Do they come from the container running 
debugpy, or from the dev machine running vscode?

**Comment by fabioz** [comment]
It should be generated in the server (where `debugpy` is running). 

You should be able to set the `DEBUGPY_LOG_DIR` environment variable to a directory where the logs will be generated in this case.

**Comment by Yajo** [comment]
OK, thanks. Here are the logs:

[debugpy.adapter-39.log](https://github.com/microsoft/debugpy/files/5628173/debugpy.adapter-39.log)
[debugpy.pydevd.1.log](https://github.com/microsoft/debugpy/files/5628174/debugpy.pydevd.1.log)
[debugpy.server-1.log](https://github.com/microsoft/debugpy/files/5628175/debugpy.server-1.log)

**Comment by Yajo** [comment]
Were those logs helpful? Anything else I can do?

**Comment by fabioz** [comment]
I just took a look and I forgot to ask you to turn on the debugging of the actual translation.

Can you rerun that setting the environment variable below and provide the new logs?

`DEBUG_PYDEVD_PATHS_TRANSLATION=1`

**Comment by fabioz** [comment]
Actually, I've been able to setup a test where I can reproduce this.

This is happening because the last `/` is actually removed during the path translation, so, it's matching: `/opt/odoo/auto/addons/l10n_es`.

I'll take a look into fixing that.

As a workaround you can put the mapping:
```
{
"localRoot": "/var/home/yajo/prodevel/doodba-devel-12.0/odoo/custom/src/odoo/addons/l10n_es/",
"remoteRoot": "/opt/odoo/auto/addons/l10n_es/"
},
```

as the last mapping so that it has less priority.

**Comment by Yajo** [comment]
I just tested installing `debugpy` from git master in the container, and the bug is fixed. Thank you! :heart:
