### ISSUE TITLE
Debug from terminal can't listen for client connections

### ISSUE THREAD

**Issue by davepwd** [microsoft/debugpy#483]
Hi,
I'm having problems with executing a simple python script via command prompt, and debugging it vith VSCode.
From the tutorial:
https://code.visualstudio.com/docs/python/debugging#_local-script-debugging
What I did:
1. Created a C:/Users/user7/Downloads/project
2. Opened the file test3.py and added the debugpy lines in the end of the script (with debugpy.listen(5678) and   debugpy.wait_for_client()).
3. from Integrated Terminal, I started >python -m pip install --upgrade debugpy
4. from Integrated Terminal, >python -m debugpy --listen 5678 test3.py
5. Started debug with F5 on the same script with VSC

All goes well up until the debugpy.listen(5678):
I get the error: RuntimeError: Can't listen for client connections: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted

I want to run the script via Command Prompt and connect it to VSC debugger, but I obtain the same error.

My launch.json file in Downloads/project/.vscode:

`{

    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: File corrente",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal"
        },
        {
            "name": "Python: Attach",
            "type": "python",
            "request": "attach",
            "connect": {
              "host": "localhost",
              "port": 5678
            }
          }
    ]
}
    `

settings.json file:

`
{
    "FUNCTIONS_WORKER_PROCESS_COUNT": 10
}
`
Thanks for your help.

**Comment by fabioz** [comment]
Well, if you already started the process with `python -m debugpy --listen 5678 test3.py`, it's already listening in port `5678`, so, you shouldn't add `debugpy.listen(5678)` again in the script (i.e.: just leave `debugpy.wait_for_client()` there).

**Comment by fabioz** [comment]
Please reopen if this doesn't fix it for you.

**Comment by davepwd** [comment]
Thank you got it fixed.
