### ISSUE TITLE
sys.exit(0) does not break by default, but sys.exit() does

### ISSUE THREAD

**Issue by nedsociety** [microsoft/debugpy#489]
## Environment data

- debugpy version: 1.2.0
- OS and version: Win10 18363.1198
- Python version (& distribution if applicable, e.g. Anaconda): 3.9.0
- Using VS Code or Visual Studio: vscode 1.51.1, Python extension v2020.11.371526539

## Description
This code triggers breakpoint even if the "Raised Exceptions" option is turned off:
```python
import sys
sys.exit()
```

![image](https://user-images.githubusercontent.com/11943013/101295938-e7fd7f80-3863-11eb-9ac8-54e869b4ef07.png)

This seems inconsistent. If I specify the exit code like `sys.exit(0)` explicitly then it ignores SystemExit as expected.

**Comment by karthiknadig** [comment]
In the launch JSON, add this and see if it helps:
```
"breakOnSystemExitZero": true
```

**Comment by nedsociety** [comment]
> `"breakOnSystemExitZero": true`

Well it makes `sys.exit(0)` also breaks as well, which is even more undesirable. The expected behavior in default should be:

 * `sys.exit()` doesn't break
 * `sys.exit(0)` doesn't break
 * `sys.exit(n)` for nonzero `n` breaks

**Comment by karthiknadig** [comment]
Ah! I see. Sorry, I misunderstood the issue.

**Comment by fabioz** [comment]
It seems that the issue is that `SystemExit.code` is `None` in this case (and not `0`).
