### ISSUE TITLE
make debugpy compatible with pyinstaller

### ISSUE THREAD

**Issue by mprosperi** [microsoft/debugpy#490]
hello, I have a main script pippo.py which launches test-vsc.py with this statement:
runpy.run_path(sys.argv[1])  
where argv[1] contains the full path to test-vsc.py
So I run from command line "python pippo.py c:\\mydir\\test-vsc.py" and then I debug test.py from vsc with remote attach and everything is ok.
I would like to compile pippo.py to pippo.exe with pyinstaller and still debug test-vsc.py (or whatever script I pass from command line) but when I run pippo.exe I get the traceback below.
From [here](https://github.com/pyinstaller/pyinstaller/issues/5363) in the end it seems that debugpy is incompatible with pyinstaller: can this be overtaken in the future?

Traceback (most recent call last):
  File "pippo.py", line 6, in <module>
  File "runpy.py", line 263, in run_path
  File "runpy.py", line 96, in _run_module_code
  File "runpy.py", line 85, in _run_code
  File "C:\Users\\paneido1\Documents\python\provavsc\test-vsc.py", line 6, in <module>
    debugpy.listen(("localhost", 5678))
  File "debugpy\__init__.py", line 113, in listen
    return api.listen(address)
  File "debugpy\server\api.py", line 143, in debug
    log.reraise_exception("{0}() failed:", func.__name__, level="info")
  File "debugpy\server\api.py", line 141, in debug
    return func(address, settrace_kwargs, **kwargs)
  File "debugpy\server\api.py", line 232, in listen
    raise RuntimeError("timed out waiting for adapter to connect")
RuntimeError: timed out waiting for adapter to connect
[10408] Failed to execute script pippo

**Comment by int19h** [comment]
If you call `debugpy.configure(python="/path/to/python")` before you call `listen()`, it'll use that interpreter to spawn its helper processes. But it does need *some* Python interpreter for that. So if you do that, it kinda renders pyinstaller moot.

My suggestion would be to run without debugpy by default, and require the end user to specify path to some compatible (with debugpy; it doesn't have to be the same as for your app!) Python interpreter if they want to enable it.

**Comment by mprosperi** [comment]
thank you for your quick response, but in a more real use case, as the one from which I started, test-vsc.py would use modules (e.g. custom modules) that are part of pippo.exe and cannot be present in a /path/to/python environment in the filesystem. Otherwise there would be no need to compile pippo.py into pippo.exe with pyinstaller

**Comment by int19h** [comment]
Your code would still run from the bundle, and use the bundled modules. But debugpy adapter (which is a separate process) doesn't need those modules - it only depends on the Python standard library, and it doesn't load any of your code.

**Comment by mprosperi** [comment]
thank you, it works fine! 
Is debugpy supposed to work also if I launch test-vsc.py with exec() instead of runpy.run_path(sys.argv[1]) ?

**Comment by fabioz** [comment]
> Is debugpy supposed to work also if I launch test-vsc.py with exec() instead of runpy.run_path(sys.argv[1]) ?

Yes, I believe it should work (please report if it doesn't).

I'm closing this request since it doesn't seem like there's anything else needed on the debugpy side.

**Comment by davetapley** [comment]
@fabioz FYI change requested here. Do you want a new issue or reopen this?

> debugpy would need to add a function, similar to `multiprocessing.freeze_support`, e.g., `debugpy.freeze_support` (which can be no-op in their implementation) that the user calls at the beginning of their entry-point script.

https://github.com/pyinstaller/pyinstaller/issues/5363#issuecomment-872115112
