### ISSUE TITLE
Debug Console with Python expression, excludes last line of output

### ISSUE THREAD

**Issue by martin0** [microsoft/debugpy#493]
Issue Type: <b>Bug</b>

using the debug console to show the value for an expression
consistently the last line of output is not shown.
for example this expression
pd.DataFrame(data={'col1':[1,2,3]})
will only show the first two rows in the dataframe

Extension version: 2020.11.371526539
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19041

**Comment by fabioz** [comment]
It seems to do the right thing for me:

![image](https://user-images.githubusercontent.com/117621/101772885-bfc38a00-3aca-11eb-97f4-1c92585a489d.png)

Can you show how it appears there?

**Comment by fabioz** [comment]
Closing since no additional feedback was provided (@martin0 please reopen when/if you're able to provide more info).
