### ISSUE TITLE
justMyCode set to false causes debugger to hang after a period of timewhen debugging Django with manage.py runserver

### ISSUE THREAD

**Issue by snowberry-clearwing** [microsoft/debugpy#497]
## Environment data

-   VS Code version: 
Version: 1.51.1 (user setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
-   Extension version (available under the Extensions sidebar): v2020.11.371526539
-   OS and version: OS: Windows_NT x64 10.0.18363
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenv
-   Value of the `python.languageServer` setting: Pylance

## Expected behaviour

Happy debugging experience.

## Actual behaviour

After a period of time (minutes) when debugging a Django Python app initiated with _manage.py runserver_ either of two things go wrong:
- If a break point is hit and active, the debugger gets stuck on a break point and becomes unresponsive. Continue/F5 does not advance the execution.
- If have ran through active breakpoints and no breakpoint is currently active, the Django app appears to become unresponsive e.g. it stops responding to requests.

## Steps to reproduce:

1. Launch Django _manage.py runserver_ with `"justMyCode": false` set in launch.json
2. Debug code
3. After a period of minutes either will hang on breakpoint or Django app will stop responding to requests

**Comment by fabioz** [comment]
@snowberry-clearwing Do you think you can share the logs when this happens?

i.e.:

* Open VS Code
* Select the command Extensions: Open Extensions Folder
* Locate the Python extension directory, typically of the form ms-python.python-2020.*.****
* In that directory ensure you do not have any debug*.log files, if you do, please delete them
* Go back into VS Code and modify your launch.json to add the setting "logToFile": true, see below:

```
{
    "name": "Python: Current File (Integrated Terminal)",
    "type": "python",
    "request": "launch",
    "program": "${file}",
    "console": "integratedTerminal",
    "logToFile": true
}
```

* Start debugging
* When done, go back into the extension directory and upload the debug*.log files into this GitHub issue.

**Comment by fabioz** [comment]
Closing since additional feedback was not provided (@snowberry-clearwing please reopen when/if you're able to provide more info).
