### ISSUE TITLE
When debugging python in VSCode, the variable bar cannot display the complete value of the variable.

### ISSUE THREAD

**Issue by Jill-Cheng** [microsoft/debugpy#499]
When debugging python in VSCode, the variable bar cannot display the complete value of the variable.
After right-clicking and selecting "Copy Value", what we get is not the complete value.

![1](https://user-images.githubusercontent.com/61971386/102052326-ecf09f00-3e20-11eb-9205-1aaaefa71449.gif)

My environment:
VSCode Version: 1.52.0 (user setup)
OS: Windows_NT x64 10.0.18363
Python: 3.8
VSCode environment: virtual: Python3.8(."env")

**Comment by karthiknadig** [comment]
This should be addressed by #498
