### ISSUE TITLE
Enable runtime invocation parameters for test runs

### ISSUE THREAD

**Issue by jdmargulici** [microsoft/debugpy#503]
It does not currently appear possible to pass arguments to the test runner when executing or debugging unit tests. This is especially problematic when tests are tagged and one typically wants to execute different test groups or group combinations.

**Comment by fabioz** [comment]
Humm, this would be an issue for the vscode-python extension itself (the debugger doesn't really make the launch configuration, that's up to vscode-python).

Now, having said that, which test runner are you using? In pytest you could specify things in a `pytest.ini` file...

Actually, taking a further look, I think you can actually change the command line in the settings by using
`"python.testing.unittestArgs"` or `"python.testing.pytestArgs"` or `"python.testing.nosetestArgs"` depending on which framework you're using...

**Comment by jdmargulici** [comment]
@fabioz, yes agreed, let me be more specific with what my frustration is.
I'm using pytest and some of these tests are tagged with the pytest.mark functionality. For instance, certain tests connect to online services (arguably they are integration tests rather than unit tests) and I don't want to run them every time I check my unit tests. So these tests are marked with a "cloud" tag, and unless I call pytest with a --cloud argument they will be ignored.
Now if I'm working on a feature that touches those cloud tests, it's true that I can just add "--cloud" to pytestArgs settings and that's a fine solution with one annoying drawback, which is that our workspace settings are under version control. So changing pytestArgs has some undesirable side effects there. And further, I always have the option to run pytest from the command line, which works but that effectively defeats the purpose of a feature-rich IDE like VS Code.
So maybe the underlying issue is really more about being able to make temporary and/or isolated configuration changes to VS Code... But either way, that's my use case and my explanation of why I find it inadequately covered in the current environment.

**Comment by fabioz** [comment]
If the workspace settings are under version control, maybe you could edit the user settings?

You can use a command to open those to edit (using the UI or JSON) and then you can change the settings just for your user as needed:

i.e.:
![image](https://user-images.githubusercontent.com/117621/103213660-10215100-48ed-11eb-84a3-02e1aec4d72c.png)

As a note, if you feel there should be a better way, please create an issue on vscode-python itself (https://github.com/microsoft/vscode-python) as there's not much that can be done regarding that on the debugger side.
