### ISSUE TITLE
Timed out waiting for debuggee to spawn

### ISSUE THREAD

**Issue by bernardo-suez** [microsoft/debugpy#507]
## Environment data

-   VS Code version: 1.52.1
-   Extension version (available under the Extensions sidebar): v2020.12.424452561
-   OS and version: Windows_NT x64 10.016299
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7.6 64-bit Anaconda
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Relevant/affected Python packages and their versions: GeoPandas 0.7.0, NetworkX 2.5, tqdm 4.48.2, Numpy 1.18.1, Pandas 1.0.3, ortools 7.8.7959
-   Relevant/affected Python-related VS Code extensions and their versions: Python 2020.12.424452561, Pylance 2020.12.2
-   Value of the `python.languageServer` setting: Pylance

[**NOTE**: If you suspect that your issue is related to the Microsoft Python Language Server (`python.languageServer: 'Microsoft'`), please download our new language server [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) from the VS Code marketplace to see if that fixes your issue]

## Expected behaviour

Code completes execution when running with debugger

## Actual behaviour

about 12 seconds into the run I get the an alert box showing "Timed out waiting for debuggee to spawn."

## Steps to reproduce:

Unfortunately the code and even more so the data are confidential, so I am unable to share. If there is anything I could run on my end to help debugging the issue I would certainly be glad to help.

## Logs

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by fabioz** [comment]
Can you provide the logs for when this happens?

i.e.:

* Open VS Code
* Select the command Extensions: Open Extensions Folder
* Locate the Python extension directory, typically of the form ms-python.python-2020.*.****
* In that directory ensure you do not have any debug*.log files, if you do, please delete them
* Go back into VS Code and modify your launch.json to add the setting "logToFile": true, see below:

```
{
    "name": "Python: Current File (Integrated Terminal)",
    "type": "python",
    "request": "launch",
    "program": "${file}",
    "console": "integratedTerminal",
    "logToFile": true
}
```

* Start debugging
* When done, go back into the extension directory and upload the debug*.log files into this GitHub issue.

**Comment by bernardo-suez** [comment]
An update to the package we're developing eliminated the problem. I'm closing the issue.
