### ISSUE TITLE
Python Debugging breaks when externalTerminal contains whitespace

### ISSUE THREAD

**Issue by ejabu** [microsoft/debugpy#509]
## Environment data

-   VS Code version: 1.52.1
-   Extension version : 2020.12.424452561
-   OS and version: Windows 10
-   Python version: 3.8

## Expected behaviour

Python Debugging run perfectly

## Actual behaviour

Windows cannot find `'C:Program '`. Make sure you typed the name correctly, and then try again

Timed out waiting for launcher to connect

## Steps to reproduce:

1. Install Windows Terminal via Windows Store
2. set External Terminal in vscode

```
{ 
...
    "terminal.external.windowsExec": "C:\\Program Files\\WindowsApps\\Microsoft.WindowsTerminal_1.4.3243.0_x64__8wekyb3d8bbwe\\wt.exe",
...
}
```

3. Configure Launch.json

```
{
    "name": "Run Python",
    "type": "python",
    "request": "launch",
    "console": "externalTerminal",    // < ------- add this line
    "python": "C:\\Program Files (x86)\\Python\\python.exe",
    "program": "C:\\dev\\server-bin",
},
```
4. Run Debugger

## Logs

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
No Output
```

</p>
</details>

**Comment by fabioz** [comment]
Humm, I don't think this is even managed by debugpy (that's managed by VSCode itself).

Now, having said that, have you tried quoting it?

i.e.: surround by `\"`:

```
"terminal.external.windowsExec": "\"C:\\Program Files\\WindowsApps\\Microsoft.WindowsTerminal_1.4.3243.0_x64__8wekyb3d8bbwe\\wt.exe\"",
```

**Comment by int19h** [comment]
Yep, we just submit a "runInTerminal" request to VSCode. Everything it does wrt spaces and quoting is not under our control.

As a workaround, try using just "wt" by itself as the property value - you should have that on PATH already if you installed it from store.

**Comment by fabioz** [comment]
I don't think we can do anything about it on `debugpy` and the workarounds proposed such as quoting or having it on the `PATH` and not having spaces on the specified terminal should work, so, I'm closing this.
