### ISSUE TITLE
Python debugging not working

### ISSUE THREAD

**Issue by maheshch123** [microsoft/debugpy#513]
https://user-images.githubusercontent.com/59368762/103337953-d72add00-4aa2-11eb-9942-6a4155d0faa2.mp4

**Comment by fabioz** [comment]
I can't reproduce this (`cmd` is properly defined for me).

It seems strange that it's not defined for you as it should be in the `PATH`.

Here, by doing `where cmd`, it says it's defined at:

`C:\Windows\System32\cmd.exe`

Can you double check if it's there for you and whether `C:\Windows\System32` is in your `PATH` environment variable?

**Comment by maheshch123** [comment]
here is the path
![issue1](https://user-images.githubusercontent.com/59368762/103411974-0b80c500-4b99-11eb-9f09-52107d82dc7f.jpg)
![issue2](https://user-images.githubusercontent.com/59368762/103411988-19cee100-4b99-11eb-9475-e32229c322f0.jpg)

**Comment by maheshch123** [comment]
here is the path
![issue2](https://user-images.githubusercontent.com/59368762/103412111-a2e61800-4b99-11eb-8dcf-f8267b2700af.jpg)
![issue3](https://user-images.githubusercontent.com/59368762/103412128-ada0ad00-4b99-11eb-987a-4820c9bbfa36.jpg)

**Comment by fabioz** [comment]
It seems it's not really there... can you try adding `c:\windows\system32` (then restarting VSCode) and see if it works?

**Comment by maheshch123** [comment]
still getting the same error

**Comment by fabioz** [comment]
I think you still have an old version of the path somehow...

Can you write in the terminal:

```
set PATH=%PATH%;c:\windows\system32
```

and then try to run the debugger again (which should use that same terminal)...

If it still doesn't, work, please provide the output of running the following in that terminal:

```
where cmd
dir c:\windows\system32
echo %PATH%
```

**Comment by maheshch123** [comment]
the problem is i the set wrong path C:\Windows\System\32 instead of C:\Windows\System32, now its working thanks

**Comment by maheshch123** [comment]
the problem is i the set wrong path C:\Windows\System\32 instead of C:\Windows\System32, now its working thanks
