### ISSUE TITLE
Support showing source using uncompyle

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/debugpy#516]
@int19h: We shouldn't need this for cells, since all source code for them is available via linecache (IPython ensures that every line is present there and does not expire).

**Comment by fabioz** [comment]
@karthiknadig one of the main issues here is that uncompyle is GPL (and I don't know of any other library implementing this...).

Given that I don't think we can use a GPL library, the only solution I see would be implementing this ourselves (which would take quite a while...).

Note that we already do some work to show some bytecode representation that tries to keep lines consistent if the source code is not available via linecache (although that's definitely not as nice as having the actual code).

**Comment by int19h** [comment]
This is an old feature request that we just carried over. There's no work expected to be happening on it yet, and the priorities are unset.

That said, one possibility would be to not redistribute uncompyle, but use it if it's installed (i.e. can be imported).

**Comment by int19h** [comment]
No traction on this to date; closing until we decide we actually need it.
