### ISSUE TITLE
Python debugger extension support

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/debugpy#517]
Currently we have two asks that can be potentially done as extensions:
1. Custom variable filtering. (ask from DS team): For these kinds of features, @int19h suggested providing hooks into the dap messaging itself, in `before`, `after` style. 

2. Custom formatting for variables. (ask from DS team)

How we do debugger extensions is also open for discussion. 
1. We could, use `entrypoint` feature in `setuptools` for this. 
2. Providing a dir to pickup extensions from.

The idea is to eventually allow supporting new frameworks entirely via extensions.

**Comment by fabioz** [comment]
As a note, there's already an extension mechanism in `pydevd` for custom formatting of variables.

See: https://github.com/microsoft/debugpy/tree/main/src/debugpy/_vendored/pydevd/pydevd_plugins/extensions

**Comment by fabioz** [comment]
For an example which can provide a custom string representation see:
https://github.com/microsoft/debugpy/blob/main/src/debugpy/_vendored/pydevd/pydevd_plugins/extensions/types/pydevd_plugins_django_form_str.py 

For an example which changes the actual structure see:
https://github.com/microsoft/debugpy/blob/main/src/debugpy/_vendored/pydevd/pydevd_plugins/extensions/types/pydevd_plugin_numpy_types.py

**Comment by int19h** [comment]
The original DS asks were resolved in other ways, and beyond that there are no specific scenarios for this. Closing until we decide we actually need it.
