### ISSUE TITLE
Secure remote connections to the debugger

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/debugpy#518]
currently the recommended way is to use SSH to connect to remotes. We no longer use 'secret' because it never provided a secure channel. Use this item to discus what we should do.

**Comment by flxmr** [comment]
> We no longer use 'secret' because it never provided a secure channel

What would you recommend for multiuser-systems then?

**Comment by int19h** [comment]
SSH tunnel is the recommended transport if you need authentication (or security in general).

**Comment by flxmr** [comment]
That is a very interesting proposition for a multiuser-system. Aka UIDs map to multiple physical users and all those share one network namespace. I would be connecting with SSH to said multi-user system. The easiest solution would be to start the server on a domain socket...
