### ISSUE TITLE
Native trace function

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/debugpy#520]
We might want to look at how this is done in the mixed-mode debugger, by directly accessing `PyThreadState` (and whether it's possible at all using Python public APIs).

If this can be done, it allows setting tracing for all the frames on all the active threads at once - i.e. there's no issue with code that was already there before attaching not being traced. I don't think this is possible with `sys.settrace`, or even with `PyEval_SetTrace`, because they only apply to the current thread.

Relevant code in MMD:

https://github.com/microsoft/PTVS/blob/4e46bdd6b8deffc8696f11aee1dbd20326c28ab9/Python/Product/Debugger.Concord/TraceManagerLocalHelper.cs#L327-L332

https://github.com/microsoft/PTVS/blob/4e46bdd6b8deffc8696f11aee1dbd20326c28ab9/Python/Product/Debugger.Concord/TraceManagerLocalHelper.cs#L283-L290

Note that this might look more complex than it really is, because it has to handle 2.7 and 3.3+ with the same code - distinguishing between them at _runtime_; and also because it does that all out-of-process, by peeking and poking bytes inside the Python process. For ptvsd/pydevd, we'd be doing this all in-proc, and we can just `#include <python.h>` directly, and build separate binaries for every supported version (or let the users build them from source), just like any regular Python package with native code in it.

**Comment by fabioz** [comment]
@karthiknadig the debugger actually uses a native trace function to set the tracing to all active threads (which is also used in the attach to process).

Also, using the frame eval mode (in 3.6 onwards with compiled extensions) it's able to detect new native threads and set the tracing accordingly.

Given that, I don't think we need additional effort here.

**Comment by fabioz** [comment]
Closing since we already use a native thread function.

i.e.: 

https://github.com/microsoft/debugpy/blob/main/src/debugpy/_vendored/pydevd/pydevd_attach_to_process/common/py_settrace.hpp

https://github.com/microsoft/debugpy/blob/main/src/debugpy/_vendored/pydevd/pydevd_attach_to_process/common/py_custom_pyeval_settrace.hpp
