### ISSUE TITLE
Hiding built-in variables when debugging through Visual Studio

### ISSUE THREAD

**Issue by AdamYoblick** [microsoft/debugpy#521]
The PTVS team has a feedback ticket (https://developercommunity2.visualstudio.com/t/python-378-debugging-using-vs2019-16/1283690) asking if there's a way to hide built-ins in the VS watch list. Is this a debugpy issue, or is this something custom that would have to be done in VS?

The customer indicated that this is a regression and it worked in VS2017, but that would be using ptvsd instead of debugpy I'm pretty sure.

I'm new to the PTVS team, sorry if this is a silly question. 😄 

## Environment data

- debugpy version: Unknown
- OS and version: Unknown
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.7.8
- Using VS Code or Visual Studio: Visual Studio 16.8.3

## Actual behavior

Built-ins are shown, and unable to be hidden

## Expected  behavior

Built-ins are able to be hidden

## Steps to reproduce:
1. Inspect an object in the watch list containing built-in methods
![image](https://user-images.githubusercontent.com/29436557/103687054-46964600-4f55-11eb-8de6-c10408e2a74b.png)

**Comment by fabioz** [comment]
Hi @AdamYoblick,

That was actually a feature added to `debugpy`. It's possible to hide it by customizing the `variablePresentation` in the `launch` config.

See: https://stackoverflow.com/a/62401205/110451 for details.

As a client, PTVS can choose to send a custom `variablePresentation` in the launch request.

**Comment by AdamYoblick** [comment]
Awesome, thank you for the info :)
