### ISSUE TITLE
Silent exit (no traceback) on uncaught exception

### ISSUE THREAD

**Issue by arijun** [microsoft/debugpy#530]
## Environment data

- debugpy version:   1.2.1
- OS and version: Debian GNU/Linux 8.10 (via vscode Remote extension)
- Python version: Python 3.7.3 with Anaconda
- Using VS Code or Visual Studio: VS Code

## Actual behavior

Breakpoints and exceptions cause the debugger to silently exit with exit code 245 (without even printing a traceback)

## Expected  behavior

Debugger pauses

## Steps to reproduce:
This doesn't happen everywhere in my code, e.g. it's fine in my main.py.

```
        print('before break')
        print('break')  <-- breakpoint here
        assert False
```

It prints `before break` and then exits with exit code 245 . If I remove the breakpoint, it prints `before break` followed by `break` and then exits. If I run normally I get the expected output of a normal traceback.

I think this must be related to the abstraction model my company uses for running on the cloud. It's running locally in this case, but maybe it does something weird with the threads (although where I'm trying to throw an assert is still on the main thread afaict)

**Comment by fabioz** [comment]
Can you provide the logs when this happens?

i.e.:

* Open VS Code
* Select the command Extensions: Open Extensions Folder
* Locate the Python extension directory, typically of the form ms-python.python-2020.*.****
* In that directory ensure you do not have any debug*.log files, if you do, please delete them
* Go back into VS Code and modify your launch.json to add the setting "logToFile": true, see below:

```
{
    "name": "Python: Current File (Integrated Terminal)",
    "type": "python",
    "request": "launch",
    "program": "${file}",
    "console": "integratedTerminal",
    "logToFile": true
}
```

* Start debugging
* When done, go back into the extension directory and upload the debug*.log files into this GitHub issue.

Another thing to check: can you run with `faulthandler` enabled and see if it shows something? (i.e.: https://docs.python.org/3/library/faulthandler.html)

**Comment by arijun** [comment]
Here are the requested files, lightly edited to remove identifying information.

[debugpy.launcher-19300.log](https://github.com/microsoft/debugpy/files/5842999/debugpy.launcher-19300.log)
[debugpy.pydevd.19312.log](https://github.com/microsoft/debugpy/files/5843000/debugpy.pydevd.19312.log)
[debugpy.server-19312.log](https://github.com/microsoft/debugpy/files/5843001/debugpy.server-19312.log)
[debugpy.adapter-19289.log](https://github.com/microsoft/debugpy/files/5843003/debugpy.adapter-19289.log)

[Results from the fault handler ](https://github.com/microsoft/debugpy/files/5843002/traceback.log). The thread that had the breakpoint was the last on that list, 0x00007ffff7fbb700

**Comment by fabioz** [comment]
This is really a bit weird... `faulthandler` says that the thread that was running when the crash occurred was inside of `json.dumps`

```
Current thread 0x00007ffff53c9700 (most recent call first):
  File "/localhomes/user/anaconda/envs/ds_conda/lib/python3.7/json/encoder.py", line 256 in iterencode
  File "/localhomes/user/anaconda/envs/ds_conda/lib/python3.7/json/encoder.py", line 199 in encode
  File "/localhomes/user/anaconda/envs/ds_conda/lib/python3.7/json/__init__.py", line 238 in dumps
  File "/homes/user/.vscode-server/extensions/ms-python.python-2020.12.424452561/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command_json.py", line 163 in process_net_command_json
  File "/homes/user/.vscode-server/extensions/ms-python.python-2020.12.424452561/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 258 in _on_run
  File "/homes/user/.vscode-server/extensions/ms-python.python-2020.12.424452561/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_daemon_thread.py", line 46 in run
  File "/localhomes/user/anaconda/envs/ds_conda/lib/python3.7/threading.py", line 917 in _bootstrap_inner
  File "/localhomes/user/anaconda/envs/ds_conda/lib/python3.7/threading.py", line 885 in _bootstrap
```

So, I'm not sure what to make of this (my guess is that something else became corrupted and this is a side effect, but I don't really know what in this case).

The logs already show that it's not really using any compiled extensions (which would be used for speed ups), which would be the usual culprit here.

So, can you do some changes and rerun your test there?

1. Disable the `showReturnValue` (the side effect of this is that some frames/data may end up living longer, so, try disabling to see if it does any difference there).
2. Set an environment variable: `PYDEVD_LOAD_NATIVE_LIB=0` (pydevd has some custom tracing using a dll, so, it may make some difference there as that code is compiled -- with this setting, nothing should be compiled).

Run as before and provide a new faulthandler output/logs with these changes in place.

**Comment by arijun** [comment]
Here are the files with the changes

[debugpy.launcher-3222.log](https://github.com/microsoft/debugpy/files/5862859/debugpy.launcher-3222.log)
[debugpy.pydevd.3228.log](https://github.com/microsoft/debugpy/files/5862860/debugpy.pydevd.3228.log)
[debugpy.server-3228.log](https://github.com/microsoft/debugpy/files/5862861/debugpy.server-3228.log)
[traceback.log](https://github.com/microsoft/debugpy/files/5862862/traceback.log)
[debugger.vscode_27145e50-9d00-4e04-ad5f-c71a68443202.log](https://github.com/microsoft/debugpy/files/5862863/debugger.vscode_27145e50-9d00-4e04-ad5f-c71a68443202.log)
[debugpy.adapter-3212.log](https://github.com/microsoft/debugpy/files/5862864/debugpy.adapter-3212.log)

**Comment by fabioz** [comment]
As far as I can see, the issue isn't really in the debugger (it's just using pure-python code).

What's the usual culprit here is that the debugger is exercising your code in different ways (usually accessing frame locals) and that makes your program crash. Given that, I don't think there's much to be done in the debugger (in such cases, what you need to do is find out the crash in your own application... usually using a native debugger such gdb for Linux).
