### ISSUE TITLE
Variable preview when debugging shows extra characters in the middle of a string

### ISSUE THREAD

**Issue by mattwelke** [microsoft/debugpy#534]
## Environment data

-   VS Code version: 1.52.1 (user setup)
-   Extension version (available under the Extensions sidebar): 2021.1.502429796
-   OS and version: Windows 10 Pro and Ubuntu 20.04 (using WSL 2)
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.1
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Poetry
-   Relevant/affected Python packages and their versions: n/a
-   Relevant/affected Python-related VS Code extensions and their versions: n/a
-   Value of the `python.languageServer` setting: Pylance

## Expected behaviour

When debugging a Python file, the "Variables" panel shows the correct value of all variables.

## Actual behaviour

For a particular variable in my program, the incorrect string value is displayed. The correct string value is displayed when I expand the variable (it is a list) and all lists inside it:

![image](https://user-images.githubusercontent.com/7719209/105790852-0d009b80-5f53-11eb-8376-a2208803388c.png)

The problematic part is the "saffron bathing suit... for women" string. The string in question has no "..." in it. This only shows up in some parts of the variable preview for the debugger.

Here's an animated version that attempts to show all situations where the extra characters appear and don't appear. Note that they appear in both Variables and Watch, and appear for the mouse hover over in each:

![vscode_python_bad_var_preview](https://user-images.githubusercontent.com/7719209/105790961-37eaef80-5f53-11eb-9307-8a8ae2fa0cad.gif)

## Steps to reproduce:

Unknown right now. This is a proprietary codebase that I can't share that generates random strings from a static corpus. I don't know of a minimal reproduction right now.

## Logs

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'ShowExtensionSurveyPrompt - control'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - experiment'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - control'
User belongs to experiment group 'LocalZMQKernel - experiment'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
User belongs to experiment group 'EnableIPyWidgets - experiment'
User belongs to experiment group 'RunByLine - experiment'
User belongs to experiment group 'CustomEditorSupport - control'
User belongs to experiment group 'pythonaacf'
User belongs to experiment group 'pythonSendEntireLineToREPL'
User belongs to experiment group 'pythonInstallPylintButtonFirst'
> pyenv root
> conda --version
> python3.7 ~/.vscode-server/extensions/ms-python.python-2021.1.502429796/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 ~/.vscode-server/extensions/ms-python.python-2021.1.502429796/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 ~/.vscode-server/extensions/ms-python.python-2021.1.502429796/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 ~/.vscode-server/extensions/ms-python.python-2021.1.502429796/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode-server/extensions/ms-python.python-2021.1.502429796/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> ~/.cache/pypoetry/virtualenvs/wisdom-demo-beacon-generator-Z4YO5UZC-py3.9/bin/python ~/.vscode-server/extensions/ms-python.python-2021.1.502429796/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> conda info --json
Error 2021-01-25 09:35:40: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file 'vscode-remote://wsl+ubuntu/home/matt/.config/Code/User/settings.json' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/home/matt/.config/Code/User/settings.json')
	at _handleError (/home/matt/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:769:473)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async y.readText (/home/matt/.vscode-server/extensions/ms-python.python-2021.1.502429796/out/client/extension.js:9:344778)
	at async p.doesFileNeedToBeFixed (/home/matt/.vscode-server/extensions/ms-python.python-2021.1.502429796/out/client/extension.js:59:500280)
	at async /home/matt/.vscode-server/extensions/ms-python.python-2021.1.502429796/out/client/extension.js:59:499407
	at async Promise.all (index 0)
	at async p.getFilesToBeFixed (/home/matt/.vscode-server/extensions/ms-python.python-2021.1.502429796/out/client/extension.js:59:499353)
	at async p.updateTestSettings (/home/matt/.vscode-server/extensions/ms-python.python-2021.1.502429796/out/client/extension.js:59:498980)] {
  code: 'FileNotFound',
  name: 'EntryNotFound (FileSystemError)'
}
Starting Pylance language server.
Python interpreter path: ~/.cache/pypoetry/virtualenvs/wisdom-demo-beacon-generator-Z4YO5UZC-py3.9/bin/python
> pyenv root
> pyenv root
> pyenv root
> conda --version
> ~/.cache/pypoetry/virtualenvs/wisdom-demo-beacon-generator-Z4YO5UZC-py3.9/bin/python ~/.vscode-server/extensions/ms-python.python-2021.1.502429796/pythonFiles/pyvsc-run-isolated.py autopep8 --diff ~/code/github.com/groupby/wisdom-demo-beacon-generator/wisdom_demo_beacon_generator/search_performer.py.ffc92f0251418e92d04fd21e19876cde.tmp
cwd: ~/code/github.com/groupby/wisdom-demo-beacon-generator
> ~/.cache/pypoetry/virtualenvs/wisdom-demo-beacon-generator-Z4YO5UZC-py3.9/bin/python ~/.vscode-server/extensions/ms-python.python-2021.1.502429796/pythonFiles/pyvsc-run-isolated.py autopep8 --diff ~/code/github.com/groupby/wisdom-demo-beacon-generator/wisdom_demo_beacon_generator/search_performer.py.ffc92f0251418e92d04fd21e19876cde.tmp
cwd: ~/code/github.com/groupby/wisdom-demo-beacon-generator
> ~/.cache/pypoetry/virtualenvs/wisdom-demo-beacon-generator-Z4YO5UZC-py3.9/bin/python ~/.vscode-server/extensions/ms-python.python-2021.1.502429796/pythonFiles/pyvsc-run-isolated.py autopep8 --diff ~/code/github.com/groupby/wisdom-demo-beacon-generator/wisdom_demo_beacon_generator/search_performer.py
cwd: ~/code/github.com/groupby/wisdom-demo-beacon-generator
> ~/.cache/pypoetry/virtualenvs/wisdom-demo-beacon-generator-Z4YO5UZC-py3.9/bin/python ~/.vscode-server/extensions/ms-python.python-2021.1.502429796/pythonFiles/pyvsc-run-isolated.py autopep8 --diff ~/code/github.com/groupby/wisdom-demo-beacon-generator/wisdom_demo_beacon_generator/search_performer.py
cwd: ~/code/github.com/groupby/wisdom-demo-beacon-generator
> ~/.cache/pypoetry/virtualenvs/wisdom-demo-beacon-generator-Z4YO5UZC-py3.9/bin/python ~/.vscode-server/extensions/ms-python.python-2021.1.502429796/pythonFiles/pyvsc-run-isolated.py autopep8 --diff ~/code/github.com/groupby/wisdom-demo-beacon-generator/wisdom_demo_beacon_generator/app.py
cwd: ~/code/github.com/groupby/wisdom-demo-beacon-generator
> ~/.cache/pypoetry/virtualenvs/wisdom-demo-beacon-generator-Z4YO5UZC-py3.9/bin/python ~/.vscode-server/extensions/ms-python.python-2021.1.502429796/pythonFiles/pyvsc-run-isolated.py autopep8 --diff ~/code/github.com/groupby/wisdom-demo-beacon-generator/wisdom_demo_beacon_generator/app.py
cwd: ~/code/github.com/groupby/wisdom-demo-beacon-generator
> ~/.cache/pypoetry/virtualenvs/wisdom-demo-beacon-generator-Z4YO5UZC-py3.9/bin/python ~/.vscode-server/extensions/ms-python.python-2021.1.502429796/pythonFiles/pyvsc-run-isolated.py autopep8 --diff ~/code/github.com/groupby/wisdom-demo-beacon-generator/wisdom_demo_beacon_generator/search_corpus.py
cwd: ~/code/github.com/groupby/wisdom-demo-beacon-generator
> ~/.cache/pypoetry/virtualenvs/wisdom-demo-beacon-generator-Z4YO5UZC-py3.9/bin/python ~/.vscode-server/extensions/ms-python.python-2021.1.502429796/pythonFiles/pyvsc-run-isolated.py autopep8 --diff ~/code/github.com/groupby/wisdom-demo-beacon-generator/wisdom_demo_beacon_generator/search_corpus.py
cwd: ~/code/github.com/groupby/wisdom-demo-beacon-generator
> ~/.cache/pypoetry/virtualenvs/wisdom-demo-beacon-generator-Z4YO5UZC-py3.9/bin/python ~/.vscode-server/extensions/ms-python.python-2021.1.502429796/pythonFiles/pyvsc-run-isolated.py autopep8 --diff ~/code/github.com/groupby/wisdom-demo-beacon-generator/wisdom_demo_beacon_generator/app.py
cwd: ~/code/github.com/groupby/wisdom-demo-beacon-generator
> ~/.cache/pypoetry/virtualenvs/wisdom-demo-beacon-generator-Z4YO5UZC-py3.9/bin/python ~/.vscode-server/extensions/ms-python.python-2021.1.502429796/pythonFiles/pyvsc-run-isolated.py autopep8 --diff ~/code/github.com/groupby/wisdom-demo-beacon-generator/wisdom_demo_beacon_generator/app.py
cwd: ~/code/github.com/groupby/wisdom-demo-beacon-generator
```

</p>
</details>

**Comment by int19h** [comment]
This is intentional. We have to trim the variable repr to ensure that overly long strings don't break UX. For lists and other collections, it's done recursively for their elements at any level of nesting. The logic is a bit convoluted, and sometimes it might decide to trim when it didn't strictly have to. But note that you can still observe the full string if you expand the collection.

**Comment by mattwelke** [comment]
@int19h I see. That explains why I can see the full string by expanding the collection.

But, I have to say, this just added confusion for me from a UX perspective. There's already some truncation happening in a spot that makes sense - the far right of the strings (to the right of "ties" in my GIF). The fact it's an elipses character used helped me realize it was a part of the VS Code UI and not part of my data itself. But inside the preview for that one string, it used three period characters instead of an elipse. There was nothing to tell me this was part of the VS Code UI and not my data itself, especially because that string was truncated in that way even though there was another string to the right of it.

**Comment by int19h** [comment]
It looks like VSCode itself might also be doing some trimming on the variable value in its UI. Note that the ellipsis is not inside the quotes - that is, it's not trimming the string literal, but rather the entire list literal. The logic in debugpy is a bit smarter than that - it tries to trim values where it "makes sense", e.g. at the end of string literals, or at the end of list literals after a comma. 

The problem there is that we can't just rely on VSCode doing it for two reasons: firstly, it's not the only client that debugpy supports, and others - e.g. VS - require the debug adapter to take care of it. Furthermore, if we don't trim the values, we end up sending potentially very large blocks of data over a socket, which would slow down debugging a lot. 

I'll see if there's anything we can do here to better coordinate this between debugpy and VSCode.
