### ISSUE TITLE
Cannot attach to process in Azure ML remote window.

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/debugpy#537]
## Environment data

- debugpy version: 1.2.1
- OS and version: Linux (Azure ML Compute Instance)
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.9, Anaconda
- Using VS Code or Visual Studio: VS Code (Remote)

## Actual behavior

Breakpoints in scripts (for which process is running) are not hit. Connection times out waiting for a debug server to connect to.

## Expected  behavior

Process attached to successfully and breakpoints are hit.

## Steps to reproduce:
1. Connect to compute instance through the AML extension.
2. Create a script with an infinite loop. Set a breakpoint within the loop.
3. Create an "Attach using Process ID" debug configuration.
4. Run the script in the terminal.
5. Start the PID attach debugger and choose your recently invoked process.
6. Check if breakpoints are hit.

**Comment by SiddhanthUnnithan** [comment]
Here is a video showing the issue:

https://user-images.githubusercontent.com/6413608/106324610-4c1e3d80-622e-11eb-83e0-07f3492f08f2.mp4

**Comment by karthiknadig** [comment]
Can you put `sleep` in the loop?

**Comment by SiddhanthUnnithan** [comment]
Added time.sleep( N ) but it never executed the print statement.

**Comment by SiddhanthUnnithan** [comment]
Seeing the same issue with the timeout.

**Comment by SiddhanthUnnithan** [comment]
@karthiknadig is there anything else that I should try to extend the time to connect?

**Comment by karthiknadig** [comment]
No. We will need logs though. Set `"logToFile": true` in the debug configuration. This should put the logs in `~\.vscode\extensions\ms-python.python` (the .vscode part could be .vscode-server). The log files all end with `*.log`, and there will be multiple of them. Please uplaod all of them.

**Comment by fabioz** [comment]
One thing to note is that on Linux the debugger uses `gdb` to connect, in which case you need to have `gdb` installed and you also need to have the proper `ptrace` configuration (see: https://stackoverflow.com/questions/19215177/how-to-solve-ptrace-operation-not-permitted).

@SiddhanthUnnithan I'm closing because the logs weren't provided. If you're still interested in diagnosing this issue, please provide the logs that are obtained from that launch.
