### ISSUE TITLE
Module import error only when debugging

### ISSUE THREAD

**Issue by chrissyast** [microsoft/debugpy#540]
## Environment data

- debugpy version: Unknown. `import debugpy; print(debugpy.__version__)` results in 'no module named debugpy'. When debugging through VS Code, shows (`\.vscode\extensions\ms-python.python-2021.1.502429796\pythonFiles\lib\python\debugpy\launcher'`)
- OS and version: Win 10
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.6.7
- Using VS Code or Visual Studio: VS Code

### resource.py
```
class MyAPI():
#some code
```

### main.py
```
from resource import LettersAPI
```

### launch.json
```
        {
            "name": "Python: Foo",
            "type": "python",
            "request": "launch",
            "module": "flask",
            "env": {
                "FLASK_APP": "path/to/my/app/main.py",
                "FLASK_ENV": "development",
                "FLASK_DEBUG": "0",
                "PYTHONPATH": "${workspaceRoot}"
            },
            "args": ["run", "--port", "5002"],
            "console": "integratedTerminal"
        },
```

## Steps to reproduce:
1. Run `C:/Python/Python36-7/python.exe "path/to/my/app/main.py"` from terminal
2. Observe working fine
3. Run `Python: Foo` debug config

## Actual behavior

`ModuleNotFoundError: No module named 'resource'`

## Expected behavior

Debug session starts fine

## What I've tried

Adding the python path to env
Adding the file path to `"python.autoComplete.extraPaths"` ([here](https://github.com/microsoft/python-language-server/issues/1085#issuecomment-493756360))

**Comment by fabioz** [comment]
It seems you have an issue in the PYTHONPATH configuration...

Can you provide the information below?

1. What is your project structure (i.e.: where's your main file, where's your `${workspaceRoot}` and where's the `resources` package.

2. Run the code below and provide the output you have (in the case where it works as well as the case where it doesn't work).

```
import sys
print('\n'.join(sorted(sys.path)))

import resource
print(resource)
```

**Comment by fabioz** [comment]
Closing as additional information wasn't provided.
