### ISSUE TITLE
Don't stop all the threads on a breakpoint

### ISSUE THREAD

**Issue by JohanMabille** [microsoft/debugpy#547]
Hi,

Is there a way to keep a given Python thread running when a breakpoint is hit in a multithreaded application? I could implement a workaround using QT Thread, but I would prefer to stick with Python threads if possible.

Thanks!

**Comment by fabioz** [comment]
Even QT Threads will be stopped on Python 3.6 onwards (when native extensions are available).

Now, having said that, you can actually mark Python threads so that they aren't really traced/tracked by the debugger by setting the following attributes in the thread:

```
thread.pydev_do_not_trace = True
thread.is_pydev_daemon_thread = True
```

**Comment by JohanMabille** [comment]
Worked like a charm, thanks, you saved my day!

**Comment by int19h** [comment]
If there's a recurring need for this, we might want to expose it as a documented API with stability guarantees.
