### ISSUE TITLE
../sysdeps/unix/sysv/linux/epoll_wait.c: No such file or directory

### ISSUE THREAD

**Issue by aantn** [microsoft/debugpy#553]
## Environment data

- debugpy version: 1.2.1
- OS and version: Linux 5.4.49+ SMP x86_64 
- Using VS Code or Visual Studio: neither

## Bug
I am trying to run debugpy inside a container directly without visual studio or vscode. debugpy crashes because it can't find /sysdeps/unix/sysv/linux/epoll_wait.c

## Full output:
```
python3 -m debugpy --connect 1010 --pid 2744026
Attaching with arch: i386:x86-64
Running: gdb --nw --nh --nx --pid 2744026 --batch --eval-command='set scheduler-locking off' --eval-command='set architecture i386:x86-64' --eval-command='call (void*)dlopen("/usr/local/lib/python3.6/dist-packages/debugpy/_vendor
ed/pydevd/pydevd_attach_to_process/attach_linux_amd64.so", 2)' --eval-command='call (int)DoAttach(0, "import codecs;import json;import sys;decode = lambda s: codecs.utf_8_decode(bytearray(s))[0] if s is not None else None;script_
dir = decode([47, 117, 115, 114, 47, 108, 111, 99, 97, 108, 47, 108, 105, 98, 47, 112, 121, 116, 104, 111, 110, 51, 46, 54, 47, 100, 105, 115, 116, 45, 112, 97, 99, 107, 97, 103, 101, 115, 47, 100, 101, 98, 117, 103, 112, 121, 47
, 115, 101, 114, 118, 101, 114]);setup = json.loads(decode([123, 34, 109, 111, 100, 101, 34, 58, 32, 34, 99, 111, 110, 110, 101, 99, 116, 34, 44, 32, 34, 97, 100, 100, 114, 101, 115, 115, 34, 58, 32, 91, 34, 49, 50, 55, 46, 48, 4
6, 48, 46, 49, 34, 44, 32, 49, 48, 49, 48, 93, 44, 32, 34, 119, 97, 105, 116, 95, 102, 111, 114, 95, 99, 108, 105, 101, 110, 116, 34, 58, 32, 102, 97, 108, 115, 101, 44, 32, 34, 108, 111, 103, 95, 116, 111, 34, 58, 32, 110, 117, 
108, 108, 44, 32, 34, 97, 100, 97, 112, 116, 101, 114, 95, 97, 99, 99, 101, 115, 115, 95, 116, 111, 107, 101, 110, 34, 58, 32, 110, 117, 108, 108, 125]));sys.path.insert(0, script_dir);import attach_pid_injected;del sys.path[0];a
ttach_pid_injected.attach(setup);", 0)'
Running gdb in target process.
stdout: b'[New LWP 2744095]\n[New LWP 2744097]\n[New LWP 2744099]\n[New LWP 2744100]\n[New LWP 2744427]\n[New LWP 2744432]\n[New LWP 2744433]\n[New LWP 2744434]\n[New LWP 2744435]\n[New LWP 2744638]\n[New LWP 2744685]\n[New LWP 2
744724]\n[New LWP 2744762]\n[New LWP 2744780]\n[New LWP 2744809]\n[New LWP 2744845]\n[New LWP 2744879]\n[New LWP 2744895]\n[New LWP 2744928]\n[Thread debugging using libthread_db enabled]\nUsing host libthread_db library "/lib/x8
6_64-linux-gnu/libthread_db.so.1".\n0x00007f01c0af3a47 in epoll_wait (epfd=3, events=events@entry=0x7ffedd6c9710, maxevents=maxevents@entry=1024, timeout=timeout@entry=100) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30\nThe targe
t architecture is assumed to be i386:x86-64\n$1 = (void *) 0x2204ef0\n$2 = 0\n'
stderr: b'30\t../sysdeps/unix/sysv/linux/epoll_wait.c: No such file or directory.\n'
```

**Comment by int19h** [comment]
debugpy (or rather pydevd) uses gdb to implement attach to process by PID. This error message looks like it's coming from gdb. You need to make whatever changes are necessary for the container to run `gdb --pid`.

**Comment by aantn** [comment]
This still seems like an error as the missing epoll_wait.c source code has nothing to do with the way pydevd injects as far as I can tell. This is what I'm attempting to do:

```

**Comment by int19h** [comment]
Does your second command also not work? This one doesn't involve attach to PID, so it shouldn't be starting gdb at all. If it fails, what error messages are you seeing in that case?

**Comment by aantn** [comment]
I might just be donig something wrong here. I thought you had to run the first command to inject the debugger and then the second command to attach to the debugger.

It looks like the injection is sucessful as this appears in the output of the debugged process:
```
E+01408.145: Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/debugpy/server/api.py", line 218, in listen
sock, _ = endpoints_listener.accept()
File "/usr/lib/python3.6/socket.py", line 205, in accept
fd, addr = self._accept()
socket.timeout: timed out

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/debugpy/server/attach_pid_injected.py", line 77, in attach
debugpy.listen(setup["address"])
File "/usr/local/lib/python3.6/dist-packages/debugpy/__init__.py", line 113, in listen
return api.listen(address)
File "/usr/local/lib/python3.6/dist-packages/debugpy/server/api.py", line 143, in debug
log.reraise_exception("{0}() failed:", func.__name__, level="info")
File "/usr/local/lib/python3.6/dist-packages/debugpy/server/api.py", line 141, in debug
return func(address, settrace_kwargs, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/debugpy/server/api.py", line 232, in listen
raise RuntimeError("timed out waiting for adapter to connect")
RuntimeError: timed out waiting for adapter to connect

Stack where logged:
File "/usr/local/bin/uvicorn", line 8, in <module>
sys.exit(main())
File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 829, in __call__
return self.main(*args, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 782, in main
...
```

**Comment by aantn** [comment]
Am I missing some flag which causes the injected debugpy to wait around for a connection?

**Comment by int19h** [comment]
The injected debugpy should respect your `--listen` or `--connect` flags. Basically it's the same as if you did `--listen ... foo.py`, except that `foo.py` is already running, and so you provide a PID instead.

However, this particular message in the log means that it didn't quite get to that point. Specifically, it couldn't spawn the debug adapter process (or it could, but then it couldn't connect to it). This is a different connection than the one that comes from the client, and normally it's all done transparently. 

Logs would help diagnose it better. If you add `--log-to ...` to your debugpy command line, it'll create a bunch of `debugpy*.log` files in the specified directory - can you share those?

**Comment by aantn** [comment]
`--log-to` doesn't seem to do anything for the `--listen` command.

I just noticed the additional output in the debugged program before the output I posted earlier:

```
Could not connect to 127.0.0.1: 45635
 Traceback (most recent call last):
   File "/usr/local/lib/python3.6/dist-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 464, in start_client
     s.connect((host, port))
 ConnectionRefusedError: [Errno 111] Connection refused
 Could not connect to 127.0.0.1: 45635
 Traceback (most recent call last):
   File "/usr/local/lib/python3.6/dist-packages/debugpy/_vendored/pydevd/pydevd.py", line 3202, in main
     debugger.connect(host, port)
   File "/usr/local/lib/python3.6/dist-packages/debugpy/_vendored/pydevd/pydevd.py", line 1262, in connect
     s = start_client(host, port)
   File "/usr/local/lib/python3.6/dist-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 464, in start_client
     s.connect((host, port))
 ConnectionRefusedError: [Errno 111] Connection refused
 Exception ignored when trying to write to the signal wakeup fd:
 BlockingIOError: [Errno 11] Resource temporarily unavailable
```

**Comment by int19h** [comment]
Note that `--log-to` must go before `--pid`, and it must point to a directory.

**Comment by aantn** [comment]
I put it after pid. I'll try again later.

Does `-c` take actual python code or a debug adapter protocol command?

**Comment by int19h** [comment]
`-c` has the same meaning it does for Python itself - it's Python code. But you can't combine it with `--pid` - both are debug targets, and there is only one of those. Also like Python, all CLI switches that follow the target are passed to that target (which doesn't really make sense in case of `--pid`, so we should probably warn about it - but it does what you'd expect with `-c` or `-m`). 

I think there might be some confusion here wrt what `--connect` does. It's not for connecting *to* a debug server. It's for starting your app with debug server in the process, and telling that debug server to connect to the debug adapter at the specified address. That is, when you use `--connect`, you must have already started `debugpy.adapter` waiting on the specified host/port; and then the client must connect to that adapter to actually debug things. With VSCode, it does that for you when you use "listen" in your launch.json. 

There are no facilities in debugpy that allow it to be used standalone gdb-style - the server/adapter combo is useless without a client that can speak DAP to it, whether over stdio or over a socket.  If your environment is too lightweight for VSCode to run it, you might want to consider Vim + https://github.com/puremourning/vimspector. Detailed docs have some examples of using it with containers and `--pid`: https://puremourning.github.io/vimspector/configuration.html#remote-debugging-support

**Comment by aantn** [comment]
That explains the misunderstanding, thank you. I am closing the issue.
