### ISSUE TITLE
Missing responses on error

### ISSUE THREAD

**Issue by cgittinger** [microsoft/debugpy#556]
## Environment data

- debugpy version: 1.2.1
- OS and version: OSX 
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.3
- Using VS Code or Visual Studio: -no-

## Actual behavior

No error response when sending commands with missing or wrong arguments, when sending unimplemented commands, or when anything unexpected happens inside debugpy.

An error message does appear on stdout, though; 
eg:
  Unhandled: on_loadedsources_request not available in PyDevJsonCommandProcessor.

This does probably not affect vscode operation, but makes debugpy hard to use from other programs.
My intention was to use debugpy to run a program under surveillance of another python program to catch errors and/or set breakpoints without user interaction.
But without negative responses, I run into response-timeouts and it is hard to find out, what went wrong.
I understand, that this is more of a quality/testability issue, not strictly a bug.

## Expected  behavior

An error response, similar to:

{"seq": N, "type": "response", "request_seq": M, "success": false, "command": "loadedSources", "reason": "on_loadedsources_request not available"}

or:

{"seq": N, "type": "response", "request_seq": M, "success": false, "command": "setBreakpoints", "reason": "bad argument"}

## Steps to reproduce:

send the following (or any command which fails) :

{"seq":6,"type":"request","command":"loadedSources","arguments":{}}

and:

{"seq":7,"type":"request","command":"setBreakpoints","arguments":{"adapterID":"foo","source":{"path":"test"},"breakpoints":{"path":"test","lineNumber":32}}}

**Comment by cgittinger** [comment]
PS: another problem arose when the adapterID was missing in a request; then __init__ response object fails with a walkback complaining about missing positional argument: adapterID.

PPS: I guess my problem above with no-response from setBreakpoints was due to two other mistakes:
1) when sending a loadedSources, followup commands fail (maybe due to loadedSources not responding and therefor no-longer-valid sequence numbers)
2) missing condition and hitCondition?

**Comment by int19h** [comment]
Note that "adapterID" is a required property per spec. The error reporting could be better, though.

Similarly, "loadedSources" shouldn't be sent at all unless "supportsLoadedSourcesRequest" capability is present and set to true. But, again, this should be communicated more clearly.

**Comment by cgittinger** [comment]
Thanks for the quick response.

if I interpret the doc https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Attach correctly, "adapterID":  seems to be only required in the InitializeRequestArguments.

Is the document wrong or the implementation?

**Comment by int19h** [comment]
"initialize" request is what I had in mind. Is it complaining about some other request missing it?
