### ISSUE TITLE
Timed out waiting for debuggee to spawn

### ISSUE THREAD

**Issue by magentalo0803** [microsoft/debugpy#557]
**Environment data**
VS Code version: 1.54.1
Extension version (available under the Extensions sidebar): v2021.2.633441544
OS and version: macOS Catilina 10.15.7 
Python version (& distribution if applicable, e.g. Anaconda): python 3.6
Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda

**Expected behaviour**
Django server will start and can create breakpoints etc to debug

Actual behaviour
Pop-up window appears stating "Timed out waiting for debuggee to spawn"

lauch.json looks like this
<img width="616" alt="Screen Shot 2021-03-08 at 7 06 23 PM" src="https://user-images.githubusercontent.com/25370111/110412730-81922400-8041-11eb-9a70-177723fa924f.png">

**Comment by int19h** [comment]
Can you try running this with `"logToFile": true` in your configuration, and then share the `debugpy*.log` files that it produces in the folder where the extension is installed?

**Comment by fabioz** [comment]
Closing as additional feedback was not given.
