### ISSUE TITLE
cannot diplay images in the debug mode

### ISSUE THREAD

**Issue by seyeeet** [microsoft/debugpy#558]
## Environment data

-   VS Code version: 1.53.2
-   Extension version (available under the Extensions sidebar):  ubuntu  
-   Python version (& distribution if applicable, e.g. Anaconda): 3.6.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
- 
in the debugin mode when I am using my code I cannot display images during the debug.
I think it is important to be able to see images in the debug bc it is debug and we need to check how it looks like

see example below which is from the debug console

```
s_map
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])
s_map.shape
(720, 1280)
import matplotlib.pyplot as plt
plt.imshow(s_map)
<matplotlib.image.AxesImage object at 0x2aab99e87898>
plt.show() 
None
```

**Comment by fabioz** [comment]
I couldn't really reproduce the issue...

i.e.: in the image below I created a numpy array and then I called:

```
import matplotlib.pyplot as plt
plt.imshow(arr)
plt.show()
```

and as you can see it did stop in the middle of the evaluation (and even printed a message saying that the evaluation didn't finish in a reasonable time -- as it's executing the UI loop there). After closing the window the evaluation finished and the debug session proceeded as expected.

![image](https://user-images.githubusercontent.com/117621/111786508-a46fd400-889c-11eb-9ad2-26a3eca29732.png)

What may be different is that I'm using a different version of Python (tested with Python 3.8, matplotlib-3.3.4, pyqt-5.9.2, qt-5.9.7).

Anyways, this doesn't seem like something which we need to address in the debugger. Creating an UI main loop for the proper backend to show an interactive graph is up to matplotlib/UI libraries, so, I'm closing as I don't think there's anything to be done in the debugger in this case.

**Comment by seyeeet** [comment]
just FYI, it is displaying out of the console, and I was asking to show it inside the debug console.
Do you think that would be something that can be added as a feature?
