### ISSUE TITLE
Walrus operator does not assign "suffix" variable in Debug Console

### ISSUE THREAD

**Issue by bersbersbers** [microsoft/debugpy#559]
## Environment data

-   VS Code version: 1.54.1
-   Extension version (available under the Extensions sidebar): v2021.2.633441544
-   OS and version: Win 10 20H2
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.8
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): none
-   Relevant/affected Python packages and their versions: none
-   Relevant/affected Python-related VS Code extensions and their versions: none
-   Value of the `python.languageServer` setting: not set

## Expected behaviour

`"x-y".endswith(suffix := "-y")` assigns `suffix`

## Actual behaviour

> NameError: name 'suffix' is not defined

## Steps to reproduce:

1. Debug Python code
2. Stop anywhere
3. Open Debug Console
4. Enter `"x-y".endswith(suffix := "-y")`
5. Enter `suffix`

Interesting, the same works with `bar` instead of `suffix`:

![image](https://user-images.githubusercontent.com/12128514/110451707-c14e1f80-80c4-11eb-91e1-d6b1867d3bb5.png)

## Logs

Nothing particular.

**Comment by int19h** [comment]
@fabioz, can you take a look? The simplest repro is basically;
```py
print('ok')  # breakpoint here
```
and when it hits, in Debug Console:
```
→ x = "_"
→ x
  '_'
→ y = "__"
    None
→ y
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
  NameError: name 'y' is not defined
```

**Comment by bersbersbers** [comment]
I cannot currently reproduce the walrus-operator case - fortunately, the snapshot shows that I am not crazy ;) Maybe fixing the `"__"` issue gives you an idea if the walrus-operator case could be the same problem.

**Comment by fabioz** [comment]
That really seems odd. I'll investigate.

**Comment by fabioz** [comment]
Those are 2 different issues. 

-- The pull request: https://github.com/microsoft/debugpy/pull/560 should address both.

**Comment by bersbersbers** [comment]
Here's another example that I just hit which reproduces in current VS Code's insiders:
```
next(x for x in range(10) if x and (y:=x))
```

![image](https://user-images.githubusercontent.com/12128514/111588154-75d1fa80-87c3-11eb-9087-6451cdcea85a.png)

I expect `debugpy` to take a while to release a new version and make it available to VS Code users, so maybe this helps you ensure that #560 fixes all aspects of this issue.
