### ISSUE TITLE
VS Code shows wrong order of dict

### ISSUE THREAD

**Issue by danieltuzes** [microsoft/debugpy#566]
The issue has been closed, but the bug is still not resolved:
https://github.com/microsoft/vscode-python/issues/3236
https://github.com/microsoft/vscode-python/issues/7787

## Environment data

-   VS Code version: 1.54.3
-   Extension version (available under the Extensions sidebar): v2021.3.658691958
-   OS and version: Win 10 
-   Python version (& distribution if applicable, e.g. Anaconda): 3.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Value of the `python.languageServer` setting: pylance v2021.3.2

## Expected behaviour

The debugger shows the dict element in the right order.

## Actual behaviour

The debugger shows the dict elements in a wrong order.

## Steps to reproduce:
Debug the code by inserting a breakpoint at the print statement:

```python
atoms = {"H": 0, "He": 1, "Li": 2, "Be": 3}
print(atoms)
```
The debugger will show an alphabetic order. The function print produces the right result though.

![Untitled-1](https://user-images.githubusercontent.com/6088393/111834794-0277d800-88ec-11eb-9567-2e48e0c10b31.png)

**Comment by fabioz** [comment]
Note: I'm working on a fix for this.

**Comment by danieltuzes** [comment]
Any information on when and how it will be included in the new version?
