### ISSUE TITLE
debugpy crashes after attaching to VSCode

### ISSUE THREAD

**Issue by angelitoTalens** [microsoft/debugpy#568]
Python 3.5.1

I'm trying to debug a test python code using attach by pid,

Script run:
python -m debugpy --listen 5678 --log-to-stderr --wait-for-client test.py 

Then I attach it with VSCode debugger with this launch.json

`
{
            "name": "Python: Attach using Process Id",
            "type": "python",
            "request": "attach",
            "processId": "${command:pickProcess}",
            "connect": {
                "host": "localhost",
                "port": 5678
              }
}`

It stops on my break pt for a while but then crashes

these are the logs from stderr

`I+00070.035: Running file 'test.py'

I+00072.471: Configuring injected debugpy: {
                 "wait_for_client": false,
                 "address": [
                     "127.0.0.1",
                     42957
                 ],
                 "adapter_access_token": null,
                 "mode": "connect",
                 "log_to": null
             }

D+00072.471: connect(['127.0.0.1', 42957], **{'access_token': None})

I+00072.472: Initial debug configuration: {
                 "qt": "none",
                 "python": "/remote/tmp/users_workplace/atalens/pwe/opr_be/env/bin/python",
                 "subProcess": true
             }

D+00072.472: pydevd.settrace(*(), **{'client_access_token': None, 'host': '127.0.0.1', 'patch_multiprocessing': True, 'dont_trace_start_patterns': ('/remote/tmp/users_workplace/atalens/pwe/opr_be/env/lib/python3.5/site-packages/debugpy',), 'dont_trace_end_patterns': ('debugpy_launcher.py',), 'suspend': False, 'port': 42957})
`

**Comment by int19h** [comment]
Your debug configuration has both "processId" and "connect" in it. Those two are actually mutually exclusive - you should use "connect" when you run your app with `debugpy --listen`, and you should use "processId" when you don't control the way the app starts (debugpy will then be injected into the running process). 

However, it could certainly use better validation. There are two points here where we should be able to do better. On debugpy side, ideally, we'd want to detect that process being injected has debugpy waiting for connection, and maybe just connect to that instead (although I'm not sure how we'd retrieve the connection endpoint).

More importantly, on VSCode side, it should prevent configuration like this from even launching at all. The way it works there now is, as soon as it sees "connect", it just connects to debugpy on that port, and then passes the rest of the config to it. And debugpy doesn't know anything about "connect", and so ignores it - but it does know "processId", and tries to respect it.

(This latter validation could also be done in debugpy, at the point where it receives the configuration from the client. But error messages are generally better when validation is done in VSCode, especially if it's captured in the JSON schema.)

**Comment by angelitoTalens** [comment]
Thanks for the quick reply.

I kept "connect" only and it worked fine in VS Code
I keptr "processId": "${command:pickProcess}" but did not worked in VSCode
I also tried just the default attach to current file but doesn't work as well.

I can attach the logs here or close this and just raise a separate issue

**Comment by int19h** [comment]
When you say that "processId" didn't work, do you mean that you're seeing the same error, or are the symptoms different?

**Comment by angelitoTalens** [comment]
Using processId, in stderr it seems successful but in VSCode it doesn't attach and stop on the debug lines


**command:**
python -m debugpy --listen 5678 --log-to-stderr --wait-for-client test.py

launch.json
`{
            "name": "Python: Attach using Process Id",
            "type": "python",
            "request": "attach",
            "processId": "${command:pickProcess}",
        }`


**Logs:**

D+00000.940: wait_for_client()

I+00009.912: Configuring injected debugpy: {
                 "address": [
                     "127.0.0.1",
                     41385
                 ],
                 "wait_for_client": false,
                 "adapter_access_token": "964a96e3bdff58e2ddba29b9401710291f4632eb8d00c937bbfe1692dda84c19",
                 "log_to": null,
                 "mode": "connect"
             }

D+00009.913: connect(['127.0.0.1', 41385], **{'access_token': '964a96e3bdff58e2ddba29b9401710291f4632eb8d00c937bbfe1692dda84c19'})

I+00009.913: Initial debug configuration: {
                 "python": "/remote/tmp/users_workplace/atalens/pwe/opr_be/env/bin/python",
                 "qt": "none",
                 "subProcess": true
             }

D+00009.914: pydevd.settrace(*(), **{'host': '127.0.0.1', 'patch_multiprocessing': True, 'client_access_token': '964a96e3bdff58e2ddba29b9401710291f4632eb8d00c937bbfe1692dda84c19', 'port': 41385, 'dont_trace_end_patterns': ('debugpy_launcher.py',), 'suspend': False, 'dont_trace_start_patterns': ('/remote/tmp/users_workplace/atalens/pwe/opr_be/env/lib/python3.5/site-packages/debugpy',)})

I+00010.660: debugpy injected successfully

**Comment by int19h** [comment]
"processId" is not compatible with `python -m debugpy`. If you intend to use it, you should start your app directly:
```sh
python test.py
```
Or you can leave the command line as is, and use "connect".

**Comment by angelitoTalens** [comment]
Ok thanks for the help. Will use connect. It worked well during my test
