### ISSUE TITLE
Timed out waiting for debuggee to spawn

### ISSUE THREAD

**Issue by www516717402** [microsoft/debugpy#569]
## Environment data

-   VS Code version
> Version: 1.54.3
  Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
  Date: 2021-03-15T11:57:12.728Z (1 wk ago)
  Electron: 11.3.0
  Chrome: 87.0.4280.141
  Node.js: 12.18.3
  V8: 8.7.220.31-electron.0
  OS: Darwin x64 19.2.0
: XXX
-   Extension version (available under the Extensions sidebar): v2021.2.633441544
-   OS and version: MacOS 10.15.2 (19C57)
-   Python version (& distribution if applicable, e.g. Anaconda): 3.6.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Relevant/affected Python packages and their versions: XXX
-   Relevant/affected Python-related VS Code extensions and their versions: XXX
-   Value of the `python.languageServer` setting: XXX

[**NOTE**: If you suspect that your issue is related to the Microsoft Python Language Server (`python.languageServer: 'Microsoft'`), please download our new language server [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) from the VS Code marketplace to see if that fixes your issue]

## Expected behaviour

XXX

## Actual behaviour

XXX

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

When use remote-ssh connect python env for debuger. Sometimes appear Timed out waiting for debuggee to spawn.
All extension keep latest version. launch.json as follows:

{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "env": {"PYTHONPATH":"${workspaceRoot}"}
        }
    ]
}

## Logs

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
> /usr/bin/python3 ~/.vscode-server/extensions/ms-python.python-2021.2.633441544/pythonFiles/pyvsc-run-isolated.py ~/.vscode-server/extensions/ms-python.python-2021.2.633441544/pythonFiles/completion.py
> /usr/bin/python3 ~/.vscode-server/extensions/ms-python.python-2021.2.633441544/pythonFiles/pyvsc-run-isolated.py ~/.vscode-server/extensions/ms-python.python-2021.2.633441544/pythonFiles/completion.py
```

</p>
</details>

**Comment by int19h** [comment]
Do you see any output in the terminal when it happens?

**Comment by MohammadJavadD** [comment]
I had the same problem. When I use ctrl+F5, it doesn't show this error!

**Comment by int19h** [comment]
@MohammadJavadD Can you clarify what you mean by "run the *.json file"? If your debug configuration is set up to run the current open file in VSCode, you need to have some .py file active when pressing F5. If you still have launch.json opened, it will try to run that as if it were a Python file (which won't work, of course).

**Comment by www516717402** [comment]
This problem appear in some times. I feel this issue relate with network speed, since not appear today.

**Comment by www516717402** [comment]
Already solved. Network congestion
