### ISSUE TITLE
Python Debugger on VSCode Not Working

### ISSUE THREAD

**Issue by angelitoTalens** [microsoft/debugpy#574]
## Environment data

- debugpy version: 1.2.1
- OS and version: Suse SLE12
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.5.1
- Using VS Code or Visual Studio: VSCode

## Actual behavior

Run Test works fine but not Debug Test

![image](https://user-images.githubusercontent.com/42295328/112562055-9422a080-8e2a-11eb-8317-a2968197fda7.png)

**launch.json:**

```
     {
            "name": "Debug Tests",
            "type": "python",
            "request": "test",
            "console": "integratedTerminal",
    }
```

Running the script below and attaching via port works fine:
python3 -m debugpy --listen 5678 --wait-for-client --log-to-stderr bms/test_sample.py 

**launch.json:**
```
    {
            "name": "Python: Attach Port",
            "type": "python",
            "request": "attach",
            "connect": {
                "host": "localhost",
                "port": 5678
            }
    },
```

Due to project constraints I cannot use a different Python environment/version

A quick test switching to Python 3.9.2 works fine

## Expected  behavior

Enter Debug mode and stop on breakpoint

## Steps to reproduce:
1. Select my venv interpreter python 3.5.1
2. Go to the test file and run Debug Test

**Comment by int19h** [comment]
Since you can debug fine when running debugpy manually in wait mode and then attaching, I believe the issue is likely to be in the wrapper script for `unittest` that VSCode uses to start and control the run. While debugpy still supports Python 3.5, the Python extension for VSCode does not - it's 3.6+.

**Comment by fabioz** [comment]
I can't really reproduce this... it does seem to stop on the breakpoint properly for me (even on Python 3.5).

One thing to try is putting `"justMyCode": true` in the `"request": "test"` to see if it's skipping due to having your code in library code.

If that still doesn't work, please provide the logs for your run.

i.e.:

* Open VS Code
* Select the command Extensions: Open Extensions Folder
* Locate the Python extension directory, typically of the form ms-python.python-2021.*.****
* In that directory ensure you do not have any debug*.log files, if you do, please delete them
* Go back into VS Code and modify your launch.json to add the setting "logToFile": true, see below:

```
{
    "name": "Debug Tests",
    "type": "python",
    "request": "test",
    "console": "integratedTerminal",
    "logToFile": true,
    "justMyCode": false
}
```

* Start debugging
* When done, go back into the extension directory and upload the debug*.log files into this GitHub issue.

**Comment by angelitoTalens** [comment]
debugger.vscode*.log

```
0 Starting Session:
{
    "name": "Debug Tests",
    "type": "python",
    "request": "launch",
    "console": "integratedTerminal",
    "justMyCode": true,
    "logToFile": true,
    "rules": [
        {
            "path": "/remote/users/atalens/.vscode-server/extensions/ms-python.python-2021.2.633441544/pythonFiles",
            "include": false
        }
    ],
    "cwd": "/remote/users/atalens/pwe/opr_be",
    "env": {
        "PROJECT_OPR_DIR": "/remote/users/atalens/pwe/opr_be",
        "PYTHONPATH": <ommited>
        "LD_LIBRARY_PATH": <ommited>
        "PYTHONIOENCODING": "UTF-8",
        "PYTHONUNBUFFERED": "1"
    },
    "envFile": "/remote/users/atalens/pwe/opr_be/.env",
    "stopOnEntry": false,
    "showReturnValue": true,
    "redirectOutput": true,
    "debugStdLib": false,
    "subProcess": true,
    "program": "/remote/users/atalens/.vscode-server/extensions/ms-python.python-2021.2.633441544/pythonFiles/visualstudio_py_testlauncher.py",
    "args": [
        "--us=./bms",
        "--up=test*.py",
        "--uvInt=2",
        "--result-port=33657",
        "-ttest_sample.TestClass",
        "--testFile=/remote/users/atalens/pwe/opr_be/bms/test_sample.py"
    ],
    "python": "/remote/users/atalens/pwe/opr_be/env/bin/python3",
    "debugAdapterPython": "/remote/users/atalens/pwe/opr_be/env/bin/python3",
    "debugLauncherPython": "/remote/users/atalens/pwe/opr_be/env/bin/python3",
    "internalConsoleOptions": "neverOpen",
    "debugOptions": [
        "ShowReturnValue",
        "RedirectOutput",
        "Multiprocess"
    ],
    "workspaceFolder": "/remote/users/atalens/pwe/opr_be"
}
12 Exit:
Exit-Code: 127
Signal: none
```


**test_sample.py**:

```
import unittest

class TestClass(unittest.TestCase):
    def test_SampleTest(self):
        self.assertTrue(True)
```

**Comment by angelitoTalens** [comment]
I manually ran the command from the log above

`python "/remote/users/atalens/.vscode-server/extensions/ms-python.python-2021.2.633441544/pythonFiles/visualstudio_py_testlauncher.py" --us=./bms --up=test*.py --uvInt=2 --result-port=44545 -ttest_sample.TestClass.test_SampleTest --testFile=/remote/users/atalens/pwe/opr_be/bms/test_sample.py`

It gives me an error: 
`no matches found: --up=test*.py`

If I remove "--up=test*.py" from the command, it can run the test case successfully with result:

```
test_SampleTest (test_sample.TestClass) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
```

**Comment by int19h** [comment]
Exit code 127 usually means that the shell couldn't find the designated binary. If you invoke `/remote/users/atalens/pwe/opr_be/env/bin/python3` directly in VSCode terminal, does that work for you?

**Comment by int19h** [comment]
Another possibility is that `LD_LIBRARY_PATH` is set up in such a way that precludes the loading of some shared library. This should also be possible to confirm by manually setting it to the same value in the remote terminal, then trying to run the test.

**Comment by angelitoTalens** [comment]
Hi,

my virtual env depends on some extra LD_LIBRARY_PATH, I've edited the activate file to add more LD_LIBRARY_PATH when the virtual env is activated.

I can confirm the following:
 
**Works in Terminal:**
 - python works completely after activating the virtual environment
 - `python -m debugpy --listen 5678 --log-to-stderr --wait-for-client test.py`
 - `python -m unittest test_sample.py`

`Works in VSCode`
 - Run Test using Code Lens
 - Run Test using Python Unittest runner
 - Python Interpreter Discovery of my virtual env

Since most of the functionalities works in vscode and on terminal, my python virtual env with custom LD_LIBRARY_PATH works.
Is there anything missing that the debugger needs?

**Comment by int19h** [comment]
Note that the Python used is specifically `/remote/users/atalens/pwe/opr_be/env/bin/python3` - it doesn't just try to invoke `python` in the terminal, it uses the full path to the current configured interpreter. If you also use the full path when doing `-m debugpy`, does that work for you?

**Comment by angelitoTalens** [comment]
`/remote/users/atalens/pwe/opr_be/env/bin/python3 -m debugpy --listen 5678 --log-to-stderr --wait-for-client test.py`

Yes it works fine as long as my virtual env is active.

If I invoke it after deactivation it gives me the error:
error while loading shared libraries: libpython3.5m.so.1.0: cannot open shared object file: No such file or directory

Which is part of the LD_LIBRARY_PATH of my custom activate file

**Comment by int19h** [comment]
Ah, I suspect you might be hitting the environment activation issue in the Python extension then.

When you start debugging, that usually opens a new terminal. If your currently selected Python environment is of the kind that requires activation, the extension will try to activate it by submitting the corresponding command line to the terminal. At the same time, the debugger will try to use the terminal to spawn the debuggee, and sometimes this happens out of order.

If this is the root cause, the usual workaround is to activate the environment yourself in a terminal outside of VSCode, and then start Code from that environment, so that it's always activated for the duration of that session.

**Comment by angelitoTalens** [comment]
Is this planned to be fixed given I successfully selected my environment during interpreter selection and in my settings all the terminal I open have this automatic activation of my virtual env?

Is there a way for me to do the workaround if I'm connecting on our Linux servers using remote-ssh features of VSCode?

Thanks for the help!

**Comment by int19h** [comment]
It would be good to confirm that this is, indeed, the issue.

For remoting, I'm not entirely sure how to force the specific environment on the server, short of putting it into .bashrc or similar. One thing I'd try is starting a remote instance of VSCode, opening its terminal, making sure the environment is active there, and then doing `code --new-window` in that terminal.

**Comment by angelitoTalens** [comment]
I did `code --new-window <directory>`  while the python environment is active. It opens a new remote instance of vscode. 
In the new instance, the terminal is the same as the deactivated python environment. If I echo PYTHONPATH and LD_LIBRARY_PATH, I don't see my expected values 

I already tried putting the environment in .bashrc or .zshrc before raising this ticket. They didn't work

**Comment by fabioz** [comment]
I don't think there's anything to be done on the `debugpy` side of things here (it seems it's all related to vscode/vscode-python making sure that the environment variables are what you want when launching the adapter itself...).

@karthiknadig @int19h do you want to move this to `vscode-python`? Is this something to be supported or is it up to the user to make sure those variables are set beforehand when vscode itself is launched? -- in which case this would be just closed...
