### ISSUE TITLE
"Cannot assign requested address" error is not being propagated to VS Code 

### ISSUE THREAD

**Issue by luabud** [microsoft/debugpy#579]
## Environment data

- debugpy version: XXX (run `import debugpy; print(debugpy.__version__)` if uncertain)
- OS and version: Windows 10 with WSL 2, using Docker 
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.9 64 bit
- Using VS Code or Visual Studio: VS Code

## Actual behavior

Error is being logged but not propagated as an exception in VS Code. It just looks like the debugger is hanging 

## Expected  behavior

Error should be propagated

## Steps to reproduce:
1. XXX

**Comment by bwateratmsft** [comment]
Here's the logs:

[debugger.vscode_ae28e5fd-fa37-4678-9f8e-1dde28147c99.log](https://github.com/microsoft/debugpy/files/6246563/debugger.vscode_ae28e5fd-fa37-4678-9f8e-1dde28147c99.log)
[debugpy.adapter-23526.log](https://github.com/microsoft/debugpy/files/6246564/debugpy.adapter-23526.log)
