### ISSUE TITLE
Exception has occurred: FileNotFoundError [WinError 2] happened in debug when I set "justMyCode" false in launch.json  

### ISSUE THREAD

**Issue by HelloBigLuo** [microsoft/debugpy#583]
## Environment data

-   VS Code version: 1.55.0  (user setup)
-   OS and version: Windows_NT x64 10
-   Python version (& distribution if applicable, e.g. Anaconda): python 3.6 (anaconda)
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda

[**NOTE**: If you suspect that your issue is related to the Microsoft Python Language Server (`python.languageServer: 'Microsoft'`), please download our new language server [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) from the VS Code marketplace to see if that fixes your issue]

## Expected behaviour
run this test command

![image](https://user-images.githubusercontent.com/49053397/113573666-26a61980-964d-11eb-94fd-e077c71c4616.png)

## Actual behaviour

something wrong happened!  maybe during start of python?

Exception has occurred: FileNotFoundError
[WinError 2] The system cannot find the file specified: : 'I:\\MyAnaconda\\envs\\MaskRCNNpy36\\python36.zip'
  File "I:\MyAnaconda\envs\MaskRCNNpy36\Lib\genericpath.py", line 19, in exists
    os.stat(path)
  File "I:\MyAnaconda\envs\MaskRCNNpy36\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "I:\MyAnaconda\envs\MaskRCNNpy36\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)

![image](https://user-images.githubusercontent.com/49053397/113573757-58b77b80-964d-11eb-90ec-30db21a18437.png)

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Start Debugging with "Raised Exceptions" and "Uncaught Exceptions"breakpoint checked.

same wrong with microsoft/vscode-python#10391

## Logs

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by int19h** [comment]
When you disabled Just-My-Code, it will also report raised exceptions inside library code - in this case, inside the implementation of `os.path`. You should be able to just press F5 and continue execution, since it's inside a `try..except` block. Or if you don't want to break at all, uncheck "Raised".

**Comment by fabioz** [comment]
Closing (since things are apparently working as they should).
