### ISSUE TITLE
Add --restart-signal

### ISSUE THREAD

**Issue by Yajo** [microsoft/debugpy#584]
I lose a lot of time restarting containers when some python code has changed and I need to restart the server and reconnect to it from VSCode.

It would be awesome if we could define some signal that, when intercepted by debugpy, instructed him to send a SIGTERM to the underlying process and relaunch it, without dropping the active clients.

Something like:

    python -m debugpy --listen localhost:5678 --wait-for-client --restart-signal HUP myfile.py

**Comment by fabioz** [comment]
I'm not sure when/if that'll be added to `debugpy` (what do you think @int19h / @karthiknadig ?), but as a note, you can already implement it yourself in your own program.

i.e.: `debugpy` will automatically attach to subprocesses, so, if you create a process that spawns your actual program in a subprocess, it'll be automatically debugged, then, what you need to do is make your initial process listen to a signal at which point it'd kill that process and relaunch it (which should again be automatically debugged by `debugpy`).

**Comment by karthiknadig** [comment]
We discussed this feature in the team and we have unfortunately decided we will not be moving forward with this idea. We think there isn't an enough widespread need for this to warrant the maintenance cost for the feature.
