### ISSUE TITLE
Break points are being ignored in Python 3.9.3

### ISSUE THREAD

**Issue by smonsays** [microsoft/debugpy#587]
## Environment data

- debugpy version: 1.2.1
- OS and version: Arch Linux
- Python version: 3.9.3
- Using VS Code: True

## Actual behavior
Debugging python code is broken for me in vscode with Python 3.9.3. The debugger simply ignores any break point. Neither downgrading vscode nor the Python vscode extension helped. Downgrading Python itself from 3.9.3 to 3.9.2 however fixed the issue for me.

**Comment by fabioz** [comment]
The solution is using Python 3.9.2 or 3.9.4. Python 3.9.3 is broken (See the related change in: https://docs.python.org/3/whatsnew/changelog.html#python-3-9-4-final).
