### ISSUE TITLE
Support for ASGI servers?

### ISSUE THREAD

**Issue by fkromer** [microsoft/debugpy#588]
I'm running a Django app with the ASGI server `daphne` (WSL2 and Docker Desktop on Windows 10). To add remote debugging capabilities for this project into VSCode I followed the debug instructions in the docs about [how to remote debug Python apps running in a container managed by `docker-compose`](https://code.visualstudio.com/docs/containers/docker-compose#_python). Cause I was not successful initially I tried to find help in SO. Unfortunatelly I found just one [open question](https://stackoverflow.com/questions/46918702/remote-debugging-visual-studio-code-django-daphne-daphne-workers-running-in-d) which comes closest to my setup. To prevent myself from wasting a lot of time... is `debugpy` able to debug apps running using `daphne` and ASGI servers in general? If I have to consider something in comparison to WSGI servers (thatÄs what's covered in the VSCode docs)?

**Comment by int19h** [comment]
debugpy itself doesn't really do anything special about web frameworks, except for Django and Flask template breakpoint support. So long as you can somehow introduce the debugpy server into the process you're trying to debug, and then connect to it, you should be fine.

Looking at that SO issue, it looks like you're starting the server directly without using `debugpy ...` command line. I'm not familiar with Daphne, but if it itself a Python application, you should be able to start it via `debugpy`, and then you should get debugging for all Python code in that process, and in all its Python subprocesses. If it's not itself Python, then you'll have to insert `debugpy.listen()` or `debugpy.connect()` somewhere in your source code, preferably as early as possible when it starts running.

**Comment by fabioz** [comment]
Closing (since I think the question is answered: `debugpy` should be able to debug any project that's running with Python itself, it shouldn't matter which web-framework or technology is being used in particular).

Feel free to reopen this issue (or create a new one) if you are having problems in setting up the debugging in some particular scenario.

**Comment by LeandroCGMS** [comment]
> O debugpy em si realmente não faz nada de especial sobre os frameworks da web, exceto o suporte ao ponto de interrupção do modelo Django e Flask. Contanto que você possa, de alguma forma, introduzir o servidor debugpy no processo que está tentando depurar e, em seguida, conectar-se a ele, tudo bem.
> 
> Olhando para esse problema do SO, parece que você está iniciando o servidor diretamente sem usar a `debugpy ...`linha de comando. Não estou familiarizado com o Daphne, mas se for um aplicativo Python, você poderá iniciá-lo por meio `debugpy`de e, em seguida, deverá obter a depuração de todo o código Python nesse processo e em todos os seus subprocessos Python. Se não for o próprio Python, você terá que inserir `debugpy.listen()`ou `debugpy.connect()`em algum lugar do seu código-fonte, de preferência o mais cedo possível quando ele começar a ser executado.

I can start debugpy and get a response from it with "telnet localhost 8005", but vscode doesn't stop at breakpoints unlike Gunicorn. I tried with "python -m debugpy --listen 0.0.0.0:8005 manage.py runserver 0.0.0.0:8000" and also with "import debugpy


debugpy.listen(("0.0.0.0", 8005))", but it doesn't stop at breakpoints.
