### ISSUE TITLE
Using `debugpy` with Microsoft Python extension 

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/debugpy#59]
Download and install insiders build of the python extension: https://pvsc.blob.core.windows.net/extension-builds/ms-python-insiders.vsix

![image](https://user-images.githubusercontent.com/3840081/75914276-54e17600-5e09-11ea-8ace-da227fd241fb.png)

To use the new debugger please add the following to your user settings:
![image](https://user-images.githubusercontent.com/3840081/75913463-d7693600-5e07-11ea-80aa-fb16481b4449.png)

```js
    "python.experiments.optInto": [
        "DebugAdapterFactory - experiment",
        "PtvsdWheels37 - experiment"
    ],
```
Reload VSCode. if you look at `Output` tab > `Python` panel, you should see these lines:
![image](https://user-images.githubusercontent.com/3840081/75914150-1c419c80-5e09-11ea-8ccc-913995d22da7.png)

This should get you the new debugger.

If you don't see the above lines in the output tab, check following settings:
![image](https://user-images.githubusercontent.com/3840081/76378776-9099a580-630b-11ea-83cd-865db603571c.png)
They should bot be ticked. Disabling telemetry disables experimental features.

**Comment by vegetable09** [comment]
this work for me on win10 python3.6!
Thanks for your excellent work! I am using multiprocess.Process() and Queue()
love Vs code for keep better!

**Comment by RonaldoDev** [comment]
I got message error when I try add optInfo. Vscode throw error of values not accepted

**Comment by karthiknadig** [comment]
Closing this since `debugpy` is now the only debugger that is shipped with VS Code Python extension.

**Comment by HaoLIU94** [comment]
**Incompatibility**: Unable to install extension 'ms-python.python' as it is not compatible with VS Code '1.58.2'.

**Comment by int19h** [comment]
@HaoLIU94 You don't need any of this anymore, since the VSCode Python extension ships with debugpy in the box. Just install the most recent version of VSCode and the extension, and you should be all set.
