### ISSUE TITLE
timed out waiting for adapter to connect

### ISSUE THREAD

**Issue by portilhe** [microsoft/debugpy#591]
I've combed through a lot of the other questions with this or a similar title, but I haven't been able to solve my issue. Apologies if I've missed something.

I have a python COM object created with win32com running "in proc" in Excel which I call with a Visual Basic script. This is what I want to debug. I've added the following lines to my code:

```python
import debugpy
debugpy.log_to(r"C:\Mercury\log")
debugpy.configure( python=r"C:\Python27\python.exe" )
debugpy.listen(5678)
```

Ultimately, I want to attach to this process with VSCode. I have the launch.json all set up, my this error occurs even before I can try to attach, so I don't think it has anything to do with it.

Since I am not calling `debugpy.wait_for_client()` I was not expecting it timeout.

The contents of the log files follow below.

I am on Windows 10, Version 10.0.19042 Build 19042
My python is a Miniconda instalation (I've installed it in C:\Python27):
Python 2.7.18 |Anaconda, Inc.| (default, Apr 23 2020, 17:02:51) [MSC v.1500 32 bit (Intel)] on win32
`>>> debugpy.__version__
u'1.2.1'`

Any help is greatly apreciated.

[debugpy.adapter-19864.log](https://github.com/microsoft/debugpy/files/6344608/debugpy.adapter-19864.log)
[debugpy.server-1548.log](https://github.com/microsoft/debugpy/files/6344643/debugpy.server-1548.log)

### debugpy.server-1548.log:

> I+00000.014: Windows-10-10.0.19041-SP0 AMD64
>              CPython 2.7.18 (32-bit)
>              debugpy 1.2.1
> 
> I+00000.017: Initial environment:
>              
>              System paths:
>                  sys.prefix: C:\Python27
>                  sys.base_prefix: <missing>
>                  sys.real_prefix: <missing>
>                  site.getsitepackages(): C:\Python27
>                                          C:\Python27\lib\site-packages
>                  site.getusersitepackages(): C:\Users\n60368\AppData\Roaming\Python\Python27\site-packages
>                  sys.path (site-packages): C:\Python27\lib\site-packages
>                  sysconfig.get_path('stdlib'): C:\Python27\Lib
>                  sysconfig.get_path('platstdlib'): C:\Python27\Lib
>                  sysconfig.get_path('purelib'): C:\Python27\Lib\site-packages
>                  sysconfig.get_path('platlib'): C:\Python27\Lib\site-packages
>                  sysconfig.get_path('include'): C:\Python27\Include
>                  sysconfig.get_path('scripts'): C:\Python27\Scripts
>                  sysconfig.get_path('data'): C:\Python27
>                  os.__file__: C:\Python27\lib\os.pyc
>                  threading.__file__: C:\Python27\lib\threading.pyc
> 
> D+00000.019: configure(None, {'python': 'C:\\Python27\\python.exe'})
> 
> D+00000.019: listen((u'127.0.0.1', 5678), **{})
> 
> I+00000.019: Initial debug configuration: {
>                  "python": "C:\\Python27\\python.exe", 
>                  "qt": "none", 
>                  "subProcess": true
>              }
> 
> I+00000.020: Waiting for adapter endpoints on 127.0.0.1:60332...
> 
> I+00000.020: debugpy.listen() spawning adapter: [
>                  "C:\\Python27\\python.exe", 
>                  "C:\\Python27\\lib\\site-packages\\debugpy\\adapter", 
>                  "--for-server", 
>                  "60332", 
>                  "--host", 
>                  "127.0.0.1", 
>                  "--port", 
>                  "5678", 
>                  "--server-access-token", 
>                  "362ec075737cfcd048fb3676f5829ceff551b933844a85d898ee6b3f01f4b976", 
>                  "--log-dir", 
>                  "C:\\Mercury\\log"
>              ]
> 
> I+00010.042: Timed out waiting for adapter to connect:
>              
>              Traceback (most recent call last):
>                File "C:\Python27\lib\site-packages\debugpy\server\api.py", line 218, in listen
>                  sock, _ = endpoints_listener.accept()
>                File "C:\Python27\lib\socket.py", line 206, in accept
>                  sock, addr = self._sock.accept()
>              timeout: timed out
>              
>              Stack where logged:
>                File "C:\Python27\lib\site-packages\win32com\server\policy.py", line 136, in CreateInstance
>                  return retObj._CreateInstance_(clsid, reqIID)
>                File "C:\Python27\lib\site-packages\win32com\server\policy.py", line 194, in _CreateInstance_
>                  myob = call_func(classSpec)
>                File "C:\Python27\lib\site-packages\win32com\server\policy.py", line 727, in call_func
>                  return resolve_func(spec)(*args)
>                File "C:\Python27\lib\site-packages\win32com\server\policy.py", line 716, in resolve_func
>                  module = _import_module(mname)
>                File "C:\Python27\lib\site-packages\win32com\server\policy.py", line 735, in _import_module
>                  __import__(mname)
>                File "C:\Mercury\AteneaExcelBridge.py", line 46, in <module>
>                  import offset.Invoke
>                File "C:\Mercury\offset\Invoke.py", line 579, in <module>
>                  debugpy.listen(5678)
>                File "C:\Python27\lib\site-packages\debugpy\__init__.py", line 113, in listen
>                  return api.listen(address)
>                File "C:\Python27\lib\site-packages\debugpy\server\api.py", line 141, in debug
>                  return func(address, settrace_kwargs, **kwargs)
>                File "C:\Python27\lib\site-packages\debugpy\server\api.py", line 230, in listen
>                  "Timed out waiting for adapter to connect:", level="info"
>                File "C:\Python27\lib\site-packages\debugpy\common\log.py", line 218, in swallow_exception
>                  _exception(format_string, *args, **kwargs)
>              
> 
> I+00010.043: listen() failed:
>              
>              Traceback (most recent call last):
>                File "C:\Python27\lib\site-packages\debugpy\server\api.py", line 141, in debug
>                  return func(address, settrace_kwargs, **kwargs)
>                File "C:\Python27\lib\site-packages\debugpy\server\api.py", line 232, in listen
>                  raise RuntimeError("timed out waiting for adapter to connect")
>              RuntimeError: timed out waiting for adapter to connect
>              
>              Stack where logged:
>                File "C:\Python27\lib\site-packages\win32com\server\policy.py", line 136, in CreateInstance
>                  return retObj._CreateInstance_(clsid, reqIID)
>                File "C:\Python27\lib\site-packages\win32com\server\policy.py", line 194, in _CreateInstance_
>                  myob = call_func(classSpec)
>                File "C:\Python27\lib\site-packages\win32com\server\policy.py", line 727, in call_func
>                  return resolve_func(spec)(*args)
>                File "C:\Python27\lib\site-packages\win32com\server\policy.py", line 716, in resolve_func
>                  module = _import_module(mname)
>                File "C:\Python27\lib\site-packages\win32com\server\policy.py", line 735, in _import_module
>                  __import__(mname)
>                File "C:\Mercury\AteneaExcelBridge.py", line 46, in <module>
>                  import offset.Invoke
>                File "C:\Mercury\offset\Invoke.py", line 579, in <module>
>                  debugpy.listen(5678)
>                File "C:\Python27\lib\site-packages\debugpy\__init__.py", line 113, in listen
>                  return api.listen(address)
>                File "C:\Python27\lib\site-packages\debugpy\server\api.py", line 143, in debug
>                  log.reraise_exception("{0}() failed:", func.__name__, level="info")
>                File "C:\Python27\lib\site-packages\debugpy\common\log.py", line 226, in reraise_exception
>                  _exception(format_string, *args, **kwargs)
>              
> 
> 

### debugpy.adapter-19864.log

> I+00000.093: Windows-10-10.0.19041 AMD64
>              CPython 2.7.18 (32-bit)
>              debugpy 1.2.1
> 
> I+00000.100: debugpy.adapter startup environment:
>              
>              System paths:
>                  sys.prefix: C:\Python27
>                  sys.base_prefix: <missing>
>                  sys.real_prefix: <missing>
>                  site.getsitepackages(): C:\Python27
>                                          C:\Python27\lib\site-packages
>                  site.getusersitepackages(): C:\Users\n60368\AppData\Roaming\Python\Python27\site-packages
>                  sys.path (site-packages): C:\Python27\lib\site-packages
>                  sysconfig.get_path('stdlib'): C:\Python27\Lib
>                  sysconfig.get_path('platstdlib'): C:\Python27\Lib
>                  sysconfig.get_path('purelib'): C:\Python27\Lib\site-packages
>                  sysconfig.get_path('platlib'): C:\Python27\Lib\site-packages
>                  sysconfig.get_path('include'): C:\Python27\Include
>                  sysconfig.get_path('scripts'): C:\Python27\Scripts
>                  sysconfig.get_path('data'): C:\Python27
>                  os.__file__: C:\Python27\lib\os.pyc
>                  threading.__file__: C:\Python27\lib\threading.pyc
> 
> E+00000.109: Error listening for incoming Client connections on 127.0.0.1:5678:
>              
>              Traceback (most recent call last):
>                File "C:\Python27\lib\site-packages\debugpy\adapter/../../debugpy\common\sockets.py", line 73, in serve
>                  listener = create_server(host, port, backlog, timeout)
>                File "C:\Python27\lib\site-packages\debugpy\adapter/../../debugpy\common\sockets.py", line 25, in create_server
>                  server.bind((host, port))
>                File "C:\Python27\lib\socket.py", line 228, in meth
>                  return getattr(self._sock,name)(*args)
>              error: [Errno 10013] An attempt was made to access a socket in a way forbidden by its access permissions
>              
>              Stack where logged:
>                File "C:\Python27\lib\runpy.py", line 174, in _run_module_as_main
>                  "__main__", fname, loader, pkg_name)
>                File "C:\Python27\lib\runpy.py", line 72, in _run_code
>                  exec code in run_globals
>                File "C:\Python27\lib\site-packages\debugpy\adapter\__main__.py", line 228, in <module>
>                  main(_parse_argv(sys.argv))
>                File "C:\Python27\lib\site-packages\debugpy\adapter\__main__.py", line 61, in main
>                  client_host, client_port = clients.serve(args.host, args.port)
>                File "C:\Python27\lib\site-packages\debugpy\adapter/../../debugpy\adapter\clients.py", line 654, in serve
>                  listener = sockets.serve("Client", Client, host, port)
>                File "C:\Python27\lib\site-packages\debugpy\adapter/../../debugpy\common\sockets.py", line 76, in serve
>                  "Error listening for incoming {0} connections on {1}:{2}:", name, host, port
>                File "C:\Python27\lib\site-packages\debugpy\adapter/../../debugpy\common\log.py", line 226, in reraise_exception
>                  _exception(format_string, *args, **kwargs)
>              
> 
> I+00000.110: Listening for incoming Server connections on 127.0.0.1:60342...
> 
> I+00000.111: Sending endpoints info to debug server at localhost:60332:
>              {
>                  "server": {
>                      "host": "127.0.0.1", 
>                      "port": 60342
>                  }, 
>                  "error": "Can't listen for client connections: [Errno 10013] An attempt was made to access a socket in a way forbidden by its access permissions"
>              }
> 
> E+00002.153: Error sending endpoints info to debug server:
>              
>              Traceback (most recent call last):
>                File "C:\Python27\lib\site-packages\debugpy\adapter\__main__.py", line 87, in main
>                  sock.connect(("127.0.0.1", args.for_server))
>                File "C:\Python27\lib\socket.py", line 228, in meth
>                  return getattr(self._sock,name)(*args)
>              error: [Errno 10061] No connection could be made because the target machine actively refused it
>              
>              Stack where logged:
>                File "C:\Python27\lib\runpy.py", line 174, in _run_module_as_main
>                  "__main__", fname, loader, pkg_name)
>                File "C:\Python27\lib\runpy.py", line 72, in _run_code
>                  exec code in run_globals
>                File "C:\Python27\lib\site-packages\debugpy\adapter\__main__.py", line 228, in <module>
>                  main(_parse_argv(sys.argv))
>                File "C:\Python27\lib\site-packages\debugpy\adapter\__main__.py", line 96, in main
>                  log.reraise_exception("Error sending endpoints info to debug server:")
>                File "C:\Python27\lib\site-packages\debugpy\adapter/../../debugpy\common\log.py", line 226, in reraise_exception
>                  _exception(format_string, *args, **kwargs)
>              
> 
> I+00002.153: Not logging to "<stderr>" anymore.
> 
>

**Comment by karthiknadig** [comment]
@portilhe Can you try reversing the direction of the connections? Use `listen` on vscode side and use `connect` in your script. This way you can start VS Code debug session first and it will wait for a connection from the debuggee. See if this direction works better.

**Comment by portilhe** [comment]
@karthiknadig Thank you for your reply. Sorry, but I'm still a bit green working with VSCode. Can you tell me how do I go about doing this? Do I write an ad-hoc python script and put the "listen" line there? or is it something to configure in the lauch.json? 

I tried the latter:
![image](https://user-images.githubusercontent.com/7792784/115510700-59245900-a280-11eb-88eb-98ca39973073.png)
But when I start debugging it seems to disapear after a few seconds.

Thanks in advance.

**Comment by portilhe** [comment]
@karthiknadig Okay, I got it working!!

It was both ways: with the listen in the lauch.json configuration and in the main code. I just had to change the port. It seems to be an issue with the Firewall.

Thanks again.
