### ISSUE TITLE
Debugger not working

### ISSUE THREAD

**Issue by karanmandve** [microsoft/debugpy#593]
## Environment data

- debugpy version: 1.2.1 (run `import debugpy; print(debugpy.__version__)` if uncertain)
- OS and version: windows 10 pro 1909
- Python version (& distribution if applicable, e.g. Anaconda): 3.9.4
- Using VS Code or Visual Studio: Vs Code

## Actual behavior
In window:
Timed out waiting for launcher to connect
In terminal :
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

## Expected  behavior

Run debugger

## Steps to reproduce:
1. Make a python file with any name
2. Write a some program
3. Click on Run which is on ribbon on vs code click on Start Debugging
4.
![IMG_20210418_091239](https://user-images.githubusercontent.com/59260030/115519876-3b1e1f00-a2a7-11eb-9020-6755d79df32a.jpg)

**Comment by karthiknadig** [comment]
We will need logs for this. Go to the debuging side-bar item, and create a launch.json. Select "Python File" as the configuration. Once you have the configuration set `"logToFile": true`.
```js
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Python: Current File",
      "type": "python",
      "request": "launch",
      "program": "${file}",
      "console": "integratedTerminal",
      "logToFile": true
    }
  ]
}
```
Go back to the python file and start debugging. This will generate logs in the extension folder. Navigate to the python extension folder (`$USERPROFILE%\.vscode\extensions\ms-python.python-2021.4.765268190`), the logs should be there. Upload all the log files.

If your extensions folder is not in the path above, then you can use this command to find the extensions folder:
![image](https://user-images.githubusercontent.com/3840081/115524216-c1ece080-a242-11eb-80f6-bfda71bc147c.png)

**Comment by karanmandve** [comment]
Ok thanks, hope error will gone. 
[Log.zip](https://github.com/microsoft/debugpy/files/6355095/Log.zip)

**Comment by fabioz** [comment]
The `Log.zip` seems to be corrupted... can you put the logs directly (without zipping) into the issue?

**Comment by karanmandve** [comment]
Ohh sorry for that, I didn't recheck it.

[log file.zip](https://github.com/microsoft/debugpy/files/6371787/log.file.zip)

**Comment by fabioz** [comment]
The actual log files in the .zip are:

[debugpy.adapter-11256.log](https://github.com/microsoft/debugpy/files/6398468/debugpy.adapter-11256.log)
[debugpy.launcher-3580.log](https://github.com/microsoft/debugpy/files/6398469/debugpy.launcher-3580.log)
[debugger.vscode_0aa4b031-c10d-42e2-a219-62985650b610.log](https://github.com/microsoft/debugpy/files/6398470/debugger.vscode_0aa4b031-c10d-42e2-a219-62985650b610.log)

So, it's failing to establish the socket connection.

@karanmandve The usual culprit here is a firewall/antivirus actively blocking the communication. Can you check that?
@int19h Do you see anything else in the log file which may be helpful here?

**Comment by karanmandve** [comment]
Thanks it is working now.

**Comment by fabioz** [comment]
Great!
