### ISSUE TITLE
Debugpy cannot respond to a breakpoint.

### ISSUE THREAD

**Issue by Y24** [microsoft/debugpy#594]
## Environment data

- debugpy version: 1.2.1 (run `import debugpy; print(debugpy.__version__)` if uncertain)
- OS and version: Linux x64 5.10.30-1-MANJARO
- Python version (& distribution if applicable, e.g. Anaconda): 3.9.3-64bit
- Using VS Code or Visual Studio: VS Code 1.55.2

## Actual behavior

Several days ago, The python debugger is just OK, but when I try to do the same debugger task as usaual, I have found that the breakpoint is ignored, this must be a issue caused by the recent update of vscode or python extension.

## Expected  behavior

Get paused at an enabled checkpoint.

## Steps to reproduce:
1. Mark a checkpoint on any python file and then debug it, it will ignore it!

**Comment by fabioz** [comment]
Can you please provide the related logs to know what's happening in this case?

i.e.:

* Open VS Code
* Select the command Extensions: Open Extensions Folder
* Locate the Python extension directory, typically of the form `ms-python.python-2021.*.****`
* In that directory ensure you do not have any debug*.log files, if you do, please delete them
* Go back into VS Code and modify your launch.json to add the setting "logToFile": true, see below:

```
{
    "name": "Python: Current File (Integrated Terminal)",
    "type": "python",
    "request": "launch",
    "program": "${file}",
    "console": "integratedTerminal",
    "logToFile": true
}
```

* Start debugging
* When done, go back into the extension directory and upload the debug*.log files into this GitHub issue.

**Comment by Y24** [comment]
> Can you please provide the related logs to know what's happening in this case?
> 
> i.e.:
> 
> * Open VS Code
> * Select the command Extensions: Open Extensions Folder
> * Locate the Python extension directory, typically of the form `ms-python.python-2021.*.****`
> * In that directory ensure you do not have any debug*.log files, if you do, please delete them
> * Go back into VS Code and modify your launch.json to add the setting "logToFile": true, see below:
> 
> ```
> {
>     "name": "Python: Current File (Integrated Terminal)",
>     "type": "python",
>     "request": "launch",
>     "program": "${file}",
>     "console": "integratedTerminal",
>     "logToFile": true
> }
> ```
> 
> * Start debugging
> * When done, go back into the extension directory and upload the debug*.log files into this GitHub issue.

I have tested an older python extension and it doesn't work either. But vscode version 1.54 is not tested because I cannot downgrade easily. Since then, I thought the major problem is inside it. The attached log file ([debugLogs.zip](https://github.com/microsoft/debugpy/files/6350597/debugLogs.zip)) is constructed by a demo python file debugging. I thought this bug is so incredible because I try to debug c++ file and it works OK.

**Comment by fabioz** [comment]
The problem is that you're using `CPython 3.9.3`. This version of CPython is unfortunately broken (it broke the CPython ABI and extension modules don't work on it -- one of which is the debugger).

i.e.: `Python 3.9.4` is a hotfix release addressing an unintentional ABI incompatibility introduced in Python 3.9.3. Upgrading is highly recommended to all users. Details in bpo-43710. 

I created an issue: https://github.com/microsoft/debugpy/issues/595 so that the debugger reports that properly (instead of just not working).

**Comment by Y24** [comment]
Thanks a lot for your help.
