### ISSUE TITLE
CPython 3.9.3 is broken and cannot be used with the debugger

### ISSUE THREAD

**Issue by fabioz** [microsoft/debugpy#595]
CPython 3.9.3 broke the ABI which is guaranteed to be compatible among all the CPython 3.9.x releases.

This makes the debugger break (as well as many other compiled extensions) and as such it cannot be used in the debugger.

See the 3.9.4 release notes: https://www.python.org/downloads/release/python-394/

As it cannot be used, the debugger should try to signal that early on (instead of just not working).

The fix for users is using CPython 3.9.4 (or any other version except CPython 3.9.3).

**Comment by int19h** [comment]
Let's keep this issue open for a while even after adding the check, so that the users can quickly find it if they hit the problem.

**Comment by int19h** [comment]
It has been a while since we had any user reports where this was a root cause, and 3.9 has had 5 more releases since this one, so it's time to close.
