### ISSUE TITLE
Debug pexepect

### ISSUE THREAD

**Issue by Yajo** [microsoft/debugpy#596]
## Environment data

- debugpy version: 1.2.1
- OS and version: Fedora 33 Silverblue
- Python version: 3.9.2 (default, Feb 20 2021, 00:00:00) [GCC 10.2.1 20201125 (Red Hat 10.2.1-9)]
- Using VS Code or Visual Studio: VS code

## Actual behavior

My test (pytest) is using pexpect to spawn a python process and interact with the TUI that it produces.

If I set a breakpoint in the program code (the program that is spawned) and click on "Debug test" option that appears floating over the test code, it doesn't obey the breakpoint.

## Expected  behavior

Somehow I should be able to configure subprocesses=True for tests. Breakpoint should happen.

## Steps to reproduce:
1. Clone https://github.com/copier-org/copier/commit/2a944bf73620f3c993155ff2754ee6218d093e62
2. Interrupt this line: https://github.com/copier-org/copier/blob/2a944bf73620f3c993155ff2754ee6218d093e62/copier/user_data.py#L204
3. Debug this test: https://github.com/copier-org/copier/blob/2a944bf73620f3c993155ff2754ee6218d093e62/tests/test_complex_questions.py#L135

**Comment by int19h** [comment]
Looking at your test, it doesn't spawn the child Python process directly - instead, it goes via `copier.cmd`. Our detection of Python subprocesses is based on intercepting the API calls used to spawn and looking at the binary they're trying to run - basically, if it's `python`, we consider it a debuggable subprocess. But when there's an intermediate non-Python subprocess, this technique doesn't work. Unfortunately, there isn't a better one available.

My suggestion would be to manually attach to the child process to debug it (via `debugpy.connect()` or `debugpy.listen()`, whichever is more convenient). VSCode lets you attach to multiple processes concurrently, if you use the drop-down to select different configurations. In this case, I'd keep the config you have to start the tests, and add a new one that does `"listen": ...`, then do `debugpy.connect(...)` from child process code somewhere, e.g. conditionally based on some env var.

**Comment by Yajo** [comment]
> basically, if it's `python`, we consider it a debuggable subprocess

Wooah! You gave me the hint I needed!

I was spawning directly another binary to workaround https://github.com/microsoft/vscode-python/issues/14222, but with https://github.com/copier-org/copier/pull/384 now I can execute copier as a module.

So, I changed the spawn code to spawn like `[sys.executable, "-mcopier", "copy", str(src), str(dst)]`, and it works! I can debug subprocesses out of the box!

Thanks!

---

Now I'm not sure if there's still something to do regarding this issue. Maybe some docs on this subject? Or maybe inspecting the shebang of the executable to know if it's a python subprocess to be debugged?

**Comment by int19h** [comment]
The shebang doesn't really help here, since the script that starts Python is not itself a Python script; since we can't debug it, we can't intercept it when it tries to spawn things (even if those things are, in turn, Python). But, in principle, we could track subprocess creation separately from the rest of debugging, and apply it to *all* subprocesses in the tree, so I guess this is an enhancement.

**Comment by fabioz** [comment]
I'm closing this as I don't think we're doing additional changes here (we may revisit if it comes up more times in new reports...).
