### ISSUE TITLE
Debugpy shuts down an embedded script host process after the debugging session is finished

### ISSUE THREAD

**Issue by yevgeni-zolotko** [microsoft/debugpy#597]
## Environment data

- debugpy version: 1.2.1
- OS and version: Microsoft Windows [Version 10.0.19042.928]
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.9.0
- VS Code

## Steps to reproduce:

In an embedded python environment, run the following script code:
```
import debugpy
debugpy.configure(python="python.exe")
debugpy.listen(5678)
debugpy.wait_for_client()

```
After the host application executes a script file (named test1.py) in the same Python scope as the code above.

Then attach a VS Code mock DAP client ([the Mock Debug extension](https://marketplace.visualstudio.com/items?itemName=andreweinand.mock-debug)) to the server with the following launch.json:
```
"configurations": [
        {
          "type": "mock",
          "request": "attach",
          "name": "mock test",
          "program": "${workspaceFolder}/test1.py",
          "stopOnEntry": true,
          "debugServer": 5678
        }
      ]
```

## Actual behavior

After VS Code attaches to the debugpy server, and subsequently the script finishes execution in debugger, the process which hosted the embedded script silently exits (presumably this is initiated by debugpy).

## Expected  behavior

I would like to have an option of not exiting the debugged process quietly, so the host application can continue working.

**Comment by fabioz** [comment]
I'm not sure about this... are you sure that it's the debugger exiting?

As far as I can see, the debugger should only exit if a `terminate` request is sent (in an attach, only a `disconnect` should be sent).

As a note, if a `terminate` is actually being sent, I don't think we should support a mode in which the debugger doesn't terminate...

**Comment by fabioz** [comment]
Closing since no further input was given.
