### ISSUE TITLE
Custom debug adapter request without `frameId` in arguments does not evaluate code in global scope

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/debugpy#598]
## Environment data

- debugpy version: 1.2.1
- OS and version: Windows_NT x64 10.0.19042
- Python version (& distribution if applicable, e.g. Anaconda): 3.8.8, python.org
- Using VS Code or Visual Studio: VS Code

## Actual behavior

I work on the Jupyter extension for VS Code, which provides data visualizers for users' Python variables while debugging Python code in VS Code via a DebugAdapterTracker which sends custom evaluate requests to the running debug session. When sending custom evaluate requests with `frameId` omitted, the requests complete without errors, but subsequent requests which reference expressions defined in that request raise NameErrors. In our case we're importing a module, but even simple variable declarations like `foobar = 42` which are evaluated with a custom debug adapter request don't seem to be subsequently accessible in either local or global scope using the debug console in VS Code.

## Expected  behavior

Our objective is to be able to evaluate a module import in global scope such that it is available for the duration of the debug session regardless of what function scope we may happen to currently be in. We could evaluate it in each function scope we break into, and we can get this working today, but we'd prefer not to do this if we can help it because the evaluate request tends to be slow. 

The debug adapter protocol spec says that in an evaluate request, when `frameId` is omitted from the evaluate arguments, the expression will be evaluated in global scope. (I'm assuming this means any variables defined as a result of evaluating the expression should be visible in any subsequent function scope.)
```
  /**
   * Evaluate the expression in the scope of this stack frame. If not specified,
   * the expression is evaluated in the global scope.
   */
  frameId?: number;
```

I did see that this should be supported with https://github.com/microsoft/ptvsd/pull/1729. As mentioned earlier, note also that I'm able to evaluate expressions in local scope with a custom eval request by tracking, and setting `frameId` to, whatever the topmost frame ID is, so we __can__ work around this at the expense of slower load times for our users. It's only when `frameId` is omitted that the eval request seems to go nowhere.

## Steps to reproduce:
(Apologies that this is a rather involved setup. Please let me know if there's a better way to provide a debugpy repro. I've also attached logs below. Also please feel free to ping me on Teams.)
1. Install VS Code and the Python extension by Microsoft
1. Clone, build and debug this branch of the Jupyter extension source https://github.com/microsoft/vscode-jupyter/tree/dev/joyceerhl%2Fdata-viewer-debugger
1. Create a Python file with this code:
```python
import pandas as pd 
import numpy as np 

def foo():
	mydf = pd.DataFrame(np.arange(500 * 30).reshape(500, 30)) 
	print(mydf)

foo()
```
1. Set a breakpoint on the `return df` line
1. Run the 'Python File` debug configuration to debug the single Python file
1. At the breakpoint, right click on `df` in the Variables window and select 'View Value in Data Viewer':
![image](https://user-images.githubusercontent.com/30305945/115950279-269c7b00-a48f-11eb-8668-c68add668830.png)
1. This causes our extension to run a bunch of custom eval requests, some of which don't have `frameId` set and which should theoretically be evaluated globally. One such expression is `import vscodeGetVariableInfo as _VSCODE_VariableImport`. We then send another eval request which references `_VSCODE_VariableImport`, which throws a NameError:
![image](https://user-images.githubusercontent.com/30305945/115949913-f5bb4680-a48c-11eb-8076-a7db7c60ba67.png)
1. Evaluating that expression in the debug console also doesn't work:
![frameid](https://user-images.githubusercontent.com/30305945/115950162-7af32b00-a48e-11eb-9be8-88f4fa0342ce.gif)

Here are the logs produced:
[debugpy.adapter-25368.zip](https://github.com/microsoft/debugpy/files/6369088/debugpy.adapter-25368.zip)

Many thanks in advance!

**Comment by fabioz** [comment]
Hello @joyceerhl, the issue here is that there's no real `global` scope in Python in a way that such a scope would then be included in all children scopes (each module has its own `global` scope, so, in https://github.com/microsoft/debugpy/blob/main/src/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py#L1133 what the debugger does is create a separate frame where such info would be evaluated, but changes won't actually be visible anywhere out of that module.

We could add the `frame.f_locals` from that frame as the `globals` of all subsequent evaluate requests, but I'm not sure that this is ideal (we don't want that in general, just in this specific use case).

I took a look at the expressions you sent in the log:

```
"expression": "import sys\nsys.path.append(\"c:\\\\Users\\\\huer\\\\Desktop\\\\projects\\\\vscode-jupyter\\\\vscode-jupyter\\\\pythonFiles\\\\vscode_datascience_helpers\\\\getVariableInfo\")",
"expression": "import vscodeGetVariableInfo as _VSCODE_VariableImport",
"expression": "_VSCODE_VariableImport._VSCODE_getVariableInfo(mydf)",
```

I think that instead of doing that, you could keep adding to the `sys.path` as you're doing , but then instead of doing an import and then using it as if it was in the global scope, you could do something as:

```
__import__('vscodeGetVariableInfo')._VSCODE_getVariableInfo('mypdf')
```

Which is still a single statement (so, it can be evaluated and still return a value as you expect)... that wouldn't require any change to the debugger and I don't think that incurs in any additional overhead.

Do you see any issue in doing it that way?

**Comment by joyceerhl** [comment]
Thank you for your detailed explanation! Based on the DAP API description I'd incorrectly assumed that debugpy would handle `frameId` like this:

> add the frame.f_locals from that frame as the globals of all subsequent evaluate requests

Replacing our existing evaluated expressions with `__import__('vscodeGetVariableInfo')._VSCODE_getVariableInfo('mypd')` works just fine for us.

Out of curiosity, the Python import docs [recommend](https://docs.python.org/3/library/functions.html#__import__) `importlib.import` over `__import__`--do you know if it matters which one we use?

Huge thanks again for your help!

**Comment by fabioz** [comment]
`importlib` will not be in the namespace, while `__import__` is (as it's a builtin), so, you can't really use it in this case.
