### ISSUE TITLE
"attach" expected

### ISSUE THREAD

**Issue by zhaoya881010** [microsoft/debugpy#599]
## Environment data

- debugpy version:1.2.1
- OS and version: windows
- Python version 3.7
- 
- Using VS Code or Visual Studio:

IDE base Microsoft.VisualStudio.Shared.VSCodeDebugProtocol

## Actual behavior

send request "launch"  recive "attach" expected.

## Expected  behavior

send request "launch" success.

## Steps to reproduce:
python -m debugpy --listen 127.0.0.1:9999 --log-to stdout  --wait-for-client  main1.py

main1.py

import sys
a = 10
print(sys.version)
print(sys.version)
print(sys.version)
print(sys.version)
print(sys.version)
print(sys.version)
print(sys.version)

[debugpy.adapter-26404.log](https://github.com/microsoft/debugpy/files/6390103/debugpy.adapter-26404.log)
[debugpy.server-28932.log](https://github.com/microsoft/debugpy/files/6390104/debugpy.server-28932.log)

**Comment by fabioz** [comment]
This is correct... when you start the process to `--listen`, only an `attach` is valid (the program is already launched, thus a `launch` is invalid).
