### ISSUE TITLE
Unable to find thread to evaluate variable reference

### ISSUE THREAD

**Issue by zhaoya881010** [microsoft/debugpy#600]
## Environment data

- debugpy version: 1.2.1
- OS and version: windows
- Python version (& distribution if applicable, e.g. Anaconda): 3.7
- Using VS Code or Visual Studio:
IDE base Microsoft.VisualStudio.Shared.VSCodeDebugProtocol
## Actual behavior

request "variables"  response "message": "Unable to find thread to evaluate variable reference."

## Expected  behavior

request "variables" success.

## Steps to reproduce:
1. python -m debugpy --listen 127.0.0.1:9999 --log-to stdout  --wait-for-client  main1.py
2. IDE connect 9999

main1.py

import sys
a = 10
print(sys.version)
print(sys.version)
print(sys.version)
print(sys.version)
print(sys.version)
print(sys.version)
print(sys.version)
print(sys.version)

[debugpy.adapter-42248.log](https://github.com/microsoft/debugpy/files/6390194/debugpy.adapter-42248.log)
[debugpy.server-12044.log](https://github.com/microsoft/debugpy/files/6390195/debugpy.server-12044.log)

**Comment by fabioz** [comment]
The logs are missing the `debug.pydevd-<pid>.log` file... can you include that one too?

**Comment by zhaoya881010** [comment]
@fabioz i see, stackframe id incorrect.
