### ISSUE TITLE
When debugging with pypy the debuggee runs twice

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/debugpy#604]
I've tried the insiders build after seeing this issue (latest stable release was complaining about pypy with `The Python path in your debug configuration is invalid`). There error message that there is no valid config is gone (and vscode also show the pypy in the status bar), but the debugger will be started twice and so I get an error popup every time I start my script.

I always get the error `Server[pid=18868] is already being debugged.`  when I try to run my script via `F5`. My test script is just `print("test")`. The `test` is showed in the terminal and debugging works! My terminal output looks like following

```cmd
c:; cd 'c:\Users\username\mypytest'; & 'c:\Users\username\mypytest\env\Scripts\pypy3.exe' 'c:\Users\tbam\.vscode-insiders\extensions\ms-python.python-2021.5.797839398-dev\pythonFiles\lib\python\debugpy\launcher' '58371' '--' 'c:\Users\username\mypytest\t.py'
Process32First failed (getting process from CreateToolhelp32Snapshot).
test
```

It seems that your extension try to run the debugger twice.

I'm using the lastest x64 version of pypy for windows.

```
Python 3.7.10 (51efa818fd9b, Apr 04 2021, 12:09:32)
[PyPy 7.3.4 with MSC v.1927 64 bit (AMD64)] on win32
```

Greetings
Michael

_Originally posted by @tonka3000 in https://github.com/microsoft/vscode-python/issues/16042#issuecomment-830287729_

**Comment by karthiknadig** [comment]
@tonka3000 Can you set `logToFile` to true, in the launch json? The logs will be stored in the extension directory (`%USERPROFILE%\.vscode-insiders\extensions\ms-python.python-2021.5.797839398-dev`), please share all the log files.

**Comment by tonka3000** [comment]
Sure.
[logfiles.zip](https://github.com/microsoft/debugpy/files/6407665/logfiles.zip)

Sometimes I also got this stack trace in the terminal during starting.

```py
Traceback (most recent call last):
  File "C:\Programs\pypy\lib-python\3\runpy.py", line 196, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Programs\pypy\lib-python\3\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\username\.vscode-insiders\extensions\ms-python.python-2021.5.797839398-dev\pythonFiles\lib\python\debugpy\launcher\__main__.py", line 95, in <module>le>
    main()
  File "c:\Users\username\.vscode-insiders\extensions\ms-python.python-2021.5.797839398-dev\pythonFiles\lib\python\debugpy\launcher\__main__.py", line 52, in main
    launcher.channel.wait()
  File "c:\Users\username\.vscode-insiders\extensions\ms-python.python-2021.5.797839398-dev\pythonFiles\lib\python\debugpy\launcher/../..\debugpy\common\messaging.py"py", line 1215, in wait
    parser_thread.join()
  File "C:\Programs\pypy\lib-python\3\threading.py", line 1044, in join
    self._wait_for_tstate_lock()
  File "C:\Programs\pypy\lib-python\3\threading.py", line 1062, in _wait_for_tstate_lock
    self._stop()
  File "C:\Programs\pypy\lib-python\3\threading.py", line 996, in _stop
    assert not lock.locked()
AssertionError
```

**Comment by abcdehc** [comment]
I ran into the same problem. And the internal build cannot be installed successfully. 
https://github.com/microsoft/vscode-python/issues/16042#issuecomment-827169854

**Comment by fabioz** [comment]
I can reproduce the issues. It really seems that `debugpy` is kind of broken with PyPy right now (it kind of works but has some weird interactions such as the sporadic traceback and the error saying that the program is already being debugged).

@karthiknadig @int19h should we start to officially support/test PyPy? (i.e.: right now we don't officially support it/ it's not in the ci)

As a note, pydevd does support PyPy / run it in the ci (so, I think the issues are on the `debugpy` part of the integration).

**Comment by fabioz** [comment]
I just provided a pull request for the issues in PyPy... this doesn't mean it's officially supported since we don't run it in the ci, but at least it should start-up the debugging properly with this fix.
