### ISSUE TITLE
debugger breakpoints on each async for loop

### ISSUE THREAD

**Issue by iTosun** [microsoft/debugpy#605]
## Environment data

- debugpy version: from _version.py
```json 
{
 "date": "2020-12-12T08:17:03-0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "58ef3da9aa99469ef114c9e1ab3a24ebcb325a7d",
 "version": "1.2.1"
}
```
- OS and version: inside docker python:3.9.2-slim-buster
- Python version (& distribution if applicable, e.g. Anaconda): 3.9.2
- Using VS Code or Visual Studio: VS Code

## Actual behavior

Debugger breakpoints on each async for loop because of raised StopAsyncIteration

## Expected  behavior

Debugger not breaking on async for loops

## Steps to reproduce:
1. build a simple async for loop script
2. debug the script

example code to reproduce:
```python
import asyncio

async def mygen(u: int = 10):
    """Yield powers of 2."""
    i = 0
    while i < u:
        yield 2 ** i
        i += 1
        await asyncio.sleep(0.1)

async def do_loop():
    async for i in mygen():
        print(i)

asyncio.run(do_loop())
```

**Comment by fabioz** [comment]
This was actually fixed already in: https://github.com/microsoft/debugpy/commit/2ae7dc96ecc4ca73b119c2056284d203afa10afd (although it's still not in a final release).

The workaround right now is disabling the option to stop at exceptions.
