### ISSUE TITLE
Stepping over a breakpoint on one thread steps over breakpoints on all threads.

### ISSUE THREAD

**Issue by jonfen** [microsoft/debugpy#609]
## Environment data

- debugpy version: 1.2.1
- OS and version: ubuntu 20.04
- Python version (& distribution if applicable, e.g. Anaconda): 3.8.4
- Using VS Code or Visual Studio:

> Version: 1.56.0-insider
> Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
> Date: 2021-05-04T22:51:32.638Z
> Electron: 12.0.4
> Chrome: 89.0.4389.114
> Node.js: 14.16.0
> V8: 8.9.255.24-electron.0
> OS: Linux x64 5.8.0-50-generic snap

## Actual behavior

When stopped on breakpoints in different threads, stepping over one breakpoint using the `CALL STACK` controls for that `THREAD-X` result in stepping over ALL breakpoints.

## Expected  behavior

Only the Thread that you are working on has the breakpoint move.

## Steps to reproduce:
1. git clone https://github.com/jonfen/vscode-python-debugging-tests
2. ./setup.sh
3. cd basic && code-insiders .
4. F5

**Comment by karthiknadig** [comment]
@jonfen Try adding `"steppingResumesAllThreads": false` to your launch configuration and see if that helps.

**Comment by fabioz** [comment]
I'm closing this issue since this should be supported by setting the `steppingResumesAllThreads` flag to `false` as mentioned above.

If it still doesn't work with that setting, please reopen the issue.
