### ISSUE TITLE
Reuslts of `torch.nn.Linear` on GPU are different with that on CPU, while using `debugpy`.

### ISSUE THREAD

**Issue by chenkangyang** [microsoft/debugpy#616]
## Environment data

- debugpy version: 1.3.0 (run `import debugpy; print(debugpy.__version__)` if uncertain)
- OS and version: CentOS Linux release 7.2.1511
- Python version 3.8.0 (& distribution if applicable, e.g. Anaconda): XXX
- Using VS Code or Visual Studio: VS Code
- NVIDIA-SMI 455.32.00    Driver Version: 455.32.00    CUDA Version: 11.1   
- GTX 1080Ti

## Actual behavior

Reuslts of `torch.nn.Linear` on the GPU are different with that on the CPU, while using `debugpy`.

## Expected  behavior

GPU and CPU results should be same

## Steps to reproduce:
1. While using `debugpy`
`bug_reproduce.py `
```python
import torch
import torch.nn as nn

x = torch.rand(4,32).to("cuda:0")
my_fc = nn.Linear(32, 3).to("cuda:0")

my_output = my_fc(x)
self_output = torch.mm(x, my_fc.weight.T) + my_fc.bias

print("On GPU")
print(my_output)
print(self_output)
# ===================================
x = x.to("cpu")
my_fc = my_fc.to("cpu")

my_output = my_fc(x)
self_output = torch.mm(x, my_fc.weight.T) + my_fc.bias

print("On CPU")
print(my_output)
print(self_output)
```

Terminal ouputs:
```zsh
(beta) ➜  proj  git:(master) ✗  cd ~/workspace/proj ; /usr/bin/env ~/anaconda3/envs/beta/bin/python /home/kychen/.vscode-server/extensions/ms-python.python-2021.4.765268190/pythonFiles/lib/python/debugpy/launcher 41680 -- bug_reproduce.py 
On GPU
tensor([[-0.0092, -0.0286, -0.0350],
        [-0.0092, -0.0286, -0.0350],
        [-0.0092, -0.0286, -0.0350],
        [-0.0092, -0.0286, -0.0350]], device='cuda:0', grad_fn=<AddmmBackward>)
tensor([[-0.0092, -0.0286, -0.0350],
        [-0.0092, -0.0286, -0.0350],
        [-0.0092, -0.0286, -0.0350],
        [-0.0092, -0.0286, -0.0350]], device='cuda:0', grad_fn=<AddBackward0>)
On CPU
tensor([[ 0.1264,  0.2798, -0.1117],
        [ 0.4350,  0.3841, -0.0133],
        [ 0.2511, -0.0445, -0.0497],
        [ 0.3326,  0.2383, -0.0987]], grad_fn=<AddmmBackward>)
tensor([[ 0.1264,  0.2798, -0.1117],
        [ 0.4350,  0.3841, -0.0133],
        [ 0.2511, -0.0445, -0.0497],
        [ 0.3326,  0.2383, -0.0987]], grad_fn=<AddBackward0>)
```
Noted that on GPU, `my_output[i] == my_fc.bias` is True, indicating that `torch.mm(x, my_fc.weight.T)` is `0`.

2. While using `python`, get the expected output

Terminal ouputs:
```zsh
(beta) ➜  proj git:(master) ✗ python bug_reproduce.py
On GPU
tensor([[-0.3802, -0.4669, -0.1915],
        [-0.0796,  0.1054,  0.2203],
        [-0.1874, -0.2297,  0.2115],
        [-0.4851, -0.0627, -0.0756]], device='cuda:0', grad_fn=<AddmmBackward>)
tensor([[-0.3802, -0.4669, -0.1915],
        [-0.0796,  0.1054,  0.2203],
        [-0.1874, -0.2297,  0.2115],
        [-0.4851, -0.0627, -0.0756]], device='cuda:0', grad_fn=<AddBackward0>)
On CPU
tensor([[-0.3800, -0.4669, -0.1917],
        [-0.0795,  0.1055,  0.2203],
        [-0.1874, -0.2297,  0.2114],
        [-0.4852, -0.0627, -0.0758]], grad_fn=<AddmmBackward>)
tensor([[-0.3800, -0.4669, -0.1917],
        [-0.0795,  0.1055,  0.2203],
        [-0.1874, -0.2297,  0.2114],
        [-0.4852, -0.0627, -0.0758]], grad_fn=<AddBackward0>)
```
3. `launch.json`
```
"version": "0.2.0",
    "configurations": [
        {
            "name": "Python: vscode bug reproduce",
            "type": "python",
            "cwd": "${workspaceFolder}",
            "request": "launch",
            "program": "testing/bug_reproduce.py",
            "console": "integratedTerminal",
            "justMyCode": false,
            "env": {
                "CUDA_VISIBLE_DEVICES": "2",
            },
        }
"
```

![bugrepoduce](https://user-images.githubusercontent.com/28588778/117533523-e2c57c00-b01f-11eb-99c3-fb8f40a3f97b.gif)

**Comment by fabioz** [comment]
I don't think this seems like an issue in the debugger.

Having different results when running some optimization algorithm in CPU vs GPU is actually expected in general (sometimes even timing differences can play a part or some internal randomization, threading changes, etc... definitely not something to be fixed up in the debugger).

And even if it is the debugger, the fix must be in the code you're using and not in the debugger (the debugger can change things such as timing, tracing, accessing variables, etc and it's up to the programmer using the debugger to make sure that the program is not brittle so that such operations don't affect its results).
