### ISSUE TITLE
VS Code freezes when a breakpoint gets triggered

### ISSUE THREAD

**Issue by hb237** [microsoft/debugpy#619]
## Environment data
- debugpy version: **1.3.0**
- OS and version: **Microsoft Windows 10 Enterprise, Version	10.0.18363 Build 18363**
- Python version (& distribution if applicable, e.g. Anaconda): **3.8.5 64-bit Anaconda**
- Using VS Code or Visual Studio: **VS Code**

## Actual behavior
I try to debug a flask application. I first set a breakpoint and then call the method that triggers it. The VS Code icon will then shortly flash up in orange. When I open VS Code I cannot navigate to any other file or tab. the whole application is frozen. This lasts  normally between 15 seconds to 75 seconds. Afterwards The debugger stops on the breakpoint and highlights the line in yellow. Now I can inspect the values without any problems. Following breakpoints in the same method work properly. If I reach a break point in another method VS code will freeze again.

## Expected  behavior
The debugger should not freeze the application and the break point should be ready for evaluation after only a few seconds.

## Steps to reproduce:
1. I don't know how to reproduce it.

## What I have tried:
- Debugging the application in the PyCharm Community Edition works without problems.
- Reinstalling VS Code results still in the same error.
- Debugging Hello World works fine.
- Running and Debugging https://code.visualstudio.com/docs/python/tutorial-flask works fine as well.
- Deleting the editor history.
- Removing all plugins except the Python plugin.
- Weirdly the debugger was working before. When I checkout the code that was working two weeks before it is now still freezing.

Any hints how to see the logs of the debugger are appreciated.

**Comment by hb237** [comment]
Thank you for your quick reply! 

Here are the generated logs:

[debugger.vscode_17d0fe51-a33c-4f9d-8cdf-929d68cf2dad.log](https://github.com/microsoft/debugpy/files/6490182/debugger.vscode_17d0fe51-a33c-4f9d-8cdf-929d68cf2dad.log)
[debugger.vscode_324186c1-a971-46e7-89f5-685b4d75cea7.log](https://github.com/microsoft/debugpy/files/6490183/debugger.vscode_324186c1-a971-46e7-89f5-685b4d75cea7.log)
[debugpy.adapter-11700.log](https://github.com/microsoft/debugpy/files/6490184/debugpy.adapter-11700.log)
[debugpy.launcher-10360.log](https://github.com/microsoft/debugpy/files/6490185/debugpy.launcher-10360.log)
[debugpy.pydevd.13400.log](https://github.com/microsoft/debugpy/files/6490186/debugpy.pydevd.13400.log)
[debugpy.pydevd.14356.log](https://github.com/microsoft/debugpy/files/6490188/debugpy.pydevd.14356.log)
[debugpy.server-13400.log](https://github.com/microsoft/debugpy/files/6490189/debugpy.server-13400.log)

**Comment by lstolcman** [comment]
Hi, I encountered a similar issue.
Our application is Django served with WSGI https://github.com/Pylons/waitress

When I create breakpoint on API endpoint, and make a request, Vscode UI notifies instantly that we're on a breakpoint, however it hangs for several seconds as the OP described.

I checked different debugpy versions - 1.3.0, 1.2.1, 1.2.0, 1.1.0.
Also, I checked vscode version 1.56.2 and 1.56.0 - the bug occurs

I think, it is related more to python vscode extension, than debugpy, but I don't have time to verify it now.

I attach the logs for debugpy==1.3.0
[debugger.vscode_f5a96241-a612-4993-bfc5-0aedad0af4ba.log](https://github.com/microsoft/debugpy/files/6539478/debugger.vscode_f5a96241-a612-4993-bfc5-0aedad0af4ba.log)
[debugpy.adapter-268.log](https://github.com/microsoft/debugpy/files/6539479/debugpy.adapter-268.log)

**Comment by hb237** [comment]
I still face the issue. But I don't know how to verify whether it is a python vs code extension problem or one with debugpy.

**Comment by fabioz** [comment]
Does someone have a project where this can be reproduced which could be shared? I can't really reproduce it here, which makes it a bit difficult to debug it myself.

If that's not possible, I can provide some instructions on how to use different debugger versions directly from git, without changing the version of the python extension to try to bisect to a debugger version where this happens (that could help to detect whether this is actually related to the debugger)....

**Comment by hb237** [comment]
Thank you fabioz! It is indeed a weird issue. I understand, that it is difficult to investigate if there you can't reproduce it. Unfortunately I am not allowed to share my project. Let me try to use different debuggers. Could you please share the instructions how to achieve that?

**Comment by fabioz** [comment]
Ok, to use the `main` branch do the following:

Clone this repo:

```
git clone https://github.com/microsoft/debugpy.git
cd debugpy
pwd
```

Then, in your launch config add:

`"debugAdapterPath": "<pwd path>/src/debugpy/adapter"` 

Then, that launch would be using the version you just downloaded, so, you should be able to use git to get a different tag or revision and check if you can get to a version where that doesn't happen (and if you do find where it doesn't happen, use git bisect to get to a single commit...).

**Comment by hb237** [comment]
Thank you for your clear instructions. I will look into it the next days and let you know.

**Comment by snalesso** [comment]
I have a similar problem: when Visual Studio Code is not the foreground window and a breakpoint is reached, the application on the taskbar flashes orange, but if you switch to the VSC window looks frozen (no mouse/keyboard interaction feedback), but in reality all operations you do are executed: in this "apparently frozen" state if you toggle off the side panel (or do any other action) VSC does it but it not shown.
To get VSC update the visual again you need to do one of the following:
- drag the window around the screen
- hover VSC on the taskbar and make the thumbnail appear, which will trigger the UI update and make it responsive again

**Comment by hb237** [comment]
I cannot reproduce it anymore.

**Comment by ReaganRealones** [comment]
Me too, any solution yet?

**Comment by int19h** [comment]
@dkent600 , @ReaganRealones Can you share the logs from a session where this happens for you, according to the instructions in earlier comments?

**Comment by dkent600** [comment]
@int19h I'm not using python.  Can you please provide other instructions?  Let me know if you need more info from me to do that.

**Comment by int19h** [comment]
@dkent600 This issue is specifically for the Python debugger used by the Python extension for VSCode. If you're seeing a similar issue with another language, it should be filed as a separate bug in the repository for the corresponding extension.

**Comment by dkent600** [comment]
Hmm, apparently it isn't specific to Python.  But I'll go ahead submit elsewhere.

**Comment by ingbabic** [comment]
This happens to me as well. VS Code freezes before it actually hits the breakpoint. I am debugging node-red...

**Comment by int19h** [comment]
@dkent600, can you link to the issue that you've created in the other repo, so that others with the same problem can find it and subscribe/upvote?

**Comment by konrad79** [comment]
Have the same problem for weeks now - debugging typescript code.

**Comment by rightclickgit** [comment]
Same problem in Autohotkey when breakpoint is set inside a Gui event handler.

**Comment by dudeImpossible42** [comment]
> Ok, to use the `main` branch do the following:
> 
> Clone this repo:
> 
> ```
> git clone https://github.com/microsoft/debugpy.git
> cd debugpy
> pwd
> ```
> 
> Then, in your launch config add to your launch configuration:
> 
> `"debugAdapterPath": "<pwd path>/src/debugpy/adapter"`
> 
> Then, that launch would be using the version you just downloaded, so, you should be able to use git to get a different tag or revision and check if you can get to a version where that doesn't happen (and if you do find where it doesn't happen, use git bisect to get to a single commit...).

This solution and removing very old breakpoints from the run and debug window worked for me. Even commenting out the above configurations but still removing the old breakpoints seemed to do the trick. For some reason I had breakpoints for files that no longer exist and once I removed them, everything began working as usual. I hope this is the final solution and not some stroke of luck. Cheers!
