### ISSUE TITLE
Error message printed when launching using relative paths

### ISSUE THREAD

**Issue by quammy** [microsoft/debugpy#620]
## Environment data

-   Language Server version: v2021.5.1
-   OS and version: Windows 10 Home
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.2

## Expected behaviour

not having any errors when starting a debug process

## Actual behaviour

getting the following errors every time I start debugging:

```
pydev debugger: critical: unable to get real case for file. Details:
filename: [here come the folder name]
drive: 
parts: ['here come the folder name in low case letters']
(please create a ticket in the tracker to address this).
Traceback (most recent call last):
  File "c:\Users\user\.vscode\extensions\ms-python.python-2021.5.829140558\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_file_utils.py", line 221, in _get_path_with_real_case
    return _resolve_listing(drive, iter(parts))
  File "c:\Users\user\.vscode\extensions\ms-python.python-2021.5.829140558\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_file_utils.py", line 184, in _resolve_listing
    dir_contents = cache[resolved_lower] = os.listdir(resolved)
FileNotFoundError: [WinError 3] The system cannot find the path specified: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\user\.vscode\extensions\ms-python.python-2021.5.829140558\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_file_utils.py", line 226, in _get_path_with_real_case
    return _resolve_listing(drive, iter(parts))
  File "c:\Users\user\.vscode\extensions\ms-python.python-2021.5.829140558\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_file_utils.py", line 184, in _resolve_listing
    dir_contents = cache[resolved_lower] = os.listdir(resolved)
FileNotFoundError: [WinError 3] The system cannot find the path specified: ''
pydev debugger: critical: unable to get real case for file. Details:
filename: [here come the folder name]
drive: 
parts: ['here come the folder name in low case letters']
(please create a ticket in the tracker to address this).
Traceback (most recent call last):
  File "c:\Users\user\.vscode\extensions\ms-python.python-2021.5.829140558\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_file_utils.py", line 221, in _get_path_with_real_case
    return _resolve_listing(drive, iter(parts))
  File "c:\Users\user\.vscode\extensions\ms-python.python-2021.5.829140558\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_file_utils.py", line 184, in _resolve_listing
    dir_contents = cache[resolved_lower] = os.listdir(resolved)
FileNotFoundError: [WinError 3] The system cannot find the path specified: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\user\.vscode\extensions\ms-python.python-2021.5.829140558\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_file_utils.py", line 226, in _get_path_with_real_case
    return _resolve_listing(drive, iter(parts))
  File "c:\Users\user\.vscode\extensions\ms-python.python-2021.5.829140558\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_file_utils.py", line 184, in _resolve_listing
    dir_contents = cache[resolved_lower] = os.listdir(resolved)
FileNotFoundError: [WinError 3] The system cannot find the path specified: ''

```

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
XXX
```

**Comment by fabioz** [comment]
@quammy The important parts would be the parts redacted to properly address this (i.e.: `[here come the folder name]`)

Can you give some more details on that? Is that some network-mapped path? What's the size of the path? Do you have long-paths enabled on Windows?

**Comment by quammy** [comment]
@fabioz, the solution is constructed from couple of Python projects as well as a NodeJS and some folders holding different files. To the point, it looks like this:
parentFolder -> pythonFolder_ProjectA
parentFolder -> pythonFolder_ProjectB
parentFolder -> [other folders...]

each of the python projects has several .py files.

The ```[here come the folder name]``` holds the "pythonFolder_ProjectA" name (as it appears in explorer - with upper and lower case letters).

The solution itself is in my one drive folder (path looks like this: C:\Users\user\OneDrive\Development\parentFolder)

Please let me know if you need more info.

**Comment by fabioz** [comment]
Can you provide the logs for this run?

i.e.:

* Open VS Code
* Select the command Extensions: Open Extensions Folder
* Locate the Python extension directory, typically of the form `ms-python.python-2021.*.****`
* In that directory ensure you do not have any debug*.log files, if you do, please delete them
* Go back into VS Code and modify your launch.json to add the setting "logToFile": true, see below:

```
{
    "name": "Python: Current File (Integrated Terminal)",
    "type": "python",
    "request": "launch",
    "program": "${file}",
    "console": "integratedTerminal",
    "logToFile": true
}
```

* Start debugging
* When done, go back into the extension directory and upload the debug*.log files into this GitHub issue.

**Comment by quammy** [comment]
I've made a copy of my solution to C:\\, deleted all folders and files (apart from .env and .vscode) and created two py files - one directly in the root folder (C:\VS-test\app2.py) and another in a folder (C:\VS-test\test\app1.py).
Then I followed your procedure (thanks for the detailed explanation). The app2.py (no parent folder) did **not** produce any errors. The one within a parent folder (app1.py) created the same errors as mentioned above.
Please see attached the logs of each case (distinguished by the name of the zip file).
thanks.
[ms-python.python-2021.5.840043038 - debug no parent folder.zip](https://github.com/microsoft/debugpy/files/6476970/ms-python.python-2021.5.840043038.-.debug.no.parent.folder.zip)
[ms-python.python-2021.5.840043038 - debug w parent folder.zip](https://github.com/microsoft/debugpy/files/6476973/ms-python.python-2021.5.840043038.-.debug.w.parent.folder.zip)

**Comment by quammy** [comment]
Is there any other info/logs/etc. I can provide to help further investigate this issue?

**Comment by fabioz** [comment]
Thanks for the logs (sorry for the delay in getting back to you)...

I see that in the you're specifying `test\\app1.py`... if you specify the full path instead of a relative path based on the `cwd`, does it work?

**Comment by fabioz** [comment]
As a note, I can reproduce it with the relative path (and specifying the full path does fix it for me).

I'll investigate on how to fix this in the debugger side even with the relative path...

**Comment by quammy** [comment]
thanks @fabioz! using the full path solves it for me as well. cheers. waiting for news if you could make it with the relative path...
