### ISSUE TITLE
Improve logging of loading of native library (used to set tracing to all threads)

### ISSUE THREAD

**Issue by emonette123** [microsoft/debugpy#623]
When trying to debug a script running in an embedded interpreter of a third party application, I can successfully connect the debugger using this code in the script running in the embedded interpreter:
```python
import debugpy
if not debugpy.is_client_connected():
    debugpy.configure(python=r"D:\Python\Python38\python.exe")
    debugpy.listen(5678)
    debugpy.wait_for_client()
```
I can see whatever runs in the embedded interpreter is waiting for VS code to connect. I use this launch.json config:
```
{
    "name": "Python: Remote Attach",
    "type": "python",
    "request": "attach",
    "port": 5678,
    "host": "localhost",
    "logToFile": true,
    "pathMappings": [
        {
            "localRoot": "${workspaceFolder}",
            "remoteRoot": "."
        }
    ]
}
```
But afterwards, I just cannot hit any breakpoint. None of the ones set using F9. `debugpy.breakpoint()` does not work either.
This is working with `ptvsd` version 4.3.2, it is no longer working with `ptvsd` version 5.0 or higher.

Here is the log of debugpy, the disconnect at the end happened when I quit the third party application running the embedded interpreter:
```
0 Starting Session:
{
    "name": "Python: Remote Attach",
    "type": "python",
    "request": "attach",
    "port": 5678,
    "host": "localhost",
    "logToFile": true,
    "pathMappings": [
        {
            "localRoot": "d:\\vscode_setup\\setup_debugpy",
            "remoteRoot": "D:\\vscode_setup\\setup_debugpy"
        }
    ],
    "__configurationTarget": 5,
    "debugOptions": [
        "RedirectOutput",
        "FixFilePathCase",
        "WindowsClient",
        "ShowReturnValue"
    ],
    "justMyCode": true,
    "showReturnValue": true,
    "workspaceFolder": "d:\\vscode_setup\\setup_debugpy"
}
2 Client --> Adapter:
{
    "command": "initialize",
    "arguments": {
        "clientID": "vscode",
        "clientName": "Visual Studio Code",
        "adapterID": "python",
        "pathFormat": "path",
        "linesStartAt1": true,
        "columnsStartAt1": true,
        "supportsVariableType": true,
        "supportsVariablePaging": true,
        "supportsRunInTerminalRequest": true,
        "locale": "en",
        "supportsProgressReporting": true,
        "supportsInvalidatedEvent": true
    },
    "type": "request",
    "seq": 1
}
3 Client <-- Adapter:
{
    "seq": 1,
    "type": "event",
    "event": "output",
    "body": {
        "category": "telemetry",
        "output": "ptvsd",
        "data": {
            "packageVersion": "1.3.0"
        }
    }
}
3 Client <-- Adapter:
{
    "seq": 2,
    "type": "event",
    "event": "output",
    "body": {
        "category": "telemetry",
        "output": "debugpy",
        "data": {
            "packageVersion": "1.3.0"
        }
    }
}
3 Client <-- Adapter:
{
    "seq": 3,
    "type": "response",
    "request_seq": 1,
    "success": true,
    "command": "initialize",
    "body": {
        "supportsCompletionsRequest": true,
        "supportsConditionalBreakpoints": true,
        "supportsConfigurationDoneRequest": true,
        "supportsDebuggerProperties": true,
        "supportsDelayedStackTraceLoading": true,
        "supportsEvaluateForHovers": true,
        "supportsExceptionInfoRequest": true,
        "supportsExceptionOptions": true,
        "supportsHitConditionalBreakpoints": true,
        "supportsLogPoints": true,
        "supportsModulesRequest": true,
        "supportsSetExpression": true,
        "supportsSetVariable": true,
        "supportsValueFormattingOptions": true,
        "supportsTerminateDebuggee": true,
        "supportsGotoTargetsRequest": true,
        "supportsClipboardContext": true,
        "exceptionBreakpointFilters": [
            {
                "filter": "raised",
                "label": "Raised Exceptions",
                "default": false
            },
            {
                "filter": "uncaught",
                "label": "Uncaught Exceptions",
                "default": true
            }
        ],
        "supportsStepInTargetsRequest": true
    }
}
18 Client --> Adapter:
{
    "command": "attach",
    "arguments": {
        "name": "Python: Remote Attach",
        "type": "python",
        "request": "attach",
        "port": 5678,
        "host": "localhost",
        "logToFile": true,
        "pathMappings": [
            {
                "localRoot": "d:\\vscode_setup\\setup_debugpy",
                "remoteRoot": "D:\\vscode_setup\\setup_debugpy"
            }
        ],
        "__configurationTarget": 5,
        "debugOptions": [
            "RedirectOutput",
            "FixFilePathCase",
            "WindowsClient",
            "ShowReturnValue"
        ],
        "justMyCode": true,
        "showReturnValue": true,
        "workspaceFolder": "d:\\vscode_setup\\setup_debugpy",
        "__sessionId": "8aff789f-24de-4f9f-a68b-f11f66bcb18b"
    },
    "type": "request",
    "seq": 2
}
19 Client <-- Adapter:
{
    "seq": 4,
    "type": "event",
    "event": "debugpyWaitingForServer",
    "body": {
        "host": "127.0.0.1",
        "port": 60102
    }
}
23 Client <-- Adapter:
{
    "seq": 5,
    "type": "event",
    "event": "initialized"
}
28 Client --> Adapter:
{
    "command": "setBreakpoints",
    "arguments": {
        "source": {
            "name": "gui.py",
            "path": "d:\\vscode_setup\\setup_debugpy\\setup_debugpy\\gui.py"
        },
        "lines": [
            130
        ],
        "breakpoints": [
            {
                "line": 130
            }
        ],
        "sourceModified": false
    },
    "type": "request",
    "seq": 3
}
28 Client --> Adapter:
{
    "command": "setBreakpoints",
    "arguments": {
        "source": {
            "name": "setup_debugpy_entrypoint.py",
            "path": "d:\\vscode_setup\\setup_debugpy\\application\\setup_debugpy_entrypoint.py"
        },
        "lines": [
            12
        ],
        "breakpoints": [
            {
                "line": 12
            }
        ],
        "sourceModified": false
    },
    "type": "request",
    "seq": 4
}
32 Client <-- Adapter:
{
    "seq": 6,
    "type": "response",
    "request_seq": 3,
    "success": true,
    "command": "setBreakpoints",
    "body": {
        "breakpoints": [
            {
                "verified": true,
                "id": 0,
                "source": {
                    "name": "gui.py",
                    "path": "d:\\vscode_setup\\setup_debugpy\\setup_debugpy\\gui.py"
                },
                "line": 130
            }
        ]
    }
}
33 Client <-- Adapter:
{
    "seq": 7,
    "type": "response",
    "request_seq": 4,
    "success": true,
    "command": "setBreakpoints",
    "body": {
        "breakpoints": [
            {
                "verified": true,
                "id": 1,
                "source": {
                    "name": "setup_debugpy_entrypoint.py",
                    "path": "d:\\vscode_setup\\setup_debugpy\\application\\setup_debugpy_entrypoint.py"
                },
                "line": 12
            }
        ]
    }
}
66 Client --> Adapter:
{
    "command": "setExceptionBreakpoints",
    "arguments": {
        "filters": [
            "uncaught"
        ]
    },
    "type": "request",
    "seq": 5
}
68 Client <-- Adapter:
{
    "seq": 8,
    "type": "response",
    "request_seq": 5,
    "success": true,
    "command": "setExceptionBreakpoints"
}
71 Client --> Adapter:
{
    "command": "configurationDone",
    "type": "request",
    "seq": 6
}
73 Client <-- Adapter:
{
    "seq": 9,
    "type": "response",
    "request_seq": 6,
    "success": true,
    "command": "configurationDone"
}
73 Client <-- Adapter:
{
    "seq": 10,
    "type": "response",
    "request_seq": 2,
    "success": true,
    "command": "attach"
}
73 Client <-- Adapter:
{
    "seq": 11,
    "type": "event",
    "event": "process",
    "body": {
        "name": "D:\\vscode_setup\\setup_debugpy\\application\\setup_debugpy_entrypoint.py",
        "systemProcessId": 5076,
        "isLocalProcess": true,
        "startMethod": "attach"
    }
}
74 Client <-- Adapter:
{
    "seq": 12,
    "type": "event",
    "event": "thread",
    "body": {
        "reason": "started",
        "threadId": 1
    }
}
76 Client --> Adapter:
{
    "command": "threads",
    "type": "request",
    "seq": 7
}
77 Client <-- Adapter:
{
    "seq": 13,
    "type": "response",
    "request_seq": 7,
    "success": true,
    "command": "threads",
    "body": {
        "threads": [
            {
                "id": 1,
                "name": "MainThread"
            }
        ]
    }
}
183 Client --> Adapter:
{
    "command": "threads",
    "type": "request",
    "seq": 8
}
206 Client <-- Adapter:
{
    "seq": 14,
    "type": "response",
    "request_seq": 8,
    "success": true,
    "command": "threads",
    "body": {
        "threads": [
            {
                "id": 1,
                "name": "MainThread"
            }
        ]
    }
}
23167 Client <-- Adapter:
{
    "seq": 15,
    "type": "event",
    "event": "terminated"
}
23171 Client --> Adapter:
{
    "command": "disconnect",
    "arguments": {
        "restart": false
    },
    "type": "request",
    "seq": 9
}
23171 Client <-- Adapter:
{
    "seq": 16,
    "type": "response",
    "request_seq": 9,
    "success": true,
    "command": "disconnect"
}
24034 Stopping Session
24035 Error:
{}
```

Configuration:
Version: 1.56.0 (user setup)
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T22:09:06.405Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042

Name: Python
Id: ms-python.python
Description: IntelliSense (Pylance), Linting, Debugging (multi-threaded, remote), Jupyter Notebooks, code formatting, refactoring, unit tests, and more.
Version: 2021.5.829140558
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-python.python

debugpy: 1.3.0

**Comment by fabioz** [comment]
If you set `"justMyCode": false` in your launch config, does it work?

If it still doesn't work, can you provide the logging from `debugpy`?

To get it you can add `logToFile": true` in your launch config and get the logs from the extension folder.

i.e.:

* Open VS Code
* Select the command Extensions: Open Extensions Folder
* Locate the Python extension directory, typically of the form `ms-python.python-2021.*.****`
* In that directory ensure you do not have any debug*.log files, if you do, please delete them
* Go back into VS Code and modify your launch.json to add the setting "logToFile": true
* Make attach/Start debugging
* When done, go back into the extension directory and attach the debug*.log files into this GitHub issue.

**Comment by emonette123** [comment]
The log file was already in the description of the problem, but here it is as an attachment.

[debugger.vscode_6d82b2c4-70a1-4dfa-b794-7d67da109235.log](https://github.com/microsoft/debugpy/files/6575779/debugger.vscode_6d82b2c4-70a1-4dfa-b794-7d67da109235.log)

**Comment by fabioz** [comment]
@emonette123 that logging isn't really enough (that's the log from `vscode` itself, whereas I'm interested in the logging from `debugpy`, which can be gotten following the instructions above).

**Comment by emonette123** [comment]
That is the only log file I have in the extension directory in my %USERPROFILE%... I also looked in the installation directory, nothing there. Looked in the `debugpy` directory, nothing either. Where would those logs be?

**Comment by fabioz** [comment]
You can reach the folder with `Select the command Extensions: Open Extensions Folder` and then go into the related `ms-python.python-2021.*.****` (which is the folder where the logs will be generated) and then you need to do the launch with `logToFile": true`.

See: https://github.com/microsoft/debugpy/issues/623#issuecomment-849619745 for detailed instructions.

**Comment by emonette123** [comment]
That is exactly what I did and where I was looking for log files. The only one there is the one I attached...

**Comment by fabioz** [comment]
Humm, maybe the attach isn't properly using the `logToFile`... Well, since it's an attach, you should also be able to do it through the API, so, remove that `logToFile` from the launch and in the server side call `debugpy.log_to` before `debugpy.listen`:

i.e.:

`debugpy.log_to("c:/temp")`  <-- change to the directory you want to log to.

As a note, you can remove the `pathMappings` in that launch as you're debugging on the same machine.

**Comment by emonette123** [comment]
By the way, thank you very much for your quick responses and availability.
Here are the logs:
[debugpy.server-7556.log](https://github.com/microsoft/debugpy/files/6576027/debugpy.server-7556.log)
[debugpy.adapter-7008.log](https://github.com/microsoft/debugpy/files/6576028/debugpy.adapter-7008.log)

**Comment by fabioz** [comment]
Humm, I'm still missing a log file (which is the one I really cared about), which is the `debugpy.pydevd-xxx.log` log file... is there any additional log file there?

**Comment by emonette123** [comment]
No, these are the 2 log files I got. Even when I close the host app and vs code. Let me try to make that log file appear.

**Comment by fabioz** [comment]
Humm, let's try to just enable the logging for that file then... remove any entry to `logFile` in the launch and the `log_to` call from `debugpy`, then set the following environment variables (in the server).

`PYDEVD_DEBUG_FILE=c:/temp/pydevd.log`  <-- replace c:/temp to any other folder you'd like
`PYDEVD_DEBUG=1`

Then, start your program, do the attach, wait for it to complete and then provide those logs.

-- p.s.: sorry about all that work, I'm not sure why those logs haven't been properly created for you in the first place...

**Comment by emonette123** [comment]
[pydevd.10212.log](https://github.com/microsoft/debugpy/files/6576171/pydevd.10212.log)
Voilà!

**Comment by emonette123** [comment]
The exact same setup of host application and remote debugging works fine with ptvsd 4.3.2. It broke with ptvsd version 5.

**Comment by fabioz** [comment]
Humm, the logs are apparently fine (the line you commented about is actually expected).

Can you try to set the following environment variables:

```
PYDEVD_USE_CYTHON=0
LOAD_NATIVE_LIB_FLAG=0
```
and rerun to see if it makes any difference?

--- 

Some additional info:

The logs show that breakpoints were added at:
```
Added breakpoint: d:\users\etiennem\nxopen\vscode_setup\setup_debugpy\application\setup_debugpy_entrypoint.py - line:12
Added breakpoint: d:\users\etiennem\nxopen\vscode_setup\setup_debugpy\setup_debugpy\gui.py - line:130
```

and later on it shows that it traced:

`Set tracing of frame: D:\users\etiennem\NXOpen\vscode_setup\setup_debugpy\setup_debugpy\gui.py - main`

So, it does seem like it should've hit the breakpoint at that place (changes in casing are expected here and should still match on windows).... Given that it's an embedded Python, it's possible that the native libs have some mismatch, so, the first step is trying to run without that.

If it doesn't fix it, I'll probably need to gather additional info on why it's not working...

**Comment by emonette123** [comment]
Same result, the only difference is the line `Using Cython speedups` is not in the log.
[pydevd.15020.log](https://github.com/microsoft/debugpy/files/6592622/pydevd.15020.log)

**Comment by fabioz** [comment]
I'm sorry, I seem to have copied/pasted one wrong value above (it should've been `PYDEVD_LOAD_NATIVE_LIB=0` -- instead of `LOAD_NATIVE_LIB_FLAG`), so, if you could rerun with that flag it'd be nice...

I'll prepare some instructions on how to get it running from a custom version from git where I add some additional tracing so that I can see better what's happening...

**Comment by fabioz** [comment]
Ok, I've created a branch (`break_skip_623`) with additional logging to provide additional information to diagnose this.

So, to run, please do the following:

1. Download this repo locally and checkout the proper branch:

```
git clone https://github.com/microsoft/debugpy.git
git checkout break_skip_623
```

2. Use the code below to attach on the server side (setting the `downloaded_debug_py_folder`  and `pydevd_debug_file` to the appropriate values):

```
import sys

# Update these variables to match the proper path where debugpy is downloaded.
downloaded_debug_py_folder = r"c:\temp\debugpy"
pydevd_debug_file = r"c:\temp\debugpy\pydevd.log"

# Add debugpy to the pythonpath
import os

add_to_pythonpath = os.path.join(downloaded_debug_py_folder, "src")
if add_to_pythonpath not in sys.path:
    assert os.path.exists(add_to_pythonpath), 'Error: %s does not exist' % (add_to_pythonpath,)
    assert "debugpy" not in sys.modules, "Error: debugpy already imported"
    os.environ["PYDEVD_LOAD_NATIVE_LIB"] = "0"
    os.environ["PYDEVD_USE_CYTHON"] = "0"
    os.environ["PYDEVD_DEBUG"] = "1"
    os.environ["PYDEVD_DEBUG_FILE"] = pydevd_debug_file
    sys.path.insert(0, add_to_pythonpath)

import debugpy

if not debugpy.is_client_connected():
    debugpy.configure(python=r"D:\Python\Python38\python.exe")
    debugpy.listen(5678)
    debugpy.wait_for_client()
```

3. Make the attach on the vscode side and provide the logging (based on the `pydevd_debug_file` value).

**Comment by emonette123** [comment]
It works with PYDEVD_LOAD_NATIVE_LIB=0... Do you still want me to do the other test? It might take me a bit longer as I do not really have access to github on the computer I have to use to test this.

**Comment by emonette123** [comment]
I logged this using your branch of `debugpy`. I just copied over the debugpy directory to my libs directory since I use a virtual environement setup, it was simpler than fiddling with the sys.path. I hope the log will help you. The PYDEVD_LOAD_NATIVE_LIB to zero is the cure for now. And yes, the embedded setup we are currently using is not the cleanest one, but we do not have any control over it. We have to live with that mess.
[pydevd.16040.log](https://github.com/microsoft/debugpy/files/6593966/pydevd.16040.log)

**Comment by emonette123** [comment]
By the way, I find it kind of awkward you would now use `sys.executable` to spawn a python interpreter of your own... For any embedded interpreter, this will actually spawn the embedding app. Why don't you rely on the python interpreter VS Code is actually using? That seems like a safer approach to me.

**Comment by int19h** [comment]
This is an attach scenario, and so the adapter is spawned before the client connects (the adapter is what opens the socket waiting for the client), hence why we can't use the client "python" setting to spawn - we don't know it yet.

In launch scenario, it works exactly as you describe - the client can (and VSCode does) set "python" and other related properties automatically.

**Comment by emonette123** [comment]
And I guess the adapter runs on the server side... makes sense.

**Comment by int19h** [comment]
To be more precise, it depends on the direction of the connection. Here you're using `listen()` on the debuggee side, and "connect" in your launch.json. But this can be reversed - you can make VSCode listen for incoming connections from debug server (and thus spawn the adapter locally) by using "listen" in your launch.json, and then use `debugpy.connect()` to attach the server.

**Comment by emonette123** [comment]
I was able to make it work in a more reliable way using VS Code as a listener. As Pavel explained, the adapter is then spawn "locally" and it uses whatever python interpreter VS Code knows about. Here is my debug function, called on the embedded interpreter:
```python
def debug():
    """
    Debug the script with debugpy.
    """
    os.environ["PYDEVD_LOAD_NATIVE_LIB"] = "0"
    import debugpy  # pylint: disable=imports

    if not debugpy.is_client_connected():
        debugpy.connect(5678)
        debugpy.wait_for_client()
```
I still need the environment variable about native lib in order to reach my breakpoints, but I no longer need a special config to tell the adapter where to find python.
My launch.json file now has a listener config:
```
        {
            "name": "Python: Listen to Remote",
            "type": "python",
            "request": "attach",
            "listen": {
                "port": 5678,
                "host": "localhost"
            }
        }
```
You have to put VS Code in debug listen mode prior to running your script on the embedded interpreter, but after that, it all works.
Let me know if you need more information on why the PYDEVD_LOAD_NATIVE_LIB env var has to be set to zero for this to work properly, but for now, this is satisfactory for me. Thank you very much for your help!

**Comment by fabioz** [comment]
Nice that it's working... apparently the code to set the tracing isn't working as it should in your case.

Can you do a final run there to check why is that? I've updated the code in the `break_skip_623` branch, so, if you could pull those changes and do a final run (with `PYDEVD_LOAD_NATIVE_LIB=1`) and then provide the logs as well as the output from stdout/stderr it could help in knowing why it didn't work.

-- i.e.: there's a custom set trace function to set tracing to all the available threads and not just the current thread (which is enabled in the native lib) and apparently that's not working properly for your case (probably due to the interpreter embedding). Still, it's a bit troubling that the code didn't automatically detect that it didn't work and proceeded to do the regular set trace provided by python (hopefully that additional logging will provide more details).

**Comment by emonette123** [comment]
[pydevd.NATIVE_LIB_1.log](https://github.com/microsoft/debugpy/files/6600386/pydevd.NATIVE_LIB_1.log)
[pydevd.NATIVE_LIB_0.log](https://github.com/microsoft/debugpy/files/6600387/pydevd.NATIVE_LIB_0.log)

First log is using native lib, second log is not using it. For the first log, the break points were not reached. For the second log, they were reached. I then ran the script to completion and closed the host app in both cases.

**Comment by fabioz** [comment]
Humm, the important bits are actually the `stdout` and `stderr` -- and those can't really be easily redirected in this case because they're printed from C/C++ and not from Python (as the issue is in the native integration and not on Python itself).

On the Python side it said that it worked (due to the message: `Tracing set for existing threads. Result: 0`), but in reality I know it didn't work because the frames aren't traced afterwards -- and the important output is printed to the `c stdout`.

Redirecting would be possible, but it requires more work on my side as it requires recompiling the native libraries (to make the print to the file and not just to the stdout).

**Comment by fabioz** [comment]
I'll take a look into improving that... having the capability to get logging from the native bits is something interesting into itself, although it may take a while until I can get to that. Hopefully you'll be able to run it from that branch once I'm able to get it done ;)
