### ISSUE TITLE
cannot assign requested address when using debugpy in vscode remote development

### ISSUE THREAD

**Issue by suyashdeshpande** [microsoft/debugpy#634]
## Environment data

- debugpy version: XXX (run `import debugpy; print(debugpy.__version__)` if uncertain)
- Vscode:
Version: 1.56.2 (Universal)
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:44:30.902Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 20.4.0

## Actual behavior

This error pops up every time irrespective of any port number I use
"cannot assign requested address"

## Expected  behavior

Code should wait to let the debug server attach to it.

## Steps to reproduce:
1. Use vscode remote development feature to work on a remote machine using ssh
2. Start the flask server in a docker container
3. Put this code in a python file
```
import debugpy
debugpy.listen(('0.0.0.0', 18304))
debugpy.wait_for_client()
debugpy.breakpoint()
```
4. Start a debug server on the above-mentioned port. I always get the error that cannot assign requested address.

**Comment by fabioz** [comment]
I think that this issue isn't really on the debugger side, but rather on the machine you're using (which is not able to assign the requested address).

See: 
https://stackoverflow.com/questions/19246103/socket-errorerrno-99-cannot-assign-requested-address-and-namespace-in-python/19267994 for more details...
