### ISSUE TITLE
Python debugging suboptimal behaviour in VSCode

### ISSUE THREAD

**Issue by KubaMichalczyk** [microsoft/debugpy#644]
Yesterday I started experiencing issues with my Python debugger. I set the breakpoint to class instantiation just after loading some data. However, when my debugger hits the breakpoint, I can't continue/step into/step over/step out - all of these options are inactive when clicked. At the same time, local variables are trying to be accessed from the debugger - see picture below:
![Screenshot from 2021-06-12 22-33-52](https://user-images.githubusercontent.com/37018819/121799383-0fc30b00-cc2c-11eb-9006-571758d0cf40.png)

Only responsive debugger options are to restart or stop debugging. At the same time, the python process still runs at ~100% CPU, and memory continuously inflates. After a while, the debugger becomes responsive again. Still, even the simplest if sth is not None check (where sth is already created object), calls the same behaviour (~100% CPU and memory continuously inflates again) and takes ages. As a result, when running without debugging mode, the whole script takes less than 30 seconds, while in debugging mode, it takes a couple of minutes with each line after some point in code (where the data is loaded).

At the beginning I thought it was connected to the recent update to 1.57 version, but I downgraded to 1.53.2 for testing purposes and the issue remained. 

Unfortunately, I can't share my code, but I'll be happy to provide any other information to make my situation clearer if needed.

CPUs | Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)
GPU Status | 2d_canvas: enabled gpu_compositing: enabled multiple_raster_threads: enabled_on oop_rasterization: disabled_off opengl: enabled_on protected_video_decode: unavailable_off rasterization: disabled_software skia_renderer: enabled_on video_decode: disabled_software vulkan: disabled_off webgl: enabled webgl2: enabled
Load (avg) | 2, 2, 2
Memory (System) | 31.28GB (11.94GB free)
Process Argv | --no-sandbox --unity-launch --crash-reporter-id d06e8ed6-24d7-4111-b07c-ecb070beae23
Screen Reader | no
VM | 0%

vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833cf:30267465
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscorehov:30309549
vscod805:30301674
binariesv517:30312825

**Comment by fabioz** [comment]
My guess is that the process of gathering the values for one of your local variables is slow (the debugger needs to `dir()` your variables and later do a `repr` on each one and that's likely slow in your program for one of your variables).

Can you provide the logs when this happens to try to diagnose better?

i.e.:

* Open VS Code
* Select the command Extensions: Open Extensions Folder
* Locate the Python extension directory, typically of the form `ms-python.python-2021.*.****`
* In that directory ensure you do not have any debug*.log files, if you do, please delete them
* Go back into VS Code and modify your launch.json to add the setting "logToFile": true, see below:

```
{
    "name": "Python: Current File (Integrated Terminal)",
    "type": "python",
    "request": "launch",
    "program": "${file}",
    "console": "integratedTerminal",
    "logToFile": true
}
```

* Start debugging
* When done, go back into the extension directory and upload the debug*.log files into this GitHub issue.
