### ISSUE TITLE
Launch option "justMyCode" does not work, but "debugStdLib" does

### ISSUE THREAD

**Issue by haimat** [microsoft/debugpy#645]
## Environment data

-   Language Server version: 2021.6.1 (pyright e3f7cccc)
-   OS and version: Ubuntu 20.04 LTS
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.5 64-bit

## Expected behaviour

I am calling a third party Python module from my code, which I have installed via `pip`. This module seems to be buggy, so I wanted to debug into it (i.e. when I call it from my code). So I added a breakpoint in the 3rd party module code. AndI also added the option `"justMyCode": false` to my launch configuration. I was expecting the debugger to stop in the call of the external module, but it didn't.

## Actual behaviour

Then I added another option `"debugStdLib": true` to my launch configuration, and with that the debugger does indeed stop at the call of the xternal code. Note: The editor of the launch JSON file does highlight  this latter option as error, but it does still work, as explained here.

**Comment by fabioz** [comment]
@haimat this is rather strange, as `debugStdLib` should be deprecated, being replaced by `justMyCode`... 

I think that the most likely scenario here is that you have an older version of the debugger installed in the environment and it's being picked up (can you confirm if that's the case?)

If that's not the case (or if you can't find it out), please provide logging for the run with `"justMyCode": false` where it's not working.

i.e.:

* Open VS Code
* Select the command Extensions: Open Extensions Folder
* Locate the Python extension directory, typically of the form `ms-python.python-2021.*.****`
* In that directory ensure you do not have any debug*.log files, if you do, please delete them
* Go back into VS Code and modify your launch.json to add the setting "logToFile": true, see below:

```
{
    "name": "Python: Current File (Integrated Terminal)",
    "type": "python",
    "request": "launch",
    "program": "${file}",
    "console": "integratedTerminal",
    "logToFile": true,
    "justMyCode": false
}
```

* Start debugging
* When done, go back into the extension directory and upload the debug*.log files into this GitHub issue.

**Comment by haimat** [comment]
> I think that the most likely scenario here is that you have an older version of the debugger installed in the environment and it's being picked up (can you confirm if that's the case?)

Would you please be so kind and elaborate on this, how can I find out whether it's an old debugger version?

**Comment by fabioz** [comment]
> Would you please be so kind and elaborate on this, how can I find out whether it's an old debugger version?

You can run:

```
import debugpy
print(debugpy)
print(debugpy.__version__)
```

to know where it's installed and what's the current version.

**Comment by haimat** [comment]
@fabioz Unfortunately that did not work from a normal Python shell:

    ModuleNotFoundError: No module named 'debugpy'

Do I have to try and import that Python module `debugpy` from within VS Code or something?

**Comment by fabioz** [comment]
> Do I have to try and import that Python module `debugpy` from within VS Code or something?

You have to run that from a debug run.

**Comment by haimat** [comment]
Ahh sure, thanks. Here is the output:

    <module 'debugpy' from '/home/mfb/.vscode-server/extensions/ms-python.python-2021.6.944021595/pythonFiles/lib/python/debugpy/../debugpy/__init__.py'>
    1.3.0

**Comment by fabioz** [comment]
It seems as it's using the correct version.

Can you provide the logging for these cases (from the version where you pass only `justMyCode` as well as the version where you pass only the `debugStdLib`?)

See: https://github.com/microsoft/debugpy/issues/645#issuecomment-863206939 for instructions...

**Comment by haimat** [comment]
Ok guys, I have no idea why but it works now.
While trying to generate the logs it turned out that `"justMyCode": false` option works fine.

Sorry for the inconvenience!
