### ISSUE TITLE
How to handle the `debugpyAttach` event?

### ISSUE THREAD

**Issue by mfussenegger** [microsoft/debugpy#655]
The wiki mentions that the [debugpyAttach](https://github.com/microsoft/debugpy/wiki/DAP-Client-reference#debugpyattach-event) includes a fully formed attach configuration and then refers to the VS Code 'debug.startDebugging' API.

I'm considering adding support for the event to nvim-dap-python (A python specific extension for nvim-dap) and wonder if there is any more information how the attach configuration should be utilized. I guess you're supposed to create another session - but how is the client then supposed to manage two (or more) sessions?

Should all requests then be sent to all sessions?
Was there already some discussion in the debug adapter protocol repository to standardize this kind of multi session requirement?  vscode-js-debug also utilizes multiple session, but they went a slightly different route.

**Comment by karthiknadig** [comment]
> but how is the client then supposed to manage two (or more) sessions?

You could try this out in VS Code to see how the UI handles various scenarios (to get some ideas on the UI aspect). Each session is listed in a selectable drop down that the user can select to make it the "active" session. From communication point of view, each session should be treated like its own thing.

The "bug" symbol indicates a separate session, in this cases they are all part of the same process tree, so they are added as a node under the process that is its parent in the process tree. The "active" session here is the one where the breakpoint is hit (Subprocess 10916), so any request from user would apply to that session.  
![image](https://user-images.githubusercontent.com/3840081/124792733-21819080-df02-11eb-97de-e2b145b677ad.png)

 User could also specifically send requests to session that are not currently active by clicking on controls for that particular session. From the previous screenshot you know that subprocess 27064 is still running, so you see the pause action available for that session:
![image](https://user-images.githubusercontent.com/3840081/124793355-c13f1e80-df02-11eb-9016-0e22c91801eb.png)


> Should all requests then be sent to all sessions?

Requests are sent to a single session (the active session). 

> Was there already some discussion in the debug adapter protocol repository to standardize this kind of multi session requirement?

Yes. They did not have plans to support multiple sessions at that time.

The main session is where the debugger first starts in, any process that the main process invokes results in child sessions that are related to the main session. This relation is important when closing sessions, like you could terminate the main session, and it would cause all child sessions to terminate as well. But terminating a child session will not terminate the main session. Most of this is handled for you automatically by debugpy. So in your client implementation you don't have to specifically handle this. 

There are things to consider though from DAP client point of view, like when you hit the same breakpoint in multiple child processes you may have to switch the "active" session based on which ever breakpoint was last hit. When the user switches "active" session you may have to re-request variables, scopes, threads etc. There are several minor things that are user experience related that a DAP client has to handle when it comes to dealing with multi-process scenarios.

We have test dap client and tests that should give you some starting point on how to work with multiple sessions:
https://github.com/microsoft/debugpy/blob/main/tests/debugpy/test_multiproc.py

Thanks for using debugpy in your extension. Let us know if you have more questions.

**Comment by mfussenegger** [comment]
Thank you for the detailed answer.

While looking into how I could implement that I encountered another undocumented custom event:

```
{
  body = {
    host = "127.0.0.1",
    port = 43825
  },
  event = "debugpyWaitingForServer",
  seq = 4,
  type = "event"
}
```

What is a client supposed to do on such a event?

**Comment by karthiknadig** [comment]
DAP clients can ignore that event. It is used to track connection and timeouts in cases where the sub-processes are taking to long to connect back to the debug adapter server. It is useful when debugging connection issues.

**Comment by mfussenegger** [comment]
Thanks for the answers :+1:
