### ISSUE TITLE
Step into targets doesn't seem to respect selected option

### ISSUE THREAD

**Issue by luabud** [microsoft/debugpy#661]
## Environment data

- debugpy version: 1.3.0
- OS and version: Windows 10
- Python version (& distribution if applicable, e.g. Anaconda): 3.8.10 (venv)
- Using VS Code or Visual Studio: VS Code

## Expected  behavior

Selecting the "Image" option that shows after I run "Step into target..." should step into the Image file:

![image](https://user-images.githubusercontent.com/45497113/125538050-11c335fb-4f42-48e3-805b-199975a29be4.png)

## Actual behavior

Selecting "Image" gives the same behaviour as if I did a normal "step into" (i.e. steps into the parse_content method)

## Steps to reproduce:
1. Clone https://github.com/luabud/pvscc-logo
2. Set up a venv and install the dependencies in the requirements.txt file
3. Create the following launch.json configuration:
```json
{
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "justMyCode": false,
            "autoReload": {"enable": true}
}
```
4. Open the generate_logo.py file (located on the root of the project)
5. Set up a breakpoint on line 13
6. Start debugging (F5) using the configuration we created above
7. When the debugger stops on line 13, right-click on line 15 (`wc = generate_wordcloud(parse_content(url),np.array(Image.open(mask_path)))` ) and select "Jump to Cursor". This is just to avoid the if condition on line 14, that will return false by default. 
8. Once in line 15, right click and select "Step into Targets..." 
9. Select "Image"
10. Watch it step into the parse_content method instead

**Comment by luabud** [comment]
it's worth noting that after I end up into parse_content, if I do a step out and then a step into again, I do end up in the Image target (or at least I'm assuming that's the Image target):

![image](https://user-images.githubusercontent.com/45497113/125540357-8682fc1b-b634-4ba6-ad87-45ea7aad7ffc.png)

**Comment by fabioz** [comment]
Something really seems off there (I already started investigating).

As a note, in this case the `Image` and `np` shouldn't even appear, only the `open` and `array` (so, something is off in the metadata collected).
