### ISSUE TITLE
timeit doesn't print to VS Code Python Debug Console

### ISSUE THREAD

**Issue by pauljurczak** [microsoft/debugpy#668]
-   VS Code version: 1.58.2
-   Extension version (available under the Extensions sidebar): 2021.6.944021595
-   OS and version: Ubuntu 18.04.5
-   Python version (& distribution if applicable, e.g. Anaconda): 3.6.9

This snippet:
```
from timeit import timeit

print('----')
timeit('math.sqrt(2.0)','import math')
print('----')
```
executed in VS Code produces this in Python Debug Console:
```
paul@desktop:~/st/hello-py$  cd /home/paul/st/hello-py ; /usr/bin/env /usr/bin/python3 /home/paul/.vscode/extensions/ms-python.python-2021.6.944021595/pythonFiles/lib/python/debugpy/launcher 41595 -- /home/paul/st/hello-py/main.py 
----
----
```
where output from `timeit` is missing. When run from command line:
```
paul@desktop:~$ python3
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from timeit import timeit
>>> timeit('math.sqrt(2.0)','import math')
0.03520860901335254
```
it produces `timeit` output.

**Comment by int19h** [comment]
`timeit` doesn't print the time - it returns it as a value. When you execute it from the Python REPL, the latter prints the value of every expression that you submit. But when running it as a script, you have to print it yourself:
```py
print(timeit('math.sqrt(2.0)','import math'))
```
This is the case regardless of whether you're debugging or not. E.g. if you run your script manually via `python3 main.py` in the terminal, you'll see the same output.
