### ISSUE TITLE
Attach to local process not working in VS Code on Windows with venv 

### ISSUE THREAD

**Issue by luabud** [microsoft/debugpy#68]
## Environment data

- PTVSD version: debugpy 1.0.0b2
- OS and version: Windows-10-10.0.18362-SP0 AMD64
- Python version (& distribution if applicable, e.g. Anaconda): CPython 3.8.2 (64-bit), using **venv**
- Using VS Code or Visual Studio: VS Code Insiders (can also repro on VS Code stable 1.43)
- Python extension version - 2020.3.66963-dev

## Actual behavior

Attaching to local process times out and a message `Unable to find python module.` is printed by the application I'm trying to attach to.

## Steps to reproduce:
1. Have a Python file with:
```py
import time
while (1):
    print("hey!")
    time.sleep(2)
    
```

2. Open a terminal and run this file. Make sure to use a virtual environment. 

3. Open VS Code and select the "attach to local process configuration". Then run it.
This is what I get:
![image](https://user-images.githubusercontent.com/45497113/76266795-e562f080-6225-11ea-9324-7de8906fdbe0.png)

And then in the terminal where my script is running:

![image](https://user-images.githubusercontent.com/45497113/76266813-f449a300-6225-11ea-96a4-b5d2eb39749f.png)

[debugger.vscode_cf3469c0-77b2-465a-b070-3da2d2fbf108.log](https://github.com/microsoft/debugpy/files/4309538/debugger.vscode_cf3469c0-77b2-465a-b070-3da2d2fbf108.log)
[debugpy.adapter-25384.log](https://github.com/microsoft/debugpy/files/4309539/debugpy.adapter-25384.log)

**Comment by luabud** [comment]
FWIW I can't repro with global interpreter, just virtual environments.

**Comment by int19h** [comment]
On Windows, when you start the script, there should be two processes showing as python.exe in the picker - one with a path under "Scripts" in venv, which is a stub; and one from a global Python install from which that venv was created, which is what that stub spawns. If you attach to the second one, does it work?

**Comment by luabud** [comment]
It does! 😲

**Comment by int19h** [comment]
So, we need to either filter out those stubs in the picker, or automatically determine the PID of the actual process if we get PID of the stub. 

Need to investigate possible approaches to detecting them first. So far as I can tell, the only thing in the binary metadata that is different is "original filename" - for the stubs it's `py.exe`, and for the real thing it's `python.exe`.

**Comment by owillebo** [comment]
> On Windows, when you start the script, there should be two processes showing as python.exe in the picker - one with a path under "Scripts" in venv, which is a stub; and one from a global Python install from which that venv was created, which is what that stub spawns. If you attach to the second one, does it work?

I confirm this. However there is another issue on Windows.

If the virtual Python interpreter is selected things still don't work. You must select the base Python interpreter.
For instance you must select "C:\Program Files\Python39\python.exe" and not the "...\Scripts\python.exe" in the venv folder.

This can be fixed by changing the following code in src/debugpy/adapter/servers.py

```
def inject(pid, debugpy_args):
    host, port = listener.getsockname()

    cmdline = [
        sys.executable,
        os.path.dirname(debugpy.__file__),
        "--connect",
        host + ":" + str(port),
    ]
```

change sys.executable in to sys._base_executable

This way the correct Python interpreter is used.

**Comment by int19h** [comment]
That command line is to run the Python script that performs the injection into the process, so it shouldn't matter if there is a mismatch (IIRC except for bitness). 

What goes wrong for you if you use venv interpreter while attaching to the correct process?
