### ISSUE TITLE
Unhandled: on_setfunctionbreakpoints_request not available in PyDevJsonCommandProcessor.

### ISSUE THREAD

**Issue by Mossaka** [microsoft/debugpy#684]
## Environment data

- debugpy version: 1.2.1
- OS and version: Ubuntu 20.10
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.12
- Using VS Code or Visual Studio: vscode 1.58.2

## Actual behavior

I added the following code snippet to my source code. And then run VSCode debugger with the attach option. 
```python
import debugpy

debugpy.connect(("localhost", 5678))
debugpy.breakpoint()
```
```Json
{
    "name": "Python: Attach",
    "type": "python",
    "request": "attach",
    "justMyCode": false,
    "listen": {
        "host": "0.0.0.0",
        "port": 5678
    }
}
```
Then I ran this program in the terminal, and encountered the following message: 
Unhandled: on_setfunctionbreakpoints_request not available in PyDevJsonCommandProcessor.

The debugger was not trigger and the terminal is blocked. 

## Expected  behavior

I should trigger the break point and I could start debugging. 

## Steps to reproduce:
described above.

**Comment by karthiknadig** [comment]
You need to update `debugpy`. Function breakpoints are available in `1.4.0`, you are currently using `1.2.1`

**Comment by aatkinson** [comment]
I experienced this issue with 1.4.0 as well.
the issue is with the artifact in the PyPI feed or pip-installing from the PyPI feed.
The function is missing from `_vendored/pydevd/pydevd_bundle/pydevd_process_net_command_json.py`

installing the packaged directly from GitHub resolves the issue
eg. `pip install https://github.com/microsoft/debugpy/archive/refs/tags/v1.4.0.tar.gz`

**Comment by fabioz** [comment]
There's something odd there (so, you're probably not using that version).

You can see that the related commit: https://github.com/microsoft/debugpy/commit/d7970b80add095c87bc34835dbd840c4d3f04d97#diff-4c4418910414da8f38b5b7d848f5ac022e6eb8dfddfe502c733b1fdc993aed78 is tagged both in 1.4.0 and 1.4.1 (and downloading the sources for those tags I can see that `on_setfunctionbreakpoints_request` is indeed defined there).

So, it seems it's getting `debugpy` from a different place in your case. 

If you want help in determining what's happening, please include the logs for your run.

i.e.:

* Open VS Code
* Select the command Extensions: Open Extensions Folder
* Locate the Python extension directory, typically of the form `ms-python.python-2021.*.****`
* In that directory ensure you do not have any debug*.log files, if you do, please delete them
* Go back into VS Code and modify your launch.json to add the setting "logToFile": true, see below:

```
{
    "name": "Python: Current File (Integrated Terminal)",
    "type": "python",
    "request": "launch",
    "program": "${file}",
    "console": "integratedTerminal",
    "logToFile": true
}
```

* Start debugging
* When done, go back into the extension directory and upload the debug*.log files into this GitHub issue.

**Comment by aatkinson** [comment]
I realized that I was running different versions of debugpy on the code-editing remote, and the code-execution remote. after using the same version on both remotes, updated to 1.4.1, I can no longer reproduce the issue.
thanks @fabioz!
