### ISSUE TITLE
Don't show Locals for module-global frame

### ISSUE THREAD

**Issue by enkeyz** [microsoft/debugpy#686]
Was send here from: https://github.com/microsoft/vscode/issues/129770

## Environment data

-   VS Code version: 1.58.2
-   Extension version (available under the Extensions sidebar): 2021.7
-   OS and version: latest Manjaro Linux
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): None
-   Relevant/affected Python packages and their versions: None
-   Relevant/affected Python-related VS Code extensions and their versions: latest weekly Pylance
-   Value of the `python.languageServer` setting: pylance

[**NOTE**: If you suspect that your issue is related to the Microsoft Python Language Server (`python.languageServer: 'Microsoft'`), please download our new language server [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) from the VS Code marketplace to see if that fixes your issue]

## Expected behaviour

show debug values once

## Actual behaviour

show debug values twice
<img src="https://user-images.githubusercontent.com/17646853/127484962-6b9d7e87-d1eb-4ed5-8386-8286ab3347f0.png">

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Enable Debug: Inline values
2. start debugging

## Logs

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by int19h** [comment]
I think that from the UX perspective, having both `Globals` and `Locals` for module-global frames is redundant - we should hide `Locals` in that case.

**Comment by judej** [comment]
Thank you for the report. Given our current resources are working on the Python 3.12 debugger, we will not be fixing this issues in the pre Python 3.12 debugger.
