### ISSUE TITLE
"Couldn't spawn debuggee" with non-ASCII filename on Python 2.7

### ISSUE THREAD

**Issue by GabrielNorell** [microsoft/debugpy#69]
Issue Type: <b>Bug</b>

I tried running the debugger on a program. I then got an error message reading: "Couldn't spawn debuggee: 'ascii' codec can't encode character u/2013 in position 27: ordinal not in range(128)". What should I do?

Extension version: 2020.2.64397
VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) m3-7Y30 CPU @ 1.00GHz (4 x 1608)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.90GB (0.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by GabrielNorell** [comment]
Thanks

**Comment by int19h** [comment]
Could you share your launch.json configuration?

**Comment by GabrielNorell** [comment]
`{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal", 
        
        }
    ]
}`

**Comment by GabrielNorell** [comment]
`{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal", 
        }
    ]
}
`

**Comment by int19h** [comment]
Thanks! And what's the full name (including path) of the file that you're trying to run?

**Comment by GabrielNorell** [comment]
hej.py
is the file i tried debugging

**Comment by GabrielNorell** [comment]
`c:/Users/egabnor5/OneDrive û Jõmtlands Gymnasief÷rbund/Desktop/python/hej.py
PS C:\Users\egabnor5\OneDrive – Jämtlands Gymnasieförbund\Desktop\python>`
