### ISSUE TITLE
Debugging with `integratedTerminal` should escape parametrized test name (pytest)

### ISSUE THREAD

**Issue by mjpieters** [microsoft/debugpy#692]
## Environment data

-   VS Code version: 1.59
-   Extension version (available under the Extensions sidebar): v2021.8.1102490946
-   OS and version: macos Big Sur (11.5.1 (20G80))
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.0b4 (via pyenv)
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): pipenv
-   Relevant/affected Python packages and their versions: pytest 6.2.4
-   Relevant/affected Python-related VS Code extensions and their versions: Pylance, v2021.8.1-pre.1
-   Value of the `python.languageServer` setting: `Pylance`

## Expected behaviour

When debugging a pytest test that uses parametrization, I'd like to be able to debug a specific variant. I have a `launch.json` configuration with the following settings:

```json
            "type": "python",
            "request": "test",
            "console": "integratedTerminal",
            "justMyCode": false,
```

and the following sample test in `test_sample.py`:

```python
import pytest

@pytest.mark.parametrize("a", ("foo", "bar"))
@pytest.mark.parametrize("b", ("foo", "bar"))
def test_test(a, b):
    assert a == b
```

Together the setup looks like this:

<img width="1199" alt="image" src="https://user-images.githubusercontent.com/46775/128555960-80087383-7863-49dc-8f21-231202237142.png">

## Actual behaviour

Starting the test fails with a zsh error (sensitive paths replaced by `...`):

```
mj@rusalye vstest % source /.../.local/share/virtualenvs/vstest-S4vllSF4/bin/activate
(vstest) mj@rusalye vstest %  /usr/bin/env /.../.local/share/virtualenvs/vstest-S4vllSF4/bin/python /.../.vscode/extensions/ms-python.python-2021.8.1105858891/pythonFiles/lib/python/debugpy/launcher 56443 -- /.../.vscode/extensions/ms-python.python-2021.8.1105858891/pythonFiles/testlauncher.py /.../vstest pytest --override-ini junit_family=xunit1 --rootdir /.../vstest --junit-xml=/.../T/tmp-40221ObeiVCcGUFf4.xml ./test_sample.py::test_test[foo-bar] 
zsh: no matches found: ./test_sample.py::test_test[foo-bar]
```

The parametrized test reference (`./test_sample.py::test_test[foo-bar]`) is not escaped but contains metacharacters that have meaning for zsh. If the command-line there used quoting or `\` escapes for the test reference, zsh would not try to expand the `[...]` metasyntax. This may be specific to pytest.

The workaround is to use `internalConsole` instead of `integratedTerminal`.

**Comment by int19h** [comment]
Unfortunately, this is not something that we control. See https://github.com/microsoft/vscode/issues/93328 for the underlying issue.

**Comment by mjpieters** [comment]
Interesting. But I filed this issue because my working setup, unchanged for months, stopped working right after I had upgraded to the latest vscode and vscode-python release. Presumably something changed *there*, but this issue was transferred to debugpy instead.
