### ISSUE TITLE
VS-Code Python debugging - ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by AndreasLuckert** [microsoft/debugpy#693]
## Environment data

-   VS Code version: 1.59.0
-   Extension version (available under the Extensions sidebar): v2021.8.1105858891
-   OS and version: Windows 10 Pro, 20H2, 19042.1110
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.9 (pip), 
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Python 3.9.4 (pip)
-   Relevant/affected Python packages and their versions: XXX
-   Relevant/affected Python-related VS Code extensions and their versions: XXX
-   Value of the `python.languageServer` setting: "Pylance" (even though it mostly states 'This setting cannot be applied in this workspace. It will be applied when you open the containing workspace folder directly.')

## Expected behaviour

I wanted to debug my local `Python` code as usual in `VS-Code` on `Windows 10` via pressing `F5`. Now, most of the times it interrupts stating the error 'ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it'.
Last morning there was an update of VS-Code (current version 1.59.0), maybe the issue is related, even though the error appeared every once in a while beforehand.

The difference is that this time the error is persistent and doesn't magically go away after trying several times.

## Actual behaviour

Often it crashes with the following Traceback Error message:
```
$  /usr/bin/env 'DEBUGPY_LOG_DIR=c:\Users\username\.vscode\extensions\ms-python.python-2021.8.1105858891' c:\\Users\\username\\Projects\\project-venv\\Scripts\\python.exe c:\\Users\\username\\.vscode\\extensions\\ms-python.python-2021.8.1105858891\\pythonFiles\\lib\\python\\debugpy\\launcher 56721 -- c:\\Users\\username\\Projects\\project\\test_files\\prediction_performance_monitoring\\modified_app_for_docker_testing.py
    Traceback (most recent call last):
      File "C:\Users\username\.pyenv\pyenv-win\versions\3.8.9\lib\runpy.py", line 194, in _run_module_as_main
        return _run_code(code, main_globals, None,
      File "C:\Users\username\.pyenv\pyenv-win\versions\3.8.9\lib\runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "c:\Users\username\.vscode\extensions\ms-python.python-2021.8.1105858891\pythonFiles\lib\python\debugpy\launcher\__main__.py", line 97, in
    <module>
        main()
      File "c:\Users\username\.vscode\extensions\ms-python.python-2021.8.1105858891\pythonFiles\lib\python\debugpy\launcher\__main__.py", line 53, in
    main
        launcher.connect(host, port)
      File "c:\Users\username\.vscode\extensions\ms-python.python-2021.8.1105858891\pythonFiles\lib\python\debugpy\launcher/../..\debugpy\launcher\__init__.py", line 34, in connect
        sock.connect((host, port))
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
```

The `launch.json` debugging configuration for local file testing:

```
    {
        "version": "0.2.0",
        "configurations": [
            {
                "name": "Python: Current File (Integrated Terminal)",
                "type": "python",
                "request": "launch",
                "program": "${file}",
                "console": "integratedTerminal",
                "python": "C:\\Users\\andreas.luckert\\Projects\\project-venv\\Scripts\\python.exe",
                "redirectOutput": true,
                "justMyCode": false,
                "logToFile": true,
                "stopOnEntry": false,
            }
        ]
    }

```

More details on what I've looked up with no avail can be found [in my issue filed on StackOverFlow](https://stackoverflow.com/questions/68709411/vs-code-python-debugging-connectionrefusederror-winerror-10061-no-connectio).
As an aside, I was forwarded by the [general VS-Code GitHub](https://github.com/microsoft/vscode/issues/130478) to yours as they identified your Python-extension to be the cause of it.

## Steps to reproduce:

1. Start VS-Code, open a Python-file, press F5 to start local file-debugging
2. Wait a certain amount of time until the error **ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it** appears

**Comment by int19h** [comment]
Since you're already running with "logToFile" enabled, can you share the logs that debugpy had generated in `c:\Users\username\.vscode\extensions\ms-python.python-2021.8.110585889`?

**Comment by int19h** [comment]
Also, I believe this to be a dup of https://github.com/microsoft/debugpy/issues/693 - this one is on Windows, but it has the same stack trace and error, so it's probably the same thing. Can you share the logs on that other issue, so that it's all in one place?

**Comment by AndreasLuckert** [comment]
**UPDATE:**

Finally, I could resolve this persisting error. You can find the details in my [answer on StackOverFlow](https://stackoverflow.com/a/73280867/12298276). I hope this helps others who have been struggling with that issue as well.
