### ISSUE TITLE
Not print message to output window when press "F10" if set breakpoint with "Actions".

### ISSUE THREAD

**Issue by ttSpace** [microsoft/debugpy#705]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/130732648-9691352e-c781-4811-a518-dd7a0cfe672f.png)

**Steps to Reproduce**
1. Create a Python Application.
2. Input below code:
```
from math import cos, radians 
def make_dot_string(x): 
    rad = radians(x) 
    numspaces = int(20 * cos(radians(x)) + 20) 
    st = ' ' * numspaces + 'o' 
    return st 
def main(): 
    for i in range(0, 1800, 12): 
        s=make_dot_string(i) 
        print(s) 
main()
```
3. Set breakpoint "for"statement".
4. Right-click on the breakpoint then select "Actions",
i. Input "This is a test message!!!!!!" on "Show a message in the Output Window" field.
ii. Uncheck "Continue code execution".

![image](https://user-images.githubusercontent.com/82852072/130733710-b8cd9af1-64c2-47a1-bb20-737a422eb669.png)

5. Press "F5" to debug.
6. Press "F10" several times.

**Expected behavior**

It should print log message to output window when press "F10".

**Additional context and screenshots**

Not print log message to output window when press "F10".

![image](https://user-images.githubusercontent.com/82852072/130733987-ccdf7f4b-f8b3-439b-8739-2e53d13a8754.png)

Press "F10" or "F5" can create a message to log to the output window.

![image](https://user-images.githubusercontent.com/82852072/130735771-0dac3259-c6d5-4d80-a867-058ede8627ee.png)

**Comment by fabioz** [comment]
I'll take a look at this.

**Comment by linette-zyy** [comment]
@fabioz 
I found this issue is still reproduced on this environment.
![image](https://user-images.githubusercontent.com/59192491/165684246-f7634df5-9e21-4620-afff-ab82bf9b5f65.png)
I want to know which build fixed this issue.

**Comment by fabioz** [comment]
This is currently only fixed in the `main` branch (so, no release includes it yet).

@karthiknadig @int19h are there any plans here? / Are there any docs on how to use the version from the repo in Visual Studio?

**Comment by int19h** [comment]
I don't think we have any way to plug a different version of debugpy into VS short of physically replacing the files on disk. The path to it should be something like:

`C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\Extensions\Microsoft\Python\Core\debugpy`
