### ISSUE TITLE
Support pyside6 (without frame-eval mode)

### ISSUE THREAD

**Issue by liheyi360** [microsoft/debugpy#709]
I import pyside6 module to use Qt6 GUI lib.I can't debug QThread with breakpoints.
Maybe add "pyside6" choice for "qt" property?

**Comment by liheyi360** [comment]
And i still  encounter the situation like #303 issue about multiple process debug, vscode pop up notification like "Failed launch debug 
 for child process xxxx".
Sometimes, debugger can't acquire call stack info itself.
```python
import multiprocessing

def funcProcess(idx):
    return idx + 1

with multiprocessing.Pool() as myPool:
    ans = myPool.map(funcProcess, range(1000))
print(ans)

```

**Comment by int19h** [comment]
Can you please file a separate issue for "Failed launch debug" error? It would also help a lot if you can include a screenshot of your debug session, and debugpy logs produced after enabling `"logToFile": true` in your launch.json (they will be in the same folder where the extension is installed - you should see that in the terminal when you start debugging).

**Comment by liheyi360** [comment]
Okay, I have posted another issue. 
By the way,  pyside6 QThread debug problem is related to the "qt" property value support?

**Comment by fabioz** [comment]
`pyside6` is not really supported, so, the automatic usage of pyside for monkey-patching is really not detected, still, if you are using CPython and have the native extensions, the debugging should still work (i.e.: in frame-eval mode the monkey-patching needed to automatically attach to QThreads shouldn't really be needed).

To better diagnose this, can you provide a sample code where this issue happens as well as the logs?

To get the logs:

* Open VS Code
* Select the command Extensions: Open Extensions Folder
* Locate the Python extension directory, typically of the form `ms-python.python-2021.*.****`
* In that directory ensure you do not have any debug*.log files, if you do, please delete them
* Go back into VS Code and modify your launch.json to add the setting "logToFile": true, see below:

```
{
    "name": "Python: Current File (Integrated Terminal)",
    "type": "python",
    "request": "launch",
    "program": "${file}",
    "console": "integratedTerminal",
    "logToFile": true
}
```

* Start debugging
* When done, go back into the extension directory and upload the debug*.log files into this GitHub issue.

**Comment by int19h** [comment]
@fabioz, from the logs:
```json5
{"usingCython": false, "usingFrameEval": false}
```

**Comment by eyalk11** [comment]
Does it solves it https://github.com/fabioz/PyDev.Debugger/pull/237/commits ? 
I am having difficulties debugging a pyside6 app

**Comment by judej** [comment]
Thank you for the report. Given our current resources are working on the Python 3.12 debugger, we will not be fixing this issues in the pre Python 3.12 debugger.
