### ISSUE TITLE
debug python service subprocess within node application

### ISSUE THREAD

**Issue by kevinwang89** [microsoft/debugpy#713]
I have an electron application. I can debug the main and renderer processes using below debug config. 
```
"configurations":[
{
            "name": "Electron:main",
            "type": "node",
            "request": "launch",
            // "runtimeExecutable": "${workspaceRoot}/public/debug.cmd",
            // "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron",
            "windows": {
                "runtimeExecutable": "${workspaceRoot}/public/debug.cmd"
            },
            "runtimeArgs": [
                "${workspaceRoot}/public/electron.cjs",
                "--remote-debugging-port=9222"
            ],
            "webRoot": "${workspaceRoot}",
            "console": "integratedTerminal",
            "resolveSourceMapLocations": [
                "${workspaceFolder}/**",
                "!**/node_modules/**"
            ]
            // "preLaunchTask": "conda"
        },
        {
            "name": "Electron:renderer",
            "type": "pwa-chrome",
            "request": "attach",
            "port": 9222,
            "webRoot": "${workspaceFolder}",
            "timeout": 30000
        }
    ],
    "compounds": [
        {
            "name": "Electron: All",
            "configurations": [
                "Electron:main",
                "Electron:renderer"
            ]
        }
    ]
```

in the electron renderer process there is a python service subprocess. I wonder if I can make config to debug python service as well ?  maybe that will add too much complexity,  I just try to get an answer.

**Comment by int19h** [comment]
There are some ways you could arrange this, but all of them would require some manual wrangling.

You can use attach-to-PID to attach directly to the Python subprocess once it's running. However, this may not be feasible if it's spun up on-demand to run your code.

You can also use the debug server functionality from inside said Python code - `debugpy.listen()` or `debugpy.connect()`.

In principle, it should also be possible to author a VSCode extension that would observer Node.js debug sessions, and programmatically start an attach session for the Python subprocess once it knows it's there. But I don't think there's any generic way to detect subprocesses - you'd have to come up with something bespoke.

**Comment by kevinwang89** [comment]
@int19h thank you for the explanation,  I add a python config which listen to to certain port and in the python script use `debugpy.connect` to connect the port and it works.
```
"configurations": [
       {
            "name": "Python:service",
            "type": "python",
            "request": "attach",
            "listen": {
                "port": 9223
            },
            
       }
]

"compounds": [
        {
            "name": "Electron: All",
            "configurations": [
                "Electron:main",
                "Electron:renderer",
                "Python:service"
            ]
        }
    ]
```
