### ISSUE TITLE
vscode terminal output condensed - Python Debug Console

### ISSUE THREAD

**Issue by ikoyfman** [microsoft/debugpy#717]
## Environment data

-   VS Code version: 1.59.1
-   Extension version (available under the Extensions sidebar): **2021.8.1159798656**
-   OS and version: XXX
-   Python version (& distribution if applicable, e.g. Anaconda): **3.9.6**
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): **venv**
-   Relevant/affected Python packages and their versions: **django**
-   Relevant/affected Python-related VS Code extensions and their versions: Windows_NT x64 10.0.19042

## Expected behaviour

Terminal output should not be condensed.

## Actual behaviour

![image](https://user-images.githubusercontent.com/46546149/131908375-8fe3821e-e8dc-4a05-885a-1f931b76eb2d.png)

## Steps to reproduce:

1. create new project
2. Start venv folder
3. Add venv interpretor
4. djang-admin create new project
5. add run configuration for django
6. run debug

**Comment by fabioz** [comment]
Well, the debugger shouldn't really do any wrapping, so, this is probably related to something else.

My guess is that this is some terminal configuration.

If you use a different terminal (say, `cmd` instead of `powershell`), do you still have the same issue?

**Comment by fabioz** [comment]
Closing as there was no additional feedback (and the issue doesn't really seem to be an issue in `debugpy`).
