### ISSUE TITLE
Python extension sends "setPydevdSourceMap" when a ms-vscode.cpptools debugger is attached 

### ISSUE THREAD

**Issue by tjahn** [microsoft/debugpy#728]
Hello,

some time ago I started to experience a problme when debugging my C++ / Python project with VSCodes C++ debugger (sadly I do not know, when this problem arose). I already brought the bug up in microsoft/vscode-cpptools#8115  and microsoft/vscode-jupyter#7480, but both maintainers do not think that the bug is on their side.

## Description

VSCode interactive Python crashes when trying to run cells after attaching the ms-vscode.cpptools C++ debugger to the Python process.

I develop a Python extension in C++. For debugging I start my python script with vscode using the interactive cell mode, attach the C++ debugger from the ms-vscode.cpptools extension to the process and then start calling cells. This worked until some weeks ago (though I do not know which extension versions I used back then).

## Expected behaviour

I should be able to connect the C++ debugger from the microsoft/vscode-cpptools extension and use breakpoints etc in my C++ module, even when running it in the interactive Python process started by vscode.

## Actual behaviour 

As soon as the next interactive Python cell is run from vscode the interactive Python session crashes. The attached C++ debugger also crashes with the following message in VSCodes Debug Console:
```
Stopping due to fatal error: InvalidOperationException: No handler registered for request of type 'setPydevdSourceMap'!
```
I only found this message type in the microsoft/debugy repository and its predecessor.

## Steps to reproduce:

* Install the extensions ms-python.python and ms-vscode.cpptools.
* create a Python script
```python
# %% first run this cell to start the Python process and get its PID
import os
print(os.getpid())
# %% after attaching the debugger run this cell to trigger the error
print("test")
```
* execute the first cell of the Python script in vscode interactively
* attach you debugger to the printed pid using the following launch.json entry
        {
            "name": "(lldb) Attach Debugger",
            "type": "cppdbg",
            "request": "attach",
            "program": "/proc/${command:pickProcess}/exe",
            "processId": "${command:pickProcess}",
            "MIMode": "lldb",
        },
* try executing the second cell after the debugger attached

## Environment data

- VSCode 1.60.0 on MacOS Big Sur 11.5.2
- remote SSH server is an OpenSuse 15.2
- ms-python.python@v2021.9.1191016588
- ms-vscode.cpptools@v1.6.0.
- debugpy version: 1.4.3 (in the .vscode-server/extensions/ms-python.*/...... directory)

**Comment by int19h** [comment]
This is not a debugpy issue, since debugpy doesn't send this message - only receives and processes it. The bug is in the code that sends it.

I left a comment on the original issue in vscode-jupyter with more details.
