### ISSUE TITLE
Listen on any port

### ISSUE THREAD

**Issue by Timmmm** [microsoft/debugpy#729]
Would it be possible to make it so that you can tell `debugpy` to listen on *any* port and then return the port? This is to support multiple people debugging on the same machine which is pretty awkward otherwise.

**Comment by fabioz** [comment]
This is already supported by listening to port `0` (in which case it will find a suitable port to listen to).

i.e.: Something like:

```
import debugpy
ip, port = debugpy.listen(0)
print(f'debugpy listening to {ip}:{port}')
debugpy.wait_for_client()
```

**Comment by Timmmm** [comment]
Ah nice, thanks!
