### ISSUE TITLE
Debugging pytest test from test explorer fails if python.testing.cwd isn't '.'

### ISSUE THREAD

**Issue by olowo726** [microsoft/debugpy#734]
Applies to v2021.9.1246542782

Trying to debug a pytest by right-clicking in the test explorer. Setting python.testing.cwd to something else that '.' yields 

```
> ============================= test session starts ==============================
> platform linux -- Python 3.8.10, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
> rootdir: /home/xyz/abc
> collected 0 items
> 
> -------------- generated xml file: /tmp/tmp-34474uvEW8uWewLSb.xml --------------
> ============================ no tests ran in 0.00s =============================
> ERROR: file or directory not found: ./tools/whatever/test/test_scan_for_published_topics.py::test_radar_server_
```

If I set python.testing.cwd to something which doesn't exist it fails when trying to set cwd. So the cwd setting is applied but no accounted for later in the process. If I set python.testing.cwd='.' everything works fine.

**Comment by int19h** [comment]
debugpy will interpret cwd relative to the working directory of the adapter, so this also depends on where VSCode launches it. What is the directory that you see in the terminal pane where the `pytest ...` command is submitted?

**Comment by olowo726** [comment]
Nothing, the only output is a python Traceback in the debug console. Terminal, python output and python test output are empty.

**Comment by int19h** [comment]
Looking at the repro, I'm a bit confused - what was "cwd" set to in the example that fails? I thought that was `"cwd": "."` at first, but then realized that that actually worked for you.

**Comment by olowo726** [comment]
"." - works.
"a/non/existing/folder" - python stack trace when setting cwd fails
"a/existing/folder" - the error message in the first message in the thread.

Den tis 28 sep. 2021 kl 21:42 skrev Pavel Minaev ***@***.***>:

**Comment by karthiknadig** [comment]
@olowo726 This might be fixed in the insiders version of the extension. Can you give it a try: https://pvsc.blob.core.windows.net/extension-builds/ms-python-insiders.vsix

**Comment by olowo726** [comment]
Thanks, it worked! Is there a way to get a notification when this
comes through to the normal release?

Den ons 29 sep. 2021 kl 07:45 skrev Karthik Nadig ***@***.***
