### ISSUE TITLE
cannot debug imported code although justMyCode is set to false

### ISSUE THREAD

**Issue by vttrifonov** [microsoft/debugpy#736]
- debugpy version: 1.4.3
- OS and version: mac OS 10.15.7
- Python version (& distribution if applicable, e.g. Anaconda): python 3.7/conda
- Using VS Code or Visual Studio: vscode

I would like to debug into code from an imported library. I have set "justMyCode": false for the debug configuration in my launch.json. Here is the complete launch.json

{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "justMyCode": false
        }
    ]
}

The project has a conda environment setup in a subfolder 'env' which includes its own python3.7. The python script is at the top level of the project folder (a sibling of the 'env' subfolder, NOT inside of it). launch.json is within the '.vscode' subfolder (a sibling of 'env').

When I click 'step into' when over a call to an imported function it just steps over it. Also if I set up a break point within the code of an imported library (within the 'env' subfolder) the breakpoint does not get turned on and says that the file is filtered out and suggests using "justMyCode": false (which I did).

I turned on logging for the debugger (added "logToFile": true in the launch.json), but could not find where the log files are produced (as suggested by a different issue, I looked into ~/.vscode/extensions/ms-python.python-2021.9.1246542782 where the python extension and debugpy live).

**Comment by int19h** [comment]
How are you starting the debug session? That "logToFile" doesn't produce logs where the extension is installed would seem to imply that your debug configuration is not used at all. Are you trying to run tests, by chance?

**Comment by vttrifonov** [comment]
I start the debug from here

![Screen Shot 2021-09-27 at 11 22 51 AM](https://user-images.githubusercontent.com/12157034/134964433-f83d7e86-57b2-4c7c-be5b-2b867f632046.png)

I am not running any tests. Just a regular launch and debug.

I also suspected that the configuration in launch.json is not being used (e.g. no error is produced when I put intentionally garbage in the launch.json), but was not sure what is happening... If I change the name of the configuration or add another configuration, it does get updated in the VSCode interface, so it is not entirely overlooked. Also the debug session starts because the integrated terminal shows a 'source activate'/launcher sequence and then it stops at a breakpoint in my code.

I am new to VSCode, so do not have a time when this has worked for me. I updated the VSCode to the latest version (1.60.2), but this did not change anything. This does not seem to work on two different mac OS Catalina laptops.

Other than this, I do not have trouble with Python in VSCode.

**Comment by karthiknadig** [comment]
@vttrifonov You need to set `purpose: ["debug-in-terminal]`:

```js
{
// Use IntelliSense to learn about possible attributes.
// Hover to view descriptions of existing attributes.
// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
"version": "0.2.0",
"configurations": [
{
"name": "Python: Current File",
"type": "python",
"request": "launch",
"program": "${file}",
"console": "integratedTerminal",
"justMyCode": false,
"purpose": ["debug-in-terminal"]
}
]
}
```

**Comment by vttrifonov** [comment]
Great! This solved it.

Perhaps this should go into the documentation. I do not see this anywhere, including a google of 'vscode purpose debug-in-terminal' just now...

**Comment by vttrifonov** [comment]
Thanks
