### ISSUE TITLE
Regression compared to ptvsd: debugging python running in a bazel runtime sandbox causes duplicate tabs to open

### ISSUE THREAD

**Issue by koenlek** [microsoft/debugpy#743]
## Context

When using python in a bazel sandbox (`bazel run //python/target`), bazel symlinks the required files into a 'runfiles' sandbox. My approach to debugging is to run it under the debugger and make it wait for client to connect (formerly ptvsd, now I'm exploring switching to debugpy). 

Once attached, breakpoints trigger, but open a copy of the file at the sandbox path (with some visual quirks, such as that breakpoints don't visually sync between both copies, see screenshot). This pollutes tabs and makes debugging messy, especially when doing complex debugging sessions that involve many files.

![image](https://user-images.githubusercontent.com/6514289/136251480-00f639a2-be26-40a3-88e5-a2209e19c8c2.png)
This screenshot shows both the double tabs issue, as well as they breakpoints visually not synchronizing between both copies of the same file.

With `ptvsd`, there was a simple workaround for this issue, just add this to the launch.json debug config:

```json
"pathMappings": [
    {"localRoot": "${workspaceFolder}", "remoteRoot": "${workspaceFolder}"}
],
```

This seemingly no-op mapping effectively solved this issue, presumably because as part of the path mapping, it canonicalizes the path (like `os.path.realpath` in python, or `readlink -f` in bash for macos and linux) in the process, causing breakpoints to cleanly trigger in the original files.

You might as yourself: why not just do this:

```json
"pathMappings": [
    {"localRoot": "${workspaceFolder}", "remoteRoot": "<sandbox_path>"}
],
```

This isn't tractable for 2 reasons:
1. The bazel sandbox path has a random hash in it, so updating the path mapping accordingly for each workspace would be annoying
2. The bazel sandbox symlinks individual files and the sandbox doesn't share the same folder structure as the workspace, i.e. files might be in some folder structure in the workspace, but are symlinked into a different folder structure in the sandbox. This means we'd need many pathmappings to get this to work and those will vary from bazel target to target. This is not manually doable in practice (unless solved programmatically perhaps).

I'd like to switch from `ptvsd` to `debugpy`, as debugpy has significantly better multiprocess handling. But this issue is a major blocker. 

## Environment data

- debugpy version: 1.5.0
- OS and version: Ubuntu 18.04 (accessed via remote ssh plugin from MacOS)
- Python version (& distribution if applicable, e.g. Anaconda): 3.9 (from apt: python3.9)
- Using VS Code or Visual Studio: VS Code

## Actual behavior

* With `ptvsd` the pathmapping trick works to avoid opening sandbox copies of files.
* With `dedubpy` the pathmapping trick does not work to avoid opening sandbox copies of files.

## Expected  behavior

I'd expect both to work. Either through the pathmappings trick, or through some other way such as introducing a new that `canonicalizes` paths.

As I believe `debugpy` was forked from `ptvsd`, we could maybe compare code and see what tweak is needed to make the pathmappings trick work again. 

## Steps to reproduce:

I've created a small example environment in which this issue can easily be reproduced. Please open this folder as a workspace in vscode and follow the instructions in the readme. 

[debugpy_issue.zip](https://github.com/microsoft/debugpy/files/7296047/debugpy_issue.zip)

**Comment by koenlek** [comment]
@int19h, agreeing with all you said. Having that flag would be awesome. I'm not sure if it would better go in the launch.json debug config or as a flag to debugpy. Either would work fine for me.

**Comment by koenlek** [comment]
@fabioz, thanks, that's a useful pointer. It actually looks like the vendored pydevd already provides tooling to map things to their canonical path, see `def canonical_normalized_path` [here](https://github.com/microsoft/debugpy/blob/3edb9f022fc87859fe2501a0aa1492ea53cd85ed/src/debugpy/_vendored/pydevd/pydevd_file_utils.py#L361).

For someone with a bit more knowledge of `debugpy`, I imagine it could be pretty easy to inject this into the breakpoint triggering logic such that we canonicalize paths before sending them off to the VS Code frontend. We can then expose this with a `--canonicalize-paths` argument for `debugpy`.

**Comment by koenlek** [comment]
@judej, I noticed this was added to Dev 17.x milestone. Does this mean it's being considered for implementation? And if so, within what time frame? Would be great if this get's addressed!

**Comment by koenlek** [comment]
Bump on this request. This is a major quality of UX issue when using debugpy with bazel sandboxes, so would be great if someone can shed light on any (tentative) roadmap for this 🙏

**Comment by fabioz** [comment]
I'll start to take a look at this.

**Comment by fabioz** [comment]
@int19h what do you think should be the name of the flag?

I'm thinking about having an environment variable:

`PYDEVD_RESOLVE_SYMLINKS: true|false`

which may be overridden in specific launch configurations with a:

`resolveSymlinks: true|false`

property.

**Comment by int19h** [comment]
Sounds good to me!

**Comment by koenlek** [comment]
SGTM too!

**Comment by fabioz** [comment]
@koenlek As a note, the actual fix (without the work related to the options/env vars) is mostly a one-line change at: https://github.com/fabioz/debugpy/commit/a0783bb5112286b754718140ba0bdc035a86fab3#diff-82a2e0a4303124b25a3c6acce599deec12927c414ac18a226a3c6d8dc34384dcR405 (in the `pydevd_file_utils.py` file).

You can probably do that change locally to check if it works until a new release is done.

If you're running in the debugger you can do:

`import pydevd_file_utils` to know the location of that file

and then you can hardcode the change to do:

`os_path_abspath = os_path_real_path`

inside the `pydevd_file_utils._abs_and_canonical_path` function.

**Comment by koenlek** [comment]
Thanks for implementing this, @fabioz! When do you expect this to be released? Or can I use a pre-release to test it?

**Comment by koenlek** [comment]
@fabioz, I'm able to use this by setting the env var `PYDEVD_RESOLVE_SYMLINKS`, but it doesn't seem to be exposed as a setting in the vscode python extension (https://github.com/Microsoft/vscode-python) yet. Would it make sense to open a ticket there to expose this setting?
