### ISSUE TITLE
debugpy --pid flag fails to start the debug server in attached process

### ISSUE THREAD

**Issue by OEP** [microsoft/debugpy#762]
I noticed that VSCode times out when I try to debug a process by its pid. I thought it must be using the `debugpy --pid` flag to start the debug server, and noticed it was failing to call `dlopen()` and then `DoAttach()`.

```
$ python3 -m debugpy --listen 5678 --pid <pid>
...
stderr: b'No symbol "dlopen" in current context.\nNo symbol "DoAttach" in current context.\n'
```

When I run that on the shell, I see it runs the gdb command:

```
gdb --nw --nh --nx --pid 25601 --batch
  --init-eval-command='set auto-solib-add off'
  --eval-command='set scheduler-locking off'
  --eval-command='set architecture auto'
  --eval-command='sharedlibrary libdl'
  --eval-command='call (void*)dlopen("<home dir>/.local/lib/python3.6/site-packages/debugpy/_vendored/pydevd/pydevd_attach_to_process/attach_linux_amd64.so", 2)'
  --eval-command='sharedlibrary attach_linux_amd64'
  --eval-command='call (int)DoAttach(0, ...)
```

When I removed the

```
  --init-eval-command='set auto-solib-add off'
```

It seems to work fine. I think that was added by 2a2c371d98c310c7a539c6a41f448e0da9e68f37. So I can work around by downgrading before then.

```
python3 -m pip install --user debugpy==1.4.1
```

If I downgrade, the debugpy command works. I also replaced the version bundled in `ms-python.python` locally and it appear's to fix the IDE's "attach to pid" behavior for Python.

## Environment data

- debugpy version: 1.5.1
- OS and version: CentOS 7.9
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.6 (appears version agnostic)
- Using VS Code or Visual Studio: code 1.61.1
- GDB: 7.6

## Actual behavior

Exits with apparent error:

```
stderr: b'No symbol "dlopen" in current context.\nNo symbol "DoAttach" in current context.\n'
```

## Expected  behavior

Should start the debug server in the attached process.

## Steps to reproduce:

0. Start a Python process to debug and note the pid
1. `python3 -m debugpy --listen 5678 --pid <pid>`

**Comment by OEP** [comment]
It turns out I can get a local version of vscode to use this replacement gdb. I couldn't figure out how to get a Remote SSH enabled vscode to use it, and I didn't have much insight into how to debug it. There is probably a way, but I'm still a pretty new user for VSCode.

I did notice the output from when I removed `--init-eval-command='set auto-solib-add off'`:

```
Reading symbols from /lib64/libdl.so.2...(no debugging symbols found)...done.
Reading symbols from /lib64/libutil.so.1...(no debugging symbols found)...done.
Reading symbols from /lib64/libc.so.6...(no debugging symbols found)...done.
Reading symbols from /lib64/ld-linux-x86-64.so.2...(no debugging symbols found)...done.
Reading symbols from /lib64/libfreebl3.so...Reading symbols from /lib64/libfreebl3.so...(no debugging symbols found)...done.
```

I tried these one at a time until I could call `dlopen()` successfully. It turns out `sharedlibrary libfreebl3` was what I was missing, and in fact, all I needed. I have no idea what it has to do with `dlopen()` though.

```
$ /usr/bin/gdb --nw --nh --nx --pid 9832 --init-eval-command='set auto-solib-add off'
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-120.el7
...
(gdb) sharedlibrary libfreebl3
Reading symbols from /lib64/libfreebl3.so...Reading symbols from /lib64/libfreebl3.so...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libfreebl3.so
Missing separate debuginfos, use: debuginfo-install nss-softokn-freebl-3.53.1-6.el7_9.x86_64
(gdb) call (void*)dlopen("blah", 2)
$1 = (void *) 0x0
```

I'm not sure which of removing the `--init-eval-command` or explicitly loading `libfreebl3` is the lesser of two evils. It feels weird to do either, and a little too low-level to make gdb boot-up commands configurable.

I do like what @int19h suggests about a configurable gdb, even as a flag or something to debugpy. Normally I'd think the right gdb being on the PATH would be enough, but since I am having trouble getting the Remote SSH plugin working, having that as a safety net might be nice. I guess to ultimately be useful for my case, it'd have to be configurable somewhere in vscode too.

**Comment by OEP** [comment]
Just wanted to say installing a new gdb version to `/usr/local/bin/gdb` actually ended up being a total solve for me. I had a second unrelated issue involving a custom python build that I worked around.

The configurable gdb path may still be a good idea for other users without sudo privileges, but I think modifying `PATH` would work there. I'll leave the issue open in case that merits more discussion, but I consider this solved.

**Comment by fabioz** [comment]
I'm closing this since it's working for @OEP -- I think that the current status quo is reasonable... if it turns out that more people stumble upon this we can revisit.

**Comment by Anthogr** [comment]
Hi,

I'm posting here because it seems my issue looks close to what is discussed here

I'm trying to debug a web app running in several docker containers, (one for flask python library, one for panel python library, one for nginx...).

In order to do this I'm using the `Remote-Containers: Attach to a Running Container` option from the **Remote - Containers** extention for VS Code. Then I'm trying to Run and debug a python process using the following `launch.json` file:
```
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Attach using Process Id",
            "type": "python",
            "request": "attach",
            "processId": "${command:pickProcess}",
            "justMyCode": false,
            "logToFile": true
        }
    ]
}
```

But I get a "Timed out waiting for debug server to connect." window in VS Code.

I went through several errors (like a `ptrace: Operation not permitted`) before getting stuck on this:
```
 I+00000.247: Injector[PID=1] output:
             b'Running: gdb --nw --nh --nx --pid 1 --batch --init-eval-command=\'set auto-solib-add off\' --eval-command=\'set scheduler-locking off\' --eval-command=\'set architecture auto\' --eval-command=\'sharedlibrary libdl\' --eval-command=\'call (void*)dlopen("/root/.vscode-server/extensions/ms-python.python-2022.0.1814523869/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd_attach_to_process/attach_linux_amd64.so", 2)\' --eval-command=\'sharedlibrary attach_linux_amd64\' --eval-command=\'call (int)DoAttach(0, "import codecs;import json;import sys;decode = lambda s: codecs.utf_8_decode(bytearray(s))[0] if s is not None else None;script_dir = decode([47, 114, 111, 111, 116, 47, 46, 118, 115, 99, 111, 100, 101, 45, 115, 101, 114, 118, 101, 114, 47, 101, 120, 116, 101, 110, 115, 105, 111, 110, 115, 47, 109, 115, 45, 112, 121, 116, 104, 111, 110, 46, 112, 121, 116, 104, 111, 110, 45, 50, 48, 50, 50, 46, 48, 46, 49, 56, 49, 52, 53, 50, 51, 56, 54, 57, 47, 112, 121, 116, 104, 111, 110, 70, 105, 108, 101, 115, 47, 108, 105, 98, 47, 112, 121, 116, 104, 111, 110, 47, 100, 101, 98, 117, 103, 112, 121, 47, 46, 46, 47, 100, 101, 98, 117, 103, 112, 121, 47, 115, 101, 114, 118, 101, 114]);setup = json.loads(decode([123, 34, 109, 111, 100, 101, 34, 58, 32, 34, 99, 111, 110, 110, 101, 99, 116, 34, 44, 32, 34, 97, 100, 100, 114, 101, 115, 115, 34, 58, 32, 91, 34, 49, 50, 55, 46, 48, 46, 48, 46, 49, 34, 44, 32, 52, 53, 56, 49, 51, 93, 44, 32, 34, 119, 97, 105, 116, 95, 102, 111, 114, 95, 99, 108, 105, 101, 110, 116, 34, 58, 32, 102, 97, 108, 115, 101, 44, 32, 34, 108, 111, 103, 95, 116, 111, 34, 58, 32, 110, 117, 108, 108, 44, 32, 34, 97, 100, 97, 112, 116, 101, 114, 95, 97, 99, 99, 101, 115, 115, 95, 116, 111, 107, 101, 110, 34, 58, 32, 34, 51, 97, 51, 98, 50, 98, 99, 102, 97, 50, 102, 51, 52, 48, 98, 50, 51, 98, 57, 53, 57, 55, 49, 48, 52, 102, 53, 48, 53, 99, 100, 49, 48, 48, 99, 101, 57, 48, 54, 97, 55, 52, 97, 57, 100, 52, 98, 98, 52, 52, 49, 51, 50, 50, 98, 102, 99, 57, 100, 98, 50, 54, 51, 53, 34, 125]));sys.path.insert(0, script_dir);import attach_pid_injected;del sys.path[0];attach_pid_injected.attach(setup);", 0)\''

I+00000.247: Injector[PID=1] output:
             b'Running gdb in target process.'

I+00000.248: Injector[PID=1] output:
             b'stdout: b\'[New LWP 11]\\n[Thread debugging using libthread_db enabled]\\nUsing host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".\\n0x0000ffffb32471ac in ?? () from /lib/aarch64-linux-gnu/libc.so.6\\nThe target architecture is set to "auto" (currently "aarch64").\\n$1 = (void *) 0x0\\n[Inferior 1 (process 1) detached]\\n\''

I+00000.248: Injector[PID=1] output:
             b'stderr: b\'No symbol "DoAttach" in current context.\\n\''

I+00000.264: Injector[PID=1] exited.
```

Which looks similar to the issue in this post but I don't  understand how to deal with this.

Any help would be very appreciated !

Thanks a lot

## Environment Data

```
$ gdb --version
GNU gdb (Debian 10.1-1.7) 10.1.90.20210103-git
```
OS: Debian GNU/Linux 11 (bullseye)
debugpy: 1.5.1
Python: 3.8.12

**Comment by int19h** [comment]
If you're getting ptrace errors, I suspect it's because you're hitting https://askubuntu.com/questions/41629/after-upgrade-gdb-wont-attach-to-process/41656#41656 (same solution should work for Debian).

**Comment by Anthogr** [comment]
Sorry I misspoke about my issue. I solved the ptrace problem already but now I'm facing this `No symbol "DoAttach" in current context` error and I don't understand how to sort that out.

Could you help me please ?

**Comment by fabioz** [comment]
@Anthogr the fix is installing a new version of gdb and making sure that it`s used.

i.e.: from the original complain: 

```
Just wanted to say installing a new gdb version to /usr/local/bin/gdb actually ended up being a total solve for me. I had a second unrelated issue involving a custom python build that I worked around.
```

So, the fix is upgrading your gdb version and making sure that it's the one being used (changing the `PATH` is probably also an option...).

**Comment by OEP** [comment]
I upgraded to gdb 8.3 from 7.6, but it looks like @Anthogr is using a newer version (10.1) so it's possible it's a different issue altogether.

**Comment by Anthogr** [comment]
I only get one version of gdb available
```
$ apt list -a gdb
Listing... Done
gdb/stable 10.1-1.7 arm64
```

**Comment by fabioz** [comment]
@Anthogr sorry, I missed the line which showed you were on arm on the initial message. 

i.e.: the reason this isn't working for you is because we don't support `arm64` right now (we don't ship with the pre-built binaries for the `attach to` process to work), so, this falls under the open item we have to support arm (https://github.com/microsoft/debugpy/issues/286).
