### ISSUE TITLE
External terminal exits immediately at the end of program

### ISSUE THREAD

**Issue by shixiaobang** [microsoft/debugpy#768]
## Environment data

-   VS Code version: 1.50.1
-   Extension version (available under the Extensions sidebar): v2020.9.114305
-   OS and version: (ubuntu 20.04.1 LTS) Linux x64 5.4.0-52-generic
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Relevant/affected Python packages and their versions: N/A
-   Relevant/affected Python-related VS Code extensions and their versions: N/A
-   Value of the `python.languageServer` setting: Pylance

## Expected behaviour

Gnome-terminal won't exit until you close it.

## Actual behaviour

Gnome-terminal exits immediately after the program finishes running when Launch the debug targe in external terminal.

## Steps to reproduce:

1.Creat a python file

```python
print("Hello world!")

```

2.Creat launch.json

```json
{
    "configurations": [{
        "name": "Python: current file",
        "type": "python",
        "request": "launch",
        "program": "${file}",
        "console": "externalTerminal"
    }]
}
```

3.Run the code

The terminal exits immediately after displaying "Hello world!".

**Comment by RickDW** [comment]
I've just run into this problem so it's still an issue. I'm not sure what's causing it, but it seems to be related to some project settings. It's a problem in an old vs code project folder and not in a new project folder that I just created.
The old project has the exact same problem with launching julia code. The terminal will launch and the script will run, but the terminal closes as soon as it's done taking all of the script's output with it. Hopefully this help someone in tracking this issue down.

**Comment by RickDW** [comment]
What's especially weird is that the workspace settings are exactly equal for both projects. The 'global' settings.json file contains this: 

{
    "telemetry.enableTelemetry": false,
    "workbench.startupEditor": "none",
    "files.autoSave": "afterDelay",
    "C_Cpp.default.systemIncludePath": [],
    "workbench.editorAssociations": {
        "*.ipynb": "jupyter-notebook"
    },
    "notebook.cellToolbarLocation": {
        "default": "right",
        "jupyter-notebook": "left"
    },
    "git.confirmSync": false,
    "keyboard.dispatch": "keyCode",
    "explorer.confirmDragAndDrop": false,
    "latex-workshop.view.pdf.viewer": "tab",
    "editor.suggest.snippetsPreventQuickSuggestions": false,
    "editor.smoothScrolling": true,
    "terminal.integrated.commandsToSkipShell": [
        "language-julia.interrupt"
    ],
    "julia.symbolCacheDownload": true,
    "julia.enableTelemetry": false,
    "workbench.colorTheme": "GitHub Dark Dimmed"
}

**Comment by int19h** [comment]
@RickDW How does launch.json look?

**Comment by int19h** [comment]
Please re-open if the issue still occurs.

**Comment by kpierce8** [comment]
I still can't figure out how to see my output in the external window on Ubuntu. I run a short script, it prints out the output and immediately closes the external terminal

**Comment by int19h** [comment]
Are you setting `"waitOnNormalExit": true`?

**Comment by kpierce8** [comment]
> Are you setting `"waitOnNormalExit": true`?

I tried but it doesn't recognize it. I think this might be a problem on Ubuntu only. Thanks for the suggestion.

**Comment by int19h** [comment]
Note that if your app exits with a non-zero exit code, then you will need "waitOnAbnormalExit".

**Comment by Muhand** [comment]
I can report the same issue on window. It exits immediately.

This is my launch.json

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            // Use IntelliSense to find out which attributes exist for C# debugging
            // Use hover for the description of the existing attributes
            // For further information visit https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md
            "name": ".NET Core Launch (console)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            // If you have changed target frameworks, make sure to update the program path.
            "program": "${workspaceFolder}/src/bin/Debug/net7.0/test-proj.dll",
            "args": [],
            "cwd": "${workspaceFolder}/src",
            // For more information about the 'console' field, see https://aka.ms/VSCode-CS-LaunchJson-Console
            "console": "externalTerminal",
            "stopAtEntry": false,
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach"
        }
    ]
}
```

**Comment by realKarthikNair** [comment]
Facing same issue herer
