### ISSUE TITLE
Cell-debugging in VSCode-Remote causes error "Canceled" "Source: Jupyter (Extension)" on second try

### ISSUE THREAD

**Issue by flixha** [microsoft/debugpy#776]
## Environment data

- debugpy version: 1.4.1
- OS and version: Remote: RHEL 8.4, User: MacOS 10.13.6
- Python version (& distribution if applicable, e.g. Anaconda): python 3.8.3 via miniconda
- Using VS Code or Visual Studio: VSCode 1.61.2, commit 6cba118ac49a1b88332f312a8f67186f7f3c1643 with Remote Extension

## Actual behavior
"Debug cell" only works on its first invocation, afterwards it causes the error "Canceled Source: Jupyter (Extension)" which requires a full restart of VSCode to make debugging work again.

A smaller (not sure if related) issue is that the debugger marks the "wrong" line in yellow when it is first started; it marks a line in the import-cell rather than in the debugging-cell.

## Expected  behavior
No "Canceled"-error. (debugging generally worked in previous versions, but I cannot say when it last worked).

## Steps to reproduce:
See screen-capture below, summarized, the following workflow causes the debugger to crash with "Canceled  Source: Jupyter (Extension)", which then requires a full restart of VSCode to continue with debugging:
1. Run a cell with a package import
2. Set a breakpoint and debug a cell. Complete cell-debugging with "continue" or abort debug with Stop/Disconnect. No problem on the first try.
3. Try the same as in 2 again. Now the debugger remains in a state where user can only press "Pause" or "Stop". Both cause this error to appear: "Canceled  Source: Jupyter (Extension)". Debugging stops working until VSCode is restarted.

https://user-images.githubusercontent.com/16126887/139912881-e5a935a5-5bca-4922-84bd-453a8bbfb274.mov

**Comment by int19h** [comment]
@DonJayamanne I'm not familiar with this "canceled source" message - I'm assuming this is something from vscode-jupyter debugger integration?

**Comment by DonJayamanne** [comment]
@int19h Apologies for not getting back to you on this. I think this might be a problem at our end, could be us thrown a `Cancellation` error and the error message is just `Cancelled`, which then ends up getting displayed by VS Code.

I've tested this against the latest version of VS Code and I'm unable to repro this, possible this is a bug in the previous version of the extension. 

@flixha Please could you update the latest versions of VS Code and the Jupyter extension and test this out.

**Comment by fabioz** [comment]
I'm closing this as it doesn't seem reproducible and there wasn't additional feedback.

@flixha please reopen if you're still able to reproduce in the latest version.
