### ISSUE TITLE
Debugger exits when debugging unit test and encounters exception

### ISSUE THREAD

**Issue by astrowonk** [microsoft/debugpy#780]
Issue Type: <b>Bug</b>

The debugger is very useful in diagnosing unit tests, but something happened where the debugging session is now ending if a unit test encounters an error, making it impossible to interogate variables, etc. that may have caused the crash.

The debugger does not exit if the same error is encountered in a regular "debug python file" session.

I have  made a simple repo. Debuging the one unit test and the debugger exits. Debug the python file directly and the debugger does not.

Not sure if this is upstream or part of the python extension?

Extension version: 2021.12.1441722766-dev
VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:53:36.800Z)
OS version: Darwin arm64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|16.00GB (0.54GB free)|
|Process Argv|--crash-reporter-id 68686b81-af00-4876-bfbb-a517c41c7bb9|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200cf:30386380
vsaa593cf:30376535
vssld246:30386377

```

</details>

Screenshot of debugger tools persisting after normal file debugging:
<img width="1076" alt="Screen Shot 2021-11-11 at 8 05 43 PM" src="https://user-images.githubusercontent.com/13702392/141391690-c41e03c7-328e-4c72-97cb-0062935b2f05.png">

Video of the debugger exiting when unit testing the same function:

https://user-images.githubusercontent.com/13702392/141391736-61402277-3039-417d-b30f-2fe653a180ad.mov

**Comment by fabioz** [comment]
@astrowonk can you provide the logs when that happens to you?

i.e.:

* Open VS Code
* Select the command Extensions: Open Extensions Folder
* Locate the Python extension directory, typically of the form `ms-python.python-2021.*.****`
* In that directory ensure you do not have any debug*.log files, if you do, please delete them
* Go back into VS Code and modify your launch.json to add the setting "logToFile": true for the `"request": "test"` -- see below:

```
{
    "name": "Debug Tests",
    "type": "python",
    "request": "test",
    "console": "integratedTerminal",
    "logToFile": true,
    "justMyCode": false
}
```

* Start debugging
* When done, go back into the extension directory and upload the debug*.log files into this GitHub issue.

**Comment by astrowonk** [comment]
Ok, so when I make a new entry for the launch.json, suddenly the behavior changes and the debugger does stop, only not where I would expected it. I had no idea there was any seperate configuration of the debugger in `launch.json` for unit tests, I have only ever made the `launch.json` with defaults for "python: current file." except for changing the output to the console.

Anyway, with an entry the debugger does stop, without it, it does not. Here's the screenshot with a "request: test"  configuration entry as you posted:

<img width="1180" alt="Screen Shot 2021-11-15 at 8 44 49 AM" src="https://user-images.githubusercontent.com/13702392/141792257-7e64878b-886e-4cfb-b287-648963bb0f97.png">

And the logs:
[debugger.vscode_50806796-0e92-4d9a-a552-80c3ce5c8ec3.log](https://github.com/microsoft/debugpy/files/7539111/debugger.vscode_50806796-0e92-4d9a-a552-80c3ce5c8ec3.log)
[debugpy.adapter-65005.log](https://github.com/microsoft/debugpy/files/7539112/debugpy.adapter-65005.log)
[debugpy.launcher-65008.log](https://github.com/microsoft/debugpy/files/7539113/debugpy.launcher-65008.log)
[debugpy.pydevd.65011.log](https://github.com/microsoft/debugpy/files/7539114/debugpy.pydevd.65011.log)
[debugpy.server-65011.log](https://github.com/microsoft/debugpy/files/7539115/debugpy.server-65011.log)

**Comment by int19h** [comment]
Judging by the screenshots, the difference that you're seeing is that between an exception being unhandled, and it being handled by your test framework (which logs it to output).

This should be controlled by the "User Uncaught Exceptions" checkbox in Breakpoints - if it's unset, try setting it.

**Comment by astrowonk** [comment]
@int19h Welp, I guess this is a behavior change because I don't remember when "User Uncaught Exceptions" was even added to the debugger pane? I thought I tried it last week and it was catching exceptions I didn't want it to, but it definitely solves the issue in my example repo. If I see other odd behavior with it, I'll open another issue. Thanks!
