### ISSUE TITLE
Debugger attempts to debug MicroPython subprocesses

### ISSUE THREAD

**Issue by Josverl** [microsoft/debugpy#781]
Issue Type: <b>Bug</b>

- create two tests 
    [tests/test_101.py][] just as a sanity check
    [tests/test_spr.py][] using subprocess.run to run a linux process  

## Expected : 
 [ ] pytest to run both tests successfully 
 [ ] vscode python testing to run both tests successfully 
 [ ] vscode to be able to debug  both tests successfully 
 
## Actual 
 [x] pytest to run both tests successfully 
 [x] vscode python testing to run both tests successfully  
    [x] tests/test_101.py
    [x] tests/test_spr.py

 [ ] vscode to be able to debug  both tests successfully 
    [x] tests/test_101.py
    [ ] **tests/test_spr.py** subprocess.run Fails while debugging with the below error:  

```
Traceback (most recent call last):
  File "/home/jos/.vscode-server/extensions/ms-python.python-2021.11.1422169775/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 24, in <module>
  File "/home/jos/.vscode-server/extensions/ms-python.python-2021.11.1422169775/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_constants.py", line 4, in <module>
ImportError: no module named \'__future__\'\
```
**Full repro in repo : https://github.com/Josverl/pytest_subprocess_run**

Extension version: 2021.11.1422169775
VS Code version: Code 1.62.1 (f4af3cbf5a99787542e2a30fe1fd37cd644cc31f, 2021-11-05T10:57:55.946Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (6.20GB free)|
|Process Argv|--crash-reporter-id ede7f3a0-1b74-4e0a-8927-2f38c66cb4a5|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2111)|
|Memory (System)|7.73GB (5.83GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2111)|
|Memory (System)|7.73GB (5.83GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vshan820:30294714
vscod805cf:30301675
vsccppwt:30393681
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534

```

</details>

**Comment by fabioz** [comment]
This is really strange... which Python version are you using?

That line in `pydevd_constants.py` should read: `from __future__ import nested_scopes` and that should work (maybe that's not needed anymore for any recent version of Python, but it should also definitely not crash anywhere).

Also, I find it strange that your error says:

`ImportError: no module named \'__future__\'\`

when it should actually say:

`ImportError: no module named __future__`

Those quotes around `__future__` seem really suspicious (definitely not something I would expect), but maybe your environment is somehow customized... if you just remove the `from __future__ import nested_scopes` from `pydevd_constants.py`, do you have a different error afterwards?

**Comment by Josverl** [comment]
sorry that i left that out : 
Windows : ./.venv
```
home = C:\Users\josverl\AppData\Local\Programs\Python\Python39
include-system-site-packages = false
version = 3.9.7
```
Python 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]

Linux: ./.venv-ub
```
home = /usr/bin
include-system-site-packages = false
version = 3.8.10
```
Python 3.8.10 (default, Sep 28 2021, 16:10:42)
[GCC 9.3.0]

**Comment by Josverl** [comment]
also I have done no customization that I am aware of, and I run into the same sort of issues when I use codespaces rather than my own WSL2-Ubunto 20.04 .
I can try to extend the repro to codespaces. then it's not just 'on my machine'

**Comment by int19h** [comment]
The error message comes from the subprocess. This is also why single quotes are themselves quoted: the exception is raised like so:
```py
assert subproc.returncode == 0, "createstubs ran with an error :" + str(subproc.stderr)
```
However, `subproc.stderr` is a `bytes` object, not a string, so `str()` on it is equivalent to `repr()` - i.e. `b'...'`. If you look closely at the screenshot, you can spot the `b` prefix in the output:
![image](https://user-images.githubusercontent.com/1175142/141848046-07bc85b5-3841-414a-8a21-d8dfa415def9.png)
So it really was reporting a failure to import `__future__`. And that's because the subprocesses here are running under MicroPython, which doesn't have it:
```py
cmd = [
        os.path.abspath("tests/tools/micropython_v1_16"),
        "main.py",
    ]
```
Now, pydevd and debugpy do not support MicroPython (and I don't think we ever will - there's too much functionality missing there to port our existing code). So the proper behavior would be for the subprocess to not have pydevd running in it at all. However, it looks like it still gets pydevd injected into it - that would be the bug here.

The workaround is to use `"subProcess": false` in your launch.json test config to disable subprocess debugger injection.

**Comment by Josverl** [comment]
Actually the goal is not to debug the MicroPython code; 
The goal was to **start** a linux executable using subprocess.run ( and yes , that is indeed a MicroPython executable ) 
( sorry for the Meta here, as im actually working on several projects to allow vscode / pylance to provide better support for Micropython through typeshed stubs) 

I added some more test to the pattern : 
- `cmd = [  exe.absolute().as_posix(),  "main.py",]`
   this is the original pattern
  - run OK 
  - debug Fails with 'ImportError: no module named \'__future__\'

additions: 
- `cmd = ["node", "--version"]`
  - run OK 
  - debug OK

- `cmd = [  exe.absolute().as_posix(),   "-X", "compile-only","main.py",]`
  - run OK 
  - debug OK

So it appears that the MicroPython ( for linux) runtime somehow detects that the python debugger is activ, and that this causes 
I did not expect that to be honest, and am not sure how to verify that theory 

I took a (very brief) look at debugpy, and the one thing that catches my eye is that it can be configured to ignore subprocesses 
https://github.com/microsoft/debugpy/#ignoring-subprocesses

Or perhaps debugpy sets environment variables that get picked-up by micropython ?

There only a few variables that [micropython reads , documented](https://docs.micropython.org/en/latest/unix/quickref.html?highlight=debug#environment-variables), and I would not expect these to get set by debugpy.

But if i know what to look for then I could perhaps clear these to allow me to debug subsequent steps in the test

**Comment by int19h** [comment]
`"subProcess": false` in debug configuration is the supported way to make debugpy ignore subprocesses.

I don't think this is a MicroPython issue - it cannot really "detect" the debugger in the parent process. However, on the debugger side, we have code that, when subprocess debugging is enabled, tries to detect spawned subprocesses, and if they appear to be Python, edits the command line used to spawn them to inject the debugger before any user code runs. So this is most likely what's happening here with the MicroPython subprocess. The debugpy bug, then, is that MicroPython subprocesses are treated as regular Python subprocesses, even though we can't actually debug them.

**Comment by int19h** [comment]
So we basically assume that it's Python if the binary name for the subprocess contains "python" (among other things):
https://github.com/microsoft/debugpy/blob/f139ed7a67bce75c7380de1cb27e02666b48f64a/src/debugpy/_vendored/pydevd/_pydev_bundle/pydev_monkey.py#L257-L267
https://github.com/microsoft/debugpy/blob/f139ed7a67bce75c7380de1cb27e02666b48f64a/src/debugpy/_vendored/pydevd/_pydev_bundle/pydev_monkey.py#L378-L380
A whitelist isn't viable here, unfortunately, since there are so many possible variations on the Python binary name. We'll probably have to specifically exclude MicroPython, CircuitPython etc. 

OTOH it means that if you rename your MicroPython binary, or symlink to it, it should work.

**Comment by Josverl** [comment]
just to circle back : setting `"subProcess": false` in the debug configuration works well and allows me to debug my CPython code .

it would be very cool if that could debug MicroPython, but trust you when you say that this is not possible.

**Comment by int19h** [comment]
It's possible in principle, since MicroPython has the requisite `sys.settrace()` API these days. But it's missing many of the Python standard library modules, including stuff that we rely on, and internals (that we sometimes need to fiddle with) are also drastically different. So a DAP-based debugger for it is certainly feasible, but it would likely have to be implemented from scratch.

**Comment by fabioz** [comment]
@int19h @karthiknadig do you think we should do something in this issue or is the status quo reasonable right now?

**Comment by int19h** [comment]
I think we're good for now. If there are more similar issues, we might consider adding an exclusion list.

**Comment by hmaerki** [comment]
@Josverl
Hi Jos. I use vscode to implement octoprobe and and stumbled over the same problem as I run the `tests/run-tests.py` from the micropython repo.

I did not want to set `"subProcess": false` as @int19h mentioned as I and other will forget to do so.

@int19h pointed at `def is_python(path): ` which then will end up in monkey patching the python subprocess.

I now wrote a function to 'un monkey patch' which prevents the subprocess to be started in the debugger.:

```python
def un_monkey_patch():
    """
    Prevent vstudio by debugging subprocesses.
    This will be applied for ALL SUBSEQUENT subprocesses!

    This is done by reverting the mocks
    from https://github.com/microsoft/debugpy/blob/main/src/debugpy/_vendored/pydevd/_pydev_bundle/pydev_monkey.py.
    """
    for module_name in ("os", "_posixsubprocess", "subprocess", "_subprocess"):
        try:
            module = __import__(module_name)
        except ModuleNotFoundError:
            continue
        prefix_original = "original_"
        for function_name_mock in module.__dict__.keys():
            if not function_name_mock.startswith(prefix_original):
                continue
            function_name = function_name_mock[len(prefix_original) :]
            setattr(module, function_name, getattr(module, function_name_mock))
```

This is now part of octoprobe: https://github.com/octoprobe/octoprobe/blob/main/src/octoprobe/util_vscode_un_monkey_patch.py

@int19h: Pavel, could above code be added by debugpy. So I just could call it and would not have to maintain it.

Another solution could be an environment variable `DEBUGPY_PREVENT_SUBPROCESS_DEBUG` set by the parent. The monkey patched functions would then would fallback to the 'original_' functions.

**Comment by int19h** [comment]
Note that I'm not a debugpy maintainer anymore. That said, it does look like it could be a useful addition to debugpy API. It already has `debugpy.configure(subProcess=false)`, but that only applies when set before calling `listen()` or `attach()`. It could be made to work afterwards using this technique, and then the API would be consistent with current usage. I would suggest filing an issue for this.

**Comment by stinos** [comment]
@hmaerki did you create a separate issue for this somewhere where this can be dicussed? Just ran into this again. I'm fine with using `"subProcess": false` as workaround but it took me a while to figure out this was the problem. The key was modifying pydevd.py to have that 'The PyDev.Debugger requires Python 3.6 onwards to be run' message also print the complete `sys.version` string which immediately made it clear MicroPython was being used to run pydevd. Seems like a worthy addition.

**Comment by hmaerki** [comment]
> [@hmaerki](https://github.com/hmaerki) did you create a separate issue for this somewhere where this can be dicussed?

I did not create a separate issue as `"subProcess": false` works fine for me.

And I also appreciate a solution like https://github.com/microsoft/debugpy/issues/781#issuecomment-2320050875
