### ISSUE TITLE
use vscode to remote debug python program with tmux session 

### ISSUE THREAD

**Issue by bizerfr** [microsoft/debugpy#783]
### VS Code version

1.62.2

### Extension version

remote-ssh v0.66.1

### OS type

Linux

### OS version

local: ubuntu 20.04;  remote:  CentOS 6.6 (x86_64) / VMware Virtual Platform

### Python distribution

Anaconda

### Python version

python3.8

### Language server

Default

### Expected behaviour

I use vscode to connect to a remote server. I create a tmux session in the remote server before. In order to let the vscode connect to the tmux session on server, I add a "terminal.integrated.automationShell.linux": "/home/tmux-nef-shell/tmux-sess.sh" in the vscode file of "settings.json", where "tmux-nef.sh" is the command to launch the existed tmux session "tmux attach -t sess".

vscode terminal can connect to the remote tmux session. there is no problem at this stage;

But I cannot use the python debugger. It says "ConnectionRefusedError: [Errno 111] Connection refused"

### Actual behaviour

I cannot use the python debugger. It says "ConnectionRefusedError: [Errno 111] Connection refused"

### Steps to reproduce

1. create a tmux session "tmux new -s sess" in the remote machine
2. write a shell file  "tmux-nef.sh" with "tmux attach -t sess"; and save "tmux-nef.sh" in the folder "/home/tmux-nef-shell/“
3. open vscode's "settings.json";
4. write  "terminal.integrated.automationShell.linux": "/home/tmux-nef-shell/tmux-sess.sh"
5. use vscode to debug a python programe

### Logs

Traceback (most recent call last):
File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
"main", mod_spec)
File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/home/ddz/.vscode-server/extensions/ms-python.python-2021.10.1336267007/pythonFiles/lib/python/debugpy/launcher/main.py", line 97, in main()
File "/home/ddz/.vscode-server/extensions/ms-python.python-2021.10.1336267007/pythonFiles/lib/python/debugpy/launcher/main.py", line 53, in main launcher.connect(host, port)
File "/home/ddz/.vscode-server/extensions/ms-python.python-2021.10.1336267007/pythonFiles/lib/python/debugpy/launcher/../../debugpy/launcher/init.py", line 34, in connect
sock.connect((host, port))
ConnectionRefusedError: [Errno 111] Connection refused

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by int19h** [comment]
The debugger expects the command that it submits to the terminal to launch the debuggee (i.e. the stuff that has `.../debugpy/launcher` in it) to run locally. There are several processes in a debug session, and they communicate via sockets - if you introduce a network boundary that the debugger is not aware of, things break.

This can be made to work, but your remoting script will have to be launcher-aware, and do whatever additional work is necessary to fix up the address/port argument that the launcher receives (normally it's just the port number, but you can use `address:port` there). If the machine on which you're running VSCode is not directly accessible from the machine that you're trying to debug, you'll need to set up port tunneling.

(If you go down this route, note that we don't consider the launcher command line to be public API, so it may change in future versions.)

It might be easier to use remote attach here. Basically just run your tmux session in a separate terminal and launch your script there manually with `debugpy --wait-for-client ...`, and set up an attach config in VSCode to connect to that.

**Comment by bizerfr** [comment]
thank you for your reply; could you please give more details on how to use remote attach. I do not know how to use "debugpy --wait-for-client ..." and how to set up an attach config in vscode. thanks

**Comment by int19h** [comment]
These doc pages should cover it:

https://github.com/microsoft/debugpy/wiki/Command-Line-Reference 
https://code.visualstudio.com/docs/python/debugging#_command-line-debugging

Please let me know if there's anything missing there.

**Comment by bizerfr** [comment]
hello,
I have a question here. Currently, I can debug the program from the remote machine under tmux session because I mount the remote folder on my local machine. I found when I ssh into remote folder using vscode, the vscode can direct to the link to the mounted folder. But the thing is that the debugger is local, not remote. Can I use switch to remote debugger ?

**Comment by bizerfr** [comment]
thank you for the docs

I tried:
1. open a ubuntu terminal, and ssh into remote machine
2. on remote machine, tmux attach to my sessions
3. on remote machine,  python -m debugpy --listen 5678 --wait-for-client ./test-remote.py
4. open vscode on my local machine, and ssh into remote folder
5. modify launching.json, like this:
 {
    "configurations": [
    {
      //"console": "externalConsole",
      "name": "Attach",
      "type": "python",
      "request": "attach",
      "connect": 
      {
        "host": "cluster", 
        "port": 5678
      },
    }
  ]
  } replace this with remote machine name

6. press F5

But I got: connect ECONNREFUSED 192.xx.xxx.xx:5678

**Comment by int19h** [comment]
When you use `--listen` with just the port number, it listens to 127.0.0.1, so you can't connect to it from another machine (to avoid security issues - keep in mind that debugpy endpoint can be used to execute arbitrary code!). You need to use `--listen 0.0.0.0:5678` to make it listen on all interfaces.

**Comment by bizerfr** [comment]
I tried 0.0.0.0:5678; it still didn't work. 
![image](https://user-images.githubusercontent.com/16448481/145071763-8e06d666-a94e-484c-893e-2f5d5e7f2746.png)


I forgot to mention: my remote machine is a gpu cluster. In order to use GPU, I need to apply for it.
So, when I first connect to the cluster, and attach to the tmux sessions; I can do remote debug with vscode.
But when I applied for a gpu, I cannot do remote deug; it will get "connection refused" that I put it here

**Comment by nvip12041994** [comment]
Did you already resolve this problem? I have the same problem as you.

**Comment by int19h** [comment]
If the port is still inaccessible despite listening on it on all interfaces, it would generally indicate that the machine in question is locked down from outside connections. If that is the case, and you're unable to ask the admins to open ports for you, the only thing I can think of is to try using SSH tunneling:

https://github.com/microsoft/debugpy/wiki/Debugging-over-SSH
