### ISSUE TITLE
Support stopping in a lambda function in tensorflow Dataset map function

### ISSUE THREAD

**Issue by afcruzs** [microsoft/debugpy#784]
### VS Code version

1.62.2

### Extension version

v2021.11.1422169775

### OS type

Windows

### OS version

21h2 (build 22000.318)

### Python distribution

Anaconda

### Python version

3.9.7

### Language server

Pylance

### Expected behaviour

The debugger should stop on a lambda function passed to tensorflow's `Dataset` map function. IT seems this happens because tf underneath autogenerates graph code into a separate file.

### Actual behaviour

The debugger ignores this breakpoint and just doesn't stop there. Using plain `set_trace` does stop the execution, which shows it's being executed on a separate file.

This happens in both pylance and jedi

### Steps to reproduce

```
import tensorflow as tf
from tensorflow.keras import datasets


def normalize_image(image, label):
    print("HEREE") # Breakpoint is set here, should work as if we do pdb.set_trace()
    return tf.cast(image, tf.float32) / 255., label

(x_train, y_train), (x_test, y_test) = datasets.cifar10.load_data()
train_dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train))
train_dataset = train_dataset.map(normalize_image)

for step, batch in enumerate(train_dataset):
  print(batch)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by int19h** [comment]
Looks like we need some special sauce just for Tensorflow here. Although I'm not sure that we can actually map the original breakpoint to generated filename.

**Comment by fabioz** [comment]
As a note, using `debugpy.breakpoint()` should break using `debugpy` (in the same way that `pdb.set_trace()` works).

**Comment by fabioz** [comment]
I took a quick look at this and I don't think this is feasible to implement -- it's may be doable, but quite a hassle as we have to monkey-patch many things to get the needed mappings (besides the different filename, a  mapping of the original line to the new line for each statement would be needed).

From what I saw, what tensorflow is doing isn't really calling the Python callback, rather, it gets the code and transforms it and then it'll execute that different code.

The workaround is really using breakpoint() to stop at the proper place:

![image](https://user-images.githubusercontent.com/117621/151433240-17967aa8-b51d-4913-b27b-e3548b4fdca2.png)
