### ISSUE TITLE
debugpy wont respect a breakpoint in a python process with a parent bash subprocess.

### ISSUE THREAD

**Issue by andrescodas** [microsoft/debugpy#793]
## Environment data

- debugpy version: 1.5.1
- OS and version: debian 11 bullseye
- Python version: 3.10.0
- Using VS Code

## Actual behavior

debugpy wont respect a breakpoint in a python process with a parent bash subprocess.
See the toy example I prepared in the code bellow.

## Expected  behavior

debugpy breaks in both subprocesses as illustrated below

## Steps to reproduce:
I have this configuration:

hello-world.py:  # with a breakpoint marked in its unique line
```python
print('hello-world')
```

hello-world.sh:  
```bash
#!/bin/bash
python3 hello-world.py 
```

hello-world-launcher.py
```python
import subprocess

subprocess.run(['bash', 'hello-world.sh'])  # the debugger does not attach to the python process launches within this subprocess
subprocess.run(['python3', 'hello-world.py'])  # the debugger is attached as expected in this case
```
launch.json
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "python-hello-world",
            "type": "python",
            "request": "launch",
            "cwd": "${workspaceFolder}",
            "program": "${workspaceFolder}/hello-world-launcher.py",
            "console": "integratedTerminal",
            "subProcess": true
        }
    ]
}
```

**Comment by int19h** [comment]
When you spawn a subprocess that is a Bash script, that process isn't debugged, since it's not a Python process. And since it's not being debugged, we can't intercept further subprocesses spawned by it. So this is a known, by-design limitation.
