### ISSUE TITLE
timed out waiting for debuggee to spawn

### ISSUE THREAD

**Issue by maarten-vandenberg** [microsoft/debugpy#794]
### VS Code version

1.62.3

### Extension version

v2021.11.1422169775

### OS type

Windows

### OS version

Windows Server 2019 Datacenter

### Python distribution

Anaconda

### Python version

3.8.6

### Language server

Default

### Expected behaviour

vs code executes Python script in debug mode

### Actual behaviour

An error message is shown in a pop-up: "timed out waiting for debuggee to spawn"

### Steps to reproduce

run a minimal Python script, e.g. a single print() statement. Then, run that same script again.

- the first time it runs as expected, the second time it does not
- I've seen a few similar issues, but those seem out of date (and I'm not entirely sure I'm posting this in the correct repository)
- killing the existing debug terminal before debugging does not change behaviour
- when I execute reload window before debugging, behaviour is as expected
- the Python 'output' remains empty

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by int19h** [comment]
Can you try adding `"logToFile": true` to your debug config, and sharing the log files that produces when the bug happens? Those are named `debugpy*.log`, and will be located in the directory where the extension is installed (you can see the path in the terminal when launching a debug session - it'll be the `...` in `.../pythonFiles/lib/python/debugpy/launcher`).

**Comment by fabioz** [comment]
Closing as no further info was given.
