### ISSUE TITLE
Implement DAP supportsSingleThreadExecutionRequests and singleThread

### ISSUE THREAD

**Issue by int19h** [microsoft/debugpy#797]
See https://github.com/microsoft/debug-adapter-protocol/issues/214 for details.

We already implement the requisite behavior in practice, but it's controlled by our own custom properties on a per-session basis. Now that DAP has a standard mechanism for the client to request this for every step or continue, we should support that as well, and report that support via the corresponding property.

(Note that we still need to maintain the custom property that we already have for back-compat reasons.)

**Comment by judej** [comment]
Thank you for the report. Given our current resources are working on the Python 3.12 debugger, we will not be fixing this issues in the pre Python 3.12 debugger.
