### ISSUE TITLE
Subprocess always waits for client to attach

### ISSUE THREAD

**Issue by memeplex** [microsoft/debugpy#81]
## Environment data

- PTVSD version: the one shipped with vscode-python March 2020
- OS and version: Ubuntu 19.10
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.5
- Using VS Code or Visual Studio: VSCode

## Actual behavior

I run this script

```
import time
import multiprocessing as mp


def f():
    x = 0
    while True:
        x += 1
        print("y")
        time.sleep(0.1)


print("x")
p = mp.Process(target=f)
p.start()
p.join()
```

with `python3 -m debugpy --listen localhost:5678 /tmp/test.py`.

I can see `"x"` but no `"y"`.

## Expected  behavior

According to your README this should not wait for a client to attach, so the subprocess should immediately start running.

## Steps to reproduce:

Run the above script as explained.

**Comment by int19h** [comment]
This is an interesting point!

The current design does indeed force a wait on any subprocess attached in the same logical session. The reason for that is to treat breakpoints as if they were also a part of that single logical session, with processes working more or less like threads. Which is to say - if you have a breakpoint set on the very first line of code inside the child process about to be spawned (e.g. inside `f`, in your example), and you step over the statement that spawns it in the parent process, the breakpoint should be hit. Just as it would be hit if you did the same thing with a thread. This requires that child process doesn't run any user code, until the client can connect and tell it what the active breakpoints are. 

I think our problem here is that this doesn't really make sense when there are *no* active client sessions in the current multiproc logical session - i.e. subprocesses should only wait implicitly at spawn if the notification about them was successfully delivered to the client.

**Comment by memeplex** [comment]
Great, thanks!
