### ISSUE TITLE
Fail to run debugpy using vscode with flask, "No module named" error message

### ISSUE THREAD

**Issue by pancudaniel7** [microsoft/debugpy#811]
## Environment data

- debugpy version: 1.5.1 
- OS and version: macOS 11.6 20G165 x86_64
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.7.12
- Using VS Code or Visual Studio: VS Code

## Actual behavior

<img width="1227" alt="Screenshot 2021-12-21 at 23 26 19" src="https://user-images.githubusercontent.com/9675142/146999789-643ca7c9-2a6e-4e14-ae5c-9214a9bae7e9.png">

And timeout Error after trying to access flask endpoint

## Expected  behavior

Expected behavior  will be to not get that error mesage after runnign the debuger and a timeout

## Steps to reproduce:
1. Using this script to start use debugpy:
```sh
import debugpy

            debugpy.listen(("localhost", 5050))
            print("VS Code debugger can now be attached, press F5 in VS Code", flush=True)
            debugpy.wait_for_client()
            print("VS Code debugger attached, enjoy debugging", flush=True)
```

2. Also this python remote config:
```sh
  # launch.json
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Python: Remote Attach",
      "type": "python",
      "request": "attach",
      "connect": { "host": "localhost", "port": 5050 },
      "pathMappings": [{ "localRoot": "${workspaceFolder}", "remoteRoot": "." }]
    },
  ]
}
```

3. And after executing: 
```sh
python -m flask run
``` 
4. Press f5 for starting vscode debugger I get this:
<img width="1227" alt="Screenshot 2021-12-21 at 23 26 19" src="https://user-images.githubusercontent.com/9675142/146999973-81a79787-1d11-4726-b038-982d89287333.png">

**Comment by int19h** [comment]
It looks like the child process (the one that runs your code) is running against a venv with a corrupted debugpy installation. You should have a subpackage `adapter` (and a bunch of others) present under `site-packages/debugpy` if everything is installed properly. Can you try removing & re-installing debugpy in that venv, and see if that helps?

If it doesn't help, are there any warnings or other unusual messages coming from `pip` (or `conda` if you're using that) when installing debugpy? And what does the directory actually look like on disk?

**Comment by fabioz** [comment]
Closing as there wasn't more feedback on the issue.
