### ISSUE TITLE
debugpy breaks `breakpoint()` in pytest context

### ISSUE THREAD

**Issue by d-chambers** [microsoft/debugpy#813]
Hello,

I recently traced an issue in the built-in `breakpoint()` behavior back to debugpy. Essentially, simply having debugpy installed causes the built-in `breakpoint()` to do nothing when run in a pytest context.

I am not using VS code. debugpy is used (and installed) by the ipython kernel. 

## Environment data
- debugpy version: 1.5.1
- OS and version: ubuntu 20.04
- Python version 3.9. Anaconda
- Using VS Code or Visual Studio: Neither

## Actual behavior

When I place a `breakpoint()` in a pytest test function:

```python 
# contents of test_it.py

def test_breakpoint():
    breakpoint()
    print('end test_breakpoint')
```

and run the test suite with pytest

```bash
pytest
```

nothing happens. However, if I uninstall debugpy it works as expected (ie the pdb session starts after the breakpoint call).

## Expected  behavior

Installing debugpy should not modify the default `breakpoint()` behavior. 

## Steps to reproduce:

1. Create the test_it.py file described above
2. Run the tests with `pytest`
3. Uninstall debug py
4. Run tests again with `pytest` and observe the expected behavior.

**Comment by int19h** [comment]
The debugpy (or rather pydevd) breakpoint hook is installed only when it is imported, so something is implicitly importing the package here.

Is it installed normally (i.e. into site-packages)? Or did you vendor it, by chance? I would expect pytest to import it if it's a package in the tests directory, but otherwise it would be rather weird.

**Comment by d-chambers** [comment]
No, it was installed normally through pip.

Right you are though, it was getting imported from the ptyest-plug-in [nbval](https://github.com/computationalmodelling/nbval) which imports something from the ipython kernel, which import debugpy. I guess I will open an issue with them. I suppose they could un-register the hook after loading the model?

**Comment by fabioz** [comment]
Well, when the package is imported, it does set the `breakpointhook` to use it (which is expected in general).

As a client you can still change `PYTHONBREAKPOINT` to use pdb if you want, but if you're not using the debugger, it probably shouldn't be imported in the first place (but that's an issue in the place that uses the debugger, not in the debugger itself...).

So, closing as the debugger seems to be doing the proper thing here.
