### ISSUE TITLE
High CPU Usage - v1.5.1  

### ISSUE THREAD

**Issue by ThePieMonster** [microsoft/debugpy#816]
## Environment data

- debugpy version: XXX (run `import debugpy; print(debugpy.__version__)` if uncertain): 1.5.1  
- OS and version: Windows 10
- Python version (& distribution if applicable, e.g. Anaconda): 3.9
- Using VS Code or Visual Studio: VS Code

## Actual behavior

CPU usage is through the roof when debugging Docker container with debugpy.

![image](https://user-images.githubusercontent.com/11359134/148720287-d7b5fa93-089d-4f9d-8f5f-4b5487bba945.png)

## Expected  behavior

My CPU doesn't catch fire.

## Steps to reproduce:
1. In VS Code, go to debug
2. Select the python attach config
3. Run the debugger 

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal"
        },
        {
            "name": "Python: Remote Attach",
            "type": "python",
            "request": "attach",
            "connect": {
                "host": "localhost",
                "port": 5678
            },
            "pathMappings": [
                {
                    "localRoot": "${workspaceFolder}",
                    "remoteRoot": "."
                }
            ]
        }
    ]
}
```

**Comment by int19h** [comment]
vmmem is the aggregate usage of everything across all VMs. Can you show the breakdown from inside the container, e.g. via `top`?

**Comment by fabioz** [comment]
Closing as no further info was given (it's very unclear whether the debugger is actually responsible for the high cpu).
