### ISSUE TITLE
Cannot step into external programs even when "justMyCode" is set to false

### ISSUE THREAD

**Issue by seishiroono** [microsoft/debugpy#817]
### VS Code version

1.63.2

### Extension version

2021.12.1559732655

### OS type

macOS

### OS version

Monterey 12.1

### Python distribution

python.org

### Python version

3.9.9

### Language server

None or Disabled

### Expected behaviour

The debugger can step into external (or standard) packages.
In particular, when we set a breakpoint at `mol.build()` in the following example, the debugger steps into mole.py.

### Actual behaviour

It cannot step into external (or standard) packages, i.e., it ignores them. 
However, the program works well, and I can obtain the collect result.

### My json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Debug Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "stopOnEntry": true,
            "justMyCode": false
        }
    ]
}
```

### setting.json
```
{
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "terminal.integrated.inheritEnv": false,
    "python.pythonPath": "/usr/local/bin/python3"
}
```

### Sample program
```
import numpy as np
from pyscf import gto

mol = gto.Mole()
mol.verbose = 0
mol.atom="""8            .000000     .000000     .119262
1            .000000     .763239    -.477047
1            .000000    -.763239    -.477047"""
mol.charge=0
mol.spin  = 0
mol.basis = "6-31G"
mol.build() # I set a breakpoint here.

print(mol.atom)
```

I saw other issues (e.g., microsoft/vscode-python#7347, microsoft/vscode-python#10637). However, the solution seems not to work for me.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by seishiroono** [comment]
I'm sorry that I gave a bad exmaple.
I update the example which is a very simple version of my actual problem.
I want to use an external package, pyscf, and debug it.

Thank you for your help in advance.

**Comment by int19h** [comment]
Can you specify which line are you trying to perform the step on? Looking at pyscf repo, it also has some native code in it.

Note that if you want to debug the C code alongside Python, it is [supported](https://docs.microsoft.com/en-us/visualstudio/python/debugging-mixed-mode-c-cpp-python-in-visual-studio?view=vs-2022) in Visual Studio proper (but not in VS for Mac or VSCode).

**Comment by seishiroono** [comment]
@int19h Thank you for your comment. Actually, I set a breakpoint `mol.build()` in the above example. 
Then, I expect that the debugger steps into mole.py (a python file of pyscf), but nothing happens.

**Comment by seishiroono** [comment]
> I'll get my hands on an Intel mac and give it another try.
Thank you for your help. Actually, my laptop is also Intel Mac.

> if you have access to a Linux environment, can you check if it repros for you there as well?
I'm sorry that I don't have a Linux environment.

**Comment by seishiroono** [comment]
@int19h Could you reproduce the problem with your mac? 
Thank you very much for your time in advance.

**Comment by fabioz** [comment]
@seishiroono can you provide the logging from running in your machine?

i.e.:

* Open VS Code
* Select the command Extensions: Open Extensions Folder
* Locate the Python extension directory, typically of the form `ms-python.python-2021.*.****`
* In that directory ensure you do not have any debug*.log files, if you do, please delete them
* Go back into VS Code and modify your launch.json to add the setting "logToFile": true, see below:

```
{
    "name": "Python: Current File (Integrated Terminal)",
    "type": "python",
    "request": "launch",
    "program": "${file}",
    "console": "integratedTerminal",
    "logToFile": true
}
```

* Start debugging
* When done, go back into the extension directory and upload the debug*.log files into this GitHub issue.

**Comment by seishiroono** [comment]
@fabioz Sorry, I didn't get what you meant. The following things are what I have to do?
1.  Install ms-python.python (Actually, I use version 2021.12.1559732655)
2. Check if there does not exist debug(filename).log (Delete it if exists in the current opened folder)
3. Add `"logToFile": true`
4. Perform debugging

If the above is correct, I actually did not get log file...

Here is the `launch.json`
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Debug Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "stopOnEntry": true,
            "justMyCode": false,
            "logToFile": true
        }
    ]
}
```

Also, I found that debug console in VScode said 
```
Frame skipped from debugging during step-in.
Note: may have been skipped because of "justMyCode" option (default == true). Try setting "justMyCode": false in the debug configuration (e.g., launch.json).
```

However, as you can see,  I add `"justMyCode": false` to my launch.json

**Comment by seishiroono** [comment]
Thank you for your message. 
I see. Let me share my screenshots.

First, I put a file named "test.py", which is the same file as the above example.
Then, VScode told me that there are no json files in this folder (see the first screenshot). 
So, I made it and add some lines to "launch.json", which results in the above json file.
"launch.json" was created in ./.vscode, as shown in the second screenshot.

(first screenshot)
<img width="1741" alt="screen1" src="https://user-images.githubusercontent.com/78581948/150438829-8038dab2-c674-45f8-a982-3d709dde71fe.png">

(second screenshot)
<img width="1741" alt="screen2" src="https://user-images.githubusercontent.com/78581948/150439159-1a986c0c-2018-4e05-8650-05fee4a5fd2e.png">

Next, I performed debug, but I got the same result...

What should I do?
Thank you for your help!

**Comment by seishiroono** [comment]
@fabioz Are there any mistakes?
If so, please let me know.

I appreciate your help.

**Comment by fabioz** [comment]
But for launching are you clicking the launch config or are you using some other shortcut?

i.e.: if you click here it should work (but if you use some other shortcut it may need to be defined differently...).

![image](https://user-images.githubusercontent.com/117621/151153079-59e35eea-36dc-4044-a7e9-b67fedb27912.png)

**Comment by fabioz** [comment]
Depending on how you run you really need to configure the `launch.json` differently (if you want to use that dropdown, I think you need to specify a different `purpose` to customize it -- see: https://code.visualstudio.com/docs/python/debugging#_purpose).

**Comment by chopeen** [comment]
Only tangentially related, but after reading this discussion many time, let me post in here - in my case, I could not enter a certain function while debugging a unit test, because that function was **patched** to return `{}`.

**Comment by vpozdnyakov** [comment]
@chopeen justMyCode does not work in unit test debugging, am I right? I have the same issue.
Any options to fix that?

**Comment by chopeen** [comment]
@vpozdnyakov I am able to step into 3rd party library code while debugging unit tests with the following configuration added to `launch.json`:

```
{
    "name": "Debug Unit Test",
    "type": "python",
    "request": "test",
    "justMyCode": false,
}
```

Source: https://github.com/microsoft/vscode-python/issues/7131#issuecomment-525873210

**Comment by Aaron-WengXu** [comment]
> @chopeen justMyCode does not work in unit test debugging, am I right? I have the same issue.
> Any options to fix that?

I agree with you. If I use Jupyter notebook and debug code segments individually, I can not step into the std library. If I put all code segments in a single python file, however, I can do it.
