### ISSUE TITLE
Print None in the Debug Console, while printing the output to the terminal

### ISSUE THREAD

**Issue by nirzaa** [microsoft/debugpy#822]
### VS Code version

1.63.2

### Extension version

v2021.12.1559732655

### OS type

Windows

### OS version

Windows 10

### Python distribution

Anaconda

### Python version

3.7.10

### Language server

Pylance

### Expected behaviour

Print the output to the Debug Console.

### Actual behaviour

When I type `print('hello world')` it prints the output to the terminal and prints `None` to the Debug Console.

### Steps to reproduce

![image](https://user-images.githubusercontent.com/72485675/149616770-a27bc643-9e09-4273-9aba-a421ea5110c3.png)

I tried to change the launch.json file to:
![image](https://user-images.githubusercontent.com/72485675/149616803-49c2667e-776a-41e1-ab25-d3ad830436c9.png)

But the bug remains the same.

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by nirzaa** [comment]
> `print()` returns `None`, so we treat that as a function return. Think running something like `sum([1,2,3])`.

I think it might be helpful that the Debug Console will act like a normal script, and as such, will not return `None` while using print. That's my opinion at least

**Comment by fabioz** [comment]
This was actually fixed in https://github.com/microsoft/debugpy/issues/678 (note that this still hasn't made it into a new release...)
