### ISSUE TITLE
VSCode Debugger for Python2 Does Not Work. 

### ISSUE THREAD

**Issue by zkzupup** [microsoft/debugpy#823]
### VS Code version

 Code 1.63.2 (899d46d, 2021-12-15T09:40:02.816Z)

### Extension version

v2021.12.1559732655

### OS type

Windows

### OS version

 Windows_NT x64 10.0.22000

### Python distribution

python.org

### Python version

python2.7

### Language server

Pylance

### Expected behaviour

normal debug

### Actual behaviour

debug function does not work for python2! I have Python2 and Python3 and Conda Python， does it influce each other?
python3 workspace works well, but python2 worksapce can not debug....

![DebugGif](https://user-images.githubusercontent.com/54658503/149659812-16519bd4-d851-4547-9cf1-6c2a350869ef.gif)

### Steps to reproduce

1.click debug or press f5 to start debug
2.debug console closely right now

### Logs

Experiment 'pythonaa' is active
Experiment 'pythonTensorboardExperiment' is active
Experiment 'PythonPyTorchProfiler' is active
Experiment 'pythonDeprecatePythonPath' is active
> conda info --json
> "D:\Program Files (x86)\Python310\python.exe" ~\.vscode\extensions\ms-python.python-2021.12.1559732655\pythonFiles\interpreterInfo.py
> python2 -c "import sys;print(sys.executable)"
> python2 -c "import sys;print(sys.executable)"
> python2 -c "import sys;print(sys.executable)"
> "D:\Program Files (x86)\Python2.7\python2.exe" ~\.vscode\extensions\ms-python.python-2021.12.1559732655\pythonFiles\interpreterInfo.py
Python interpreter path: d:\Program Files (x86)\Python2.7\python2.exe
> "D:\Program Files (x86)\Anaconda3\python.exe" ~\.vscode\extensions\ms-python.python-2021.12.1559732655\pythonFiles\interpreterInfo.py
> "D:\Program Files (x86)\Anaconda3\envs\TestPython\python.exe" ~\.vscode\extensions\ms-python.python-2021.12.1559732655\pythonFiles\interpreterInfo.py
> python2 -c "import sys;print(sys.executable)"
> python2 -c "import sys;print(sys.executable)"
> python2 -c "import sys;print(sys.executable)"
> python2 -c "import sys;print(sys.executable)"
> python2 -c "import sys;print(sys.executable)"
> python2 -c "import sys;print(sys.executable)"
> python2 -c "import sys;print(sys.executable)"
> python2 -c "import sys;print(sys.executable)"
> python2 -c "import sys;print(sys.executable)"
> python2 -c "import sys;print(sys.executable)"
> python2 -c "import sys;print(sys.executable)"
Starting Pylance language server.
> python2 -c "import sys;print(sys.executable)"
> python2 -c "import sys;print(sys.executable)"
> python2 -c "import sys;print(sys.executable)"

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fabioz** [comment]
Well, right now python 2 should still run (and there shouldn't be any problems -- unless you have something mixed up in your own install).

From your gif, it shows that you're clicking the button to `run`, not the button to `debug`... if you click that dropdown and select the `Debug Python File` doesn't it run?

What about if you create an entry in `launch.json` and configure it to make the debug, does it work then?

If you still can't get it to work, please provide the logs for the run.

i.e.:

* Open VS Code
* Select the command Extensions: Open Extensions Folder
* Locate the Python extension directory, typically of the form `ms-python.python-2021.*.****`
* In that directory ensure you do not have any debug*.log files, if you do, please delete them
* Go back into VS Code and modify your launch.json to add the setting "logToFile": true, see below:

```
{
    "name": "Python: Current File (Integrated Terminal)",
    "type": "python",
    "request": "launch",
    "program": "${file}",
    "console": "integratedTerminal",
    "logToFile": true
}
```

* Start debugging that launch configuration from the launch view.
* When done, go back into the extension directory and upload the debug*.log files into this GitHub issue.

**Comment by zkzupup** [comment]
> 
I did as you wish! This is the Log file. Please Check, thank you. 
[debugger.vscode_fea0e005-5fd5-4687-a8ff-a67323dbc606.log](https://github.com/microsoft/debugpy/files/7914360/debugger.vscode_fea0e005-5fd5-4687-a8ff-a67323dbc606.log)

**Comment by zkzupup** [comment]
> Well, right now python 2 should still run (and there shouldn't be any problems -- unless you have something mixed up in your own install).
> 
> From your gif, it shows that you're clicking the button to `run`, not the button to `debug`... if you click that dropdown and select the `Debug Python File` doesn't it run?
> 
> What about if you create an entry in `launch.json` and configure it to make the debug, does it work then?
> 
> If you still can't get it to work, please provide the logs for the run.
> 
> i.e.:
> 
> * Open VS Code
> * Select the command Extensions: Open Extensions Folder
> * Locate the Python extension directory, typically of the form `ms-python.python-2021.*.****`
> * In that directory ensure you do not have any debug*.log files, if you do, please delete them
> * Go back into VS Code and modify your launch.json to add the setting "logToFile": true, see below:
> 
> ```
> {
>     "name": "Python: Current File (Integrated Terminal)",
>     "type": "python",
>     "request": "launch",
>     "program": "${file}",
>     "console": "integratedTerminal",
>     "logToFile": true
> }
> ```
> 
> * Start debugging that launch configuration from the launch view.
> * When done, go back into the extension directory and upload the debug*.log files into this GitHub issue.

I did as you wish! This is the Log file. Please Check, thank you.
debugger.vscode_fea0e005-5fd5-4687-a8ff-a67323dbc606.log

**Comment by fabioz** [comment]
Humm, these aren't really the debug files I was expecting... the files I was expecting would be in the format `debugpy.xxx-<pid>.log`.

p.s.: I've tested it here and it is working for me for Python 2 (so, this is likely some misconfiguration on the python 2 you have on your machine... I'd suggest you try to get conda and create an isolated python 2 environment using it and try with that...)

**Comment by zkzupup** [comment]
> Humm, these aren't really the debug files I was expecting... the files I was expecting would be in the format `debugpy.xxx-<pid>.log`.
> 
> p.s.: I've tested it here and it is working for me for Python 2 (so, this is likely some misconfiguration on the python 2 you have on your machine... I'd suggest you try to get conda and create an isolated python 2 environment using it and try with that...)

Sorry, I didn't find the debug file you mentioned....
and I tried the virtual python2 env created by anaconda, but it does not work too.(same as the gif)

**Comment by int19h** [comment]
We're not investigating Python 2 issues at this point. If you need Python 2 support, please use the most recent version of the Python for VSCode extension that supported it.
