### ISSUE TITLE
Compiled code without file, but with source in `linecache` confuses VSCode debugger unless `justMyCode` is explicitly set to `false`, but that's difficult to understand or discover

### ISSUE THREAD

**Issue by posita** [microsoft/debugpy#828]
_UPDATED:_ #627 is marked as closed and indicates support for in-memory code that is represented in `linecache`, but this doesn't work with the defaults. VSCode is confused by linecache entries unless `justMyCode` is set to `false` in `launch.json`. The entry doesn't appear at all in the default config, so it's difficult to know it even exists, much less what it does, or what to set it to in order to get the desired behavior.

## Environment data

- debugpy version: 1.5.1
- OS and version: Mac 11.6.1
- Python version (& distribution if applicable, e.g. Anaconda): 3.9.10
- Using VS Code or Visual Studio: 1.63.2

Test file:

``` python
# test_case.py
import linecache

import debugpy

print(debugpy.__version__)

func_def = """
def final_countdown(arg, count: int = 10):
  print(count)
  if count <= 0:
    return were_leaving_together(arg)
  else:
    return final_countdown(arg, count - 1)
""".strip()


def were_leaving_together(arg):
    print(repr(arg))
    breakpoint()


filename = "<myfile>"
code_obj = compile(func_def, filename, "single")
linecache.cache[filename] = (
    len(func_def),
    None,
    func_def.splitlines(keepends=True),
    filename,
)

exec(code_obj, globals(), globals())
final_countdown("but it's still farewell")
```

Works well (as expected) in `pdb`:

``` sh
% python test_case.py
1.5.1
10
9
8
7
6
5
4
3
2
1
0
"but it's still farewell"
--Return--
> /Users/matt/dev/dyce/test_case.py(20)were_leaving_together()->None
-> breakpoint()
(Pdb) bt
  /Users/matt/dev/dyce/test_case.py(33)<module>()
-> final_countdown("but it's still farewell")
  <myfile>(6)final_countdown()
-> return final_countdown(arg, count - 1)
  <myfile>(6)final_countdown()
-> return final_countdown(arg, count - 1)
  <myfile>(6)final_countdown()
-> return final_countdown(arg, count - 1)
  <myfile>(6)final_countdown()
-> return final_countdown(arg, count - 1)
  <myfile>(6)final_countdown()
-> return final_countdown(arg, count - 1)
  <myfile>(6)final_countdown()
-> return final_countdown(arg, count - 1)
  <myfile>(6)final_countdown()
-> return final_countdown(arg, count - 1)
  <myfile>(6)final_countdown()
-> return final_countdown(arg, count - 1)
  <myfile>(6)final_countdown()
-> return final_countdown(arg, count - 1)
  <myfile>(6)final_countdown()
-> return final_countdown(arg, count - 1)
  <myfile>(4)final_countdown()
-> return were_leaving_together(arg)
> /Users/matt/dev/dyce/test_case.py(20)were_leaving_together()->None
-> breakpoint()
(Pdb) u
> <myfile>(4)final_countdown()
-> return were_leaving_together(arg)
(Pdb) u
> <myfile>(6)final_countdown()
-> return final_countdown(arg, count - 1)
(Pdb) l
  1     def final_countdown(arg, count: int = 10):
  2       print(count)
  3       if count <= 0:
  4         return were_leaving_together(arg)
  5       else:
  6  ->     return final_countdown(arg, count - 1)
[EOF]
(Pdb) n
--Return--
> <myfile>(6)final_countdown()->None
-> return final_countdown(arg, count - 1)
(Pdb) l
  1     def final_countdown(arg, count: int = 10):
  2       print(count)
  3       if count <= 0:
  4         return were_leaving_together(arg)
  5       else:
  6  ->     return final_countdown(arg, count - 1)
[EOF]
(Pdb) count
1
(Pdb) arg
"but it's still farewell"
(Pdb) c
```

Also works as expected with `PYTHONBREAKPOINT=IPython.core.debugger.set_trace ipython test_case.py` (not shown, but substantially similar to `pdb` above).

But VSCode gets confused:

``` sh
% python -m debugpy --listen 5678 --wait-for-client test_case.py
```

Upon connection, VSCode breaks on line 33 (which is incorrect) and shows nothing on the stack (which is also incorrect):

![screenshot](https://user-images.githubusercontent.com/222581/151395193-ea3b470f-ff91-4a91-8331-23a5622c025c.png)

From there, hitting step-over ends the program, which is also not expected.

Remote debug config:

``` javascript
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
    
        {
            "name": "Python: Remote Attach",
            "type": "python",
            "request": "attach",
            "connect": {
                "host": "localhost",
                "port": 5678
            },
            "pathMappings": [
                {
                    "localRoot": "${workspaceFolder}",
                    "remoteRoot": "."
                }
            ]
        }
    ]
}
```

**Comment by posita** [comment]
I'm wondering if `true` is the correct (implicit) default for this setting? Is there any reason not to default to `false` where it's omitted?

**Comment by fabioz** [comment]
Well, ideally you'd read through the manual (https://code.visualstudio.com/docs/python/debugging) -- `justMyCode` does affect the debugger quite a bit (as it restricts where you can step and what you see while debugging to remove anything which isn't considered your own code) -- in this case it filtered out that file because the heuristics don't consider non-valid filenames to be user code.

Maybe the templates could add `"justMyCode": true` by default (even though that's already the default) to make it clearer that this is such an important setting? (although that's in the `vscode-python` scope, not really debugpy...)

@karthiknadig @int19h @luabud what do you think?

**Comment by posita** [comment]
Thanks! I read the manual years ago, but don't revisit it often. My assumption has always been that the default settings don't invoke any magic or shouldn't present any surprises. 🤷 Adding an entry (preferably with a comment or at least a link back to the docs) might help.

> the heuristics don't consider non-valid filenames to be user code

Maybe those are the wrong heuristics? Maybe `<…>` entries or those with `mtime` equal to `None should be included? Not sure.

**Comment by fabioz** [comment]
> Thanks! I read the manual years ago, but don't revisit it often. My assumption has always been that the default settings don't invoke any magic or shouldn't present any surprises. 🤷 Adding an entry (preferably with a comment or at least a link back to the docs) might help.
> 
> > the heuristics don't consider non-valid filenames to be user code
> 
> Maybe those are the wrong heuristics? Maybe `<…>` entries or those with `mtime` equal to `None should be included? Not sure.

Unfortunately the standard library has many of those and the user usually doesn't want to see the whole boilerplate when stepping when dealing with dataclasses, namedtuples, etc (many libraries use this). I think there's no setting which will make everyone happy all the time...

**Comment by posita** [comment]
https://xkcd.com/1172/

😉

**Comment by luabud** [comment]
> Maybe the templates could add "justMyCode": true by default (even though that's already the default) to make it clearer that this is such an important setting? 

I like that idea! It also could help with discoverability of the setting.  I created https://github.com/microsoft/vscode-python/issues/18389 to track this request in the Python extension side.

**Comment by fabioz** [comment]
Given that the discoverability was dealt with in `vscode-python`, I don't think there's anything else to do here, so, I'm closing the issue...
