### ISSUE TITLE
`sys.path` as initialized by debugger differs from regular python interpreter

### ISSUE THREAD

**Issue by david-cortes** [microsoft/debugpy#830]
## Environment data

- debugpy version: 1.5.1
- OS and version: debian sid
- Python version (& distribution if applicable, e.g. Anaconda): 3.9.7 (anaconda)
- Using VS Code or Visual Studio: vscode

From https://github.com/microsoft/debugpy/issues/759

## Actual behavior

When debuggin a python file, the `sys.path` initialized by the debugger differs from that of the regular python interpreter or of the interactive python interpreter in vscode.

Particularly, on a stock debian linux installation, launching `python` will make `sys.path` contain an empty string as one of the entries, while the vscode python debugger does not have that. Regular `pdb` has the same entries in `sys.path` as the python interpreter.

## Expected  behavior

The debugger should have all of the entries that are in `sys.path` when the regular python interpreter is launched under its default configuration (e.g. when running `python` in a terminal on linux), plus any additional necessary entries if any appended at the end.

## Steps to reproduce:
1. Launch the debugger, execute this: `import sys; print(sys.path)`.
2. Compare against the same output executing that in a regular python interpreter.

**Comment by fabioz** [comment]
This is really weird (I definitely don't know why/how you're having that behavior).

i.e.: What I get on Ubuntu is the following:

![image](https://user-images.githubusercontent.com/117621/151585176-69a5df0d-ef9a-4564-90ff-d68e10f781a6.png)

This matches the documentation: https://docs.python.org/3/library/sys.html#sys.path

> As initialized upon program startup, the first item of this list, path[0], is the directory containing the script that was used to invoke the Python interpreter. If the script directory is not available (e.g. if the interpreter is invoked interactively or if the script is read from standard input), path[0] is the empty string, which directs Python to search modules in the current directory first. Notice that the script directory is inserted before the entries inserted as a result of PYTHONPATH.

When you tested it, are you testing launching a file and then checking printing from the launch or going into the interactive terminal (where this would be expected) -- or some other way?

**Comment by david-cortes** [comment]
I was testing by launching the python interpreter without any file as argument, like in your first example, but if I launch it with a file as argument then it does replace the empty string with the working directory path.

IMHO I nevertheless think the debugger should prefer to mimic an interactive interpreter, as that's the kind of environment that one would get in other debuggers (at least in spyder, which has the empty string in `sys.path` when debugging a file, in addition to the current working directory as first argument) and in vscode when e.g. running code with shift+enter; the moreso since one usually does not debug a project by launching the main script directly but by first isolating the problem and running a smaller script.

**Comment by fabioz** [comment]
> I was testing by launching the python interpreter without any file as argument, like in your first example, but if I launch it with a file as argument then it does replace the empty string with the working directory path.
> 
> IMHO I nevertheless think the debugger should prefer to mimic an interactive interpreter, as that's the kind of environment that one would get in other debuggers (at least in spyder, which has the empty string in `sys.path` when debugging a file, in addition to the current working directory as first argument) and in vscode when e.g. running code with shift+enter; the moreso since one usually does not debug a project by launching the main script directly but by first isolating the problem and running a smaller script.

The debugger can't really make something as that (i.e.: that goes against the python docs) -- if you want something like that to be changed, you need to advocate that change to Python itself (the debugger should try to do exactly what Python has implemented, if it doesn't I see people complaining the other way around -- i.e.: why is it that this works in the debugger but not when I run my program...).
