### ISSUE TITLE
Cannot debug pytest tests on gevent based code

### ISSUE THREAD

**Issue by sradhakrishna** [microsoft/debugpy#834]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

1.  Clone https://github.com/sradhakrishna/test-nameko
2.  Open Visual Studio Code, and open the workspace.code-workspace file.
Command Palette -> Tasks: Manage Automatic Tasks in Folder -> Select Allow Automatic Tasks in Folder
3.  Close and Reopen Visual Studio Code.
4.  The automatic tasks should now run and setup a virtualenv, and install both Sources and Tests requirements. Pytest should also be configured and setup. pytest.ini and the requirements file in Tests/requirements.txt should provide information about how pytest is setup.
5.  On the Testing pane, test_event_interface should be visible.
6.  Kick off debugging the test by hitting Debug Test icon
7.  The debugger will hang.

Is there a way we can set gevent=true for test debug sessions? 

Not really sure if this is a python extension related issue or if its more of an issue with Visual Studio Code as such. 

Extension version: 2022.0.1762517795-dev
VS Code version: Code 1.64.0 (Universal) (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:20:17.224Z)
OS version: Darwin x64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (3.98GB free)|
|Process Argv|--crash-reporter-id 1d4acee8-c892-481f-9175-595f87e67243|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dsc:30433058
pythonvs932:30410667
wslgetstarted:30426333
vscop940:30404999
vsrem710:30416614

```

</details>

**Comment by luabud** [comment]
Hi @sradhakrishna! Apologies for the delay.

I noticed that at the time you filed this issue there was no launch.json configuration in the repo you added here, but now it seems that it does: https://github.com/sradhakrishna/test-nameko/blob/main/.vscode/launch.json

And at first glance, the way to pass `gevent: true` for debugging tests seem to be correct as well. Did you get it working?

**Comment by sradhakrishna** [comment]
Hi Luciana,

Yes, I was able to get it to work. I had posted this on the vscode-python
project here https://github.com/microsoft/vscode-python/issues/18495, and
got help from Kartik. Thanks much!

--
Regards,
Radha

**Comment by sradhakrishna** [comment]
Got help to have his resolved here: https://github.com/microsoft/vscode-python/issues/18495.

Thanks,
Radha!
