### ISSUE TITLE
Breakpoint in hypothesis test is not hit

### ISSUE THREAD

**Issue by tekumara** [microsoft/debugpy#837]
In VS Code a breakpoint on the assert line will not be hit, eg:

```python
from statistics import mean

from hypothesis import given
from hypothesis import strategies as st


@given(st.lists(st.floats(allow_nan=False, allow_infinity=False), min_size=1))
def test_mean(xs):
    print("test_mean")
    assert min(xs) <= mean(xs) <= max(xs)
```

Hypothesis: 6.26.1
Vscode: 1.64.0 (commit 5554b12acf27056905806867f251c859323ff7e9)
Debugpy: 1.5.1
Python: 3.9.7
Pytest: 6.2.5
OS: Darwin x64 21.3.0

See [tekumara/hypothesis-debug-vscode](https://github.com/tekumara/hypothesis-debug-vscode) for a full reproduction.

**Comment by tekumara** [comment]
If `export PYDEVD_USE_FRAME_EVAL=1` is set the breakpoint will be hit.

If a `breakpoint()` line is added, it will be hit.

**Comment by gramster** [comment]
I could not get your repro code to work, but do you have the right settings in VS Code?

https://github.com/microsoft/debugpy/wiki/FAQ

**Comment by tekumara** [comment]
I'm using [`"justMyCode": false`](https://github.com/tekumara/hypothesis-debug-vscode/blob/main/.vscode/launch.json#L15) and

<img width="290" alt="Screen Shot 2022-02-15 at 4 02 49 pm" src="https://user-images.githubusercontent.com/125105/153995892-683fbd49-0b16-4c9d-b484-4ba02f146e7d.png">

**Comment by karthiknadig** [comment]
@tekumara Can you share your launch.json?

**Comment by tekumara** [comment]
This is it here: [launch.json](https://github.com/tekumara/hypothesis-debug-vscode/blob/main/.vscode/launch.json)

**Comment by karthiknadig** [comment]
@tekamura Thanks for the details, I am able to repro the bug. Looks like removing the `given` decorator it works as expected, but with the `given` decorator it does not. 

/cc @fabioz
Potentially related: https://github.com/microsoft/debugpy/issues/709 
related: https://github.com/microsoft/debugpy/issues/215

**Comment by fabioz** [comment]
I'm investigating. 

As a note, when running under the debugger, programmatically using `breakpoint()` will stop at the proper place (but I still don't know why it's not working in the first place...)

**Comment by fabioz** [comment]
I've just pushed a fix for this in the debugger.

The issue was the same seen in https://github.com/microsoft/debugpy/issues/844 but in a different context.
