### ISSUE TITLE
Debug Attach to Jupyter Notebook process kills kernel macos M1

### ISSUE THREAD

**Issue by dektoud** [microsoft/debugpy#839]
Issue Type: <b>Bug</b>

# Behaviour
Kernel is dying when attaching a python debugger in macos m1, some relation to cython and zeromq ... Have an intel macbook with the same issue that was resolved by downgrading cython. 

## Expected vs. Actual

Expected to attach a python debug session to a running notebook. 

Actual: 

kernel dies, this output is repeated in the terminal 5 times

```
Traceback (most recent call last):
  File "/Users/uzr/my-python/envs/test/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/uzr/my-python/envs/test/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/uzr/my-python/envs/test/lib/python3.10/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/Users/uzr/my-python/envs/test/lib/python3.10/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.initialize(argv)
  File "/Users/uzr/my-python/envs/test/lib/python3.10/site-packages/traitlets/config/application.py", line 88, in inner
    return method(app, *args, **kwargs)
  File "/Users/uzr/my-python/envs/test/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 632, in initialize
    self.init_sockets()
  File "/Users/uzr/my-python/envs/test/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 282, in init_sockets
    self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
  File "/Users/uzr/my-python/envs/test/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 229, in _bind_socket
    return self._try_bind_socket(s, port)
  File "/Users/uzr/my-python/envs/test/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 205, in _try_bind_socket
    s.bind("tcp://%s:%i" % (self.ip, port))
  File "/Users/uzr/my-python/envs/test/lib/python3.10/site-packages/zmq/sugar/socket.py", line 214, in bind
    super().bind(addr)
  File "zmq/backend/cython/socket.pyx", line 540, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in use
```

## Steps to reproduce:

1. `conda create --name test python notebook`
2. `conda activate test`
3. `jupyter notebook`
4. In the notebook, confirm we're running from the new environment (`import sys;sys.executable`). `import os; os.getpid()` to get the pid of the process to attach too. 
5. Using the launch.json entry below, click debug and attach to the pid from 4.

```
        {
            "name": "Python: Attach using Process Id",
            "type": "python",
            "request": "attach",
            "processId": "${command:pickProcess}"
        },
```

6. Kernel dies with "Dead Kernel" popup and traceback from above printed out to the terminal

Thanks!

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.9 & 3.10
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Conda
-   Value of the `python.languageServer` setting: Pylance

<details>

<summary>User Settings</summary>

<p>

```

defaultLS: {"defaultLSType":"Pylance"}

downloadLanguageServer: true

envFile: "<placeholder>"

venvPath: "<placeholder>"

venvFolders: "<placeholder>"

condaPath: "<placeholder>"

pipenvPath: "<placeholder>"

poetryPath: "<placeholder>"

languageServer: "Pylance"

linting
• enabled: true
• cwd: "<placeholder>"
• Flake8Args: "<placeholder>"
• flake8Enabled: true
• flake8Path: "<placeholder>"
• lintOnSave: true
• banditArgs: "<placeholder>"
• banditEnabled: false
• banditPath: "<placeholder>"
• mypyArgs: "<placeholder>"
• mypyEnabled: false
• mypyPath: "<placeholder>"
• pycodestyleArgs: "<placeholder>"
• pycodestyleEnabled: false
• pycodestylePath: "<placeholder>"
• prospectorArgs: "<placeholder>"
• prospectorEnabled: false
• prospectorPath: "<placeholder>"
• pydocstyleArgs: "<placeholder>"
• pydocstyleEnabled: false
• pydocstylePath: "<placeholder>"
• pylamaArgs: "<placeholder>"
• pylamaEnabled: false
• pylamaPath: "<placeholder>"
• pylintArgs: "<placeholder>"
• pylintPath: "<placeholder>"

sortImports
• args: "<placeholder>"
• path: "<placeholder>"

formatting
• autopep8Args: "<placeholder>"
• autopep8Path: "<placeholder>"
• provider: "autopep8"
• blackArgs: "<placeholder>"
• blackPath: "<placeholder>"
• yapfArgs: "<placeholder>"
• yapfPath: "<placeholder>"

testing
• cwd: "<placeholder>"
• debugPort: 3000
• nosetestArgs: "<placeholder>"
• nosetestsEnabled: undefined
• nosetestPath: "<placeholder>"
• promptToConfigure: true
• pytestArgs: "<placeholder>"
• pytestEnabled: true
• pytestPath: "<placeholder>"
• unittestArgs: "<placeholder>"
• unittestEnabled: false
• autoTestDiscoverOnSaveEnabled: true

terminal
• activateEnvironment: false
• executeInFileDir: "<placeholder>"
• launchArgs: "<placeholder>"

experiments
• enabled: true
• optInto: []
• optOutFrom: []

insidersChannel: "off"

tensorBoard
• logDirectory: "<placeholder>"

```

</p>
</details>

Extension version: 2022.0.1786462952
VS Code version: Code 1.64.0 (Universal) (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:20:17.224Z)
OS version: Darwin arm64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 7, 8|
|Memory (System)|32.00GB (4.90GB free)|
|Process Argv|--crash-reporter-id 99ef5ba8-3174-45c2-a664-379854d0f4b6|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dsc:30433058
pythonvs932:30410667
wslgetstarted:30433507
vscop453:30404998
vsrem710cf:30416617

```

</details>

**Comment by karthiknadig** [comment]
FYI @rchiodo

**Comment by nelsonlin2708968** [comment]
Same issue on Jupyter notebooks

**Comment by int19h** [comment]
We don't support attach-by-PID on ARM yet. You should be able to make this work by using `debugpy.listen()`, however.

**Comment by artemmukhin** [comment]
@int19h I can reproduce it on Intel macOS with Python 3.11 and the latest version of debugpy. Attaching to a Jupyter kernel process results in the kernel dying with `The kernel appears to have died. It will restart automatically` message.

## Environment data

- debugpy version: 1.6.7
- OS and version: Intel macOS Big Sur 11.1
- Python version: Python 3.11
- VS Code: 1.76.2
