### ISSUE TITLE
Handled exception is reported

### ISSUE THREAD

**Issue by Drmikej** [microsoft/debugpy#842]
The following program generates an exception when run in debug mode but works perfectly when run without debug and works under Pycharm etc... The IndexError exception is handled by the inherited __iter__ method but it is reported as an error when run with debug.
 System is Windows 10 latest VSCode Python 3.9.1
Version: 1.64.1 (user setup)
Commit: d6ee99e4c045a6716e5c653d7da8e9ae6f5a8b03
Date: 2022-02-07T17:16:22.147Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

Run the following with debug - it prints 1 to 10  and an exception is reported at the line `raise IndexError('Index out of range')` 
run with no-debug it prints 1 to 10 and no exception is reported (which is the correct behavior). 
```

import collections.abc
class TestSequence(collections.abc.Sequence):
    def __init__(self):
        self.i=1
        self.len=10
    def __len__(self):
        return self.len
    def __getitem__(self,key):
        if key>len(self):
            raise IndexError('Index out of range') 
        return key

t=TestSequence()
for n in t:
    print(n)
```

**Comment by gramster** [comment]
What does your breakpoints pane show? 
<img width="299" alt="image" src="https://user-images.githubusercontent.com/2762632/153659608-178b52ac-c9a2-4bb4-8c11-f6199f3fdf0a.png">

**Comment by Drmikej** [comment]
Sorry -- Raised Exceptions was ticked....
So my bug is really that I didn't know that feature existed.

**Comment by Drmikej** [comment]
A feature not a bug.
