### ISSUE TITLE
import behaves different in debugpy vs python?

### ISSUE THREAD

**Issue by andreihes** [microsoft/debugpy#843]
## Environment data

- debugpy version: `python -c "import debugpy; print(debugpy.__version__)"`
1.5.1

- OS and version: `systeminfo | select-string "OS "`
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19043 N/A Build 19043
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              HP T76 Ver. 01.04.01, 6/1/2021

- Python version (& distribution if applicable, e.g. Anaconda): `python --version`
Python 3.9.6 (CPython)

- Using VS Code or Visual Studio:
VS Code and CLI

### VS Code
Fail in **Run Python File**, no fail in **Debug Python File**
Create a file open with VS Code:
```
import importlib
importlib.util.spec_from_file_location('foo', 'bar')
```
It fails when run and no fail when debug.
Same can be reproduced with launch configuration. It fails on **Run Without Debugging** (CTRL+F5) and no fail when **Start Debugging** (F5). The below error is expected and the problem there is no error in debug mode:
```
Traceback (most recent call last):
  File "c:\Temp\issue\test.py", line 2, in <module>
    importlib.util.spec_from_file_location('foo', 'bar')
AttributeError: module 'importlib' has no attribute 'util'
```

### CLI
Fail in python, no fail in debugpy
```
PS C:\Temp\issue> cat .\test.py
import importlib
importlib.util.spec_from_file_location('foo', 'bar')

PS C:\Temp\issue> python .\test.py
Traceback (most recent call last):
  File "C:\Temp\issue\test.py", line 2, in <module>
    importlib.util.spec_from_file_location('foo', 'bar')
AttributeError: module 'importlib' has no attribute 'util'

PS C:\Temp\issue> python -m debugpy --listen localhost:5678 .\test.py
```

### VS Code
Fail when "run" and fail when "debug"
### CLI
Fail in python and fail in debugpy

## Steps to reproduce:
1. Create file test.py with below code
```
import importlib
importlib.util.spec_from_file_location('foo', 'bar')
```
2. Run `python -m debugpy --listen localhost:5678 .\test.py`
There is no fail however the import must be importlib.util and not just importlib and I expect a fail
3. Open the file from VS Code
run -> it fails (ok), debug -> no fail (**bug?**)

**Comment by gramster** [comment]
Ah, seems like an issue on Windows:

```
C:\Users\grwheel>python  test.py
<module 'importlib' from 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\\lib\\importlib\\__init__.py'>
Traceback (most recent call last):
  File "C:\Users\grwheel\test.py", line 3, in <module>
    print(importlib.util)
AttributeError: module 'importlib' has no attribute 'util'

C:\Users\grwheel>python -m debugpy --listen 12345 test.py
<module 'importlib' from 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\\lib\\importlib\\__init__.py'>
<module 'importlib.util' from 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\\lib\\importlib\\util.py'>C:\Users\grwheel>python  test.py
<module 'importlib' from 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\\lib\\importlib\\__init__.py'>
Traceback (most recent call last):
  File "C:\Users\grwheel\test.py", line 3, in <module>
    print(importlib.util)
AttributeError: module 'importlib' has no attribute 'util'

C:\Users\grwheel>python -m debugpy --listen 12345 test.py
<module 'importlib' from 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\\lib\\importlib\\__init__.py'>
<module 'importlib.util' from 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\\lib\\importlib\\util.py'>
```

**Comment by andreihes** [comment]
@gramster 
It can be reproduced in Linux as well:
```
[ec2-user@ip-172-31-21-156 ~]$ uname -a
Linux ip-172-31-21-156.eu-central-1.compute.internal 5.10.96-90.460.amzn2.x86_64 #1 SMP Fri Feb 4 17:12:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

[ec2-user@ip-172-31-21-156 ~]$ python3 --version
Python 3.7.10

[ec2-user@ip-172-31-21-156 ~]$ python3 -c "import debugpy; print(debugpy.__version__)"
1.5.1

[ec2-user@ip-172-31-21-156 ~]$ cat test.py
import importlib
importlib.util.spec_from_file_location('foo', 'bar')

[ec2-user@ip-172-31-21-156 ~]$ python3 test.py
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    importlib.util.spec_from_file_location('foo', 'bar')
AttributeError: module 'importlib' has no attribute 'util'

[ec2-user@ip-172-31-21-156 ~]$ python3 -m debugpy --listen localhost:5678 test.py

```

**Comment by gramster** [comment]
This might be expected behavior (and I suspect is probably an issue for https://github.com/fabioz/PyDev.Debugger/, rather than debugpy). I'd like to understand why it concerns you so we can tell whether this is a curiosity, an annoyance, or a showstopper.

**Comment by gramster** [comment]
Thanks for checking pdb. On the one hand it's good to know its not just us, but on the other hand I agree that its not great that code that passes pytest fails in production. Tagging @brettcannon as he knows much more than me about the details of how Python's imports work; may be interesting to him and perhaps he can shed some light on this, and also @fabioz may have ideas.

**Comment by andreihes** [comment]
@gramster thank you for paying attention however it looks like my fault to call this a bug. It looks like the difference between executing a script and executing a module as a script: https://www.python.org/dev/peps/pep-0338/

As far as I see `-m` imports some modules automatically. This actually doesn't look obvious though:
```
PS C:\Temp> cat .\test.py
import sys
if 'importlib.util' in sys.modules.keys():
  print('Yes')
else:
  print('No')

PS C:\Temp> python .\test.py
No

PS C:\Temp> python -m test
Yes

PS C:\Temp> python
Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by brettcannon** [comment]
@andreihes correct, `-m` imports more modules than if you didn't use it as `-m` uses the [`runpy` module](https://docs.python.org/3/library/runpy.html#module-runpy) as its implementation. And if that code imports `importlib.util` then that would let you get away with only `import importlib` to get at `importlib.util`.

Because [`importlib.util` is a submodule](https://docs.python.org/3/library/importlib.html#module-importlib.util) of the `importlib` package, you should always import it via either `import importlib.util` or `from importlib import util`.
