### ISSUE TITLE
Allow to debug python code running within a container that itself runs on cloud infrastructure with limited connectivity options

### ISSUE THREAD

**Issue by jschaeck** [microsoft/debugpy#852]
Hi, 

I am trying to solve this scenario.

I want to debug python code from my local machine that is running in a container in a cloud infra with limited connectivity options.
For example, there is no ssh allowed and also no container exec or port forwarding.

I can however define routes like https://infradomain.com/route/containers/mycontainer.

Looking at the doc, I can see that it is possible to define a host but not a uri, or a path extension in addition to the host.

So it seems this scenario is not supported.

Is this something that you think would make sense to support ?

**Comment by int19h** [comment]
We use TCP as a transport for our DAP connections, so endpoints can't be mapped to HTTP URLs. However, if you can run arbitrary code on both ends, you may be able to use a websocket tunnel such as https://github.com/erebe/wstunnel.
