### ISSUE TITLE
Latest IPython (8.1.0) doesn't support stepInto correctly with 1.5.1

### ISSUE THREAD

**Issue by rchiodo** [microsoft/debugpy#854]
## Environment data

- debugpy version: 1.5.1
- OS and version: Windows 10
- Python version (& distribution if applicable, e.g. Anaconda): 3.10
- Using VS Code or Visual Studio: VS code

## Actual behavior

Create a notebook with cell with a number of lines:

![image](https://user-images.githubusercontent.com/19672699/155815764-f76a45af-955d-4e2d-919a-db5236f375a5.png)

Put a breakpoint on the first line
Debug the cell
Step into

Step into gets stuck on the first line.

Run by line (another way we support debugging) 
![image](https://user-images.githubusercontent.com/19672699/155815851-5403dded-b8a2-4d8e-b39e-f72dff4bf607.png)
also behaves strangely. It can't step through the function.

## Expected  behavior

Stepping works

@fabioz I believe this was caused by your recent change to IPython? Do we need a newer version of Debugpy to handle that change?

**Comment by rchiodo** [comment]
Seems like if there's a breakpoint on the first line, every step into will alternate between that line and the actual line to step into.

**Comment by int19h** [comment]
It sounds like https://github.com/microsoft/debugpy/pull/851 was the fix for this?

**Comment by rchiodo** [comment]
I don't think so? At least I cloned debugpy and copied it into my site packages. I'm still getting the problem.

**Comment by rchiodo** [comment]
Maybe that didn't work. It looks like I don't have the latest changes for some reason.

**Comment by rchiodo** [comment]
No even with the latest changes, still repros.

**Comment by fabioz** [comment]
> No even with the latest changes, still repros.

This happens because in Python 3.10 there is always a line event at line 1 and Python itself is making that line event due to the way it's compiled now.

It seems my fix wasn't complete then... This will need another fix in IPython so that besides the new `co_name` the `co_lnotab` is also redone so that this spurious line event isn't done.

**Comment by fabioz** [comment]
Actually, this didn't need a change in `IPython` again (the debugger already had something to ignore spurious lines like this for `<module>`, so, I've extended it to handle the new `<cell` pattern for `co_name` in `IPython`).

**Comment by rchiodo** [comment]
@fabioz do you know when debugpy might issue a new release? Otherwise debugging is broken in VS code with 1.5.1.

**Comment by int19h** [comment]
We'll do a release this week.
