### ISSUE TITLE
Shell expansion is not working in "args"

### ISSUE THREAD

**Issue by llabusch93** [microsoft/debugpy#86]
## Environment data

Version: 1.43.1
Commit: fe22a9645b44368865c0ba92e2fb881ff1afce94
Date: 2020-03-18T07:17:38.324Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.5.8-1-MANJARO

## Expected behaviour

On launch of a run configuration, environment variable calls like $(XXX) or ${XXX} defined in the args section are escaped by putting it between quotation marks.

So if for instance `--arg-xyz=$(XXX)` is put into the args section and should evaluate into 

`--arg-xyz=WHATEVER_IS_THE_OUTPUT_OF_THE_CALL`

## Actual behaviour

`--arg-xyz=$(XXX)` is evaluated to `--arg-xyz="$(XXX)"` what causes the python program launch to fail.

## Steps to reproduce:

Actually I don't know, I used this configuration since months and today it did stop working by some kind of escaping these evaluations by putting it just into the quotation marks.

So the launch.json config:

```
{
            "name": "Odoo",
            "type": "python",
            "request": "launch",
            "program": "/odoo/odoo-bin",
            "args": [
                "--config",
                "/workspace/.devcontainer/etc/odoo.conf",
                "--addons-path",
                "$(gen_addons_path -d /addons)",       <<<<< THIS IS EVALUATED WRONG!
                "--load",
                "base,web,base_test_db",
                "--dev=xml,qweb",      
            ],
            "console": "integratedTerminal",
            "justMyCode": false
        }
```

will result in this actual call of the program:

```
env DEBUGPY_LAUNCHER_PORT=40595 /usr/bin/python3 /var/lib/odoo/.vscode-server/extensions/ms-python.python-2020.3.69010/pythonFiles/lib/python/debugpy/wheels/debugpy/launcher /odoo/odoo-bin --config /workspace/.devcontainer/etc/odoo.conf --addons-path "$(gen_addons_path -d /addons)" --load base,web,base_test_db --dev=xml,qweb 
Usage: odoo-bin [options]

odoo-bin: error: option --addons-path: no such directory: '$(gen_addons_path -d /addons)'
```

As you see here, $(gen_addons_path -d /addons) is not evaluated, but just put in a string.

I would be very grateful for any hints to get this working again...

Thanks in advance!

**Comment by int19h** [comment]
The proper fix is for launcher to not look at JSON for "args", and use its own `sys.argv` instead, so that results of shell expansion are propagated. The code in the adapter that generates the launcher command line should also be checked to ensure that it correctly passes and escapes everything - it might be making some shortcuts, since it was purely decorative before.

There might also be some interplay with "cwd" - we don't parse this in the adapter currently, but instead let the launcher handle it. This would mean that it's not in effect for glob and subshell, potentially producing wrong results.

**Comment by karthiknadig** [comment]
You have to add this to the user settings.json, to switch to the old debugger:
![image](https://user-images.githubusercontent.com/3840081/77391981-37902f80-6d57-11ea-93b1-0cb234836876.png)
```js
    "python.experiments.optOutFrom": [
        "PtvsdWheels37 - experiment"
    ],
```

**Comment by llabusch93** [comment]
Hello @int19h and @karthiknadig 

thanks for that incredibly fast answer. Putting ```"python.experiments.optOutFrom": [
        "PtvsdWheels37 - experiment"
    ],``` in the settings did solve the issue like a charm, my args are now evaluated again.

Great respect of solving an issue under 24h in such a huge project, that's support on the edge!

A little hint for those who use remote container development as I do:

In that case you have to put the opt out setting in the **container** json config. Best practice would be to put in directly in the `devcontainer.json` and rebuild the container.

@int19h so as I got your explanation you are currently tweaking that part of the new debugger and will "solve" this issue to have the evaluation of extended shell expressions built in? Means I can at some point in time remove this opt out?

Again thanks a lot for that great software and support!

**Comment by int19h** [comment]
Yes. Since this is a regression, and the quoting rules in VSCode are intended to allow shell expansion, I'm treating it as a bug. I'm going to reopen this issue to keep track of the related work.

**Comment by int19h** [comment]
It looks like https://github.com/microsoft/vscode/issues/98471 regressed this on VSCode side. Need to clarify if this is the intended behavior.
