### ISSUE TITLE
python -m debugpy --wait-for-client … doesn't honor (some) breakpoints with pytest-cov

### ISSUE THREAD

**Issue by posita** [microsoft/debugpy#863]
I discovered this while trying to reproduce #165.

## Environment data

- debugpy version: 1.5.1
- OS and version: OS X and Linux (various)
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.9.6 and 3.10.2
- Using VS Code or Visual Studio: 

```
Version: 1.64.2 (Universal)
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:00:58.347Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0
```

## Steps to reproduce:
1. Set breakpoint in VSCode
2. `python -m debugpy --listen 0.0.0.0:5678 --wait-for-client -m pytest …`
3. Connect to `pytest` process and verify breakpoint is hit
4. Continue
5. `python -m debugpy --listen 0.0.0.0:5678 --wait-for-client -m pytest --cov … …`
6. Connect to `pytest` process
7. Note that breakpoint is not hit this time

You _**can**_ trigger the debugger by placing a `breakpoint()` statement somewhere, after which other breakpoints will work, even with `--cov`.

I'll have a repository up soon that will reproduce this. (Should I call that a repo repo?)

**Comment by posita** [comment]
[posita/debugpy-863](https://github.com/posita/debugpy-863) should illustrate this well. I can reproduce locally on OS X and in the provided container.

``` sh
% git clone https://github.com/posita/debugpy-863.git
% cd debugpy-863
% code .  # opens a new window
```

Open the workspace in a container (the `Remote - Container` extension is needed).

Once it starts up, open `spam/ham.py` and set a breakpoint [here](https://github.com/posita/debugpy-863/blob/0d438569f1c93fe8a244a8118b380749b9da0a8e/spam/ham.py#L6).

Open a terminal in VSCode and do:

``` sh
[root@3981af7673fc debugpy-863]# ./run-without-cov.sh 
+ exec python -m debugpy --listen 0.0.0.0:5678 --wait-for-client -m pytest
```

Execution will pause. Run the `localhost remote` debugger. In the terminal, you'll see:

``` sh
======================================= test session starts =======================================
platform linux -- Python 3.9.6, pytest-7.0.1, pluggy-1.0.0
rootdir: /workspaces/debugpy-863
plugins: cov-3.0.0
collected 1 item                                                                                  

tests/test_ham.py 
```

That will hang, and you should hit your breakpoint. Continue execution, and your test should finish. Now run:

``` sh
[root@3981af7673fc debugpy-863]# ./run-with-cov.sh 
+++ dirname ./run-with-cov.sh
++ cd .
++ pwd
+ exec /workspaces/debugpy-863/run-without-cov.sh --cov spam
+ exec python -m debugpy --listen 0.0.0.0:5678 --wait-for-client -m pytest --cov spam
```

Execution will pause again. Run the `localhost remote` debugger again. Your breakpoint will _**not**_ be hit, and the test will finish without interruption.

Now uncomment [this line](https://github.com/posita/debugpy-863/blob/0d438569f1c93fe8a244a8118b380749b9da0a8e/spam/ham.py#L2) and run `./run-with-cov.sh` again. Your newly-uncommented `breakpoint()` statement will be honored, but so will your prior breakpoint!

**Comment by fabioz** [comment]
This is expected. Coverage uses (and overrides) the tracing that's used in the debugger.

Basically, it's not possible to run a debugger and code-coverage at the same time...

**Comment by posita** [comment]
Is this prominently documented somewhere? Neither https://code.visualstudio.com/docs/python/debugging nor https://github.com/microsoft/debugpy makes any mention of this, and it took me quite a but of time to figure out what was going on.

Better yet, can this be detected when running `debugpy`? Is it possible to surface a warning to the user at runtime?

**Comment by fabioz** [comment]
The problem is that coverage uses a c-level tracer (debugpy has provisions for dealing with warning when the tracing is set from Python, but there's no hook we can add to know that it'd be replaced from c).

Unfortunately the API in Python makes it hard for a tool to know that it was disabled by another tool :(

From the debugger angle, this could be fixed at coverage (it could check if `sys.gettrace()` is set and warn that it'd disable the previous tracer prior to registering its own).
