### ISSUE TITLE
Can't debug python threads in VSCode

### ISSUE THREAD

**Issue by zmarwig** [microsoft/debugpy#874]
Issue Type: <b>Bug</b>

I can't debug a python thread. It's something on my system, but even after a clean install of vscode, I am running into a issue where python will not break in the thread function and the call stack is not showing threads. 

Extension version: 2022.2.1924087327
VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Gold 6128 CPU @ 3.40GHz (24 x 3392)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|127.65GB (83.63GB free)|
|Process Argv|--crash-reporter-id 7e6265a5-cdc2-4f4c-9758-61742f2ee9eb|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30450902
vscscmwlcmc:30438804
vscgsvidc:30447482
pynewfile477cf:30450039

```

</details>

Here is a image of what I am seeing in vscode. 

![threadMissingInCallstack](https://user-images.githubusercontent.com/101901886/159076124-8fb60377-ae89-46eb-9ed1-6f6f3760609d.PNG)

**Comment by fabioz** [comment]
If you un-comment the `x.join()` and just leave the breakpoint inside the `thread_function` doesn't it work?

i.e.: the way things are setup in your example showing just one thread is possible -- keep in mind that when the debugger hits a breakpoint it will stop all threads (which is why it never gets to that breakpoint inside the other thread -- and if the thread hasn't reached user code it's possible that it's not really reported depending on racing conditions which are expected in this situation).

**Comment by zmarwig** [comment]
I reimaged my pc. Works now. I Likely had a bad python or a bad variable somewhere :( Thanks for trying to help me out @fabioz :)

**Comment by MikeWise2718** [comment]
I am getting this now - no threads window and just displaying <module>. It was working correctly just like an hour ago and I didn't change any settings - that I am aware of at least.

This is maybe some kind of bug - and I need to fix it.

**Comment by rchiodo** [comment]
@MikeWise2718, I recommend opening a new issue. There may be a change in VS code itself causing the problem (which would explain why it suddenly happened).
