### ISSUE TITLE
Debugger on VS Code is not working on Python with Output: DAP Server launched with command: conda run -n MyEnvironment --no-capture-output

### ISSUE THREAD

**Issue by mmhammad** [microsoft/debugpy#885]
## Environment data

- debugpy version: 1.5.1
- OS and version: Windows 10 Pro
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.9.7 | Anaconda Prompt (Miniconda3) 
- Using VS Code or Visual Studio: VS Code

## Actual behavior
`DAP Server launched with command: conda run -n testenv --no-capture-output --live-stream python c:\Users\user.name\.vscode\extensions\ms-python.python-2022.4.0\pythonFiles\lib\python\debugpy\adapter`

![Error](https://user-images.githubusercontent.com/102912710/161435368-960cbac5-4203-4e36-b53d-98beb4f83864.PNG)
![image](https://user-images.githubusercontent.com/102912710/161435398-3d1bacfa-0a12-4c21-af3c-e132cfeb52f7.png)

## Expected  behavior
It supposed to work normal and stop at the breakpoint.

## Steps to reproduce:
I am using the Debugger on VS Code since a while for debugging Python scripts and it always worked fine. Yesterday I tried to work on some scripts written on C-Language and debugging them .. Now the Debugger on VS Code is not working on the Python scripts.

**Comment by fabioz** [comment]
I think there were some changes in the extension regarding running with conda in the latest version (and this appears related).

@karthiknadig should this be moved to `vscode-python`?

**Comment by mmhammad** [comment]
After trying several options, the problem was only solved by uninstalling VSCode completely and starting again from a new one.
