### ISSUE TITLE
Breakpoints not hit when run from embeddable Python

### ISSUE THREAD

**Issue by angelo-peronio** [microsoft/debugpy#890]
## Environment data

- debugpy version: 1.6.0
- OS and version: Microsoft Windows 10 Pro 10.0.19044
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.10.4 ([Windows installer 64-bit](https://docs.python.org/3/using/windows.html#the-full-installer) + [Windows embeddable package 64-bit](https://docs.python.org/3/using/windows.html#the-embeddable-package))
- Using VS Code or Visual Studio: VS Code

## Actual behavior

When starting a debugpy server from a module installed within the [embeddable Python](https://docs.python.org/3/using/windows.html#the-embeddable-package) distribution, breakpoints are not hit. If instead the embeddable Python runs the same code but located outside its folder, breakpoints are hit as expected.

## Expected behavior

**Short answer:** breakpoints are hit in both cases.
**Long answer:** I am not sure what it is reasonable to expect. On one side:

- I am somehow stretching the possibilities of the embeddable Python,
- The embeddable Python includes the standard library as a zipped archive of pre-compiled `.pyc` files, and I suspect this could be a problem for debugpy – see warning below.

On the other side, in certain situations debugpy works as expected, as shown below.

**Question:** is it possible to use debugpy with the embeddable Python?

## My actual goal

I have a C++ application embedding the Python interpreter. This application ships with the embeddable Python, and my Python module installed within. I would like to use debugpy in this configuration.

## Steps to reproduce

Here PowerShell is used.

1. Download and expand the embeddable Python

    ```PowerShell
    Invoke-WebRequest https://www.python.org/ftp/python/3.10.4/python-3.10.4-embed-amd64.zip -OutFile python-embed.zip

    Expand-Archive python-embed.zip python-embed
    ```

3. Uncomment `import site` in `python-embed\python310._pth`

    ```PowerShell
    (Get-Content python-embed\python310._pth).replace('#import site', 'import site') | Set-Content python-embed\python310._pth
    ```

4. Use pip from the "system" Python to install debugpy in the embeddable Python, which ships without pip.

    ```PowerShell
    py -m pip install debugpy --target python-embed\Lib\site-packages
    ```

5. Place the following minimal reproducible example in a `mre.py` file next to the `python-embed` folder.

    ```python
    import debugpy

    if __name__ == "__main__":
        print("Executing " + __file__)
        debugpy.listen(address=("localhost", 5678))
        print("Waiting for a debug client to attach...")
        debugpy.wait_for_client()
        breakpoint()
        print("Finished.")
    ```

6. Run the MRE and connect the VS Code debugger using *Python: Remote Attach* debug configuration.

    ```PowerShell
    .\python-embed\python.exe mre.py
    ```

    Output:

    ```text
    Executing N:\debugpy-issue\mre.py
    0.02s - Debugger warning: The os.path.realpath.__code__.co_filename (ntpath.py)
    0.00s - is not absolute, which may make the debugger miss breakpoints.
    0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
    Waiting for a debug client to attach...
    ```

    Within the VS Code debugger the execution is now paused after `breakpoint()`, warning notwithstanding. This is the "correct" behavior.

7. Copy the MRE inside the `site-packages` folder of the embeddable Python, run it from there, and connect the VS Code debugger.

    ```PowerShell
    New-Item python-embed\Lib\site-packages\mre -ItemType Directory

    Copy-Item mre.py python-embed\Lib\site-packages\mre\

    .\python-embed\python.exe python-embed\Lib\site-packages\mre\mre.py
    ```

    Output:

    ```text
    Executing N:\debugpy-issue\python-embed\Lib\site-packages\mre\mre.py
    0.00s - Debugger warning: The os.path.realpath.__code__.co_filename (ntpath.py)
    0.00s - is not absolute, which may make the debugger miss breakpoints.
    0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
    Waiting for a debug client to attach...
    Finished.
    ```

    The execution pauses until the debugger is attached, but afterwards the breakpoint is skipped. This is the "wrong" behaviour.

**Comment by fabioz** [comment]
Can you provide the logs for this?

i.e.: set the following environment variables:
```
PYDEVD_DEBUG=True
PYDEVD_DEBUG_FILE=C:\logs\pydevd.log
```

Ensure that C:\logs directory exists. Note that this may generate more than one `pydevd.<pid>.log` file.

**Comment by int19h** [comment]
Side note: you can also use `DEBUGPY_LOG_DIR` to set both of the above at once:
https://github.com/microsoft/debugpy/blob/2ac9538dd5d59d0bb582d445e4a6b87663cfbab4/src/debugpy/_vendored/force_pydevd.py#L23-L26

**Comment by angelo-peronio** [comment]
I am attaching the logs for the ["correct"](https://github.com/microsoft/debugpy/files/8449713/logs-5-correct.zip) and the ["wrong"](https://github.com/microsoft/debugpy/files/8449718/logs-6-wrong.zip) behaviors [I observed](https://github.com/microsoft/debugpy/issues/890#issue-1196178534).

Side note: calling

```python
debugpy.log_to(log_folder)
```

was not enough to collect also the pydevd logs. Instead, I needed the following:

```python
os.environ["DEBUGPY_LOG_DIR"] = log_folder
debugpy.log_to(log_folder)
```

This behavior seems odd to me. Is it expected? Would you like me to open another issue about it?

**Comment by int19h** [comment]
The main reason is that pydevd logging starts very early on, so in cases like attach where debugpy doesn't control process startup (and can ensure that env vars are set correctly before anything checks for them), env vars were the only way to enable it.

I'm not sure that still holds, however - @fabioz, is there a reliable way to enable pydevd logging _after_ importing pydevd, now?

**Comment by fabioz** [comment]
> I'm not sure that still holds, however - @fabioz, is there a reliable way to enable pydevd logging _after_ importing pydevd, now?

Sort of -- there's an internal API for that (`_pydev_bundle.pydev_log.log_context`), but it receives a stream and works as a context manager (mostly for testing).

It should be reasonably simple to create a public API to set the logging level/filename if needed though.

**Comment by fabioz** [comment]
Analyzing the logs there are some things noteworthy:

1. there are no logs referring to `setBreakpoints` at all (@angelo-peronio, maybe you didn't create a breakpoint when you ran this scenario -- otherwise this would imply that VSCode itself has some issue as the breakpoints weren't sent at all).

2. You're copying things to `N:\debugpy-issue\python-embed\Lib\site-packages` -- in this case you **must** set `"justMyCode": false` in your configuration (otherwise it's expected that breakpoints won't be hit).

3. There's an entry to `pathMappings`:
```
"pathMappings": [
    {
        "localRoot": "N:\\debugpy-issue",
        "remoteRoot": "."
    }
],
```

In general you should not set any path mappings unless you're actually running in a different machine or if you have some pre-compiled pyc that was created in a different place that you want to translate. Also, setting `remoteRoot` to `.` will make a translation from `N:\\debugpy-issue` to the `cwd`, which I don't think makes sense in this scenario (so, you can just remove that).

4. Related to the warning saying that `Debugger warning: The os.path.realpath.__code__.co_filename (ntpath.py) is not absolute`, I believe you can mostly ignore it in this particular case as this is how the embeddable Python seems to work (the actual fix would be having the `.py` files in place instead of `.pyc` files or generate those `pyc` files in your machine so that you have absolute paths for them -- the debugger does work around that, so, that's mostly a warning for you to be aware that sometimes the debugger may make the wrong thing for such files given that it needs to search the PYTHONPATH for a match instead of being able to just directly get the file location for some frame).

**Comment by angelo-peronio** [comment]
@fabioz, thank you for taking the time to look into this. About your points:

1.  I am not creating a breakpoint through the VS Code user interface –  did you mean that? –. Instead, I am calling `breakpoint()`.
2. That was the problem! In hindsight, it is not surprising at all. I went with VS Code defaults without paying too much attention. My bad.

Right now the minimal reproducible example I put together for this issue works flawlessly. The actual "production" code unfortunately not yet. I will look into it some more, and possibly open another issue.
