### ISSUE TITLE
bug: Can't  use the debug of python-extention 

### ISSUE THREAD

**Issue by JWleo** [microsoft/debugpy#892]
os:win10

VSCode version:
![f49069a81704b9d4f802269b34002b4](https://user-images.githubusercontent.com/32316654/162393105-c1451b27-89f0-44cd-af1e-75fb5b5c209b.jpg)

Python extenion version:v2022.4.1

Problem just like below:
![7161750214dcd8ac08ebb98342b8734](https://user-images.githubusercontent.com/32316654/162393878-a35a45ae-2364-415b-ae6c-4a57e97855e6.png)

ps:The python v2022.2.19 has no this.

**Comment by int19h** [comment]
We don't support Python 2.7 anymore, sorry. You'll have to use an older version of the extension to work with it.
