### ISSUE TITLE
ImportError: No module named _thread

### ISSUE THREAD

**Issue by ChenghaoZHU** [microsoft/debugpy#903]
# launch file
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal"
        },
        {
            "name": "Python: clover2",
            "type": "python",
            "request": "launch",
            "program": "${workspaceFolder}/main.py",
            "console": "integratedTerminal"
        }
    ]
}
```
# extension version
<img width="379" alt="image" src="https://user-images.githubusercontent.com/15712697/162924332-11dc3af4-3518-4cf4-8745-7a1379739715.png">
with the latest two version, I press F5 to start to debug, I will get "ImportError: No module named _thread"
<img width="750" alt="image" src="https://user-images.githubusercontent.com/15712697/162924523-325bc896-ad87-4250-8ab8-8dc7d24a35f7.png">
however, the older versions can work properly.

does anyone have any ideas ? Thanks.

**Comment by fabioz** [comment]
Python 2.7 is no longer supported. See: https://github.com/microsoft/debugpy/issues/884 for details.

**Comment by ChenghaoZHU** [comment]
> #884

thanks. a little disappointed about this. I use python2 for a long time.
