### ISSUE TITLE
Debugpy subprocess out-lives process being debugged

### ISSUE THREAD

**Issue by christopherhesse** [microsoft/debugpy#905]
## Environment data

- debugpy version: 1.5.1
- OS and version: Ubuntu 20.04.3 LTS
- Python version (& distribution if applicable, e.g. Anaconda): 3.9.9
- Using VS Code or Visual Studio: VSCode

## Actual behavior

`debugpy` fails to listen

```
      File "/root/.pyenv/versions/3.9.9/lib/python3.9/site-packages/debugpy/__init__.py", line 113, in listen                                                                                         
        return api.listen(address)                                                                                                                                                                    
      File "/root/.pyenv/versions/3.9.9/lib/python3.9/site-packages/debugpy/server/api.py", line 143, in debug                                                                                        
        log.reraise_exception("{0}() failed:", func.__name__, level="info")                                                                                                                                 File "/root/.pyenv/versions/3.9.9/lib/python3.9/site-packages/debugpy/server/api.py", line 141, in debug                                                                                        
        return func(address, settrace_kwargs, **kwargs)                                                                                                                                               
      File "/root/.pyenv/versions/3.9.9/lib/python3.9/site-packages/debugpy/server/api.py", line 243, in listen                                                                                       
        raise RuntimeError(str(endpoints["error"]))                                                                                                                                                   
    RuntimeError: Can't listen for client connections: [Errno 98] Address already in use  
```

## Expected  behavior

`debugpy` should listen on the port

## Steps to reproduce:

I don't have a reliable reproduction case for this, it just happens to me once a day or so.  This appears to be due to the parent process dying (perhaps killed) and then the debugpy process still running.  This can be fixed by manually killing the debugpy process, but it would be much better if the debugpy process killed itself.  Example process (re-parented to process 1):

`root     41149     1  0 18:24 ?        00:00:00 /root/.pyenv/versions/3.9.9/bin/python /root/.pyenv/versions/3.9.9/lib/python3.9/site-packages/debugpy/adapter --for-server 46771 --host 127.0.0.1 --port 5678 --server-access-token ...`

Since this is linux, it should be possible to have the process get a SIGKILL when the parent process dies: https://gist.github.com/evansd/2346614

**Comment by int19h** [comment]
The adapter already has some logic in it to exit when the corresponding server dies, although it is triggered by a socket timeout. 

Is there anything unusual about the scenario - e.g. multiple processes being debugged? I wonder if there's some issue with the existing check, or it's just a matter of running it fast enough that the timeout doesn't kick in.

**Comment by christopherhesse** [comment]
This adapter was sitting around for multiple minutes.  The scenario is some complicated python process with threads, subprocesses, etc, so reproducing this would be hard if the issue is triggered by some particular part of the setup here.  If I see this again, is there a way to tell what the adapter is doing?  How long should it take for a timeout?

**Comment by int19h** [comment]
It should be 15 seconds at most, so this would seem to be a bug in the existing logic. 

You could enable debugpy logging to see what's going on - add `"logToFile": true` in launch.json, or set `DEBUGPY_LOG_DIR` env var if you want to control the destination. The log files it creates have PIDs in the name, so they'll accumulate across runs. The most interesting one would be `debugpy.adapter*.log`, which would show what the session orchestration looked like from the adapter perspective, and why it thinks it shouldn't exit yet.

**Comment by christopherhesse** [comment]
Is this process created after I connect via vscode to the running remote process?  Otherwise I'm not sure how debugpy on the remote machine would see the value in `launch.json`.

**Comment by int19h** [comment]
Yeah, launch.json won't work if you're attaching - you'll need to set `DEBUGPY_LOG_DIR` on the remote side before running the process you're attaching to.

If you're using the debugpy API rather than the CLI, you can also do `debugpy.log_to("...")`.

**Comment by int19h** [comment]
Please re-open with more details as outlined above if this issue still occurs.
