### ISSUE TITLE
Python initialisation issues with django-request - no issue with legacy debugger

### ISSUE THREAD

**Issue by billyquith** [microsoft/debugpy#914]
## Environment data

- debugpy version: 1.2.0
- OS and version: Windows 10 20H2 19042.1586
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.9 Python.org Win64
- Using VS Code or Visual Studio: VS2019.

## Actual behavior

I start the app and get the behaviour on the [issue logged with Django-request](https://github.com/django-request/django-request/issues/244#issuecomment-1102923367). I get Python initialisation problems. If I run the legacy debugger I don't get this issue.

Here is a log of the debug adapter: [DebugAdaper.log.txt](https://github.com/microsoft/debugpy/files/8515494/DebugAdaper.log.txt)

## Expected  behavior

I expect to hit F5 to start the debugger and Django runserver is executed

## Steps to reproduce:
1. create a Django app. 
2. Install django-request and configure.
3. `python manage.py runserver` from the command-line works without error.
4. Run the same app in the VS2019 debugger and you get the above errors.

**Comment by fabioz** [comment]
As a note, `debugpy version: 1.2.0` seems like a rather old version at this point. Is it possible to get a newer one in the `VS` scenario?

**Comment by billyquith** [comment]
> As a note, `debugpy version: 1.2.0` seems like a rather old version at this point. Is it possible to get a newer one in the `VS` scenario?

Sure. The 1.2.0 is from the MS2019 Pro install in `C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\Extensions\Microsoft\Python\Core\debugpy`.

**Comment by billyquith** [comment]
I updated VS2019 via Help > Check for updates... and it hasn't updated debugpy. _version.py still says 1.2.0.

```
Microsoft Visual Studio Professional 2019 Version 16.11.13
VisualStudio.16.Release/16.11.13+32413.511 Microsoft .NET Framework Version 4.8.04084

Installed Version: Professional

Python   16.11.21196.2

Python - Django support   16.11.21196.2

Python - Profiling support   16.11.21196.2
```

**Comment by billyquith** [comment]
I've copied debugpy 1.6.0 over 1.2.0.

**Comment by billyquith** [comment]
I think that has fixed one issue. I don't get the [`SERVER_NAME` not found issue](https://github.com/django-request/django-request/issues/244#issuecomment-1112144666). However, I still get the "'super' object has no attribute '__getattr__'" issue, which I don't get when I run Django from the command-line via runserver. 

I get different behaviours from using different launching methods:

- `python manage.py runserver` works without error.
- VS2019 Debug > Start without Debugging... works without error.
- VS2019 Debug > Start Debugging... I get the error linked above.

**Comment by fabioz** [comment]
Can you provide the logs when you run?

i.e.: Add following environment variables to your launch:

PTVSD_LOG_DIR=C:\logs
PYDEVD_DEBUG=True
PYDEVD_DEBUG_FILE=C:\logs\pydevd.log

Ensure that C:\logs directory exists. Note that this may generate several ptvsd-.log files. When the issue occurs, stop debugging and share the latest ptvsd-.log and pydevd.log files. Remove any personal information from the log files.

**Comment by int19h** [comment]
Please re-open with more details as outlined above if this issue still occurs.
