### ISSUE TITLE
debug console causes vscode to be unresponsive

### ISSUE THREAD

**Issue by skamansam** [microsoft/debugpy#916]
Issue Type: <b>Performance Issue</b>

# Behaviour
When debugging django pytests, there can be a lot of output when a test fails. While the lengthy output is printed to the debug console, VSCode is nearly unresponsive and takes (sometimes 10+) minutes to fully render. When I close the debug panel, VSCode is still very slow, but at least it's usable.

## Expected vs. Actual
I expect the output to be rendered as fast as with the normal console. I expect the editor to be usable while this is happening.
In reality, VSCode is nearly unresponsive, and the output hangs occassionally.

XXX

## Steps to reproduce:
1. Quickstart: clone the repo https://github.com/skamansam/vscode-pytes-debug-issue and follow the instructions in the  README
1. Start a debug session for  a test with a lot of debugging information, > 2000 lines of debug output. 
1. make sure the test fails.

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.7
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Pyenv
-   Value of the `python.languageServer` setting: Jedi

<details>

<summary>User Settings</summary>

<p>

```

defaultLS: {"defaultLSType":"Pylance"}

downloadLanguageServer: true

envFile: "<placeholder>"

venvPath: "<placeholder>"

venvFolders: "<placeholder>"

condaPath: "<placeholder>"

pipenvPath: "<placeholder>"

poetryPath: "<placeholder>"

languageServer: "Jedi"

linting
• enabled: true
• cwd: "<placeholder>"
• Flake8Args: "<placeholder>"
• flake8Enabled: true
• flake8Path: "<placeholder>"
• lintOnSave: true
• banditArgs: "<placeholder>"
• banditEnabled: false
• banditPath: "<placeholder>"
• mypyArgs: "<placeholder>"
• mypyEnabled: true
• mypyPath: "<placeholder>"
• pycodestyleArgs: "<placeholder>"
• pycodestyleEnabled: false
• pycodestylePath: "<placeholder>"
• prospectorArgs: "<placeholder>"
• prospectorEnabled: false
• prospectorPath: "<placeholder>"
• pydocstyleArgs: "<placeholder>"
• pydocstyleEnabled: false
• pydocstylePath: "<placeholder>"
• pylamaArgs: "<placeholder>"
• pylamaEnabled: false
• pylamaPath: "<placeholder>"
• pylintArgs: "<placeholder>"
• pylintPath: "<placeholder>"

sortImports
• args: "<placeholder>"
• path: "<placeholder>"

formatting
• autopep8Args: "<placeholder>"
• autopep8Path: "<placeholder>"
• provider: "black"
• blackArgs: "<placeholder>"
• blackPath: "<placeholder>"
• yapfArgs: "<placeholder>"
• yapfPath: "<placeholder>"

testing
• cwd: "<placeholder>"
• debugPort: 3000
• nosetestArgs: "<placeholder>"
• nosetestsEnabled: undefined
• nosetestPath: "<placeholder>"
• promptToConfigure: true
• pytestArgs: "<placeholder>"
• pytestEnabled: true
• pytestPath: "<placeholder>"
• unittestArgs: "<placeholder>"
• unittestEnabled: false
• autoTestDiscoverOnSaveEnabled: true

terminal
• activateEnvironment: true
• executeInFileDir: "<placeholder>"
• launchArgs: "<placeholder>"

experiments
• enabled: true
• optInto: []
• optOutFrom: []

tensorBoard
• logDirectory: "<placeholder>"

```

</p>
</details>

Extension version: 2022.4.1
VS Code version: Code - Insiders 1.67.0-insider (e7c6ad74aff28965d0189ca1dd584f5e9829cf06, 2022-04-19T05:17:48.321Z)
OS version: Linux x64 5.16.20-200.fc35.x86_64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|15.47GB (0.29GB free)|
|Process Argv|--unity-launch --crash-reporter-id 02322043-412c-4372-a6fb-f9a7b5e9e83f|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    79	504382	code-insiders main
    0	     0	504395	   zygote
    0	   127	2069365	     gpu-process
    0	     0	2069470	       broker
    0	     0	504397	   zygote
    0	     0	504441	     zygote
    0	    79	3728507	       issue-reporter
    0	    16	504575	   utility-network-service
    0	   349	504593	   window (fixtures.py - api-server - Visual Studio Code - Insiders)
    1	    79	505106	   shared-process
    0	    16	505238	     ptyHost
    0	     0	507970	       /bin/bash --login
    0	     0	508017	       /bin/bash --login
    0	    63	506880	     fileWatcher
    0	     0	3729054	     /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   174	506966	   extensionHost
    0	     0	510458	     /usr/share/code-insiders/code-insiders --ms-enable-electron-run-as-node /home/sam/.vscode-insiders/extensions/redhat.vscode-yaml-1.6.0/dist/languageserver.js --node-ipc --clientProcessId=506966
    0	    32	511653	     /usr/share/code-insiders/code-insiders --ms-enable-electron-run-as-node /home/sam/.vscode-insiders/extensions/googlecloudtools.cloudcode-1.17.2/dist/server/server.js --node-ipc --clientProcessId=506966
    0	    48	511656	     /usr/share/code-insiders/code-insiders --ms-enable-electron-run-as-node /home/sam/.vscode-insiders/extensions/streetsidesoftware.code-spell-checker-2.1.11/packages/_server/dist/main.js --node-ipc --clientProcessId=506966
    0	    63	513415	     /usr/share/code-insiders/code-insiders --ms-enable-electron-run-as-node /usr/share/code-insiders/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=506966
    0	   333	514968	     /home/sam/.pyenv/versions/3.9.7/bin/python /home/sam/.vscode-insiders/extensions/ms-python.python-2022.4.1/pythonFiles/run-jedi-language-server.py
    0	     0	515274	       /home/sam/.pyenv/versions/3.9.7/bin/python /home/sam/.vscode-insiders/extensions/ms-python.python-2022.4.1/pythonFiles/lib/jedilsp/jedi/inference/compiled/subprocess/__main__.py /home/sam/.vscode-insiders/extensions/ms-python.python-2022.4.1/pythonFiles/lib/jedilsp 3.9.7
    0	     0	515704	     /usr/share/code-insiders/code-insiders --ms-enable-electron-run-as-node /home/sam/.vscode-insiders/extensions/ms-azuretools.vscode-docker-1.22.0/dist/dockerfile-language-server-nodejs/lib/server.js --node-ipc --node-ipc --clientProcessId=506966
    0	     0	515723	     /usr/share/code-insiders/code-insiders --ms-enable-electron-run-as-node /home/sam/.vscode-insiders/extensions/ms-azuretools.vscode-docker-1.22.0/dist/compose-language-service/lib/server.js --node-ipc --node-ipc --clientProcessId=506966
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (fixtures.py - api-server - Visual Studio Code - Insiders)
|    Folder (api-server): 12062 files
|      File types: txt(5549) pdf(1711) json(1545) png(929) pyc(337) html(279)
|                  py(256) js(238) vue(159) scss(81)
|      Conf files: dockerfile(4) settings.json(3) package.json(2)
|                  launch.json(1) tasks.json(1) webpack.config.js(1)
|                  jsconfig.json(1)
|      Launch Configs: python(5) cloudcode.kubernetes chrome firefox;
```

</details>

**Comment by karthiknadig** [comment]
Transferred this to `debugpy` for initial investigation.

**Comment by fabioz** [comment]
I started to investigate but I wasn't able to reproduce it on some preliminary investigation.

Can you give some additional info:

1. Are you using the terminal or debug console to see the output?
2. Can you provide your launch configuration?
3. If you don't run as a test and run it directly, does it still happen?

i.e.: something as:

```
COMMON_P = (
    "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod "
    "tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim "
    "veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea "
    "commodo consequat. Duis aute irure dolor in reprehenderit in voluptate "
    "velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint "
    "occaecat cupidatat non proident, sunt in culpa qui officia deserunt "
    "mollit anim id est laborum."
)


number_lines_output = 10000

def func(x):
    for i in range(number_lines_output):
       print(COMMON_P)
    return x + 1

if __name__ == '__main__':
    func(4)
```

**Comment by int19h** [comment]
Given that it slows down the VSCode *UI*, I think it's more likely to be an issue with rendering the text in VSCode itself. If debugpy was the limiting factor, I'd expect to see the printed messages lagging behind the actual output, but the UI being perfectly responsive.

Note also that this is VSCode 1.67.0-insider running on Linux, so it might be specific to that environment.

There's an interesting bug that could be relevant: https://github.com/microsoft/vscode/issues/146737.
