### ISSUE TITLE
remote debugger `pathMappings` issue? is it possible to add more than one mapping?

### ISSUE THREAD

**Issue by gerardosabetta** [microsoft/debugpy#920]
### Discussed in https://github.com/microsoft/vscode-python/discussions/18976

<div type='discussions-op-text'>

<sup>Originally posted by **gerardosabetta** April 21, 2022</sup>
Hi I'm struggling to add more than one thing to the `pathMapping` settings when configuring a remote debugger. 

This how my coworkers have their pycharm set up
![image](https://user-images.githubusercontent.com/55319644/164570232-b1123427-ea49-46d8-ab1b-693cbd27feb5.png)

So I thought the equivalent would be something like this 
![image](https://user-images.githubusercontent.com/55319644/164570499-61922832-0cc4-4d35-b2e3-fdc5412a0ed0.png)

But it's not working as expected, the breakpoint for the file on the right triggered an error saying "api.py does not exist, do you want to create it" and it was created on the path you can see on the left 👇
![image](https://user-images.githubusercontent.com/55319644/164570676-81493dbb-e045-4ebd-9eae-57c68a94fbba.png)

My initial thought was "it seems like you can only do one map" but this can't be the case, pathMappings expects an array. I must be doing something wrong.

Thanks in advance</div>

**Comment by gerardosabetta** [comment]
hey @fabioz thanks for jumping in, if you could take a look at the discussion where this was originaly posted I've had included those logs and a few more. Please let me know if something is missing

**Comment by fabioz** [comment]
@gerardosabetta you only provided partial occurrences of the logs, so, it's not possible to really analyze things completely through the info provided... is it possible for you to provide the full (pydevd) logs and attach them to this issue?

**Comment by fabioz** [comment]
p.s.: you can clean things if needed by changing the name of the files for dummy names... (say A/B/C while trying to keep the structure of the log the same if you have privacy issues).

**Comment by fabioz** [comment]
As a note, the answer to your question is that yes, it's possible to add more than one mapping and I can see that it was applied doing a translation by the log you posted:

```
0.00s - Request for breakpoint in: /home/gera/dev/platform-backend/ai_cloud_foundation/ai_cloud_foundation/ai_cloud/api/phase/api.py line: 26
0.00s - Breakpoint (after path translation) in: /opt/attackiq/firedrill-data/ai_py/firedrill/ai_django/ai_cloud_foundation/ai_cloud/api/phase/api.py line: 26
0.00s - Added breakpoint:/opt/attackiq/firedrill-data/ai_py/firedrill/ai_django/ai_cloud_foundation/ai_cloud/api/phase/api.py - line:26 - func_name:None
```

But there's no indication of anything related to the actual error where it says that `api.py` is not found in the client.

**Comment by int19h** [comment]
Please re-open with more details as outlined above if this issue still occurs.

**Comment by mapa17** [comment]
I was running into similar issues not being able to step library code. Maybe this is known, but it was new to me. The pathMapping in the launch configuration does not seem to be order invariant. Rather it appears that the "inner" folders have to specified first, followed by the outer folders.

In my case, with a typical python project setup having a `.venv` folder in the project workspace and the source folder ending up inside an contianers `app` folder this boils down to.

```json
"pathMappings": [
		{
          "localRoot": "${workspaceFolder}/.venv",
          "remoteRoot": "/app/.venv"
		},
		{
			"localRoot": "${workspaceFolder}/SOURCE_FOLDER",
			"remoteRoot": "/app"
		}
	]
```

Flipping the order of the mapping will fail for the .venv mapping, causing library files to be "missing".
