### ISSUE TITLE
Suppress debug launch command in terminal

### ISSUE THREAD

**Issue by rongxin-liu** [microsoft/debugpy#922]
When launching the python debugger, users would see the launch command persists in the terminal, which is not ideal and irrelevant to the program that the users are trying to debug.

![Screen Shot 2022-04-29 at 13 46 34](https://user-images.githubusercontent.com/10591665/165996852-c8823fe1-89f4-47cb-919b-66e50e9f3f4a.png)

Is it possible to suppress or hide this launch command so it is not shown to the user?

**Comment by fabioz** [comment]
As far as I know, no, that's not possible (unless you don't want to run in the terminal -- i.e.: if you use the `"console": "internalConsole"` then the command won't be shown).

Note that to hide this in the terminal, this would need to be implemented in `vscode` itself (and if available it'd need to be used/adapted in `vscode-python`, so, it's probably out of the scope for `debugpy`...).

**Comment by rongxin-liu** [comment]
Thanks @fabioz , will open an issue with `vscode-python`.
