### ISSUE TITLE
Multi-line "Evaluate in Debug Console" fails to store intermediate variables.

### ISSUE THREAD

**Issue by CmpCtrl** [microsoft/debugpy#932]
Issue Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

When debugging and stopped at a breakpoint inside a function, using `Evaluate in Debug Console` on a multi-line selection executes OK, but fails to store intermediate variables. I expect it to store all of the intermediate variables as if the code were run normally.

## Steps to reproduce:

Set a breakpoint in a function and debug. When stopped at the breakpoint highlight several rows, right-click, and select `Evaluate in Debug Console`. 

In this example you can see that the debugger executed OK but only `f` was stored in the locals. I expect `a` thru `f` to be stored.
![image](https://user-images.githubusercontent.com/90776324/167932225-42b97e81-431b-4700-9b6f-c1f6ed005b4b.png)

Sample script to reproduce:
``` python
import numpy as np


def main():
    """main"""
    a = np.random.rand(100)
    b = np.random.rand(100)
    c = a + b
    if a.any():
        d = np.random.rand(100)
        e = np.random.rand(100)
        f = d + e


if __name__ == "__main__":
    main()
```

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.2
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Venv
-   Value of the `python.languageServer` setting: Pylance

<details>

<summary>User Settings</summary>

<p>

```

defaultLS: {"defaultLSType":"Pylance"}

downloadLanguageServer: true

envFile: "<placeholder>"

venvPath: "<placeholder>"

venvFolders: "<placeholder>"

condaPath: "<placeholder>"

pipenvPath: "<placeholder>"

poetryPath: "<placeholder>"

languageServer: "Pylance"

linting
• enabled: true
• cwd: "<placeholder>"
• Flake8Args: "<placeholder>"
• flake8Enabled: true
• flake8Path: "<placeholder>"
• lintOnSave: true
• banditArgs: "<placeholder>"
• banditEnabled: false
• banditPath: "<placeholder>"
• mypyArgs: "<placeholder>"
• mypyEnabled: false
• mypyPath: "<placeholder>"
• pycodestyleArgs: "<placeholder>"
• pycodestyleEnabled: false
• pycodestylePath: "<placeholder>"
• prospectorArgs: "<placeholder>"
• prospectorEnabled: false
• prospectorPath: "<placeholder>"
• pydocstyleArgs: "<placeholder>"
• pydocstyleEnabled: false
• pydocstylePath: "<placeholder>"
• pylamaArgs: "<placeholder>"
• pylamaEnabled: false
• pylamaPath: "<placeholder>"
• pylintArgs: "<placeholder>"
• pylintPath: "<placeholder>"

sortImports
• args: "<placeholder>"
• path: "<placeholder>"

formatting
• autopep8Args: "<placeholder>"
• autopep8Path: "<placeholder>"
• provider: "black"
• blackArgs: "<placeholder>"
• blackPath: "<placeholder>"
• yapfArgs: "<placeholder>"
• yapfPath: "<placeholder>"

testing
• cwd: "<placeholder>"
• debugPort: 3000
• nosetestArgs: "<placeholder>"
• nosetestsEnabled: undefined
• nosetestPath: "<placeholder>"
• promptToConfigure: true
• pytestArgs: "<placeholder>"
• pytestEnabled: false
• pytestPath: "<placeholder>"
• unittestArgs: "<placeholder>"
• unittestEnabled: false
• autoTestDiscoverOnSaveEnabled: true

terminal
• activateEnvironment: true
• executeInFileDir: "<placeholder>"
• launchArgs: "<placeholder>"

experiments
• enabled: true
• optInto: []
• optOutFrom: []

tensorBoard
• logDirectory: "<placeholder>"

```

</p>
</details>

Extension version: 2022.6.1
VS Code version: Code 1.67.0 (57fd6d0195bb9b9d1b49f6da5db789060795de47, 2022-05-04T12:06:02.889Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.61GB (15.80GB free)|
|Process Argv|--crash-reporter-id e55d3703-d7b2-409d-9ef3-d55e0fc5446e|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by CmpCtrl** [comment]
@fabioz when might this fix make it into a release? The issue is still present with the following versions. 

Let me know if i am missing something. Thanks.

vscode: 1.68.1
python: 2022.9.11661004
vscode-pylance: 2022.6.20

**Comment by int19h** [comment]
There haven't been any debugpy releases since the fix went in, hence why it's not in VSCode yet. We don't have a specific schedule for releases; they happen once enough fixes have been accumulated. But you can keep track on them on the Releases tab in this repo, or on PyPI.

**Comment by fabioz** [comment]
@CmpCtrl not sure about the release timeframe, but you can use the current version in `main` if you'd like by doing the following:

Clone this repo:

```
git clone https://github.com/microsoft/debugpy.git
cd debugpy
pwd
```

Then, in your launch config add:

`"debugAdapterPath": "<pwd path>/src/debugpy/adapter"`
