### ISSUE TITLE
Input from external file doesn't work with Microsoft Python VS Code extension while debugging

### ISSUE THREAD

**Issue by ydmykr** [microsoft/debugpy#933]
According to the document of vsocde,

![image](https://user-images.githubusercontent.com/100815370/168530371-470f2fd3-df35-42e0-9923-b42a3ab0fc36.png)

I can pass the shell redirect syntax (for example, "<" or ">") as arguments.

However, when I use this feature, it doesn't work. The redirect ("<") is automatically escaped (prepended with "\") by the Microsoft's Python extension.

Here is my launch.json and output.

![image](https://user-images.githubusercontent.com/100815370/168530876-06a652df-2cd0-445d-a5c7-e3a5c7882cb7.png)

`cd /workspaces/pyt ; /usr/bin/env /usr/local/bin/python /home/vscode/.vscode-server/extensions/ms-python.python-2022.7.11332232/pythonFiles/lib/python/debugpy/launcher 41587 -- /workspaces/pyt/test.py \< input.txt `

Is Python not supported? Or do I have any mistakes in operation

**Comment by sgrade** [comment]
The same issue is discussed in [#13264](https://github.com/microsoft/vscode-python/issues/13264#issuecomment-1120439271). It would be great to have it solved.

**Comment by fabioz** [comment]
@int19h @karthiknadig given the comments from @int19h at https://github.com/microsoft/vscode/issues/98471#issuecomment-668261519, this doesn't seem to be fixable in `debugpy` nor `vscode-python`.

Do you know if there is an open issue to fix this in `VScode` itself?

It doesn't seem worthy to leave an unfixable issue open in our side... (this one and https://github.com/microsoft/vscode-python/issues/13264 are unfixable as it stands without support from VSCode itself).

**Comment by int19h** [comment]
See https://github.com/microsoft/vscode-python/issues/13264#issuecomment-1133292264

**Comment by int19h** [comment]
The short story is that this was due to https://github.com/microsoft/vscode/issues/148887, which is fixed in VSCode 1.67.2, so you need to update to that.
