### ISSUE TITLE
Cannot remote debug Python through SSH

### ISSUE THREAD

**Issue by nicolalandro** [microsoft/debugpy#936]
Issue Type: <b>Bug</b>

* using [remote-ssh](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh) open a remote project
* configure .vscode/lanuch.json for remote attach
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Remote Attach",
            "type": "python",
            "request": "attach",
            "connect": {
                "host": "localhost",
                "port": 5678
            },
            "pathMappings": [
                {
                    "localRoot": "${workspaceFolder}",
                    "remoteRoot": "."
                }
            ],
            "justMyCode": true
        }
    ]
}
```
* go into port and bind 5678
* run debug a afile with one or many breakpoins
* it  open and close rapidly, it does not show nothing and do not debug.

(the same procedure with localmachine works, with also a local launch.json)

Extension version: 2022.6.2
VS Code version: Code 1.66.1 (8dfae7a5cd50421d10cd99cb873990460525a898, 2022-04-06T14:51:26.173Z)
OS version: Linux x64 5.4.0-104-generic
Restricted Mode: No
Remote OS version: Linux x64 4.10.0-38-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) N4100 CPU @ 1.10GHz (4 x 2288)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.61GB (0.17GB free)|
|Process Argv|--unity-launch --crash-reporter-id 6a381ab9-4a65-473c-8c36-35efc7fd385d|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH: 193.206.183.137|
|OS|Linux x64 4.10.0-38-generic|
|CPUs|AMD Ryzen Threadripper 1900X 8-Core Processor (16 x 3799)|
|Memory (System)|31.36GB (6.54GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217
vscaat:30438848
vsclangdc:30486549

```

</details>

**Comment by int19h** [comment]
Can you clarify what you mean by "go into port and bind 5678"? Does it correspond to `debugpy --listen` /  `debugpy.listen()`, or did you have something else in mind?

Side note: when connecting to local, you shouldn't need "pathMappings" at all.

**Comment by nicolalandro** [comment]
I mean this:

![immagine](https://user-images.githubusercontent.com/18419702/168903875-da21fee7-bd05-46e8-b833-dc435de55557.png)

I also try to run manually (instead of from vscode button) with `python -m debugpy --listen 0.0.0.0:5678 my_script.py` or `python -m debugpy --listen 5678 my_script.py` but nothing happen (I put break points from the vscode)

**Comment by int19h** [comment]
I believe these are mappings of local ports to remote access. In your scenario, since the entirety of VSCode sans its UI is running on the remote machine, the connection between VSCode and debugpy is local, so it shouldn't be needed (although it also shouldn't hurt anything).

For the same reason, you should also be able to use `--listen 5678` (which is the same as `--listen localhost:5689`) instead of explicit `0.0.0.0`. I wouldn't expect this to make any difference here, but it might be worth checking just in case.

That aside, if I understand correctly, the script does in fact run to completion, but the problem is that you're not hitting any breakpoints? i.e. it still prints whatever output you'd expect and exits correctly? If so, this might have something to do with the location of that file that you're trying to debug remotely getting counted as "not my code" for the purposes of `"justMyCode": true` - try setting it to false and see if that helps.

**Comment by int19h** [comment]
By the way, if you don't mind me asking - since you're manually starting your script via `python -m debugpy ...`, why not use a launch configuration rather than attach? Then you won't have to deal with ports etc at all, it should just work.

**Comment by nicolalandro** [comment]
I'm tring also without the attach config:
```
{
    // Usare IntelliSense per informazioni sui possibili attributi.
    // Al passaggio del mouse vengono visualizzate le descrizioni degli attributi esistenti.
    // Per altre informazioni, visitare: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: File corrente",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "justMyCode": true
        }
    ]
}
```
To show you better the problem this is a video of three cases that have the same results.
![show bug](https://github.com/nicolalandro/yolov5_streamlit/releases/download/0.1/bug_debug.gif)

**Comment by fabioz** [comment]
Can you provide the logs for this?

Also, have you tried without `pathMapping`? (it's possible that the `pathMapping` makes the debugger do a wrong translation of paths in this case)

**Comment by fabioz** [comment]
As a note, you can use environment variables to get the logging in this case.

It's something like:

```
PTVSD_LOG_DIR=/tmp/logs
PYDEVD_DEBUG=True
PYDEVD_DEBUG_FILE=/tmp/logs/pydevd.log
```

p.s.: Ensure that `/tmp/logs` directory exists.

**Comment by nicolalandro** [comment]
I try to run vscode with the enviroment variables that you show, but I does not create nothing:
```
mkdir /tmp/logs/
PTVSD_LOG_DIR=/tmp/logs PYDEVD_DEBUG=True PYDEVD_DEBUG_FILE=/tmp/logs/pydevd.log code
```
But the file `/tmp/logs/pydevd.log ` remain empty, how can I get the vscode logs to share?

**Comment by fabioz** [comment]
In the attach you need to set in the shell with:

```
export PTVSD_LOG_DIR=/tmp/logs
export PYDEVD_DEBUG=True
export PYDEVD_DEBUG_FILE=/tmp/logs/pydevd.log
```

Note that you need to set this in the same shell where you make the run.

**Comment by nicolalandro** [comment]
So you mean that I:
* open vscode into ssh session
* Use the .vscode configuration for attach (not launch configuration)
* open a terminal(that is remote) and run:
```
mkdir /tmp/logs/
export PTVSD_LOG_DIR=/tmp/logs
export PYDEVD_DEBUG=True
export PYDEVD_DEBUG_FILE=/tmp/logs/pydevd.log

python3.7 -m debugpy --listen 5678 my_script.py
```
Also in that way the file `/tmp/logs/pydevd.log` is not created

**Comment by int19h** [comment]
Are there any other logs in `/tmp/logs`? The fact that you're able to attach to it at least, even if the breakpoints are not hit, indicates that debugpy was running long enough that it should be able to produce at least one log file.

**Comment by tt0059** [comment]
I have same problem. I cannot remote debug. The debug bar appears two second. Then it disappears. There is some thing on our GPU server,  it cannot connect to outside network.

**Comment by STRUGGLE1999** [comment]
I have problems in remote debug Python through SSH. When I clicked "Run and Debug", it doesn't appear information, and it lets me enter the debugging host:port, but I have no idea which host and port should I enter, because I am trying to debug file on VS Code through cloud server.
Please help me!

![image](https://user-images.githubusercontent.com/66925708/184144870-23b0aafe-eb7e-49ea-8a55-6e54f0473fe1.png)
