### ISSUE TITLE
Timed out waiting for debuggee to spawn

### ISSUE THREAD

**Issue by AnandVishnu** [microsoft/debugpy#953]
Before creating a new issue, please check the [FAQ](https://github.com/microsoft/debugpy/wiki/FAQ) to see if your question is answered there.

## Environment data

- debugpy version: 1.6
- OS and version: Windows 10 with Remote SSH into Red Hat Enterprise Linux Server(version 7.9)
- Python version (& distribution if applicable, e.g. Anaconda): 3.9.12 (miniconda)
- Using VS Code or Visual Studio: 2022.6.1

## Actual behavior

Debugging any python script.
This was working fine till a month ago. Now this has stopped working. 

![image](https://user-images.githubusercontent.com/3669875/172805281-330d5cec-29e6-4199-b33c-fd3341be2bcd.png)

Debugging Configuration

 {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "justMyCode": false,
            "env": {
                "LANG": "en_US"
            }
  }

Log(WINDOW)
[2022-06-08 14:25:00.119] [renderer1] [error] read ECONNRESET: Error: read ECONNRESET
	at TCP.onStreamRead (node:internal/stream_base_commons:220:20)

One thing that I have noticed is debugpy is trying to open a socket on 127.0.0.1 and on a certain port (as can be seen in the image attached. I had added logs in debugpy to print this out). Accoriding to the documentation T_o be able to attach from another machine, make sure that the adapter is listening on a public interface - using 0.0.0.0 will make it listen on all available interfaces_ . Could this be an issue ?

I had earlier raised the same issue with Python 3.6 which was rejected. https://github.com/microsoft/debugpy/issues/930

## Expected  behavior

Should be able to debug when I click debug Python: Current Script

## Steps to reproduce:
1. to install new Python Extension and try debugging on remote machine.
Also if this issue in not reproducible then please let me know what logs do I need to share

**Comment by int19h** [comment]
The matter of ports pertains to `"request": "attach"` and remoting debugpy over TCP. Since you're remoting VSCode over SSH, and doing a `"launch"`, things ought to just work.

Is there any output in the terminal where the launch was attempted? Logs (obtained by setting `"logToFile": true` - they'll be in the `.../ms-python.python...` directory) would also be very helpful.

**Comment by AnandVishnu** [comment]
Thanks for your reply. Here are the logs which were generated after I added `"logToFile": true` to launch configuration.


[logs.zip](https://github.com/microsoft/debugpy/files/8870977/logs.zip)

```
E+00021.222: /handling #2 request "launch" from Client[1]/
             Traceback (most recent call last):
               File "/home/AnandVishnu/.vscode-server/extensions/ms-python.python-2022.0.1814523869/pythonFiles/lib/python/debugpy/adapter/../../debugpy/common/messaging.py", line 1062, in __init__
                 raise self
             debugpy.common.messaging.MessageHandlingError: Timed out waiting for debuggee to spawn
             
             Stack where logged:
               File "/home/AnandVishnu/.conda/envs/test_py39/lib/python3.9/threading.py", line 930, in _bootstrap
                 self._bootstrap_inner()
               File "/home/AnandVishnu/.conda/envs/test_py39/lib/python3.9/threading.py", line 973, in _bootstrap_inner
                 self.run()
               File "/home/AnandVishnu/.conda/envs/test_py39/lib/python3.9/threading.py", line 910, in run
                 self._target(*self._args, **self._kwargs)
               File "/home/AnandVishnu/.vscode-server/extensions/ms-python.python-2022.0.1814523869/pythonFiles/lib/python/debugpy/adapter/../../debugpy/common/messaging.py", line 1510, in _run_handlers
                 handler()
               File "/home/AnandVishnu/.vscode-server/extensions/ms-python.python-2022.0.1814523869/pythonFiles/lib/python/debugpy/adapter/../../debugpy/common/messaging.py", line 747, in _handle
                 result = handler(self)
               File "/home/AnandVishnu/.vscode-server/extensions/ms-python.python-2022.0.1814523869/pythonFiles/lib/python/debugpy/adapter/../../debugpy/adapter/components.py", line 95, in lock_and_handle
                 return f(self, message)
               File "/home/AnandVishnu/.vscode-server/extensions/ms-python.python-2022.0.1814523869/pythonFiles/lib/python/debugpy/adapter/../../debugpy/adapter/clients.py", line 199, in handle
                 f(self, request)
               File "/home/AnandVishnu/.vscode-server/extensions/ms-python.python-2022.0.1814523869/pythonFiles/lib/python/debugpy/adapter/../../debugpy/adapter/clients.py", line 391, in launch_request
                 launchers.spawn_debuggee(
               File "/home/AnandVishnu/.vscode-server/extensions/ms-python.python-2022.0.1814523869/pythonFiles/lib/python/debugpy/adapter/../../debugpy/adapter/launchers.py", line 192, in spawn_debuggee
                 raise start_request.cant_handle("Timed out waiting for debuggee to spawn")
               File "/home/AnandVishnu/.vscode-server/extensions/ms-python.python-2022.0.1814523869/pythonFiles/lib/python/debugpy/adapter/../../debugpy/common/messaging.py", line 560, in cant_handle
                 return self.error(MessageHandlingError, *args, **kwargs)
               File "/home/AnandVishnu/.vscode-server/extensions/ms-python.python-2022.0.1814523869/pythonFiles/lib/python/debugpy/adapter/../../debugpy/common/messaging.py", line 546, in error
                 exc = exc_type(reason, self, silent)  # will log it
               File "/home/AnandVishnu/.vscode-server/extensions/ms-python.python-2022.0.1814523869/pythonFiles/lib/python/debugpy/adapter/../../debugpy/common/messaging.py", line 1064, in __init__
                 log.swallow_exception()
               File "/home/AnandVishnu/.vscode-server/extensions/ms-python.python-2022.0.1814523869/pythonFiles/lib/python/debugpy/adapter/../../debugpy/common/log.py", line 218, in swallow_exception
                 _exception(format_string, *args, **kwargs)
```

**Comment by int19h** [comment]
The pydevd log only has this line:
```
Using Cython speedups
```
Which seems to indicate that it crashed while trying to load the corresponding .pyd files. I wonder if there's something unusual about the conda-built Python on RHEL that causes ABI incompatibility for binary modules?

If that is indeed the problem, you can work around it by disabling those Cython speedups; set `PYDEVD_USE_CYTHON=false` in your remote environment for that (`"env"` in launch.json should also do the trick).

**Comment by int19h** [comment]
https://github.com/microsoft/debugpy/issues/772 might be related

**Comment by AnandVishnu** [comment]
This still does not work. I first tried with `"PYDEVD_USE_CYTHON": "false"` then as suggested in 772, I also tried setting  both `"PYDEVD_USE_CYTHON": "0", "PYDEVD_LOAD_NATIVE_LIB": "0"`. 

I have attached logs with the new settings? Anything else I should look on ?
[logs.zip](https://github.com/microsoft/debugpy/files/8877397/logs.zip)

**Comment by int19h** [comment]
Hm, so it didn't produce `debugpy.pydevd*.log` at all when running with those environment variable set?

**Comment by AnandVishnu** [comment]
Yes. correct. Setting those variables only produce following logs

1. `debugpy.launcher-*.log`
2. `debugpy.adapter-*.log`
3.  `debugger.*log`

Please let me know if I can switch on any other logging or manually put more logs in the code to find out what is causing the timeout.

**Comment by int19h** [comment]
@fabioz, do you have any suggestions? What could possibly cause a difference in log generation like that between pydevd with and without native code? The only thought I have is that, if the log is created on demand, the log entry about using native code just happens to be the only one logged before it crashes, so without it, the file isn't there at all. But what could possibly be a cause of such an early crash, if native is not in the picture?

**Comment by AnandVishnu** [comment]
So instead of launching the debugger from VSCode.. how could I launch the debugpy manually so that it hits the break point above ?

**Comment by int19h** [comment]
You can try using "attach" mode:

https://github.com/microsoft/debugpy/wiki/Command-Line-Reference

Since you're using VS SSH remoting already, it would be a localhost attach, so you only need to specify the port, and no port mapping should be necessary.

**Comment by fabioz** [comment]
@AnandVishnu do you still have this error?

@int19h
> What could possibly cause a difference in log generation like that between pydevd with and without native code?

This usually indicates a problem in the Python installation or user code (without native code in place Python shouldn't crash in general -- to be fair, even with native code it is very rare to get a debugger crash and that'd usually be due to some system incompatibility).

**Comment by int19h** [comment]
Please re-open if the issue still occurs.

**Comment by fengxijia** [comment]
I got the same problem here. Using SSH to connect a remote server, and VS Code shows timed out for debugged to spawn. This warning didn't show up every time but indeed showed a lot.

**Comment by thinthazin96** [comment]
I had same issue and just solved it by adding **Attach using Process ID** in launch.json. [https://code.visualstudio.com/docs/python/debugging](url)

**Comment by fengxijia** [comment]
> I had same issue and just solved it by adding **Attach using Process ID** in launch.json. https://code.visualstudio.com/docs/python/debugging

I tried but still got the same issue :( I wondered if it was the network connection between my local computer and the remote server.

**Comment by basilevh** [comment]
Is there a way to simply increase the timeout waiting value?

**Comment by int19h** [comment]
Indeed there is - you can set `DEBUGPY_PROCESS_SPAWN_TIMEOUT` environment variable to the desired value, in seconds (default is 15s).

**Comment by CanyonWind** [comment]
Setting `DEBUGPY_PROCESS_SPAWN_TIMEOUT ` seems not to help. Any other suggestions? thanks

**Comment by shenmishajing** [comment]
> Indeed there is - you can set `DEBUGPY_PROCESS_SPAWN_TIMEOUT` environment variable to the desired value, in seconds (default is 15s).

Hi, @int19h, it doesn't seem to change anything when i set the env var in launch.json. Am I setting it in the wrong place? I also try to set it in the terminal as `export DEBUGPY_PROCESS_SPAWN_TIMEOUT=6000`, but it still doesn't work. How can I set it correctly?

**Comment by shenmishajing** [comment]
> It is also not working for me. It seems like VSCode is simply not waiting long enough.
> 
> Edit: found the solution, which is to add `export DEBUGPY_PROCESS_SPAWN_TIMEOUT=1200` to your `~/.profile`

It works! Thanks for your reply very much!

**Comment by doubleZ0108** [comment]
My situation is that I use my local vscode to connect to the server via SSH. My project is large which takes time to start. When debugging inside vscode, I also got such an error. And I tried nearly every possible solution, and it works sometimes finally. (when restarting the debug 5 times, it got 1 time for correctly debugging.). I have tried these:
1. set the env variable inside `launch.json`
```
"env": {
              "DEBUGPY_PROCESS_SPAWN_TIMEOUT": "1200000",
              "DEBUGGER_CONNECT_TIMEOUT": "1200000"
          },
```
2. set env variable inside `~/.profile`
```
export DEBUGPY_PROCESS_SPAWN_TIMEOUT=1200000
export DEBUGGER_CONNECT_TIMEOUT=1200000
```
> And make sure you can get `echo $DEBUGPY_PROCESS_SPAWN_TIMEOUT` with a really big number
3. open the vscode setting, and search for `Remote.SSH: Connect Timeout`, I set it to 180(seconds)

In consolation, I think the problem is just simple that the debugged project is big so it takes really time for the debugger to start. But the disgusting thing is that we don't know how to control that timeout exactly, **so I really hope the team of the vscode-python-debug-extension can offer a simple API that really matters.**

**Comment by doubleZ0108** [comment]
🎉🎉🎉 Hi there, I find the best practice when facing this bug during debugging.
1. change your `.vscode/launch.json` to:
    ```bash
    {
        "version": "0.2.0",
        "configurations": [
            {
                "name": "@doubleZ0108 best practice",
                "type": "python",
                "request": "attach",
                "listen": {
                    "host": "0.0.0.0",
                    "port": 5678
                },
                "pathMappings": [
                    {
                        "localRoot": "${workspaceFolder}", 
                        "remoteRoot": "."
                    }
                ]
            }
        ]
    }
    ```
2. click the green button on the left panel, and your vscode-debugger will keep waiting the server to connect...

    <img width="282" alt="image" src="https://github.com/user-attachments/assets/d014cadb-9bba-4d69-9ca0-02ebd72a5453">

3. install `debugpy` library and add these two lines in your code
    ```python
    import debugpy
    debugpy.connect(('localhost', 5678))
    ```
    > you can add them in the beginning of your main code or the first place you want to inspect.

4. just run your project in the terminal like you always run them.

Finally, you will see that your vscode begins to debug just like the original extension and you will never see the annoying `Timed out waiting for debuggee to spawn` bug.

Just Enjoy!!!

**Comment by charmzhao** [comment]
Hi, I have also met the problem you have raised. After some time of trying, I realized that the python version of the virtual environment on the server was too low, which caused the local remote debugging to report errors. Just set the python version of the virtual environment on the server to no less than 3.8.

**Comment by JohannesAck** [comment]
For WSL users:

The environment variables have to be set in the `~/.profile` of your WSL home folder.
Setting them in the `launch.json` did nothing for me.
