### ISSUE TITLE
Support exeuctable directory argument

### ISSUE THREAD

**Issue by thejcannon** [microsoft/debugpy#958]
Since Python 2.6, you can `python -m foo` if `foo` is a directory with `__main__.py`. The Python interpreter runs `__main__.py`.

Trying this with `debugpy ... foo` I get `Not a file: 'foo'`, which leads me to believe this feature isn't yet supported.

**Comment by int19h** [comment]
We use `runpy` to run things, and it does support directories, so this should work. Can you provide more details: the complete command line, in particular, and what your directory structure looks like.

**Comment by thejcannon** [comment]
Well now I can't reproduce! Error must've been between keyboard and chair :sweat_smile:
