### ISSUE TITLE
Debugger error

### ISSUE THREAD

**Issue by ronak1009** [microsoft/debugpy#965]
Hi VSCode team,

With the latest update on Windows 10 of VSCode, I am facing a wierd issue. The python debugger does not work with shortcut of F5 to connect to debugger.  I get Exception has occurred: FileNotFoundError and debugger stops at line 647 of python39/Lib/ntpath.py

The debugger works fine when using the debug button in the right side tab bar.

Thanks,
Ronak
ronak1009@gmail.com

![image](https://user-images.githubusercontent.com/12443143/175974097-6f0c03ee-3b82-4f26-abb1-d886780a59a8.png)

**Comment by ronak1009** [comment]
@fabioz I got your point. But With `Raised Exceptions` set with `justMyCode: false`. If I use the Debug & Run on UI, I don't the raised exceptions as shown to the attached image. But if I debug using `F5`, the code hits. So not sure, why the behaviors are different.

**Comment by fabioz** [comment]
The difference is that when you use the shortcut for debug and run you don't have `justMyCode: false` set (unless you created a launch configuration with the proper `purpose`: https://code.visualstudio.com/docs/python/debugging#_purpose).
