### ISSUE TITLE
Difficulty debugging Rust's tokio spawned-thread

### ISSUE THREAD

**Issue by thejcannon** [microsoft/debugpy#968]
## Environment data

- debugpy version: 1.6.0
- OS and version: Ubuntu 20
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.8
- Using VS Code or Visual Studio: VS Code (client) debugpy CLI for server

Also, this has many moving parts, this may not be debugpy, but starting here.

I'm working on a Python application (https://www.pantsbuild.org/) which calls into a Rust native module, which uses [tokio](https://tokio.rs/) and [PyO3](https://github.com/PyO3/PyO3).

## Actual behavior

Breakpoints aren't hit unless I specifically use `debugpy.debug_this_thread()` _every time_ I FFI from Rust into Python in the called Python function.

## Expected  behavior

Breakpoints are hit if I use `debugpy.debug_this_thread()` in each thread.

## Steps to reproduce:
(Sorry for not having a minimally reproducible example. if you really want I can set you up with a branch of Pants that demonstrates easily)

1. Python calls into Rust-implemented module (using PyO3)
2. that module installs itself as a bridge for async code, with the implementation using tokio threads
3. [on_thread_start](https://docs.rs/tokio/latest/tokio/runtime/struct.Builder.html#method.on_thread_start) call `debug_this_thread`
```
on_thread_start(|| {
  Python::with_gil(|py| {
    let _ = py.eval("__import__('debugpy').debug_this_thread()", None, None);
  } )
});
```
(I've verified this call is on the thread executing the async code with the breakpoint and doesn't error)
5. Launch the python app using `debugpy --wait-for-client ...`
6. attach VS Code client, and app runs to completion without stopping at breakpoints

If I use `debugpy.debug_this_thread()` in the function the Rust module FFIs into in Python it works. However it calls that function hundreds of times as tasks are added/removed. Ideally calling `debug_this_thread` is a one-time cost.

**Comment by thejcannon** [comment]
(Work is being done on [this PR](https://github.com/pantsbuild/pants/pull/15951))

**Comment by thejcannon** [comment]
Ah and even more interesting, if I change my `py.eval` to call custom code which calls `debugpy.debug_this_thread()` I have the same issue, but I _am_ able to hit breakpoints in that exact function. So it seems whatever is being done in `debug_this_thread` is being undone at some point.

**Comment by int19h** [comment]
Python tracks tracing on the level of OS threads, so this is what `debug_this_thread()` sets. If you use async on the Rust side, it would resume execution on different worker threads, wouldn't it?

**Comment by fabioz** [comment]
Humm, can you verify if tracing isn't being unset?

i.e.: if you call `print(sys.gettrace())`, right after `debug_this_thread()` and after a new `ffi` call, what do you have as results?

**Comment by thejcannon** [comment]
Yeah thats an amazingly good idea :joy:

`on_thread_start`: `functools.partial(<built-in function trace_dispatch>, <pydevd.PyDB object at 0x7fb4545a70a0>)`
In my code: `None`

Well that explains it doesn't it :smile:

**Comment by thejcannon** [comment]
Was juuuuuuuuust doing that :joy: 

Yeah the engine spawns about 80 threads, and the one I'm trying to debug is in the list of dumped thread IDs (using `threading.get_ident()`)

**Comment by thejcannon** [comment]
My next thought is to see if I can't patch sys.settrace on_thread_start and log caller(s) to see if it's being called and overwritten.

Other than that I got nothin

**Comment by thejcannon** [comment]
`on_thread_start`
```
          let _ = py.eval("__import__('debugpy').trace_this_thread(True)", None, None);
          let x = py.run(
            r#"
import sys
import threading
sys.settrace = lambda *args,**kwargs: sys.exit(44)
threading.settrace = lambda *args,**kwargs: sys.exit(44)
"#,
None,
None
);
```
and in my code: `logger.error(sys.settrace)` gives me `[ERROR] <function <lambda> at 0x7feeedd55310>`

so no one seems to be calling the Python function to settrace

**Comment by thejcannon** [comment]
Now that's interesting.... (and thank so much for y'all's attention and time <3)

The log contains `AssertionError: Trying to set tracing to the same thread again?` but not for the thread I'm trying to debug. So thats slightly concerning. (Although, if we were just setting `debugpy.debug_this_thread()` I assume thats idempotent). So concerning, but maybe a red herring. Using `traceback.print_stack` and printing it to a separate file gives me about what I expect:
```
  File "<string>", line 23, in <module>
  File "<string>", line 15, in __init__
```
I also am sure to wipe the log dir each time. This is maybe relevant: "Thread identifiers may be recycled when a thread exits and another thread is created." from [the docs](https://docs.python.org/3/library/threading.html#threading.get_ident). Using `get_native_id` I _don't_ see the assertion, so I'm chalking it up to red herring.

Back on topic:

I see that in my thread-to-debug, _which has an empty log file_, `gettrace` is still `None`. So that checks out with the above. I also tried `flush`ing the stream and using `print(..., file=self.stream)` just to be sure. No dice.

Can you elaborate on "it's even possible that tokio threads are creating some async threads in the C++ level which makes the tracing misbehave"?

**Comment by fabioz** [comment]
I'm not that familiar with `tokio threads` nor `PyO3` to really know how they work regarding python tracing/threading.

All I can say is that from the behavior what appears to be happening is that someone is removing the tracing which is required for the debugger to work... it'd be nice if someone who is familiar with those could chime in.

**Comment by davidhewitt** [comment]
I'm not aware of anything which PyO3 is doing which jumps to mind.

So, a couple of thoughts to throw out there based on the observation that the trace function is being removed:
- Looks like from the CPython source that the functions set via `sys.settrace` are automatically unset if an exception is raised during tracing:
  https://github.com/python/cpython/blob/544531de23d69f5b23883794fc7bb23a958a0fcb/Python/sysmodule.c#L984
  Is it possible that the trace function is erroring out and so getting cleared?
- Trace hook is attached to the Python thread state - could something be replacing the Python thread state associated with the OS thread? PyO3 doesn't do anything weird here as far as I am aware (just calls the Python C API), does your tokio integration do anything special or just uses PyO3 APIs?

**Comment by thejcannon** [comment]
CC @stuhood who knows the pants engine better than I

The first bullet could easily be tested by setting a noop trace and seeing if it survives to the FFI call. My money is on no.

The second point is something to explore 👀

(Thanks again!)

**Comment by thejcannon** [comment]
One other interesting data point is I added to the Py FFI function being called to sebug_this_thread if gettrace is None and log. And it seemed _every_ time is was called it got set and logged

**Comment by thejcannon** [comment]
Actually I'm starting to lean towards PyO3-side. The tokio threads are started via `Python::with_gil` which seems to me calls `PyGILState_Ensure` on construction (to ensure there's a thread-state object made known to Python for the run), but then calls `PyGILState_Release` on drop which IIUC will destroy the thread-state object (therefore undoing our tracing).

Later when we're calling our async code we use `Python::with_gil` again, which does the same, but in this case now makes a new threadstate.

**Comment by thejcannon** [comment]
I'm like 95% sure this the issue. I'll close and open an issue for PyO3 for more guidance. Thanks again <3

**Comment by davidhewitt** [comment]
Oh thanks, that's very interesting - I knew that `PyGILState_Ensure` will create a Python thread state of needed, though I confess that's new to me that `PyGILState_Release` would correspondingly delete (even if in hindsight should be obvious).

Yes, let's carry on the discussion on the PyO3 issue.
