### ISSUE TITLE
Variables/statements with "None" value are not printed in the debug console

### ISSUE THREAD

**Issue by ssavary** [microsoft/debugpy#979]
Issue Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

Expected: "None"
Actual: nothing gets printed

## Steps to reproduce:

1. Add breakpoint in code
2. Break on breakpoint.
3. Assign None to a variable (existing or new variable), e.g. A = None
4. Write A in the debug console to display its value. Its value, None, is not displayed.

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.10
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Conda
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

linting
• flake8Enabled: true

```

</p>
</details>

Extension version: 2022.10.0
VS Code version: Code 1.69.0 (92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9, 2022-07-07T05:28:41.511Z)
OS version: Darwin x64 21.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|32.00GB (1.57GB free)|
|Process Argv|--crash-reporter-id 2a273040-cc5d-49bc-b505-46f4293dc6a3|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by int19h** [comment]
This behavior is intentional - it's the same as the standard Python REPL. I believe the point is to avoid printing `None` every time you invoke a function.
