### ISSUE TITLE
Python VS Code Debugger Exiting Immediately in Docker Container

### ISSUE THREAD

**Issue by aaharr** [microsoft/debugpy#980]
When I click the run/debug button on previously working launch configs, the debugger starts and then immediately disappears from the call stack. This only happens while running in a docker container, and only started yesterday.

Behavior is similar to https://github.com/microsoft/vscode-python/issues/18436
but I am not using Conda. Note that `conda info --json` does appear in output, but neither the container nor host system have Conda installed.

The logs from the debugger do show a return value of 1, but no explanation.

Working assumption is that I introduced a permissions issue creating a new git branch and rebuilding the container. Behavior is similar to existing Conda issues, but I am not using Conda. 

## Environment data

- debugpy version: 1.5.1
- Python Extension version: v2022.10.0
- OS and version: 
Linux container (Debian Version 11 bullseye)
WSLg - Ubuntu 20.04 (Docker Desktop running via WSL)
Windows11
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.15
- Using VS Code or Visual Studio: VS Code

## Actual behavior

Debugger exits before hitting breakpoint or executing python.
No error output to console.

## Expected  behavior

Debugger hits breakpoint and sends output to debug console and/or terminal.
Debug-level error output goes to terminal or Python output.

## Steps to reproduce:
Build a python linux container.
Use the docker extension to attach VS Code.
Add any python module and run successfully from terminal or without launch config.
Run with the debugger and known working launch config.
Debugger exits immediately without error output.

## Things I've tried:
- Restarting PC (this sometimes resolves container issues)
- Removing and rebuilding container
- Uninstalling and reinstalling Python Extension
- Deleting .vscode config files
- Rebuilding container as user or sudo
- Pulling different branches of container source as user or sudo
- `chown -R root:root <dir>` (Container items begin as 1000:1000)
- Rolling back VS Code python to version v2021.12.1559732655
- Creating a fresh venv, changing python interpreter via command palette

Log output using `logToFile: true`
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "logToFile": true,
            "console": "integratedTerminal",
            "justMyCode": true
        },
```
0 Starting Session:
{
    "name": "Python: Current File",
    "type": "python",
    "request": "launch",
    "program": "scratch_test.py",
    "logToFile": true,
    "console": "integratedTerminal",
    "justMyCode": true,
    "__configurationTarget": 5,
    "python": "/usr/local/bin/python",
    "debugAdapterPython": "/usr/local/bin/python",
    "debugLauncherPython": "/usr/local/bin/python",
    "cwd": "/core",
    "envFile": "/core/.env",
    "env": {
        "PYTHONIOENCODING": "UTF-8",
        "PYTHONUNBUFFERED": "1"
    },
    "stopOnEntry": false,
    "showReturnValue": true,
    "internalConsoleOptions": "neverOpen",
    "debugOptions": [
        "ShowReturnValue"
    ],
    "workspaceFolder": "/core"
}
16 Client --> Adapter:
{
    "command": "initialize",
    "arguments": {
        "clientID": "vscode",
        "clientName": "Visual Studio Code",
        "adapterID": "python",
        "pathFormat": "path",
        "linesStartAt1": true,
        "columnsStartAt1": true,
        "supportsVariableType": true,
        "supportsVariablePaging": true,
        "supportsRunInTerminalRequest": true,
        "locale": "en-us",
        "supportsProgressReporting": true,
        "supportsInvalidatedEvent": true,
        "supportsMemoryReferences": true
    },
    "type": "request",
    "seq": 1
}
39 Exit:
Exit-Code: 1
Signal: none
```

Python Panel Output
```
Experiment 'pythonaa' is active
Experiment 'pythonTensorboardExperiment' is active
Experiment 'pythonSurveyNotification' is active
Experiment 'PythonPyTorchProfiler' is active
LSP Notebooks experiment is disabled -- Pylance disabled or not installed
> conda info --json
LSP Notebooks experiment is disabled -- not in treatment group
> /usr/local/bin/python ~/.vscode-server/extensions/ms-python.python-2022.10.0/pythonFiles/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2022.10.0/pythonFiles/interpreterInfo.py
Python interpreter path: /usr/local/bin/python
```

Note: I suspect we could diagnose this more easily if debug-level output were coming from debugpy or Python Extension to that log, but there is no "debug" level option in my user settings, only "trace" which doesn't seem to change that output.

Thanks! Please feel free to move this issue however seems appropriate (:

**Comment by nurkkala** [comment]
I have seen what sounds like the identical problem trying to debug in a Docker container on AWS. I've found that pre-release `v2022.11.11891004` appears to work okay. Neither the current release nor any other pre-releases that I've tried are working.

**Comment by ei-eiron** [comment]
Thanks @nurkkala. This is working for me.👍

**Comment by int19h** [comment]
Looks like this is something that was fixed on vscode-python side, since debugpy version didn't change on remote.

**Comment by lrhazi** [comment]
I seem to have the same issue, on MacOS and on Windows!
I tried reinstalling. I made sure I have the latest version, even tried the insiders version.. to no avail!
also updated docker desktop to the latest version.

**Comment by karthiknadig** [comment]
if you are using python 3.6 debugger will not work. The recent version of debugpy dropped support for it. If you need to work with python 3.6 please pin the extension to version 2022.8.*.

**Comment by lrhazi** [comment]
> 2022.8.

Thanks a lot. How do I force an old version to be installed in my container?
I tired adding 
```
"extensions": [
		"ms-python.python@2022.8.1"
	],
```
But it seems to be ignored!

**Comment by lrhazi** [comment]
> if you are using python 3.6 debugger will not work. The recent version of debugpy dropped support for it. If you need to work with python 3.6 please pin the extension to version 2022.8.*.

Thanks a lot! I moved to python 3.9 and it works fine now!!

**Comment by zzk0** [comment]
> if you are using python 3.6 debugger will not work. The recent version of debugpy dropped support for it. If you need to work with python 3.6 please pin the extension to version 2022.8.*.

Thanks for your reply. It would be user-friendly if there is hint from python output panel
