### ISSUE TITLE
add support for thread names for non python threads 

### ISSUE THREAD

**Issue by gedalia** [microsoft/debugpy#993]
Currently threads that are created with pyqt eg:

class ReadDofAngles(QtCore.QThread):

require debug_this_thread() to be called:
def run(self):
        vscode_debugger.debug_this_thread()
It seems that for the build-in threading.thread the name attribute is picked up by the debugger. Maybe an optional name argument to debug_this_thread could allow named QThreads as well?

**Comment by fabioz** [comment]
@gedalia the debugger uses the name gotten from:  `threading.current_thread().name`.

In the case of non-python threads, Python creates a dummy thread... so, if you want a different name you can get the dummy thread and change the name to the name you'd like.

i.e.: `threading.current_thread().name = "MyQtThread"`

Given that, I'm not sure we should do any special treatment in this case...

**Comment by gedalia** [comment]
Thanks that worked well.
