### ISSUE TITLE
VSCode Python debugger stopped launching

### ISSUE THREAD

**Issue by xxc-zsz** [microsoft/debugpy#994]
I'm using VSCode v1.69.0. My OS is MacOS v10.15.7 (Catalina).

I have a python code that I'm usually debugging with VSCode Python debugger (using the launch.json file).

For no apparent reason the debugger recently stopped working, i.e. when I click on "Run Debug", the debug icons (stop, resume, step over etc.) show up for 1 second, then disappear and nothing else happens. There is no error message in the terminal or anything (no command is launched apparently).

I tried to uninstall VSCode and reinstall it => no success. I deleted the Python extension in /userprofile/.vscode/extensions and then reinstalled it (both the current v2022.10.1 and pre-release v2022.11.12011103) => no success.

The python program runs properly on another IDE.

Any idea?

Thanks a lot!

**Comment by karthiknadig** [comment]
@xxc-zsz If you are using python 3.6 then the latest version of the debugger dropped support for it. Please pin the extension to 2022.08.* if you are using python 3.6.

**Comment by xxc-zsz** [comment]
@karthiknadig  It worked, thank you very much for your reply.
